### ISSUE TITLE
[Source Request] [vietnamese] www.nettruyen.com/

### ISSUE THREAD

**Issue by Sokiro** [inorichi/tachiyomi-extensions#1002]
Please add Extensions nettruyen(www.nettruyen.com/) for sources Tiếng Việt, the other Extensions are die and i can't read Detective Conan . Thank you very much 👍 tachiyomi very good

**Comment by as280093** [comment]
Rename title @CarlosEsco @arkon 
**[Source Request] [vietnamese] www.nettruyen.com/**

**Comment by vannessqn** [comment]
Yes pleaseee..

**Comment by namnguyendeveloper** [comment]
They are stealing work from other sites.

**Comment by vannessqn** [comment]
With tachiyomi we won't give them any money bro, beside that if I've ever using their website, ublock blocked all the ads anyway, no hard feelings

**Comment by namnguyendeveloper** [comment]
DIY

**Comment by vannessqn** [comment]
What's up with you kid? Somebody stole your candy?
