### ISSUE TITLE
E-hentai No coverart appear in Catalogues

### ISSUE THREAD

**Issue by p3nguin224** [inorichi/tachiyomi-extensions#1003]
Tachiyomi ver 0.8.2
Cover arts from this extensions are not appearing as in my screenshot.
I cleares Cookies, Chapter Caches, databases from app, Refresh meta. And I also cleared caches from Android setting. I tried to reinstall the app. But it's not working.
screenshot : https://ibb.co/Yhp38KR

**Comment by justinkruit** [comment]
Got the same here, for a few days now. The image loads when you open the comic, but not when you browse through them.
