### ISSUE TITLE
Tumangaonline [tmofans.com] problems trying to get the catalog

### ISSUE THREAD

**Issue by Heavyarms04** [inorichi/tachiyomi-extensions#1005]
For about a week Tumangaonline does not allow access or download its content, I have cleaned data from advanced options, I have also connected to different networks and does not work and if I use a VPN works for maximum 3 minutes and begins to present The same problem, I must clarify that the other sources work perfectly

Desde hace aproximadamente una semana tumangaonline no permite acceder ni descargar su contenido, ya he limpiado datos desde opciones avanzadas, también me he conectado a distintas redes y no funciona y si utilizo una vpn funciona por máximo 3 minutos y empieza a presentar el mismo problema, debo aclarar que las otras fuentes funcionan perfectamente

![Screenshot_2019-04-07-06-25-12](https://user-images.githubusercontent.com/49253118/55682963-c49c6780-58ff-11e9-9f26-e46bde4bd614.png)
![Screenshot_2019-04-07-06-25-32](https://user-images.githubusercontent.com/49253118/55682965-d1b95680-58ff-11e9-9e11-400b4fe26829.png)
![Screenshot_2019-04-07-06-25-42](https://user-images.githubusercontent.com/49253118/55682981-0fb67a80-5900-11e9-875c-0d1792930564.png)

**Comment by MerradOklom** [comment]
Pusieron algún tipo de restricción en la página y te bloquean la IP al actualizar la librería de Tachiyomi en busca de nuevos capítulos.

**Comment by Heavyarms04** [comment]
He realizado la búsqueda desde otro dispositivo y en otra red wifi y me presenta el mismo problema, podrían aconsejar que hacer para resolverlo

I Have done the search from another device and another WiFi network and presents the same problem, They could give me some advice to solve it.

**Comment by MerradOklom** [comment]
No importa cómo lo hagas, el resultado será el mismo porque es una restricción que TMO puso para los que acceden a su página de forma consecutiva y muy rápida ( al menos así lo entiendo). En caso de que te bloqueen, reinicia tu módem de internet y eso lo soluciona.

**Comment by Heavyarms04** [comment]
Lo extraño es que puedo acceder a la página desde el navegador más no desde Tachiyomi

**Comment by MerradOklom** [comment]
Un comentario de la administración de TMO

![Screenshot_2019-04-09-09-01-11](https://user-images.githubusercontent.com/43864503/55798895-69f14000-5aa6-11e9-9f53-7be6f480c775.png)

**Comment by gabrielpb1** [comment]
Por lo que se ve solo afecta a quienes descarguen los mangas para luego leerlos, si solo lees lo que cachea no hay ban

**Comment by Credits125** [comment]
Yo leo y descargo sin ningún problema

**Comment by Heavyarms04** [comment]
Siempre que utilizo la opción refrescar la biblioteca me banean la ip el problema es que I no lo hago no se si ha salido algo nuevo

**Comment by MerradOklom** [comment]
Mi solución (aunque burda y no la más conveniente), es agregar X manga dos veces, por ejemplo Berserk de TMO y Berserk de MangaDex, y cuando actualizo la librería eso genera un delay/retraso que evita el bloqueo del IP.

**Comment by Heavyarms04** [comment]
Ojalá en algún momento vuelva a la normalidad

**Comment by Heavyarms04** [comment]
> Mi solución (aunque burda y no la más conveniente), es agregar X manga dos veces, por ejemplo Berserk de TMO y Berserk de MangaDex, y cuando actualizo la librería eso genera un delay/retraso que evita el bloqueo del IP.

Es cierto el problema de Tachiyomi es su gran eficiencia ya que al ser tan rápido dispara las alarmas de tu manga Online si hubiera manera de bajar esa velocidad todo regresaría a la normalidad

**Comment by edgarMejia** [comment]
Ya ellos tenían varias restricciones desde que se agregó la extensión hace unos meses, una de ellas pasaba cuando ponías a descargar una serie completa o varios capítulos a la vez, el servidor notaba que tu ip estaba haciendo demasiadas peticiones (descargas) al mismo tiempo y te baneaba porque obviamente un humano no puede moverse de forma tan rápida entre capítulos o mangas a la vez, te empezaba a devolver un 403, yo lo solucionaba desde **Configuraciones > Avanzado > Limpiar cache, Limpiar cookies y Borrar redundancia de la base de datos**, lo hacia por rutina para estar probando pero en su caso creo que solo bastaría con darle a **Limpiar cookies**.

La recomendación es leer mangas de forma que parezca que lo haces desde su web. No descargando series completas o varios capítulos a la vez, también evitando moverse entre capítulos bruscamente, así pueden evitar ser baneados por el server.

**Comment by edgarMejia** [comment]
También acabamos de agregar NineManga el cual incluye su versión en español (NineMangaEs), desde ahi pueden descargar y leer sin restricciones por ahora y alternar entre el y TMO, pueden descargar de uno y leer los últimos capítulos en el otro.
Yo ya me estoy descargando One Piece desde NineMangaEs.

**Comment by Heavyarms04** [comment]
A mi me banean solo por actualizar la biblioteca es más estoy tan baneado que hasta desde otro dispositivo no me permite, tengo que usar vpn

**Comment by edgarMejia** [comment]
@CarlosEsco please close this issue.
