### ISSUE TITLE
[Chinese] manhuagui.com

### ISSUE THREAD

**Issue by KusanagiRyu** [inorichi/tachiyomi-extensions#1006]
Source Request for ManHuaGui.com - Simplified Chinese. Reason: Other chinese source are either pay to read or no longer up to date for some titles.

**Comment by as280093** [comment]
#271 is same but its mentioned traditional Chinese with url (https://tw.manhuagui.com/)
and this one is Simplified Chinese url (https://www.manhuagui.com/)

Website language could be different but as i checked one manhua they were same on both sites, it could be that they provide both simplified and traditional manhua 
thats what i came to know by comparing the manhua sites 
if both url provide different manhua then it ok but if both provide same manhua and just website language is different then they should be merged to one and provide two language

**Comment by KusanagiRyu** [comment]
Well, since the extension for it is still not released and the existing chinese extension for those websites has problems. So I made this issue, feel free to merge both issues together.

**Comment by frgmnt** [comment]
I agree that the current existing Chinese extensions are plagued with problems. Either they do not have the content that is on a lot of sites, or I keep running into page list empty on the ones I do find. 

Not sure if I should make a separate thread to suggest this, but here are some other Chinese sites that could be an alternative:
[ManHuaTai](https://www.manhuatai.com/)
[TuHaoManHua](https://www.tohomh123.com/)

I'll be glad if any viable Chinese extension gets added.

**Comment by arkon** [comment]
> Not sure if I should make a separate thread to suggest this

Please create a new request for each.

**Comment by GanjaCubes** [comment]
I agree, and would be very happy if ManHuaGui or the others were made available as extensions! Thanks

**Comment by arkon** [comment]
Closed via #1156
