### ISSUE TITLE
Newtoki search not working. 

### ISSUE THREAD

**Issue by Reraru** [inorichi/tachiyomi-extensions#1009]
The search doesn't work for this source, I am using the latest Dev version. It didn't work before as well. I searched this > 버림 받은 황비 nothing showed up but on site when I search this series it shows up.

**Comment by DitFranXX** [comment]
Currently `NewToki` extension is only work for Manga(`.net`) contents.
Seems `버림 받은 황비` is Webtoon(`.com`) contents so it doesn't show up.

TL;DR - Currently only shows manga. no webtoons rn.

**Comment by DitFranXX** [comment]
Starting Newtoki Extension `1.2.7`. Webtoon contents are supported as new, separated catalogue `NewToki (Webtoon)`.

After update extension, you can see the new catalogue. (I think it's yet another korean raw Manhwa source)
