### ISSUE TITLE
Library and catalogs not syncing in MangaRock

### ISSUE THREAD

**Issue by Adsam112** [inorichi/tachiyomi-extensions#1011]
Tachiyomi version = 0.8.2
Manga Rock version = 1.2.10

After updating the manga rock extension my previously tracked manga would be no longer be tracked. But when i go to my library they are still there but the can't receive updates unless i re track them in the catalog which clears all read data on the manga.

**Comment by CarlosEsco** [comment]
yea the last update changed that fixed the open in browser when in the manga info.  Changed the urls which are considered the unique ids for a manga.  long story short.

you will have to re-add them from catalog.  and remove the old ones.

**Comment by pervertkirito** [comment]
You can use source migration if you don't want to lose your data
