### ISSUE TITLE
MangaDex HTTP 403 error

### ISSUE THREAD

**Issue by MistaBibi** [inorichi/tachiyomi-extensions#1012]
Seems like the MangaDex 1.2.53 extension on Tachiyomi 0.8.2 doesn't work. I'm getting HTTP error 403 when trying to access any chapter, is this a result of the intermittent captcha?

**Comment by MistaBibi** [comment]
Can you reference a relevant ticket or cite a reason for closing?

**Comment by CarlosEsco** [comment]
#871 renamed it so it was easier to fine

**Comment by MistaBibi** [comment]
Awesome, thanks.
