### ISSUE TITLE
0.8.3 Broke catalogs entirely

### ISSUE THREAD

**Issue by pitman10** [inorichi/tachiyomi-extensions#1017]
Just installed the update and now either clicking search (globally) or going into browse/latest of **any** extension immediately closes the app.

**Comment by roworit** [comment]
Same thing happens to me.

**Comment by einstein95** [comment]
Wrong place, https://github.com/inorichi/tachiyomi/issues/1973

**Comment by mitsuhama** [comment]
some extensions are not working,
kissmanga
manghakakalot
readcomicsonline
