### ISSUE TITLE
MangaDex Browse not working

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi-extensions#1019]
BUGS:
MangaDex browse returning "no results found" on v1.2.54

Edit: Issue occurs after logging in through webview. 

Tachiyomi v0.8.4 r1499

**Comment by arkon** [comment]
Also posted this in the #faq channel on Discord:

> If you're getting "No results found" when trying to browse MangaDex after logging in, set your view mode to "Detailed" on https://mangadex.org/titles
