### ISSUE TITLE
[MangaDex] Incorrect parsing of HTML entities in manga titles

### ISSUE THREAD

**Issue by null-dev** [inorichi/tachiyomi-extensions#1020]
Example, try searching/viewing this manga: https://mangadex.org/title/26052/mage-demon-queen

Notice the `&amp;` in the title.

**Comment by arkon** [comment]
Corresponding API endpoint: https://mangadex.org/api/manga/26052

It returns encoded entities:

```json
"title":"Mage &amp; Demon Queen"
```

**Comment by Ha5yA** [comment]
https://mangadex.org/title/39474/a-stepmother-s-m-rchen
Stuff like this too with things like ä

**Comment by as280093** [comment]
it's Just not **Title** happens to **Author** and other info too
https://mangadex.org/title/32367/suterare-yuusha-wa-kitakuchuu

ON MD **Author:** Naname44°
in App *Author:** Naname44&deg;

this might happen to all the data, adding HTML entities decoding system is needed
