### ISSUE TITLE
kissmanga page list is empty

### ISSUE THREAD

**Issue by Hulkmaster** [inorichi/tachiyomi-extensions#1021]
0.8.4

Kissmanga
Trying to open a manga gives "Page list is empty" error

I guess cloudflare issues is not yet fixed

**Comment by arkon** [comment]
Try clearing your cookies/cache.

**Comment by Hulkmaster** [comment]
still an error

am i the only one getting it?

**Comment by Hulkmaster** [comment]
Cleared cache and cookies from the Application

Cleared application cache from android settings

first 503 error
then page list is empty error

**Comment by HoLLy-HaCKeR** [comment]
I'm getting a DuktapeException, not sure if that's related. Been getting it for about 2 weeks now. I'd try to debug this myself but I have no experience with android java apps.

**Comment by Fokkusuteru** [comment]
Getting same issue. First 503 error then the page list empty error on kissmanga. Latest stable version.

**Comment by leanne9362** [comment]
Getting page list is empty on webcomic and clear cookie but still having it also mangago gets 503 error

**Comment by leanne9362** [comment]
How do I fix it

**Comment by CarlosEsco** [comment]
@leanne9362  if there was a fix this issue wouldnt be open..

**Comment by HoLLy-HaCKeR** [comment]
@leanne9362 Make sure you have updated to the latest version in the Extensions tab, otherwise just wait for an update.

**Comment by maz0r** [comment]
Seems to be related to a reCaptcha widget on the site but the web view built into Tachiyomi is not compatible so manually entering the captcha in the web view every few chapters isn't possible.
