### ISSUE TITLE
ReadComicOnline Page List Is Empty

### ISSUE THREAD

**Issue by Bombonfun** [inorichi/tachiyomi-extensions#1023]
So, I can finally open the catalogue and browse along it, but after clicking on a comic and pressing a chapter, it just closes and says "Page List is Empty"

Tachiyomi Dev 0.8.4-1499

**Comment by neufel** [comment]
Hi,
Have you tried resolving a new captcha for the source?
Click on the info tab of the series, click on the three dots on the top right, and then open in web view. Try to open a book from this page, and you will probably prompted with a new captcha to solve.
Solving it should resolve the page list is empty problem.

If that is the problem, you can expect to resolve a new captcha every few issues.

**Comment by Bombonfun** [comment]
@neufel yeah no, I've done that multiple times, but i use VPNs a lot, so, it resets my ip and its cookies, so it's a brand new process all over again. I just made a new issue where i requested a similar source without captchas, so let's see where that gets me.

Conversely, i bulk read and download, usually on the bus, so entering captchas for 15 minutes every 2-3 issues gets a little annoying. 

I know i sound like a choosing beggar, but I'm so close to actually starting to enjoy bus ride, stress-free.

**Comment by neufel** [comment]
I totally get it, that's also how I use the source, and yeah the number of captchas (and their difficulty) has become grating.

But yeah the source "works" for me so I can't help you much more. Hope someone will be able to help !
