### ISSUE TITLE
Mangasee - timeout error

### ISSUE THREAD

**Issue by leoteesh** [inorichi/tachiyomi-extensions#1031]
Hi i am using the most recent version of tachiyomi. 0.8.4.
I am getting timeout popup messages each time I try to read a chapter from mangasee. E.g. Eden's zero
Could you please advise?

Many thanks

**Comment by Zilveari** [comment]
Having the same issue with Mangasee.  having other issues with every library except for MangaPark.  None of the others are currently working for me.

Kiss gets the Duktape error
Dex gets the Duktape error
Fox says no results found
Here says No Results Found
See says timeout.  I think the rest are in the Discord FAQ though.

**Comment by CarlosEsco** [comment]
@Zilveari  if you are getting duktape you arent on latest version of tachiyomi

**Comment by CarlosEsco** [comment]
@leoteesh  their website is down.

**Comment by leiurus906** [comment]
i'm also getting same error only on my wifi ip address when i switch to the lte network on my phone or when i use a vpn it works well, but whenever back to my wifi network without vpn i get the timeout error from mangasee, readmangatoday works tho without vpn.

**Comment by leiurus906** [comment]
the issue got fixed, today i tried the mangasee extension and it worked properly without using vpn, idk how it got fixed but thanks for the one who fixed it :) i think this issue is closed now.
