### ISSUE TITLE
[Source Request][English]Mangabat

### ISSUE THREAD

**Issue by Lavuan** [inorichi/tachiyomi-extensions#1037]
please add this one, thanks

Mangabat
https://mangabat.com/

**Comment by pervertkirito** [comment]
the site has same content with manganelo.com... heck, even the score and upload date is same

https://github.com/inorichi/tachiyomi-extensions/blob/1cd55127bb783082277bbf445272e9ee62e4a83b/src/en/manganelo/src/eu/kanade/tachiyomi/extension/en/manganelo/Manganelo.kt

**Comment by arkon** [comment]
Duplicate of #1475
