### ISSUE TITLE
LHTranslation date parsing puts it above other sources

### ISSUE THREAD

**Issue by einstein95** [inorichi/tachiyomi-extensions#1050]
https://github.com/inorichi/tachiyomi-extensions/blob/de52d6c215ac69360a1cde8ccf8031329b76e741/src/en/lhtranslation/src/eu/kanade/tachiyomi/extension/en/lhtranslation/LHTranslation.kt#L120-L157

The parsing in this function puts manga that hasn't been updated recently above manga that has (e.g. ones from Mangadex) when sorted by update time.

**Comment by DitFranXX** [comment]
It's on rawQQ, rawLH, TruyenTranhLH and [more sources](https://github.com/inorichi/tachiyomi-extensions/search?q=day%28s%29+ago&unscoped_q=day%28s%29+ago) too. IIRC.
It is cause site provide relative dates, not absolute dates.

\+ Also if it uploaded under a hour, there was bug that minutes relative dates parsed as hours. Fix PR is  #1051
