### ISSUE TITLE
mangadex failing again

### ISSUE THREAD

**Issue by c-h-u-c-k** [inorichi/tachiyomi-extensions#1053]
Syntax error: invalid return (line 1)

**Comment by bbtora** [comment]
Give more information regarding the issue. 

App version, extension version 

We can't read minds sadly.

**Comment by c-h-u-c-k** [comment]
Ext 1.2.54 latest
V. 0.8.0 for main app

**Comment by bbtora** [comment]
Update app to 0.8.4 

And if you want to enable search, login to MangaDex through "Open in webview" in any of your MangaDex title info page (same place as of "open in browser")
