### ISSUE TITLE
bug:the dmzj can't search some comic that can be found in the browser

### ISSUE THREAD

**Issue by 7sevenseven** [inorichi/tachiyomi-extensions#1059]
tachiyomi:0.8.4 
the extension of dmzj:1.0.4
When I use this extension,I can't search some manga that I can find in the browse.
![Screenshot_20190424-173138](https://user-images.githubusercontent.com/49519653/56649503-d9c31580-66b7-11e9-8095-cbd725a81754.png)

![Screenshot_20190424-173216](https://user-images.githubusercontent.com/49519653/56649506-d9c31580-66b7-11e9-8c6a-ab21e9e7ca24.png)

**Comment by arkon** [comment]
Does it work on the site?

**Comment by 7sevenseven** [comment]
> 它在网站上有效吗？

it works on the site

**Comment by fenixan** [comment]
by the way, some comics can be searched and added but can't be viewed

**Comment by 7sevenseven** [comment]
> 它在网站上有效吗？

ver1.2.5 

> Does it work on the site?

The latest version( 1.2.5 )still has this problem. Some comics can be found in the browser, but cannot be searched

**Comment by arkon** [comment]
#1692
