### ISSUE TITLE
[Source Request][English] Webtoon Factory

### ISSUE THREAD

**Issue by kbhasi** [inorichi/tachiyomi-extensions#1062]
I'm just going to leave this here for if anyone wants to create a plugin to add support for [the English version of Webtoon Factory](https://www.webtoonfactory.com/en/home/) (not to be confused with Line Webtoon, for which a plugin already exists).

The site is also available in French, however, I don't read that version for semi-obvious reasons, and to be fair, the current Line Webtoon plugin only supports the English version, not any other languages it supports, nor Naver Webtoon (Korean), from what I could tell.

**Comment by as280093** [comment]
Here the icons
[webtoonfactory.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614415/webtoonfactory.zip)

**Comment by SnakeDoc83** [comment]
@kbhasi You know only the first 3 chapters are free, right?  You have to pay to read full chapters after that.

**Comment by kbhasi** [comment]
Oh! It used to be free, but they must've changed it some time after I filed this request, due most likely to budget constraints, so **it looks like I may have to drop this request**.

The 2 series I had in mind when I filed this request, and checked the series pages for:
* [Imaginary Dave](https://www.webtoonfactory.com/en/webtoons/35-imaginary-dave-saison-1/)
* [Noah vs Nature](https://www.webtoonfactory.com/en/webtoons/31-noah-vs-nature-saison-1/)
