### ISSUE TITLE
ReadComicOnline Duktape Syntax Error

### ISSUE THREAD

**Issue by ovheurdrive** [inorichi/tachiyomi-extensions#1063]
# Versions

- tachiyomi : 0.8.2
- readcomiconline extension : 1.2.5

# Bug

When trying to load a comic or to explore the catalog, i get the following error:

```com.squareup.duktape.DuktapeException: Syntax Error: invalid return (line 1)```

**Comment by DarKCroX** [comment]
go to settings > about > tap on version
and update to latest version

**Comment by ovheurdrive** [comment]
Oh thanks, i thought i was on the latest one.
I'm closing the issue ^^
