### ISSUE TITLE
[Source Request] [Spanish]
LeoManga

### ISSUE THREAD

**Issue by Credits125** [inorichi/tachiyomi-extensions#1068]
URL:

[LeoManga](https://leomanga.xyz)

**Comment by arkon** [comment]
Not sure if the site's still the same as before, but we might be able to resurrect the old extension.

**Comment by edgarMejia** [comment]
> Not sure if the site's still the same as before, but we might be able to resurrect the old extension.

Not sure too, the site is quite similar to the previous.
I didn't update the extension when it came out because I thought I would die fast, but no.

**Comment by MerradOklom** [comment]
I think the site owner is the same than the one from https://submanga.online (both looks the same) 
But https://leomanga.xyz has an smaller catalogue and is less up-to-date with popular manga.
