### ISSUE TITLE
Wentoons are not properly coordinated

### ISSUE THREAD

**Issue by Kaushik-Paul** [inorichi/tachiyomi-extensions#1070]
Webtoons pages are not properly coordinated...
Can't read manhawa properly

**Comment by arkon** [comment]
Provide the source/title/chapter and a screenshot of the issue.

**Comment by Kaushik-Paul** [comment]
Name-close as neighbors
Source-kissmanga
Chapter -4

**Comment by arkon** [comment]
And what isn't "properly coordinated"? It looks fine to me.

**Comment by Kaushik-Paul** [comment]
The girl's face from the last page isn't properly lined up with the face
from the current page

**Comment by CarlosEsco** [comment]
Post a picture of the issue or I will close for lack of information

**Comment by Kaushik-Paul** [comment]
The girls face from the previous page is not properly lined up with the
girls face from the current page

**Comment by CarlosEsco** [comment]
No provided picture and arkon and I both seen nothing wrong
