### ISSUE TITLE
[Source Request][Spanish] Joker Fansub

### ISSUE THREAD

**Issue by MerradOklom** [inorichi/tachiyomi-extensions#1071]
Site: http://reader.jkrfb.xyz

This fansub works faster than others and they only upload to their site.

**Comment by edgarMejia** [comment]
The only problem is that in the recent list there's no cover image, only the list of the entire catalog has cover images.

**Comment by MerradOklom** [comment]
@edgarMejia maybe a workaround would be getting the covers from MAL like the Mangastream extension?

**Comment by edgarMejia** [comment]
I had not thought of it D:
I will test today and if everything goes well I will publish it tomorrow :)
Thanks.

**Comment by as280093** [comment]
for Res folder 📂 here https://github.com/as280093/TIcons/tree/master/Requested%20Extensions%20Icons/reader.jkrfb.xyz/res

**Comment by MerradOklom** [comment]
@edgarMejia thanks to you :)

**Comment by edgarMejia** [comment]
@as280093 Thanks!

**Comment by MerradOklom** [comment]
@edgarMejia I think I'll close this request in favor of EsManga and InManga (these sites scrape their content, so this one is not really necessary)

**Comment by edgarMejia** [comment]
Hi!, this extension is almost finished, I just need to add the date of the chapters.

**Comment by MerradOklom** [comment]
@edgarMejia oki, then forget what I said. (perdón, supuse que éste te causaría dolor de cabeza por eso pensé en descartarlo)

**Comment by edgarMejia** [comment]
Y sabes que al final resultó ser el más fácil, lo terminé casi todo el día siguiente que creaste este issue pero no lo he publicado aún por falta de tiempo además siempre lo de las fechas es lo que me da más problemas así que pensaba terminar este fin de semana y subir.

**Comment by Mickuchiha** [comment]
EsMangas es superior :v y no lo digo porque yo fuera el hizo el request uwur

**Comment by edgarMejia** [comment]
No he publicádo esta extensión porque desde mi último comentario la página de JnF ha estado caída, he estado revisando su fanpage para ver si dan alguna información pero nada, así que hasta no ver nada estable no publicaré la extensión, por el momento me centrare en publicar la extensión del issue #1085, sientete libre de cerrar este issue y reabrirlo en un futuro de ser necesario.

**Comment by MerradOklom** [comment]
@edgarMejia sip, también me percaté de eso. No parece que lo vayan a solucionar pronto asi que seguiré tu consejo, pero en cuanto lo hagan te informaré por aquí.
