### ISSUE TITLE
(bug) All NainManga titles are marked as read.

### ISSUE THREAD

**Issue by RapedTrap** [inorichi/tachiyomi-extensions#1076]
(CATALOGUE) SOURCE REQUESTS:
  One source per issue, create more issues if you have more websites
  Check for duplicates, use search (in issues, not the global one)
  Put the name of the site as Title, replace this text with clickable link to the site
BUGS:
  Provide tachiyomi version as well as version of source the report is about

**Comment by arkon** [comment]
Do you mean NineManga?

**Comment by SnakeDoc83** [comment]
@arkon I'd call this closeable: lack of information to work on, user is uncommunicative, doesn't seem like something that could be caused or fixed by the extension.
