### ISSUE TITLE
[Source Request][English] mangatensei.com

### ISSUE THREAD

**Issue by shaishaiNg** [inorichi/tachiyomi-extensions#1078]
Hi, if anyone can make a catalogue extension for https://mangatensei.com. Some paid webtoons are uploaded in the site. Also the site has tons of adverts that you cant really see anything anymore.

**Comment by zagrib** [comment]
I love reading https://mangatensei.com
Ads? I have no problem with them.

**Comment by Ozs000** [comment]
+

**Comment by as280093** [comment]
Here are the icons 
https://github.com/as280093/TIcons/tree/master/Requested%20Extensions%20Icons/mangatensei.com/res
