### ISSUE TITLE
Mangahere bug

### ISSUE THREAD

**Issue by ccrowles** [inorichi/tachiyomi-extensions#108]
Latest version (0.6.3-1228) gives me this error when I open any manga bookmarked from Mangahere or try to access the Mangahere catalogue.

![screenshot_20170928-025424](https://user-images.githubusercontent.com/12866474/30944605-5800469e-a3f9-11e7-9e60-1b565a0cd64c.png)

**Comment by mrskizzex** [comment]
Really... 
1. Wrong repo.
2. If you actually bothered to posting to correct repo it would be clear that it's a [known problem](https://github.com/inorichi/tachiyomi/issues)

**Comment by ccrowles** [comment]
Sorry, I was uncertain in which repo to post it... Guess I got it wrong. Really sorry again
