### ISSUE TITLE
Mangarock

### ISSUE THREAD

**Issue by ferdyfachrur** [inorichi/tachiyomi-extensions#1083]
Tachyomi : 0.8.4

Mangarock version : 1.2.10

New chapter manga wont show in the library but manga order in the latest release is still availble and when i try to refresh to get new chapter it wont show/load

**Comment by Adsam112** [comment]
Same I'm getting the same problem since this morning

**Comment by pavan3999** [comment]
same here from 2 hours ago

**Comment by reddeimon** [comment]
Me too

**Comment by reddeimon** [comment]
From my observation any manga from Mangarock that you put into library are the only manga that don't get updated. Other manga in Mangarock are updated just usual.

**Comment by arkon** [comment]
Seems like the API isn't returning the full list.

e.g. Solo Leveling, which has ch35 on the site, but only goes up to ch33 (as of writing): https://api.mangarockhd.com/query/web401/info?oid=mrs-serie-100350535

Will need to look into it further.

**Comment by arkon** [comment]
Seems like appending the `country` query param returns more chapters. I'm not entirely sure what the default value is, or if it matters which country is passed: 

https://api.mangarockhd.com/query/web401/info?oid=mrs-serie-100350535&country=

**Comment by arkon** [comment]
They both show the same thing for me now too. I assume the extension update didn't do anything for the people experiencing issues?

**Comment by Adsam112** [comment]
The extension update fixed the issue for me.

**Comment by ShionXIII** [comment]
I just notice that when you search for manga in mangarock through catalogue.
That whether you already follow/add that manga to your library. Its shows that you didn't follow that manga. Even though it still shows on your library 
Yet if you re follow/add it, it will duplicate with the previous one still exist also with their read history and the new one that you just follow

**Comment by arkon** [comment]
That's unrelated.

> A recent update to the MangaRock extension affects the bookmark status of library entries in the catalogue. You can do a "source migration" from existing MangaRock entries to "new" entries.
> 
> This isn't actually necessary unless you care about your entries not being greyed out when looking at the catalogue.

**Comment by heyben9** [comment]
Don't know if this helps at all, but opening a mangarock manga in tachiyomi web view never seems to load, while switching to a browser on the same device and opening the same webpage works just fine.

**Comment by arkon** [comment]
Haven't gotten very far with this yet. Looking at some of the decompiled app code and API calls on the site leads me to believe that the `country` query param is relevant, but I'm not entirely sure how they're detecting it (it sends `India` on my laptop, even though I'm not in India).

**Comment by ShionXIII** [comment]
Well it did updating.. upon further observation.
Its just delayed, before, it took the same time as the real web/apps from mangarock.

Now, the update got delayed.. for like what... 2 - 3 hours, i guess?

**Comment by pavan3999** [comment]
![Screenshot_2019-05-12-23-19-36](https://user-images.githubusercontent.com/23577468/57586007-c5cb4080-750c-11e9-96da-ae290a4d3771.jpg)
i think it's server problem

**Comment by Code027** [comment]
I've had instances that updates take longer than 2-3 hours. One time an update took something like 12 hours.

**Comment by ferdyfachrur** [comment]
Now the delayed updated getting worse
.9+ hours i think
