### ISSUE TITLE
[Source Request][Spanish] EsMangas

### ISSUE THREAD

**Issue by Mickuchiha** [inorichi/tachiyomi-extensions#1085]
Reason: They have the latest chapters on some mangas [not even the most popular english sites have the lattest chapter of 5-toubun for example, but they do(in spanish)]
Site: 
[https://esmangas.net/](https://esmangas.net/)

**Comment by edgarMejia** [comment]
I'll add it soon.

**Comment by Mickuchiha** [comment]
Soon as in Soon™? xD

**Comment by edgarMejia** [comment]
Se hace lo que se puede con el tiempo que se tiene.

**Comment by Mickuchiha** [comment]
Si lo se estaba bromeando en mayor parte xD, solo quería asegurarme que no estuviera abandonada la idea de implementar esto

**Comment by Mickuchiha** [comment]
Any news on this?

**Comment by as280093** [comment]
Here the icons
[EsMangas.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614381/EsMangas.zip)

**Comment by edgarMejia** [comment]
This website is no longer available.
