### ISSUE TITLE
Some manga on Mangahere seems broken

### ISSUE THREAD

**Issue by pervertkirito** [inorichi/tachiyomi-extensions#1089]
Extension version: 1.2.8
App version: r1505

manga link: https://www.mangahere.cc/manga/shounen_shoujo_akatsuki_akira/

Logcat here
`eu.kanade.tachiyomi.debug D/ChapterLoader$loadChapter: Loading pages for Ch.010
eu.kanade.tachiyomi.debug E/ReaderActivity: com.squareup.duktape.DuktapeException: SyntaxError: unterminated statement (line 1)
eu.kanade.tachiyomi.debug E/ReaderActivity:     at com.squareup.duktape.Duktape.evaluate(Native Method)
eu.kanade.tachiyomi.debug E/ReaderActivity:     at com.squareup.duktape.Duktape.evaluate(Duktape.java:69)
eu.kanade.tachiyomi.debug E/ReaderActivity:     at eu.kanade.tachiyomi.extension.en.mangahere.Mangahere.extractSecretKey(Mangahere.kt:255)
eu.kanade.tachiyomi.debug E/ReaderActivity:     at eu.kanade.tachiyomi.extension.en.mangahere.Mangahere.pageListParse(Mangahere.kt:180)
eu.kanade.tachiyomi.debug E/ReaderActivity:     at eu.kanade.tachiyomi.source.online.ParsedHttpSource.pageListParse(ParsedHttpSource.kt:175)
eu.kanade.tachiyomi.debug E/ReaderActivity:     at eu.kanade.tachiyomi.source.online.HttpSource$fetchPageList$1.call(HttpSource.kt:244)
eu.kanade.tachiyomi.debug E/ReaderActivity:     at eu.kanade.tachiyomi.source.online.HttpSource$fetchPageList$1.call(HttpSource.kt:23)`

**Comment by pervertkirito** [comment]
Last mangahere pull request https://github.com/inorichi/tachiyomi-extensions/issues/1089 also remove parseChapterDate for "Today" and "Yesterday"

**Comment by pervertkirito** [comment]
I wonder if I should open another issue about this
Search filters for genres won't works unless you change Type or Completed series to something else that not default

**Comment by Yasminetje96** [comment]
I also have some broken manga with mangahere. I get the following logcat everytime:
![Screenshot_20190702-191438_Tachiyomi](https://user-images.githubusercontent.com/16435942/60533137-27cf4780-9cff-11e9-946c-0dc64ddccb63.jpg) i wasnt certain if i should create a seperate issue for this.

**Comment by SnakeDoc83** [comment]
@Yasminetje96 Ao no Exorcist is licensed, Mangahere took the chapters off their website.

**Comment by CarlosEsco** [comment]
swipe the chapter list down to refresh and you will see chapters gone then
