### ISSUE TITLE
Mangarock not updating. Yet still can download previous chapter

### ISSUE THREAD

**Issue by ShionXIII** [inorichi/tachiyomi-extensions#1094]
Sorry, this'll be my first time posting.

Mangarock on tachiyomi suddenly did not update any new chapter. Whether through update library menu or catalogue.

It did nothing. Like there's no new chapter at all.

Yet on mangarock there are new chapter for aot for the past hours and dungeon seeker & the mage will do better, a moment ago.

Also, there are no problem downloading the already existing chapter

I already update the mangarock extension and have the latest tachiyomi version

Thanks for your help!

**Comment by CarlosEsco** [comment]
#1083
