### ISSUE TITLE
Manga Plus by Shueisha 1.2.2 is broken

### ISSUE THREAD

**Issue by sprite-1** [inorichi/tachiyomi-extensions#1105]
MangaPlus by Shueisha
https://mangaplus.shueisha.co.jp/

I'm using a fork of Tachiyomi but the main issue is the extension itself doesn't load anything. It returns "ReferenceError: identifier 'require' undefined" when I try to browse it and when I use the option to open it in browser, it takes me to this page which returns a 404.

https://jumpg-webapi.tokyo-cdn.com/api

**Comment by ZaneHannanAU** [comment]
Not an issue on r1505 or tachiyomieh. Which fork are you using?

**Comment by arkon** [comment]
Do you have a VPN, or maybe you're located in a place where it doesn't work?

**Comment by ZaneHannanAU** [comment]
For the time being, I've reversed the proto. [mangaplus.zip](https://github.com/inorichi/tachiyomi-extensions/files/3172810/mangaplus.zip).

This could help with debugging, and with sharing (sns data). Could store ducktape output as structured json output and use it or whatever.

This could give more information on eg geoip and so on. Generate and embed, minify/inline where possible.

Could use pb-rs and wasm (wasi?) in the background to set up references or something.

**Comment by sprite-1** [comment]
Hi, sorry for the late reply @ZaneHannanAU, I'm using the NerdNumber9 fork called [TachiyomiEH](https://github.com/NerdNumber9/TachiyomiEH)

@arkon I don't think it's an issue with my particular location because or VPN because

1. I don't have a VPN set up
2. It was working before but just stopped randomly (not sure when as I don't read on MangaPLUS often)

**Comment by ZaneHannanAU** [comment]
NN9 has its own issues and the retainer does not seem to have pursued updates in some time. My current fork is https://github.com/ilwaz/TachiyomiEH though there are some current issues I have with it.

**Comment by sprite-1** [comment]
There has been quite some updates since your fork: https://github.com/NerdNumber9/TachiyomiEH/releases
