### ISSUE TITLE
[English] mangakakalot.com

### ISSUE THREAD

**Issue by opheliakc** [inorichi/tachiyomi-extensions#111]
www.mangakakalot.com

**Comment by LakotaGray** [comment]
Yep, I like this one too

**Comment by RatchetNine76** [comment]
Me as well. As mangahere is getting problematic with missing chapters, I plan to migrate to mangakakalot, as it is my next reading site

**Comment by opheliakc** [comment]
Since I found out this site hosts (steals) pictures from manganelo I no longer want this.

**Comment by CarlosEsco** [comment]
most places just take from other sources..

**Comment by LakotaGray** [comment]
Carlos, should I open a new issue for this Source Request, or can you reopen this one? Even if original poster doesn’t want it anymore, it doesn’t mean the others who commented feel the same :-/
