### ISSUE TITLE
[Source Request] [English] toomics.com

### ISSUE THREAD

**Issue by yoshiro12** [inorichi/tachiyomi-extensions#1120]
please add 
https://toomics.com/en

**Comment by SnakeDoc83** [comment]
It seems this source is pay to read after a few chapters in to a series.

**Comment by arkon** [comment]
#1390

**Comment by pavan3999** [comment]
this is toomics.com and toomics.me are different

**Comment by as280093** [comment]
Here the icons
[toomics.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614386/toomics.zip)
