### ISSUE TITLE
[bug] [broken extension] Mangazuki

### ISSUE THREAD

**Issue by superiorthirst** [inorichi/tachiyomi-extensions#1124]
Mangazuki not loading any mangas/manhwas or any chapthers, not even on browse nor search mode.
Tachiyomi version: 0.8.4
Mangazuki version: 1.0.5

**Comment by arkon** [comment]
Seems to work fine for me, although it only loads 5 things and 0 or a few chapters for each, which is apparently accurate.

(This source sucks, honestly)

**Comment by superiorthirst** [comment]
I'll try backup my Tachiyomi's data and restart, see if that changes anything, Mangazuki seems to be the only source updated on a manhwa I'm reading.

**Comment by arkon** [comment]
Make sure you can actually access the site (try opening it in WebView, if you have something added to your library already).

**Comment by superiorthirst** [comment]
I'm reading it on my browser bcs Mangazuki's Tachiyomi extension doesn't seem to be working, I don't have anything from Mangazuki on my library. ;;

**Comment by arkon** [comment]
Sort of superseded by #1240
