### ISSUE TITLE
Chapter closes on Reopening the app via either Home Screen or App Drawer

### ISSUE THREAD

**Issue by thesidejoe** [inorichi/tachiyomi-extensions#1136]
Versions: 
occurs on dev build r1504 (tested on Pixel XL 2016 Android 9)
occurs on dev build r1506 (tested on OnePlus 7 Pro Android 9 Oxygen OS 9.5.3)
occurs on stable build 0.8.4 (tested on OnePlus 7 Pro)
does NOT occur on stable build 0.7.4 (tested on Pixel XL 2016)

From the looks of it the source of the manga does not matter, although was only tested with MangaDex and one Boredom Society manga. 

When reading a chapter, if you change to another app by multitasking or if you press the home button and then tap the app icon for Tachiyomi either via the home screen or the app drawer, the chapter closes. If you tapped to read the chapter either from the library or the updates tab, the screen will go back to the chapter list or the updates page respectively. This does not happen if you reopen Tachiyomi through multitasking, thereby avoiding tapping the app icon.

**Comment by arkon** [comment]
Wrong repo, but I think this is related:

https://www.reddit.com/r/androiddev/comments/9shz1a/_/
