### ISSUE TITLE
TuMangaOnline

### ISSUE THREAD

**Issue by tamarindoss** [inorichi/tachiyomi-extensions#1141]
BUGS:
HTTP error 403
Tachiyomi version 0.8.4 TuMangaOnline version 1.2.3

**Comment by MerradOklom** [comment]
Hola. La extensión está funcionando sin problemas, visita el sitio https://tmofans.com, si recibes el error 1006 es que bloquearon tu IP por hacer demasiadas peticiones (ya sea por descargar o actualizar la librería). Puedes reiniciar tu módem de internet o esperar 24 horas que es el tiempo que dura el bloqueo.
