### ISSUE TITLE
MangaStream: HTTP Error 400 when downloading

### ISSUE THREAD

**Issue by cerebrain** [inorichi/tachiyomi-extensions#1148]
**Tachiyomi version:** 0.8.4
**Extension version:** 1.0.3

I'm trying to download some chapters of Vigilantes: My Hero Academia Illegals from MangaStream, but when I try to open them/download them in the app it sends HTTP Error 400. I checked that MangaStream was online and that the chapter is available (which it is) but still, the same error. I tried clearing my library and adding it again but it didn't work. I noticed that I could download all the chapters except those that have a name like:

- 00X+ Alpha
- 00X+ Beta

where X is a digit. This doesn't happen with the other chapters with a normal numeration. I'm not particularly desperate to download them but I thought I should report this.

**Comment by sharedkestrel** [comment]
I should add that the final chapter of Shokugeki no Soma gives the same error, probably because there's an "END" in the chapter number. Maybe a regex error?
