### ISSUE TITLE
Webtoons deleting downloaded chapters

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi-extensions#1155]
I don't know why, I don't know how. But the webtoons extension is deleting downloaded chapters.
It has happened with me thrice now. The chapter list even shows the "download" mark but trying to open the chapter gives "page list is empty".

Steps:
1. Go to any webtoons manga in your library (I tested it with [Your Letter](https://www.webtoons.com/en/drama/your-letter/list?title_no=1540))
2. Download chapters
3. Check whether they have been downloaded via file explorer
4. Close app

Now here comes the tricky part. I don't when the issue takes place. I have usually gone back to the manga a day after in every case.

5. The manga in library prominently shows the red download badge
6. Go to chapter list and see the "downloaded" sign on the chapter
7. Open the chapter and get "Page list is empty".

[GIF PROOF](https://giphy.com/gifs/eNRsJRg4qZGofTsRgA)

Tested on: Tachiyomi v0.8.4 r1512 / Webtoons 1.2.16

**Comment by CarlosEsco** [comment]
If you click into a chapter you have. Then back out the downloaded text for the fakes are gone right?  And the download badge is correct number

**Comment by bbtora** [comment]
No, all these still exist. The GIF has shown this too I assume? Or are you talking about something else?

**Comment by arkon** [comment]
Are the chapters still listed on the site?

**Comment by bbtora** [comment]
I can read the chapters online in the app just fine.

**Comment by CarlosEsco** [comment]
So what I am saying is can you click the chapter after the downloaded one then go back to chapter list. Does it still show downloaded text?

**Comment by bbtora** [comment]
Yes, it still shows. Nothing changed. 

You can also see this...
![Screenshot_20190602-010813_Tachiyomi](https://user-images.githubusercontent.com/23010526/58752822-f6324900-84d2-11e9-8f06-e6f016c9ef61.jpg)

**Comment by bbtora** [comment]
A little update: This behaviour has now started happening in "Tower of God" too. Downloaded the chapter yesterday and when going to read it, the same thing happens.

**Comment by Efreak** [comment]
Is it possible that the files are being removed by another app? I have Google's Files app installed, it regularly asks me in a notification to 'clean' the 10000s of files in the Tachiyomi directory to free up space on my device; if I run the app itself, it wants to clean up large folders containing images, including the Tachiyomi folder (this last part may be fixable by placing a .nomedia file in the Tachiyomi folder to prevent media indexing; I haven't tried). Perhaps you have the same/similar app installed?

**Comment by bbtora** [comment]
This behaviour is only happening with Webtoons extension. All the downloaded manga from other sources are not affected.

**Comment by SnakeDoc83** [comment]
When you checked with your file explorer whether the chapter was downloaded or not, did you check that the images were there or did you stop when you saw a chapter folder?  Can you open an image with the file explorer?  After you try viewing the chapter in Tachiyomi and get that error, have you gone back in to your file explorer to see if there are any changes with the folders or images?

**Comment by bbtora** [comment]
>did you check that the images were there or did you stop when you saw a chapter folder?

Yes, the images were present when I initially downloaded it.

>Can you open an image with the file explorer?

Yes, I can open it in file explorer as well as in the app reader.

>After you try viewing the chapter in Tachiyomi and get that error, have you gone back into your file explorer to see if there are any changes with the folders or images?

The folder is present, but the images have been deleted.

And as I said in the initial post,
>I don't know when the issue takes place. I have usually gone back to the manga a day after in every case.

**Comment by SnakeDoc83** [comment]
> And as I said in the initial post,
> 
> > I don't know when the issue takes place. I have usually gone back to the manga a day after in every case.

Which is why I asked the questions I asked, to verify that the images were present and uncorrupted up until you tried to view them in Tachiyomi.  From the wording of your original post, that wasn't 100% necessarily so.  So I asked questions to double check.  I read your post, just trying to help.

**Comment by bbtora** [comment]
Yup, I don't have any problem when reading the downloaded chapters initially. I will try to check whenever I can during the whole day when the problem occurs.

**Comment by bbtora** [comment]
Quick update on the issue: The images inside the chapter folder get deleted at the start of the next day, that is, on midnight. 
And before anyone starts asking if any "optimization" settings have been enabled, please note that this issue is only occurring with Webtoons extension and downloaded chapters from other extensions are not affected.

**Comment by bbtora** [comment]
Found the root cause of the chapter image deletion. 
![](https://i.imgur.com/gxYPSEg.jpg)

There must be something about Webtoons images that causes the native storage booster to target then ahmed not other chapters too.

**Comment by arkon** [comment]
¯\_(ツ)_/¯

**Comment by DeathCel** [comment]
> Quick update on the issue: The images inside the chapter folder get deleted at the start of the next day, that is, on midnight.
> And before anyone starts asking if any "optimization" settings have been enabled, please note that this issue is only occurring with Webtoons extension and downloaded chapters from other extensions are not affected.

This happens with batons extension too
