### ISSUE TITLE
[Arabic] manga.ae

### ISSUE THREAD

**Issue by yshalsager** [inorichi/tachiyomi-extensions#116]
(CATALOGUE) SOURCE REQUESTS:
Please Add Arabic Managa Site 
https://www.manga.ae/

**Comment by yshalsager** [comment]
After about two years, I'll add its support by myself :joy:
I'll send a PR in a few days.
Icons are needed if anyone can provide them.

**Comment by as280093** [comment]
Here are the icons
[manga_ae.zip](https://github.com/inorichi/tachiyomi-extensions/files/3661051/ic_launcher.1.zip)

**Comment by yshalsager** [comment]
@as280093 Thanks so much!
