### ISSUE TITLE
New MANGAPlus extension missing English catalogue

### ISSUE THREAD

**Issue by BloodOath08** [inorichi/tachiyomi-extensions#1162]
Edit: Never mind, restarting Tachiyomi fixed it. I probably should have done that first, sorry...

**Comment by MerradOklom** [comment]
It is not missing for me. Do you have it selected in Catalogue > Sources? 
![Screenshot_2019-06-04-11-56-10](https://user-images.githubusercontent.com/43864503/58890250-a87b3380-86c0-11e9-8dc3-a7a999c62c56.png)

**Comment by bbtora** [comment]
Here's what you should do...

Go to Extensions -> Uninstall 1.2.4 (EN) -> Install 1.2.1 (All) -> Restart app -> Read titles as usual
