### ISSUE TITLE
Option to select various (1 or more) mangas and download as many chapters as requested per each manga

### ISSUE THREAD

**Issue by RoMaAg** [inorichi/tachiyomi-extensions#1169]
I thought that it would be a good idea to add this option described before, so now I will explain it in more detail.

_From a client perspective,_ it would work like this: first of all, (in the library where one has its mangas saved) **you select a number of mangas,** as many as one wishes, for example, 3. When those 3 are selected, **there would appear an option**  (maybe a downside arrow, I don't know, it can be whatever that can be distinguished for this one function) that then (if selected) **would ask how many chapters is it wished to download for each of these mangas,** in our case, 3 mangas. Let's say that we want to download 30 chapters for each of these mangas, in which case **you would type in the number of chapters desired to download,** in our case "30", **and then it would start downloading.** This option is thought not only for use of 3 mangas, but for some numbers much bigger, like 40 mangas.

However, this isn't all that has to be taken account of. Let's say that in one of those 3 mangas, one has already been read for 40 chapters, then, one question arrises: which chapters are to be selected for download? There are four possible combinations taking into account 2 variables; [from read/unread chapters] and [from the top/bot of the previously selected]. Now let's make an example for each using our example of the manga which one has already read 40 chapters (also called as from chapter 1 to 40, being unread from 41 to 100, let's say).
- If it is desired to download from the read (variable 0 let's say) and the top (variable 0 let's say), it would download from 11 to 40. (**00** )
- If it is desired to download from the read (variable 0 let's say) and the bot (variable 1 let's say), it would download from 1 to 30. (**01** )
- If it is desired to download from the unread (variable 1 let's say) and the top (variable 0 let's say), it would download from 71 to 100. (**10** )
- If it is desired to download from the unread (variable 1 let's say) and the bot (variable 1 let's say), it would download from 41 to 70. (**11** )

It wouldn't take into account those chapters that are already downloaded, so if I download (with option 01, so from 1 to 30) 30 chapters and from 6 to 10 are already downloaded (so 5 chapters already downloaded), it would skip those and stop at 30 still, downloading in this operation a total of 25 chapters. Maybe taking those chapters into account (so, with the same example, downloading until chapter 35, having downloaded 30 chapters in total) could be another variable in this.

Thanks for reading until here, you attention is very appreciated. Thanks for your time, take care.

**Comment by CarlosEsco** [comment]
2 things.
1.  wrong repository for this 
2.  this is so much over kill
