### ISSUE TITLE
[Source Request] [ENG]  hentai.cafe

### ISSUE THREAD

**Issue by legioncyclops** [inorichi/tachiyomi-extensions#1170]
Greetings! I'd love it if an extension could be made to support this website in Tachiyomi/TachiyomiEH.

hentai.cafe 

Thanks!

**Comment by MerradOklom** [comment]
Hi, 
There is already a source called Hentai Cafe within the FoolSlide extension, is not that the one you're asking for?

**Comment by legioncyclops** [comment]
Ah I wasn't aware about "FoolSlide" having it. Thanks, just checked, it works like a charm!
