### ISSUE TITLE
Mangachan doesn't work

### ISSUE THREAD

**Issue by Tosterr1** [inorichi/tachiyomi-extensions#1171]
This site were shut down today at 2 PM. and reopen on new address. Fix problem when all of this site been fully recover.

Text on picture:
Urgently !!! This is a new site address.
manga-chan.me
Redirect will soon stop working, manage to save a new address and tell everyone !!!
http://manga-chan.me/catalog
http://anime-chan.me/
http://yaoi-chan.me/
http://h-chan.me/

![image](https://user-images.githubusercontent.com/42684479/59150221-abf81d00-8a28-11e9-891f-925d66662e3b.png)

**Comment by arkon** [comment]
#1177
