### ISSUE TITLE
Hentaichan (henchan) doesn't work

### ISSUE THREAD

**Issue by Tosterr1** [inorichi/tachiyomi-extensions#1172]
This site were shut down today at 2 PM. and reopen on new address. Fix problem when all of this site been fully recover.

Text on picture:
Urgently !!! This is a new site address.
manga-chan.me
Redirect will soon stop working, manage to save a new address and tell everyone !!!
http://manga-chan.me/catalog
http://anime-chan.me/
http://yaoi-chan.me/
http://h-chan.me/

![image](https://user-images.githubusercontent.com/42684479/59150239-fa0d2080-8a28-11e9-8f27-4b9d1e950ab3.png)

**Comment by arkon** [comment]
#1178
