### ISSUE TITLE
[Source Request] HBrowse English

### ISSUE THREAD

**Issue by Jzarecta** [inorichi/tachiyomi-extensions#1174]
Please add HBrowse from HBrowse.net

**Comment by as280093** [comment]
Here the icons
[hbrowse.com.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614391/hbrowse.com.zip)

**Comment by MercerBoi** [comment]
Yes, I support this as well. Generous developers, I summon thee! Take a gander at this issue and see what you can do!
