### ISSUE TITLE
[Source request] [Italian] DDT Reader

### ISSUE THREAD

**Issue by arkon** [inorichi/tachiyomi-extensions#1179]
Originally from #753 

https://ddt.hastareader.com/

**Comment by SnakeDoc83** [comment]
I was about to open a PR to add this source to Foolslide when I saw this (https://github.com/inorichi/tachiyomi-extensions/pull/115) about a different hastareader previously being removed.

Now, hastareader.com and ddt.hastareader.com have different content and the username on the uploads are different, but in the end they are both on the same domain.

So, should I go ahead with opening that PR for this under the idea that ddt.hastareader.com is a separate entity from the main domain or would you rather close this issue without adding it?

**Comment by as280093** [comment]
Here the icons
[DDT Reader.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614399/DDT.Reader.zip)
