### ISSUE TITLE
Extension title update problem

### ISSUE THREAD

**Issue by Znova99** [inorichi/tachiyomi-extensions#1181]
BUGS:
  Extension not updating titles at the same rate as their online websites

Eg: martial peak on mangadex extension
Latest chapter no.:78 on website but in the app latest chp: 76 (tried updating and refreshing= no effect ) 

App version : 0.8.4
Mangadex ext version: 1.2.6.1

**Comment by arkon** [comment]
Chapters 77 and 78 are scheduled to be released later.
