### ISSUE TITLE
Hard to see what's included in an extension.

### ISSUE THREAD

**Issue by Presac** [inorichi/tachiyomi-extensions#1184]
It is quite hard for a user to see which sites are part of the foolslide and madara extension. Is it possible to list it on the wiki, or get it in another way than going to [MadaraFactory.kt](https://github.com/inorichi/tachiyomi-extensions/blob/master/src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt)/[FoolSlideFactory.kt](https://github.com/inorichi/tachiyomi-extensions/blob/master/src/all/foolslide/src/eu/kanade/tachiyomi/extension/en/foolslide/FoolSlideFactory.kt)

**Comment by ZaneHannanAU** [comment]
I have also wanted this for some time. Ideally the extensions would have their own page; or perhaps they would include some breakdown through internal methods; eg through reading of the baseUrl before deployment.

**Comment by CarlosEsco** [comment]
in 1.x they will be separate apks.  But if anyone wants to make a faq or something go ahead.

**Comment by arkon** [comment]
#841 could potentially address this with some extra stuff.
