### ISSUE TITLE
Mangazuki Raws

### ISSUE THREAD

**Issue by akinari1412** [inorichi/tachiyomi-extensions#1186]
I have request for mangazuki.co and https://raws.mangazuki.co/, it's seems there is a same name in your catalog app but the web is diferent and not realy active.

**Comment by CarlosEsco** [comment]
mangazuki.co already exists

**Comment by ara8ara** [comment]
mangazuki.co only show 5 tittle of manwha, must be update it,

**Comment by arkon** [comment]
They only have 5 things on their website, I'm not sure what you're expecting.

**Comment by arkon** [comment]
Potentially replaceable with https://mangazuki.club/
