### ISSUE TITLE
Page list is empty error in ReadComicOnline

### ISSUE THREAD

**Issue by TheSorrowfulJack** [inorichi/tachiyomi-extensions#1193]
BUGS:
I am unable to view any chapters from titles in the ReadComicOnline extension

App version: 0.8.4
Source version: 1.2.5

**Comment by S-Raza-A** [comment]
Same here. Plus I'm not getting any error prompts. When viewing the chapters, it is just showing the retry button. And when downloading a chapter, it does not download or give any prompt.

While troubleshooting, noticed that I can load readcomiconline website just fine, but the images for any of the series chapters never load an image (shows the broken image icon). Both on the mobile version and the desktop version for the webpage. 

But the website is fine on my Desktop. 

Tried already:
Removing and reinstalling the ReadComicOnline extension.
Clearing the Cache.
Tried the "Dev Build", same problem.

**Comment by TheMile** [comment]
I suspect this is a captcha thing, as the download queue in Tachiyomi will work for a bit after I complete a captcha at readcomiconline.to.

**Comment by S-Raza-A** [comment]
> I suspect this is a captcha thing, as the download queue in Tachiyomi will work for a bit after I complete a captcha at readcomiconline.to.

You may be on to something, though in my case I haven't seen any Captcha on both my Android or my Desktop on the readcomiconline.to webpage.

**Comment by S-Raza-A** [comment]
I have isolated the problem. The images on readcomiconline.to are loaded from bp.blogpost which is google image server, these images are not loading only on Android. Not because of an Ad-blocker, but something else. Will update when I find something else.

**Comment by S-Raza-A** [comment]
EUREKA!! Found it, my Android was not using Google's DNS. Tried to manually changed it in Android settings but had trouble. Just look up a decent DNS changer in the Google App store and use Google's DNS (8.8.8.8 and 8.8.4.4). Works fine now. Cheers.

**Comment by TheMile** [comment]
> EUREKA!! Found it, my Android was not using Google's DNS. Tried to manually changed it in Android settings but had trouble. Just look up a decent DNS changer in the Google App store and use Google's DNS (8.8.8.8 and 8.8.4.4). Works fine now. Cheers.

This doesn't work for me as I was already using the Google DNS servers.  I tried switching to the OpenDNS servers, but the problem continued.  I fear this may be a temporary or coincidental solution.

**Comment by SnakeDoc83** [comment]
Closing due to age and changes in extension.
