### ISSUE TITLE
Manga rock extension delay issue

### ISSUE THREAD

**Issue by LoLyeah** [inorichi/tachiyomi-extensions#1199]
Tachiyomi ver r1515
Mangarock ver 1.2.11

There's always some delay on Mangarock in Tachiyomi. Is it a bug or just an intentional delay?
![Screenshot_2019-06-15-17-31-44-470_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/11774211/59550338-b3bd4180-8f93-11e9-9597-89bdfd6c1e50.png)
![Screenshot_2019-06-15-17-31-29-354_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/11774211/59550342-b9b32280-8f93-11e9-9594-e4affdd57125.png)
![Screenshot_2019-06-15-17-31-52-889_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/11774211/59550347-d0f21000-8f93-11e9-9f86-1a4b4fdbac29.png)

(27 chapters on Mangarock site vs 26 chapters on Tachiyomi)
The latest chapter was uploaded 11 hours ago, but it's still not updated on Tachiyomi yet.

**Comment by ZaneHannanAU** [comment]
I'm presuming you've refreshed the page or done a manual update...
By the way; the translators upload on mangadex directly; so that could be why they don't show it through the api: https://mangadex.org/manga/23569/

**Comment by LoLyeah** [comment]
Yes, I already refreshed the page or done a manual update, obviously. 

And yes, the translators upload on Mangadex (I've followed this manga on Mangadex but not on Tachiyomi, that's why I noticed the delay on the Manga Rock extension.)

Other manga on manga rock extension also have a same issue.

**Comment by ZaneHannanAU** [comment]
In that case there would be almost nothing we can do about it. If they have the delay for their API; there's probably some reason like waiting *n* hours to scrape from mangadex to pull information in.

**Comment by thegodofplay** [comment]
There is  actually nothing to scrape from mangadex. Because most of popular manga got removed from mangadex because of some issues between translators and mangadex.

I am facing same issue. That new chapters are available on mangarock website but doesn't show up in tachiyomi app if you add manga from mangarock catalog, even after you clear Cache and cookies. 
(sorry for bad English)

**Comment by CarlosEsco** [comment]
Most popular lol.

**Comment by arkon** [comment]
It's some issue with the MangaRock API, but I'm not really sure what. Could be a caching issue. Otherwise, we could potentially start scraping the site instead.

**Comment by pavan3999** [comment]
same for every manga delaying update for 5~11 hours

**Comment by brassica77** [comment]
Issue still happens : more than 13 hours delay between Manga Rock app/site and Tachiyomi for my series.

**Comment by thegodofplay** [comment]
@arkon
This fix isn't working for me too.
Open this issue again.

**Comment by arkon** [comment]
Considering the imminent legal issues MangaRock is facing, I doubt it's even worth trying to fix.

**Comment by arkon** [comment]
Considering it's literally dying, probably not worth looking into if it's still an issue.
