### ISSUE TITLE
Add icon to apks

### ISSUE THREAD

**Issue by j2ghz** [inorichi/tachiyomi-extensions#12]
```
# aapt dump badging repo/tachiyomi-de.wiemanga-v1.0.1-debug.apk
package: name='eu.kanade.tachiyomi.extension.de.wiemanga' versionCode='1' versionName='1.0.1' platformBuildVersionName='7.1.1'
sdkVersion:'16'
targetSdkVersion:'25'
ERROR getting 'android:icon' attribute: attribute is not a string value
```
~I see two solutions, add the icon, or I will make the metadata manually, without icon.~
~It's not a problem, just new catalogues won't be published as soon as commited, I will have to add the metadata, until then builds will fail~
```ERROR: Failed to get apk information, skipping repo/tachiyomi-ru.readmanga-v1.0.1-debug.apk
ERROR: Failed to get apk information, skipping repo/tachiyomi-en.kissmanga-v1.0.1-debug.apk
ERROR: Failed to get apk information, skipping repo/tachiyomi-en.mangahere-v1.0.1-debug.apk
ERROR: Failed to get apk information, skipping repo/tachiyomi-en.mangasee-v1.0.1-debug.apk
ERROR: Failed to get apk information, skipping repo/tachiyomi-en.readmangatoday-v1.0.1-debug.apk
ERROR: Failed to get apk information, skipping repo/tachiyomi-ru.mangachan-v1.0.1-debug.apk
ERROR: Failed to get apk information, skipping repo/tachiyomi-it.mangaeden-v1.0.1-debug.apk
ERROR: Failed to get apk information, skipping repo/tachiyomi-ru.mintmanga-v1.0.1-debug.apk
ERROR: Failed to get apk information, skipping repo/tachiyomi-en.mangafox-v1.0.1-debug.apk
ERROR: Failed to get apk information, skipping repo/tachiyomi-de.wiemanga-v1.0.1-debug.apk
```
my bad, it won't work without the icons

**Comment by inorichi** [comment]
What is the command needed for?

I don't mind having icons in the apks, but finding/creating an icon big enough is an annoying task. I'll leave it open for PRs.

**Comment by j2ghz** [comment]
To be able to add an apk to fdroid repo, fdroid gets info (app name, version, icon, ...) from `aapt dump badging`

**Comment by j2ghz** [comment]
Would it be okay to use the same as the main app has? Or just modifying it a bit? The icon won't be displayed almost anywhere anyway (fdroid and Settings > Apps)

**Comment by inorichi** [comment]
I would use either a modification or the default android icon (the one shown when the icon is null).
