### ISSUE TITLE
MangaDex download HTTP Error 503

### ISSUE THREAD

**Issue by serjflint** [inorichi/tachiyomi-extensions#1203]
Tachiyomi r1515 and 0.8.4
Mangadex 1.2.62
Android 9.0.0
Honor Play and OnePlus 3T
Today the latest version of Mangadex plugin fails to open or download any chapter with HTTP Error 503. When I tried to check on another phone with an old version, it opened normally. After an update on the same phone, the error appeared again. I still can search and open a webview with a chapter. I am logged in user.

**Comment by serjflint** [comment]
Re-installing the plugin, cache clean, logging out/in and reboot don't help.

**Comment by LoLyeah** [comment]
Try to open mangadex website via Tachiyomi. (Click a manga from Tachiyomi, click menu on the top right, choose open in webview.)

It was because some douche spamming on Mangadex forum with script, and that activated the Cloudflare protection system.

**Comment by serjflint** [comment]
Yeah, as I said web view works by itself, but it doesn't solve the problem. Also previous version of the plugin was working normally

**Comment by serjflint** [comment]
Now it is working

**Comment by serjflint** [comment]
Now it is working
