### ISSUE TITLE
Mangadex doesnt change read/unread status anymore

### ISSUE THREAD

**Issue by MammothJerk** [inorichi/tachiyomi-extensions#1210]
Tachiyomi v: 0.8.4
Mangadex source: 1.2.62

I'm not sure at what end this problem is coming from but im assuming it's from the latest mangadex source update, and it might even have been an intentional change.

When logged in on mangadex through the webview option when a new chapter gets downloaded it would automatically change the status of the chapter in mangadex to "read". Now downloading through mangadex does NOT change the unread status of a chapter.

Was this an intentional change? personally i really liked this option since i read both on phone and on desktop so knowing what i had already read on the phone was really helpful.

**Comment by CarlosEsco** [comment]
It's a mangadex thing. Not tachiyomi change. Tachiyomi just  reads the image url.  Maybe turn off auto tracking in mangadex if that's an option

**Comment by arkon** [comment]
It was not an intentional change, so we do not intend on supporting it.

**Comment by CarlosEsco** [comment]
I don't know how we could?  A completely different instance of webview so cookies aren't in it for image urls?
