### ISSUE TITLE
[Source Request] MangaSail

### ISSUE THREAD

**Issue by KeirLoire** [inorichi/tachiyomi-extensions#1211]
Hello,

I would like to request an extension for Tachiyomi app with MangaSail as source.

Here is the link to the source:
https://mangasail.co/

**Comment by SnakeDoc83** [comment]
I think I'll be working on this next.

@as280093 I'll take some icons if you want to ready them.

**Comment by as280093** [comment]
its not official one but its fine as official logo quality is low
[ic_launcher (2).zip](https://github.com/inorichi/tachiyomi-extensions/files/3307327/ic_launcher.2.zip)
![logo art](https://user-images.githubusercontent.com/25240839/59788222-e2674f00-92e8-11e9-9865-5ed465ada9c8.png)

**Comment by zagrib** [comment]
Why don't you try https://mangaseinen.com

**Comment by KeirLoire** [comment]
Thank you for working on this.
