### ISSUE TITLE
MangaDex doesn't filter languages

### ISSUE THREAD

**Issue by FatGamers** [inorichi/tachiyomi-extensions#1215]
MangaDex's Latest Manga list shows other languages updates, showing old manga updates. It should be just 1 language source instead of checking the whole entire language database from MangaDex. 

MangaDex 1.2.62

**Comment by ZaneHannanAU** [comment]
This is an issue on the mangadex side of things; due to performance reasons.

**Comment by arkon** [comment]
The extension relies on a cookie to filter the language which I think no longer works. Needs to be further investigated.

**Comment by ZaneHannanAU** [comment]
<https://mangadex.org/updates/1>

Huh... oops.

 The tl;dr is that you'll need to set language in webview right now.

**Comment by ZaneHannanAU** [comment]
https://mangadex.org/thread/149126
currently the back end ignores the `mangadex_filter_langs` cookie and relies on the session cookie only.

**Comment by SnakeDoc83** [comment]
Browsing mangadex.org/updates (where latest is pulled from in Tachi), it looks like language settings are being respected now.  Unless I'm overlooking something, this can be closed.

**Comment by AriaMoradi** [comment]
Is this still relevant?

**Comment by CarlosEsco** [comment]
i dont believe so.

**Comment by arkon** [comment]
Pretty sure it is, but /shrug

**Comment by CarlosEsco** [comment]
its not a bug on our end though.  They dont offer the ability to filiter out by langauge currently
