### ISSUE TITLE
[Source Request] [English] Valhalla Scans

### ISSUE THREAD

**Issue by TigerUppercut** [inorichi/tachiyomi-extensions#1223]
I'd like to request a source for Valhalla Scans

https://valhallascans.com/

Best quality icon I could find is this one:
![PAQEhgu - Imgur](https://user-images.githubusercontent.com/6539689/59978799-6736bf00-95ae-11e9-848a-799c5d7e0f76.jpg)

Thanks guys

**Comment by SnakeDoc83** [comment]
Added yesterday, this can be closed.
