### ISSUE TITLE
ADD new source: 8muses

### ISSUE THREAD

**Issue by darkDaiyo** [inorichi/tachiyomi-extensions#1228]
A must website for western adult genre. There is a lack of western adult content/source and 8muses is E-hentai for western artists.
https://www.8muses.com/comics

**Comment by pervertkirito** [comment]
> (CATALOGUE) SOURCE REQUESTS:
  One source per issue, create more issues if you have more websites
  **Check for duplicates, use search (in issues, not the global one)**
  Put the name of the site as Title, replace this text with clickable link to the site

duplicate https://github.com/inorichi/tachiyomi-extensions/issues/542
