### ISSUE TITLE
MangaHentai won't load

### ISSUE THREAD

**Issue by SamAresOfficial** [inorichi/tachiyomi-extensions#1229]
If I try to load into the Catalogue for the source is says, "No Results" and the Manwha I have in my Library opens and closes everytime I click on a chapter, though it doesn't give any error message, I am on the latest dev build.

**Comment by ramattos** [comment]
Domain now redirects to brazzers, that's why it doesn't work anymore. I have no idea if this is a temporary thing, if it's a domain seizure or if their domain got stolen, or if they simply closed shop.

**Comment by karnadii** [comment]
mangahentai or manhwahentai? for manhwahentai issue already closed, see #1230

**Comment by arkon** [comment]
Actually, reopening until the extensions are removed.

**Comment by karnadii** [comment]
manhwahentai related to manhwahand, so makesure to remove it as well.

**Comment by SamAresOfficial** [comment]
I really hope this is temporary, but does anyone know of any extensions that are like ManwhaHentai?
