### ISSUE TITLE
Manhwa hentai is not working

### ISSUE THREAD

**Issue by Titus30** [inorichi/tachiyomi-extensions#1230]
(CATALOGUE) SOURCE REQUESTS:
  One source per issue, create more issues if you have more websites
  Check for duplicates, use search (in issues, not the global one)
  Put the name of the site as Title, replace this text with clickable link to the site
BUGS:
  Provide tachiyomi version as well as version of source the report is about

**Comment by karnadii** [comment]
> We're offline due to a Cease and Desist.
> We will not be coming back online to host Comics. However, we will continue to build this server up as the place to Find/Discuss Manhwa, Pornhwa, Hentai, etc.
source: Manhwahentai discord channel
