### ISSUE TITLE
[Source Request] [Spanish] 
CoHentai

### ISSUE THREAD

**Issue by Credits125** [inorichi/tachiyomi-extensions#1233]
URL: ⬇️ 🙏 

[CoHentai](https://cohentai.com)

**Comment by as280093** [comment]
Here the icons
[CoHentai.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614401/CoHentai.zip)

**Comment by edgarMejia** [comment]
This source is no longer available.
Please close it.
