### ISSUE TITLE
Manhwahentai.com has offically shifted to Manhwahentai.site

### ISSUE THREAD

**Issue by Titus30** [inorichi/tachiyomi-extensions#1234]
(CATALOGUE) SOURCE REQUESTS:
Manhwahentai.com has offically shifted to Manhwahentai.site
  One source per issue, create more issues if you have more websites
  Check for duplicates, use search (in issues, not the global one)
  Put the name of the site as Title, replace this text with clickable link to the site
BUGS:
  Provide tachiyomi version as well as version of source the report is about

**Comment by karnadii** [comment]
![Manhwahentai discord announcement](https://imgur.com/a/be9ppvH)

there is no official statement from manhwahentai. they say they won't go back online. it seems just a copycat site.

**Comment by SamAresOfficial** [comment]
This should be closed...
