### ISSUE TITLE
Mangazuki extension should be directed to mangazuki.me

### ISSUE THREAD

**Issue by chriskendall90** [inorichi/tachiyomi-extensions#1240]
Hello, 

Currently the Mangazuki extension goes to mangazuki.co which has no manwha/manga. It should be sourced to https://mangazuki.me/

**Comment by arkon** [comment]
Looks like that site (.me) does contain the 5 things that the old site has (.co), so this is a valid request.

**Comment by SnakeDoc83** [comment]
Is .me really Mangazuki though?  I was taking a look around before when one of the older requests came up and I had found this .me site and also a mangazuki.online.  From what I remember, the two sites had slightly different content.  Meanwhile, Mangazuki on MangaDex and Facebook only pointed to mangazuki.co.  Are they all Mangazuki or is the name used by multiple parties?  It made me wonder if the people who were asking for Mangazuki were all asking for the same source or not.

If someone does go forward with using the .me or .online site, it can probably go in the Madara extension.

**Comment by CarlosEsco** [comment]
closing this cause i agreewith Snakedoc
