### ISSUE TITLE
Manhwahentai

### ISSUE THREAD

**Issue by vikashranjan12** [inorichi/tachiyomi-extensions#1245]
One of the Extension on Tachiyomi got offline i.e "manhwahentai.com" and now they have started new website as "manhwahentai.site" so plzz add this extension.

One more thing add mangazuki.me extension also bcz the mangazuki that you have added has less manga only 6-8.

**Comment by CarlosEsco** [comment]
as per another ticket mangazuki.me does not seem to be the official site for them.  Its a different clone it seems

**Comment by vikashranjan12** [comment]
But can't you add mangazuki.me extension

**Comment by as280093** [comment]
best alternative for ManhuaHentai is 
Heaven Manga, MangaPark, Mangazuki, MangaRock 
New Updates will not be found as most of them scrapped from ManhuaHentai

if you can't find any series refer to this spreadsheet
https://docs.google.com/spreadsheets/d/1hMfCCiBADxgNjnxgDFvDcP3vSsRxVJ4XnBWyFqrKd68/edit?usp=sharing

ManhuaHentai owers has confirmed that they will not open any new sites and if any site with same name is found its a fake.

**Comment by BhenChod1221** [comment]
Now you can read all of your favourite [manhwahentai manga here](https://www.mangazuki.online/manga-genre/manhwahentai/)

**Comment by CarlosEsco** [comment]
manhwahentai.site is also not offiically from manhwahentai.com.  If you want 

manhwahentai.site and or mangazuki.me  please open 1 ticket for each of them.
