### ISSUE TITLE
MangaDexSFW

### ISSUE THREAD

**Issue by LightWing-IsMe** [inorichi/tachiyomi-extensions#1249]
I'm trying to make a SFW version of the MangaDex extension, and I don't have access to a computer, so I'm using an app call AIDE (it's supposed to be able to create the APK from the source code, after my edits), after I try and compile the APK, I get an error "aapt failed" I have no idea what to do from here, this is my first time trying to compile an app, and first time posting here (I think), any help would be much appreciated

**Comment by CarlosEsco** [comment]
We don't really support non Android studio building. But long story short you need to look at the logs and see what it says
