### ISSUE TITLE
LeviatanScans 404 in Browse, Empty in latest, opens fine in webview

### ISSUE THREAD

**Issue by loocool2** [inorichi/tachiyomi-extensions#1254]
R1518; Madara 1.2.1
title, tried clearing cache and extension data, titles associated with madara no longer work either.

**Comment by arkon** [comment]
Looks like it's using the same system as the PsychoPlay site, not sure if that's related to any of these aggregate extensions.

**Comment by SnakeDoc83** [comment]
The system seems fairly new, don't think it's in any of the current factory extensions.  I've got a new factory extension including Psycho Play, Leviatan Scans, and One Shot Scans I'll submit soon.

**Comment by arkon** [comment]
Now in Genkan extension.
