### ISSUE TITLE
[Indonesian] Mangaku.web.id

### ISSUE THREAD

**Issue by naaiil** [inorichi/tachiyomi-extensions#126]
Site Request
Please Add Indonesian Manga :
http://mangaku.web.id

Thanks

**Comment by as280093** [comment]
Domain changed to [https://mangaku.in/](https://mangaku.in/)

**Comment by abesty** [comment]
Is there any progress for mangaku.in?

**Comment by arifr007** [comment]
https://github.com/inorichi/tachiyomi-extensions/pull/1602

**Comment by arifr007** [comment]
this can be closed :D
