### ISSUE TITLE
Feature Request: tell the user to use another source when MangaDex gives HTTP error 300

### ISSUE THREAD

**Issue by RunningDroid** [inorichi/tachiyomi-extensions#1270]
Tachiyomi version: 0.8.4
MangaDex extension version: 1.2.63

When I try to read or download the first chapter of [Dr. Stone](https://mangadex.org/manga/20882/) MangaDex gives me HTTP error 300 (Multiple Choices)

**Comment by RunningDroid** [comment]
Apparently the reason MangaDex gives HTTP error 300 when trying to read the first chapter of Dr. Stone in English is because Dr. Stone has a licensed English translation on "Manga Plus by Shueisha".

I guess it would be nice if the MangaDex extension would catch this and say "the $LANG translation of this manga has been licensed and is no longer available from MangaDex. Use the $EXTENSION source to read it with Tachiyomi"

**Comment by CarlosEsco** [comment]
Your getting 300 because at some point there were chapters and you had them cached. Then mangadex removed them. Mangadex doesn't have a status on why things are removed so your request makes no sense.  There is already a pop up when there are no chapters found and is the best we can do
