### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by yasnil03** [inorichi/tachiyomi-extensions#1273]
Just now i tried to download some manga. The problem is i can't download in all sources like kissmanga, mangahasu, myreadingmanga. Can you help me fix it or ask if only i have encountered this problem?

**Comment by arkon** [comment]
You'll need to provide a lot more information than that.

What version of the app are you on?
Are all of the extensions updated?
_Exactly_ which sources and chapters are you trying to download?
Can you access the sites in your browser?

**Comment by yasnil03** [comment]
V.0.8.4
All extensions are updated
Like in myreadingmanga itried to download  Hard X Heat X Heart using WiFi and data. I tried many tikes but the end i can't download it. I thought maybe just this manga and try another but i still can't download any manga

**Comment by arkon** [comment]
Do you get any errors?

**Comment by yasnil03** [comment]
Yeah it says download error the downloader null... Like that

**Comment by arkon** [comment]
Can you provide the full error message?

**Comment by mil7005** [comment]
I also can't download from Readmangatoday ext. It hangs and then error out on time expiration.  I can download from the other extensions.

**Comment by mil7005** [comment]
For ReadMangaToday I can see catalogs but get retry for any Manga I try to open.

Running 0.8 on S9

**Comment by yasnil03** [comment]
I also can't open myreadingmanga sometines

**Comment by yasnil03** [comment]
SSL handshake aborted:
ssl=0x5564730740: I/0 error.
That what i see when i open myreadingmanga

**Comment by yasnil03** [comment]
And i tried to download
java.net.SocketTimeoutException: timeout

**Comment by ZaneHannanAU** [comment]
Try checking through webview, then setting your DNS to 1.1.1.1, or installing https://1.1.1.1, and then checking webview again.

**Comment by arkon** [comment]
Make sure the date/time on your device is correct.
