### ISSUE TITLE
Hitomi.la

### ISSUE THREAD

**Issue by fam007e** [inorichi/tachiyomi-extensions#1278]
Hitomi.la fork for latest tachiyomiEH is not working... It shows " Handshake failed". In extension menu, it doesn't show either. Also tsumino is absent from extension options.
I've used 8.7 version to 7.2 all of them...
My Android device is Xiaomi Redmi Note 4X. Please solve this issue...
Thank you

**Comment by SnakeDoc83** [comment]
Uh, if you're having a problem with TachiyomiEH, you should probably post to their github page, not here.

https://github.com/NerdNumber9/TachiyomiEH/issues

**Comment by bbtora** [comment]
Not probably, you should definitely not post in this repo. Close this asap.
