### ISSUE TITLE
ReadMangaToday Error

### ISSUE THREAD

**Issue by Thoasty** [inorichi/tachiyomi-extensions#128]
I'm getting this error when trying to read chapters from ReadMangaToday. I have cleared my cookies and cache but still no luck. Is anyone getting this issue also and how do I fix it? Thank you.

![screenshot_20171117-151619](https://user-images.githubusercontent.com/17102931/32984312-af9de440-cc69-11e7-8174-14c873cbd90a.png)

**Comment by j2ghz** [comment]
This issue is tracked at inorichi/tachiyomi#1070, but since readmangatoday is available in app and as an extension, it can be kept open in both repositories.

**Comment by na-ji** [comment]
To fix this problem, three options are now available:
 - Wait for the next stable release of Tachiyomi
 - Use the dev version of Tachiyomi
 - [Download Readmangatoday as an extension from F-Droid](https://github.com/inorichi/tachiyomi-extensions#usage)
