### ISSUE TITLE
[Source Request][English] ShoujoHearts

### ISSUE THREAD

**Issue by kiriya-aoi** [inorichi/tachiyomi-extensions#1291]
(CATALOGUE) SOURCE REQUESTS:
  http://shoujohearts.com/

**Comment by arkon** [comment]
For context, I thought this was in Foolslide at some point.

**Comment by SnakeDoc83** [comment]
I'll work on this one.

**Comment by Vesnyx** [comment]
http://shoujohearts.com/reader/

Foolslide based, should be very simple to add.
