### ISSUE TITLE
[Source Request][English] Man Manga

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi-extensions#1296]
It's a mobile site

Source: https://m.manmanga.com/

It has many exclusive and popular manhwa from Lezhin and other manhwa sites

**Comment by waptik** [comment]
I've begun working on it today, so it might take some time because it's my first building a mobile and first with kotlin.
If anyone is working on it already, let me know so i can stop.

**Comment by as280093** [comment]
@waptik here are the logos if you are working on this source
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3402546/ic_launcher.4.zip)

**Comment by waptik** [comment]
> 
> 
> @waptik here are the logos if you are working on this source
> [ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3402546/ic_launcher.4.zip)

@as280093 Thanks for providing me with the logos

**Comment by waptik** [comment]
@as280093 bro, how do i test it properly after creating the extension?
I followed the guildelines in the contributing section, but as i can't use my phone to run it directly(drivers issues), i use the **Building** options:
- `Build > Generate Signed Bundle / APK.`, gives me certification issues during installations
- `Build > Build Bundle(s) / APK(s) > Build APK(s)`, gives me **App not installed** error
I'd be grateful if you could guide me in the extension generation process in order to generate mine without issue.

**Comment by arkon** [comment]
>  gives me App not installed error

Uninstall the existing one first.

**Comment by waptik** [comment]
> > gives me App not installed error
> 
> Uninstall the existing one first.

I've done that!

**Comment by waptik** [comment]
How do i deal with parts of the chapters that are being loaded with javascript?
This is the element that loads it: `<li id="showMore"><a class="more" href="javascript:void(0)"></a></li>`
eg. [https://m.manmanga.com/detail/e4q9v81yMO](https://m.manmanga.com/detail/e4q9v81yMO)

**Comment by ZaneHannanAU** [comment]
Generally, it's done through parameter modification. In this case, if seems likely that it's loading through JSON; so try opening the network tab and looking for repeatable patterns in it.

It's rare for an irrepeatable pattern to occur in software; so test with and without js; and with/without curl.

**Comment by waptik** [comment]
> Generally, it's done through parameter modification. In this case, if seems likely that it's loading through JSON; so try opening the network tab and looking for repeatable patterns in it.
> 
> It's rare for an irrepeatable pattern to occur in software; so test with and without js; and with/without curl.

Ok. It seems that it's able to fetch all chapters by default by ignoring `<li id="showMore"><a class="more" href="javascript:void(0)"></a></li>` . I guess it behaves the same way when viewing the source of the page using `ctrl+u`.
Listing of mangas seems to be done per page with the next page being loaded at the end of the scroll(fetched through js not json):[popular & latest js file]( https://static.manmanga.com/official/manmanga/m/js/category.js) [search js file] ,(https://static.manmanga.com/official/manmanga/m/js/search_list.js) and `next_page_url` which is the variable for the next page url.

You can view my latest code at [ManManga Extension](https://github.com/waptik/tachiyomi-extensions/blob/master/src/en/manmanga/src/eu/kanade/tachiyomi/extension/en/manmanga/ManManga.kt).
