### ISSUE TITLE
[Source Request] Explosm (Cyanide and happiness)

### ISSUE THREAD

**Issue by hXtreme** [inorichi/tachiyomi-extensions#1299]
[Link to webpage](http://explosm.net/comics/archive)

**Comment by kakardo** [comment]
How do you link this to your app? Sorry I'm quite new to this.

**Comment by as280093** [comment]
Here the icons
[explosm.zip](https://github.com/inorichi/tachiyomi-extensions/files/3612908/explosm.zip)
