### ISSUE TITLE
Catalogue Request : Chinese sources

### ISSUE THREAD

**Issue by lilyke** [inorichi/tachiyomi-extensions#13]
Would it be possible to add Chinese sources such as DM5 http://www.dm5.com/ and manhua dmzj http://manhua.dmzj.com ? 

Thanks

**Comment by j2ghz** [comment]
(CATALOGUE) SOURCE REQUESTS: One source per issue, create more issues if you have more websites Check for duplicates, use search (in issues, not the global one) Put the name of the site as Title, replace this text with clickable link to the site

**Comment by inorichi** [comment]
Closing issues that do not follow the guidelines. Feel free to open a new one that complies with them.
