### ISSUE TITLE
mangarock.com: Value Chapter is removed at data of type java.lang.String cannot be converted to JSONArray

### ISSUE THREAD

**Issue by LuigiHarrisMario** [inorichi/tachiyomi-extensions#1307]
[mangarock.com](mangarock.com)

Tachiyomi version: 0.8.4
MangaRock extension version: 1.2.11

Getting this error when trying to read/download specific chapters of different manga:

> Value Chapter is removed at data of type java.lang.String cannot be converted to JSONArray

This applies to **chapter 165 of Yuuna and the Haunted Hotsprings** and **chapter 938 of Tomo-chan is a Girl!** on my end.

I have already seen the existing closed issues, where it was resolved with a simple update of the extension. However I am already on the latest version of the MangaRock Extension.
Have been directed to here by the support in the Discord server

Links to the chapters, which are working fine in browser:
[Chapter 165 of Yuuna and the Haunted Hotsprings](https://mangarock.com/manga/mrs-serie-283326/chapter/mrs-chapter-200077713)
[Chapter 938 of Tomo-chan is a Girl!](https://mangarock.com/manga/mrs-serie-254590/chapter/mrs-chapter-200082835)

**Comment by SnakeDoc83** [comment]
I think it's a problem on Mangarock's end.  

This is the API response when asking for Yuuna chapter 165: https://api.mangarockhd.com/query/web401/pages?oid=mrs-chapter-200077713, it says chapter is removed (even though it's available on the website).  

This is the response for a working chapter: https://api.mangarockhd.com/query/web401/pages?oid=mrs-chapter-200071881.

**Comment by Syborg49** [comment]
Still shows the same issue

https://ibb.co/SmHB9ZQ

**Comment by LuigiHarrisMario** [comment]
> 
> 
> Still shows the same issue
> 
> https://ibb.co/SmHB9ZQ

Update your library
