### ISSUE TITLE
MangáLivre broken

### ISSUE THREAD

**Issue by TemptingBadger** [inorichi/tachiyomi-extensions#1309]
I've been a bug with one extension.
MangáLivre (PT) version 1.2.4, on Tachiyomi I'm using version 0.8.4 .
When I update any Mangá in this source, it make this erro: 
![Screenshot_20190718-034846](https://user-images.githubusercontent.com/31442758/61435913-fe720680-a90f-11e9-9163-319cb9ef2dcf.jpg)
When I thought in just migrate de source, it show nothing forever.
![Screenshot_20190718-035016](https://user-images.githubusercontent.com/31442758/61435997-324d2c00-a910-11e9-8e7a-b2058cb197e3.jpg)
Can anyone help me with that?
Tks.

**Comment by SnakeDoc83** [comment]
If you visit that source's website (https://mangalivre.com/) you'll see it's not accessible at this time.  It's been like this for a while (I noticed it on July 6).

**Comment by arkon** [comment]
You might need to uninstall that extension first.

**Comment by alessandrojean** [comment]
Just uninstall the MangaLivre extension and install the MangasProject one, as the MangaLivre catalog was incorporated in the current version of MangasProject. You might need to restart the app, but you won't even need to migrate your titles after that.

**Comment by TemptingBadger** [comment]
Thanks guys, after uninstalling MangaLivre, I was able to migrate to other sources. 
My suggestion is to remove this source from the list as it is not working at all.
Again, thanks to much to everyone.

**Comment by alessandrojean** [comment]
It will be removed soon.

**Comment by TemptingBadger** [comment]
Ok, thank you.
