### ISSUE TITLE
mangarock issue

### ISSUE THREAD

**Issue by Syborg49** [inorichi/tachiyomi-extensions#1317]
Tachiyomi version : R1519, build date July 13th 2019
Extension : mangarock 1.2.12

Issue : still can't read any manga as it shows the following [error](https://ibb.co/SmHB9ZQ). Please check.

**Comment by arkon** [comment]
As @LuigiHarrisMario suggested in #1307:

> Update your library

**Comment by 7alanjack** [comment]
You could try going in library option and choose to migrate source and reselect mangarock. This worked for me.

**Comment by Syborg49** [comment]
Thanks @7alanjack. That worked!
