### ISSUE TITLE
[English] MangaTown

### ISSUE THREAD

**Issue by JanhrldI** [inorichi/tachiyomi-extensions#132]
[Site](http://www.mangatown.com/)

**Comment by LakotaGray** [comment]
I’ll second the request for this site. Through searching site for particular series, aside from Mangago which is being difficult at the moment, MangaTown has the next best selection for harder to find titles.

**Comment by LakotaGray** [comment]
Already seconded this one... Well I suppose I'll third it? nah that sounds dumb
