### ISSUE TITLE
[TMO] Recent Uploads

### ISSUE THREAD

**Issue by MerradOklom** [inorichi/tachiyomi-extensions#1332]
Currently the Recent tab for TuMangaOnline is showing only the newly added manga, it would be nice if it could show recent uploads too. I think this can be done using this:
https://tmofans.com/?page=1&uploads_mode=thumbnail#latest_uploads

**Comment by edgarMejia** [comment]
Cuando hice la extensión no vi ese apartado o no estaba, tratare de agregarlo ahora.

**Comment by MerradOklom** [comment]
@edgarMejia muchas gracias!

**Comment by MerradOklom** [comment]
@edgarMejia una consulta. Hay algunos mangas que tienen capítulos publicados por dos o más scans (por ejemplo Smokin' Parade, cap. 9 por Gotei Konoha y Ravens Scans), pero sólo es posible leer una versión de dicho capítulo (el que se publicó primero, en éste caso la versión de Gotei Konoha). ¿Hay alguna forma de poder separar los capítulos por scan? Si es factible abriré otro issue con relación a eso. 
Otra vez, gracias por tu tiempo.

**Comment by edgarMejia** [comment]
Trate de hacerlo pero no supe como, la app no te permite poner varias versiones del mismo capitulo, deberia ser una mejora que se haga en la aplicación principal, por lo que deberias solicitarla en su repo: [Tachiyomi](https://github.com/inorichi/tachiyomi)
