### ISSUE TITLE
[Source Request][Spanish] HeavenManga

### ISSUE THREAD

**Issue by MerradOklom** [inorichi/tachiyomi-extensions#1335]
Source: http://heavenmanga.com/

**Comment by waptik** [comment]
Does it have latest/updates page?

**Comment by MerradOklom** [comment]
@waptik Hi. It is more visible in the mobile page (http://m.heavenmanga.com/). As for the catalog, they don't have one, you have to use the search or filter for letter or genre (http://m.heavenmanga.com/alfabetico/)

**Comment by SnakeDoc83** [comment]
There's already an extension for this source.  There's also HolyManga which has the same content.

**Comment by waptik** [comment]
@MerradOklom  The latest chapters are both available on mobile and pc versions. Also http://heavenmanga.com/top/ seems to be for popular mangas.

**Comment by MerradOklom** [comment]
@SnakeDoc83 that's for heavenmanga.vip (English source)

**Comment by waptik** [comment]
> heavenmanga.vip

So you want Spanish source?

**Comment by SnakeDoc83** [comment]
Ah, my mistake.

**Comment by MerradOklom** [comment]
@waptik yeah, this is a Spanish source (it's mentioned on the title).

**Comment by waptik** [comment]
@MerradOklom okay. I hope you are aware some mangas don't have their chapter images displaying like http://heavenmanga.com/one-piece-hentai/ .
I'll work on it during weekend if no one has taken it by then?

**Comment by MerradOklom** [comment]
@waptik Yes, no problem. In fact I have no hurry. Thank you for taking your time.

**Comment by waptik** [comment]
@as280093 can I have the icons for heavenmanga?

**Comment by as280093** [comment]
@waptik 
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3443691/ic_launcher.10.zip)

Here are the icons

**Comment by waptik** [comment]
Thanks
