### ISSUE TITLE
Script cannot be converted to JSONObject

### ISSUE THREAD

**Issue by naegahosh316** [inorichi/tachiyomi-extensions#1336]
BUGS:
 Tachiyomi Version 0.8.4
This issue only happens for my mangarock source

![Screenshot_2019-07-23-23-24-48-803_eu kanade tachiyomi](https://user-images.githubusercontent.com/53223470/61724716-17136e00-ada1-11e9-94cf-665128f84e4b.png)

**Comment by naegahosh316** [comment]
When I click the chapters, this measage only shows up

**Comment by MerradOklom** [comment]
Some people in Discord recommends to clear the cache in settings and refresh the chapter list.
