### ISSUE TITLE
Nothing form ReadComicsOnline loads

### ISSUE THREAD

**Issue by jonasprokopf** [inorichi/tachiyomi-extensions#1339]
Tachiyomi version: 0.8.4
Read Comics Online version: 1.2.5

Attempting to load any chapter instantly gives the error message "page list empty".

**Comment by rama982** [comment]
Just testing the extension and tested 6 mangas, all loaded fine.

**Comment by MerradOklom** [comment]
Check response by neufel in #1023
Just follow his instructions if you haven't yet

**Comment by jonasprokopf** [comment]
I see, thanks.
