### ISSUE TITLE
[Source request] 1stkissmanga

### ISSUE THREAD

**Issue by Mechanical-sanity** [inorichi/tachiyomi-extensions#1347]
1stkissmanga would be great to add!

**Comment by SnakeDoc83** [comment]
It's in the Madara extension.

**Comment by Mechanical-sanity** [comment]
What's mandatory?

**Comment by SnakeDoc83** [comment]
There are extensions with multiple sources.  Madara is one of those
extensions, it includes many sources and 1st Kiss is one of them.
