### ISSUE TITLE
[Source request] webnovel

### ISSUE THREAD

**Issue by Mechanical-sanity** [inorichi/tachiyomi-extensions#1350]
webnovel has miracle doctor which I really want to read!

**Comment by as280093** [comment]
Webnovel is a paid app all chapters after certain chapter you need to unlock it so currently it's not possible
MangaToon has most chapters free try that app

**Comment by Mechanical-sanity** [comment]
Wheres mangatoon?

**Comment by as280093** [comment]
Here the icons
[webnovel.zip](https://github.com/inorichi/tachiyomi-extensions/files/3612688/webnovel.zip)

**Comment by Cwavs** [comment]
> Webnovel is a paid app all chapters after certain chapter you need to unlock it so currently it's not possible
> MangaToon has most chapters free try that app

Is it possible to do something like Toomics where paid chapters are locked until you buy them?
