### ISSUE TITLE
Trust Anchor not found for HentaiFantasy

### ISSUE THREAD

**Issue by LazyBlueTurtle** [inorichi/tachiyomi-extensions#1352]
Hi! As the title said an error pops-up when i try opening the catalogues for the extension HentaiFantasy. 
The full error string is the following : 
java.security.cert.CertPathValidatorExeption: Trust anchor for certification path not found.
I'll also send the image with the error
Tachiyomi version is 0.8.4
Extension version is 1.0.2
Is this error my problem or is something to do with the site? 
![Screenshot_20190728_185007_eu kanade tachiyomi](https://user-images.githubusercontent.com/53405615/62010285-6246cb80-b169-11e9-9ffb-f2e05b5a17c6.jpg)
Thanks in advance if you manage to solve the issue!!

**Comment by arkon** [comment]
Can you access the site from your browser? I think this error shows up if the country is blocking a site too.

**Comment by LazyBlueTurtle** [comment]
I just tried and yea i can enter the site from the browser

**Comment by arkon** [comment]
I can't reproduce this. Do you have some sort of VPN or data saver enabled?

**Comment by SnakeDoc83** [comment]
@arkon Closeable: Extension appears to be working.  User wanted to know if the issue was on his end or with the extension; seems like it is or was on his end.  They haven't responded to your question; so it seems like they're no longer interested in engaging here.
