### ISSUE TITLE
[MULTI-LANG]  Zahard

### ISSUE THREAD

**Issue by KrisKamweru** [inorichi/tachiyomi-extensions#1368]
(CATALOGUE) SOURCE REQUESTS:
Name: Zahard 
Link: https://zahard.win/

It's got raws, it's got fastpass chapters, and it's multilingual 
Perfect for what tachiyomi is, I think

**Comment by GiowGiow** [comment]
It is an awesome source! maybe I'll try building an extension if get some time this semester

**Comment by as280093** [comment]
Here the icons
[zahard.zip](https://github.com/inorichi/tachiyomi-extensions/files/3612644/zahard.zip)
