### ISSUE TITLE
【SOURCE REQUEST : ONEMANHUA chinese manga】

### ISSUE THREAD

**Issue by Andi234Pisces** [inorichi/tachiyomi-extensions#1369]
(CATALOGUE) SOURCE REQUESTS:
Link : https://www.onemanhua.com
nice to read chines manhua for update and not need premium to read, , free read and always update

**Comment by as280093** [comment]
Here the icons
[onemanhua.zip](https://github.com/inorichi/tachiyomi-extensions/files/3612632/onemanhua.zip)
