### ISSUE TITLE
Manhwa extensions request

### ISSUE THREAD

**Issue by kagenui** [inorichi/tachiyomi-extensions#1374]
(CATALOGUE) SOURCE REQUESTS:
Link : https://manhwa18.com/
Please add this Manhwa extensions website in catalogue

**Comment by dragonofdragons** [comment]
i would love to see this extension
it is like scanlation type site

**Comment by rama982** [comment]
i'm working on this

**Comment by dragonofdragons** [comment]
any progress?

**Comment by pavan3999** [comment]
this site using same theme as rawlh

**Comment by dragonofdragons** [comment]
is it possible to add extension?
hakuneko has this extension.

**Comment by rama982** [comment]
Actually i already finished the extension only icons left

**Comment by dragonofdragons** [comment]
the extension on hakuneku is not working Today  like it is downloading files in .bin format of 4 kb file instead of image file. I think the site owner did something to site. did you check your extension.

**Comment by joseph619** [comment]
Apparently Manhwa18 has changed their UI completely

**Comment by TheKarateNinja** [comment]
What happened to the source, can't be found anymore?

**Comment by happywillow0** [comment]
@TheKarateNinja I believe it now is merged into FMReader

**Comment by Craagh** [comment]
Help I do not know how please ?

**Comment by Craagh** [comment]
> @TheKarateNinja I believe it now is merged into FMReader

How? Please help
