### ISSUE TITLE
[SOURCE REQUEST] Zandy no Fansub

### ISSUE THREAD

**Issue by Orochi101** [inorichi/tachiyomi-extensions#1380]
Link: http://zandynofansub.aishiteru.org/reader/

**Comment by happywillow0** [comment]
Your lucky Zandy no Fansub uses FoolSlide for their reader. I just tested it out and it seems to be working. Let me update my branch and submit a pull request to add it to the foolslide list.

**Comment by Orochi101** [comment]
Thank you!
