### ISSUE TITLE
[Source Request] [English] Hotoon

### ISSUE THREAD

**Issue by as280093** [inorichi/tachiyomi-extensions#1385]
https://m.hotoon.app/
This site has some best hidden gems manhua which can't be found anywhere

**Comment by rama982** [comment]
Just take a view of site source, they use api with encoded values.

**Comment by as280093** [comment]
Here the icons
[hotoon.zip](https://github.com/inorichi/tachiyomi-extensions/files/3612618/hotoon.zip)

**Comment by happywillow0** [comment]
I just took a look at the site and I think they shut down. Google only shows old apps on apk mirror sites. Google play listing removed. 

Close this?
