### ISSUE TITLE
Cannot read pages after update to manga rock.

### ISSUE THREAD

**Issue by derekhearst** [inorichi/tachiyomi-extensions#1392]
BUGS:
When I open new anime after updating my extension.
Version 1.2.12 
Pretty sure the old version was 1.2.0

![Screenshot_20190812-161351__01](https://user-images.githubusercontent.com/12779264/62902231-3eb08300-bd1c-11e9-9979-5dc212d6285e.jpg)

**Comment by arkon** [comment]
#1385 1336
