### ISSUE TITLE
Cat(?) gifs in MRM

### ISSUE THREAD

**Issue by fatimagrace015** [inorichi/tachiyomi-extensions#1393]
in chapter 4 and 5 of "Kiraide Isasete" in mrm source the pages are cat-like gifs, the whole ch4 and 5 are like that while others seems to be working well. I checked the site and it's normal as usual. I encountered this gif on other manga chapter sometime ago (forgot what their titles)

Tachiyomi ver. 0.8.4
MyReadingManga ver. 1.2.2.1

**Comment by fatimagrace015** [comment]
[](url)
![Screenshot_2019-08-13-12-40-24-54](https://user-images.githubusercontent.com/39181806/62915632-bdaec580-bdc7-11e9-8de7-c47cf0794d82.png)

**Comment by happywillow0** [comment]
I just checked chapters 4 and 5 of Kiraide Isasete in a relative fresh install and they seem to be loading fine right now for me. Have you tried clearing the chapter cache to reload the pages (I'm assuming that is the function of the button)?

**Comment by fatimagrace015** [comment]
Oh. It worked. Thanks!
