### ISSUE TITLE
[Russian title] Nude moon. Broken

### ISSUE THREAD

**Issue by Pavkazzz** [inorichi/tachiyomi-extensions#1395]
Version: r1512

![IMAGE 2019-08-15 00:50:56](https://user-images.githubusercontent.com/3702034/63058945-be924500-bef6-11e9-8b42-82cb7352e603.jpg)

**Comment by Pavkazzz** [comment]
https://github.com/inorichi/tachiyomi-extensions/pull/973

**Comment by Tosterr1** [comment]
+
