### ISSUE TITLE
Catalog requests

### ISSUE THREAD

**Issue by HoneyBo** [inorichi/tachiyomi-extensions#14]
Can you add https://myreadingmanga.info/ and eventually http://mangatraders.biz/ (not sure if you can read online when logged in) please? Thank you!

**Comment by j2ghz** [comment]
(CATALOGUE) SOURCE REQUESTS: One source per issue, create more issues if you have more websites Check for duplicates, use search (in issues, not the global one) Put the name of the site as Title, replace this text with clickable link to the site

**Comment by inorichi** [comment]
Closing issues that do not follow the guidelines. Feel free to open a new one that complies with them.
