### ISSUE TITLE
Mintmanga and Readmanga don't update manga

### ISSUE THREAD

**Issue by vergiliablack** [inorichi/tachiyomi-extensions#1407]
Tachiyomi version: 0.8.4
Readmanga version: 1.2.12
Mintmanga version: 1.2.12

They cannot update new chapters of manga. It writes that all mangas are licensed. 
![Screenshot_20190821-231445_Tachiyomi](https://user-images.githubusercontent.com/54254874/63461449-b3e12e00-c469-11e9-90f5-28f1974409de.jpg)
![Screenshot_20190821-231542_Tachiyomi](https://user-images.githubusercontent.com/54254874/63461450-b3e12e00-c469-11e9-807a-3a1227491c99.jpg)
![Screenshot_20190821-231516_Tachiyomi](https://user-images.githubusercontent.com/54254874/63461451-b3e12e00-c469-11e9-969b-bf75cf731fc5.jpg)
![Screenshot_20190821-231643_Tachiyomi](https://user-images.githubusercontent.com/54254874/63461475-c22f4a00-c469-11e9-8305-e847c0796e60.jpg)

**Comment by arkon** [comment]
I think #1406 fixed this.
