### ISSUE TITLE
[enchancement]  zh: manhuadui extension can't process extra content

### ISSUE THREAD

**Issue by wrlssqi** [inorichi/tachiyomi-extensions#1413]
tachiyomi : v0.8.4
manhuadui extension : v1.2.3

For example, this manga https://www.manhuadui.com/manhua/zhongjiangchengweini/  has two content, listed below "章节列表" and “单行本列表”. But the extension can only fetch data in "章节列表" category. 

(contents in red box can be fetched, but not in red circle)
![image](https://user-images.githubusercontent.com/9946624/63589874-d778b580-c5dc-11e9-8f29-3ca5de932bc3.png)

**Comment by wrlssqi** [comment]
@feilongfl  @neverfelly  Could you guys handle this? THX!!

**Comment by wrlssqi** [comment]
Seems that this fix couldn't handle all conditions. 
Contents in "其它系列列表" can't be extracted in this manga [魔法使的新娘](https://www.manhuadui.com/manhua/mofashizhijia/)
Also, Contents in "番外列表" can't be extracted in this manga [家有女友](https://www.manhuadui.com/manhua/jiayounvyou/)
Is it possible to handle all these conditions?

**Comment by feilongfl** [comment]
I found that there may have several class for chapter list,I will test `chapter-list-\d+`

**Comment by SnakeDoc83** [comment]
`ul[id^=chapter-list]` is what you want to get the chapter list sections

**Comment by feilongfl** [comment]
sorry for late response,I've fix it.
thanks for @SnakeDoc83

**Comment by wrlssqi** [comment]
Thank you guys so much!!
