### ISSUE TITLE
Unparseable date: "" (at offset 0) in MRM

### ISSUE THREAD

**Issue by fatimagrace015** [inorichi/tachiyomi-extensions#1417]
So when I tried updating a manga in mrm there's a notice saying "Unparseable date: "" (at offset 0) in MRM" below and doesn't show the update. I tried doing it to other mangas as well but they're also the same. Site is okay though.

Tachiyomi ver: 0.8.4
MyReadingManga ver: 1.2.22.

**Comment by fatimagrace015** [comment]
[
![Screenshot_2019-08-24-22-45-43-29](https://user-images.githubusercontent.com/39181806/63639504-74634d80-c6c6-11e9-9f66-72513f2a19d8.png)
](url)

**Comment by yasnil03** [comment]
Just like mine. I tried to add some manga but there's no chapters to read.

**Comment by godemperorshooblers** [comment]
Same here.

**Comment by happywillow0** [comment]
Confirmed issue. I'm not sure if the change on the website is temporary or not. I'll see how quickly I can throw some code together.

**Comment by happywillow0** [comment]
All things considered, that was a quick fix. 
I need to go to bed now.

**Comment by yasnil03** [comment]
Can I ask? Why can't I download manga? The case is the download is ongoing but the pages is not working/processing. Help pls

**Comment by aurynluna** [comment]
I updated everything and even reinstalled the myr extension, but it still shows the same "unparsenable date" error.

**Comment by bbtora** [comment]
The PR is still open. Please wait before an update is pushed
