### ISSUE TITLE
Mangadex not showing all chapters

### ISSUE THREAD

**Issue by Porky623** [inorichi/tachiyomi-extensions#1418]
See the attached screenshot. On the Mangadex website there are all 1-118 chapters of Dr. Stone available, but in the app it skips straight from 3 to 118. I have already used the id: way to get access to the series, but this issue seems to happen with all other Mangadex series I try as well. I have Tachiyomi 0.8.4 and Mangadex 1.2.65.
![Screenshot_20190824-142541](https://user-images.githubusercontent.com/35199779/63641832-bf5b7180-c682-11e9-8e3a-a137c67cc45b.jpg)

**Comment by arkon** [comment]
Have you tried opening them on the site? They're probably linked to MangaPlus.

**Comment by Porky623** [comment]
Wait I actually think it might be the fault of Mangadex missing English translations, my bad. I'll close this issue, but could you recommend other extensions to read popular manga like Dr. Stone and Haikyuu?

**Comment by yambadr** [comment]
manga plus extension
