### ISSUE TITLE
Sense scans

### ISSUE THREAD

**Issue by mrinmy** [inorichi/tachiyomi-extensions#1420]
When opening the source in catalogue (after downloading the extension foolslide) i get this error

![Screenshot_2019-08-25-09-18-31-807_eu kanade tachiyomi](https://user-images.githubusercontent.com/54491293/63645479-d353b180-c71c-11e9-8b9e-2a4ba037aa01.png)

**Comment by happywillow0** [comment]
Ry in discord provided a great hint of what was happening. 521 is a web server down message. Not sure if the https is broken or not but I took it out and it should be working again.

**Comment by mrinmy** [comment]
Thanks for your reply but sense-scan still isn't working.

**Comment by mrinmy** [comment]
> Ry in discord provided a great hint of what was happening. 521 is a web server down message. Not sure if the https is broken or not but I took it out and it should be working again.

Thanks for your reply but sense-scan still isn't working.

**Comment by bbtora** [comment]
The PR is still open. Please wait before an update is pushed.
