### ISSUE TITLE
MangaCards extension is broken

### ISSUE THREAD

**Issue by k0rak0ra** [inorichi/tachiyomi-extensions#1425]
Tachiyomi : 0.8.4
MangaCards : 1.2.1

Clicking on any manga chapters from NANI? Scans and Valhalla Scans returns "HTTP error 404". Lists/covers updates fine, issue is only with reading chapters. Clearing chapter cache/cookies/database didn't help.

**Comment by Vesnyx** [comment]
I've already made a pull request (#1424) to fix it. Don't worry :)
