### ISSUE TITLE
[Issue] Myreadingmanga still doesn't work

### ISSUE THREAD

**Issue by aurynluna** [inorichi/tachiyomi-extensions#1426]
Most recent version for both. The extension was updated but the problem wasn't fixed unfortunately, it still stays "unparseable date" whenever you try to read any chapter.

**Comment by SnakeDoc83** [comment]
Try clearing your cache in settings > advanced and refreshing your library (pull down on a chapter list in MRM).

**Comment by aurynluna** [comment]
I have already tried both.

**Comment by happywillow0** [comment]
What version of the app and extension are you running? Version 1.2.23 should be latest with the update on the date parsing. 

Does it happen with all entries or just some? Are you looking at old bookmarked ones or new ones that are just being posted?

**Comment by aurynluna** [comment]
I'm using the version 1.2.23 and 0.8.4 for the app. It happens with all titles whenever I browse through the MRM catalogue, even old ones. If I go to the ones I've  bookmarked I can read them with no issue but if I try to refresh the chapters list, the unparseable error comes back. I don't  know what to do.

**Comment by aurynluna** [comment]
It shows: 

[Takagi Ryou] Aka x Koi [Eng]

August 26, 2019 To Comments

So it seems to be the same. I don't know anything about coding so I'm not of much help here.

**Comment by delllette** [comment]
Hello, i have the same problem since Friday and I already cleaned chapter cache and cookies.

**Comment by aurynluna** [comment]
Yes, I did. I've tried everything. I'm from another country so I don't know if that's  the reason.

**Comment by aurynluna** [comment]
But I can load the site just fine on a browse and I can load the old bookmarks from the MRM extension, so that doesn't  make sense.

**Comment by delllette** [comment]
@aurynlyna Same for me

**Comment by aurynluna** [comment]
I think I found the problem, in Settings/General, the default langague I was using was the system default (which was Spanish), so I switched it to English and that seems to have solved the issue for me.

**Comment by delllette** [comment]
Thanks @aurynluna I switched with english uk and it's working now.

**Comment by aurynluna** [comment]
That makes sense. Thank you so much for your time and your help. <3
