### ISSUE TITLE
Mangarock issue: chapters not loading despite using cache clearing fix from FAQ

### ISSUE THREAD

**Issue by BillNyetheRussianSpy1** [inorichi/tachiyomi-extensions#1429]
App Version: 0.8.4 
Mangarock extension version: 1.2.13 english
Android version: 9
Issue: Licensed manga chapters not loading

When I was trying to read Yotsuba from Mangarock today I encountered the Value <url> at 0 bug and used the fix posted by arkon#4275 in the FAq discord channel and reloaded the chapter list as per the fix's instructions. However, this brought up a new bug, which read this:
Value Manga is licensed at data of type java.lang.String cannot be converted to JSONObject

I tested out a few more mangarock manga and they worked after the chapter cache clearing. I assume this bug is only present with licensed manga like Yotsuba. 
Image is attached:
![20190826_112308](https://user-images.githubusercontent.com/54547322/63706617-e38f8d80-c7fd-11e9-83a0-9333567c3178.jpg)

**Comment by pavan3999** [comment]
that manga opening fine for me

**Comment by pavan3999** [comment]
> are you guys in the US by any chance?

nope, india

**Comment by ferdyfachrur** [comment]
Just happened to me too.

Manga uzaki chan asobitai.

Country Indonesia

**Comment by brassica77** [comment]
I have the issue as well.
No issue when using the Definitive app, but I noticed when I visited the Manga Rock website that many of my favorites are missing.
So what should I do? Use a VPN app, refresh the manga with issues, read at least one chapter, and then disable the VPN app?

**Comment by CarlosEsco** [comment]
closing this because MR is going away

**Comment by CarlosEsco** [comment]
nevermind guess they "closing" down

**Comment by SnakeDoc83** [comment]
My understanding is their app will remain so long as people are paying for it but their website will shut down.  If the web API access goes with it, that's a wrap unless we use their app's API access (someone on Github supposedly cracked it).
