### ISSUE TITLE
[Source Request] [Japenese] Rawdevart 

### ISSUE THREAD

**Issue by as280093** [inorichi/tachiyomi-extensions#1433]
URL : https://rawdevart.com
Language: Japanese

best site for new Japanese manga

**Comment by rama982** [comment]
i'm working on this

**Comment by as280093** [comment]
Thx
Here is the logo
[ic_launcher .zip](https://github.com/inorichi/tachiyomi-extensions/files/3549436/ic_launcher.3.zip)
