### ISSUE TITLE
[ Request source] Kiryuu (id) & komikindo (id)

### ISSUE THREAD

**Issue by hostkit** [inorichi/tachiyomi-extensions#1435]
Site: https://kiryuu.co
Lang: Indonesia

Site: https://www.komikindo.web.id/
Lang: Indonesia

Up to date and famous comic in Indonesia
Thanks

**Comment by arifr007** [comment]
@hostkit kiryuu done https://github.com/inorichi/tachiyomi-extensions/pull/1569
