### ISSUE TITLE
TuMangaOnline issue: all the chaprtes to all the manga have page that cannot be seen

### ISSUE THREAD

**Issue by AlexPuyol95** [inorichi/tachiyomi-extensions#1437]
App Version: 0.8.4
TuMangaOnline version 1.2.6 spanish
Android version: 7
Issue: i cann't see some page of manga

When i was trying reed eny chapter of eny manga some page cannot be seen, a button that say "retry" appears on the page but even though I press it i can not see it.

I tried to fix it uninstall the extension but it didn't work

**Comment by MerradOklom** [comment]
Parece ser solamente con los capítulos recientes, no he tenido problemas con mangas que tienen años de antigüedad. Por cierto, éste problema no afecta a la extensión de LectorManga, asi que por el momento recomiendo que usen esa o NineMangaEs.

**Comment by AlexPuyol95** [comment]
Tenes razón, fui a intentar leer mangas viejos y no había ningún problema en sus capítulos y solo eran en los capítulos nuevos o mangas nuevos, voy a hacer lo que decís y descargar esas dos extensiones. Igual espero que lo solucionen al problema ya que esta muy buena esa extensión porque hasta te permite revisar los nuevos mangas agregados a TuMangaOnline.

**Comment by edgarMejia** [comment]
Pueden darme nombres de series que les estan dando este problema, estoy tratando de replicarlo pero no he tenido mucha suerte, gracias.

**Comment by AlexPuyol95** [comment]
y no se man la verdad el problema empezó un día de la nada cuando algunos caps nuevos que salieron les faltaban paginas y desde ahí todos los nuevos caps de cualquier manga le pasaba igual, yo creo que deberías revisar porque hace eso ahora si antes no lo hacia

**Comment by MerradOklom** [comment]
@edgarMejia ocurre con mangas nuevos y capítulos recientes, algunas páginas no cargan, aquí un ejemplo:
![Screenshot_2019-08-30-07-52-53](https://user-images.githubusercontent.com/43864503/64015913-f35bea00-cafb-11e9-9b64-edbdc35c6d9d.png)

**Comment by edgarMejia** [comment]
Hace unos días actualice la extensión, he buscado ese manga y me cargan todas la paginas, asumo que los cambios que hice para poder ver los mangas recientes arreglo este problema, subire los cambios.
