### ISSUE TITLE
[French] MangaKawaii

### ISSUE THREAD

**Issue by pichu66** [inorichi/tachiyomi-extensions#144]
French site request: MangaKawaii

Thanks for your amazing job!

**Comment by cmalard** [comment]
https://www.mangakawaii.com/liste-mangas

**Comment by AmineI** [comment]
I'm almost sure that this one is powered by FoolSlide2. Anyones knows if the foolslide extension is compatible with foolslide 2 websites ? Would make the process easier

**Comment by AmineI** [comment]
That's definitely My Manga Reader CMS. Went to add support for it in that extension but they use the CloudFlare "I'm Under Attack" Protection, which prevents me to do so.

I'll see with them if they have plans to lower that protection, since it also blocks RSS feeds readers and basically anything that's not a browser.

**Comment by as280093** [comment]
new Url  [https://www.mangakawaii.to/](https://www.mangakawaii.to/)

**Comment by AmineI** [comment]
Looks like they aren't cloudflare ddos protected anymore, I'll check and see if I can add that soon(ish).

**Comment by AmineI** [comment]
Mangakawaii use a weird version of MMRCMS, with most endpoints renamed, but that seems to be the same functionality wise. After writing a few lines of site-specific code, like renaming "/manga-list" to "/liste-manga" and more, I decided not to add Manga kawaii in the big MMRCMS extension, but instead try to make a new one using the MMRCMS one as a template (I think it would be better than cluttering it with site-specific code as mangakawaii is really the only one to do that so far.)

Can't guarantee when, nor if I'll be able to, though.
