### ISSUE TITLE
Mangadex search not working again

### ISSUE THREAD

**Issue by Zaroz** [inorichi/tachiyomi-extensions#1446]
Tachiyomi v0.8.4
Mangadex v1.2.65
When trying to use just the search term 'summon' this happens in TY:
![mangadex search failure](https://user-images.githubusercontent.com/22653076/64071921-e568af00-cc4a-11e9-937c-1335769ce246.png)

Compared to doing the same on Mangadex website:
![online](https://user-images.githubusercontent.com/22653076/64071936-0d581280-cc4b-11e9-9282-b66e72d9369e.PNG)

it seems like the search function is broken.

**Comment by bbtora** [comment]
Mangadex has disabled search for guest users so you have to login.
Please follow the steps [here](https://tachiyomi.org/#mangadex-no-results) to start searching again.

**Comment by mqus** [comment]
I got lost following the link, [here](https://tachiyomi.org/help/faq/extensions/#no-results-when-searching) is the updated one for enabling mangadex search
