### ISSUE TITLE
[SOURCE REQUEST] fanfox.net

### ISSUE THREAD

**Issue by kanekihaise777** [inorichi/tachiyomi-extensions#1466]
Would it be possible to add this source? http://fanfox.net/

**Comment by SnakeDoc83** [comment]
Note for developers:

Site has the same layout as [Mangahere](http://www.mangahere.cc).

There's an age check on some manga, Freezing for an example; will need to set a cookie to get chapter list in some cases.

**Comment by kanekihaise777** [comment]
This site is actually mangafox butvthey changed urls

**Comment by CarlosEsco** [comment]
Yep it's mangafox
