### ISSUE TITLE
Toonily advanced search filters not working

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi-extensions#1470]
App and Extension version - r1521 / English 1.2.1 / Android 9

Advanced search filters give no results found.

Tagging dev @DarKCroX

**Comment by rama982** [comment]
tell how you produce the "no result found"

**Comment by bbtora** [comment]
I have mainly got the error while trying to enable completed under status.

**Comment by SnakeDoc83** [comment]
The Toonily website uses Madara.  So, the Madara extension could be used as a basis to fix this or simply add Toonily to Madara instead.
