### ISSUE TITLE
Mangapanda is not working

### ISSUE THREAD

**Issue by samanta-widjaja** [inorichi/tachiyomi-extensions#1484]
BUGS:
 mangareader & mangapanda 1.2.4. 
I open manga panda with opera and its work fine. but when i open through catalogue its said "Failed to connect to www.mangapanda,com/36.86.63.185:443"

**Comment by SnakeDoc83** [comment]
I just tried Mangapanda on 2 devices and it worked for me.  Could you try it again?  Could have been a temporary issue with the site.

**Comment by rama982** [comment]
Seems like his access is blocked by his internet provider

**Comment by samanta-widjaja** [comment]
but if its blocked by my provider, how can i still open it in the same device by using opera?

**Comment by rama982** [comment]
Well i'm also can open its on catalogue, so 2 people confirming it working now

**Comment by samanta-widjaja** [comment]
okay. sorry it is really blocked by my provider. dont know how opera do it,but i tried with chrome and it said its blocked. thanks everyone
