### ISSUE TITLE
Kimi no Suizou wo Tabetai error when trying to read/download

### ISSUE THREAD

**Issue by iKeiko** [inorichi/tachiyomi-extensions#1487]
Pixel 3 / Android 10 / Tachiyomi 0.8.4 / MangaDex 1.2.66

You can read it fine on the website and when in web view but it wont open in the app.

https://mangadex.org/title/21863/kimi-no-suizou-wo-tabetai
![Screenshot_20190909-171930](https://user-images.githubusercontent.com/26834071/64545787-b24cac80-d329-11e9-8f4b-aeb9465c08c5.png)

**Comment by arkon** [comment]
@iKeiko Which chapter is happening on?

**Comment by iKeiko** [comment]
@arkon I just tested a few and it seems to be all of them

**Comment by joseph619** [comment]
It works fine for me

**Comment by arkon** [comment]
Synced up on Discord; caused by AdGuard DNS.
