### ISSUE TITLE
Manga Rock extension uses search from website instead of from Mangarock app. 

### ISSUE THREAD

**Issue by DSeah17** [inorichi/tachiyomi-extensions#1489]
(CATALOGUE) SOURCE REQUESTS:
  One source per issue, create more issues if you have more websites
  Check for duplicates, use search (in issues, not the global one)
  https://www.mangarock.com/
BUGS:
  Tachiyomi Ver 0.8.4, Manga Rock English 1.2.14
Currently, the extension is using the search from the Manga Rock website instead of from the Manga Rock application. Manga Rock's application is more up to date than the website. This can be easily seen when you search for certain titles and it shows up on the app but not in the search bar on the website. However, doing a google search can help you find the link to the series.
Example:

Title: Migi To Dali
Author: Nami Sano

By searching on the Manga Rock app, you can easily find it and see that the rank is #6969 (heh). If you do a search through Tachiyomi extension, it brings up no results for both the author and the title. If you search on the Manga Rock website, you see that it doesn't come up as well and the author's Manga Rock page doesn't even have the author's works properly listed. (The author also did Sakamoto Desu Ga)

If you google search "Migi To Dali Manga Rock", a link appears for the title but when you click on it, it's stuck in a endless load. This shows that the website is not as updated as compared to the application.

I also did a manual search by rank in the Tachiyomi app where I browsed the Manga Rock catalogue and sorted it by rank and jumped to the 6k - 7k rank filter. The title was missing there as well and I could find #6968 and #6970 but there was no #6969.

This means that a lot of manga, especially less well-known ones, cannot be found in Tachiyomi and can only be found on the Manga Rock app itself.

I'm not sure how this can be fixed as I do not know the inner workings of this app. Thank you for reading.

**Comment by SnakeDoc83** [comment]
The website, and by extension Tachiyomi, doesn't show licensed manga.  I'm guessing Migi To Dali is licensed but usually the page would say that instead of being stuck in a loading loop.

The MR app doesn't have that limitation, it shows all manga regardless of licensing status.  In order to use the API it uses the app would need to be cracked/reverse-engineered.

**Comment by samanta-widjaja** [comment]
beside i heard they're closing down?

**Comment by DSeah17** [comment]
@SnakeDoc83 I see, thank you for the quick reply.
@samanta-widjaja I don't know about that but a quick search shows something to that effect while some people are just saying that some manga cannot be shown in certain countries only.

Anyway, what site do you guys use then? I'd like to change to another site if Manga Rock has restrictions.

**Comment by arkon** [comment]
No intention of fixing this considering MangaRock is on the path of deprecation.
