### ISSUE TITLE
MangaHere won't fetch any images 

### ISSUE THREAD

**Issue by TheOnlyZii** [inorichi/tachiyomi-extensions#149]
So apparently Mangahere stopped working again. 
This time it won't fetch any images but everything apart from that still working fine 

Using Dev Build r1302

**Comment by CarlosEsco** [comment]
i dont have any issue with this check with regular and dev builds.  Please try steps here

https://github.com/inorichi/tachiyomi/wiki/Source-problems

**Comment by CarlosEsco** [comment]
If this isn't an issue anymore can you please close?
