### ISSUE TITLE
[SOURCE REQUEST : Line Webtoon (Indonesian Language)

### ISSUE THREAD

**Issue by MikuDroid** [inorichi/tachiyomi-extensions#1492]
The site is https://www.webtoons.com/id , I know there's already webtoon extension for tachiyomi. So maybe instead of adding new extension, can we have a selection for selecting the language? Because every language afaik have different sets of comics.
![image](https://user-images.githubusercontent.com/22476406/64619305-1182ed80-d40c-11e9-8315-5f7fe658ebc9.png)

**Comment by arkon** [comment]
Potentially includes Portuguese, as mentioned in #1517
