### ISSUE TITLE
[Mangatensei] Pages not correctly listed

### ISSUE THREAD

**Issue by MerradOklom** [inorichi/tachiyomi-extensions#1495]
I don't particularly use this source, but while trying to read a manga I noticed that the pages were misplaced. For example the page 1 of this manga: https://www.mangatensei.com/chapter/1366168/1
It's page 22 on the app:
![Screenshot_2019-09-11-20-54-21](https://user-images.githubusercontent.com/43864503/64743894-ff6e8100-d4d7-11e9-9ca9-b2e9ff2bf6c7.png)

**Comment by rama982** [comment]
I tested and iya fine here, 
![Screenshot_2019-09-12-07-23-26-416_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/14274061/64744529-70d91e80-d52e-11e9-995c-08618519d627.png)
![Screenshot_2019-09-12-07-23-04-642_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/14274061/64744530-7171b500-d52e-11e9-8d50-1992d3021118.png)

**Comment by MerradOklom** [comment]
@rama982 I tried using VPN but still the same. It is not a big problem for me, I just opened the issue to keep track of it. Not really sure what it could be... By the way, I'm from Argentina if that's of any help.

**Comment by MerradOklom** [comment]
Seems like some of the library used to write the extension is not compatible with my old crappy phone Android version, so I'm closing this issue since it is not worth keeping it open.
