### ISSUE TITLE
Mangago source problem

### ISSUE THREAD

**Issue by LakotaGray** [inorichi/tachiyomi-extensions#150]
When selecting source Mangago there is an attempt before it displays error message
"Http 503 error"
I've attempted steps in source trouble section, verified issue on several personal devices with latest dev build r1304 and 6.6, as well as confirmed other users are having same issue.

**Comment by joseph619** [comment]
I have tried it on Galaxy Note 4 running Android 6.0.1 and Nexus 6P android 8.1. Mangago extension is broken, says 'HTTP error 503' here's a screenshot taken from my Note 4: [https://imgur.com/a/3OJ0Y](url)

**Comment by AerosAtar** [comment]
Could this be related to their Cloudflare DDoS protections? I know that can screw with various things.

Have you tried visiting the website in a browser first and then (if successful), trying the app again?

**Comment by joseph619** [comment]
Yes, I have tried browsing Mangago on Google Chrome browser on PC and Samsung browser on phone, works fine on both. Only the app is giving issues

**Comment by LakotaGray** [comment]
The cloudflare was present prior to it having stopped working. But it still could be. 

It appears the addresses for manga and chapters has been altered to use a random set of numbers instead of manga name/chapter/page

**Comment by joseph619** [comment]
So has any fix been found?

**Comment by LakotaGray** [comment]
I’ve been clearing caches and databases on both devices every other day or so to check, but as of yet I’ve seen no change. Error still pops up.

**Comment by CarlosEsco** [comment]
This requires an update in Tachiyomi main app.  I opened a pull request for it.  Also I dont know how you guys use this source its so slow  to load :-)

**Comment by LakotaGray** [comment]
Thanks @CarlosEsco! It’s working again and that’s very much appreciated! 

It’s def slower now, but it works. :). I use it for the quick updates and collection they have. They seem to have many manga not available anywhere else.
