### ISSUE TITLE
Not all doujinshi's are showing on latest / when you search for them with the source nhentai

### ISSUE THREAD

**Issue by MrAndre96** [inorichi/tachiyomi-extensions#1509]
When you search or compare the latest doujinsi's to the actual website there seems te be always some missing. Which you can only find once you search them with the id but not with the name. You have for example "(C96) [Otaku Beam (Ootsuka Mahiro)] Spiritual Lunch 3" which was not by the latest results and couldn't be searched by name inside the app, but could only be found when you searched with the id (id:285155).

The version I am using for nhentai is: 1.2.13
App version: r1518

**Comment by SnakeDoc83** [comment]
The example you gave is tagged as Japanese language on the site.  If you're browsing or searching from the English version of NHentai you won't see non-English doujinshi.  If you want to browse or search other languages, enable them in your catalog and do a global search.
