### ISSUE TITLE
[Site Request] Manga Rock

### ISSUE THREAD

**Issue by Thoasty** [inorichi/tachiyomi-extensions#151]
Would really appreciate it if this source is considered.

https://mangarock.com/

**Comment by rouji4256** [comment]
I would like this source to be added as well. With bato.to down and kissmanga (Shoujo Shuumatsu Ryokou) being a mess it is. I think this is the next best source.

I think madokami is good but due to its nature, should be excluded.

**Comment by ChaotikZ** [comment]
I also requested MangaRock some months ago.
https://github.com/inorichi/tachiyomi-extensions/issues/99

HQ scans, VERY organized, great selection of manga (even stuff not available on other readers), and knowing it's MangaRock's main source (an app that's been alive for more than 7 years on both android and ios) means it might be available for quite some time in the future.

I feel like it could be a great addition.

**Comment by ccrowles** [comment]
Seconded, I actually have to download for now the official mangarock app because they deleted many of the manga I was following on mangago and only mangarock right now still have them. Would love to go back on keeping only Tachiyomi.

**Comment by jsilvermist** [comment]
MangaRock seems like it could easily be the best source atm, would definitely like to see this added.

**Comment by CarlosEsco** [comment]
#99
