### ISSUE TITLE
[SOURCE REQUEST] : Line Webtoon (Portuguese Language)

### ISSUE THREAD

**Issue by nicker7** [inorichi/tachiyomi-extensions#1517]
Line Webtoon site has a translation area made by fans, and I would like to know if the possibility of adding the extension "Webtoon all" if not, patience

[Webtoon Translate](https://translate.webtoons.com/translate) 

I could not find a page of this with all of them in Portuguese, so it may not be possible to add this extension, but it costs nothing to ask.

**Comment by arkon** [comment]
Merging with #1492

**Comment by mook** [comment]
Unfortunately this would be the user translations; #1510 will not fix this, as it's closer to the French support (which is currently broken).
