### ISSUE TITLE
Golden Mangas duplicate chapters

### ISSUE THREAD

**Issue by nicker7** [inorichi/tachiyomi-extensions#1520]
BUGS:
  
When I open a chapter that should have 10 pages, it turns out to be 20. When I finish reading the chapter, I kind of read it again because of the duplicate.

**Comment by alessandrojean** [comment]
I thought this will not happen because I tested and everything was okay. Can you provide me the mangas and chapters that this are happening?

**Comment by nicker7** [comment]
all of these four that I opened look like this, so I guess it's with everyone.  try Stalker x Stalker as it is very short chapters, only 4 pages per chapter.

[Imagem no Google driver](https://drive.google.com/file/d/11rP7knhh0clp2PRo2SC8SZuYTOQ16hJi/view?usp=drivesdk)
