### ISSUE TITLE
Source RawLH not working on Android app

### ISSUE THREAD

**Issue by Hellscythe789** [inorichi/tachiyomi-extensions#1523]
The manga from RawLH always show a 'retry' message when loaded up on the RawLH extension version 1.2.11. When accessed on the website however, the manga load up with no issues. The version of Tachiyomi I'm using is 0.8.4.

**Comment by rama982** [comment]
no issue here, manga pages showed successfully, if you just update extension try clear cache. or clear tachiyomi data

**Comment by Hellscythe789** [comment]
that fixed it, tysm
