### ISSUE TITLE
Version 0.102.3 - ReadComicOnline 1.0.1 - F-Droid

### ISSUE THREAD

**Issue by raiskream** [inorichi/tachiyomi-extensions#153]
ReadComicOnline source no longer working. HTTP error 503, backups result in errors and comics not downloaded.

**Comment by CarlosEsco** [comment]
please try the latest release 0.6.7 should solve your issue.

**Comment by raiskream** [comment]
My mistake, the version i was using was 0.6.6, not 0.102.3 (that was the f-droid version). I've updated to 0.6.7 and it solved the issue :)
