### ISSUE TITLE
 add new source in Spanish

### ISSUE THREAD

**Issue by swordart16** [inorichi/tachiyomi-extensions#1535]
http://mangacasa.com
Android: 5.1
v.0.8.4

**Comment by as280093** [comment]
Here is the icon:
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3638514/ic_launcher.2.zip)

**Comment by swordart16** [comment]
I'm sorry, I apologize, I made a mistake, the new account in Spanish that I
really want you to add is: http: //mangadoor.com the reason is because some
chapters come out advanced

**Comment by swordart16** [comment]
I'm sorry, I apologize, I made a mistake, the new account in Spanish that I
really want you to add is:
http: //mangadoor.com
the reason is because some chapters come out advanced

**Comment by swordart16** [comment]
I'm sorry, I apologize, I made a mistake, the new source in Spanish that I really want you to add is: http: //mangadoor.com 
the reason is because some chapters come out advanced

**Comment by MerradOklom** [comment]
MangaDoor is already under the extension "My Manga Reader CMS". Although it is giving a 403 error as of late. Anyway, you can find Submanga and Mangas.pw (both Spanish sources) under the same extension, they look kinda similar.

**Comment by happywillow0** [comment]
MangaCasa is now redirecting to Tumangaonline

Tumangaonline I think is using MMRCMS so we can add it with the rest. 

I'm not sure how the source generator works though. 
`Triple("es", "Tumangaonline", "http://tumangaonline.co"),`
