### ISSUE TITLE
Mangachan Downloader error

### ISSUE THREAD

**Issue by DArkHekRoMaNT** [inorichi/tachiyomi-extensions#1545]
Tachiyomi 0.8.4
MangaChan 1.2.8

When I try to download manga from mangachan-source, I'm get notification about "Downloader" error:
`downloadsDir    ...y(getMangaDirName(manga)) must not be null`

Unfortunately, I don't known how to see full error.
Error appeared a few days ago.

**Comment by SnakeDoc83** [comment]
Use a different download directory.  Could be that you selected one that's protected or otherwise doesn't play well with Tachi.  This suggestion is going off of this issue being mentioned on Discord.
