### ISSUE TITLE
Manga hasu loading

### ISSUE THREAD

**Issue by fatimagrace015** [inorichi/tachiyomi-extensions#1548]
Some mangas in mangahasu has this blank rectangle with a loading. No matter how long I wait, it doesn't load. Even clearing cookies, cache and data base

Tachiyomi ver. 0.8.4
Manga hasu ver. 1.2.4

**Comment by fatimagrace015** [comment]
[
![Screenshot_2019-09-22-18-07-44-62](https://user-images.githubusercontent.com/39181806/65385723-7faca600-dd64-11e9-8826-31387c6cd0d4.png)
](url)

Like this

**Comment by ennui169** [comment]
Tachiyomi Version 0.8.4
Mangahasu 1.2.4

I'm having similar issues. Seems to be specific for some chapters, as earlier chapters of affected series load fine. I can read them on the web view just fine.

**Comment by happywillow0** [comment]
Found it!

var lstDUrls	= "W3sicGFnZSI6MCwidXJsIjoiaHR0cHM6XC9cL2ltYWdlcy53ZXNlcnYubmxcLz91cmw9bWFuZ2FkZXgub3JnJTJGZGF0YSUyRjgxYmVlYWJlZGFiNTY5NjNmYWJhNDVjNzI0ODBkODBlJTJGRjEucG5nIn0seyJwYWdlIjoxLCJ1cmwiOiJodHRwczpcL1wvaW1hZ2VzLndlc2Vydi5ubFwvP3VybD1tYW5nYWRleC5vcmclMkZkYXRhJTJGODFiZWVhYmVkYWI1Njk2M2ZhYmE0NWM3MjQ4MGQ4MGUlMkZGMi5wbmcifSx7InBhZ2UiOjIsInVybCI6Imh0dHBzOlwvXC9pbWFnZXMud2VzZXJ2Lm5sXC8/dXJsPW1hbmdhZGV4Lm9yZyUyRmRhdGElMkY4MWJlZWFiZWRhYjU2OTYzZmFiYTQ1YzcyNDgwZDgwZSUyRkYzLnBuZyJ9XQ==";
