### ISSUE TITLE
Add Login functionality to Mangadex extension

### ISSUE THREAD

**Issue by WasdeAsde** [inorichi/tachiyomi-extensions#1555]
Add login functionality to [Mangadex](https://mangadex.org) extension to bypass the DDOS protection. Could fix the search lockdown and some download issues.

**Comment by arkon** [comment]
#871

https://tachiyomi.org/help/faq/extensions.html#mangadex

**Comment by cdr9042** [comment]
> https://tachiyomi.org/help/faq/extensions.html#mangadex

the link is now 404
