### ISSUE TITLE
MyReadingManga forces to uninstall

### ISSUE THREAD

**Issue by fatimagrace015** [inorichi/tachiyomi-extensions#1557]
Happened yesternight. I thought I accidentally uninstall it so I reinstalled it. But it happened again- thrice the whole night and twice this morning.

Edit: okay, it disappears but would be back after a while then disappear again.

Tachiyomi ver. 1.8.4
MyReadingManga ver. 1.2.26

**Comment by fatimagrace015** [comment]
[
![Screenshot_2019-09-24-13-03-26-21](https://user-images.githubusercontent.com/39181806/65482463-c963d080-decb-11e9-937e-e80faa2e5873.png)
](url)

Happened again, see. It was there a moment ago but it suddenly disappeared without informing me.

**Comment by arkon** [comment]
Do you have some sort of antivirus or cleaner app?

**Comment by fatimagrace015** [comment]
Yes, I do.

**Comment by arkon** [comment]
Try removing those.

**Comment by fatimagrace015** [comment]
Oh, I can't. The only cleaner I have is the system cleaner. And if that's the problem this issue should've happened months ago but it didn't. Nothing happened before whenever I clean so

**Comment by fatimagrace015** [comment]
Oppo A37f. Android version is 5.1.1.

**Comment by happywillow0** [comment]
I think I know what is happening. I've been running some tests and may have isolated it down to one line or section. I may have introduced this bug from the filter parsing. 

The extension doesn't actually uninstall itself but rather seem to be crashing cleaning under specific circumstances. 

When normal, a okhttpclient grabs the home page and jsoup parses everything before passing it to the filterlist. Something breaks here when the network has a failure and I haven't been able to isolate and fix further just yet. 

Easy way to reproduce is turning on airplane mode. I'm assuming something crashes cleanly that the Tachiyomi app just bypasses loading the extension. 

I tried refactoring some code and providing null exceptions where the extension will stay on the list when offline but then the whole app crashes when you try to browse.

**Comment by arkon** [comment]
I'm not sure, but that's why I was hesitant to merge it after a similar issue where Guya was crashing the whole app too. If it isn't strictly necessary, hard-coded lists are perfectly fine.

**Comment by happywillow0** [comment]
I found the section on exception handling for Kotlin and Okhttp. A network error is is being property handled now with try and catch. 

It it does happen, it throws a null back and the rest of the section is has null handling as well. 

It took me a while to work it out but it works.
