### ISSUE TITLE
[Source Request][Japanese] Mangahato.com

### ISSUE THREAD

**Issue by MerradOklom** [inorichi/tachiyomi-extensions#1559]
Source: https://mangahato.com/

Also https://mangatiki.com/ seems to be scraping their content from them and the site structure is identical, maybe both can be added in one extension like Mangareader/MangaPanda.

**Comment by as280093** [comment]
[MangaHato.zip](https://github.com/inorichi/tachiyomi-extensions/files/3661999/ic_launcher.2.zip)
