### ISSUE TITLE
Unable to open this Manhua on app

### ISSUE THREAD

**Issue by Lovestar98** [inorichi/tachiyomi-extensions#1560]
Can be opened on the website but not on the app. The others from this same extension is working fine though. 

![Screenshot_2019-09-26-01-43-22-44](https://user-images.githubusercontent.com/55808462/65629835-b86baa00-e006-11e9-8f9e-7315877cf51d.png)

Source: Tohomh123, Version 1.2.1
App version: Tachiyomi 0.8.4

**Comment by SnakeDoc83** [comment]
I need to change a selector, getting 2 elements where it should only be 1.  I'll get to this after I've slept.

**Comment by Lovestar98** [comment]
Erm, is it supposed to work now?

**Comment by SnakeDoc83** [comment]
I've updated the code but it hasn't been accepted yet.  Once it's merged you'll get an option to update your extension and after you do that it should work.  You just have to wait until that happens.

**Comment by Lovestar98** [comment]
Ohh I see. Ty. 😄
