### ISSUE TITLE
Multiple extensions, same name

### ISSUE THREAD

**Issue by j2ghz** [inorichi/tachiyomi-extensions#157]
As @wopian noticed, some extensions have the same name
https://github.com/inorichi/tachiyomi-extensions/blob/7b2072e4df62554d559a890a02cfe8c2b600b64f/src/en/mangaeden/build.gradle#L5 https://github.com/inorichi/tachiyomi-extensions/blob/7b2072e4df62554d559a890a02cfe8c2b600b64f/src/it/mangaeden/build.gradle#L5

**Comment by CarlosEsco** [comment]
Does this matter?  It seems to be no different then when you have 1 extension with ALL language.  Each "source" shows up only under its language group.

**Comment by wopian** [comment]
@CarlosEsco this matters for extensions on F-Droid. Catalogues with same name on there are physically identical as you don't have the app ID or `ALL`/`EN`

**Comment by CarlosEsco** [comment]
Is fdroid officially supported anymore? With the switch to using GitHub to host the apk?

**Comment by CarlosEsco** [comment]
Also any others besides mangaeden with this issue?

**Comment by wopian** [comment]
@CarlosEsco PervEden. 

Will take a guess and say they're not supported anymore, as extensions shown as installed were downloaded within Tachiyomi with a mismatched signature for the available versions. `all.mangadex` is not there either.

**Comment by j2ghz** [comment]
I will remove extensions from the fdroid repo as soon as github hosting hits stable. They are broken and not updating again anyway.
