### ISSUE TITLE
MangaDex blocking certain manga from general public (error 451)

### ISSUE THREAD

**Issue by de-odex** [inorichi/tachiyomi-extensions#1576]
https://mangadex.org/manga/33691/ returns an error 451 (Unavailable For Legal Reasons) when opened in tachiyomi or opened while not logged in to mangadex (may be also when logged in as it is hidden without certain permissions accdg to ZaneAU)
![image](https://user-images.githubusercontent.com/11498305/65816653-0f54c780-e231-11e9-9f1f-eb0f879a3928.png)
![image](https://cdn.discordapp.com/attachments/349436576037732355/627483358645059595/unknown.png)

**Comment by metroid112** [comment]
I thought the MangaDex extension required to log-in to work properly anyways?

**Comment by de-odex** [comment]
@metroid112 it does, but afaik the loader does not use login details so you get a 451
