### ISSUE TITLE
MangaDex not selected catalog languages upload dates affecting "Last Updated"

### ISSUE THREAD

**Issue by loocool2** [inorichi/tachiyomi-extensions#1577]
App Version;: r1524
MangaDex Extension Version: 1.26.67

To elaborate on this issue, languages that the user has not selected affects the order of the catalog they've selected.

Examples:
I think the intended order should be 
1. manga1 (last updated in English)
2. manga2 (last updated in English)
3. manga3 (last updated in English)

currently, it's 
1. manga1 (last updated in Spanish)
2. manga2 (last updated in English)
3. manga 3 (last updated in french)
4. manga4 (last updated in English)

**Comment by arkon** [comment]
Is this the same thing as https://github.com/inorichi/tachiyomi/issues/2217 , or is this talking about the "Latest" catalogue?

**Comment by joseph619** [comment]
Yes it is. It's caused by Mangadex which doesn't respect the languages enabled/disabled in Catalogues. Thus it breaks Last updated sorting in My Library by updating chapters of disabled languages.

**Comment by happywillow0** [comment]
@joseph619  Just to be sure we are talking about the same page, when you go to Catalogues, are you pressing "Latest" or "Browse"? 

If you are talking about "Latest" you can select the languages you want to display in the MangaDex settings via webview. Changing the chapter languages on the website will pre-filter the results meaning the "Latest" view is in the correct order for you and your language. 

![Screenshot_20191017-222900](https://user-images.githubusercontent.com/45346080/67061394-2e5ac100-f12e-11e9-8e15-e288768a7695.png)

**Comment by joseph619** [comment]
By Catalogues I meant sources on top right (where you enable/disable extensions), not Latest or Browse.

**Comment by MerradOklom** [comment]
I used to have Spanish and English chapters enabled on the site but while browsing "Latest" in MangaDex EN I would often encounter updates for Spanish chapters. So now I only filter English chapters to avoid the confusion.

**Comment by arkon** [comment]
Potentially related to #1215

**Comment by AriaMoradi** [comment]
Is this still relevant (too)?
#1215 was closed

**Comment by joseph619** [comment]
It's been fixed since Latest chapter was added.
