### ISSUE TITLE
[Source Request][English] Boommanga.com

### ISSUE THREAD

**Issue by KuroViLolitannia** [inorichi/tachiyomi-extensions#1578]
https://www.boommanga.com/

Has some webtoon not available in other sites

**Comment by waptik** [comment]
Do you have the url where mangas can be viewed on the web or an api url?

**Comment by KuroViLolitannia** [comment]
Yes, it's from here https://m.boommanga.com/category

You can see their website by using the mobile version too the https://m.boommanga.com/
