### ISSUE TITLE
MangaPark issue: Broken covers in Latest

### ISSUE THREAD

**Issue by BloodOath08** [inorichi/tachiyomi-extensions#158]
When browsing 'Latest', most of the covers are completely broken. This doesn't happen in 'Browse'.
![screenshot_20180116-023953](https://user-images.githubusercontent.com/32828655/34952996-4a953428-fa67-11e7-9d18-3f42deee5ae4.png)

**Comment by LakotaGray** [comment]
Beyond the broken covers, which also happens to me, the images within any chapter of any manga all fail to load and display the retry button on every page. This occurs in both 0.6.7 and r1317 on  both my android devices running 4.4.4 and 5.1.1
