### ISSUE TITLE
[French] Scantrad.fr

### ISSUE THREAD

**Issue by Zwoider** [inorichi/tachiyomi-extensions#1582]
Link : https://scantrad.fr/

The main french website on Tachiyomi Japscan is having more and more issues lately, it was down for two days, things like that, and since the last request for Scantrad is from 1 year ago on the last page it probably won't be done + the quality is better on Scantrad imo.

**Comment by SnakeDoc83** [comment]
>since the last request for Scantrad is from 1 year ago on the last page it probably won't be done 

Not a valid reason to open another issue.  Someone commented on it 13 hours ago, people who are willing to work on it have or will take notice of it.

**Comment by arkon** [comment]
#414
