### ISSUE TITLE
Kill Six Billion Demons

### ISSUE THREAD

**Issue by emidelgado01** [inorichi/tachiyomi-extensions#1588]
There is a webcomic called Kill six billion demons ([www.killsixbilliondemons.com](https://killsixbilliondemons.com/)) 

It is a very popular webcomic and it would be awesome if you could create a plugin for this website.

Thank you very much!

**Comment by as280093** [comment]
Here is the Icons
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3674823/ic_launcher.2.zip)

**Comment by metroid112** [comment]
Would love to have this extension too

**Comment by AriaMoradi** [comment]
is the text on the bottom of each page important?
if it is I don't think there is any way to replicate it on the app

**Comment by emidelgado01** [comment]
It adds lore to the story, they are like pieces of a seudo-bible of that universe. It's not fundamental to understand the story, but it certainly adds to the experience.

**Comment by AriaMoradi** [comment]
well still with the current structure, we cant add flavor text to manga pages.
@SnakeDoc83 am I correct?

**Comment by SnakeDoc83** [comment]
You can use a service to make images from text--see xkcd.  I don't think it's something we really want to encourage, but it's doable if really need be.  There's also the idea of building a bitmap programmatically but that's a questionable route.

**Comment by AriaMoradi** [comment]
then it could be planned for the next version of the extension
