### ISSUE TITLE
[source request] ddmmcc [Chinese]

### ISSUE THREAD

**Issue by 1608637229** [inorichi/tachiyomi-extensions#1590]
url : http://ddmmcc.com/
A free online comics website.

**Comment by as280093** [comment]
Redirects me to http://ddmmcc.com/

**Comment by 1608637229** [comment]
> Redirects me to http://ddmmcc.com/

It looks like the same website

**Comment by 1608637229** [comment]
> Redirects me to http://ddmmcc.com/

You can  use this URL.Their content is the same

**Comment by as280093** [comment]
Here is the Icons based on ddmmcc 
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3675229/ic_launcher.3.zip)

**Comment by 1608637229** [comment]
> Here is the Icons based on ddmmcc
> [ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3675229/ic_launcher.3.zip)

https://github.com/inorichi/tachiyomi-extensions/pull/1214
These two websites look the same.So I closed this  issue.
