### ISSUE TITLE
Mangarock 1.2.14 Issue

### ISSUE THREAD

**Issue by zyzzyvo** [inorichi/tachiyomi-extensions#1599]
I can't search, can't update and can't do anything
![Screenshot_2019-10-02-21-48-27-562_eu kanade tachiyomi](https://user-images.githubusercontent.com/56079643/66050030-06306700-e55f-11e9-8fa9-6147fb3820da.png)

**Comment by arkon** [comment]
Maybe they're finally bringing it down?

**Comment by joseph619** [comment]
It works fine for me.

**Comment by rama982** [comment]
It works fine for me too.

**Comment by arkon** [comment]
Same for me, actually. Potentially a network issue?

**Comment by zyzzyvo** [comment]
i don't think its the network tho cause i tried several connections.

**Comment by joseph619** [comment]
f you get this error when opening MangaRock chapters, try clearing your chapter cache.

Chapter cache can be cleared by going to Settings → Advanced then pressing Clear chapter cache.

**Comment by zyzzyvo** [comment]
tried it but it says "Cache cleared. 0 files have been deleted" and still doesnt work

**Comment by joseph619** [comment]
Clear your app cache. Go to Settings -> Apps > Tachiyomi > Storage then clear cache, then go back and click Force Stop

**Comment by zyzzyvo** [comment]
Thanks. Its working now.

**Comment by SnakeDoc83** [comment]
This can be closed.
