### ISSUE TITLE
[Bug] Japscan(FR) : Search bar removed -> "Not a JSON Array: null"

### ISSUE THREAD

**Issue by o01210o** [inorichi/tachiyomi-extensions#1618]
### Device information
* Tachiyomi extension version: 1.2.12
* Tachiyomi version: 0.8.4
* Android version: 8.00

## Steps to reproduce
1. Go to the Catalogue and select Japscan
2. Type a manga name in the search bar

### Expected behavior
Display the manga(s) you search

### Actual behavior
The message : "Not a JSON Array: null"

### Other details
https://github.com/inorichi/tachiyomi-extensions/issues/1618#issuecomment-540873227

**Comment by SnakeDoc83** [comment]
Seems like an issue on Japscan's side.  Give them some time to fix it; if they don't, we can change how Tachiyomi performs its search but it'll be an inferior approach more than likely.

**Comment by AidenPe4rce** [comment]
It bug all the time => infinite loading.
the other extensions do not have the last chapter whereas japscan yes (googel trad)

**Comment by o01210o** [comment]
I just noticed that they remove the search bar on their website :(

It seems that we need to return to the search method before this  : https://github.com/inorichi/tachiyomi-extensions/issues/663#issuecomment-445934060

**Comment by Mitia99** [comment]
Got the same issue..Infinite loading on Japscan search.Waiting for extension update

**Comment by o01210o** [comment]
I hope it will be fixed soon because we litteraly can't add any other manga to our library... :(

**Comment by SnakeDoc83** [comment]
With the new search method I've opened a PR for, it's important that you include the first word of a manga title when you do a search.  As an example, if you were trying to search for "Tales of Demons and Gods", searching for "Demons and Gods" wouldn't return results but "Tales of Demons" would.
