### ISSUE TITLE
[Feature Request] Source name : chaptermanga.com (english extension)

### ISSUE THREAD

**Issue by nurananto** [inorichi/tachiyomi-extensions#1620]
Hai... can you add chaptermanga for the extension
because it has fast update, complete chapter (like assassins pride, boku no kanojo sensei etc) which is missing in majority english extension

here's the url : https://chaptermanga.com/

Thanks before

**Comment by happywillow0** [comment]
The chapter list is not on the manga page but rather fetched off of another url.

I'm having trouble figuring out how to process the following code as my testing at https://reqbin.com/ isn't working 

```
 $(document).ready(function () {
            $.ajax({
                type: 'post',
                data: {
                    manga_slug : 'a-returner-s-magic-should-be-special-manga',
                    manga_id : '452',
                },
                dataType: 'html',
                url: 'https://chaptermanga.com/get-chapter-list',
                success: function (response) {
                    $('.chapter-list').html(response);

```

**Comment by SnakeDoc83** [comment]
I'm working on this as part of a multi-source extension. The two data variables get used in a `RequestBody` but you also need some headers to properly make the request.
