### ISSUE TITLE
[Bug] Manhuagui : Some mangas could not load chapter/IP get blocked when update library

### ISSUE THREAD

**Issue by accs1234** [inorichi/tachiyomi-extensions#1623]
2 bugs in one issue
### Device information
* Tachiyomi extension version: 1.2.1
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. Find a manga (ex:家有女友(https://www.manhuagui.com/comic/12912/)) from manhuagui and add it to my library
2. Tap this manga in my library and change to CHAPTERS tap to load chapters

|

1. Find some mangas and add them to my library from manhuagui
2. Update my library

### Expected behavior
Chapters should be loaded | My libarry should be updated

### Actual behavior
No Chapters found  | The ip get blocked and could not access manhuagui

### Other details
For bug 1: Guess that the reason may be the age restriction of the website. You may find that when you enter the link above(https://www.manhuagui.com/comic/12912/) for the first time, you need to comfirm that you are over 18, or the chapters list would not be shown. In fact, lots of such mangas could be found, but none of them could load chapters.
For bug 2: Confirm that it is a IP restriction, because you could access manhuagui in a minute if you change your IP with a VPN or something else. In another manga app I use, the similar step (update library) would not cause to IP block.

**Comment by musouking** [comment]
#1759

**Comment by musouking** [comment]
#1759 有开发者回复

**Comment by SnakeDoc83** [comment]
Closed via https://github.com/inorichi/tachiyomi-extensions/pull/3556
