### ISSUE TITLE
[Bug] Hanhankuman:unable to load thumbnails

### ISSUE THREAD

**Issue by ShiroSakurairo** [inorichi/tachiyomi-extensions#1624]
### Device information
* Tachiyomi extension version: 1.2.2
* Tachiyomi version: r1525
* Android version: 9.0

## Steps to reproduce
1.Add comics from hanhankuman to My library
2.Back up the My library list
3.Clear tachiyomi's data storage
4.Pour the contents backed up in step 2

### Expected behavior
Comic thumbnails load normally

### Actual behavior
Comic thumbnails are not loaded at all and cannot be replaced manually

### Other details
Backup import comics can't display thumbnails anyway, other comics can load thumbnails normally.

**Comment by joseph619** [comment]
What's bookshelf?

**Comment by ShiroSakurairo** [comment]
@joseph619 Wrong word, Edited
