### ISSUE TITLE
[Meta] Support apis to login in some comic source

### ISSUE THREAD

**Issue by lfkdsk** [inorichi/tachiyomi-extensions#1627]
###  Why/Project's Benefit/Existing Problem
(explain why this should be added)
I am writing a comic plugin for tachiyomi. However, I noticed that many comic resources require login or other verification methods to obtain.
Maybe we need to provide a fixed page to allow the user to log in to a plugin and store the corresponding token or other authentication data.

**Comment by SnakeDoc83** [comment]
@arkon Wouldn't this be covered by webview?  If not, wouldn't this need to be handled through the main app?

**Comment by CarlosEsco** [comment]
It is supported through webview.  but having a native solution would be ideal.  Previous versions has batoto support with native login but thats because the source was internal

**Comment by arkon** [comment]
I'm wondering if we should expose `LoginSource` or just make the app's UX in redirecting to webview when needed clearer.

**Comment by arkon** [comment]
Will work on improving the UX in the main app to point towards webview when needed.
