### ISSUE TITLE
[Source Request] HBrowse

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi-extensions#1630]
### Source Website
The website for this source can be found [here](https://www.hbrowse.com/).

### Other Details
This extension is already in-built in the Tachiyomi-EH fork, so I *suppose* it should be easy to implement it as a separate extension as well. I'd really appreciate it, thanks.

**Comment by SnakeDoc83** [comment]
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/1174

TachiyomiEH uses some custom stuff for this source, won't be a straight port.
