### ISSUE TITLE
[Bug] wuxiaworld.site : not working in madara extension

### ISSUE THREAD

**Issue by tyme2tb** [inorichi/tachiyomi-extensions#1636]
### Device information
* Tachiyomi extension version: 1.2.17
* Tachiyomi version: 1528
* Android version: 9

## Steps to reproduce
1. Try to load latest from wuxiaworld

### Expected behavior
Shows manga

### Actual behavior
Nothing returns. Just a blank page. Same result of I do the browse option, but that actually says "no results found"

**Comment by tyme2tb** [comment]
It does appear to download new chapters and be catalog searchable, just can't browse.

**Comment by SnakeDoc83** [comment]
Probably need to change the requests to tag/webcomic from tag/comic, they've changed it back and forth a couple times now.  I'd do it myself but I'm away from home until Sunday.

**Comment by SnakeDoc83** [comment]
This can be closed.
