### ISSUE TITLE
Install extensions without installing app.

### ISSUE THREAD

**Issue by RaXorX** [inorichi/tachiyomi-extensions#1639]
Possible to install extensions without installing the apps? Basically just wondering if it's possible for the extensions to be installed within the app without having to install an app for it.

I saw that previously extensions came within the app itself. The option to download individual app is good but still would have loved that I wouldn't just have to install another damn application just to install another extension. 😢

**Comment by arkon** [comment]
What's wrong with having another application? It doesn't show up in your app drawer.

**Comment by joseph619** [comment]
Extensions are not executable nor they take up much memory. Also built in extensions are against Tachiyomi's basic philosophy, that's why they have been removed.

**Comment by MerradOklom** [comment]
The in-built extensions were removed because if one broke you would need to release a new version of the app with a fix everytime it happened. Extension are more convenient and easy to maintain.

**Comment by RaXorX** [comment]
@arkon How about loading loose/unpacked extensions from storage?
Put simply, extensions don't get packed within tachiyomi neither as an apk and just load those extensions in tachiyomi from external storage. 

"What's wrong with having another application? It doesn't show up in your app drawer."
Nothing's wrong, whenever I look at the installed applications list and seeing the whole list which is already large enough, it just gets redundant when you have applications which are addons for different apps. For example, I have 15+ different extensions running for tachiyomi. Not to mention, it'll also save from the compiling of different apks and maintaining them eventually.

**Comment by arkon** [comment]
I'm not sure if you're familiar with how Android apps work, but I'm not sure if that's actually feasible?

**Comment by RaXorX** [comment]
Yeah I am not familiar with how android apps work. I guess that's the reason why themes and other icon packs usually come as an installer rather than a file(s) downloaded and integrated into the app itself. But apparently, that's why the android/data and android/obb folders are for. Things get downloaded from the dev's/app's servers and they are integrated into the apps. Again you're right, I have no understanding about how android apps works, might look into it one day if not now 😅

Either ways, it's not just with tachiyomi but any other apps that provide addons in this similar fashion. Why wouldn't it be feasible though? Extensions will still be update-able on individual level separate from the app. Or would that not be the case, if it were even possible in the first place?
