### ISSUE TITLE
[Feature Request] manhwa18 : Changed Domain

### ISSUE THREAD

**Issue by lucasrs9** [inorichi/tachiyomi-extensions#1660]
Good day, 
the site manhwa18.com has changed to manhwa18.net if you can update this. 
Thank you!

**Comment by joseph619** [comment]
It hasn't actually changed domain, Manhwa18.com will host raws and regular manga, and .net will host English manhwa. Also, not all English manhwa has been transferred from .com to .net. Both sites will run side by side as per the owner
