### ISSUE TITLE
[Bug] Source Name : Short Description

### ISSUE THREAD

**Issue by MechaNarutoSucks** [inorichi/tachiyomi-extensions#1661]
### Device information
* Tachiyomi extension version: 1.2.19
* Tachiyomi version: r1531
* Android version: 9

## Steps to reproduce
1. Open wuxiaworld
2. Scroll all the way to the bottom

### Expected behavior
It should show all the series but only shows some.

### Actual behavior
When you scroll all the way to the bottom you get http 400 error.

**Comment by SnakeDoc83** [comment]
You were seeing all their manga, the 404 error was from trying to get 1 more page than there actually is.
