### ISSUE TITLE
[Source Request] Source sektekomik

### ISSUE THREAD

**Issue by emyrulzul** [inorichi/tachiyomi-extensions#1664]
### Source Website
The website for this source can be found [here] (https://sektekomik.com/).

### Other Details

source indonesia

**Comment by emyrulzul** [comment]
bro please add sektekomik

**Comment by happywillow0** [comment]
We have made some progress and figured out how we should proceed. 
Please continue to be patient as we work on the extension. 

@arifr007 Do you need any help adding the source to the factory? You still know the extension and the layout the best since you just wrote it up.
