### ISSUE TITLE
MangaFox or MangaTown

### ISSUE THREAD

**Issue by LakotaGray** [inorichi/tachiyomi-extensions#167]
The extension MangaFox nearly always says "Series is Licensed" so no chapters are available. However while looking through the site I noticed on each of the licensed series there's a link saying "read 'series name' now" When you follow the link it takes you away from MangaFox and to another website called MangaTown. I don't know if you'd be able to forward or alter the MangaFox extension to use MangaTown or if the coding would need to be wholly different?

**Comment by CarlosEsco** [comment]
Would need a new extension.  I didn't see the links you mentioned in mangafox but going to mangatown it has same issues where series is licensed its not available.  My guess is they are owned by same company

**Comment by CarlosEsco** [comment]
I would close this and just open a issue for [Site Request] MangaTown
