### ISSUE TITLE
Madara extension wuxiaworld doesn't show all the series

### ISSUE THREAD

**Issue by MechaNarutoSucks** [inorichi/tachiyomi-extensions#1672]
### Device information
* Tachiyomi extension version: 1.2.21
* Tachiyomi version: r1531
* Android version: 9-pie

## Steps to reproduce
1. Open wuxiaworld catalogue
2. And scroll for a bit and you'll see that not all the series are showing up.

### Expected behavior
All the series within the site should appear.

### Actual behavior
Instead only few show up.

### Other details
Even if you use search it won't work for example you can try to search empress's gigolo and it won't show up even though it shows up in the site.

**Comment by MerradOklom** [comment]
I think the extension only shows webtoons and filter out novels (yes, the one you mention is a novel).

**Comment by MechaNarutoSucks** [comment]
Lemme check

**Comment by MechaNarutoSucks** [comment]
Looks to be true thx for that.
