### ISSUE TITLE
[Bug]  MangaOwl: timeout

### ISSUE THREAD

**Issue by hajaulee** [inorichi/tachiyomi-extensions#1679]
### Device information
* Tachiyomi extension version: 1.2.1
* Tachiyomi version: `latest`
* Android version: 9.1

### Expected behavior
View `Latest`, `Browse`, `Search` from source MangaOwl

### Actual behavior
 `timeout` error was returned

**Comment by happywillow0** [comment]
MangaOwl may have had some temporary problems on the website. Have you tried again to see if it is working? 

Have you also tried visiting MangaOwl via your browser to make sure you can get to the website?
