### ISSUE TITLE
[Bug] Pururin : Tag/General Search not working

### ISSUE THREAD

**Issue by Kermiticus** [inorichi/tachiyomi-extensions#1689]
### Device information
* Tachiyomi extension version: Pururin 1.2.1
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. Click search filters
2. or Click search bar and type in a tag

### Expected behavior
This should have happened
Manga/doujin should come out in correlation to the searched tag
### Actual behavior
This happens instead
https://imgur.com/a/LiteZWV
### Other details
whenever i search a tag nothing pops up on the search bar, and the tag filter on the right is empty. its the only extension that does this for me all other seem to work fine, I've tried to clear cache cookies etc., uninstall and reinstall and nothing.

**Comment by happywillow0** [comment]
The filter list on the sidebar is incomplete and does not function. 

As for the search, the extension only passes along your search request to the website to preform the search. It is up to the website on how the search is preformed and results returned back. The search box on the website does not behave as you are expecting. Following your example, searching `bbw` on the website itself does not produce any results either.
