### ISSUE TITLE
[Source Request] Multi-source extension for Bulgarian translations

### ISSUE THREAD

**Issue by roshavagarga** [inorichi/tachiyomi-extensions#1690]
### Source Website
Shinshi Doumei Cross BG - http://sdc-bg.com/
Current projects - http://sdc-bg.com/Projects.aspx?cat=1
Completed projects - http://sdc-bg.com/Projects.aspx?cat=2
One-shots - http://forum.sdc-bg.com/viewtopic.php?f=39&t=4472 (download links noted as 'Свали' from Google Drive)
Abandoned projects - http://sdc-bg.com/Projects.aspx?cat=3
Future projects - http://sdc-bg.com/Projects.aspx?cat=4
Utsukushii - https://manga.utsukushii-bg.com/manga-list
Otaku.bg - http://ftp.otaku.bg/Manga-BG/

### Other Details
The first two links are translation groups, the last link is a translation group that has uploads for its translations, as well as translations by the former two groups.

**Comment by SnakeDoc83** [comment]
Shinshi Doumei Cross BG - I only see .rar files, no image pages.  Their "online reader" is MangaDex.

Utsukushii - looks like it could be added to MMRCMS

Otaku.bg - Again, I only see .rar and .zip files.

**Comment by roshavagarga** [comment]
@SnakeDoc83 
Shinshi Doumei Cross BG - yup, they only offer .rar files with png's or using Mangadex as an online reader.
Utsukushii - you can use the online reader or click the 'Изтегли' button (lower right) to download a zip file.
Otaku.bg - That's the link to the ftp. There is a reader within the website, located here: https://otaku.bg/?page_id=46

All three sources have limited manga coverage and update either with a few chapters monthly or in bursts, hence why I suggested grouping them together in 1 multi-source, if that's humanly possible and/or easy. Whatever works for you, I'd be glad just having access to these in any manner, their websites rarely seem to change, which at least means there wouldn't be that much to update on the extensions.
