### ISSUE TITLE
[Bug] Manghasu: Can't download

### ISSUE THREAD

**Issue by yasnil03** [inorichi/tachiyomi-extensions#1700]
Device information
* Tachiyomi extension version: 1.2.5
* Tachiyomi version: 0.8.4
* Android version: 9

Expected behavior
Download Mangas

Actual behavior
I can't download chapter, when i tried to download "attemp to invoke virtual method 'com.hippo.unfile" always appear.

**Comment by MerradOklom** [comment]
Read this if you haven't done it yet:
https://tachiyomi.org/help/faq/application/#why-do-i-see-attempt-to-invoke-virtual-method-com-hippo-unifile

**Comment by yasnil03** [comment]
Oh thank you😍
