### ISSUE TITLE
[Feature Request] manhwa18.net (Madara) :  HTTP ERROR 404 - Changed mangas link

### ISSUE THREAD

**Issue by lucasrs9** [inorichi/tachiyomi-extensions#1703]
manhwa18.net is presenting the **HTTP error 404** 
     
The link has changed, there is no more manhwa18.net/manga/namemanga is now manhwa18.net/manga-namemanga.html.  

Example: 
In the extension is sending to https://manhwa18.net/manga/a-killer-woman   _-->displaying the error: 404 Not Found_  

Now the link to the page is https://manhwa18.net/manga-a-killer-woman.html  _-->working normally_

**Comment by joseph619** [comment]
It appears than Manhwa18.net is not using Madara anymore
