### ISSUE TITLE
[Feature Request] manhwa18.net(Madara extension): HTTP 404 ERROR

### ISSUE THREAD

**Issue by fawadkhan121** [inorichi/tachiyomi-extensions#1706]

**Comment by fawadkhan121** [comment]
manhwa18. net should be fixed because many manhwa are not in manhwa18. com

**Comment by SnakeDoc83** [comment]
There's already an issue open about this.

**Comment by fawadkhan121** [comment]
oh ok sorry for the inconvenience i am new to github
