### ISSUE TITLE
[Feature Request] NHentai : Display pretty title

### ISSUE THREAD

**Issue by Xwilarg** [inorichi/tachiyomi-extensions#1711]
### What feature should be added to this source?
Currently, NHentai extension display the full title, for example for 161194, it will display:
```
[Yuizaki Kazuya] Tsuna-kan. | Tuna Can (COMIC Potpourri Club 2013-08) [English] [PSYN]
```
But if you look [at the API](https://nhentai.net/api/gallery/161194) there is a section called title->pretty, that would look like that:
```
Tsuna-kan. | Tuna Can
```
Since all mangas are ordered by title in alphabetic order in your library, taking the full title would put it in the 'Y' (because of the 'Yuizaki'), instead of the 'T'.
Others mangas also only display the title so I think it would unify it with the others.

**Comment by arkon** [comment]
I didn't even realize their API is back...
