### ISSUE TITLE
[Bug] Source Name : Short Description

### ISSUE THREAD

**Issue by princess15mm** [inorichi/tachiyomi-extensions#1716]
### Device information
* Tachiyomi extension version: 1.2.23 Madara (Mangakomi)
* Tachiyomi version: 0.8.4
* Android version: 8

## Steps to reproduce
1. Open Mangakomi
2. Error pops up

### Expected behavior
Cataloque to load and the capability to browse

### Actual behavior
Error pops up that says java.security.cert.CertPathValidatorException: Trust Anchor for cer...

### Other details
I've tried restarting the app, refreshing the cataloque, and have hit retry nothing has helped fix the problem though.

**Comment by haivp3010** [comment]
Mangakomi certificate expired. We could ignore the SSL error but then it's surely not best practice.

**Comment by happywillow0** [comment]
A SSL error is occurring because, Mangakomi is down currently. 
If you go into the website, it is loading the login page for Zabbix monitoring software.

**Comment by arkon** [comment]
Not much we can do here.
