### ISSUE TITLE
[Bug] Tohomh123

### ISSUE THREAD

**Issue by Reraru** [inorichi/tachiyomi-extensions#1720]
* Tachiyomi extension version: 1.2.2
* Tachiyomi version: r5313
* Android version: 9

Doesn't download or view. Says unexpected url. When I open in webview the chapter links don't work but when I open in web browser the chapter link works fine. 

This is also happening with pufei extension.

**Comment by happywillow0** [comment]
Do you have any specific manga that isn't working? I tested both Tohomh and pufei now and they both loaded ok from my internet connection.

**Comment by Reraru** [comment]
我是这家的孩子 this one

**Comment by happywillow0** [comment]
我是这家的孩子 on pufei is having issues on the main website:
图片载入失败

![not load](https://user-images.githubusercontent.com/45346080/67974193-5e06d000-fbe8-11e9-9067-3f3ba69d1352.PNG)

**Comment by Reraru** [comment]
Okay so I checked it out. It was removed due to copyright. All the links have been deleted. That's what they're saying.
