### ISSUE TITLE
[Bug] Mangabox: Mangakakalot manga doesn't load, broke library updates

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi-extensions#1726]
### Device information
* Tachiyomi extension version: 1.2.1
* Tachiyomi version: r1531
* Android version: 9

Most manga in Mangakakalot are broken, receiving various errors such as "No chapters found", "Did not find balanced marker at status", "Page list empty" etc. It also broke Library Updates.

**Comment by arkon** [comment]
Did you uninstall the other Mangakakalot extension?

**Comment by SnakeDoc83** [comment]
I have to make a couple changes, I didn't realize some of the manga on kakalot's site is hosted on a different domain.

**Comment by arkon** [comment]
Ah yeah, I was just looking at it. It loads some stuff from Manganelo IIRC, should just be overriding some methods to check for `http` prefixes.

**Comment by joseph619** [comment]
@arkon Yes I did, I uninstalled Mangakakalot first, then installed Mangabox.

**Comment by happywillow0** [comment]
@arkon There are a a bit more weirdness with the Mangakakalot website. I think we need to remove setUrlWithoutDomain from the manga urls as well because some manga (at least the latest manga "Under Prin" is redirecting to manganelo completely) and not just the chapter list

**Comment by joseph619** [comment]
Just updated the extension now, issue still not fixed. Still says "No chapters found" @arkon

**Comment by happywillow0** [comment]
Which manga are you looking at as an example?

**Comment by joseph619** [comment]
Solo Leveling, One Piece, Kimetsu No Yaiba, Iron Ladies, Kingdom etc

**Comment by arkon** [comment]
Clear chapter cache.

**Comment by happywillow0** [comment]
Shoot! I know why it is broken still. 

Because mangakakalot is redirecting to / merging with / something is happening with manganelo, look at [the source code of kimetsu no yaiba (view-source:https://mangakakalot.com/manga/kimetsu_no_yaiba)

They are doing a redirect. 
```
<!doctype html>
<html>
<head>
<meta name="robots" content="noindex,nofollow" />
<script>
         window.location.assign("https://manganelo.com/manga/kimetsu_no_yaiba");
      </script>
</head>
<body>
REDIRECT :
https://manganelo.com/manga/kimetsu_no_yaiba </body>
</html>
```

If you have a saved manga in the library, it tachiyomi has the manga.url already saved as `manga/kimetsu_no_yaiba` but when it tries to grab it for the chapter update, it doesn't find anything because it is "moved"
