### ISSUE TITLE
Manga-TR and Manga Adonis Fansub 

### ISSUE THREAD

**Issue by proxlavee** [inorichi/tachiyomi-extensions#1730]
### Source Website
Website can be found at https://manga-tr.com/ and https://manga.adonisfansub.com

### Other Details
Both of them turkish.

**Comment by MerradOklom** [comment]
As I told you before, Manga-TR is already available under the FMReader extension. 
![IMG_201911305_104831](https://user-images.githubusercontent.com/43864503/68029180-7680f400-fc95-11e9-9a8b-2ea15a3786c2.png)

**Comment by proxlavee** [comment]
What about https://manga.adonisfansub.com ?

**Comment by proxlavee** [comment]
> As I told you before, Manga-TR is already available under the FMReader extension.
> ![IMG_201911305_104831](https://user-images.githubusercontent.com/43864503/68029180-7680f400-fc95-11e9-9a8b-2ea15a3786c2.png)
What about https://manga.adonisfansub.com ?

**Comment by happywillow0** [comment]
Adonis Fansub looks like it is running on Madara but I'm getting a 401 currently in testing. Someone will have to work on it a bit more.

**Comment by proxlavee** [comment]
> Adonis Fansub looks like it is running on Madara but I'm getting a 401 currently in testing. Someone will have to work on it a bit more.

Yes we are using Madara

**Comment by proxlavee** [comment]
> Adonis Fansub looks like it is running on Madara but I'm getting a 401 currently in testing. Someone will have to work on it a bit more.

Which page are you getting 401 ?
