### ISSUE TITLE
Mangadex chapter number, scanlator group name, and an unreadable manga

### ISSUE THREAD

**Issue by Tokramon** [inorichi/tachiyomi-extensions#174]
Tachiyomi dev version: r1329
Mangadex extension version: 1.21

-----

When viewing manga labeled with both volume and chapter numbers, the app uses volume number to populate chapter number related fields.

For example, the "Last chapter" field in a manga's info tab displays the number of the latest volume instead. And if we change the display mode of the chapters (via overflow menu in the chapter tab) to "Show chapter number", it shows the chapters as "Chapter [VOLUME NUMBER]" instead.

-----

In the scanlator group field underneath chapter names, it displays the name of the user who uploaded the chapter, when it should display the scanlator group that translated the chapter.

Example: In Kami-sama no Ekohiiki, the app displays Tooko, the user, instead of Hachimitsu Scans, the group, as the scanlator.

-----

Lastly, the manga mentioned above is not readable with the Mangadex source for some reason. Clicking any chapter enters the viewer. The app displays the "Downloading..." message, fails after a while and shows the retry button.

The manga is readable in browser without any problems. No other manga I tried has the same issue. I've cleared the cache, user data, reinstalled the app and extension, and tried this on another phone, all has the same problem with just this one particular manga. 

-----

Also a general question: should this issue be split into multiple issues each containing one particular bug for ease of tracking, or is this acceptable?

**Comment by CarlosEsco** [comment]
last chapter is addressed with this pull request 
https://github.com/inorichi/tachiyomi/pull/1213

The rest im addressing in #170  i just didnt have time yesterday to do look into the scanlator, and chapter not reading.

In general i would do 1 per an issue unless they are related or caused by each other.

**Comment by CarlosEsco** [comment]
Latest dev and latest mangadex fix all this.  Please verify and close.  You might need to clear cache and cookies for the last updated number to refresh correct

**Comment by Tokramon** [comment]
Thanks, everything is working now. Apologies for not checking existing pull requests before opening this issue.
