### ISSUE TITLE
[Bug] Available extensions : Could not list available extensions

### ISSUE THREAD

**Issue by Max-Learning** [inorichi/tachiyomi-extensions#1746]
### Device information
* Tachiyomi extension version: 1.2.1~1.2.6 installed
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. Open app
2. Goto extension page

### Expected behavior
List all installed extensions and all available extensions

### Actual behavior
Only installed extensions are listed, other available extensions that haven't installed disappeared.

### Other details
Environment: Tested on both of my Huawei phones, and they failed to load via WiFi or cellular network.

I tried clear chapter chache, clear cookies ,reinstall the application and version 0.8.1, but did not work.

Installed extensions work as usual, but I cannot update these extensions.  One of my phone cannot receive the push of extension updates, while the other one cannot download them, even when they are connected to the same WiFi network.

I once successfully load the available extensions list when refreshing again and again, but it disappeared soon afterwards. All attempts to reproduce it failed.

Sorry for bad English.

**Comment by arkon** [comment]
Are you able to open GitHub on your phone? What country are you in?

**Comment by Max-Learning** [comment]
In mainland China, and I can open GitHub on both phone. I thought it may be blocked, but those extensions were accessible in October when I downloaded this app.

**Comment by Max-Learning** [comment]
And I managed to list the available extensions and even download some yesterday, but the connection only last for about 5 minutes after I noticed that.

**Comment by arkon** [comment]
Sounds more like an issue on your side, but could potentially be addressed in the main app via https://github.com/inorichi/tachiyomi/issues/2299
