### ISSUE TITLE
[Bug] Manganelo : Chapters have no date

### ISSUE THREAD

**Issue by Vaturobi** [inorichi/tachiyomi-extensions#1760]
### Device information
* Tachiyomi extension version: 1.2.4
* Tachiyomi version: 0.8.4
* Android version: 8.1

## Steps to reproduce
1. Download extension
2. Look at any manga

### Expected behavior
Chapters should be dated like in other sources

### Actual behavior
Chapters show no date

**Comment by arkon** [comment]
MangaBox supports MangaNelo including dates.
