### ISSUE TITLE
Extension under Madara not working

### ISSUE THREAD

**Issue by fam007e** [inorichi/tachiyomi-extensions#1769]
### Device information
* Tachiyomi extension version: 1.2.26
* Tachiyomi version: 0.8.4
* Android version: 7.0 (NRD90M XIAOMI REDMI NOTE 4X)

## Steps to reproduce
Opening the "Allporncomic" catalogue results in error even after force closing and opening the app. I've also tried restarting the phone before using the app. Although the individual comics of the aforementioned site is accessible from its page via webpage view NOT the catalogue "browse" or "latest" option.

### Expected behavior
Selecting the catalogue/extension should open all the comics of "allporncomic", but it shows error. (However, I can view individual bookmarked comics of that extension via web view)

### Actual behavior
Error message pops up: 
"java.lang.Exception:  Challenge not found"

**Comment by happywillow0** [comment]
I don't know exactly what is wrong. It did work for me in testing last night and this morning but I guess that wasn't it.
