### ISSUE TITLE
[Source Multimedia Bugg] Webtoons

### ISSUE THREAD

**Issue by amboris** [inorichi/tachiyomi-extensions#177]
(CATALOGUE) SOURCE webtoons:
webtoons source cant filter by genre nor popularity. and it does not list all content, you need to tip/search the name of the manhwa to find most of it, even some of the most populare ones "tower of god", "noblesse".

BUGS:
tachiyomi ver.0.6.8
webtoon extenion 1.0.1

the app or extention are unable to play multimedia manwha(audio,gif) like "chiller", "shriek" ect. 
error message "the page list is empty"

would be ultra great if you could make it happen to read those. the app from lineWebtoons itself is able to play those manwhas.

**Comment by TonyToscana** [comment]
1) The page's search doesn't let you filter by genre nor popularity. As for how it's implemented, LATEST show the manhwas from "Daily Featured", the column that matches the current day; BROWSE show the ones from "Popular", the column sorted by genre and ALL selected. The last one can be changed to show every manhwa but it wouldn't be sorted (try a blank search query).

2) AFAIK the app itself doesn't allow that kind of multimedia files.

**Comment by CarlosEsco** [comment]
closing due to what TonySoscana said
