### ISSUE TITLE
[Bug] KissManga: Constant "HTTP error 403".

### ISSUE THREAD

**Issue by aronshrv** [inorichi/tachiyomi-extensions#1772]
Samsung Galaxy S10 One UI 2 Beta 3
* Tachiyomi extension version: 1.2.9
* Tachiyomi version: 0.8.4
* Android version: 10

## Steps to reproduce
1. Open KissManga source manga
2. Attempt to read.

### Expected behavior
Chapter opened.

### Actual behavior
HTTP error 403

### Other details
I've cleared my cache and redid the Kissmanga captcha to no success. I cannot search the source in "catalogs" either. No updates as well

**Comment by arkon** [comment]
#1768
