### ISSUE TITLE
[Bug] manhwa18.net - Madara : New Chapters Not Loading

### ISSUE THREAD

**Issue by Thoasty** [inorichi/tachiyomi-extensions#1774]
### Device information
* Tachiyomi extension version: Madara 1.2.26
* Tachiyomi version: 0.8.4
* Android version: 9

Most new chapters of certain series are not loading recently. It goes to the retry screen. The chapter images don't load in the built in Tachiyomi browser or web view but they load properly in external web browsers like chrome. Examples are chapter 51 & 52 (Loser Team 201), 42 & 43 (Queen Bee) and 6 & 67 (My Office Ladies). Thanks.

**Comment by joseph619** [comment]
Chapters are not being downloaded either.

**Comment by happywillow0** [comment]
Manhwa18.net is currently part of FMReader as far as I can tell.  They were moved over 18 days ago as part of #1707 

That aside, the listed chapters seem to be working for me. They load and download without issue on my phone. 

Want to double check you have updated extensions or could it be a server side issue?

**Comment by Thoasty** [comment]
Thanks for checking. I have the latest version of Madara extension. I still cannot load those chapters within the app. I'm located in the US. More example chapters include 46 (Freshman) and 13 & 14 (Dead Land).

**Comment by SnakeDoc83** [comment]
@Thoasty You may be misunderstanding.  Having Madara won't help you, manhwa18.net isn't in Madara any more.  You need to install FMReader.

**Comment by Thoasty** [comment]
Ah I did misunderstand. I downloaded the FMReader extension and those chapters do indeed work. Thank you.
