### ISSUE TITLE
[Bug] NewToki : error 404 Not Found on search/browse 

### ISSUE THREAD

**Issue by officermeow** [inorichi/tachiyomi-extensions#1775]
### Device information
* Tachiyomi extension version: 1.2.9
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. Try to either browse catalogue or search for something

### Expected behavior
Should work as expected 

### Actual behavior
Popup with 404 not found shows up, nothing happens

### Other details
Can't 100% verify whether updates from NewToki work or not, I had none from NewToki today so I think they dont work either

**Comment by SnakeDoc83** [comment]
Go to the extensions tab and click on the NewToki extension.
Click "Override BaseUrl."
Enter "https://newtoki31.net" (without quotes) and click OK.
Restart Tachi, extension should work fine.

Note: You can override for "New Toki" or "New Toki (Webtoon)"--you can do either or both depending on which you use.
