### ISSUE TITLE
(Spanish) Extensiones de TuMangaOnline y Lector Manga no funcionan

### ISSUE THREAD

**Issue by Xtikma** [inorichi/tachiyomi-extensions#1777]
Saludos

Hace unos días TuMangaOnline habia empezado a tener problemas, entonces migre los mangas a LectorManga pero ahora ambas y a la actualidad (13/11/19) siguen con el mismo problema.

Todo manga y todos los episodios regresa un error HTTP error 404 despues de intentar cargar
![Imgur](https://i.imgur.com/9GlqjXs.jpg)

**Comment by MerradOklom** [comment]
Este problema ya está siendo discutido aquí: #1749

**Comment by Xtikma** [comment]
@MerradOklom  Oh gracias por la información, a esperar como evoluciona la situación. No habia visto el tema abierto
