### ISSUE TITLE
[Improvement request] Organize extension source per language

### ISSUE THREAD

**Issue by M2ck** [inorichi/tachiyomi-extensions#178]
Currently it's mess, it's impossible to know which languages are available for each extension source

**Comment by Kovaelin** [comment]
The naming conversion used to incorporate this. I'm not sure why it changed.

**Comment by cd0rw0** [comment]
Currently work in progress to integrated extension download into main app, current name change also to support that. since we in "migration period" its look mess, all become clear once new feature been integrated into main app.

**Comment by inorichi** [comment]
The extensions tab is organized by package name/language now.
