### ISSUE TITLE
[Bug] http error 403 kissmanga 

### ISSUE THREAD

**Issue by Scififan117** [inorichi/tachiyomi-extensions#1782]
### Device information
* Tachiyomi extension version: kissmanga
* Tachiyomi version: current
* Android version: marshmallow 

## Steps to reproduce
1. First Step open kissmanga source 
2. Second Step open individual manga from kissmanga saved to library 

### Expected behavior
This should have happened opened the chapter or shown books 

### Actual behavior
This happens instead crashes and s never loads

**Comment by arkon** [comment]
#1768

**Comment by Monkeyfan727** [comment]
I've had this issue for a week however after using the web view feature to attempt to read a chapter of a Manga then backing out realizing it was the wrong one the kiss Manga error code stopped popping up and that specific Manga updated as well this may be a work around I hope this helps
