### ISSUE TITLE
[Bug] Manwha18 : Manwha not loading.

### ISSUE THREAD

**Issue by SamAresOfficial** [inorichi/tachiyomi-extensions#1785]
### Device information
* Tachiyomi extension version: 1.2.1
* Tachiyomi version: r1532
* Android version: 9

## Steps to reproduce
Try to load chapters post-november 9th in Manwha such as Doumi Engsub Chap 17-20, Silent War Chap-55, Ajeossi Manwha Chap 33-34.

### Expected behavior
The chapter should load properly.

### Actual behavior
Retry buttons appear, and no matter how many times you hit it nothing loads. It seems to load rather quickly, but it doesn't seem to do anything.

### Other details
If you visit the website all of the chapters are in working condition and load instantly. I assume they changed something about the way their new uploaded chapters work, because older ones work perfectly fine.

**Comment by SnakeDoc83** [comment]
That extension is no longer supported.  Install the FMReader extension to use Manhwa18.
