### ISSUE TITLE
[Source Request] [Spanish] DoujinYang

### ISSUE THREAD

**Issue by Credits125** [inorichi/tachiyomi-extensions#1787]
URL:

[DoujinYang](https://doujin-yang.es)

**Comment by arkon** [comment]
Why are you recreating issues?

**Comment by rs3mk** [comment]
https://doujin-yang.es/

**Comment by as280093** [comment]
Here are the icons: 
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3916835/ic_launcher.4.zip)
