### ISSUE TITLE
[Bug] Madara wuxiaworld : HTTP error 403

### ISSUE THREAD

**Issue by tyme2tb** [inorichi/tachiyomi-extensions#1790]
Device information
Tachiyomi extension version: 1.2.26
Tachiyomi version: 1532
Android version: 9

Steps to reproduce
Try to load latest from wuxiaworld

Expected behavior
Shows manga

Actual behavior
Get a "HTTP error 403"

Other
This actually happens when trying to update a saved manga, or when trying to browse the catalogue also.

**Comment by happywillow0** [comment]
Something has changed with or broken with the automatic Cloudflare browser check. It normally should process in the background. 

A workaround is to open webview and let the cloudflare check go though first.

**Comment by tyme2tb** [comment]
That did work as a work around

**Comment by myrridDarknessgod** [comment]
I'm getting the same from kissmanga, where I get most of mine, and I've been able to open in in web viewer, but still getting the 403

**Comment by happywillow0** [comment]
WuxiaWorld turned off the ddos browser check. Should we considered this done and close it for now?
