### ISSUE TITLE
有2个源有问题

### ISSUE THREAD

**Issue by linbeii** [inorichi/tachiyomi-extensions#1791]
漫画柜(啥也出不来)
百年漫画(搜的到，能看目录，漫画出不来)

**Comment by arkon** [comment]
ManHuaGui also mentioned in #1759

**Comment by musouking** [comment]
你试试网页版漫画柜(manhuagui.com)打不打得开，这个和你的网有关和tachiyomi没啥关系。
It seems ManHuaGui or your ISP have IP/DNS block problem, I'm not pretty sure for I get err time out too even if I change my proxy.

**Comment by linbeii** [comment]
> 你试试网页版漫画柜(manhuagui.com)打不打得开，这个和你的网有关和tachiyomi没啥关系。
> It seems ManHuaGui or your ISP have IP/DNS block problem, I'm not pretty sure for I getting error time out/empty response soon after not change my proxy.

确实是，漫画柜网页也打不开。百年漫画在另一个应用cimoc中能看，但是在tachiyomi只能看到目录

**Comment by accs1234** [comment]
既然说到漫画柜了我就顺带提一嘴，漫画柜应该是大陆IP没法看，挂个梯子试一下
不过我之前就提过个issue
https://github.com/inorichi/tachiyomi-extensions/issues/1623
既有的两个bug是18+漫画能搜能加收藏但是不能load chapter，以及update library会直接封ip，导致tachiyomi的漫画柜直接没法用。。。

**Comment by musouking** [comment]
> 既然说到漫画柜了我就顺带提一嘴，漫画柜应该是大陆IP没法看，挂个梯子试一下
> 不过我之前就提过个issue
> #1623
> 既有的两个bug是18+漫画能搜能加收藏但是不能load chapter，以及update library会直接封ip，导致tachiyomi的漫画柜直接没法用。。。

18+的我也提了#1759 有开发者回复你可以看下
另外漫画柜是这样ban ip的吗，难怪我代理总是换了又换没用多久就连不上了，我服了

**Comment by accs1234** [comment]
漫画柜这个banip在我这里是这样：用原始版本的cimoc，更新收藏不会banip。用feilongfl大佬的cimoc更新收藏就会banip。tachiyomi的漫画柜插件似乎也是feilongfl大佬写的，这个问题就继承下来了。。。

**Comment by 1608637229** [comment]
漫画柜日常屏蔽ip的。

**Comment by SnakeDoc83** [comment]
Closed via https://github.com/inorichi/tachiyomi-extensions/pull/3556
