### ISSUE TITLE
[Bug] Missing extensions that used to exist

### ISSUE THREAD

**Issue by frgmnt** [inorichi/tachiyomi-extensions#1793]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 5.1.1

Not too sure if this falls under Bug or Source request, but since I hard reset my tablet and reinstalled Tachiyomi, I noticed that RawLH, RawQQ, and Mangakakalot extensions are no longer showing up in the list of extensions to install. Looking at the history of past commits in the history shows that they still were there but I don't see them in the list of files for extensions.

**Comment by MerradOklom** [comment]
Mangakakalot is now available under the multi-source extension MangaBox, something similar happened with RawLH and RawQQ, you can find them in the multi-source extension FMReader.
