### ISSUE TITLE
[Bug] Madara (mangazuki.online) : Trust Anchor not found

### ISSUE THREAD

**Issue by Vaturobi** [inorichi/tachiyomi-extensions#1794]
### Device information
* Tachiyomi extension version: 1.2.26
* Tachiyomi version: 0.8.4
* Android version: 8.1

## Steps to reproduce
1. Download extention
2. Browse mangazuki.online in catalogue

### Expected behavior
This should have happened
Catalogue should be searchable

### Actual behavior
This happens instead
Can't browse the site or update, download manga already in library

(used an image i found with same error different source)

![62010285-6246cb80-b169-11e9-9ffb-f2e05b5a17c6](https://user-images.githubusercontent.com/57532719/69021511-fa0b4680-09f2-11ea-8093-5a61f0a4e147.jpg)

## Other details
Discovered by trying to refresh and download manga in library
Site still accessible if using chrome

**Comment by samanta-widjaja** [comment]
i have chapter already in queue. have the same error

**Comment by happywillow0** [comment]
Could mangazuki.online may have been having temporary problems. I tried it earlier but it wouldn't load. 

I'm trying it now and while it seems a little sluggish (connection even timed out once), it did load for me without the error messages.

**Comment by SnakeDoc83** [comment]
Are either of you still experiencing this?  Are you using a VPN?

**Comment by Vaturobi** [comment]
Not anymore fixed after updating the extension
