### ISSUE TITLE
[Bug] Mangadex results take an extremely long time to load

### ISSUE THREAD

**Issue by ccrowles** [inorichi/tachiyomi-extensions#1797]
Covers and info take more than 1 minute to load EACH, to the point that the covers show up as broken in the search results, except for those loaded previously. Each time I open a manga I have to wait around 1 or 2 minutes for the info to load (but still no cover 90% of the time). Manga pages do load normally though. 

![Screenshot_2019-11-18-23-16-59-168_eu kanade tachiyomi](https://user-images.githubusercontent.com/12866474/69099594-6d48a300-0a5b-11ea-8d4f-b4744b380062.jpg)

![Screenshot_2019-11-18-23-17-57-190_eu kanade tachiyomi](https://user-images.githubusercontent.com/12866474/69099593-6d48a300-0a5b-11ea-8886-3833d8da8e37.jpg)

I have updated the extension to the latest version, added the main app and all the extensions to adblock whitelist, and even disabled the adblock itself thinking that might be the issue, but that fixed nothing.
All other extensions work properly and load fast.
I also did the whole "login on mangadex" thing a few weeks ago and everything worked properly that time, so I'm pretty sure the whole login process was done properly, which means that shouldn't be what's causing the issue either. 

I am on Tachiyomi 0.8.4, with mangadex extension 1.2.73

**Comment by CarlosEsco** [comment]
update to latest extension.
then in advanced setting clear cache, clear cookies, clear database.  
there was a change on mangadex side that changed urls which causes the delay.
