### ISSUE TITLE
[Bug] mangatensei and others : page ordering wrong

### ISSUE THREAD

**Issue by CodeDoes** [inorichi/tachiyomi-extensions#1798]
### Device information
* Tachiyomi extension version: 1.2.4
* Tachiyomi version: 0.8.4
* Android version: 4.4.4

The page order of the manga is wrong. on the websites they show up fine. Not so in the app.

**Comment by SnakeDoc83** [comment]
Post an example including which manga and which chapter.

**Comment by MerradOklom** [comment]
I had the same problem (#1495).
As I said in my comment there, this only happens with old Android versions (I have KitKat 4.4.2).

**Comment by SnakeDoc83** [comment]
@arkon This should be closed.  OP never replied with further details.  Pages are being parsed from a JSON array, can't see how this would be anything but the source's fault.
