### ISSUE TITLE
[Source Request] [18+] H-browser

### ISSUE THREAD

**Issue by Jumpgang** [inorichi/tachiyomi-extensions#1802]
### Source Website:
Hbrowse.com

### Other Details
Great Doujin site with multiple chapter Doujins all grouped together, instead of each chapter being treated as a separate book.

**Comment by SnakeDoc83** [comment]
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/1174

**Comment by Jumpgang** [comment]
It was previously closed, I am trying to bring it to attention once again

**Comment by arkon** [comment]
It's not closed. Don't create duplicates
