### ISSUE TITLE
[Source Request][Spanish] AnimeXtremist

### ISSUE THREAD

**Issue by MerradOklom** [inorichi/tachiyomi-extensions#1805]
### Source Website
Website can be found at <http://animextremist.com/mangas.htm>

### Other Details
The site has been inactive for a while but their catalogue is still readable.

**Comment by edgarMejia** [comment]
No se si sea conveniente trabajar en un source que puede desaparecer en cualquier momento.

**Comment by MerradOklom** [comment]
Lleva bastantes años en línea, pero tienes razón. Lo cerraré.

**Comment by edgarMejia** [comment]
Estuve revisandolo, pero no encontre las imagenes de los episodios

**Comment by edgarMejia** [comment]
Gracias, si hay más sources no dudes en agregar la solicitud
