### ISSUE TITLE
[Source Request] LHTranslation

### ISSUE THREAD

**Issue by Rowgath** [inorichi/tachiyomi-extensions#1806]
### Source Website
Website can be found at https://lhtranslation.net/.

### Other Details
LHTranslation was a source before but for some reason it got removed when the repo updated to 17ededee503e434cd0bc8ccfcbaf331f065e9090 Oct 16.

**Comment by SnakeDoc83** [comment]
It's part of the FMReader extension now.

**Comment by Rowgath** [comment]
> 
> 
> It's part of the FMReader extension now.
Oh, thanks.

**Comment by setlec** [comment]
Hello there, could you guys update this extension? there are way to much broken manga other this FMreader extension.
