### ISSUE TITLE
SyntaxError: unterminated statement (line 1) when trying to read

### ISSUE THREAD

**Issue by Nesaijn** [inorichi/tachiyomi-extensions#1808]
### Device information
* Tachiyomi extension version: Mangahere 1.2.10
* Tachiyomi version: 0-8-4
* Android version: 9

## Steps to reproduce
1. Install Mangahere as an extension in Tachiyomi
2. Find and but "Solo Leveling" and/or "Peerless Dad" in your library.
3. Try to read any Chapter from "Peerless Dad" or "Solo Leveling" from Mangahere, except the latest one from "Solo Leveling".
4. Try other chapters.

### Expected behavior
Chapter should have loaded and be readable.

### Actual behavior
Info bubble pops up at the bottom of the screen, saying "SyntaxError: unterminated statement (line 1)".

### Other details
This does not happen on all Chapters or Mangas. I couldn't see any rule behind it, but seems to be recurrent on the already mentioned Mangas.

**Comment by happywillow0** [comment]
Some background info related to the issue, the effected mangas I suspect are webtoons. Mangahere has a specific webtoon viewer which is different from their normal manga (per page) viewer which the page parser is not equipped to handle. 

On the flip slide, the packed javascript function contains a json of all the image urls.

**Comment by happywillow0** [comment]
That was easier than I expected.

**Comment by Nesaijn** [comment]
Wow, awesome. That was fast. Thank you!
