### ISSUE TITLE
[Bug] Kissmanga giving Page list is empty

### ISSUE THREAD

**Issue by buzmeg** [inorichi/tachiyomi-extensions#1818]
### Device information
* Tachiyomi extension version: 1.2.9
* Tachiyomi version: 0.8.4
* Android version: 9

Kissmanga appears to be doing some nasty redirect games in order to bury the captcha more layers in.

Its hard for me to reproduce easily.  Sorry for the vague report.

**Comment by tinster4x4** [comment]
I ran into the same issue in the past. It's definitely part of the captcha verification. My current workaround is to load up kiss in the browser of your device open up any manga chapter and fulfill the captcha requirement. This will authenticate your access and allows you to download the chapters

**Comment by buzmeg** [comment]
I tried to do that, but it didn't work.

What "seemed" to happen is that kissmanga wasn't throwing the captcha right away.

Even, when you attempted to load a chapter is the browser, everything on kissmanga would show fine.  Then when you went to read a chapter, it would do a redirect to an ad page or two.  And only *after* the ad would it throw you the captcha and even that seemed to be buried in a frame.

They don't seem to be doing that anymore, for the moment.

**Comment by tinster4x4** [comment]
@buzmeg sorry, I was using a browser that blocked ads and trackers so I might have bypass the redirect ads. I would recommend using something similar or clear your cache and cookies for the browser so they will throw the captcha earlier. 

Browser: Brave
Device: Kindle Fire HD 10
