### ISSUE TITLE
[Bug] MangaSY : java.lang.Exception: Challenge not found

### ISSUE THREAD

**Issue by samanta-widjaja** [inorichi/tachiyomi-extensions#1828]
### Device information
* Tachiyomi extension version: Madara 1.2.32
* Tachiyomi version: 0.8.4
* Android version: 7.1.1

I got java.lang.Exception: Challenge not found when trying to download bad girls punishment games chapter 41. I already forced closed and restart like in the faq, but no use. 

Help please.

Thanks

**Comment by happywillow0** [comment]
They have turned on cloudflare ddos protection with the automatic browser verification. There should be an auto bypass but it doesn't seem to be working correctly so as a temporary workaround, you can open and bypass cloudflare in webview before reading / downloading.

**Comment by happywillow0** [comment]
I'm not sure if cloudflare is changed or is just doing something different temporary but the challenge url off of my current browser is:
`https://www.mangasy.com/?__cf_chl_jschl_tk__={hash}`
while I'm pretty sure the app is looking for `chk_jschl`

**Comment by samanta-widjaja** [comment]
When i open via tachiyomi view, it show the image. but when i download it still show the same challenge error  message.

**Comment by SnakeDoc83** [comment]
@arkon This can be closed.
