### ISSUE TITLE
[Bug] westmanga : image not load

### ISSUE THREAD

**Issue by hostkit** [inorichi/tachiyomi-extensions#1829]
### Device information
* Tachiyomi extension version: 1.2.1
* Tachiyomi version: r1532
* Android version: 7.1

## Steps to reproduce
1. Open this titles
Tensei Shitara Slime Datta Ken: Spin Off
2. Go to chapter 5
Only display trying button

### Other details
Open via browser images load normally
![Screenshot_20191127-214139](https://user-images.githubusercontent.com/3790389/69732811-e41e2400-115e-11ea-889d-14d128954f9b.png)

**Comment by hostkit** [comment]
![Screenshot_20191127-214508](https://user-images.githubusercontent.com/3790389/69732999-3a8b6280-115f-11ea-96c2-5cafe0e3f3ef.png)
Open via browser

**Comment by happywillow0** [comment]
Is that the same chapter? My browser shows chapter 4 and 5 with broken images on the website.

![Screenshot_20191127-151126](https://user-images.githubusercontent.com/45346080/69756321-3e4fc280-1128-11ea-9347-598cfbbeebb3.png)

**Comment by hostkit** [comment]
> Is that the same chapter? My browser shows chapter 4 and 5 with broken images on the website.
> 
> ![Screenshot_20191127-151126](https://user-images.githubusercontent.com/45346080/69756321-3e4fc280-1128-11ea-9347-598cfbbeebb3.png)

Yes but via browser tachiyomi work normally. Like above screen

**Comment by hostkit** [comment]
![Screenshot_20191128-145404](https://user-images.githubusercontent.com/3790389/69787385-052e5580-11ef-11ea-82ca-946bf86c2dc1.png)
Open in web browser from tachiyomi

**Comment by hostkit** [comment]
How to build/debug via myphone it self?

**Comment by llreizh** [comment]
All indonesian extention doesn't shown on catalogue even after instaled.

**Comment by SnakeDoc83** [comment]
@arkon This was a server-side issue and images are working again.  This can be closed.
