### ISSUE TITLE
[Bug] https://com-x.life/ comics disappeared

### ISSUE THREAD

**Issue by evylmen** [inorichi/tachiyomi-extensions#1835]
### Device information
* Tachiyomi extension version: `0.8.4`
* Tachiyomi version:   0.8.4
* Android version: ?

### Expected behavior

a couple of days ago everything stopped working
### Actual behavior
This happens instead

**Comment by evylmen** [comment]
![Capture+_2019-11-28-14-16-43](https://user-images.githubusercontent.com/55300871/69802567-e332d400-11ea-11ea-905a-09c4745ca98e.png)
![Capture+_2019-11-28-14-17-24](https://user-images.githubusercontent.com/55300871/69802577-e8901e80-11ea-11ea-949d-d59ecba1e6a7.png)

**Comment by happywillow0** [comment]
Com-X is using the Russian cloudflare equivalent Antibot.cloud
They are using their own version of a bot check / ddos check.

Tachiyomi doesn't know how to handle it so you will have to bypass it manually. 

You will have to use the Tachiyomi Dev version currently which includes the new feature to open up the catalog (browse or latest) in web view. Opening the source in web view will temporarily allow you to access Com-X until antibot decides to check you again.

**Comment by Pavkazzz** [comment]
Fix in https://github.com/inorichi/tachiyomi-extensions/pull/1842
Update the extension
