### ISSUE TITLE
[Bug] Tsumino : Newest Sorting Broken.

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi-extensions#1837]
### Device information
* Tachiyomi extension version: 1.2.2
* Tachiyomi version: 0.8.4
* Android version: 6.0.1

## Steps to reproduce
1. Open the side menu while in Tsumino.
2. Select sorting as "newest".

### Expected behavior
Sorting by newest should have sorted them by newest entries ( as can be seen from the website).

### Actual behavior
 Sorting by newest shows the same entries as the ones in popular.

### Other details
I'm actually using Tsumino on regular Tachiyomi, instead of Tachiyomi-EH. I downloaded the extension through EH (since it wasn't on the regular extension list and no one bothered to add it either), and then it appeared on my regular one as well so I've been using that.

**Comment by SnakeDoc83** [comment]
If all you want is to view the newest entries on the website, tap "latest" instead of "browse."  The "newest" sort option works but you need to enter other search options to go with it (you can't leave everything else blank).

**Comment by MercerBoi** [comment]
That's a pretty fair solution, though I do think someone should look into this sorting issue since the website doesn't require other options to be filled to show the new ones. Thanks!
