### ISSUE TITLE
[Bug] Source Name : Komga extension not installing OP5T

### ISSUE THREAD

**Issue by alphat5** [inorichi/tachiyomi-extensions#1843]
### Device information
* Komga extension version: 1.2.4
* Tachiyomi version: 0.8.2
* Android version: 9

## Steps to reproduce
1. Go in the extension tab
2. Install Komga
3. Kill the app
4. Re-open the app
5. Go in the extension tab
6. Komga is not installed

### Expected behaviour
The extension should be installed and visible in the APP

### Actual behaviour
The extension shows as installed but not visible in the app. After killing the app and restarting, it reshows that I have to install the extension

### Other details
@gotson for follow-up

**Comment by SnakeDoc83** [comment]
Try upgrading to Tachiyomi .8.4

**Comment by arkon** [comment]
Installs fine on my OP5T.
