### ISSUE TITLE
[Bug/Feature request] Mangadex : Error 451: Log in to view manga

### ISSUE THREAD

**Issue by SkiFire13** [inorichi/tachiyomi-extensions#1845]
# Device information
* Tachiyomi extension version: 1.2.73
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. Search for id:42110 in Mangadex
2. Try to open a chapter

I don't know if it can be considered a bug or a feature request. Just got this error while downloading a chapter "Error 451: Log in to view manga; contact Mangadex if err..."

This happened to me with just this manga (but there may be others) which looks like can't be viewed without logging in, not even on a pc (with a logged in session it works fine). This is probably the result of some recent update on Mangadex (the website) since I was able to read the previous chapter a week ago. 

Hence the request to be able to login inside the Mangadex extension. The ability to synchronize viewed chapters would be welcome too. I guess there could be some problems with what the sources API allows to do, but maybe we can get away with an option to set the chapter as read (on Mangadex) when the page list is fetched (?)

**Comment by SnakeDoc83** [comment]
You can log in, read: https://tachiyomi.org/help/faq/extensions/#no-results-when-searching

If you want additional features take a look at using [Neko](https://github.com/CarlosEsco/Neko/).

**Comment by SkiFire13** [comment]
Thank you it worked
