### ISSUE TITLE
Mangadex option about R18+ filter

### ISSUE THREAD

**Issue by secw** [inorichi/tachiyomi-extensions#185]
Can't seem to find a way to search R18 stuff. You have to toggle on the website. A similar simple toggle on tachiyomi would be nice. Thank you!

**Comment by CarlosEsco** [comment]
Toggle won't happen until external sources can have preferences.  But the pull request I have open enables show all

**Comment by CarlosEsco** [comment]
#198 should solve most of this.  You cant browse by r18 but you can search by letter or regular search with r18 enabled

**Comment by secw** [comment]
Thank you so much!
