### ISSUE TITLE
[Bug] Mangarock : Value Manga is licensed at data of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by Narukami11** [inorichi/tachiyomi-extensions#1861]
### Device information
* Tachiyomi extension version: 1.2.14
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
Attempting to open manga "So Pure, So Flirtatious" shows the error. Chapters don't show up but cover and info loads.
![Screenshot_20191207-233327](https://user-images.githubusercontent.com/50742232/70378829-06782480-194b-11ea-9575-e8469983d06c.png)

**Comment by SnakeDoc83** [comment]
It's not on their website anymore; nothing we can do.  Use a different source--I'd suggest 1st Kiss or Mangazuki.online from the Madara extension.
