### ISSUE TITLE
[Source Request] 《崩坏3》IP站

### ISSUE THREAD

**Issue by MisakaSakura** [inorichi/tachiyomi-extensions#1877]
### Source Website
Website can be found at <comic.benghuai.com>.

### Other Details
its a series of game comic constantly update from miHoYo,which a Chinese game corporation.

**Comment by as280093** [comment]
Here are the Icons:
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3965083/ic_launcher.11.zip)
