### ISSUE TITLE
Mangapark source bugg

### ISSUE THREAD

**Issue by amboris** [inorichi/tachiyomi-extensions#188]
(CATALOGUE) SOURCE REQUESTS:
mangapark
BUGS:
mangapark have a bugg where all manga has zero chapters
tachiyomi 0.6.8
mangapark 1.0.2

**Comment by CarlosEsco** [comment]
please update to 1.0.3.  Then in settings advanced clear chapter cache, cookies, and database

**Comment by amboris** [comment]
there is no 1.0.3 on J2ghz's FDroid Repo

**Comment by CarlosEsco** [comment]
Download from official repo here. https://github.com/inorichi/tachiyomi-extensions/blob/repo/apk/tachiyomi-en.mangapark-v1.0.3.apk

**Comment by CarlosEsco** [comment]
Uninstall other version first no needed to remove manga though

**Comment by amboris** [comment]
how to add github repo source to f-droid? i mean if i have to update everythign manually everytime new update comes out kina meh :(

and i thought J2ghz's FDroid Repo is the offical repo for f-droit as description says

**Comment by CarlosEsco** [comment]
j2ghz's was the official repo.  The current Dev tachiyomi has external sources downloadable in app and refer to github repo i linked.  When external sources downloadable in app goes to stable you  will have to uninstall all fdroid releases anyways.  Manual update is just until a new stable is released.

**Comment by CarlosEsco** [comment]
please close this after you update to 1.0.3 and issue is resolved
