### ISSUE TITLE
[Source Request][Spanish] Leer-Comics

### ISSUE THREAD

**Issue by MerradOklom** [inorichi/tachiyomi-extensions#1883]
### Source Website
Website can be found at <https://leer-comics.blogspot.com/>.

### Other Details
Probably the only spanish site that let you read western comics online. Not a site as a whole but a blog (I hope this is not much of a inconvenience).

**Comment by edgarMejia** [comment]
Los blogs son más fáciles de hacerles scraping, por ejemplo vermangaspor... y vercomicspor... creo que usan blogger y fueron bastante fáciles de "scrapear".

**Comment by MerradOklom** [comment]
@edgarMejia si es así, buenísimo. Me preocupaba porque no tienen sinopsis ni géneros, y cada capítulo de cada cómic está separado en posts/publicaciones individuales.

**Comment by happywillow0** [comment]
I took a quick look at the site. Everything looks easy to pull however, blogspot doesn't seem to use a easy page system. Since everything is sorted by post date, the next page link filters by date (<dec 17, <dec 14, < dec 10, etc) rather than just by page (page 2, page 3, etc.)

**Comment by edgarMejia** [comment]
> I took a quick look at the site. Everything looks easy to pull however, blogspot doesn't seem to use a easy page system. Since everything is sorted by post date, the next page link filters by date (<dec 17, <dec 14, < dec 10, etc) rather than just by page (page 2, page 3, etc.)

Yap, I have problems to use blogger pagination .... sad.

**Comment by MerradOklom** [comment]
Here is another blog managed by the same people: 
https://centraldelectura.blogspot.com/

It seems to work like an index for Leer-Comics. For example if you select "Ediciones Glénat" you will get a list of the comics released by that editorial, and if you select one of these comics you will get all the issues available (some are available in Leer-Comics and others in Central de Lectura).

Thank you both, Edgar and Happywillow, for taking your time reviewing this request, and I hope this helps in some way.

**Comment by edgarMejia** [comment]
This source is no longer available.
Please close it.
