### ISSUE TITLE
[Bug] MangaNelo : download queue always page list empty

### ISSUE THREAD

**Issue by samanta-widjaja** [inorichi/tachiyomi-extensions#1889]
### Device information
* Tachiyomi extension version: mangabox 1.2.6 
* Tachiyomi version: 0.8.4
* Android version: 7.1.1

## Steps to reproduce
1. I already have a lot of chapter download queue from manganelo 
2. Suddenly it all pagelist is empty. Though when i open via manganelo web is fine

Help please

**Comment by Starmann** [comment]
Can confirm. If I used Mangakakalot and select Gundam: The Origin, it gets the same issue. On desktop, Mangakakalot links to Manganelo, so this is a similar issue.

**Comment by SnakeDoc83** [comment]
Try refreshing chapter list (pull down on it).

If that doesn't work, go to settings > advanced, tap on clear chapter cache and clear database, then restart Tachi.

**Comment by samanta-widjaja** [comment]
Does clear chapter cache and database will remove my downloads queues?

**Comment by SnakeDoc83** [comment]
I'm not sure.  Were they queued before you updated your extension?  If so, you may need to clear them regardless.

**Comment by samanta-widjaja** [comment]
And manganelo latest and browse gave empty list. But i can open it fine using chrome. So whenever i tried to refresh chapter by pull down, it said no chapters found

**Comment by aniik8pv2** [comment]
Can confirm. Open in webview seems to be working fine.
1. No new updates even though the website is adding chapters.
2. "page list empty" error on opening any chapter

**Comment by SnakeDoc83** [comment]
@aniik8pv2 @samanta-widjaja 

Make sure you're using MangaBox 1.2.7

**Comment by aniik8pv2** [comment]
@SnakeDoc83 Isn't mangabox a different extension than Manganelo?
I have about 50 series sourced from Manganelo and I really don't wanna move all of them ONE BY ONE to a different source and then reset covers too

is there no chance of the manganelo extension being fixed?
I noticed that manganelo extension has been removed from the available list if you uninstall it

**Comment by arkon** [comment]
Just uninstall MangaNelo and install MangaBox. You shouldn't need to migrate.
