### ISSUE TITLE
[Bug] webtoons showing page empty and can't read the chapters from toons saved

### ISSUE THREAD

**Issue by leoteesh** [inorichi/tachiyomi-extensions#1891]
### Device information
* Tachiyomi extension version: 1.2.6
* Tachiyomi version: ? O.8.4
* Android version: ?7.0

## Steps to reproduce
1. First Step clicked on chapter I wanted to read
2. Second Step checked the catalogue to verify if the webtoon comes up

### Expected behavior
It should have come up with a list and I should have been able to read and access it

### Actual behavior
This happens instead- when I clicked onto the chapters a page list is empty comes up.
When I clicked on the catalogue nothing shows up on the webtoons.

### Other details
I have also tried version 1.2.12 but there is only a few webtoons available. It is not the full list. It does not include my favourites.

Apologies if this is not the correct form to complete.

Many thanks

**Comment by as280093** [comment]
If you are running into **"Page List is Empty"** errors when trying to access webtoon with the Webtoons extension, you'll have to open the entry in webview and verify your age, as Webtoons has recently added age gates on their site

**Comment by Rajh** [comment]
And how do you do that "you'll have to open the entry in webview" please ?

**Comment by SnakeDoc83** [comment]
https://tachiyomi.org/help/guides/source-problems/#solving-a-captcha

**Comment by ObserverOfTime** [comment]
It seems to me that users who don't already have a Webtoons series in their library can't access the webview to verify their age and because both `LATEST` and `BROWSE` return nothing they can't add any series to their library.

**Comment by happywillow0** [comment]
While stable is reliable, the dev version and other forks have newer feature such as opening up webview from the catalog screen directly (`Latest`/`Browse`)
