### ISSUE TITLE
[Bug]Mangabox: Mangakakalot page not found  : filter page error

### ISSUE THREAD

**Issue by ck1811** [inorichi/tachiyomi-extensions#1895]
He ### Device information
* Tachiyomi extension version: 1.2.6
* Tachiyomi version: 0.8.4
* Android version: Android 5.0

### Other details
After updating the Mangabox: Mangakakalot to 1.2.6,
![Screenshot_20191222-231932_Tachiyomi](https://user-images.githubusercontent.com/59142650/71323738-8c7e9880-2511-11ea-8e39-e600bd619ef3.jpg)
![Screenshot_20191222-231926_Tachiyomi](https://user-images.githubusercontent.com/59142650/71323740-91dbe300-2511-11ea-9b2e-905cc2294d8c.jpg)

 all  categories page could not be Found.

**Comment by samanta-widjaja** [comment]
Yup. I can confirm about that. Mangakalot and manganelo is broken after update

**Comment by SnakeDoc83** [comment]
Nelo made changes to their filtered search; needs a fair amount of work so I skipped it.

Kakalot's an easy fix, just need to add a selector.
