### ISSUE TITLE
[Bug] Manhuadui : no chapters found 

### ISSUE THREAD

**Issue by rrprrp** [inorichi/tachiyomi-extensions#1897]
### Device information
* Tachiyomi extension version: 1.2.6
* Tachiyomi version: 0.8.4
* Android version: 8

## Steps to reproduce
open manga “五等分的花嫁"

### Other details
some manga only show in moblie web page
PC web page hiden many content 

https://www.manhuadui.com/manhua/wudengfendehuajia/443321.html (miss chapters)
https://m.manhuadui.com/manhua/wudengfendehuajia/443321.html (ok)

**Comment by saasddsaasdd** [comment]
support，up
