### ISSUE TITLE
[Bug] Source Name : Mangadex Manga plus stops queue

### ISSUE THREAD

**Issue by taksaru** [inorichi/tachiyomi-extensions#1899]
### Device information
* Tachiyomi extension version: 1.2.73
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. Download a manga plus chapter from a mangadex series that has manga plus chapters as it's source. I.e. Kimetsu no Yaiba 
2. Download additional chapters from anywhere else

### Expected behavior
Kimetsu no Yaiba chapter gives a suggestion to use manga plus service and either removes itself from queue or is skipped

### Actual behavior
Entire queue stops. Queue needs to be cleared to download anything

**Comment by SnakeDoc83** [comment]
Can't really implement your expected behavior at the extension level.  We could add an option not to add MangaPlus chapters to the chapter list at all, but I think it may be better to solve this through MangaDex itself.  You can log in to your MangaDex account and block groups; so if you block the MangaPlus group you shouldn't get any of their chapters in your chapter lists (after refreshing any manga in your library).

**Comment by taksaru** [comment]
As I understand it the current extensions don't support logins so I don't see how this would work with tachiyomi.

**Comment by SnakeDoc83** [comment]
You log in through webview.

https://tachiyomi.org/help/faq/extensions/#mangadex

**Comment by taksaru** [comment]
Thanks, I think it might be worth considering adding a manga plus exception to the extension overall but as long as you're aware of the issue.

**Comment by arkon** [comment]
We should actually handle this sort of exception more gracefully

**Comment by taksaru** [comment]
The Web view login and block fix doesn't work on mangadex.cc. While I understand mangadex.cc is temporary. I figured I should draw attention to this

**Comment by CarlosEsco** [comment]
Yea mangaplus needs to be filtered out in the extension if possible.  so it doesnt even show them

**Comment by taksaru** [comment]
Manga plus chapters on mangadex are now being added to my queue with every update and stop the queue before anything starts to download

**Comment by CarlosEsco** [comment]
I'll work on this later today
