### ISSUE TITLE
[Bug] Komikcast : Thumbnail did not appear

### ISSUE THREAD

**Issue by herdax** [inorichi/tachiyomi-extensions#1900]
### Device information
* Tachiyomi extension version: 1.2.4
* Tachiyomi version: 0.8.4
* Android version: 9.0 Pie

## Steps to reproduce
1. Attempt to open Latest or Browse on Komikcast 

### Expected behavior
This should have happened
![Screenshot_2019-12-23-22-31-31-47_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/12084129/71366285-2c9cf600-25d4-11ea-8279-211b56521b60.png)
Broken thumbnail

**Comment by arkon** [comment]
#2636 addresses the version in WPMangaStream, but apparently it's an issue in the separate extension.

We should probably remove the separate one if possible.

**Comment by SnakeDoc83** [comment]
Separate extension seems to be working now, going to close this.
