### ISSUE TITLE
[Bug] Mangahasu : error 400 on catalogue browse and search and also downloads

### ISSUE THREAD

**Issue by officermeow** [inorichi/tachiyomi-extensions#1901]
### Device information
* Tachiyomi extension version: 1.2.5
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
Catalogue browse and search throws 400 as well as when I'm trying to download additional chapters of any Mangahasu-sourced manga that is already in the library.

**Comment by happywillow0** [comment]
Just to check in, I just added Mangahasu on my phone and everything is loading fine. Is this still an issue? It may have been a temporary issue with the source / webpage server. 

You can also try to clear cache, cookies, and database in the Advanced Settings.

**Comment by officermeow** [comment]
Ah, now I feel dumb, I didn't know there is such option, but I should have looked better. Thanks a lot, it worked!!! :)
