### ISSUE TITLE
[Bug] Toonily : Chapters not loading / hanging

### ISSUE THREAD

**Issue by Thoasty** [inorichi/tachiyomi-extensions#1908]
Tachiyomi extension version: Toonily 1.2.3
Tachiyomi version: 0.8.4

You can search for latest series updates but no chapters are loading. It just hangs with the spinning loading sign. Been happening for a week or so.

**Comment by SnakeDoc83** [comment]
The standalone extension has been deprecated.  Uninstall it and use/update Madara for a working Toonily.

**Comment by Thoasty** [comment]
Gotcha. Thanks a bunch.
