### ISSUE TITLE
MangaDex manga details are not being parsed correctly

### ISSUE THREAD

**Issue by rsyh93** [inorichi/tachiyomi-extensions#191]
Tachiyomi v0.6.7
MangaDex extension v1.2.2

Excluding the latest chapter number, all other information in the "Info" section of any manga as well as the thumbnail, are missing.

**Comment by CarlosEsco** [comment]
Please update to 1.2.3 and then in advanced settings clear database of manga not in library

**Comment by CarlosEsco** [comment]
Can you close this after you update to 1.2.4 and verify it works
