### ISSUE TITLE
[Feature Request] please add New extension : website (ww2.mangacruzers.com) and thanks

### ISSUE THREAD

**Issue by saadiens** [inorichi/tachiyomi-extensions#1922]
### Why/User Benefit/User Problem
(explain why this feature should be added)

### What/Requirements
(explain how this feature would behave)

**Comment by as280093** [comment]
**Here are the icons:**
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/4006910/ic_launcher.14.zip)
