### ISSUE TITLE
[Bug] Source Name : Short Description

### ISSUE THREAD

**Issue by Louis-ui** [inorichi/tachiyomi-extensions#1928]
### Device information
* Tachiyomi extension version: I don't know（It seems that i didn't install it）
* Tachiyomi version: 8.4.5-EH
* Android version: 9

When i try installing Expansion module，i get a error saying that Error parsing installation package。I don‘t know how to solve it，please help me。Thank you。QAQ

**Comment by SnakeDoc83** [comment]
Seems like an issue you should take up over at [TachiyomiEH](https://github.com/NerdNumber9/TachiyomiEH/).
