### ISSUE TITLE
Hentai2Read showing "no chapters found"

### ISSUE THREAD

**Issue by Otend** [inorichi/tachiyomi-extensions#193]
tachiyomi r1343, extension version 1.0.1

Everything on the site is currently showing "no chapters found" as of the time of this report.  This issue was brought up in the support discord, then replicated.

Steps to replicate (assuming you've already got the prerequisites installed):
1. Open Tachiyomi
2. go to the Catalogues section and use either Browse or Latest on Hentai2Read
3. Click any manga displayed
4. observe bug

**Comment by samir2122** [comment]
Yeah same for me
