### ISSUE TITLE
[Bug] Mangakakalot: Attempt to invoke virtual method

### ISSUE THREAD

**Issue by zyzzyvo** [inorichi/tachiyomi-extensions#1930]
### Device information
* Tachiyomi extension version: 1.2.8
* Tachiyomi version: 0.8.4
* Android version: 9

### Other details
A few of my manga's has this error but its the said manga is fine on webview
![Screenshot_2019-12-28-22-00-01-122_eu kanade tachiyomi](https://user-images.githubusercontent.com/56079643/71544781-3d77ae00-29be-11ea-94a0-881170f64831.jpg)

**Comment by happywillow0** [comment]
Uninstall the mangakakalot extension and install the new Mangabox extension. All your manga entries will stay the same.
