### ISSUE TITLE
[English] MangaHasu

### ISSUE THREAD

**Issue by samir2122** [inorichi/tachiyomi-extensions#194]
Pls add this source.

**Comment by jerycho007** [comment]
+ I support this!

**Comment by qupound** [comment]
Could someone please add this as a source, the site updates manhwa faster, the website is http://mangahasu.se/

**Comment by Reraru** [comment]
This could replace Mangago. I hope the Dev adds it and it's easy to add.

**Comment by Moecalypse** [comment]
I wanted to create also a request for Mangahasu. Good that I checked the threads beforehand. This is a very very good alternative to mangago. Would really recommend adding this source
