### ISSUE TITLE
[Bug] Mangadex : not all covers show up

### ISSUE THREAD

**Issue by fefo-dev** [inorichi/tachiyomi-extensions#1942]
### Device information
* Tachiyomi extension version: 1.2.73
* Tachiyomi version: r1531
* Android version: 9.0

## Steps to reproduce
1. Delete app cache on \Android\data\eu.kanade.tachiyomi.debug
2. Open Tachiyomi and wait for the covers to download

### Expected behavior
Every manga cover should show up.

### Actual behavior
Seemingly random covers show on gallery, others only on info tab and some not at all:
https://images2.imgbox.com/5f/da/IVSBEfAO_o.png

Info tab only:
Berserk
Festival of Champions
The Ancient Magus' Bride
*OP is M+ ofc

### Other details
Manually setting the covers (download througth web view then set manualy) works as expected. I know about Mangadex' spotty behavior due to site rules, but it doesn't explain the inconsistent behaviour.

**Comment by CarlosEsco** [comment]
In the app clear cache and db (this only affects non library manga). Then try again

**Comment by CarlosEsco** [comment]
It's expected in the browse view to have  <5% covers not load but when clicking they should

**Comment by fefo-dev** [comment]
Cleaned all cache and some images popped as expected, some still only in info and some didn't, but they are updating slowly. Thanks, I'll update later on a more stable connection.

**Comment by CarlosEsco** [comment]
You have an example of one not loading at all?

**Comment by CarlosEsco** [comment]
But my guess is this is a connection issue so closing.
