### ISSUE TITLE
Unable to install new extensions on rooted motorola xoom wingray 4.4.4 (cyanogenmod 11))

### ISSUE THREAD

**Issue by ForgetfulJones** [inorichi/tachiyomi-extensions#195]
Using tachiyomi r1343, I'm unable to install new extensions.
I eventually downloaded the APKs directly from here and they installed just fine.  I should try to see if they upgrade once installed, but haven't yet.
Same version works just fine on my phone (rooted Nexus5-6.0.1)
The message given by the package installer is "The package appears to be corrupt."

It *looks* like the apk is being deleted before the package installer gets done, I'll enclose the ~20 seconds of log.

[tachi debug.txt](https://github.com/inorichi/tachiyomi-extensions/files/1714989/tachi.debug.txt)

**Comment by inorichi** [comment]
The apk is automatically deleted after 10s starting when the install screen is launched. It makes sense that the file is not found after 20s, but it should have been installed before that.

You can try [r1341](http://tachiyomi.kanade.eu/tachiyomi-r1341.apk) which doesn't have the 10s timeout, but I don't think it'll solve the issue.

**Comment by inorichi** [comment]
So, did you have any luck?

**Comment by ForgetfulJones** [comment]
Yes.  Extensions install just fine w\ r1341.

**Comment by inorichi** [comment]
It's fixed now in upstream.
