### ISSUE TITLE
[Bug] MangaDex failed to connect.

### ISSUE THREAD

**Issue by Aericio** [inorichi/tachiyomi-extensions#1954]
Tachiyomi v0.8.4.
MangaDex v1.2.73.
Android v9.

When you try to open the MangaDex library, it shows an error. It's been this way the whole day, and I tried on both wireless and data, same result.

Catalogues -> MangaDex -> Latest/Browse

`failed to connect to mangadex.org/5.135141.76:443`

(Sorry I'm on mobile using ForkHub and it's not giving me the template here)

**Comment by arkon** [comment]
MangaDex is down for maintenance for up to 3 days.

**Comment by Mutank** [comment]
Mangadex is back online, temporarily moved to www.mangadex.cc

https://www.reddit.com/r/manga/comments/ek70pk/sl_mangadex_is_back/

**Comment by Birsing** [comment]
but we cannot search/read manga because the extension is fixed on Mangadex.org not Mangadex.cc.
If possible can anyone update the extension?

**Comment by arkon** [comment]
You'll just have to wait until they move back to .org.

**Comment by arkon** [comment]
Extension is updated. Some chapters may not work -- double check in webview before reporting issues.
