### ISSUE TITLE
[Mangadex ver. 1.2.3] Error while trying to parse newly added manga info and cover

### ISSUE THREAD

**Issue by GumiFlatline** [inorichi/tachiyomi-extensions#196]
Hi,
If I add a new manga from mangadex source into my reading list, Tachiyomi fails to parse its info and cover art. And if I try to add a cover manually, I get a _failed to update cover_ message.

I don't know if ver. 1.2.3 is responsible for it, but everything else in my reading list (from mangadex) is parsed correctly.

**Comment by CarlosEsco** [comment]
Please close #191 already has this opened.
