### ISSUE TITLE
[Source Request] Source Name : its 2 sources first is ( gmanga ) second is ( mangaarabteam )

### ISSUE THREAD

**Issue by ahmad-elmasry** [inorichi/tachiyomi-extensions#1962]
### Source Website
Website can be found at <https://mangaarabteam.com>. And the second source is < gmanga.me >

**Comment by SnakeDoc83** [comment]
Again, mangaarabteam already exists as part of the Madara extension; gmanga already has an open request; and issues are supposed to be reported separately.

**Comment by ahmad-elmasry** [comment]
Well, thank you @SnakeDoc83
