### ISSUE TITLE
[Bug] ( manga.ae) : Failed to load chapters

### ISSUE THREAD

**Issue by ahmad-elmasry** [inorichi/tachiyomi-extensions#1963]
### Device information
Tachiyomi v0.8.4.
 
Go to ( manga.ae ) source try to open kengan asura for example it failed to load chapters, some manga work well and others have a problem with loading some pages of the chapter

**Comment by CoutoSH** [comment]
same problem with Madara (1st Kiss) a lot of manga only showing Retry

**Comment by happywillow0** [comment]
I just took a look at this issue and I think it is a source / webpage issue. 

Can you double check if this loads all the images?
https://mangaae.com/kengan-ashua1/236/0/full

I can't tell if I'm shadow banned, region locked, or if the source is broken.

**Comment by arkon** [comment]
> Can you double check if this loads all the images?

Seems to work for me?

**Comment by ahmad-elmasry** [comment]
It works
