### ISSUE TITLE
Tritinia Scans is broken

### ISSUE THREAD

**Issue by alexporth** [inorichi/tachiyomi-extensions#1967]
Tachiyomi Version: 0.8.4
Favourites from this group don't get updated and the catalogue returns an error.
I don't know what extension this is from because it doesn't say it in the app as far as I can tell.
Error message: Unable to resolve host "ghajik.ml": no address associated with hostname
![Screenshot_20200104-213721](https://user-images.githubusercontent.com/4528445/71771549-352eee00-2f3d-11ea-93b0-d975d9ee9f67.jpg)

**Comment by SnakeDoc83** [comment]
Either they're down or they changed domain names again.  If it's the former, nothing we can do.  If it's the latter, someone just needs to find it.

**Comment by SnakeDoc83** [comment]
Just joined their discord to do some research.  Seems their website is finito; it was only meant to be temporary and from now on they'll be publishing to MangaDex exclusively.
