### ISSUE TITLE
[Bug] Source Name : Update required for Mangadex Extension.

### ISSUE THREAD

**Issue by Birsing** [inorichi/tachiyomi-extensions#1972]
### Device information
* Tachiyomi extension version: 1.2.73
* Tachiyomi version: 0.8.4
* Android version: 9.0

## Steps to reproduce
1. First Step - Open Tachiyomi, and go to "Catalogues"
2. Second Step - Select "Mangadex"

### Expected behavior
It should have shown the manga list.

### Actual behavior
We get an error "Unable to resolve host :mangadex.org. No host name or address associated."

**Comment by arkon** [comment]
See #1970
