### ISSUE TITLE
[Source Request] MangaDex.cc

### ISSUE THREAD

**Issue by Fox-of-Embers** [inorichi/tachiyomi-extensions#1974]
### Source Website
Website can be found at MangaDex.cc.

### Other Details
Since MangaDex.org is unavailable for an unknown amount of time, would it be possible to create a second source for the provisional website?

**Comment by patrickhgb** [comment]
Didn't they fully migrate to .CC?

**Comment by Fox-of-Embers** [comment]
Not fully, some mangas are still not uploaded, they will upload the rest in the coming week.
Quote: "2. Due to the length of time it takes to move the domain, older chapters aren't available just yet. It will probably be the beginning of next week before they're available but we're hoping the move will complete before the weekend is over. You can, however, upload new chapters, comment on old chapters, etc., etc."



About the .cc domain being provisional:
"1. Our .cc domain is temporary for now. Our .org domain was acquired via our reseller, who has removed us from CF and have stopped supporting us due to legal pressure. .org will be unavailable until the transfer to our new provider completes."

"- Similarly, any other links pointing directly to mangadex.org in places such as title/group descriptions etc. will obviously not work unless edited, but since we're going to go back to .org eventually, probably no reason to fix those"

The quotes are from this announcement:
https://mangadex.cc/thread/200708/1

**Comment by Birsing** [comment]
So we cannot read from Mangadex through Tachiyomi, for a while?

**Comment by Deathray-II** [comment]
for those interested to actually make a PR and test it, it should be as simple as editing the `baseUrl` and the `cndUrl` variables in `src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt` but it seems that their CDN is not up atm, as all the chapters that are up, are pulled from mangadex.cc insted of `s0` or `s5` or whatever `.mangadex.cc` so we might want to change that to simply `mangadex.cc` for now

**Comment by CarlosEsco** [comment]
#1969

**Comment by Fox-of-Embers** [comment]
I honestly do not understand why you closed this request.
The Bugreport wanted to change the source, but I ask for an additional source, since we
have no idea how long it will take until MangaDex.org will be back.

**Comment by CarlosEsco** [comment]
If the domain does not get transferred in a timely matter. aka by next week then will consider a separate source.
