### ISSUE TITLE
[Feature Request] (readcomiconline.to )add a quality picker for this source

### ISSUE THREAD

**Issue by fxsparrow** [inorichi/tachiyomi-extensions#1976]
Readcomiconline.to has 2 quality available for reading comics low quality /high quality.
If possible can this extension have a quality preference.

**Comment by fxsparrow** [comment]
![Screenshot_2020-01-05-14-40-48~3](https://user-images.githubusercontent.com/47497822/71779750-027f0700-2fca-11ea-86f9-e4e2e3a5700a.png)
![Screenshot_2020-01-05-14-40-36~2](https://user-images.githubusercontent.com/47497822/71779751-03179d80-2fca-11ea-9e06-0f8c12019a16.png)

**Comment by CarlosEsco** [comment]
Do you want the low quality?  It defaults to the high quality last I knew

**Comment by fxsparrow** [comment]
Yeah..
For when I am in places with really bad network/low on data and needs to read some new issues it will really helpful.also they're some comics in high quality takes a lot of Mbs sometimes 70-80 per one issue
