### ISSUE TITLE
[Source Request] mangadex

### ISSUE THREAD

**Issue by beteng-Q** [inorichi/tachiyomi-extensions#1977]
### Source Website
https://mangadex.cc/

### Other Details
Mangadex changed their hosts after targeted by DMCA subpoena

**Comment by ZeroExistence** [comment]
I changed the URLs, so it would appreciate it if it can be checked. Thanks!
#1978

Not sure if this is enough change though.

**Comment by MerradOklom** [comment]
![Screenshot_2020-01-05-11-06-22](https://user-images.githubusercontent.com/43864503/71781301-bde47300-2fab-11ea-92eb-8e3c9577591c.png)
#1970 
There are no plans for this, at least until MD goes back to use their .org domain.

**Comment by ZeroExistence** [comment]
@MerradOklom - yeah, just noticed the closed PR.

Is it not possible to create a new MandaDex-Cc extension, then migrate/copy existing MangaDex library to MangaDex-Cc extension? I assume it's only feasible when you play with the backup itself?

The restoration of the .org domain may take a while, so playing with some quickfixes would be great.

**Comment by CarlosEsco** [comment]
The .org is expected soon.  If you put a cc extension when it's move .org it would need another new release to support the old .org. Also a temporary release only allows chapters that have been uploaded in last day to present the
