### ISSUE TITLE
[Bug] ReadMangaToday doesn't show any results

### ISSUE THREAD

**Issue by USFHunTer** [inorichi/tachiyomi-extensions#1980]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
After installing ReadMangaToday extension i should be able to load chapter from it

### Actual behavior
ReadMangaToday doesn't show any results after installing the extension

### Other details
Additional details and attachments.

**Comment by SnakeDoc83** [comment]
This is a problem with the source--the page being scraped for popular is blank.  You can still browse by latest or use search.  As for popular, it seems like something RMT would want to fix on their end; so not really worth changing in the extension at the moment.

**Comment by evo85210** [comment]
Also having this problem, but I've noticed that when viewing the latest section, it'll always give me java.lang.exception challenge error, then if I press retry, it'll load normally. 
Not sure if this is affecting my library from getting updates.

**Comment by SnakeDoc83** [comment]
@evo85210 That's a cloudflare issue, it can happen with any extension at the moment.  It might have some effect on your library updates but not to an extent that you should worry much.

**Comment by SnakeDoc83** [comment]
@arkon This can be closed, source fixed their issues, extension works as-is again.
