### ISSUE TITLE
[Bug] Extension  TuMangaOnline :  "Expected URL scheme 'http' or 'https' no colon was found"

### ISSUE THREAD

**Issue by faritvidal** [inorichi/tachiyomi-extensions#1986]
### Device information
* Tachiyomi extension version: 1.2.14
* Tachiyomi version: 8.4.5
* Android version: 10
* Phone Brand: One Plus 6t

## Steps to reproduce
1. Download extension TuMangaOnline
2. Try open any manga

### Expected behavior
Open Normally the manga, but it shows in an error instead

### Actual behavior
shows in an error instead   "Expected URL scheme 'http' or 'https' no colon was found"

### Other details
 "Expected URL scheme 'http' or 'https' no colon was found"

**Comment by arkon** [comment]
Can just keep all the TMO issues to #1957
