### ISSUE TITLE
Mangadex Chapter Date

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi-extensions#199]
I'm not clear if it's the app but I'm guessing it's related to the extension, Mangadex 1.2.4
Date not available *for new chapters post new update. 

![screenshot_2018-02-15-10-53-00-426_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/23010526/36241801-7263b3aa-123e-11e8-85c7-35009e2983d3.png)

Tachiyomi r1343
Mangadex All 1.2.4

Edit: info after the asterisk (*)

**Comment by Skcyte** [comment]
Probably something changed on their side. So the parsing most likely to be broken. 
Wait for devs confirmation.

**Comment by bbtora** [comment]
While I would say it's been solved but, on my device the extension shows as an entirely different source. 

It has all the manga with chapter date showing but it's not the one that's in my library. 
I can actually have the title both from the updated source and the previous source in my library.

**Comment by CarlosEsco** [comment]
@bbtora Its supposed to show as a difference source the package switched from 1.2.3 which had only english to 1.2.4 which has all languages.  1.2.5 will update over 1.2.4.  Easiest thing to do would be uninstall 1.2.3 and 1.2.4.  Then install 1.2.5 you wont lose any manga in your library and then when there is another update aka 1.2.6 it will just show as update button in the extensions page.

**Comment by bbtora** [comment]
The problem occured after updating from 1.2.4 to 5. 
I must correct that while it's not showing as a different extension but I can actually have two same titles one from the previous version and the new version too in my library. 
One doesn't have the chapter date while the other does

**Comment by CarlosEsco** [comment]
I might be wrong but i think you not seeing date is making it seem like its the old extension.  Can you swipe down in the chapter list for the manga where date doesnt show?  The data is cached and the swipe will force to re pull the data

**Comment by bbtora** [comment]
Here is the problem I'm trying to convey...

![screenshot_2018-02-17-21-45-00-187_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/23010526/36343011-571efcc2-142c-11e8-9948-c4b71b7d6093.png)

**Comment by bbtora** [comment]
The new version manga is all new to the library with no earlier saved tracking or reading history.

I also tried uninstalling the extension and reinstalling it but that didn't help either.

**Comment by CarlosEsco** [comment]
Can you attach screen shots of boths info page?

**Comment by CarlosEsco** [comment]
NVM I am able to repeat this let me look into it

**Comment by bbtora** [comment]
Manga in 1.2.4 (There was a new chapter a few hours ago so the date has been updated in info page)
![screenshot_2018-02-17-21-52-42-342_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/23010526/36343126-19a02ae0-142e-11e8-868a-a31c92594bb2.png)

Manga in new 1.2.5
![screenshot_2018-02-17-21-52-48-623_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/23010526/36343133-2960fca2-142e-11e8-8c74-318569863bb4.png)

Sorry for the poor edit skills.

**Comment by Terrill1988** [comment]
When you look in json from backup, you will see that links changed
/manga/19193
/manga/19193/maou-jou-de-oyasumi

**Comment by CarlosEsco** [comment]
Yep just saw that.  im pushing 1.2.6 shortly

**Comment by CarlosEsco** [comment]
@bbtora just remove any of the 1.2.5 ones you added and add them again when 1.2.6 comes out should be in next ten mins or so

**Comment by bbtora** [comment]
Okay. Thanks for the update!

**Comment by CarlosEsco** [comment]
One thing is dates won't show currently for old chapters cause there isn't a way to update the metadata for chapter if the chapter name,url or scanlator didn't change.  Working on getting something in the main app to handle metadata changes

**Comment by bbtora** [comment]
So the initial issue remains somewhat unresolved right? Maybe we should keep this one open.

**Comment by CarlosEsco** [comment]
so dates for newly added manga will work fine.  As for manga in your library you could remove it from library clear database in settings and then re add it.  Should have a pull request of some sorts to update chapter metadata added to tachiyomi later

**Comment by BaronKrause** [comment]
As far as the doubling is concerned, I noticed the same thing when going to 2.4. It seems to be treated as a different source has the same name/saves to a folder of the same name. If you have lets say 4 chapters downloaded and enter both duplicate entries, both show the same files, so if you just want your library sorted out just delete the old entry in your library without deleting the files and re search/favorite any previously added entries, should not be any need to redownload anything.

**Comment by CarlosEsco** [comment]
@bbtora when this gets merged into the main app swipe to refresh will update the metadata.

**Comment by CarlosEsco** [comment]
@BaronKrause the cause is because the unique id for a source a manga uses is the url 
at some point Mangadex changed from 
/manga/1044/
to 
/manga/1044/kimagure-orange-road

so Tachiyomi is seeing them as different manga.  What i did with 1.2.6 was removed everything after the last /  to make sure Tachiyomi sees these as the same

**Comment by bbtora** [comment]
@CarlosEsco Thank you. Will do that.
