### ISSUE TITLE
[Bug] MangaRock : The Manga info and chapters do not load

### ISSUE THREAD

**Issue by 0mniscience** [inorichi/tachiyomi-extensions#1990]
### Device information
* Tachiyomi extension version: 1.2.15
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. First Step
Open up the app and go to mangarock.
2. Second Step
Try to open any manga.
### Expected behavior
The manga should load.

### Actual behavior
Some manga show "page list is empty" when you select a chapter, while the others don't even load the manga information and only show "value manga is licensed at data type java.lang.string cannot be converted to JSONObject"

### Other details
![Screenshot_20200106-003913](https://user-images.githubusercontent.com/49893555/71798021-7ba84980-301e-11ea-923e-3e897dc2271d.png)
![Screenshot_20200106-004910](https://user-images.githubusercontent.com/49893555/71798022-7ba84980-301e-11ea-9ce7-7a71b4c5909f.png)

**Comment by SnakeDoc83** [comment]
They've removed that manga from their site, you can't read it any more.  Further, Manga Rock is dying.  Use a different source.

**Comment by anakaiti** [comment]
I'm having the same issue on all series, not just licensed ones.  
I'm on the r1571 with extension 1.2.15.

**Comment by 0mniscience** [comment]
I did make this post because all series weren't loading but now I see that mangarock is shut down. Thanks for clearing this up @SnakeDoc83.
