### ISSUE TITLE
[Bug] MangaRock: Page list is empty

### ISSUE THREAD

**Issue by Fooftilly** [inorichi/tachiyomi-extensions#1993]
### Device information
* Tachiyomi extension version: 1.2.15
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. Click on chapter and it woud tell that page list is empty. Tryed this on few mangas and the problem is same only on mangarock source.

### Expected behavior
This should have happened

### Actual behavior
This happens instead

**Comment by arkon** [comment]
MangaRock shut down.
