### ISSUE TITLE
[Bug] 1stkissmanga(Madara) : Failed to load chapters

### ISSUE THREAD

**Issue by DumpDumpDump** [inorichi/tachiyomi-extensions#1995]
### Device information
* Tachiyomi extension version: 1.2.41
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. Open any chapter of any manga

### Expected behavior
The chapter's pages loaded and shows images

### Actual behavior
It keeps showing Retry button

### Other details
The update function works fine. 
I can also open the details of any comic. 
Browsing the catalogue doesn't show any problem. 
I can load the chapters properly when I tried opening it directly to their website using web browsers.

**Comment by happywillow0** [comment]
`private val cdnUrl = "cdn.1stkissmanga.com"`

Current CDN is `1stkissmanga.b-cdn.net/`

I'm not sure if they switched everything over or if it is just for new updates. (looks like everything as far as I saw). I'm at work and can't update and test yet so if someone else wants to do it, feel free.
