### ISSUE TITLE
[Bug] Manga Rock Manga Not Loading: "Page List is Empty"

### ISSUE THREAD

**Issue by GentlemanGamer94** [inorichi/tachiyomi-extensions#1996]
### Device information
* Tachiyomi extension version: Manga Rock
* Tachiyomi version: 8.4
* Android version: 10

## Steps to reproduce
1. First Step: Load any Manga added from Manga Rock Extension
2. Second Step: Error Occurs

### Expected behavior
 Manga loaded

### Actual behavior
This happens instead: "Page List is Empty" error. Cache has been cleared as well as app data, everything's been reinstalled, error still exists.

**Comment by arkon** [comment]
Manga Rock is dead.
