### ISSUE TITLE
[Bug] Cyanide & Happiness : No dates in chapter list

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi-extensions#1998]
### Device information
* Tachiyomi extension version: 1.2.1
* Tachiyomi version: r1581
* Android version: 9

No dates shown in chapter list

### Other details
@SnakeDoc83 Please look into it.

**Comment by SnakeDoc83** [comment]
The date is part of the chapter name; I thought it'd be redundant to set it elsewhere but you'd find it useful?

**Comment by bbtora** [comment]
New chapters do not show in Library Updates otherwise.

**Comment by SnakeDoc83** [comment]
Oh, really?  Huh.  Alright, I'll take care of it.
