### ISSUE TITLE
[Question] F-Droid/Extension KissManga Source difference from Bundled KissManga Source?

### ISSUE THREAD

**Issue by BaronKrause** [inorichi/tachiyomi-extensions#200]
Just wondering if there is any difference with the KissManga source available on the F-Droid repo/Extensions list from the one bundled with Tachiyomi (the bundled sources don't show a version number that i'm able to find at least).

**Comment by CarlosEsco** [comment]
There isnt

**Comment by inorichi** [comment]
Unless you have an outdated version of Tachiyomi installed, there isn't, but extensions takes precedence when loading so you can have the bundled outdated but still use the extension.
