### ISSUE TITLE
[Bug] Manga Life : Can't read manga

### ISSUE THREAD

**Issue by MrGumms** [inorichi/tachiyomi-extensions#2007]
### Device information
* Tachiyomi extension version: 1.2.1
* Tachiyomi version: 0.8 4
* Android version: 10

## Steps to reproduce
1. Attempt to load any manga from the manga life source.

### Expected behavior
Load manga from manga life source.

### Actual behavior
Error Message Appears
Attempt to invoke virtual method 'java.lang String org.jsoup.nodes.Element.attr(java.lang.String)' on a null object reference.

**Comment by bad-guy678** [comment]
Same problem here too

**Comment by xPatogeno** [comment]
This is because they changed the URL from the website.

 https://manga4life.com

**Comment by happywillow0** [comment]
MangaLife has changed their website and the extension will require a minor or major rewrite and update. 

Someone will work on it at some point (I might give it a try later when I have time). 

Thank you for your patience.

**Comment by strflw** [comment]
Why was this closed? Was it fixed?

**Comment by CarlosEsco** [comment]
probably cause the source completely changed.  Its not manga life anymore and will need a new extension with a new name.  It effectively is dead

**Comment by xPatogeno** [comment]
> Why was this closed? Was it fixed?

Yes. It was fixed
