### ISSUE TITLE
[English] Tsumino.com r18+

### ISSUE THREAD

**Issue by metroid112** [inorichi/tachiyomi-extensions#201]
Arguably one of the best hentai manga/doujin site on the internet because of a huge variety of features, one of the things I love the most about it is how clean the titles are (avoids the usual bullshit of including translators/languages/etc). Not only that but it's one of the few sites which group series together and also has a system to keep track of the progress within each chapter. I could go on forever but I'm not here to promote the site itself. 
I'm no programmer myself but if anyone's up to it, I'd love to see this source added to Tachiyomi as an extension.

**Comment by CarlosEsco** [comment]
Source could be added but any other features unique to the site would not be.  You could also look into TachiyomiEH fork which has this source https://github.com/NerdNumber9/TachiyomiEH

**Comment by lewdstuff** [comment]
Would appreciate this too

**Comment by as280093** [comment]
Here the icons
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3615325/ic_launcher.4.zip)
