### ISSUE TITLE
[Bug] Can't read or download manga

### ISSUE THREAD

**Issue by Vecr0z** [inorichi/tachiyomi-extensions#2010]
Device information
Tachiyomi version: 0.8.4
Android version: 9 PPR1

I wanna read or download a manga but it says Page list empty, and my extensions are all updated

Expected behavior
Open/download manga

Actual behavior
Error Page list empty

**Comment by arkon** [comment]
Please specify the sources you're having issues with.

**Comment by Vecr0z** [comment]
I can't read any manga at all, from all extensions, I add manga to library, click read and it says Page list empty, I tried over 20+ mangas, none are working. Tried downloading them not working. I can only read mangas I had downloaded before.

**Comment by CarlosEsco** [comment]
there are 100+ extensions.  specific one you are trying

**Comment by cybernami** [comment]
Manga Rock does this...

**Comment by cybernami** [comment]
#1997 might be the reason

**Comment by Vecr0z** [comment]
Mangarock and Kissmanga

**Comment by Vecr0z** [comment]
It's because of mangarock and kissmanga, others are fine thanks.
