### ISSUE TITLE
[Bug] TuMangaOnline : Not loading any manga, stuck in retry

### ISSUE THREAD

**Issue by faritvidal** [inorichi/tachiyomi-extensions#2011]
### Device information
* Tachiyomi extension version: 1.2.15
* Tachiyomi version: 8.4.5
* Android version: 10

## Steps to reproduce
1. download the extension tuMangaOnline version 1.2.15
2. try to open any manga using this source

### Expected behavior
That there will be the manga that you want to read without problems

### Actual behavior
when the sleeve is opened it stays on a black screen with a button in the center that says "retry"

### Other details
I'm getting a oneplus 6t cell phone, today the application from version 1.2.14 to version 1.2.15 was updated but it still doesn't work

**Comment by happywillow0** [comment]
*sigh\*

> tumangaonline no funciona actualmente, es debido a los cambios que hacen para rastrear bot's.
> actualmente sigue funcionando lector manga, que es de los dueños de tmo.
> 
> TuMangaOnline does not work currently due to the changes they make to track bot's.

Lector Manga (also by the same people) is currently still working as I am aware
NineManga ES is also an option.
