### ISSUE TITLE
[Source Request] mangakyo

### ISSUE THREAD

**Issue by beteng-Q** [inorichi/tachiyomi-extensions#2016]
### Source Website
Website can be found at https://www.mangakyo.com/

### Other Details
Easy downloading an underrated manga in here

**Comment by SnakeDoc83** [comment]
Probably could be added to WPMangastream

**Comment by beteng-Q** [comment]
Let me try

Pada tanggal Kam, 9 Jan 2020 02.47, Mike <notifications@github.com> menulis:

**Comment by as280093** [comment]
**Here are the icons:**
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/4050289/ic_launcher.20.zip)
