### ISSUE TITLE
[Bug] NinemangaEn : Wrong address

### ISSUE THREAD

**Issue by NanayaRyuuichi** [inorichi/tachiyomi-extensions#2017]
### Device information
* Tachiyomi extension version: Ninemanga v1.2.7
* Tachiyomi version: Stable v. 0.8.4 & EH v.8.4-5EH
* Android version: 7.1 & 9.0

## Steps to reproduce
1. Opening a manga in NinemangaEn

### Expected behavior
Manga and Chapter loaded normally, webmode open Ninemanga website normally

### Actual behavior
Error pop up : unable to resolve address "en.ninemanga.com/http" no address associated.
![Screenshot_2020-01-08-18-44-25-082_eu kanade tachiyomi eh2](https://user-images.githubusercontent.com/51222187/71975718-3d41a300-3247-11ea-9438-1d3aa620c14d.png)

Webview -
![Screenshot_2020-01-08-18-44-32-982_eu kanade tachiyomi eh2](https://user-images.githubusercontent.com/51222187/71975606-f5228080-3246-11ea-91eb-669db568f7c7.png)

**Comment by happywillow0** [comment]
Are you still having this issue? I just installed NineManga1.2.7 and loaded up Supernova on NineMangaEn and things loaded fine.

**Comment by NanayaRyuuichi** [comment]
> Are you still having this issue? I just installed NineManga1.2.7 and loaded up Supernova on NineMangaEn and things loaded fine.

The issue is kinda weird, sometime it works sometime it is bugged.
And it concern the Ninemanga address itself not the manga since all manga can be plagued with the bug.
