### ISSUE TITLE
[Bug report] <manhwa18.net>: <madara extension >

### ISSUE THREAD

**Issue by fawadkhan121** [inorichi/tachiyomi-extensions#2019]
### What feature should be added to this source?
Manhwa 18.net not working i have tried web view but its saying 404 error but when i tried to open on simple web browser its working

**Comment by joseph619** [comment]
This is a bug report, not a feature request. Change your thread title and put bug report.

**Comment by happywillow0** [comment]
What version are you running for Madara and FMReader?

Manhwa18.net was moved due to their site switching software.

**Comment by joseph619** [comment]
This should be changed to FMReader instead of Madara, and Manhwa18.net hasn't been dmworking for sevwral days now due to layout change.

**Comment by fawadkhan121** [comment]
It started working again

**Comment by fawadkhan121** [comment]
Yes the layout was changed and not it reverted back again
