### ISSUE TITLE
Henchan not working

### ISSUE THREAD

**Issue by Tosterr1** [inorichi/tachiyomi-extensions#2024]
Device information
* Tachiyomi version: 0.8.4
* Android version: 4.4.2

Expected behavior
IDK

Actual behavior
IDK

Other details
Nothing

**Comment by SnakeDoc83** [comment]
Not much detail to go on here.

That said, their website seems to be down; so I can only assume that's the issue here.

**Comment by SnakeDoc83** [comment]
@arkon This can be closed, site is back up and the extension works as is.
