### ISSUE TITLE
[Bug] AllPornComic (Madara ext) :  java.lang.Exception: Challenge not found

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi-extensions#2029]
Extension version: 1.2.42

This error messages shows up in Browse. Force-quitting and reopening didn't fix the issue.

**Comment by happywillow0** [comment]
There is a (temporary?) block based on the "browser" that we are using. 
The browser version is "randomly" changed based on the day and time. 

Check in tomorrow to see if the block list gets updated or if it goes though. 
Or we can change the randomization code some more.

**Comment by joseph619** [comment]
okk

**Comment by happywillow0** [comment]
The next time someone edits Madara, they should also make the following change:
private val day = SimpleDateFormat( "**~~d~~**d", Locale.US).format(Date()) //take out the extra d

It's a small edit which really only affects the first 9 days of each month.
