### ISSUE TITLE
MangaDex 1.2.6 Timeout error on downloads

### ISSUE THREAD

**Issue by BaronKrause** [inorichi/tachiyomi-extensions#203]
Just updated to the new 1.2.6 update to the MangaDex source and it fixed the chapter date issue, but i'm noticing that when I download a series I will often get timeouts on random chapters when Tachiyomi tries to initiate the download (not mid download). If you delete the entry/files and try again you still get random timeouts (roughly 1 out of every 5-6) but it will be on different chapters, so it doesn't seem to be an issue with the source files.  After it finishes and the download queue just has the timed out chapters you can just have it try again and they will download (unless a few randomly time out again, in which case you can just try again)

Happens on both my phone and tablet. Maybe the extension or tachiyome needs a longer timeout?

**Comment by CarlosEsco** [comment]
For now just keep repeating when they fail.  Mangadex website is super super slow.  They are supposedly getting a new server soon.

**Comment by f0lie** [comment]
I can confirm that the servers are super slow. Almost every thing on the website is slow on tachiyomi. Oddly enough, the mobile website works reasonablely well.

**Comment by BaronKrause** [comment]
Just tried it at super late off hours and it maybe hot 1 time out every 20-30 chapters, big difference.

**Comment by CarlosEsco** [comment]
Yea their server can't handle the load currently.  Off hours is completely different things actually load after a second and stuff downloads

**Comment by CarlosEsco** [comment]
i increased timeout in 1.2.8 version to 30s per a request.
