### ISSUE TITLE
[Bug] Mangadex : HTTP error 403 on mangadex extension

### ISSUE THREAD

**Issue by Mannenn** [inorichi/tachiyomi-extensions#2031]
### Device information
* Tachiyomi extension version: 1.2.76
* Tachiyomi version: 0.8.4
* Android version: 7.0

## Steps to reproduce
Try to open any mangadex manga

### Expected behavior
Open the reader normally

### Actual behavior
A message saying HTTP 403 error pops up

**Comment by CarlosEsco** [comment]
reader is fine again

**Comment by Mannenn** [comment]
![Screenshot_2020-01-09-18-09-39](https://user-images.githubusercontent.com/59537822/72104950-41cf8f80-330b-11ea-95c4-c5fc4c37bdf3.png)

**Comment by Mannenn** [comment]
@CarlosEsco

**Comment by CarlosEsco** [comment]
are you able to access through the webview?

**Comment by Mannenn** [comment]
yes

**Comment by Mannenn** [comment]
oh wait its working normally now
