### ISSUE TITLE
[Source Request] Yaoi Toshokan

### ISSUE THREAD

**Issue by MXThink** [inorichi/tachiyomi-extensions#2040]
### Source Website
Website can be found at https://www.yaoitoshokan.com.br/.

### Other Details

Language: Portuguese (Brazil)

**Comment by SnakeDoc83** [comment]
>Access Denied You don't have permission to access on this server.

Site's region locked?

**Comment by MXThink** [comment]
probably ;(

**Comment by as280093** [comment]
**Here is the icon's**
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/4050274/ic_launcher.19.zip)

**Comment by alessandrojean** [comment]
They use Madara, so I think it can be added to the extension. However, I have never worked with the Madara extension, it's better that someone with experience add it to the extension sources.

**Comment by happywillow0** [comment]
I was feeling nice so I bought a month of a VPN so I could access the site. I'm taking a look now and trying to work around the overrides that I need to put in Madara.

**Comment by MXThink** [comment]
Thanks <3
