### ISSUE TITLE
Ninehentai/thumbnail and actual manga and tags to match

### ISSUE THREAD

**Issue by Pineapplepe** [inorichi/tachiyomi-extensions#2042]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1.download 0.8.4
2.add the attachment go to a different wifi (optimum to verison) 
### Expected behavior
Thumbnail should show the write manga

### Actual behavior
It showing a random manga title from a long time ago

### Other details
Redownload doesn't fix it either and other sites are extensions are fine and 
Have the accurate title and tags
![Screenshot_20200111-092821_Tachiyomi](https://user-images.githubusercontent.com/59768508/72205766-c5e15e80-3454-11ea-8b9e-a7ba32d1fe42.jpg)
![Screenshot_20200111-092710_Tachiyomi](https://user-images.githubusercontent.com/59768508/72205767-c679f500-3454-11ea-9299-e089b0006c0f.jpg)

**Comment by SnakeDoc83** [comment]
It's a little confusing that you'd post screencaps from 2 different sources.  Are you saying you were viewing something on Ninehentai on one data connection and that when you went to a different data connection somehow all the details (title, author, etc) changed?

**Comment by Pineapplepe** [comment]
Yes but the changes haven't reverted when I came back to the original data
connection. I've tested it on my phone but it was fine. I don't know if it
has to deal with how new device is. Sorry I don't know if this is going to
help.

**Comment by SnakeDoc83** [comment]
Try going to the info tab and pull down to refresh it.

**Comment by Pineapplepe** [comment]
Could you be more specific? If it's for the doujinshi it doesnt change
anything

**Comment by SnakeDoc83** [comment]
Yeah, where you see the details for the affected doujinshi, pull down to refresh.  Nothing changes, it continues to appear exactly as it does in the second pic?

**Comment by Pineapplepe** [comment]
Yep still the exact same title and tags

**Comment by Pineapplepe** [comment]
If there are still anymore questions,I'll try to answer them to my best of
my ability.
