### ISSUE TITLE
[Bug] MangaLife : Chapters won't load

### ISSUE THREAD

**Issue by Jirash** [inorichi/tachiyomi-extensions#2044]
### Device information
* Tachiyomi extension version: 1.2.3
* Tachiyomi version: 0.8.4
* Android version: 7.0

### Expected behavior
Chapters should load normally.

### Actual behavior
Chapters won't load, there's only a retry button, though it's not doing anything. Example: Komi-san can't communicate, Jormungand chapters 2+ and many other titles.

### Other details
None.

**Comment by xPatogeno** [comment]
#2039
