### ISSUE TITLE
[Bug] Mangakalot : Jsoup error on some manga's

### ISSUE THREAD

**Issue by MrAndre96** [inorichi/tachiyomi-extensions#2049]
### Device information
* Tachiyomi extension version: 1.2.8
* Tachiyomi version: r1518
* Android version: 9

## Steps to reproduce
Search for example 'Revival Man' on the source mangakalot
When you get the result for it and check the info page you get the error

### Expected behavior
You get to see the info page and the chapters the manga has

### Actual behavior
You get no results on both the chapter and info screen and get this error instead:
'Attempt to invoke virtual method 'org.jsoup.select.Elements.org.sjoup.nodes.Elemets.select(java.lang.string)' on a null object reference'

**Comment by kingwolf13** [comment]
I checked that what's happening is on mangakalots actual site it redirects you to a completely different site for whatever reason.

**Comment by happywillow0** [comment]
The extension should already account for the re-direct to Nelo.

**Comment by happywillow0** [comment]
Things look good on my end. 

Uninstall Mangakakalot 1.2.8 first
Then install Mangabox 1.2.12

**Comment by MrAndre96** [comment]
Thanks seems like I was using a unsuported version for mangakalot. Works fine on the new one.
