### ISSUE TITLE
Dynasty Scans Search Results

### ISSUE THREAD

**Issue by BaronKrause** [inorichi/tachiyomi-extensions#205]
Been using the Dynasty Scans source a bit lately and figured id list a few issues I noted while using it. 

When using the search some results do not come up as you would expect.

For instance the manga "Linkage" when searched comes up with nothing, but when you enter the dynasty anthologies source and scroll all the way down to the L's you can find and add it, and its listed exactly the way it was typed.

I've also noticed One Shots don't search like you would expect. You can't search the name of a one shot if it isn't part of an anthology, even manually scrolling won't find it listed anywhere. You need find and search the magazine issue it was released under by checking the websites listing and add that magazine as it seems only to be recognized as a chapter of that magazine. You also need to do it manually by entering the Dynasty-Issues source and scrolling down to the magazine title, as searching the names doesn't work.
I haven't found one to try, but I suspect that if there is a oneshot that isn't listed as part of a magazine or a doujin, there might not be any way to find it.

When you search something like "Citrus" the same results come up in every Dynasty source too, even though it should just be a series (and is manually only findable in the series source). It seems as though all the Dynasty sources report back the results of a Series search (except doujin's, nothing ever comes up in there).

I'm not shure if these are things that actually are addressable, for all I know the method used to access the site is really limited. But just in case, here they are.

**Comment by CarlosEsco** [comment]
#219  fixed your 3 issues.  Had to add a oneshots variation also.

**Comment by BaronKrause** [comment]
You rock! Just tested it, it works great! Needed to uninstall the old to install the new, kept saying cant install after download, but once that was done it worked perfect!

**Comment by CarlosEsco** [comment]
If you had fdroid version originally that's probably why

**Comment by BaronKrause** [comment]
it was my mistake, tried on another device and it worked fine.

The mistake was trying chain clicking on the dynasty and mangadex extension update back to back, the install window for dynasty was replaced by the mangadex one, which installed, while the dynasty one failed. The dynasty one then continued to fail the update until I removed and reinstalled it.

**Comment by BaronKrause** [comment]
I'm not sure if there is anything you can do about this, but I noticed an overwhelming amount of oneshots there that they haven't labeled as such, and if it isn't part of a magazine release, is there any way to reach them?

Here is a newly released example called "Jealousy Shure is nice"
https://dynasty-scans.com/chapters/jealousy_sure_is_nice
