### ISSUE TITLE
[Bug] Webtoons : No result when searching with apostrophe

### ISSUE THREAD

**Issue by MrAndre96** [inorichi/tachiyomi-extensions#2050]
### Device information
* Tachiyomi extension version: 1.2.12
* Tachiyomi version: r1518
* Android version: 9

## Steps to reproduce
Search 'Empira's Awakening' on webtoons
Now you will see that you won't get any results (unless you just search with Empira, so without the apostrophe)

### Expected behavior
Get the result with the full name of the webtoon

### Actual behavior
No results

**Comment by happywillow0** [comment]
Check webtoon's website. The search function passes the search to the search box on the website. For whatever reason, webtoons search cannot find `Empira's Awakening` 

If you just search `'s`, it pulls up others with apostrophes

**Comment by MrAndre96** [comment]
weird but seems to be indeed a problem on their side
