### ISSUE TITLE
[Bug] mangasPROJECT: Could not get read token

### ISSUE THREAD

**Issue by maz1no** [inorichi/tachiyomi-extensions#2055]
### Device information
* Tachiyomi extension version: 1.2.5
* Tachiyomi version: 0.8.4
* Android version: Android 8.1.0

## Steps to reproduce
1. Downloading or reading the chapter
2. Having the issue

### Expected behavior
![Screenshot_20200113-015054](https://user-images.githubusercontent.com/38970314/72233714-bb83a980-35a7-11ea-8024-ad70fff768a5.png)

### Actual behavior
![Screenshot_20200113-014343](https://user-images.githubusercontent.com/38970314/72233930-ef130380-35a8-11ea-8de9-e1e1baca8e64.png)
![Screenshot_20200113-014049](https://user-images.githubusercontent.com/38970314/72233679-88411a80-35a7-11ea-8d19-b699a1e91872.png)![Screenshot_20200113-014232](https://user-images.githubusercontent.com/38970314/72233832-5d0afb00-35a8-11ea-82ae-4b29896f7064.png)

### Other details
This maintenance message seems to only appears in webview, in a normal browser the site works normally. So then i came here.

**Comment by maz1no** [comment]
Guys? please don't ignore me.

**Comment by happywillow0** [comment]
Sorry, can't fix what I can't access.
`Error 1020 Access denied`

**Comment by maz1no** [comment]
The site always been region-restricted, i dont think that's the problem. 
there must be a way to fix... also thanks for the feedback

**Comment by SnakeDoc83** [comment]
@maz1no What he's saying is that because the site is region locked, that limits who can work on the problem.  We need access to the site to figure out what the issue is: no access means no way to figure out the issue, which means no way to correct it.

**Comment by maz1no** [comment]
Understood. I can help with something? I'm not a senior programmer but i need this extension working again.

**Comment by 0klux** [comment]
This bug only affects mangasproject, and not all mangas, from my testing, at least One Piece still works fine for some reason.

Also, Mangalivre, which comes with the mangasproject extension, seems to have the exact same content as mangasproject and is working without any problems that I could find. In fact, looking at some commits, the extension maintainer even points out the mangaslivre site is just a mirror of mangasproject,  but with licensed stuff.
So I recommend you to just migrate everything you have to mangalivre, at least temporarily, until mangasproject is fixed.

**Comment by alessandrojean** [comment]
I will take a look and see if I can fix it. Meanwhile, you can use temporarily the MangaLivre catalogue as pointed out by @0klux.

**Comment by SnakeDoc83** [comment]
@alessandrojean I took a look at their website by using a proxy.  I think it's an issue with `val readerSrc = document.select("script[src*=\"reader.min.js\"]")` not having the token in all cases.  Something for you to check anyway.

**Comment by alessandrojean** [comment]
Probably they have changed how the reader works and how they do the request to get the chapter pages, updating the backend and frontend only in the MangaProject and not yet on MangaLivre. Anyway, I will take a look, thanks @SnakeDoc83.

**Comment by alessandrojean** [comment]
Okay, apparently they have changed the script to ```reader.toon.min.js```, so Jsoup will not find the element, resulting the error reported. However, the token it's still there. Tomorrow I will submit a PR fixing it.
