### ISSUE TITLE
Mangadex: can't set cover

### ISSUE THREAD

**Issue by Intervencion** [inorichi/tachiyomi-extensions#206]
Versions: stable 0.6.8, dev r1356, mangadex extension English 1.2.2

Set as cover feature doesn't work. It gives an error "Failed to update cover"

**Comment by Intervencion** [comment]
Didn't notice there was also an extension called all, versión 1.2.6. This one works so I'm closing this.

**Comment by wopian** [comment]
ℹ Probably unrelated to this issue, but your MangaDex extension is the old one. 1.2.3 onwards (1.2.6 currently) is a different extension with multi-language support. Migration just requires uninstalling EN and installing ALL :thumbsup:

**Comment by Intervencion** [comment]
@wopian
Is there a way to install Mangadex All 1.2.6 over Stable Tachiyomi? Don't really want to use Dev to be honest.
