### ISSUE TITLE
[Source Request] Viewcomiconline

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi-extensions#2065]
### Source Website
Website can be found at https://viewcomiconline.com/

### Other Details
A worthy companion to the already existing ReadComicOnline, this source has certain comics not available in the other one, checked and tested by yours truly. Please implement this as an extension, if possible.

**Comment by joseph619** [comment]
It appears the website is down

**Comment by MercerBoi** [comment]
Works just fine from what I'm seeing.
