### ISSUE TITLE
[Bug] Hentai Cafe : No Results is Returned as a Manga

### ISSUE THREAD

**Issue by MCAxiaz** [inorichi/tachiyomi-extensions#2067]
### Device information
* Tachiyomi extension version: FoolSlide 1.2.31
* Tachiyomi version: r1636
* Android version: 8.1

## Steps to reproduce
1. Search something in Global or Hentai Cafe search which should return 0 results

### Expected behavior
No results found

### Actual behavior
A manga called "Nothing to Show Right Now" is returned. Clicking it throws parsing errors.

### Other details
![Screenshot_1578989480](https://user-images.githubusercontent.com/24946428/72325696-85efc680-3662-11ea-8524-cb4aea2097fb.png)

**Comment by rama982** [comment]
Confirmed
