### ISSUE TITLE
[Bug] 1st kiss (madara Source ) broken

### ISSUE THREAD

**Issue by CoutoSH** [inorichi/tachiyomi-extensions#2068]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. First step: try to open any "comic" from the source 
2. Second step: only shows a retry buttom

**Comment by happywillow0** [comment]
The extension is now at version 45 with a fix. Please make sure to update it and try again.

**Comment by samanta-widjaja** [comment]
Although I already updated to the latest version, i still can't download chapter

**Comment by happywillow0** [comment]
Have you tried clearing the chapter cache? The image url has changed and needs to be refreshed.

**Comment by samanta-widjaja** [comment]
I already did that. If i read the chapter via program it's fine (not download). but for download it still can't

**Comment by happywillow0** [comment]
Weird. You cleared the download queue and tried downloading it again? I my phone just downloaded peerless dad fine. Is there a specific manga you are looking at and having trouble with?

**Comment by samanta-widjaja** [comment]
Clear Chapter Cache
Clear Cookies
Restart phone
and voila, it's work. Thanks
