### ISSUE TITLE
[Bug] Various sources: "java.lang.Exception: Challenge not found"

### ISSUE THREAD

**Issue by arkon** [inorichi/tachiyomi-extensions#2076]
A variety of Cloudflare-protected sources aren't working properly on first try within Tachiyomi.

Workarounds include retrying and loading in Webview. It appears to only affect older versions of Android (up to 7.x).

Issue in main repo: https://github.com/inorichi/tachiyomi/issues/2344

**Comment by yurigiu** [comment]
> It appears to only affect older versions of Android (up to 7.x).

I have two devices running Android 9 and this problem happens systematically on ReadComicOnline source (which is indeed Cloudflare-protected).

**Comment by asakurato** [comment]
I also get this message from time to time, on Android 9 (Miui 11).

**Comment by namv22** [comment]
I just got this problem since yesterday on MangaKisa
Android 10

**Comment by ara8ara** [comment]
did manganelo also affected by this bug? android 10,
![Screenshot_20200123-203448](https://user-images.githubusercontent.com/15099415/72990134-32c80180-3e22-11ea-83fc-afc8be037cb8.png)

**Comment by namv22** [comment]
> did manganelo also affected by this bug? android 10,
> ![Screenshot_20200123-203448](https://user-images.githubusercontent.com/15099415/72990134-32c80180-3e22-11ea-83fc-afc8be037cb8.png)

I think it's starting to affect every extension, I was getting it with MangaKisa but now Mangarock is affected by it too

**Comment by SnakeDoc83** [comment]
@ara8ara "Page list is empty" is probably due to something else.

@namv22 Manga Rock is dead--it won't work not due to any bug but because they shut down.

**Comment by ManjaWarior** [comment]
I also have this issue with KissManga whenever I press browse or latest it has the same error message

**Comment by Harunyaanuwu** [comment]
![Screenshot_20200209-221822](https://user-images.githubusercontent.com/60847445/74103797-1e0d9c80-4b8a-11ea-823e-03ad7c406cee.jpg)
Send help ;((

**Comment by happywillow0** [comment]
- Check to see if you can update webview.
- Also try to clear your cookies in app to reset cloudflare. MRM recently changed from auto check to manual captcha too.

**Comment by QuietusWolfe** [comment]
> * Check to see if you can update webview.
> * Also try to clear your cookies in app to reset cloudflare. MRM recently changed from auto check to manual captcha too.

Tried both of these multiple times and it did nothing.

**Comment by arkon** [comment]
Try using the dev version of Tachiyomi.

**Comment by QuietusWolfe** [comment]
I tried, but since I'm a Fire tablet, I keep getting "update WebView" warnings (even after I installed the WebView for Andorid app from the Google store) and the dev build won't import anything other than my categories from my backup file.

When I tried to just load a catalog, I got the WebView warning and then "failed to bypass Cloudfire".

**Comment by joseph619** [comment]
Go to developer settings and set webview to latest version.

**Comment by TheWrightStuff1994** [comment]
@joseph619 There is no option for that in developer settings so there needs to be a option for that for Fire tablet users

**Comment by joseph619** [comment]
Nothing can be done about Webview then. If Webview is a deal breaker for you, I would suggest getting an actual android tablet.

**Comment by QuietusWolfe** [comment]
> Nothing can be done about Webview then. If Webview is a deal breaker for you, I would suggest getting an actual android tablet.

And I'd suggest not being snarky.

**Comment by Flat** [comment]
I don't believe he was being snarky. There is no way for us or you to update webview on an Amazon device. They push out updates to webview when they see fit, see [here](https://forums.developer.amazon.com/questions/152941/update-webview-fireos.html#).

**Comment by QuietusWolfe** [comment]
> I don't believe he was being snarky. There is no way for us or you to update webview on an Amazon device. They push out updates to webview when they see fit, see [here](https://forums.developer.amazon.com/questions/152941/update-webview-fireos.html#).

The "get a real Android tablet" was the snarky part. As for the rest, I know, it's just an annoyance because it means I have to migrate my entire bookmarked library to another source, which is going to take a while. If there's nothing to be done other than that, so be it, 'cause I'm not in a position to get another tablet at this point.

**Comment by joseph619** [comment]
I was not being snarky, I was being serious. Webview is an essential feature on Tachiyomi to solve captcha or login to various sites. And webview is often outdated on Amazon tablets with no way to update. You would need an actual Android tablet to use latest webview.

**Comment by QuietusWolfe** [comment]
> I was not being snarky, I was being serious. Webview is an essential feature on Tachiyomi to solve captcha or login to various sites. And webview is often outdated on Amazon tablets with no way to update. You would need an actual Android tablet to use latest webview.

And Fire tablets are Android tablets. The fact that Amazon wanted to be dumb and use their own version of the OS and not update it and it's components as often as they should doesn't lessen that IMO. But again, I get your point, and since I can't really spare the cash for a new tablet I just went through the process of migrating to a different source. Hopefully Amazon pushes an update at some point, if not no big loss.

**Comment by arkon** [comment]
This should be fine on most devices using Tachiyomi 0.8.5 or newer.

Unfortunately I don't think there's a good solution for devices that don't have updated or configurable webview apps. Regardless, that should be an issue on the main app repo, not this one.
