### ISSUE TITLE
[Bug] MangaDex : Not being able to search

### ISSUE THREAD

**Issue by MrAndre96** [inorichi/tachiyomi-extensions#2078]
### Device information
* Tachiyomi extension version: v1.2.78
* Tachiyomi version: r1518
* Android version: 9

## Steps to reproduce
For example go to the latest manga on mangadex (while being logged in)
Click on a manga and then click on the title (so it will check all the sources on which it is available)
Now you see that mangadex is not between one of those sources (while you know it is)

### Expected behavior
Give the manga you searched for

### Actual behavior
No results

**Comment by arkon** [comment]
https://tachiyomi.org/help/faq/extensions/#mangadex

**Comment by arkon** [comment]
Are you sure you're logged in via the webview and not your regular browser?

**Comment by MrAndre96** [comment]
I was logged in (checked it because it seems that I was logged out and yes this was the webview) but it didn't work. After restarting the app I was logged out again (idk what happend)

**Comment by arkon** [comment]
Did you clear your cookies or forget to check "Remember me"?

**Comment by MrAndre96** [comment]
No didn't clear them and did check the remember me option. Sometimes it occasionally just decides for me to logout (even though it says that it keeps me logged in for a year)

**Comment by arkon** [comment]
Not entirely sure what happened in your case, but it's good that logging in worked.
