### ISSUE TITLE
[Bug] HentaiNexus and HentaiCafe : No Distinction Between "Latest" and "Browse".

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi-extensions#2083]
### Device information
* Tachiyomi extension(s) version: 
1. HentaiNexus 1.2.1
2. FoolSlide 1.2.32
* Tachiyomi version: r1648
* Android version: 6.0.1

## Steps to reproduce
1. Go to Catalogues.
2. Tap on "Latest" or "Browse" in the aforementioned sources.

### Expected behavior
Tapping on "Latest" should show the latest available entries in each source, and tapping on "Browse" should show the default list.

### Actual behavior
Both options show the same thing.

### Other details
None.

**Comment by SnakeDoc83** [comment]
Both sources only have one sort order, which is by date.  There's no way to have differing lists in this case; so the only thing that could be changed is removing "latest" from the catalog so that you only see "browse."

**Comment by MercerBoi** [comment]
Ah, it is what it is then, I guess. I just reported what I observed. Thanks for clarifying.
