### ISSUE TITLE
[Source Request] mangadao

### ISSUE THREAD

**Issue by Reviaz** [inorichi/tachiyomi-extensions#2084]
Website can be found at https://mangadao.com/

With mangarock closed, I cant find other reliable sources for my Manhua (Apotheosis, Last Human, etc.) other than mangadao. I respectfully request for this site to be added to Tachiyomi's extension. Thank you.

**Comment by SnakeDoc83** [comment]
No, don't do it dude, Mangadao's translations are bad.  You can read Apotheosis through Night Comic (Madara) and The Last Human through Meraki Scans.  I'm sure they show up in other sources too and I guarantee you can find whatever manhua you're looking for in sources we already have.  Don't read Mangadao--I'm serious, just don't.

**Comment by Reviaz** [comment]
Alright! I look into those. Thank you for the tips. I hope those have the other manhuas I lost after mangarock's closure, ill also check more of the existing sources.
