### ISSUE TITLE
[Bug] Can't use search tools on mangadex

### ISSUE THREAD

**Issue by 3booo6** [inorichi/tachiyomi-extensions#2085]
### Device information
* Tachiyomi extension version: 1.2.78
* Tachiyomi version: 0.8.4
* Android version: Android 10 (One UI 2.0)

## Steps to reproduce
1. Go to mangadex catalogue  
2. Press on search button and search for anything

### Expected behavior
I should be able to search and find the manga that i want

### Actual behavior
Gives me an error and tells me to press retry which doesn't help

### Other details
This also happens when i try to use filters

**Comment by arkon** [comment]
https://tachiyomi.org/help/faq/extensions/#no-results-when-searching

**Comment by 3booo6** [comment]
Thanks!
