### ISSUE TITLE
[Feature Request] Mangadex: Rating in the info page for a manga

### ISSUE THREAD

**Issue by vishalanandch** [inorichi/tachiyomi-extensions#2097]
Include a field which shows the rating of a manga in the info page. Not a necessary feature but will be good to have.

**Comment by CarlosEsco** [comment]
Too specific to the source that would require a change in the main app

**Comment by arkon** [comment]
I think they mean just having it in the description. Only issue is that it wouldn't always be up to date.

**Comment by CarlosEsco** [comment]
That would be doable if it was included in API. Which it's not
