### ISSUE TITLE
[Bug] MangaDex : Search tool

### ISSUE THREAD

**Issue by Shampo0oing** [inorichi/tachiyomi-extensions#2105]
### Device information
* Tachiyomi extension version: 1.2.78
* Tachiyomi version: 0.8.4
* Android version: 9.0.7

## Steps to reproduce
1. Selecte MangaDex in your catalogues
2. Do a title search

### Expected behavior
This should show you the manga corresponding to your search.

### Actual behavior
This shows you every time the message : "No results found"

**Comment by SnakeDoc83** [comment]
https://tachiyomi.org/help/faq/extensions/#no-results-when-searching
