### ISSUE TITLE
[Bug] allporncomic extension is not working

### ISSUE THREAD

**Issue by Naruto-hub** [inorichi/tachiyomi-extensions#2106]
### Device information
* Tachiyomi extension version: ?
* Tachiyomi version: ?
* Android version: ?

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened

### Actual behavior
This happens instead

**Comment by SnakeDoc83** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/2076

Next time pay attention to what's been posted already and if you're going to make a bug report then actually use the template and provide useful information.
