### ISSUE TITLE
[Bug] MangaDex : Thumbnails fail to load

### ISSUE THREAD

**Issue by Orioz** [inorichi/tachiyomi-extensions#2110]
### Device information
* Tachiyomi extension version: 1.2.79
* Tachiyomi version: 0.8.4
* Android version: 7.0

## Steps to reproduce
1. Browse manga on MangaDex

### Expected behavior
Thumbnails should load for each comic.

### Actual behavior
Only a few thumbnails successfuly loads.
![Screenshot_20200121-224955](https://user-images.githubusercontent.com/15891817/72846269-8dd1eb00-3ca0-11ea-9921-7f2b5ca9e9ce.png)

### Other details
Workaround is visiting the info page of a comic.
This loads the thumbnail successfully and can be seen on the browse page. This needs to be done for each thumbnail that failed to load (most of them).

**Comment by CarlosEsco** [comment]
So some are expected. Your amount is not. Can you go to advanced and clear cache and clear db

**Comment by Orioz** [comment]
Clearing the db immediately improved the loading immensely.
There's still some comics that doesn't load but now it's only a few.

**Comment by CarlosEsco** [comment]
The few is expected. To reduce network calls we are guessing the full size cover url.
