### ISSUE TITLE
xkcd: low quality images

### ISSUE THREAD

**Issue by yambadr** [inorichi/tachiyomi-extensions#212]
Tachiyomi 0.6.8
xkcd 1.2.0

xkcd images are low quality compared to other xkcd apps (eg. Easy xkcd).

**Comment by wopian** [comment]
They're identical to the source images though?

https://xkcd.com/1959/

![](https://imgs.xkcd.com/comics/the_simpsons.png)

**Comment by CarlosEsco** [comment]
I'm just grabbing what the official Json provided..

**Comment by CarlosEsco** [comment]
I can add the 2x but there is no guarantee the url is correct.

**Comment by CarlosEsco** [comment]
#213
