### ISSUE TITLE
[Source Request] multiple arabic sources

### ISSUE THREAD

**Issue by Manga-Killer** [inorichi/tachiyomi-extensions#2122]
### Source Website
https://www.mangaka3rb.com/

https://mangatales.com/

https://www.nakanaide.me/

https://madscientists33.blogspot.com/

**Comment by Manga-Killer** [comment]
Add
https://golden-manga.ml
To them

**Comment by mged** [comment]
give the code for the scrape needed for them

**Comment by CarlosEsco** [comment]
Don't know how this slipped through. But 1 request per a source. Title appropriately and make sure it's not a duplicate
