### ISSUE TITLE
[BUG] Japscan not working

### ISSUE THREAD

**Issue by Ximaxe** [inorichi/tachiyomi-extensions#2125]
### Device information
Japscan extension version: 1.2.13
Tachiyomi version: 0.8.4
Android version: 10
### Steps to reproduce
Install Japscan as extension
Select a manga from its catalog
Then try to read any chapter
### Expected behavior
First page of chapter is displayed and readable

### Actual behavior
Chapter is not loaded and a retry button appears. (Even with retrying multiple times it's still not working).

### Other details
Can't download any chapter.

**Comment by dryx01** [comment]
**Research** doesn't work either.

**Comment by amar33** [comment]
Please fix it i want reaaaaad. 
It's not working since 3 or 4 days .

**Comment by amar33** [comment]
This is still not working..

**Comment by happywillow0** [comment]
Do you have an example of which manga and chapter it is not working on? 

I just tried Spy X Family 9 VF for example and it loaded up for me.

**Comment by amar33** [comment]
All the manga from this source dont Work for me.  
I can see them but the research give me a error 404. 
And of course i can't read, the pictures dont load. 
Even with the new update. 

![Screenshot_2020-01-29-00-43-18-526_eu kanade tachiyomi](https://user-images.githubusercontent.com/56921708/73315510-97bf9500-4230-11ea-92d4-8298eb217d86.jpg)
![Screenshot_2020-01-29-00-43-45-349_eu kanade tachiyomi](https://user-images.githubusercontent.com/56921708/73315511-98582b80-4230-11ea-9afd-23b57eb25fd1.jpg)

**Comment by happywillow0** [comment]
Just to be sure, what version of japscan are you on? 
Images are loading fine on my end. Do they come up when you use webview to look at the chapter? 

I have to defer to @SnakeDoc83 on the search issue as he did that section of code if he doesn't mind taking a look at what is happening there.

**Comment by SnakeDoc83** [comment]
The site used to have a manga directory by letters, so for example "/path/A" for manga starting with the letter "A" that I would search through for the user's query.  Those pages aren't there anymore; so any query 404s right now.
