### ISSUE TITLE
[Source Request] [Indonesian] Komikcast

### ISSUE THREAD

**Issue by horacebmagic** [inorichi/tachiyomi-extensions#2130]
Source:
https://komikcast.co.id

Other Details:
Hi. There is already komikcast extension but it's using https://komikcast.com which i believe it's an old domain, they are already have a new domain. The manga, manhua, and manhwa are more update in the new domain too. 

eg: 
Latest Apotheosis's chap in https://komikcast.com is 283 and,
Latest Apotheosis's chap in https://komikcast.co.id is 411.
I was checking the other Indonesian source/extension too, but it's the same as https://komikcast.com

Hopefully you guys will make this extension.
Thanks before :smiley:

**Comment by beteng-Q** [comment]
the original domain still works well, why should it be changed

**Comment by horacebmagic** [comment]
> 
> 
> the original domain still works well, why should it be changed

There is the reason on the other details and I did not ask for changing the source, I'm using Source Request label. Just like manhwa18 and manhwa18.net
