### ISSUE TITLE
[Meta] Update Genkan logo

### ISSUE THREAD

**Issue by ash123456789** [inorichi/tachiyomi-extensions#2131]
###  Why/Project's Benefit/Existing Problem
I'm the developer behind Genkan, the project runs various scanlation sites. Recently sorted out a proper logo, prefer if it was used instead of the "G" one that was added a long time ago.

### Other Details
Might take a little while to display embedded here since I just disabled hotlink protection on Cloudflare for the domain.

URL: https://genkan.org/images/logo.png

Demo:
![Genkan](https://genkan.org/images/logo.png "Genkan")

**Comment by arkon** [comment]
Your CF config seems to be blocking access to the image.

**Comment by ash123456789** [comment]
> Your CF config still seems to be blocking access to the image.
> 
> Did you want to submit a PR, or did you just want someone else to do it?

Anyone can feel free to submit a PR for this. I have some free time later this week so if no one gets around to it in their spare time, I'll submit a PR for this.

**Comment by SnakeDoc83** [comment]
@ash123456789 Hey, I'm the one who made the extension.  Have you noticed search results are a bit broad for sites using Genkan?  I don't suppose there's a way to request results a little less so?

**Comment by ash123456789** [comment]
> @ash123456789 Hey, I'm the one who made the extension. Have you noticed search results are a bit broad for sites using Genkan? I don't suppose there's a way to request results a little less so?

Hi there, I've noticed a few issues relating to searching and the way it indexes records behind the scenes.

The broadness of the search are to do with fuzzy configuration, every time I tweak it it either returns no results or too many results that are not obvious with how they match. I have a rather large update coming up within the next few months so _hopefully_ some search-related issues should be resolved. Unfortunately, this update will break the extension (sorry in advanced).

**Comment by SnakeDoc83** [comment]
>Unfortunately, this update will break the extension (sorry in advance).

Eh, it happens.  Could you do me a favor though and make a post here or let me know on discord when your changes are live so I know to check on it?
