### ISSUE TITLE
[Source Request]  madara Source 

### ISSUE THREAD

**Issue by baytout** [inorichi/tachiyomi-extensions#2135]
Can you plz  add this website to the app? it's based on madara

https://mangalek.com/

https://golden-manga.ml/

Tanks

**Comment by baytout** [comment]
https://gmanga.me/

**Comment by Manga-Killer** [comment]
أهلًا، هل عندك حساب ديسكورد؟ ولو عندك فموجود بأي معرف وبأي سيرفر؟

**Comment by happywillow0** [comment]
gmanga is running on complicated software to pull from. It might not happen. 
Also, dup to #117

**Comment by CarlosEsco** [comment]
Please have 1 issue per a source request.  and also make sure there is not an existing request open
