### ISSUE TITLE
[Bug] Gufeng manhua : Search 404 error

### ISSUE THREAD

**Issue by pavan3999** [inorichi/tachiyomi-extensions#2140]
![Screenshot_20200128-110335](https://user-images.githubusercontent.com/23577468/73287553-6a1e2000-421f-11ea-9ef5-9d5d5e2c77b0.jpg)
### Device information
* Tachiyomi extension version: 1.2.2
* Tachiyomi version: r1567
* Android version: 8.0

## Steps to reproduce
Casually searching manhua with names in search bar

### Actual behavior
Giving 404 error, even after retry

### Expected behavior
Have to show searched results

**Comment by happywillow0** [comment]
I think this may be because uri is attempting to encode the chinese. I'll double check at some point.

**Comment by happywillow0** [comment]
@pavan3999 
How is the source apart from this bug? 
It seems really slow for me but I wasn't sure if it was my location.

**Comment by pavan3999** [comment]
you mean downloading/reading online? yes, don't know almost zh extensions are  slow for me
