### ISSUE TITLE
[Bug] Manganelo : Error

### ISSUE THREAD

**Issue by samanta-widjaja** [inorichi/tachiyomi-extensions#2142]
### Device information
* Tachiyomi extension version: Mangabox 1.2.12
* Tachiyomi version: 0.8.4
* Android version: 7.11

I can't download in queue or open latest. It's like taking a long time to connect to manganelo. But when i open manganelo.com using opera browser to test it's fine. Help please. Thank you

**Comment by SnakeDoc83** [comment]
I'm guessing you're on the old standalone extension; remove it and install MangaBox for an updated Manganelo.

**Comment by happywillow0** [comment]
What version are you running? 
"Latest" doesn't really tell us any useful information to help you.

**Comment by samanta-widjaja** [comment]
Mangabox 1.2.12

**Comment by happywillow0** [comment]
Hm, ok. Thanks for updating that. 
Is it a consistent issue or could it be a temporary thing (like a connection or ISP issue) ?

**Comment by samanta-widjaja** [comment]
i have this issue for 12 hours already. and on browser such as opera and chrome it's fine

**Comment by samanta-widjaja** [comment]
Sorry, i reboot my phone and the problem solved, thank you
