### ISSUE TITLE
[Source Request] Source Name mangaswat

### ISSUE THREAD

**Issue by baytout** [inorichi/tachiyomi-extensions#2144]
https://mangaswat.com

Can you add this source plz
Tanks

**Comment by joseph619** [comment]
Mangaswat is already added, get WP manga extension

**Comment by happywillow0** [comment]
Um... I didn't see it in the wp manga source yet which is why I made the PR. It's not merged yet. 
I'm not missing anything right?

**Comment by Manga-Killer** [comment]
Um....
I downloaded it, but when i open it a "no result found" message appears.
Is that problem fom my phone or from the source?

**Comment by happywillow0** [comment]
I haven't figured out why it doesn't load at first but if you keep hitting retry it should load.

**Comment by happywillow0** [comment]
Either that or open it in webview first which is also part of dev or a fork.

**Comment by happywillow0** [comment]
Found it! They are using Sucuri protection. There is no auto bypass yet like cloud flare. I might put a note in there later but opening it in webview will pass the browser check.

**Comment by mekodke** [comment]
> Found it! They are using Sucuri protection. There is no auto bypass yet like cloud flare. I might put a note in there later but opening it in webview will pass the browser check.

After I passed the browser check and close the webview, the app close automatically (I guess it has something to do with mangaswat covers loading).
