### ISSUE TITLE
[Bug] Sense Scan : Chapter date missing

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi-extensions#2145]
### Device information
* Tachiyomi extension version: Foolslide 1.2.34
* Tachiyomi version: r1674
* Android version: 9

Date missing in new chapter

**Comment by happywillow0** [comment]
by new chapter, do you mean this one?
![Capture](https://user-images.githubusercontent.com/45346080/73330198-16ff9980-422e-11ea-8381-a23c8ead2802.PNG)

**Comment by bbtora** [comment]
Yep, that's how I noticed the bug.
