### ISSUE TITLE
[Source Request] Astral Library

### ISSUE THREAD

**Issue by dustter** [inorichi/tachiyomi-extensions#2150]
### Source Website
https://astrallibrary.net/

### Other Details
More scan group extensions, more earlier releases. Thank you ^^

**Comment by happywillow0** [comment]
Madara source

**Comment by dustter** [comment]
> Madara source

Where? Or is it just under different name?
![Screenshot_20200129-183501_Tachiyomi](https://user-images.githubusercontent.com/54286558/73381500-27635300-42c6-11ea-8cc4-8e7e5758a5f5.jpg)

**Comment by happywillow0** [comment]
Sorry, I meant it can be added as a Madara source for whoever gets to it.
