### ISSUE TITLE
[Source Request] Newtoki: Fix URL

### ISSUE THREAD

**Issue by mniokyo** [inorichi/tachiyomi-extensions#2155]
### What feature should be added to this source?
This should be a simple fix! The URL moved from newtoki39 to newtoki43 for both the dot com and dot net addresses. Please fix this!

**Comment by happywillow0** [comment]
Does it keep changing? This is the one where you can override the url in the extension settings by hitting details in the extensions page

**Comment by mniokyo** [comment]
Oh I see, thanks for the tip.
