### ISSUE TITLE
[Bug] 扑飞漫画 (ZH) / Pufei: Search result empty

### ISSUE THREAD

**Issue by bajuwa** [inorichi/tachiyomi-extensions#2156]
### Device information
* Tachiyomi extension version: Pufei 1.2.1
* Tachiyomi version: Dev r1675
* Android version: 10

## Steps to reproduce
1. Open "browse" for pufei
2. Search for any series (such as 萌师在上) or commonly used character (such as 王)

### Expected behavior
Should have some results.  I know on previous non-dev version that this same extension version gives matching result(s) for the above characters

### Actual behavior
No results shown.

### Other details
These same steps work as expected using the tachiyomi version 0.8.4 with the exact same extension.

**Comment by arkon** [comment]
I don't get any results in either stable (0.8.4) or dev.
