### ISSUE TITLE
how to reassign manga.url?

### ISSUE THREAD

**Issue by Light-Wing** [inorichi/tachiyomi-extensions#2159]
I'm trying to write an extension, and the url (SManga url) needs to go to a different site not the baseUrl site...

how can I change it? I'm getting errors:
when I try to override it I get: Modifier "override" is not applicable to "local variable"
if I just try to reassign it, I'll get: Val cannot be reassigned 

```
    override fun latestUpdatesFromElement(element: Element) = mangaFromElement(element)
    override fun popularMangaFromElement(element: Element) = mangaFromElement(element)
    override fun searchMangaFromElement(element: Element) = mangaFromElement(element)

    private fun mangaFromElement(element: Element): SManga {
        val manga = SManga.create()
//this is where I want reassign it
        manga.url = "https://example.com"
        return manga
    }
```

**Comment by happywillow0** [comment]
A few extensions take into account different urls. 
Snakedoc worked on Mangabox I think and I wrote up Hiveworks comics. 

Anyways save the url as an absolute url and you will need to override the chapter list request function.

I'll double check when I get to a computer and give you an update.

**Comment by happywillow0** [comment]
Yes, normally you either want to save the url as relative or if it is a absolute url, you want to use setUrlWithoutDomain(). For example

```
<a href = "/manga/">
manga.url = attr("href")

<a href = "http://www.example.com/manga">
manga.url  = setUrlWithoutDomain(attr("href"))
```

However, you want to go ahead and directly set the absolute url as the manga url. 

Then you want to override the method to request the chapter. 

```
override fun chapterListRequest(manga: SManga) = GET( baseurl + manga.url, headers)  //how it normally works
override fun chapterListRequest(manga: SManga) = GET( manga.url, headers) //how you want it to work
```

**Comment by happywillow0** [comment]
Also, chat with us on discord and we can offer other pointers as necessary.

**Comment by CarlosEsco** [comment]
as mentioned if you go into discord you will get more help in the dev-extensions channel

**Comment by Light-Wing** [comment]
Ok, I'll check it the discord, I just didn't have a reason until now to download discord (I have an account, just didn't have much use for discord)

And I'll definitely try what you wrote about overriding the URL, thanks
