### ISSUE TITLE
[Bug] Japscan downloads not working

### ISSUE THREAD

**Issue by Koxmo** [inorichi/tachiyomi-extensions#2164]
### japscan
Website can be found at <www.japscan.co>.

### Other Details
known manga that I can find here

**Comment by SnakeDoc83** [comment]
Source already exists.

**Comment by Koxmo** [comment]
Sorry, it's excatly... The download scan does not work...

**Comment by happywillow0** [comment]
What extension version are you running?

Do you have a example of which manga and chapter you are having issues with?

What is your location? 

I'm testing on a USA connection and the mangas I'm testing load fine.

**Comment by Koxmo** [comment]
Hello !
Manga: one punch man, or solo leveling, or other...

Location: Toulouse in France 🇫🇷

Tachiyomi 0.8.4

**Comment by happywillow0** [comment]
What phone and system are you running? Do you have a custom rom?

What happens when you load the page via webview? Does it pass cloudflare and then load completely?

Tachiyomi 0.8.4 doesn't have the latest cloudflare bypass so that may be an issue. You can try the dev version.

**Comment by Koxmo** [comment]
in google chrome it works, but not in the application

**Comment by happywillow0** [comment]
> What phone and system version are you running? Do you have a custom rom?

I ask this because some phones are having trouble bypassing cloudflare in the app. 

You can double-check if you have any options for webview in the Android system settings, hidden developer options, webview implementation.

**Comment by DiogoVieiraFerreira** [comment]
i have try with dev version and is work

**Comment by Koxmo** [comment]
In mode search not working all version.

Stable app: in the catalog I can go into it and see some manga, I may have some manga, but just before that did not work and that several times.
the search does not work (maybe because the site has no search mode)

Dev app: it works every time, I can't see all the manga on the site, the search mode doesn't work there too

**Comment by Koxmo** [comment]
I have xiaomi redmi note 7, miui 11.0.4.0 stable, original version, no hacked

**Comment by DiogoVieiraFerreira** [comment]
i confirm, the search function doesn't work

**Comment by happywillow0** [comment]
The site doesn't have a search function. They used to have an alphabetized directory but it disappeared too. There is currently not a good way for us to search for a specific manga on the website. 

As for the viewing and downloads, glad to see that the dev version is working better. You can migrate from stable to dev by backing up and restoring your library.

**Comment by Koxmo** [comment]
thank you all, and thank you very much for this backup tip.  At least the problem and known now ...
