### ISSUE TITLE
[Source Request] [french] scantrad

### ISSUE THREAD

**Issue by Koxmo** [inorichi/tachiyomi-extensions#2165]
### Source Website
Website can be found at <scantrad.net>.

### Other Details
known manga that I can find here

**Comment by SnakeDoc83** [comment]
Source already exits (though it's currently scantrad.fr, could be updated).

**Comment by Koxmo** [comment]
Sorry, exactly... The search does not work correctly, I test one punch man and other...

**Comment by happywillow0** [comment]
What exactly is your search terms you are having issue with?

For your example, one punch man is found on the website as `One Punch-Man`

**Comment by Koxmo** [comment]
scantrad works now ... Sorry, I have been using the application for 2 days, maybe the site is not working
