### ISSUE TITLE
[Source Request] [french] novel-france

### ISSUE THREAD

**Issue by Koxmo** [inorichi/tachiyomi-extensions#2166]
### Source Website
Website can be found at <novel-france.fr>.

### Other Details
Star martial god technique is a minimum up to date on this site

**Comment by SnakeDoc83** [comment]
Will be added to Madara.

**Comment by Koxmo** [comment]
thank you for your speed, for the moment I do not see it in the application, nor on the site, so I'm patient.  thank you !

**Comment by SnakeDoc83** [comment]
When Madara version 1.2.51 becomes available you'll be able to read Novel France.  The people who can approve it are more than likely asleep.

**Comment by happywillow0** [comment]
#2167
