### ISSUE TITLE
[Bug] Mangahub: No manga pages are loading

### ISSUE THREAD

**Issue by Adsam112** [inorichi/tachiyomi-extensions#2170]
### Device information
* Tachiyomi extension version: 1.2.4
* Tachiyomi version: latest
* Android version: 5.1.1

## Steps to reproduce
Just open a manga from the source, the pages instantly result in a retry button pooping up

**Comment by happywillow0** [comment]
#2168

**Comment by Adsam112** [comment]
> #2168
So I'm not familiar with this stuff, how exactly do you apply the fix?

**Comment by happywillow0** [comment]
A fix is waiting for review and approval. Once applied, the extension will display as a update is available in the app.
