### ISSUE TITLE
[Bug] Source Name : mangaswat

### ISSUE THREAD

**Issue by baytout00** [inorichi/tachiyomi-extensions#2180]
Mangaswat not working 
Arabic source

**Comment by happywillow0** [comment]
If it is saying no source found, open it up in webview first to bypass the browser check. They are using another service not cloudflare but similar to protect their website. 

*You will want to be on the dev version or a fork to open up webview directly from the catalog screen.

**Comment by baytout00** [comment]
I'm sorry, but it doesn't show anything.

https://drive.google.com/file/d/1mhc9ENmH0L_37cl2zvow5JeJtzaxT-I-/view?usp=sharing

**Comment by happywillow0** [comment]
Install the dev version. http://tachiyomi.kanade.eu/latest
At the same screen ("Browse"), you can use the three dots menu and click "Open in webview"
Once the page loads, you can go back and open the catalog again. 

You can migrate your manga over by backing up from 0.8.4 stable and restoring it into dev.

**Comment by baytout00** [comment]
Thanks, bro.

**Comment by baytout00** [comment]
Hey, bro, the last version of the app (tachiyomi) doesn't work on my phone.Is there any way to run it in a Kitkat 4.4.4 version?

**Comment by CarlosEsco** [comment]
No there is not
