### ISSUE TITLE
[Bug] nhentai : Popular works if not using a tag, but fails otherwise, instead sorting by Date

### ISSUE THREAD

**Issue by OVERPWREDCATSCIENCE** [inorichi/tachiyomi-extensions#2181]
### Device information
* Tachiyomi extension version: 1.2.7
* Tachiyomi version: 0.8.4
* Android version: 8.0.0 on Samsung Galaxy S7

## Steps to reproduce
1. Click search button
2. Type in tag
3. Go to search filters drawer
4. Filter defaults to "Popular," yet the manga is displayed as if it was sorted by "Date."

### Expected behavior
When using a tag the most popular manga should appear, however, it is sorted by "Date." The button should change if it is sorted by "Popular" or if it is sorted by "Date."

### Actual behavior
It is sorted by "Date," even when "Popular" is selected instead. The button also displays "Popular" although, it is sorted by "Date."

### Other details
When the app is opened, it is possible to sort by "Date" and "Popular." However, when using a tag, "Popular" does not work, instead it sorts by "Date," even when the search filter is explicitly changed to "Popular." The page that first appears when the app is first opened is sorted by "Popular" by default, however, when a tag is used, it is sorted by "Date" by default, however, the search filters button does not change to reflect this.

**Comment by GutHib123** [comment]
Same issue. Been around for more than a year. Tried to log in via web view expecting it to be similar to how Mangadex operates but no dice.
