### ISSUE TITLE
[Source Request] the best (arabic)

### ISSUE THREAD

**Issue by Manga-Killer** [inorichi/tachiyomi-extensions#2185]
### Source Website

https://www.theb3st.com/

**Comment by happywillow0** [comment]
I'm having a little trouble navigating the site since I don't read arabic. 
It looks like a forum to me. 

Do they have a reader page? A place to read online the manga posted?

**Comment by mged** [comment]
its a forum not a manga website.

**Comment by yshalsager** [comment]
> I'm having a little trouble navigating the site since I don't read arabic.
> It looks like a forum to me.
> 
> Do they have a reader page? A place to read online the manga posted?

Indeed it's. I suggest closing the issue.
