### ISSUE TITLE
http 400 error message mangahasu

### ISSUE THREAD

**Issue by leoteesh** [inorichi/tachiyomi-extensions#2193]
### Device information
* Tachiyomi extension version: ? 1.2.5
* Tachiyomi version: ?0.8.4
* Android version: ?9

## Steps to reproduce
1. First Step clicking manga and chapter to read in the latest updates, updating saved mangas
2. Second Step

### Actual behavior
This happens instead - getting error 400 messages

### Other details
The website is working fine.

Could you please advise?
Many thanks

**Comment by leoteesh** [comment]
Tried in we view but getting the below message. Anyone else having the same issue
![Screenshot_20200209-103758_Tachiyomi](https://user-images.githubusercontent.com/21075197/74100565-62685080-4b28-11ea-9236-fa1da853c0e8.jpg)

**Comment by happywillow0** [comment]
I've not been able to reproduce this on my phone.

Have you tried clearing chapter cache, cookies, database?

**Comment by Kavboy** [comment]
I had the same problem but now with the new mangahasu version 1.2.6 and after clearing cache, cookies and database it works again

**Comment by origamiii0** [comment]
Can't access manga from mangahasu, how I can fix it?
