### ISSUE TITLE
Dynasty Scans Oneshot bug?

### ISSUE THREAD

**Issue by BaronKrause** [inorichi/tachiyomi-extensions#220]
I might have found an issue with the newly added Oneshot category in the Dynasty Scans extension.

When you browse in it, after 20 results you seemingly get to the bottom and then unlike the other groups it auto loads in more content, but it's just a repeatedly of the first 20, and it will keep going on like that as you scroll down.

Also I'm not sure if there is anything you can do about this, but I noticed an overwhelming amount of oneshots there that they haven't labeled as such, and if it isn't part of a magazine release, is there any way to reach them?

Here is a newly released example called "Jealousy sure is nice"
https://dynasty-scans.com/chapters/jealousy_sure_is_nice

Thanks for always working on this extension, I really do appreciate it.

**Comment by CarlosEsco** [comment]
fixed but had to remove the tag and just limit it to type as chapter this caused chapters from series to also show.  but at least now you can view everything not tagged to oneshot.

as for browse its fixed.

**Comment by BaronKrause** [comment]
Oh this is perfect! Thanks again!

**Comment by BaronKrause** [comment]
Oh this is perfect! Thanks again!

I noticed covers can't be set for these, which isn't a big deal as most these don't have anything that would be suitable for a cover anyway. Is it because Tachiyomi does not allow covers for individual chapters, and this is just kind of a shortcut to a chapter (looking at the file structure, it looks to be the case)?

@CarlosEsco

**Comment by CarlosEsco** [comment]
If you look click on a chapter on their website you will notice they have no cover for them

**Comment by BaronKrause** [comment]
Oh I meant that it won't let you manually set one from a page or a file, it gives a failed error right after selecting the image or page you want to use. I totally get why they wouldn't have a default cover.
@CarlosEsco
