### ISSUE TITLE
[Bug] Union manga extension: aren't working, java error

### ISSUE THREAD

**Issue by Norazoki** [inorichi/tachiyomi-extensions#2200]
### Device information
* Tachiyomi extension version: 1.2.9
* Tachiyomi version: 0.8.4
* Android version: 8.1

## Steps to reproduce
1. Open the extension
2. Try to see the catalog

### Expected behavior
The caltalog should be open and show the manga

### Actual behavior
Nothing happen, just a java error appear.

### Other details
The stable version aren't working neither the dev version.
I had already tried to clean the cookies, the cache and nothing changes.
![Screenshot_20200206-081225-1](https://user-images.githubusercontent.com/60742761/73942836-816ba600-48ce-11ea-84f7-20a03e2d47a5.jpg)
This is the error that always appear.

**Comment by arkon** [comment]
Do you have a VPN or something similar set up?

**Comment by alessandrojean** [comment]
Probably they have changed the domain or something like that, I will take a look.

**Comment by happywillow0** [comment]
Their cert expired back in Dec '19 and they still haven't updated it. 

We may have to switch it back from `https` to `http`

**Comment by alessandrojean** [comment]
> We may have to switch it back from `https` to `http`

That's what I am doing right now.
