### ISSUE TITLE
[Feature Request] Mangalib (RU): Russian title names create problems with tracking

### ISSUE THREAD

**Issue by oplexz** [inorichi/tachiyomi-extensions#2203]
Ever since #2175 was released, titles' names are now being fetched in Russian.
While this may have been the only solution for the "blank title" problem (described by a fellow developer at #2173), now there's a problem with tracking:
I used to tap the "tracking" tab, press "Edit" and it would use the current title's name as the search query (which is the intended way). Well, _sadly_, AniList does not have Russian names, nor is it going to implement them any time soon (or ever), so I have to manually find and type out the English (or rather, Romaji) title name, and that's the only way to go.

I didn't know whether this is a bug (since it used to work correctly until the last Mangalib extension update) or a feature request, so I went with the second one.

**Comment by happywillow0** [comment]
Which title would you prefer? On top, you have three choices:

`Бурный век`
`Hwasan Jeonjaeng` / `Volcanic Age `

`Моя геройская академия`
`Boku no Hero Academia` / `My Hero Academia `

`Обещанный Неверленд`
`Yakusoku no Neverland` / `The Promised Neverland`

Native         `manga.title = document.select(".manga-title h1").text()`
Romaji        `manga.title = document.select(".manga-title small").text().substringBefore("/").trim()`
English        `manga.title = document.select(".manga-title small").text().substringAfter("/").trim()`

**Comment by oplexz** [comment]
Romaji is how Anilist stores/displays their manga, and that's what I'm used to. Ideally, a way to pick one yourself would be great. For example, in extension preferences.
