### ISSUE TITLE
[Bug] Mangahere can not be used!

### ISSUE THREAD

**Issue by Biodie** [inorichi/tachiyomi-extensions#2204]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 8.1

Mangahere can not be accessed and i think its because they changed their website address 
thanks and have fun!

**Comment by happywillow0** [comment]
Is there a specific manga and chapter you can provide as an example? 

For example, I can load up World Customize Creator Chapter 68 which just came out and opens fine with 22 pages.

**Comment by Biodie** [comment]
Hi sorry for the late response
There are a few that I have problems with like :
Comics underground Japan or secret comics Japan 
Thanks for the hard work

**Comment by SnakeDoc83** [comment]
@arkon There have been updates to the extension since this was opened and OP was on an older version of Tachi.  I think this should be closed.
