### ISSUE TITLE
[SOURCE REQUEST]manhuas.net [Eng]

### ISSUE THREAD

**Issue by Samk19** [inorichi/tachiyomi-extensions#2215]
### Source Website
Link of the website 

https://manhuas.net/

### Other Details
Language : ENGLISH 
![Screenshot_20200209-003541](https://user-images.githubusercontent.com/36104528/74090680-2dcaa980-4ad4-11ea-9b4a-18ce49de9a75.jpg)

**Comment by happywillow0** [comment]
Looks like it can be added to Madara.

**Comment by happywillow0** [comment]
Not that there is anything really wrong but just to check in, does this site have anything special as compared to any of the other sites hosting manhuas?

**Comment by Samk19** [comment]
Some chapters available that i couldn't find on other sites.....like Against the gods
