### ISSUE TITLE
[Bug] Japscan(FR) : Encoding patern has changed

### ISSUE THREAD

**Issue by o01210o** [inorichi/tachiyomi-extensions#2219]
### Device information
* Tachiyomi extension version: 1.2.14
* Tachiyomi version: 0.8.4
* Android version: 8.00

Here is the old patern https://github.com/inorichi/tachiyomi-extensions/issues/698#issuecomment-467929831
![image](https://user-images.githubusercontent.com/45663409/74103601-56c25d00-4b1b-11ea-93d4-47f0781a98be.png)

![1](https://user-images.githubusercontent.com/45663409/74112156-32d93880-4b68-11ea-81a5-680872842410.jpg)
(https://i.imgur.com/eRcJBuE.jpg)

Snapshot from the website
![1](https://user-images.githubusercontent.com/45663409/74112159-379dec80-4b68-11ea-95ef-fede01e3cabd.png)
(https://i.imgur.com/WrFyzOI.png)

**Comment by Krylanc3lo** [comment]
Hello,
I tried to update the python code but no luck so far :(
Were you able to fix it?

Thank you

**Comment by nanartoon** [comment]
the latest update didn't include a fix for this problem :( it's too bad. this problem is realy big, lot's of manga have this problem, it's not only on the first volumes you have to look furder

**Comment by o01210o** [comment]
I found this from hakuneko's repo : https://github.com/manga-download/hakuneko/pull/1100
Maybe someone can adapt it to Tachiyomi ?

**Comment by Krylanc3lo** [comment]
I tried but my python skills are not good enough :)

**Comment by CarlosEsco** [comment]
japscan has been removed

**Comment by o01210o** [comment]
:(
