### ISSUE TITLE
[Bug] Japscan: Search not working

### ISSUE THREAD

**Issue by dryx01** [inorichi/tachiyomi-extensions#2222]
### Device information
* Tachiyomi extension version: 1.2.14
* Tachiyomi version: 0.8.4 and dev R1705
* Android version: 10

## Steps to reproduce
1. Install Tachiyomi
2. In the app, install japscan extension.
3. Make a search in the "Catalogues"

### Expected behavior
The search should be successful.

### Actual behavior
No matter what research, it doesn't work

### Other details
I tested the extension with stable and dev version, both doesn't work.
An exemple here:
During the search
![Screenshot_20200209-162827](https://user-images.githubusercontent.com/6872170/74108767-d41eb980-4b7d-11ea-87fb-1ba015f9060c.jpg)
After
![Screenshot_20200209-162832](https://user-images.githubusercontent.com/6872170/74108792-f9abc300-4b7d-11ea-8560-750564a40b65.jpg)

Thanks in advance.

**Comment by happywillow0** [comment]
Just FYI, 

Japscan themselves does not have a search function built into their website. The previous system is broken too (as you noted) because they also took out a alphabetical list of all manga.

**Comment by dryx01** [comment]
So then, there is a method/procedure do add manually manga from japscan without this search function ? Like a conf file to modify ?
Currently there is no way to add more from this source.

**Comment by happywillow0** [comment]
Two of us were talking about different ways to get what you need in discord. 
I might try to type up my method when I have time and test it out. 

If it is early in the alphabet, you can scroll your way though browse currently, or what I do for discovering new manga is to pick it up when it shows up in the Latest section as things get updated. (Still doesn't help for old finished manga though)

We'll link to this issue any workarounds that we might try.

**Comment by dryx01** [comment]
Perhaps a method where the user find the manga in a webview and click on a button when the good manga is displayed.

Thanks for the fast reply.

If the issue is known, then I close the subject.
