### ISSUE TITLE
[BUG] TMO (TuMangaOnline) is not working anymore.

### ISSUE THREAD

**Issue by Kanocchi** [inorichi/tachiyomi-extensions#2223]
Device info:
- Tachiyomi v0.8.4
- Tachiyomi Extension v1.2.9
- Android 9

It seems like it's broken again.

"Explore" tab is throwing HTTP Error 403 (for some reason, you can still lookup at the "Recent" tab) and when you try to read a chapter, it just throw HTTP Error 404.

**Comment by arkon** [comment]
We no longer support TMO (cf. #2196).
