### ISSUE TITLE
[Source Request] Onemanga [English]

### ISSUE THREAD

**Issue by EdvinAkerstrom** [inorichi/tachiyomi-extensions#2228]
### Source Website
Website can be found at https://1manga.co/.

### Other Details
Most up to date source for a lot of manga / manwhas. A lot of rare ones can be found here.

**Comment by happywillow0** [comment]
It looks like they are run by https://mangahub.io/ which we do have an extension for. 
Do you want to check if what you can find there?

**Comment by EdvinAkerstrom** [comment]
They indeed seem to be the same from my limited testing, thank you for the quick response and for informing me of the extension. Closing this for now.
