### ISSUE TITLE
[Bug] Manga Plus extension broken

### ISSUE THREAD

**Issue by RYNAPU** [inorichi/tachiyomi-extensions#2235]
### Device information
* Tachiyomi version:  0.9.761
* Android version: 10

## Steps to reproduce
1. Access the latest tab or manga from the source.

### Expected behavior
It should load everything

### Actual behavior
An error 404.

### Other details
Seems like the API is down since the main site works.

**Comment by arkon** [comment]
Works fine for me. Did it work before for you? Do you have a VPN or ad blocker?

**Comment by RYNAPU** [comment]
> Works fine for me. Did it work before for you? Do you have a VPN or ad blocker?
Nope. I was able to access them Sat. just fine, only issues coming now. 

The 404 error shows when in web view and in browser view.

**Comment by happywillow0** [comment]
> The 404 error shows when in web view and in browser view.

The 404 on web view / browser because the extension is set to go directly to the API and not the website. This is one example where webview doesn't actually tell you what is going on with he extension.

**Comment by CarlosEsco** [comment]
Yesterday  when the ticket was opened, i couldnt access chapters.  Dunno about after the fact maybe their api was down for an hour?
