### ISSUE TITLE
[Bug] Source Name : Mangahasu incorrect thumbnail 

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi-extensions#2236]
### Device information
* Tachiyomi extension version: 1.2.6
* Tachiyomi version: r1719
* Android version: 9

Most Mangahasu thumbnails appear as this

![Screenshot_20200210-223623_TachiyomiAZ](https://user-images.githubusercontent.com/34897862/74326955-51525600-4d59-11ea-95ce-201b189d7148.jpg)

**Comment by happywillow0** [comment]
I looked at this one night and found that it is something that is triggered server side.

The extension is grabbing the correct url for the thumbnail.

However, something triggers the hotlinking protection and the server uses a 302 redirect to the image seen.

**Comment by joseph619** [comment]
Does Clean Database affect Reading history?

**Comment by happywillow0** [comment]
It clears everything not in your library so maybe? If you read something but never bookmarked it, it will be cleared. 

Things in your library is a little harder. There was a different issue open about updating covers.

**Comment by joseph619** [comment]
I see, I will test clear database then. Is there a way to not trigger the hotlinking protection?
