### ISSUE TITLE
[Source Request] loveheaven [japanese]

### ISSUE THREAD

**Issue by railzy** [inorichi/tachiyomi-extensions#2237]
### Source Website
Website can be found at https://loveheaven.net/

**Comment by MerradOklom** [comment]
I think this one can be added to the FMReader extension.

**Comment by pavan3999** [comment]
Rawlh, it's in fmreader extension

**Comment by happywillow0** [comment]
Thank you for your request. 
As mentioned, the website is already part of the extension just under a shorthand name. 

This can be closed.
