### ISSUE TITLE
[Bug] Scantrad (FR) : Missed the 3 first pages

### ISSUE THREAD

**Issue by o01210o** [inorichi/tachiyomi-extensions#2239]
### Device information
* Tachiyomi extension version: 1.2.4
* Tachiyomi version: 0.8.4
* Android version: 8.00

## Steps to reproduce
...

### Expected behavior
Loads all 1-... pages from the website

### Actual behavior
Loads 4-... pages from the website

### Other details
![0](https://user-images.githubusercontent.com/45663409/74481047-fbc49900-4e7f-11ea-9c45-faa0ad63be20.jpg)

https://scantrad.net/mangas/one-punch-man/127
![1](https://user-images.githubusercontent.com/45663409/74481053-febf8980-4e7f-11ea-983d-dc67936d0dfe.PNG)

**Comment by happywillow0** [comment]
The title says `Japscan` but you mean `ScanTrad` right? 

I just checked Chapter 127 of One Punch-Man and it loaded 43 pages for me (which is also weird considering as you said there is 39.

Can you go into Advanced Settings, Clear Chapter Cache and see if this is still happening?

**Comment by o01210o** [comment]
Oh shit, yes it's Scantrad. I just copied it from my last post 😵 
  
  
> Can you go into Advanced Settings, Clear Chapter Cache and see if this is still happening?  

Done and nothing change.

**Comment by happywillow0** [comment]
Interesting, it looks like it has something to do with 0.8.4 Stable. 
You can download dev and see what loads as test yourself. 

However, now that I look at Scantrad via dev, it loads the number of pages as expected but it doesn't load the images correctly. 

Leave this here and someone will take another look and fix things.

**Comment by happywillow0** [comment]
I looked at it again and fixed the selector some more. That help reduce my 43 pages to the correct 39. However, it didn't change how stable is adding the pages for what ever reason. Everything looks right but it isn't displaying it right.

**Comment by o01210o** [comment]
0.8.5 Fixed it.
