### ISSUE TITLE
[Bug] NineManga : ID1ID2 bug

### ISSUE THREAD

**Issue by NanayaRyuuichi** [inorichi/tachiyomi-extensions#2240]
### Device information
* Tachiyomi extension version: NineManga 1.2.8
* Tachiyomi version: v8.4.5-EH
* Android version: Lolipop

## Steps to reproduce
1. Loading Manga or Refresh manga list in NineMangaEn

### Expected behavior
Manga and Chapter Loaded as normal

### Actual behavior
Error code " ID1ID2: actual 0x00003c21 != expected 0x00001f8b "

### Other details

![Screenshot_2020-02-14-19-04-58-623_eu kanade tachiyomi eh2](https://user-images.githubusercontent.com/51222187/74531000-10775e80-4f5e-11ea-9244-26e90237e2c8.png)

**Comment by happywillow0** [comment]
> Tachiyomi version: v8.4.5-EH

Can you check with the Dev version to see this this still happens. 

If it only happens with EH, I would check / post in the EH / AH github issues.

**Comment by NanayaRyuuichi** [comment]
@happywillow0 

![Screenshot_2020-02-16-05-51-18-517_eu kanade tachiyomi eh2](https://user-images.githubusercontent.com/51222187/74596330-66dcbe00-5080-11ea-916a-fa826d3f780a.png)

Still persist in Tachi 0.8.4

**Comment by arkon** [comment]
I can't reproduce this, but Googling it seems to make it seem like an issue with the response and GZIP. Do you have any sort of VPN/ad blocking/site blocking going on?

**Comment by NanayaRyuuichi** [comment]
If site blocking, maybe.. but I dunno since I can open Ninemanga in web without vpn

**Comment by arkon** [comment]
Can't reproduce. Open another issue if it's still happening in 0.10.3+.
