### ISSUE TITLE
[Bug] West Manga : unparseable date

### ISSUE THREAD

**Issue by deardian20** [inorichi/tachiyomi-extensions#2243]
### Device information
* Tachiyomi extension version: 1.2.1
* Tachiyomi version: 0.8.4
* Android version: 5.1.1

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Can see chapter and read manga

### Actual behavior
Chapter can't shown in extension

**Comment by happywillow0** [comment]
Hm... that's interesting. There are two in the repo. 

Try uninstalling West Manga extension from your phone and install WPManga extension which should contain updated code for West Manga. (You can disable the others in the Catalog Screen)
