### ISSUE TITLE
[Source Request] The NoNames

### ISSUE THREAD

**Issue by ZEXERJK** [inorichi/tachiyomi-extensions#2245]
### Source Website
Website can be found at [The NoNames](https://the-nonames.com/home) .

### Other Details
They are also uploading on mangadex [HERE](https://mangadex.org/group/994/the-nonames) but with a substantial delay.

**Comment by happywillow0** [comment]
Powered by Genkan

**Comment by ZEXERJK** [comment]
> Powered by Genkan

It means you will add it to the Genkan Extension?

**Comment by happywillow0** [comment]
Someone can, at some point, whenever they get to it.

**Comment by ZEXERJK** [comment]
> Someone can, at some point, whenever they get to it.

Thanks! :+1:

**Comment by Jerrk** [comment]
I'm on `Genkan (multiple sources)` version 1.2.20 and The NoNames still doesnt show up under sources.

Any idea what the issue might be?

**Comment by AbdullahM0hamed** [comment]
@Jerrk Have you checked your filters? Perhaps you've accidentally disabled it.

**Comment by ZEXERJK** [comment]
> I'm on `Genkan (multiple sources)` version 1.2.20 and The NoNames still doesnt show up under sources.
> 
> Any idea what the issue might be?

It's already present in Genkan Extension.
