### ISSUE TITLE
[Source Request] Timelessleaf

### ISSUE THREAD

**Issue by ZEXERJK** [inorichi/tachiyomi-extensions#2251]
### Source Website
Website can be found at [Timelessleaf](https://timelessleaf.com) .

### Other Details
They are also uploading on mangadex [HERE](https://mangadex.org/group/2907/timelessleaf)  but with a 1day delay. They are a scanlation group that translate various manga/manhua in english. The website maybe is not user-friendly to navigate but I will try to provide as much links as possible.
Links:
[List of manga/manhua](https://timelessleaf.com/manga/) 
[Recent Updates](https://timelessleaf.com/2018/12/20/recent-updates/)

**Comment by ZEXERJK** [comment]
So is it possible to add the source?

**Comment by samanta-widjaja** [comment]
and there are manga which they don't upload in mangadex. i have to read on web. add the source please

**Comment by Mizora15** [comment]
Why is it closed? The source isn't even added yet

**Comment by Mizora15** [comment]
I need the Timelessleaf source

**Comment by CarlosEsco** [comment]
So make it?  Or just use mangadex since they upload there

**Comment by Mizora15** [comment]
I need the core source, the real source. Sorry if i'm requesting too much.

**Comment by AriaMoradi** [comment]
> I need the core source, the real source. Sorry if i'm requesting too much. I think Timelessleaf would make a pretty good source.

worry not my good sir, it will be in your hands in no time!

**Comment by Mizora15** [comment]
> > I need the core source, the real source. Sorry if i'm requesting too much. I think Timelessleaf would make a pretty good source.
> 
> worry not my good sir, it will be in your hands in no time!

Thank you very much😁

**Comment by AriaMoradi** [comment]
@Mizora15 the extension will be available in a few minutes. just mentioning it as you asked.

**Comment by Mizora15** [comment]
@AriaMoradi Thank you very much for the hard work, sorry i couldn't be of any help, since i don't know how.
