### ISSUE TITLE
[Bug] MangaDex : 'No chapters found' when sorting by 'Update date'

### ISSUE THREAD

**Issue by ghost** [inorichi/tachiyomi-extensions#2252]
### Device information
* Tachiyomi extension version: 1.2.79
* Tachiyomi version: r1680
* Android version: Android 9

## Steps to reproduce
1. Catalogues
2. MangaDex -> Browse
3. Filter button
4. Sort by 'Update date'
5. Demographic by 'Seinen'
6. Search

### Expected behavior
Been shown titles with actual chapters to read

### Actual behavior
Latest raws without english chapters are shown showing you a list of unusable titles you can't even read in the original language because 'No chapters found' is still showed

### Other details
I enabled the hide toggle to ignore titles without chapters in mangadex options but the change didn't reflect within the extension so I don't think it actually looks at the profile settings at all.
What I'm trying to do here is to look for latest english chapters but the search function prioritizes raws first creating a list of unusable titles making the sorting by 'Update date' meaningless.
![image](https://user-images.githubusercontent.com/60162875/74592017-6ced8300-501d-11ea-8e0e-df0415f8fcda.png)

**Comment by arkon** [comment]
This is related to #1215. Does it not respect your language choices?

**Comment by leewdch** [comment]
I don't think I've ever set a language in the first place. I do have english set as filter chapter language so I assume it should use that one. I also appended a webm of a recording of my phone in case you want to see it "live".
[recording_20200215_185458-[00.08.037-01.09.085].webm.zip](https://github.com/inorichi/tachiyomi-extensions/files/4208851/recording_20200215_185458-.00.08.037-01.09.085.webm.zip)

**Comment by n0k0m3** [comment]
Add to this, not only sorting doesn't work, whole search functionality for the extension is broken.
Probably MD server-side changed the search API, may need an update

**Comment by n0k0m3** [comment]
Found the webview workaround for login: https://tachiyomi.org/help/faq/extensions/#mangadex

**Comment by leewdch** [comment]
Glad the workaround fixed your issue but in my case search results are correctly listed.
The issue is only english chapters are allowed withing the plugin (I think) and the first results listed are all raws causing a no chapters found issue I repoted

**Comment by CarlosEsco** [comment]
@leewdch did you verify if you search and sort by latest on their site that manga it is not matching?  I ask because i asked Mangadex dev and when you sort by last update on their site (without the demographic)  it corresponds to this url.  https://mangadex.org/titles?s=0#listing  which they told me is a bug that cannot be fixed currently and it ignores your user settings

**Comment by leewdch** [comment]
Right now website is on maintenance so I'll test it later
![image](https://user-images.githubusercontent.com/60162875/75263282-0cfd9600-57ee-11ea-8703-083f68119a53.png)

**Comment by leewdch** [comment]
Website is back up but still recovering. I tried checking your link and doing the same research on tachiyomi but it shows raws first (entries without english chapters) so the result doesn't match the link

**Comment by CarlosEsco** [comment]
When you sort is the arrow up or down?  Cause it should be up
