### ISSUE TITLE
[Source Request] hanascan & loveheaven (rawqq & rawlh)

### ISSUE THREAD

**Issue by ptoump** [inorichi/tachiyomi-extensions#2258]
### Source Website
Rawqq.com transfered to hanascan.com, old extension almost works (viewer doesn't work).

Rawlh.com transfered to loveheaven.com, old extension almost works (viewer doesn't work).

### Other Details

It would be great to reuse the old extensions, as no source transfer will be needed for anyone who hasn't removed the extension...

**Comment by happywillow0** [comment]
Thank you for your suggestions. 

Rawqq and RawLH are part of FMReader

**Comment by p2635** [comment]
I almost filed a bug request but saw this ticket. It would be good to tell people who still the old extension somehow so they know what  is going on. I thought it was just broken but it's just a case for me to just add FMReader now.
