### ISSUE TITLE
Site Details in the Extension

### ISSUE THREAD

**Issue by wruizcanal** [inorichi/tachiyomi-extensions#2259]
(CATALOGUE) SOURCE REQUESTS:
  All
BUGS:
 I would like the website addresses to be added to the extension details option.

This is more necessary for extensions from multiple sources (ext: FMReader, FoolSlide, Gekan, Madara, etc ...) since it is not known what extension belongs to which site when you have many extensions installed.

**Comment by happywillow0** [comment]
Thank you for your suggestion. 
This issue tracker is mainly targeted toward issues with specific extensions. 
The issue of multi-source extensions and their respective sites has already been opened here:
https://github.com/inorichi/tachiyomi/issues/2279

**Comment by happywillow0** [comment]
That said, we do have a handy dandy spreadsheet on the main website
https://tachiyomi.org/help/faq/extensions/

Or directly here:
https://docs.google.com/spreadsheets/d/1TyJEUg78WWH4zgnf3g6M2lkbWpBWbd40FYiPVQhW8IU/edit#gid=0
