### ISSUE TITLE
Dynasty Scans tags doubled

### ISSUE THREAD

**Issue by BaronKrause** [inorichi/tachiyomi-extensions#226]
Super minor bug, the dynasty Scans source will double the tags for every manga listing, the end of the last tag of the first set will be combined with the first tag of the second repeated set. Really doesn't impact anything but just figured I'd report it.

This does not affect the newly added chapter listing if that makes any difference.

The chapter listing I also noticed can not have a cover set as reported in a previous already closed issue, but this isn't in relation to covers being auto set. Since they are chapters they definitely wouldn't have a default cover, but tachiyomi actually gives a failed to set cover error when you try to manually set one from a page or external picture.

**Comment by CarlosEsco** [comment]
makes sense for part 1 cause i had rewrote the genre code for chapters.  Will do same monday or tuesday with the rest of them.  I'll also look into the cover issue

**Comment by BaronKrause** [comment]
Newest update fixed the normal series/anthology tags but seem to have broken the previously working chapter tags. Also chapters now when added to your favorites, and say they are added to your favorites, the favorites bookmark icon never changes to solid.

This is only on newly added chapters not in your database. If you look at a previously added one the tags and bookmark solid coloring are there, even if you unbookmark and rebookmark it. You need to unbookmark it, clear cache of items not in your library and then re add it for it to show without the tags/no bookmark icon nightlight.

@CarlosEsco

**Comment by CarlosEsco** [comment]
Chapter tags seem fine for chapters

**Comment by BaronKrause** [comment]
Now that I look through them, most have tags, but many seem missing. "Jealousy sure is nice" and "the sunset, aromas, and The signs of love" had them, and after removing, clearing the database in advanced settings and re searching them they no longer do. I have a before and after screenshot from my phone after noticing it on my tablet.

@CarlosEsco

**Comment by BaronKrause** [comment]
The ones that don't show tags seem to be the only ones affected by the bookmark solid color bug too. All the "met my sister on a dating site" chapters also seem affected, though you normally wouldn't add those separately.

**Comment by CarlosEsco** [comment]
I'll look into those chapters giving me issues too. Guessing html is different or missing something so causing an error
