### ISSUE TITLE
[Bug] manga.ae: no pages 

### ISSUE THREAD

**Issue by Amr-4** [inorichi/tachiyomi-extensions#2268]
App version: 8.4

Android version: 9.1

Issue/Request: Fix

Steps to reproduce (if applicable)

Screenshot_20200219_191622_eu kanade tachiyomi

Screenshot_20200219_191605_eu kanade tachiyomi

All Mangas appear Like this
Other details:
Also the mangas no apear in library updates

Thank you

**Comment by Amr-4** [comment]
![74851588-80b22580-534c-11ea-97eb-9107cd06ef94](https://user-images.githubusercontent.com/59889000/74853753-6af22f80-534f-11ea-96df-4cdd807755c3.jpg)
![Uploading 74851571-7d1e9e80-534c-11ea-98b4-6b579222a4c4.jpg…]()

**Comment by Amr-4** [comment]
![Uploading 74851571-7d1e9e80-534c-11ea-98b4-6b579222a4c4.jpg…]()

**Comment by happywillow0** [comment]
How does the webpage look like when you open up the site in webview? Does it load everything?

Do you want to try downloading the dev version and seeing how it loads?

**Comment by Amr-4** [comment]
Yes it load everything, but I want to download the chapters

في الأربعاء، ١٩ فبراير، ٢٠٢٠ ٩:٣٥ م happywillow0 <notifications@github.com>
كتب:

**Comment by baytout00** [comment]
I changed the link in the app to  http://manga.ae
And it works, but unfortunately not all of it works.
