### ISSUE TITLE
[Bug] Source Name : Short Description

### ISSUE THREAD

**Issue by llreizh** [inorichi/tachiyomi-extensions#2271]
### Device information
* Tachiyomi extension version: mangaku 1.2,1
* Tachiyomi version: 0.84
* Android version: pie

## Steps to reproduce
1. Instal indonesian extension
2. Look for in catalogue

### Expected behavior
Indonesian manga web shown

### Actual behavior
Indonesian web skipped. Doesnt exist

### Other details
Reinstal + change android does not fix it

**Comment by happywillow0** [comment]
There should be a button on the top right of catalog that enables and disables languages and websites.

**Comment by llreizh** [comment]
It works
