### ISSUE TITLE
[Bug] DMZJ : Can Neither Restore Backup nor Batch Import

### ISSUE THREAD

**Issue by Schezuk** [inorichi/tachiyomi-extensions#2272]
### Device information
* Tachiyomi extension version: 1.2.8 and before
* Tachiyomi version: Latest
* Android version: 4

## Steps to reproduce
1. Setting - Backup -Restore - Select .json file
2. Manually batch import Web page or Json api from domain
www.dmzj.com, m.dmzj.com, v2.api.dmzj.com or v3.api.dmzj.com

### Expected behavior
1. All galleries should have been restored.
2. At lease one URL should have worked.

### Actual behavior
1. Only to find all galleries restored but DMZJ. 
Error Message: source_not_installed 2884190037559094000
2. Failed to import either way.

### Other details
Batch import is a feature of Forked distributions, which will not, however, cause different behaviors amongst extensions.

**Comment by Schezuk** [comment]
By the way, galleries which have been deleted online should be restored even if restored as empty galleries. They may reappear any time when updating the bookshelf.

**Comment by happywillow0** [comment]
> Error Message: source_not_installed 2884190037559094000
This error message normally means that the extension was not installed on the phone previous to a restore. 

Have you installed the DMZJ extension and tried the restore again?

**Comment by Schezuk** [comment]
> > Error Message: source_not_installed 2884190037559094000
> > This error message normally means that the extension was not installed on the phone previous to a restore.
> 
> Have you installed the DMZJ extension and tried the restore again?

Yes, and checked that the extension is enabled.

**Comment by Schezuk** [comment]
> > Error Message: source_not_installed 2884190037559094000
> > This error message normally means that the extension was not installed on the phone previous to a restore.
> 
> Have you installed the DMZJ extension and tried the restore again?

JSON parsing changed magic number from 2884190037559093788 to 2884190037559094000, I am trying again.

**Comment by SnakeDoc83** [comment]
DMZJ's ID is 2884190037559093788.  If your import log states "Error Message: source_not_installed 288419003755909400" then you're missing an extension but it's not DMZJ, it's something else.

**Comment by Schezuk** [comment]
> DMZJ's ID is 2884190037559093788. If your import log states "Error Message: source_not_installed 288419003755909400" then you're missing an extension but it's not DMZJ, it's something else.

It was a truncation error. I have the ID corrected and import it with no error now. Thank you all for pointing it out.

By the way, since DMZJ is constantly hiding metadata of some comics while still updating chapters of them (thus comics can get bookmarked by RECENT UPDATE, SEARCH, or other tricks), it is better off just importing them all while ignoring all those server metadata fetching failure.

**Comment by SnakeDoc83** [comment]
@arkon This can be closed.
