### ISSUE TITLE
[Bug] MangaMx : Error 403 appears sometimes

### ISSUE THREAD

**Issue by edgarMejia** [inorichi/tachiyomi-extensions#2277]
### Device information
* Tachiyomi extension version: **1.2.4**
* Tachiyomi version: **r1749 (2c23c42c)** dev version
* Android version: **10**

## Steps to reproduce
1. Open Catalogues
2. Open Latest or Browse on MangaMx

### Expected behavior
Show latest or all mangas

### Actual behavior
403 error

### Other details
The error happens sometimes

**Comment by happywillow0** [comment]
When it happens, did you check webview at the time like we did with TMO?

**Comment by lovablesweet35** [comment]
Is there a problem with kono-basho extension too? I'm also having the http 403 error whenever i try to read a manga source from there. I already cleared up my cache and restarted my device but so far noting. May i know if its probably the server that is having problems?

**Comment by MerradOklom** [comment]
MangaMx updated their site to version 2.0 and is now giving error 404 in Latest and No results found in Browse.
