### ISSUE TITLE
[Source Request] Manga-TR

### ISSUE THREAD

**Issue by Valkie23** [inorichi/tachiyomi-extensions#2283]
### Source Website
Website can be found at https://manga-tr.com/.

### Other Details
Since there are no Turkish sources yet, I believe this would be a valuable extention for Tachiyomi

**Comment by MerradOklom** [comment]
This one is in the multi-source extension FMReader.

**Comment by Valkie23** [comment]
> This one is in the multi-source extension FMReader.

Yup you're right I'm really sorry :D
