### ISSUE TITLE
Extensions on F-Droid disappeared. 

### ISSUE THREAD

**Issue by k1mzep** [inorichi/tachiyomi-extensions#229]
Tachiyomi version: 0.6.8
F-Droid version: 1.1 -alpha3

All of a sudden the J2ghz FDroid Repo stopped showing all of the possible extensions. It was fine a few days ago. Opened the app today looking for some sources to add / remove which I normally find via the cat page or searching but nothing appeared for either of those options. Only Tachiyomi related apps / files I can see are the standard app and the dev app.

**Comment by Flat** [comment]
F-Droid is deprecated. https://github.com/inorichi/tachiyomi-extensions/tree/repo

**Comment by wopian** [comment]
Should clarify that only the extensions on the F-Droid repo are deprecated. The stable and dev releases are 👌

**Comment by CarlosEsco** [comment]
For now manually download here.

https://github.com/inorichi/tachiyomi-extensions/tree/repo/apk

Next stable will be reading from the above repo in app.
