### ISSUE TITLE
[Bug] readmanga.me : parser broken, htm downloaded

### ISSUE THREAD

**Issue by abubaca4** [inorichi/tachiyomi-extensions#2300]
### Device information
* Tachiyomi extension version: 1.2.16
* Tachiyomi version: 0.8.4-1768
* Android version: 5.1

## Steps to reproduce
I just open new chapter and get message that image can't be decoded
After than I try to download chapter and get htm files
![Screenshot_2020-02-27-10-28-55](https://user-images.githubusercontent.com/55701175/75424580-fbcd9a00-5951-11ea-868d-3c52516471ba.png)
![Screenshot_2020-02-27-10-29-04](https://user-images.githubusercontent.com/55701175/75424645-23bcfd80-5952-11ea-9a6d-3d82ac020140.png)
![Screenshot_2020-02-27-11-04-05](https://user-images.githubusercontent.com/55701175/75424661-2ae40b80-5952-11ea-849e-4b7ba03cd7eb.png)
![Screenshot_2020-02-27-11-13-58](https://user-images.githubusercontent.com/55701175/75424716-49e29d80-5952-11ea-88b9-06102d47b124.png)

**Comment by BlueCat300** [comment]
Same error for mintmanga and possibly for selfmanga.
Extension give broken url to main app and as result it's download html pages because site redirect to main page.
https://h23.mangas.rocks/manga/https://h23.mints.rocks/auto/15/27/74/11.png_res.jpg?t=1582811166&u=0&h=57H9BS1G6uVkbDfW23POKw

**Comment by abubaca4** [comment]
I installed readmanga extension version 1.2.17 but the error still here

**Comment by abubaca4** [comment]
I installed readmanga extension version 1.2.17, clean cache and all is ok
