### ISSUE TITLE
[Bug] Readmanga : failed to decode image

### ISSUE THREAD

**Issue by VeryBadKiwi** [inorichi/tachiyomi-extensions#2303]
### Device information
* Tachiyomi extension version: 1.2.17
* Tachiyomi version: r1771 (0f2d4800)
* Android version: 10

## Steps to reproduce
1. Pick manga from Readmanga repository
2. Start reading

### Expected behavior
Manga will load pages to read

### Actual behavior
Writes that it was not possible to decode the image

### Other details
-

**Comment by arkon** [comment]
Duplicate of #2300
