### ISSUE TITLE
[Bug] Sync with Shikimori : sync don't work because Shikimori.org ban in Russia.

### ISSUE THREAD

**Issue by wooterland** [inorichi/tachiyomi-extensions#2304]
### Device information
* Tachiyomi version: 0.8.4
* Android version: 10

## Steps to reproduce
1. Open Settings
2. Open Tracking
3. Try to connect Shikimori

### Other details
Shikimori.org work only with VPN. New domain Shikimori.one.

**Comment by CarlosEsco** [comment]
update to dev version.  as this is fixed
