### ISSUE TITLE
[Source Request] Toonkor

### ISSUE THREAD

**Issue by schiezcka** [inorichi/tachiyomi-extensions#2320]
### Source Website
Website can be found at https://toonkor.ws/%EC%9B%B9%ED%88%B0.

### Other Details
A good source for Korean raws. NewToki already has problems/restrictions, so currently there isn't any available reliable Korean raws source in the app.

**Comment by as280093** [comment]
**icons:**
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/4271664/ic_launcher.5.zip)
