### ISSUE TITLE
[Bug] MMRCMS : Manga Info (Name) issue

### ISSUE THREAD

**Issue by as280093** [inorichi/tachiyomi-extensions#2326]
### Device information
* Tachiyomi extension version: Latest
* Tachiyomi version: Latest
* Android version: 9

## Steps to reproduce
1. Open any Source from MMRCMS
2. Open any manga from that source
2. view manga info page

### Expected behavior
![IMG_20200301_135349](https://user-images.githubusercontent.com/25240839/75622276-93d2ba00-5bc4-11ea-9982-4ef25a42f48b.jpg)

### Actual behavior
![IMG_20200301_135427](https://user-images.githubusercontent.com/25240839/75622282-a0efa900-5bc4-11ea-9bf6-e9834432538d.jpg)

**Comment by happywillow0** [comment]
Currently does not affect:

- 0.8.5 Stable
- r1810 Dev

Affects

- J2K
- AZ
- EH

There was a similar issue before (pull/1964) fixed by az 
I wonder what the difference is. I think kotlin and jsoup versions are the same.

**Comment by as280093** [comment]
SMH using J2k
