### ISSUE TITLE
[Feature Request] all sources in one apk

### ISSUE THREAD

**Issue by Fahad1998** [inorichi/tachiyomi-extensions#2328]
### What feature should be added to this source?
Instead of maintaining multiple apks what about merging all sources in one apk.

**Comment by arkon** [comment]
No, the point is to have multiple APKs so they're easier to update.

**Comment by MakuSensei** [comment]
It might be useful to group only one source with very similar codes in an apk.

**Comment by CarlosEsco** [comment]
Anyone is welcome to do that. Tachi supports third party extensions. But officially there is no plans to do 1 apk

**Comment by happywillow0** [comment]
> It might be useful to group only one source with very similar codes in an apk.

That is already happening. The multi source extensions such as Madara and FMReader etc are groups of multiple websites using similar / same code.
