### ISSUE TITLE
Webtoons not showing specific webtoon even if it is available online

### ISSUE THREAD

**Issue by blureshadow** [inorichi/tachiyomi-extensions#233]
It's been happening ever since I installed the Webtoons extension months ago, so it's version independent. My issue is a webtoon isn't showing up on the webtoons source, while it is available on the website.
Carciphona
http://www.webtoons.com/en/challenge/carciphona/list?title_no=42670

**Comment by CarlosEsco** [comment]
issue was resolved in discord
