### ISSUE TITLE
[Bug] MMRCMS: Latest Fix

### ISSUE THREAD

**Issue by as280093** [inorichi/tachiyomi-extensions#2330]
### Device information
* Tachiyomi extension version: Latest
* Tachiyomi version: Latest
* Android version: 9

## Steps to reproduce
1. First Step
2. Second Step

### Issue
Most of the sources now support **latest**  like Baimam, Fallen Angel & other sources
![IMG_20200301_205839](https://user-images.githubusercontent.com/25240839/75628533-10cf5500-5c00-11ea-8f40-2575a1974a2a.jpg)

**Comment by happywillow0** [comment]
Not sure if the extension is due for a re-write but it will take a bit more work than the title fix. 

Just a bit of background of what is happening:
The extension is checking the manga list and the sorting options that are available. This is different from the latest release link on the top.

Fallen Angels for example only has 
![facapture](https://user-images.githubusercontent.com/45346080/75630883-5407d480-5bbc-11ea-8834-6a8b701753ae.PNG)

The only one supported is the read comics online which has a option to sort by latest release. 
![comiccapture](https://user-images.githubusercontent.com/45346080/75630893-6c77ef00-5bbc-11ea-8001-6b0f0ffa020d.PNG)

We can try to convert it to the other latest release list but the urls and parsing will need to be updated in a few places.
