### ISSUE TITLE
[Source Request] Novelle Leggere [ita]

### ISSUE THREAD

**Issue by aslupo98** [inorichi/tachiyomi-extensions#2340]
### Source Website
https://www.novelleleggere.com/

### Other Details
Is an good Italian source for manga but also light novel... I'm interested for the manga obviously.
They have good manga translation

**Comment by as280093** [comment]
**Here the Icons:**
- [ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/4275467/ic_launcher.8.zip)

**Comment by as280093** [comment]
**Here the Icons:**
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/4276086/ic_launcher.9.zip)

**Comment by aslupo98** [comment]
thanks bro <3
