### ISSUE TITLE
[Question]: how to omit a element in popularMangaFromElement

### ISSUE THREAD

**Issue by Trim21** [inorichi/tachiyomi-extensions#2342]
I'm writing a new extensions.

Some elements selected by `popularMangaSelector` don't contain a manga, and it's hard to omit them by a css selector.
So is there any way I can tell the app to omit this element in `popularMangaFromElement` ?
throw an exception won't work.

**Comment by happywillow0** [comment]
You can go up one step and try to do some interpretation and filtering here:
``` kotlin
override fun popularMangaParse(response: Response): MangasPage {
        val document = response.asJsoup()

        val mangas = document.select(popularMangaSelector()).map { element ->
            popularMangaFromElement(element)
        }

        val hasNextPage = popularMangaNextPageSelector()?.let { selector ->
            document.select(selector).first()
        } != null

        return MangasPage(mangas, hasNextPage)
    }
```

**Comment by CarlosEsco** [comment]
also discord channel dev-extensions can help with any questions on developing an extension
