### ISSUE TITLE
manga.ae not working

### ISSUE THREAD

**Issue by mged** [inorichi/tachiyomi-extensions#2344]
you released a new version and said it fixed the issue but its still there, on Mangaae (arabic manga https://mangaae.com )

https://i.ibb.co/Gk5BNWn/Capture.png

**Comment by mged** [comment]
i just dont get why you wasted your time updating the extension when the new update CHANGE NOTHING at all. ;C

**Comment by CarlosEsco** [comment]
Please just report the issue. Your personal opinion on the issue is not needed

**Comment by mged** [comment]
roger that! :)

( im sorry anyway, i was just annoyed i cant read my fav manga on my fav app :heart: )

**Comment by happywillow0** [comment]
What version of Tachiyomi are you using? 
What version of Mangaae extension is on your phone? 

To be honest, the Mangaae extension doesn't even use duktape so I'm not sure where the error is coming from.

**Comment by mged** [comment]
yeah i tried all extensions and all versions of the app i ended up giving up on mangaae

i found a new way to read arabic manga from good website using your app guys,

here is its code "https://pastebin.com/LusSSJr9"

 its fine everything is fine until... i enter a chapter to read it show retry error if i fix only this small issue i can read arabic manga in peace

this is not working, it scrape the chapters count, the details and the status and the plot ( the description ) but when i enter on a chapter to read

for example naruto chapter 700, it show retry when i click retry it wont load images.

any help will be highly appreciated!

**Comment by joseph619** [comment]
Change the title and follow the format. You are constantly breaking the rules.

**Comment by happywillow0** [comment]
Once again, it would be best if you can provide:

> What version of Tachiyomi are you using?
> What version of Mangaae extension is on your phone?

I am having trouble reproducing the page list / retry bug. 
It feels like it is a server-side program to cause the image to break (404)

You should also preform the following troubleshooting:
In Tachiyomi app, go to `Settings` -> `Advanced` -> the hit the first two clear buttons `Clear chapter cache` and `clear cookies`. Then, you can go back into the chapter to try loading again.

**Comment by mged** [comment]
it worked thanks
