### ISSUE TITLE
[Bug] Russian and English Resources Bugs

### ISSUE THREAD

**Issue by D3xron** [inorichi/tachiyomi-extensions#2345]
1. Anibe - connect timed out
2. "AkaiYuhiMun team" has been changed to 
"https://j-comics.ru/" and has a certificate error
3. Com-x - HTTP error 404
4. Bato.to, Mangatensei and Mangawindow - Has a same manga library ???
5. Onlinecomics - HTTP error 404

**Comment by happywillow0** [comment]
2. Added J-comics (Not removed AkaiYuhiMun  yet)
4. Old Bato.to shut down. Current Bato.to is run by same people as Mangatensei for example

**Comment by D3xron** [comment]
Thank you, If this issue still on? Or, I have to close it?
