### ISSUE TITLE
[Bug] MangaOwl : Chapters and Page not Loading

### ISSUE THREAD

**Issue by AlliedJoe** [inorichi/tachiyomi-extensions#2350]
### Device information
* Tachiyomi extension version: 1.2.3
* Tachiyomi version: 0.8.5
* Android version: 10

## Steps to reproduce
1. go into manga in library
2. Refresh Chapters Tab
3. no chapters found
-or-
1. go into catalogues
2. click browse on MangaOwl 
3. pick any random manga
4. info loads fine
5. go into chapters tab
6. no chapters found

### Expected behavior
Give me some chapters to read

### Actual behavior
Gave me a blank page in the chapter tab in any manga from that source

**Comment by happywillow0** [comment]
Notes for later, or someone else I suppose: 

```
override fun chapterListSelector() = "div.table-chapter-list ul li"
chapter.date_upload = parseChapterDate(element.select("small").text()) 
```
