### ISSUE TITLE
[Source Request] Add Russian Sources

### ISSUE THREAD

**Issue by D3xron** [inorichi/tachiyomi-extensions#2354]
Can you add this russian manga resources?
1. https://mangaclub.ru/
2. https://manga24.ru/
3. https://bestmanga.club/

**Comment by CarlosEsco** [comment]
Please open 1 request per a source and verify before you do verify there is not an open request

**Comment by D3xron** [comment]
What do you mean, with the open request?

**Comment by joseph619** [comment]
Somebody has already requested it before you did
