### ISSUE TITLE
[Japanese] lhscans.com

### ISSUE THREAD

**Issue by uenoshita** [inorichi/tachiyomi-extensions#236]
[http://lhscans.com](url) one of the few Japanese raw site that updates frequently and has a decentish resolution.

**Comment by ramattos** [comment]
+1
and we really need this since the raw.senmanga plugin doesn't work properly anymore

**Comment by paronos** [comment]
http://lhscans.com redirects to http://rawlh.com (which already has an extension)

**Comment by ramattos** [comment]
The issue was raised back when RawLH didn't have an extension IIRC.
