### ISSUE TITLE
[Bug] Questionable Content: downloads never show up in Library Updates

### ISSUE THREAD

**Issue by Fry-kun** [inorichi/tachiyomi-extensions#2362]
### Device information
* Tachiyomi extension version: 1.2.4
* Tachiyomi version: 0.8.4
* Android version: Q

## Steps to reproduce
1. Install QC extension, add comic to library, set auto download
2. Wait for download the happen

### Expected behavior
Should appear in Library Updates

### Actual behavior
Does not appear in Library Updates

**Comment by bbtora** [comment]
Does chapter list show release dates for the chapters?

**Comment by Fry-kun** [comment]
No, don't think so

**Comment by bbtora** [comment]
Can you share a screenshot of the chapter list tab of the manga for clarity?

**Comment by Fry-kun** [comment]
![Screenshot_20200304-095957](https://user-images.githubusercontent.com/1214224/75910623-0630dd80-5e03-11ea-8de0-355647ceed70.png)

**Comment by bbtora** [comment]
Yep, can be easily solved if chapter dates are added in the extension.

**Comment by einstein95** [comment]
QC doesn't give chapter dates on the site
