### ISSUE TITLE
[Bug] FMReader - RawLH : Must Login to get Chapter List

### ISSUE THREAD

**Issue by Donnie-B** [inorichi/tachiyomi-extensions#2366]
### Device information
* Tachiyomi extension version: 1.2.7
* Tachiyomi version: 0.8.4
* Android version: 5.3.7

## Steps to reproduce
1. Try to refresh manga chapter
2. Get "No chapter found message"

### Expected behavior
Successfully update the chapter list

### Actual behavior
Get "No chapter found message"

### Other details
Seems like now they require user login to view chapter list.
Can still access the chapters by going into each manga page and click the link to "Read The Last Chapter"

**Comment by as280093** [comment]
Open latest/browse 
Click 3 dots in right corner 
Select open in webview
Login 

This will solve the issue

**Comment by SnakeDoc83** [comment]
@Donnie-B I'm not experiencing this, is this still an issue for you?

**Comment by happywillow0** [comment]
I think they turned off the log in to view chapter list option. 
@arkon I think we can close this issue. If they do turn it on, you can use webview to log in.
