### ISSUE TITLE
[Bug] Mangakakalot not updating

### ISSUE THREAD

**Issue by CapNinja** [inorichi/tachiyomi-extensions#2375]
### Device information
* Tachiyomi version: 0.8.4
* Android version: I'm using Kindle Fire HD 10

## Steps to reproduce
1. Choose some mangas
2. Read or download the mangas you've chosen

### Expected behavior
You can read or download

### Actual behavior
Most mangas didn't update since the first half of december, for example: one piece, my hero academia, haikyuu and dr. Stone
And some manga get you "the page list is empty" error.

### Other details
Additional details and attachments.

**Comment by happywillow0** [comment]
What version of the extension are you running? 
Under Extensions, is it `Mangabox` or `Mangakakalot`?

Also, just FYI, the current version of Tachiyomi available on github is 0.8.5

**Comment by CapNinja** [comment]
> What version of the extension are you running?
Mangakakalot version 1.2.8

>Also, just FYI, the current version of Tachiyomi available on github is 0.8.5
Updated. Thanks.

**Comment by arkon** [comment]
@CapNinja Does it work now?

**Comment by happywillow0** [comment]
> Mangakakalot version 1.2.8

Please uninstall the `Mangakakalot` extension. 

Please install `MangaBox (Mangakakalot and others)`

Your library will automatically convert.

**Comment by SnakeDoc83** [comment]
@arkon Probably just needed to switch to MangaBox, might as well close this after 3 weeks of radio silence.
