### ISSUE TITLE
Set custom images for the manga soruces

### ISSUE THREAD

**Issue by mged** [inorichi/tachiyomi-extensions#2379]
Hello,

let us set a custom icon for each soruce or make the soruce icon not the first letter, but the manga soruce icon!

the current code is
` // Set circle letter image. 
 itemView.post { 
     image.setImageDrawable(image.getRound(source.name.take(1).toUpperCase(), false)) 
 } `

let us choose our custom icons or make it get the icons from the soruce icon (not letter)
if its not possible give me the code to set a custom icon for the soruces from drawable folder,

i tried this code
` itemView.post {
            image.setImageResource(R.drawable.bronze)}` but it set the bronze image for all soruces! not for the first soruce only, how to make it set it for the first soruce only?
here is how the current system are working in this screenshot.

https://i.imgur.com/e2hJaYy.png

**Comment by arkon** [comment]
I'd turn down custom icons.

Using the original icons is already posted as https://github.com/inorichi/tachiyomi/issues/2261, which you're commenting in too.

I also see you're asking about it on Discord too.
