### ISSUE TITLE
[Feature Request] wutopiacomics: Requesting Login for downloading unlocked chapters

### ISSUE THREAD

**Issue by amit34521** [inorichi/tachiyomi-extensions#2382]
I have unlocked a few chapters for Soul Land 2. when i am trying to download them, i only get the first page. Is it possible to add login feature to get all pages?

**Comment by happywillow0** [comment]
Which website? 
Have you tried to open the browse / latest / manga info via webview to log into the site?

**Comment by amit34521** [comment]
Wutopiacomics.com is the site.

Trying to open in webview gives this error:
Webpage not available
The webpage at https://www.wutopiacomics.com/mobile/cartoon-collection/get could not be loaded because:

net::ERR_INVALID_RESPONSE

**Comment by pavan3999** [comment]
same here
