### ISSUE TITLE
[Bug] Open in app option gone(mangadex)

### ISSUE THREAD

**Issue by jestarray** [inorichi/tachiyomi-extensions#2384]
### Device information
* Tachiyomi extension version: 1.2.85
* Tachiyomi version: 0.8.5
* Android version: 9.0

## Steps to reproduce
1. You can no longer right click a mangadex link and "open with app" in any web browser.

In the past you could, and i recall this ability was stripped between the past few recent updates.

**Comment by CarlosEsco** [comment]
did you sent default to open in chrome by accident?

**Comment by jestarray** [comment]
Ah, tested it on another android device. Interestingly the case seems to be only isolated to my galaxy s8... I never touched my settings and one day it just happened. I cleared all default apps and still no luck. Going to close for now

**Comment by E3FxGaming** [comment]
@jestarray Would you happen to remember where you got the link from?

I noticed that
- the google search results give you a link with the format https://mangadex.org/title/SomeID/...
- other search engines, such as Duckduckgo and Bing give you a link with the format https://www.mangadex.org/title/SomeID/...

Both website formats work (to view things in your browser), but so far there was no app intent filter for www.mangadex.org, thus you didn't get the option to open it directly with Tachiyomi.

I'm trying to fix this oversight with commit #2614

**Comment by jestarray** [comment]
Ohh, so that was the problem? No, I don't know which site gave me the link but the manga was "Hakoiri Drops", and it was prefixed with www.
