### ISSUE TITLE
[Bug] Japscan : no loading pictures of scans

### ISSUE THREAD

**Issue by DiogoVieiraFerreira** [inorichi/tachiyomi-extensions#2386]
### Device information
* Tachiyomi version: r1835 (52434819) 
* Android version: 10
* Phone : Huawei mate 20 pro

## Steps to reproduce
1. Install japscan extension 
2. go to catalog
3. go to recent 
4. choose a random manga 😅
5. choose a random chapiter
6. wait download load
7. the rety buttom ia visible
8. click on retry many times do you want

### Expected behavior
Images of scan is visible and readible. 

### Actual behavior
Impossible to read scans

I  uninstalled and reinstalled extension but nothing changes. 
I use developpement version of tachiyomi, but i tried with stable version and the same problem is visible... i asked to my friend with an asus phone on last android version and he has the same problem. 

### Other details
i have to check website of japscan and i can watch and read scan.

i tried with mangakawaii extension and i can read scans.

**Comment by happywillow0** [comment]
Thank you for your report. There is already an open issue. If there is anything else, you can add to the issue here: #2315
