### ISSUE TITLE
[Source Request] Source"  Madara" 1stkissmanga,manga68,zinmanga ......

### ISSUE THREAD

**Issue by baytout00** [inorichi/tachiyomi-extensions#2387]
https://zinmanga.com
 https://1stkissmanga.com
 https://manga68.com
https://manhuas.net/

**Comment by happywillow0** [comment]
Please have only one website per request. 
Please make sure the site isn't already part of the extension. 
The following sites are already in Madara:
- Zin Manga
- 1st Kiss Manga
- Manhuas.net
