### ISSUE TITLE
Manga Plus can't Download

### ISSUE THREAD

**Issue by KaoticOblivion** [inorichi/tachiyomi-extensions#2391]
Trying to download chapter of Kimetsu No Yaiba from Manga Plus and I get en error and it won't download. If I open to read online it does seem to load the pages though. 

Tachiyomi Version: 0.8.5
MANGA Plus version: 1.2.3

**Comment by happywillow0** [comment]
Do you know what the error message said? 

The error message would determine what the issue is and which next steps to take.

**Comment by KaoticOblivion** [comment]
![Screenshot_20200308-135052](https://user-images.githubusercontent.com/8932192/76168212-e7548300-6143-11ea-9ab7-7eb18069d190.jpg)
This is all I see. Is there somewhere I can look for a more detailed error?

**Comment by KaoticOblivion** [comment]
Nevermind I see the error number is in the notification. HTTP error 502

**Comment by happywillow0** [comment]
I don't know if it is my connection or if Manga Plus managed to break.

https://mangaplus.shueisha.co.jp/titles/100009 doesn't load the manga for me. Just the header and footer.

**Comment by arkon** [comment]
It loaded for me after a bit.

**Comment by KaoticOblivion** [comment]
That link loaded for me

**Comment by happywillow0** [comment]
I just tried on my phone and it seemed to load after a time out error. Want to clear the download queue, (optionally clear chapter cache) and try the download again?

**Comment by MerradOklom** [comment]
I got the 502 error, opened the manga in Chrome and there was nothing on the page, switched to desktop view and back to mobile view and everything was working again. Maybe the site is kind of unstable right now.

**Comment by KaoticOblivion** [comment]
I did that a couple times before posting. 

I think it's weird that only the download failed though, if I give it a minute the pages will load if I just open it.

**Comment by alessandrojean** [comment]
I tried to download the chapter and it downloaded normally. As commented by the others, maybe the site is unstable in some regions. Are you still getting the error?

**Comment by KaoticOblivion** [comment]
This afternoon I tried again and it was able to download!
