### ISSUE TITLE
[Bug] Tapas: Extension broken

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi-extensions#2397]
### Device information
* Tachiyomi extension version: 1.2.4
* Tachiyomi version: J2k and AZ latest
* Android version: 10

## Steps to reproduce
1. Open in Browse

### Expected behavior
Manga list should appear

### Actual behavior
Shows 'No results found' 

### Other details
Source works fine in Webview.

**Comment by happywillow0** [comment]
Yep yep.
The website code looks different so there is a lot to re-write / update all the selectors. 
I'll work on it when I have time.

**Comment by happywillow0** [comment]
Oops, sorry. I forgot there was another one open already. 
#2369
