### ISSUE TITLE
[Bug] Source Name : Mangabat

### ISSUE THREAD

**Issue by AlbedoSuzuki** [inorichi/tachiyomi-extensions#2398]
### Device information
* Tachiyomi extension version: 1.2.14
* Tachiyomi version: 0.8.5
* Android version: 8.0.0

## Steps to reproduce
1. Click on: Catalogues
2. Click on: Mangabat lastest

### Expected behavior
Mangabat Manga list opens

### Actual behavior
Nothing happens

### Other details
Screenis completely without anything except the viewoptions at the top

**Comment by happywillow0** [comment]
Looks like they changed the website. I'm not even sure if it technically is Mangabox anymore.
