### ISSUE TITLE
Page List Empty Error

### ISSUE THREAD

**Issue by jsantuele96** [inorichi/tachiyomi-extensions#24]
(CATALOGUE) SOURCE REQUESTS:
please help
BUGS:
 not being able to read any manga or download. page liest empty is showing up after having the news for updates v5.0. tried to update to fix the issue.nothing happened

**Comment by inorichi** [comment]
It's already fixed. Please next time write which source is failing.

**Comment by jsantuele96** [comment]
i am still getting the Page List is Empty error
