### ISSUE TITLE
[Bug] ManhwaScan : Doesn't load mangas 

### ISSUE THREAD

**Issue by LeenaLion20** [inorichi/tachiyomi-extensions#2402]
### Device information
Tachiyomi extension version: 1.2.14
Tachiyomi version: 0.8.5
Android version: 8.0.0

## Steps to reproduce
Click on: Catalogues
Click on: ManhwaScan either Lastest or Explore

### Expected behavior
ManhwaScan Manga list opens

### Actual behavior
Runs timeout and doesn't show up anything

**Comment by happywillow0** [comment]
> Runs timeout and doesn't show up anything

A time out error normally means the server was slow to respond. I'm testing it myself and it is bit slow. If the website is having issues and being slow, there is not much we can do. 

We can adjust the time out but that won't fix the slowness which needs to be fixed on their end.

**Comment by happywillow0** [comment]
The site looks to be running a bit better. Is this still an issue for you?

**Comment by SnakeDoc83** [comment]
@arkon Seems like this was a temporary site issue, might as well close this.
