### ISSUE TITLE
[Source request repair] manhuadui [cn]

### ISSUE THREAD

**Issue by hanxin1997** [inorichi/tachiyomi-extensions#2403]
new address
Website can be found at https://m.manhuadui.com.
Other Details
It needs to be parsed through a mobile phone. This site can only be accessed using a mobile phone

**Comment by happywillow0** [comment]
I'm on my computer and tested it on my phone too. It seems to be working fine. 

Is not working for you? Have you tried a VPN to see if it isn't blocked somehow?

**Comment by hanxin1997** [comment]
> I'm on my computer and tested it on my phone too. It seems to be working fine.
> 
> Is not working for you? Have you tried a VPN to see if it isn't blocked somehow?

Tried vpn is invalid, https://m.manhuadui.com is available, The source in the app is www.manhuadui.com and cannot be accessed

**Comment by hanxin1997** [comment]
Resolved, blocked in some areas, resolved using vpn
