### ISSUE TITLE
[Source Repair Request] Error 403 in Kono-Basho source

### ISSUE THREAD

**Issue by ShakkoRyu** [inorichi/tachiyomi-extensions#2410]
Tachiyomi v.0.8.5 shows a message when I try to get backup or loading a manga in source Kono-Basho

**Comment by happywillow0** [comment]
I'm slightly surprised that we didn't have a open issue until now. 

The website for Kono-Basho has been not working for a while now. Nothing we can do to fix their website. 

If it says down any longer, I think I might disable / remove the source. 

For now, you may have to manual re-add manga using a different website source.

**Comment by ShakkoRyu** [comment]
Yeah me too I was surprised nobody said something about it, anyways thx
