### ISSUE TITLE
[Bug] Doujin-Yang needs icons

### ISSUE THREAD

**Issue by happywillow0** [inorichi/tachiyomi-extensions#2413]
@as280093 Sorry for the direct ping but your the master of icons. 
#2408 needs some icons when you have a chance. Thank you and take your time.

**Comment by as280093** [comment]
@happywillow0 I don't mind getting direct ping, I prefer you ping when an icon is needed in PR 
mostly I will provide icon within 24hr of the creation of a PR if not I might DM you in Discord.

**Comment by happywillow0** [comment]
Good to know. 👍
