### ISSUE TITLE
[Bug] MangaMx: HTTP error 404

### ISSUE THREAD

**Issue by edgarMejia** [inorichi/tachiyomi-extensions#2417]
### Device information
* Tachiyomi extension version: 1.2.6
* Tachiyomi version: r1749 (dev version)
* Android version: 10

## Steps to reproduce
1. Go to Catalogues.
2. MangaMx -> Latest or Browse.

### Expected behavior
Show mangas

### Actual behavior
HTTP error 404 toast.

### Other details
The error always appears

**Comment by MerradOklom** [comment]
Hola Edgar. El error es porque la página está en mantenimiento, al menos lo ha estado desde esta mañana.

**Comment by happywillow0** [comment]
> Mientras tanto puedes ver este sexy baile.

![image](https://user-images.githubusercontent.com/45346080/76575818-b1423680-6496-11ea-8ee0-0bca387d1c90.png)

**Comment by edgarMejia** [comment]
Lo siento, mi error, me faltó revisar el sitio desde mi navegador.

**Comment by edgarMejia** [comment]
La extensión funciona correctamente, cerraré el issue.
