### ISSUE TITLE
[Bug] Japscan : image transformed into scattered squares

### ISSUE THREAD

**Issue by DiogoVieiraFerreira** [inorichi/tachiyomi-extensions#2418]
### Device information
* Tachiyomi extension version: 1.2.18
* Tachiyomi version: r1896 (9deaff91)
* Android version: 10

## Steps to reproduce
1. open shine 
![shine](https://user-images.githubusercontent.com/47444284/76633451-06d51c80-6545-11ea-8175-29db157f3eb3.jpg)
2. try to read chaps 6 to 30
3. several types of squares are visible with different parts of the current page
4. example : 
![example with squares](https://user-images.githubusercontent.com/47444284/76633698-68958680-6545-11ea-95a0-539194292346.jpg)

### Expected behavior
we can see a full picture

### Actual behavior
we see several squares with our picture

**Comment by o01210o** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/2219
