### ISSUE TITLE
[Bug] Japscan catalog missing

### ISSUE THREAD

**Issue by maggotb** [inorichi/tachiyomi-extensions#2419]
Device information

    Tachiyomi version: 0.8.5
    Android version: 7.1.1

Steps to reproduce

    Install Tachiyomi
    In the app, install japscan extension.
  
Expected behavior

There should be a Japscan catalog

Actual behavior

Catalog is missing

I tried reinstalling the app and the extension but it is still missing

**Comment by happywillow0** [comment]
On the catalog screen, do you have the French language enabled? Check the filters on the top right.

**Comment by maggotb** [comment]
> 
> 
> On the catalog screen, do you have the French language enabled? Check the filters on the top right.

It is fixed thanks, I didn't think about going in the filters
