### ISSUE TITLE
[Bug] Komikcast : Cannot Acces, Bypass Cloudflare

### ISSUE THREAD

**Issue by Bcahthekill** [inorichi/tachiyomi-extensions#2420]
**Device Information**
Tachiyomi extension version: 1.2.4
Tachiyomi version: 0.8.5

**Step to Reproduce**
Click on: Catalogues
Click on: Komikcast, either lastest or explore

**Expected Behavior**
Acces to Komikcast 

**Actual Behavior**
Blank page, cannot acces to Komikcast

**Bug**
Java.io.IOException:Failed to bypass Cloudflare!

**Comment by happywillow0** [comment]
Tachiyomi uses cloudflare to attempt to bypass cloudflare. 

What kind of phone do you have? Who made the phone?
What system version is the phone running?
Have you checked to see if there is a update to Android webview and Google Chrome in the play store?

**Comment by pervertkirito** [comment]
this could be same with [this too](https://github.com/inorichi/tachiyomi/issues/2552)

**Comment by SnakeDoc83** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/3475
