### ISSUE TITLE
[Bug] mangadex: latest does not populate correctly.

### ISSUE THREAD

**Issue by lllBARC0DElll** [inorichi/tachiyomi-extensions#2421]
### Device information
* Tachiyomi extension version: 1.2.85
* Tachiyomi version: 0.8.5
* Android version: 10

### Expected behavior
I click latest and should get a list of manga longer than 30 entries and should pull up to access more if loading. Alternatively i should be able to go into browse and sort by new and get anything.

### Actual behavior
This happens instead: latest only has a few titles and when i try going through browse and sorting through there i get 0 titles.

### Other details
I am signed in through mangadex. webview seems to work fine. I have fresh installed tachiyomi and uploaded a backup. Have changed image server. Went to support through discord. They are not able to replicate my issues. 

![Screenshot_20200314-041155_Tachiyomi](https://user-images.githubusercontent.com/62170293/76678295-0b352000-65ad-11ea-8c73-aaa9956d6d53.jpg)

![Screenshot_20200314-035942_Tachiyomi](https://user-images.githubusercontent.com/62170293/76678285-ff495e00-65ac-11ea-9ebe-046e98c1ed1c.jpg)

**Comment by CarlosEsco** [comment]
Arrow should be down but also. I can't replicate this.  Latest has endless scroll for me

**Comment by happywillow0** [comment]
Have you tried to search manually within webview to see what happens?

**Comment by lllBARC0DElll** [comment]
> Arrow should be down but also. I can't replicate this. browse Latest has endless scroll for me

The arrow is up just to match someone from discords test, both up and down do not reveal any results

> Have you tried to search manually within webview to see what happens?

I get my desired manga listed
