### ISSUE TITLE
[Bug] Dmzj : many new comics can't be found

### ISSUE THREAD

**Issue by pkszzcq** [inorichi/tachiyomi-extensions#2422]
### Device information
* Dmzj version: 1.2.8
* Tachiyomi version: 0.8.5
* Android version: 10

Lots of comics can't be searched but they are works on the site.I'm not sure what they have in common.Maybe it ’s because they are all new on the website.
forexample:
”裂口姐姐“
https://manhua.dmzj.com/liekoujiejie

“想让你说出喜欢我”
https://manhua.dmzj.com/xiangrangnishuochuxihuanwo

“落后的驯兽师慢生活”
https://manhua.dmzj.com/luohoudexunshoushimanshenghuo

**Comment by happywillow0** [comment]
I have no clue why search results are different right now but I recommend trying out Tachiyomi dev where the search results do include the manhua you have as examples.

**Comment by pkszzcq** [comment]
> ~I have no clue why search results are different right now but I recommend trying out Tachiyomi dev where the search results do include the manhua you have as examples.~
> 
> Edit: Now it works for both. 💢
> I don't know what is happening with the search

I'm so sorry for my incorrect submit . 
I try to use the function "clear database" in setting then the search returns to normal.
