### ISSUE TITLE
[Bug] HeavenManga (ES) : Broken Extension

### ISSUE THREAD

**Issue by MerradOklom** [inorichi/tachiyomi-extensions#2432]
### Other details
So, the site (https://heavenmanga.com/top) changed their framework thus rendering the extension completely unusable. I will leave it up to you, the devs, to choose what to do with it, either fix it or delete it, whatever you choose is fine. When I requested this source there were not many Spanish sources to read from, but this has since changed and now there are plenty to choose and definitely much better than this one.

**Comment by happywillow0** [comment]
I agree, the site isn't that great. 

Looking at the link, a number of covers are missing. In addition, the sorting `?orderby=views` doesn't seem to work for me either.

Side bar, I'm still keeping an eye on TMO and was thinking about bringing it back after their servers settle down.
