### ISSUE TITLE
[Bug] مانغا العاشق : Chapers not found

### ISSUE THREAD

**Issue by houx00** [inorichi/tachiyomi-extensions#2437]
### Device information
* Tachiyomi extension version: 1.2.1
* Tachiyomi version: 0.8.4
* Android version: 6.0

**Comment by happywillow0** [comment]
Are you talking about Shqqaa manga? 

I just tested it out and it seems to load fine. Is there a specific one that it doesn't work with or is it a different website?

**Comment by houx00** [comment]
3asq.org<https://3asq.org/manga/kimetsu-no-yaiba/>
This is the web site

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by happywillow0** [comment]
Sorry I didn't know what site so I took an educated guess.

I'm looking at 3asq.org right now. 

I had briefly got the message `الموقع مغلق للصيانة` translated ' The site is closed for maintenance' so that may be the issue. I would try again later.

**Comment by houx00** [comment]
Oh i see thank you for your time

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by happywillow0** [comment]
The site looks to be running. Is this still an issue for you?

**Comment by houx00** [comment]
No the app going well thank so much you for your time

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
