### ISSUE TITLE
[Bug] TuMangaOnline : Change Domain

### ISSUE THREAD

**Issue by wruizcanal** [inorichi/tachiyomi-extensions#2438]
The TuMangaOnline site changed its domain url to: https://lectortmo.com/

**Comment by joseph619** [comment]
TuMangaOnline is no longer supported

**Comment by wruizcanal** [comment]
OK

**Comment by happywillow0** [comment]
I'm still looking at the servers and how they are doing. They are still facing SSL issues with the image server. 

I was debating if I want to re-upload it again once things settle down.
