### ISSUE TITLE
[Bug] LectorManga : does not open the series chapters

### ISSUE THREAD

**Issue by wruizcanal** [inorichi/tachiyomi-extensions#2439]
## Steps to reproduce
1. Find a series in LectorManga.
2. Select and Open a Chapter.

### Expected behavior
The images of the chapter are shown.

### Actual behavior
Launches a notification that the page is empty.

### Other details
When I go to the web view option it shows me the description and the image of the series well. But when I select a chapter and click on see instead of the images it shows me an advertisement for the Scan. This makes the app not find the images and therefore the chapters cannot be seen.

**Comment by MerradOklom** [comment]
Limpia el caché de imágenes y la base de datos en las configuraciones avanzadas y prueba cambiando el método de obtención de imágenes a Paginado en las preferencias de la extensión. A mí me funcionó siguiendo estos pasos, aunque algunas páginas cargan muy lento, pero ese es un problema de la web de LectorManga ya que sus servidores están muy sobrecargados.

**Comment by happywillow0** [comment]
Thank you for confirming that the servers are possibly overloaded and the slowness isn't just me. 
I have been testing a fix for the pages but I've been wondering what the slowness was from.
