### ISSUE TITLE
Mangadex mostly empty fields

### ISSUE THREAD

**Issue by Timmy1e** [inorichi/tachiyomi-extensions#244]
Versions: 0.6.8, r1370

A whole bunch of things are not showing for Mangadex:
cover images, author, last chapters, title header, source, description, updated, and everything for the chapters.

I've cleaned my database and cache.

**Comment by CarlosEsco** [comment]
What version of mangadex?

**Comment by Timmy1e** [comment]
@CarlosEsco version 1.2.16
I resolved it by uninstalling Mangadex, cleaning cache and database, and reinstalling it.

**Comment by CarlosEsco** [comment]
In future if you on latest just swipe refresh on the manga info page
