### ISSUE TITLE
[Bug] NineMangaEs: Does not load extension

### ISSUE THREAD

**Issue by jorxvader** [inorichi/tachiyomi-extensions#2442]
The NineMangaEs extension does not work but the website does.

**Comment by MerradOklom** [comment]
What do you mean? It's working perfectly for me.

**Comment by jorxvader** [comment]
![Screenshot_2020-03-18-12-30-36](https://user-images.githubusercontent.com/33550088/76956537-85023c00-6914-11ea-92d6-32054c784991.png)
this is the only show me every time. Reload, can't open any manga, search or something.

**Comment by MerradOklom** [comment]
Well, it's most likely a problem in your end. Are you using WiFi? Try switching to data and try again. If the problem persists try using a VPN.
![S1](https://user-images.githubusercontent.com/43864503/76957409-828fea00-68f4-11ea-9afe-b93c82fd64df.png)

**Comment by jorxvader** [comment]
Same, can't enter. But i can see the website with Chrome.

![Screenshot_2020-03-18-12-54-13](https://user-images.githubusercontent.com/33550088/76958260-b0d2f100-6917-11ea-9924-7bd04c5d81c1.png)

**Comment by MerradOklom** [comment]
Make sure the extension and app are up-to-date. Latest version of the NineManga extension is 1.2.8 and the latest (stable) version of the app is 0.8.5. Also, do you have disabled the Android Web View? It is necessary to bypass the Cloudflare protection in some sources, I don't think it's related to your problem but try enabling it and update it if required.

**Comment by jorxvader** [comment]
I have the last update 0.8.5 and 1.2.8 for NineManga.

How can I disable the Android Web View? I don't think I have enabled but I don't know if it was.

**Comment by MerradOklom** [comment]
Check this: https://play.google.com/store/apps/details?id=com.google.android.webview
Enable it (if disabled) and update it (if required)
I don't have any more ideas, if that doesn't work hopefully someone more capable and with more knowledge will come to help you.

**Comment by jorxvader** [comment]
Ok... reset router and now works... 😒
Internet is trolling me today. Thanks for your help.
