### ISSUE TITLE
[Bug] Tapas : chapters won't load

### ISSUE THREAD

**Issue by Sheppysneik** [inorichi/tachiyomi-extensions#2449]
### Device information
* Tachiyomi extension version: 1.2.5
* Tachiyomi version: dev r1928
* Android version: 7.0

## Steps to reproduce
1. Choose a tapas comic
2. Open a chapter

### Expected behavior
for the page to load and display the chapter

### Actual behavior
Upon clicking on the chapter, the page briefly loads before displaying "retry", when clicking on it nothing else happens.

### Other details
For a short period after 1.2.5 was released everything was working smoothly. Thumbnails are being loaded correctly, just like the list of chapters.

**Comment by happywillow0** [comment]
note for others or me for later:
```kotlin
if (it.hasAttr("data-src")) it.attr("abs:data-src") else it.attr("abs:src")
```
