### ISSUE TITLE
[French] nihonscan

### ISSUE THREAD

**Issue by xcsh** [inorichi/tachiyomi-extensions#245]
http://nihonscan.com/

Thanks !

**Comment by cmalard** [comment]
Hi @CarlosEsco , what's missing to remove the `Source Request` label ?

**Comment by CarlosEsco** [comment]
So the label, is just so any  developers who is looking to implement a source knows that this is a Source Request, not necessarily asking for the source url

**Comment by as280093** [comment]
Url redirects to http://animes9.com/ which is anime site
