### ISSUE TITLE
[Bug] Mangatensei is broken the cover of manga not showing properly

### ISSUE THREAD

**Issue by AyatoHigashi** [inorichi/tachiyomi-extensions#2450]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 9

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

### Other details
Additional details and attachments.

**Comment by happywillow0** [comment]
Notes for later or others:
``` kotlin
val imgurl = item.select("img").attr("src")
```
