### ISSUE TITLE
[Source Request] Gmanga

### ISSUE THREAD

**Issue by dzotaku66** [inorichi/tachiyomi-extensions#2452]
### Source Website
Website can be found at <gmanga.me>.

### Other Details
It's an arabic website which contains a lot of manga series

**Comment by happywillow0** [comment]
Thank you for your suggestion and input. There is already an open suggestion for gmanga here #117

That said, they use a complex website with authentication / tokens for all their server communications so it is unlikely that this source can be added.

**Comment by mged** [comment]
try it this time? maybe use jsoup or try to get their api?
