### ISSUE TITLE
[Source Request] SMBC (Saturday Morning Breakfast Cereal)

### ISSUE THREAD

**Issue by opusforlife2** [inorichi/tachiyomi-extensions#2453]
### Source Website
Website can be found at https://www.smbc-comics.com/

### Other Details
It would be a good complement to XKCD. :)

**Comment by happywillow0** [comment]
SMBC comics can actually be accessed with Hive Works Comics. We still need to attempt a basic search and add a letter filter but you should be able to find it at some point in the browse catalog.

**Comment by opusforlife2** [comment]
Found it. I see Hiveworks also contains Cyanide & Happiness, but not XKCD. Is there no source that contains all three? Or is there a specific reason why XKCD and C&H are their own extensions?

**Comment by happywillow0** [comment]
XKCD is still independent and isn't part of the Hiveworks network of comics. 
Cyanide & Happiness uses a custom archive page which isn't supported at this time. It was just easier to use it's own.

**Comment by happywillow0** [comment]
You didn't ask but because of you, #2458 upgrades SMBC to include the extra comic and alt text (like XKCD)

**Comment by opusforlife2** [comment]
Awesome! Thanks so much! :)
