### ISSUE TITLE
Mangasy : HTTP Error 403

### ISSUE THREAD

**Issue by samanta-widjaja** [inorichi/tachiyomi-extensions#2457]
### Device information
* Tachiyomi extension version: Madara 1.2.60
* Tachiyomi version: 0.8.5
* Android version: 7.1.1

## Steps to reproduce
1. Browse and latest not working. No new chapter detected from update library

### Expected behavior
Browse and latest should working. New chapter detected when running update library

Thanks

### Actual behavior
This happens instead

**Comment by happywillow0** [comment]
MangaSY has turned on manual captcha. While the manual captcha is on, you must open up the site in [webview and solve the captcha](https://tachiyomi.org/help/guides/source-problems/#solving-a-captcha) before you can do anything.

![image](https://user-images.githubusercontent.com/45346080/77138346-11f9e200-6a48-11ea-823e-ce002567df86.png)

**Comment by samanta-widjaja** [comment]
ok. thanks. can it bypass automatically?

**Comment by happywillow0** [comment]
There is not currently a way to bypass the _manual_ captcha automatically.

**Comment by samanta-widjaja** [comment]
ok. thanks @happywillow0
