### ISSUE TITLE
[Source Request] Mangalord

### ISSUE THREAD

**Issue by ZEXERJK** [inorichi/tachiyomi-extensions#2461]
### Source Website
Website can be found at [MANGALORD](https://www.mangalord.com) .

### Other Details
Site that do english translations and also hosts mangatoon projects etc.
They upload only on the website, they have a fair amount of manhuas.

**Comment by einstein95** [comment]
Uses Madara, should be as simple as adding it to the existing extension.

**Comment by ZEXERJK** [comment]
Then it will be added?

**Comment by einstein95** [comment]
@ZEXERJK yes, I have it added locally. I am trying to find more requested Madara sites before committing

**Comment by ZEXERJK** [comment]
> @ZEXERJK yes, I have it added locally. I am trying to find more requested Madara sites before committing

Thanks 👍
