### ISSUE TITLE
[Bug] Disaster Scans : Name of manhuas not showing

### ISSUE THREAD

**Issue by ZEXERJK** [inorichi/tachiyomi-extensions#2462]
### Device information
* Tachiyomi extension version: Madara 1.2.60
* Tachiyomi version: 0.8.5
* Android version: 10

## Steps to reproduce
1. Go to Catalogs in tachiyomi and search for Disaster Scans.
2. Tap to see all the manhuas for that particular source.

### Expected behavior
![20200320_141919](https://user-images.githubusercontent.com/48049633/77167232-ea416300-6ab5-11ea-915b-d13d58cf848e.jpg)

### Actual behavior
![20200320_141820](https://user-images.githubusercontent.com/48049633/77167358-3096c200-6ab6-11ea-9427-7ae70c778634.jpg)

### Other details
Overall view:
![20200320_141717](https://user-images.githubusercontent.com/48049633/77167289-0ba24f00-6ab6-11ea-9e2a-19d99e0073e7.jpg)

Webview:
![20200320_142559](https://user-images.githubusercontent.com/48049633/77167671-be72ad00-6ab6-11ea-83fa-b1000d7458ef.jpg)

**Comment by banra123** [comment]
Same issue here
