### ISSUE TITLE
[Source Request] 2x Madara sites: Manga Tales and MangaWOW

### ISSUE THREAD

**Issue by einstein95** [inorichi/tachiyomi-extensions#2466]
### Source Website
Websites can be found at https://mangatales.com/ and https://mangawow.com/.

### Other Details
Both sites use the Madara WordPress plugin, of which there's a pre-existing implementation.

**Comment by happywillow0** [comment]
MangaWow can be added. They don't really have good dates though. 

I'm not sure MangaTales is a Madara website. It doesn't look like one to me.

**Comment by einstein95** [comment]
@happywillow0 oh, you're right, MangaTales isn't. It was on a Madara "featured users" thing on a site, along with a few others.

Closing the issue since MangaWow has been added.
