### ISSUE TITLE
[Feature Request] Mangaeden login: logging in Mangaeden to access NSFW content

### ISSUE THREAD

**Issue by aatuvaa** [inorichi/tachiyomi-extensions#2476]
Recently the site Mangaeden (I'm using the italian one but i think the problem is the same with the english one) made the access to NSFW content not possible unless you're logged into the site. My suggestion is to add the possibility to log in through the extension to solve the problem.

**Comment by MerradOklom** [comment]
Have you tried logging in using web view?

**Comment by aatuvaa** [comment]
> Have you tried logging in using web view?

solved, thank you. I'll remove the issue
