### ISSUE TITLE
[Source Request] Super hentai Manga

### ISSUE THREAD

**Issue by Darlos28** [inorichi/tachiyomi-extensions#2479]
###One of the best hentai or doujin manga readers Portuguese (Brazil)

https://www.superhentais.com/hentai-manga

###There is no need to login or verify, access is quick and convenient, without errors.

**Comment by MerradOklom** [comment]
Why are you posting the same request over and over again (#2477, #2478)? One is more than enough.

**Comment by Darlos28** [comment]
Oops, I posted the same post over and over again because I thought they
weren't going to see it because there are several, I didn't think it was
going to be a problem. Sorry

Em dom, 22 de mar de 2020 3:07 PM, arkon <notifications@github.com>
escreveu:
