### ISSUE TITLE
Can you add readcomiconline.to please

### ISSUE THREAD

**Issue by almozayaf** [inorichi/tachiyomi-extensions#248]
http://readcomiconline.to/

**Comment by CarlosEsco** [comment]
Extension already exists

**Comment by almozayaf** [comment]
How to use it, And can you explain as easer as you can (My english is weak)

**Comment by CarlosEsco** [comment]
If you are on latest stable 0.7.0 open extensions on left side bar and then scroll til you find and click install

**Comment by almozayaf** [comment]
@CarlosEsco 

It worked, but why there was no extensions tap before?

**Comment by CarlosEsco** [comment]
Was new feature added

**Comment by mikykeane** [comment]
Hi. It seems as the extension is not working any more? Would it be possible to add it again? I'm getting a parsing error in line 1.

**Comment by CarlosEsco** [comment]
update your extensions and or app

**Comment by Dread0004** [comment]
Bro I think I have the latest vers. of the app... But its still not working....

**Comment by arkon** [comment]
Open a new issue with more information if you think it's not working as expected.

**Comment by mikykeane** [comment]
I thought the same. But I download it again and it works just fine for me.
