### ISSUE TITLE
[Bug] Hocvientruyentranh extension is still not loading Image 

### ISSUE THREAD

**Issue by leoparker157** [inorichi/tachiyomi-extensions#2482]
### Device information
* Tachiyomi extension version: 1.2.7
* Tachiyomi version: 0.8.5
* Android version: 8

After updated , Extension is still not loading some chapters , 
Example : https://hocvientruyentranh.net/chapter/203344/nanatsu-no-taizai-chapter-344-raw or https://hocvientruyentranh.net/chapter/204769/act-age-chapter-104
 those chapters still load on normal Browser or Webview , but it's got error in tachiyomi  
![image](https://user-images.githubusercontent.com/59758841/77321592-fc850080-6d44-11ea-805f-99d123bb448c.png)

**Comment by mged** [comment]
the app and its extension is almost useless after the new updates, tons of extensions has stopped working and the other are half workig ( first chapters not loading, donwloading is unavaibale, crashes and slow loading i tried it on mulity extensions.)

a good exapmle is manga ae the first chapters are not loading.
