### ISSUE TITLE
[Bug] MangaDex : Http error 502

### ISSUE THREAD

**Issue by TheOnlyReeee** [inorichi/tachiyomi-extensions#2489]
### Device information
* Tachiyomi extension version: ?
* Tachiyomi version: ?
* Android version: ?

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened

### Actual behavior
This happens instead

**Comment by happywillow0** [comment]
> ZephyrusToday at 10:17 PM
> We are aware of the issues the site is experiencing. Remember, we are experiencing the upper limits of our user capacity due to various quarantines and lockdowns. We will upgrade as soon as we are able. In the meantime, please be patient while we investigate.

**Comment by CarlosEsco** [comment]
They announced site back up so should have no issues now
