### ISSUE TITLE
Mangakakalot: HTTP error 403; web view shows "site is closed"

### ISSUE THREAD

**Issue by nicodemus88** [inorichi/tachiyomi-extensions#2491]
**Device information**
Tachiyomi extension version: MangaBox 1.2.16
Tachiyomi version: r1936
Android version: 8.0.0

**Steps to reproduce**
Browse and latest not working. No new chapter detected from update library

**Expected behavior**
Browse and latest should be working. New chapter detected when running update library

**Actual behavior**
HTTP error 403

**Steps tried to fix the issue**
1. Uninstalled and reinstall the extension
2. Updated Tachiyomi to latest dev version

In addition to that, browsing mangakakalot on the web (https://mangakakalot.com) shows the message "This site is closed. Thank you. Have a nice day." 

I think they changed their webpage or something as when I browse https://mangakakalots.com, I was able to view it. 

Maybe the extension needs some updating here? Or is there any way I can solve this issue?

Thank you very much.

**Comment by happywillow0** [comment]
-  Mangakakalot**s** is a different website
- Site closed is a IP ban, similar to KissManga site is under maintenance.  (Likely per country / location). Use a VPN or migrate to a different source. (Try the other sister site, nelo?)

**Comment by SnakeDoc83** [comment]
@arkon If he can't even access the website by browser, there's nothing we can do.
