### ISSUE TITLE
[Issue] MangaDex : HTTP Error 500

### ISSUE THREAD

**Issue by marcos123123** [inorichi/tachiyomi-extensions#2493]
##Device information
* Tachiyomi extension version: 1.2.85
* Tachiyomi version: 0.8.5
* Android version: 5.1.1

###Steps to reproduce
1. Go to recently read
2. Click on "resume chapter" on any manga hosted by MangaDex

### Expected behavior
Chapter should open normally

### Actual behavior
Http error 500 occurs 

###Other details
Mangadex worked fine the day before, could read anything without problem. Error came up while I was trying to resume a manga. Searching doesn't work (even searching via id:xxxx).

**Comment by marcos123123** [comment]
My apologies to any user, developer or moderator if this issue has been brought up before and has been resolved, I'm quite new to this app and I don't know many of its quirks and problems.

**Comment by CarlosEsco** [comment]
website was down per their discord, it should be up now.
