### ISSUE TITLE
Kissmanga - 403 error [Kissmanga is banning users]

### ISSUE THREAD

**Issue by mrcn0** [inorichi/tachiyomi-extensions#2496]
* Tachiyomi version: 0.8.5
* Android version: 9

Steps:
1a. Open Kissmanga catalogue
1b. Open any manga from Kissmanga catalogue

Expected to be open/loaded.

Actual behavior: error 403 pops up, content fails to load.

Additional info: it seems to be failing this way for the last day or so.

**Comment by Wang-Derr** [comment]
It's an error on kissmanga side, they are having server issues
https://www.reddit.com/r/KissCommunitySupport/comments/fo57n7/kissmanga_is_down/

**Comment by dr-nyt** [comment]
Kissmanga is back online and HTTP error doesn't appear anymore but instead it says "Page list empty" which I'm assuming is that they changed something on the server or the formatting of the website.

**Comment by Sajeeb97** [comment]
Any idea when the issue is resolved or should I move all my favorite mangas to other sources. If the issue is permanent

**Comment by SlurpelDur** [comment]
> * Tachiyomi version: 0.8.5
> * Android version: 9
> 
> Steps:
> 1a. Open Kissmanga catalogue
> 1b. Open any manga from Kissmanga catalogue
> 
> Expected to be open/loaded.
> 
> Actual behavior: error 403 pops up, content fails to load.
> 
> Additional info: it seems to be failing this way for the last day or so.

I'm getting a "page list is empty" error

**Comment by otonieru** [comment]
Kissmanga is live, but it still show page list empty. So this is no captcha nor server issue.

**Comment by CarlosEsco** [comment]
a new build was pushed.  update in about 10mins and report back

**Comment by gediefedilo1123** [comment]
still says page list is empty

**Comment by ptoump** [comment]
Tachiyomi r1940 & KissManga 1.2.12, webview seems to return a white line only, browser (FF) loads KissManga correctly.
Nothing else loads (lists, manga, chapter lists)

**Comment by Sajeeb97** [comment]
Dont know why when I try to visit kissmanga site with wifi it says maintenance break but if I visit it with mobile data the site loads and working fine.Whats wrong with kissmanga will it be fixed or there is issues cauz some ppl saying on reddit that kissmanga is ip banning users who are using apps like tachiyomi.Plz if anyone knows the situation well, elaborate it.

**Comment by otonieru** [comment]
Yeah, opera saying its on maintenance, while chrome opening it just fine

**Comment by gediefedilo1123** [comment]
apparently they're ip banning people for using tachiyomi. So what you're seeing is only "under maintenance" but the site is already working

**Comment by Sajeeb97** [comment]
> apparently they're ip banning people for using tachiyomi. So what you're seeing is only "under maintenance" but the site is already working

Yeah I think so.
So whats the soln, should we move to different source or they are gonna negotiate with them .Either way admin should explain the situation cauz many users who use kissmanga as their primary source as it has vast amount of series and updates fast.

**Comment by CarlosEsco** [comment]
negotiate?  what do you even mean.  They want that ad revenue.  Also what situation should we explain the source doesn't work cause you were ip banned?

**Comment by dr-nyt** [comment]
I could access the website earlier today for a little bit on my PC but now I can't access it at all. I will ask my friend who doesnt use tachiyomi and get back to you.

**Comment by dr-nyt** [comment]
Yeap my friend who doesnt use tachiyomi can access the site just fine. We got hit with a ban hammer. Sadly I live in Dubai where VPNs are banned but could anyone try using a VPN and let me know if that works?

**Comment by Sajeeb97** [comment]
> negotiate? what do you even mean. They want that ad revenue. Also what situation should we explain the source doesn't work cause you were ip banned?

So is there no way.
That means kissmanga is also down like manga rock for free users like us.
In short we have to migrate our manga to other sources.
If u could elaborate the situation to us it would be helpful,as I have lots of favorite manga from kissmanga source.So that we can move the mangas on other sources

**Comment by Sajeeb97** [comment]
> Yeap my friend who doesnt use tachiyomi can access the site just fine. We got hit with a ban hammer. Sadly I live in Dubai where VPNs are banned but could anyone try using a VPN and let me know if that wo

> Yeap my friend who doesnt use tachiyomi can access the site just fine. We got hit with a ban hammer. Sadly I live in Dubai where VPNs are banned but could anyone try using a VPN and let me know if that works?

Using vpn works just fine

**Comment by dr-nyt** [comment]
Can anyone recommend a good manga source

**Comment by Sajeeb97** [comment]
> Can anyone recommend a good manga source

Mangadex,mangasee,isekaiscans,mangaowl

**Comment by arkon** [comment]
GitHub is not a casual discussion forum. If you have non-development related questions or need general help, please use our Discord server.

---

Tachiyomi is not a content provider and we do not negotiate with content providers. We can do our best to provide access via the extensions, but it's just a best-effort attempt.
