### ISSUE TITLE
[Source Request] 2x B-Hentai, Neox Scan

### ISSUE THREAD

**Issue by Darlos28** [inorichi/tachiyomi-extensions#2497]
### Oii, I again here. Thanks for adding the Super Hentai font At Tachiyomi, I came humbly to ask you to add two new fonts to the App, if it’s not too much work for you guys, from now on you guys have my gratitude. PT-BR

https://neoxscan.com/newsite/

http://baixarhentai.net/h-mangas

### Both sites are great, both don't need boring logins or checks.

**Comment by alessandrojean** [comment]
BaixarHentai is already available at the FoolSlide extension.

Neox can be added to Madara, I will work on that.
