### ISSUE TITLE
[Bug] Source Name : KissManga - "Page list is empty" Error

### ISSUE THREAD

**Issue by SlurpelDur** [inorichi/tachiyomi-extensions#2504]
### Device information: Samsung Galaxy s8
* Tachiyomi extension version: 1.2.11
* Tachiyomi version: 0.8.5
* Android version: 9

## Steps to reproduce
1. First Step: Select and open any manga you want to read.

2. Second Step: Select and open any chapter.

### Expected behavior:
Chapter loads and I begin reading.

### Actual behavior
Chapter tries to load and then closes. I also get a message saying "Page list is empty".

### Other details:
I tried restarting my phone and closing and reopening the app, still get the same issue.

**Comment by bbtora** [comment]
#2496
