### ISSUE TITLE
[Source Request] Mangago

### ISSUE THREAD

**Issue by Dicer03** [inorichi/tachiyomi-extensions#2507]
### Source Website
Website can be found at http://mangago.me/

### Other Details
It supports numerous latest and in demand manga, manhua and manhwas.

**Comment by bbtora** [comment]
Thanks for the suggestion. Mangago is on the `no longer supported extensions` list due to their actions that actively break the extension link.

#988

**Comment by Dicer03** [comment]
Aw thats too bad, but thanks for the heads up
