### ISSUE TITLE
[Source Request] Manga Pro Z (AR)

### ISSUE THREAD

**Issue by dzotaku66** [inorichi/tachiyomi-extensions#2511]
### Source Website
Website can be found at <https://www.mangaproz.com/?m=1>

### Other Details
Manga source which contains a lot of manga and manhwa series

**Comment by AbdullahM0hamed** [comment]
Exists:

https://github.com/inorichi/tachiyomi-extensions/blob/15c6ade5fbe023db0963e53ae442fe9b78e5bf06/src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt#L645
