### ISSUE TITLE
dummykiss leike obsolete mangarock extension

### ISSUE THREAD

**Issue by Batlh** [inorichi/tachiyomi-extensions#2520]
Tachiyomi Stable v0.8.5
kissmanga: 1.2.13

can we made this extension a dummy version like the obsolete mangarock extension?

**Comment by arkon** [comment]
Dummyrock was a third party extension, so someone would need to do that.

**Comment by Batlh** [comment]
oh never had known that

**Comment by SnakeDoc83** [comment]
Somebody posted one on discord, you can find a link in #faq.

**Comment by Batlh** [comment]
I saw that
I was also the one that helped to recreate it for kiss but i thought it was created from the tachiyomi extension repository 
But anyway thx i will close this issue then
