### ISSUE TITLE
Can't  access manga from mangahasu

### ISSUE THREAD

**Issue by BrownIndianGuy** [inorichi/tachiyomi-extensions#2521]
**App version:**
J2k 0.9.81
**Android version:**
9.p
**Issue/Request:**
Ask yo enable javascript. In browser as well as webviee
**Steps to reproduce (if applicable)**

 1.open in webview
 2.
 3.

**Other details:**
[Link ](https://i.ibb.co/SXybBcg/Screenshot-20200326-210447.png)

**Comment by happywillow0** [comment]
I just tried looking at nozomanu fushi no boukensha chapter 24 as you linked on dev and j2k and it seems to be loading fine. Have you tried it recently and is it still not working for you?

**Comment by Quantitativity** [comment]
I've had this issue before, I had to go to my developer options and change my webview to chrome

**Comment by arkon** [comment]
#2193
