### ISSUE TITLE
[Bug] Cover image not displaying from 1st Kiss and GetManhwa Source

### ISSUE THREAD

**Issue by vipzzx** [inorichi/tachiyomi-extensions#2524]
### Device information
* Tachiyomi version: 0.9.81
* Android version: 10

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
Cover image should be visible and editable if wanted.

### Actual behavior
There is no image. When going into source (1st Kiss) and selecting a manga, the cover image will disappear and become editable too. 

### Other details
Additional details and attachments.

**Comment by SnakeDoc83** [comment]
version .9.81?  You're using j2k.  Just tested and it's not an issue in stable.

**Comment by vipzzx** [comment]
> version .9.81? You're using j2k. Just tested and it's not an issue in stable.

Yes I am using j2k. I downloaded the stable and dev to see if it works. GetManhwa works but I am still having the same issue with 1st Kiss extension. When I click into the manga, the cover image disappears and does not show up afterwards
