### ISSUE TITLE
[Bug] hitomi.la on tachiyomiEH

### ISSUE THREAD

**Issue by Gjalarhorn** [inorichi/tachiyomi-extensions#2526]
### Device information
* Tachiyomi extension version: ?
* Tachiyomi version: v8.4.5-EH
* Android version: 8.1.0

## Steps to reproduce
1. First Step
 Searching manga on hitomi.la, nhentai, ehentai
2. Second Step

### Expected behavior
I get the result from any source

### Actual behavior
I get 'http error 404' only on hitomi.la

**Comment by arkon** [comment]
Open an issue in the EH or AZ repo, we don't support those.
