### ISSUE TITLE
[Bug]  the contents in manga park extension differs from that of the webview in both the latest and browse from the app 

### ISSUE THREAD

**Issue by kuroBi99** [inorichi/tachiyomi-extensions#2528]
### Device information
* Tachiyomi version: ? r1940
* Android version: ? Android Q

## Steps to reproduce
1. First step/ download and install mangapark extension (v.1.2.10)
2. Second step go to catalogues and open latest or browse of mangapark

### Expected behavior
This should happen. In latest You should be seeing the latest of mangas if you opened it 
Or in browse you should be able to browse all contents 

### Actual behavior
This happened instead. In latest it brings me contents that are from 2019 , in browse it brings limited contents not all of them like in the webview. 

### Other details
Additional details and attachments.
You should open mangapark in both the tachiyomi apk and in webview and carefully compare them so You can see the difference , it shouldn't bring any contents from 2019 like it has happened in the app it also doesn't bring  all the latest updates.

![Screenshot_2020-03-27-17-13-31-950_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/61652119/77767723-8806d600-7052-11ea-859f-d28d22af8f0c.jpg)
![Screenshot_2020-03-27-17-14-41-598_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/61652119/77767737-8b9a5d00-7052-11ea-832f-0c884e648d00.jpg)
![IMG_20200327_174515](https://user-images.githubusercontent.com/61652119/77767861-bd132880-7052-11ea-8765-349a8ad55fce.jpg)

**Comment by SnakeDoc83** [comment]
I'm not seeing this happen.  Check again, may have been a hiccup on their side.  Also, the extension pulls from https://mangapark.net/genre?update and https://mangapark.net/search?orderby=views_a for latest and browse.

**Comment by kuroBi99** [comment]
No , it certainly is happening .if you open the site on your browser and compare the updated titles to that of tachiyomi app you see that there are difference in titles . Look at this title 
It was updated long ago in the site but now it's in the latest updates in the app, also go to the browse in the app try to pull to the bottom then you see that the amount of titles are too few compared to the site 
![IMG_20200329_113842](https://user-images.githubusercontent.com/61652119/77844812-4a20c380-71b2-11ea-81bf-fab637570c4a.jpg)
![Screenshot_2020-03-29-11-41-01-583_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/61652119/77844815-4e4ce100-71b2-11ea-990c-da7ace504c24.jpg)

**Comment by kuroBi99** [comment]
This one too ![Screenshot_2020-03-29-11-38-28-123_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/61652119/77844955-8143a480-71b3-11ea-9954-39623a1334cd.jpg)

**Comment by kuroBi99** [comment]
Isn't that wrong the the extension should pull from "
https://mangapark.net/latest" cause that's the latest updated titles

**Comment by SnakeDoc83** [comment]
It's not exactly "wrong" per se; the page being used is for the search engine and it's supposed to return the most recently updated manga.  It does return manga with new chapters, but I think there are other factors under consideration as well (e.g. changes to descriptions, tags, etc.) that make for other manga sometimes also being included.  So, using /latest might be better.

**Comment by kuroBi99** [comment]
I'm not convinced 😞
