### ISSUE TITLE
[Bug] Manga Eden : 404 HTTP -error

### ISSUE THREAD

**Issue by asif001** [inorichi/tachiyomi-extensions#2531]
### Device information
* Tachiyomi extension version: English 1.2.4
* Tachiyomi version: 0.8.5
* Android version: 10

## Steps to reproduce
1. Open Manga Eden catalogue
2.  Open any manga which cover page is blank

### Expected behavior
Expected to be showed the cover pages and be open/loaded

### Actual behavior
Cover page not showing and error 403 pops up, content fails to load

**Comment by asif001** [comment]
The issue is occurring because some urls ar returning 403 error from manga eden website like the url
https://www.mangaeden.com/en/en-manga/one-piece/
is returning 403 error. But it can be solved by using mangaeden api:
https://www.mangaeden.com/api/
I would like to work on this issue

**Comment by arkon** [comment]
I assume this is fixed by #3156
