### ISSUE TITLE
[Bug] Source Name : ChapterManga not working

### ISSUE THREAD

**Issue by ArzuHrpt** [inorichi/tachiyomi-extensions#2534]
Device information
* Tachiyomi extension version: English v1.2.16
* Tachiyomi version: v0.8.5
* Android version: 10

Steps to reproduce
1. Open ChapterManga source/ any manga from said source
2. View/read/download chapters

Expected behavior
Opening, reading or downloading a manga that has been added to library/browsing through source library

Actual behavior 
Manga chapter doesn't load, source doesn't show up in sources/categories list 

Other details
When i tap the chapter it says the loader is not implemented. However i uninstalled and then reinstalled the extension that has this source,nothing changed. Where the manga source name should have been i see these numbers:   4651816987362917150

**Comment by happywillow0** [comment]
The Chapter Manga website has been broken for a while now. Does it load manga for you when you try to read anything via your browser?

The source is broken and has been removed from Tachiyomi so you should migrate the manga to another website.

**Comment by ArzuHrpt** [comment]
Kinda figured that this was the issue but wanted to be sure. Thanks for the quick relpy ^^ and no it doesn't load anything anymore, last i saw chaptermanga working was about 10 days ago i believe. Website doesn't open in browser either.
