### ISSUE TITLE
[Feature Request] Mangadex: Show description in language of Sytem locale only

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi-extensions#2540]
Extension Version: 1.2.85

Currently, Mangadex shows manga description for all languages in the INFO tab, which makes it almost unreable for many manga. Requesting to show description for language of the system locale only, so that it's not a mess anymore.

**Comment by happywillow0** [comment]
I'm not sure there is any level of control provided. That is just how the descriptions are set up. 

- Example 1: https://mangadex.org/title/21562/kusuriya-no-hitorigoto
- Example 2: https://mangadex.org/title/22440/jumyou-wo-kaitotte-moratta-ichinen-ni-tsuki-ichimanen-de

**Comment by joseph619** [comment]
Carlos managed to make it work in Neko somehow

**Comment by arkon** [comment]
Neko is English only, which makes it much easier.

**Comment by CarlosEsco** [comment]
True but I got an idea I will try that should hopefully work.
