### ISSUE TITLE
[Bug] Mangapark : Smart list option not working

### ISSUE THREAD

**Issue by BurgerBob00** [inorichi/tachiyomi-extensions#2541]
### Device information
* Tachiyomi extension version: 1.2.11
* Tachiyomi version: j2k 0.9.81
* Android version: 10

## Steps to reproduce
1. Get mangapark extension
2. Use the extension setting smart list
3.Check manga senyuu. chapters
4.check mangapark website for senyuu. chapters

### Expected behavior
Both should have the same chapters

### Actual behavior
The site shows the chapters normally in it's full number while tachiyomi shows only 6 different chapters

### Other details
Here are some screenshots
![Screenshot_20200329-195805_Tachiyomi](https://user-images.githubusercontent.com/37774475/77856459-a35f1600-71f7-11ea-876f-c6341061a761.jpg)
![Screenshot_20200329-195916_Chrome](https://user-images.githubusercontent.com/37774475/77856480-cb4e7980-71f7-11ea-8aa4-b40429c6a1d3.jpg)

**Comment by BurgerBob00** [comment]
It seems like it does this at some other mangas too

**Comment by SnakeDoc83** [comment]
I'm guessing it's because that particular manga has volume numbers in the chapter names.
