### ISSUE TITLE
[Bug] Komga : Null reference error

### ISSUE THREAD

**Issue by w1kl4s** [inorichi/tachiyomi-extensions#2551]
### Device information
* Tachiyomi extension version: 1.2.8 
* Tachiyomi version: dev 1955
* Android version: 9

## Steps to reproduce
1. Open any entry from Komga source on dev version

### Expected behavior
Chapters load 

### Actual behavior
No chapters load, and Tachiyomi throws `Attempt to invoke virtual method 'eu.kanade.tachiyomi.extension.all.komga.dto.BookMetadataDto.getNumberSort()' on a null object reference` exception

**Comment by CarlosEsco** [comment]
Is your komanga on computer up to date?

**Comment by w1kl4s** [comment]
It was not, thanks for the tip, it fixed the issue. Didn't realize Komga had such a rapid release schedule.

Problem was not present on stable 0.8.5 with Komga extension with same version, so i ruled out server-side problem at first.
