### ISSUE TITLE
[Bug] Mangakakalot: chapters not updating anymore

### ISSUE THREAD

**Issue by panslothda** [inorichi/tachiyomi-extensions#2552]
### Device information
* Tachiyomi extension version: Mangabox 1.2.16
* Tachiyomi version: 0.9.82 (TachiyomiJ2K)
* Android version: 9

## Steps to reproduce
1. Subscribe to some series
2. Some of them update some dont

### Expected behavior
Always see new chapters

### Actual behavior
Some series i am subcribed to simply dont update

### Other details
Specifically i have some series that i am subscribed to that do not realise there are new chapters. For example against the gods has 74 chapters when checking in my librarym and on the catalogue it has 76
![Screenshot_20200330-221609](https://user-images.githubusercontent.com/19254254/77958010-b1369900-72d4-11ea-8e74-569a30d51694.jpg)
![Screenshot_20200330-221550](https://user-images.githubusercontent.com/19254254/77958012-b267c600-72d4-11ea-8562-98bfda688dc7.jpg)

This happens with quite a few of them on mangakakalot of my multiple hundred subscribtions and more and more are not updating anymore. 

Also when i check the catalogue directly and search for it shows it as if i am no longer subscribed to the series and if I subscribe to it again i have 2 in my library. One that is "dead" and one that is up2date. But both show the correct extension and name but content is different.

![Screenshot_20200330-222245](https://user-images.githubusercontent.com/19254254/77958229-01156000-72d5-11ea-972e-b22d50b3ed68.jpg)

**Comment by SnakeDoc83** [comment]
From discord's #faq

> 2020-03-25
> Mangakakalot may be creating new entries for manga again on their site, so your old entries are obselete and can't access the new content. 
> 
> To resolve this, migrate the manga to the Mangakakalot extension from the Mangakakalot extension, manually, as batch/auto migration doesn't support it, though you can begin a auto migration and manually go down the list. 
> Or you can migrate to a different extension and stay there or back to Mangakakalot.

**Comment by panslothda** [comment]
Hmm i see thats good to know.

But would there bo no option to simply make the "dead" entries work again? As users with larger libraries might not realise this is happening when its only for lets sag 50 or 100 of their multiple hundred subscribed series.


And the entry is at least in some capacity still linked so it should be possible to get the new data no? Since if i click on webview it redirects me to the correct web page

**Comment by happywillow0** [comment]
Do you have any currently in your library as a duplicate (one working and one that doesn't)? 

Do you mind sharing a copy of your backup? We can see what the difference is in the URLs. (although you do say it redirects you somehow)

**Comment by panslothda** [comment]
Unfortunatly i migrated them all away like the dunce I am....

But i do have automatic backup enabled. Here are the last 2 backups
[Archive.zip](https://github.com/inorichi/tachiyomi-extensions/files/4409122/Archive.zip)
The mangas named against the gods and 80,000 gold for sure are "dead" versions in those saves.

**Comment by happywillow0** [comment]
Thanks for the upload. Just FYI, I didn't find anything out of the ordinary when matching it up against the website so I'm still not sure what happened with the extension and website.

**Comment by SnakeDoc83** [comment]
@arkon The site created new entries for manga they already had and stopped updating the old entries.  If the old entry doesn't forward I don't see what we could do.

**Comment by arkon** [comment]
Yup, guidance is to just migrate to the new entry.
