### ISSUE TITLE
[Bug] Mangakakalot : Chapter does not load, 3 kind of errors

### ISSUE THREAD

**Issue by nanamiku739** [inorichi/tachiyomi-extensions#2553]
### Device information
* Tachiyomi extension version: Mangabox 1.2.16
* Tachiyomi version: 0.9.82
* Android version: 10

## Steps to reproduce
1. Open title in Mangakakalot source
2. Tap on the newest chapter

### Expected behavior
The chapter should open like normal

### Actual behavior
The chapter does not load and it appears at random (i.e random title). I found 3 kinds of error:
![image](https://user-images.githubusercontent.com/62822330/77985051-8a607d00-733d-11ea-970a-561a64f427da.png)
Page does not load, only retry button appears or page load very slowly

![image](https://user-images.githubusercontent.com/62822330/77985072-9cdab680-733d-11ea-8cb7-f0f9fab22e5f.png)
Java error, tried force close the app but still the same

![image](https://user-images.githubusercontent.com/62822330/77985096-ad8b2c80-733d-11ea-8add-22840dc65aab.png)
Page list is empty

### Other details
When I tried to open in web view, I can open the chapter or the newest chapter are there, but the chapter are not in the app.

**Comment by SnakeDoc83** [comment]
For me, the first one has broken images on their website and the other two load fine.  Might be a server-side issue.

**Comment by happywillow0** [comment]
For the second two examples, I see you have already read chapters. Are these manga accessed from the catalog screen (Latest, Browse, Search) or from your library screen? 

From discord's #faq

> 2020-03-25
> Mangakakalot may be creating new entries for manga again on their site, so your old entries are obselete and can't access the new content.
> 
> To resolve this, migrate the manga to the Mangakakalot extension from the Mangakakalot extension, manually, as batch/auto migration doesn't support it, though you can begin a auto migration and manually go down the list.
> Or you can migrate to a different extension and stay there or back to Mangakakalot.

**Comment by SnakeDoc83** [comment]
@arkon Of the three examples given, #1 is due to broken images server-side and the other 2 are working now.  I think the issue was either the duplicate entries thing they've been doing or something else that was temporary.
