### ISSUE TITLE
[Bug] Webtoons : java.io.ioexception: mark invalid upon opening a chapter

### ISSUE THREAD

**Issue by loocool2** [inorichi/tachiyomi-extensions#2554]
### Device information
* Tachiyomi extension version: 1.2.15
* Tachiyomi version: dev r1955
* Android version: 9

## Steps to reproduce
1. Open Safely Endangered or Adventures of God
2. Encounter error

### Expected behavior
The chapter shouldn't throw and should proceed normally

### Actual behavior
An  java.io.ioexception: mark invalid error is thrown instead

### Other details
Adventures of God and Safely Endangered are the known affected webtoons at this time, while Bluechair and Boyfriend of the Dead load fine. 

For me, it doesn't load in webview, for the user who reported this, the chapters loaded fine in webview, and another user could load it fine in both inapp and webview,

**Comment by SnakeDoc83** [comment]
So, kind of weird, but I think this may be an issue with dev.  Trying to read Safely Endangered on my tablet using r1949 and on my virtual device using r1955 causes the error but not on my virtual device using stable or j2k .9.81.

**Comment by arkon** [comment]
I suspect this is due to a JSoup update in dev.

**Comment by arkon** [comment]
Should be fixed by https://github.com/inorichi/tachiyomi/commit/89df50da4e84ef1571021c1dc9f3c3ccb5c708b1
