### ISSUE TITLE
[Bug] Madara - 1st Kiss : Thumbnails not showing when content is added to "My Library"

### ISSUE THREAD

**Issue by HunterCha** [inorichi/tachiyomi-extensions#2555]
### Device information
* Tachiyomi extension version: Madara (Multiple sources) 1.2.65
* Tachiyomi version: 0.8.5
* Android version: 10

## Steps to reproduce
1. Clear Cache
2. Clear Cookies
3. Force Close Tachiyomi and relaunch.
4. Tried opening in webview, its working fine. I just cant see thumbnails when its already added to My Library.

### Expected behavior
This should shoe thumbnails.

### Actual behavior
When searching it will still show the thumbnail. But once youve added it to My Library its just showing black background. And it will not show thumbnails anymore in search tab as well. 

### Other details
![IMG_20200331_134948](https://user-images.githubusercontent.com/62924394/77991466-85f48e00-7356-11ea-8af8-ac5ec6b745ba.jpg)

**Comment by HunterCha** [comment]
Those other manhwas you can see that are working fine are from MangaDex. MangaDex doesnt have this contents im reading thats why im using 1stKiss as an alternative. (Most sources doesnt have it)

**Comment by happywillow0** [comment]
A recent fix was put in to fix 1st Kiss Thumbnails (#2538) and you are on the current version (1.2.65) 

Were these manga added to your library before or after v65 update? 
If the manga were added before you updated, they may have saved with an incorrect thumbnail in the database. 

You may have to reset the specific manga by bookmarking them (remove them from your library), clearing the database in advanced settings, and then add them back.

**Comment by HunterCha** [comment]
> A recent fix was put in to fix 1st Kiss Thumbnails (#2538) and you are on the current version (1.2.65)
> 
> Were these manga added to your library before or after v65 update?
> If the manga were added before you updated, they may have saved with an incorrect thumbnail in the database.
> 
> You may have to reset the specific manga by bookmarking them (remove them from your library), clearing the database in advanced settings, and then add them back.

Hello. It works like a charm. Yeah those contents are already their before I updated it to the latest version earlier. Been trying some basic troubleshooting. Its now working!! Thanks everyone!
