### ISSUE TITLE
[Bug] Search in Catalogues : the app crashes itself during the loading when I search or open a Manga from my Catalogues. The app stays open in the background. 

### ISSUE THREAD

**Issue by K4m3lb** [inorichi/tachiyomi-extensions#2556]
### Device information
* Tachiyomi extension version: ?
* Tachiyomi version: 0.8.5
* Android version: 10

## Steps to reproduce
1. Go to the catalogues 
2. Search a Manga in the bar

### Expected behavior
The Manga in my Catalogues should appear but during the loading, the app crashes and stay open in the background. 
Sometimes I can open a Manga from the results of my search only for the app to crashes itself again in the page.

**Comment by CarlosEsco** [comment]
Go to your extensions page. And upload all your extensions then try again

**Comment by arkon** [comment]
Please provide logs.

https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android

**Comment by arkon** [comment]
I assume this was fixed after reverting to an older Gson method.
