### ISSUE TITLE
[Bug] Hentainexus won't load any images or pages

### ISSUE THREAD

**Issue by alwayswannaflyhi** [inorichi/tachiyomi-extensions#2557]
Hentainexus extension
* Tachiyomi version: 8.5
* Android version: ?

Hnexus looks okay when i opened it. Updating new doujins, and their thumbnails. But when i read it theres no images or pages shown and only reload button is there. 

I tried to uninstall the extension and reinstalling but still not working  :(

![aa](https://user-images.githubusercontent.com/62924977/77990974-8437b580-72d7-11ea-94db-ea69be6d23a8.png)
)

**Comment by Argchow** [comment]
Same issue with this extension. It works in webview but reader doesn't function. Also downloads come up with this error:
![20200331_144154](https://user-images.githubusercontent.com/46412511/78077739-c73c6c00-735d-11ea-831b-da8b92b1168a.jpg)
