### ISSUE TITLE
[Bug] Manganelo : cant decode images of certain manga 

### ISSUE THREAD

**Issue by baraa272** [inorichi/tachiyomi-extensions#2562]
### Device information
* Tachiyomi extension version: mangabox 1.2.16
* Tachiyomi version: r1936
* Android version: 7.0

## Steps to reproduce
1. Open tachiyomi , open for example "namae no nai kaibutsu" 
2. Error image can't be decoded 
Well I tried opening the image in web view but it direct me to a broken image hosted on mkklcdnv8 
So I opened manganelo website and tried to read the manga there and the images loaded successfully 
![Screenshot_20200401-024551](https://user-images.githubusercontent.com/32843097/78085533-c41b9d00-73aa-11ea-9cfa-4d3d5fb284f0.png)

**Comment by arkon** [comment]
You could at least provide what the "certain manga" are.

**Comment by baraa272** [comment]
> You could at least provide what the "certain manga" are.

Really sorry I edited my comment

**Comment by SnakeDoc83** [comment]
Seems like an issue with them, not Tachi; the first image is broken on their website but the rest load fine.  If you check the website again you should be able to see that 18 of 19 images load, not all of them.
