### ISSUE TITLE
Teamx cloudflare

### ISSUE THREAD

**Issue by mged** [inorichi/tachiyomi-extensions#2565]
failed to bypass cloudflare fix it please

**Comment by Soitora** [comment]
failed to bother caring about spam issues fix it please

**Comment by mged** [comment]
what do u mean?

**Comment by Soitora** [comment]
You think this issue is different from all the others you've done with the exact same content?

Fix it yourself, the devs has already discussed this with you in previous issues. I'm not gonna speak for them but I'd be pretty annoyed dealing with these repetitive actions.

**Comment by mged** [comment]
I do apologize very much, i already fixed many issues in the extensions. but there is some of them i can not fix so i simple want to notice the devs, i absloutly do not force anyone do fix them.

i hope you can forgive me if i did annoy you. i do apologize again
