### ISSUE TITLE
[Source Request] TruyenTranhLH and Otaku Sanctuary

### ISSUE THREAD

**Issue by gonz1324** [inorichi/tachiyomi-extensions#2566]
### Source Website
TruyenTranhLH can be found at <https://truyentranhlh.net/>.
Otaku Sanctuary can be found at <https://otakusan.net/Manga>.

### Other Details
These are two big manga websites in Vietnam.
TruyenTranhLh has many romcom and isekai, while Otaku Sanctuary is multi-genre and multi-lingual.

**Comment by MerradOklom** [comment]
Otakusan has been already requested #1292, and TruyenTranhLH is in the FMReader extension.
