### ISSUE TITLE
[Bug] Search in Catalogues BlogTruyen

### ISSUE THREAD

**Issue by gonz1324** [inorichi/tachiyomi-extensions#2567]
### Device information
* Tachiyomi extension version: 1.2.7
* Tachiyomi version: 0.8.5-1928
* Android version: 7.0

## Steps to reproduce
1. Go to the catalogues
2. Search a Manga in the bar

### Expected behavior
Search for the manga with the information entered

### Actual behavior
No return search results and show error messages "Not Used" instead

**Comment by happywillow0** [comment]
Opps, that was an oversight on [line 121](https://github.com/inorichi/tachiyomi-extensions/blob/b0255f932555d1e86539da1a31a42d0f0c43c76f/src/vi/blogtruyen/src/eu/kanade/tachiyomi/extension/vi/blogtruyen/BlogTruyen.kt#L122)

**Comment by gonz1324** [comment]
> Opps, that was an oversight on [line 121](https://github.com/inorichi/tachiyomi-extensions/blob/b0255f932555d1e86539da1a31a42d0f0c43c76f/src/vi/blogtruyen/src/eu/kanade/tachiyomi/extension/vi/blogtruyen/BlogTruyen.kt#L122) when I did the update for thumbnails

Oh, please fix it >W< Thank you for your work hard UwU
