### ISSUE TITLE
[Source Request] Manhuaplus

### ISSUE THREAD

**Issue by ChrisN6** [inorichi/tachiyomi-extensions#2570]
### Source Website
Website can be found at <https://manhuaplus.com/>.

**Comment by banra123** [comment]
Yes need this,they translate faster, whenever there is chinese release they just translate it to to english and upload it on their wensite

**Comment by ruuno123** [comment]
https://manhuaplus.com/ please for this

**Comment by CarlosEsco** [comment]
@ruuno123  wpcomicfactory has it.
