### ISSUE TITLE
[Bug] Mangahere pagelist empty

### ISSUE THREAD

**Issue by evo85210** [inorichi/tachiyomi-extensions#2573]
### Device information
* Tachiyomi extension version: 1.2.12
* Tachiyomi version: r1964
* Android version: 10

## Steps to reproduce
1. Open any manga chapter from mangahere

### Expected behavior
Opens chapter normally. 

### Actual behavior
Receives pagelist is empty.

### Other details
I'm able to view the chapter in web view tho, I've tried clearing all the cache, no difference.

**Comment by SilverBeamx** [comment]
If anyone's interested/able to work, i found out what is wrong and how to fix it. I wrote it in tachi's discord channel dev-app-ext. I don't have the development environment set up, otherwise i'd open a PR myself.

**Comment by richylyq** [comment]
thanks all for the fixes!
