### ISSUE TITLE
[Bug] Extension page needs very long time to show extensions that not installed

### ISSUE THREAD

**Issue by star2056** [inorichi/tachiyomi-extensions#2576]
* Tachiyomi version: 0.8.5
* Android version: 6.0

## Steps to reproduce
1.I opened Extension page
2. slide down screen to show all extensions (see if there any new extensions I wish to install)

### Expected behavior
Those non-installed extensions should be show quickly.

### Actual behavior
At first it only showed extensions I've already installed.
Until I wait long time those non-installed extensions finally appears.

### Other details
I have no ad-block apps in my phone.
I live in China Mainland. (My guess is maybe the GFW block the extension list/update server?)

**Comment by arkon** [comment]
Is GitHub slow in general for you? That's where the list comes from.

**Comment by CarlosEsco** [comment]
GitHub was having issues earlier so that might have been issue

**Comment by star2056** [comment]
Looks like it's all GFW's fault, I use VPN and refresh Extension page again, everything is OK.
THX arkon for telling me the update server address.
