### ISSUE TITLE
[Feature Request] Manga Plus Extension doesn't  have an option for high resolution 

### ISSUE THREAD

**Issue by ZoroLegend** [inorichi/tachiyomi-extensions#2578]
### Why/User Benefit/User Problem
Currently the resolution of the Manga Plus manga is low and unclear when zoomed in.  The Manga Plus app has an option for high resolution.

### What/Requirements
With an option for high resolution the extension, we would be able to see the latest manga clearly without having to use a browser or another app.

**Comment by alessandrojean** [comment]
The extension do exactly the same call that the app and website does to their API, using the high resolution parameter in the url.

https://github.com/inorichi/tachiyomi-extensions/blob/master/src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlus.kt#L189
