### ISSUE TITLE
[Bug] MangaLib : Chapters not loading

### ISSUE THREAD

**Issue by Hell13Cat** [inorichi/tachiyomi-extensions#2598]
### Device information
* Tachiyomi extension version: 1.2.14
* Tachiyomi version: r1764
* Android version: 6.0

## Steps to reproduce
1. Open any manga
2. Start reading

### Expected behavior
Page opening

### Actual behavior
![Screenshot_2020-04-05_171911](https://user-images.githubusercontent.com/46496367/78501376-33efa600-7764-11ea-8e33-fd4f287b6414.png)

### Other details
No

**Comment by arkon** [comment]
Should be fixed via #2594
