### ISSUE TITLE
[Bug] Newtoki not working 

### ISSUE THREAD

**Issue by Reraru** [inorichi/tachiyomi-extensions#2599]
Newtoki hasn't been working. I tried to override the url but it won't change even when I closed the app several times.

And I think they have added a captcha to it now.

**Comment by SnakeDoc83** [comment]
@arkon This is covered by https://github.com/inorichi/tachiyomi/commit/c2330fe3af3cd48f771f353c3bc8e2c615a13354, right?

**Comment by arkon** [comment]
Yup, should be.

**Comment by dingdonng22** [comment]
Today i Also tried many times to enter but couldn't successed!please solve the prob
