### ISSUE TITLE
[Feature Request] Mangalib (RU): Rename server

### ISSUE THREAD

**Issue by oplexz** [inorichi/tachiyomi-extensions#2601]
I can't make a pull request from my phone, so I decided to go with feature request instead.

The newly added "compressed" server should be named "Третий (экономия трафика)" instead of "Сжатия (эконом трафика)", since it's more logical (**first**, **second**, _third_) and grammatically correct.

**Comment by SnakeDoc83** [comment]
Closed by https://github.com/inorichi/tachiyomi-extensions/pull/4259
