### ISSUE TITLE
[Bug] FMReader : Manhwa18.net is down and changed source to Manhwa18.com

### ISSUE THREAD

**Issue by kingxjullien14** [inorichi/tachiyomi-extensions#2604]
Samsung Galaxy S9+
* Tachiyomi extension version: 1.2.7
* Tachiyomi version: 0.8.4
* Android version: 10
Manhwa18.net changed to Manhwa18.com, so the extension is unable to load the contents from Manhwa18.

**Comment by SnakeDoc83** [comment]
Manhwa18.com and manhwa18.net have existed side-by-side for months, they're even both in FMReader.  The .net version is down, either temporarily or permanently, but I'm not sure what you're expecting when as I say, the other version is already there.

**Comment by kingxjullien14** [comment]
Hahhaha... i just came over it actually... lol...
