### ISSUE TITLE
[Bug] BH3: the extension not working

### ISSUE THREAD

**Issue by MisakaSakura** [inorichi/tachiyomi-extensions#2611]
### Device information
* Tachiyomi extension version: 1.2.1
* Tachiyomi version: stable v0.8.5&lastest beta version.
* Android version: 10

## Steps to reproduce
1. First Step,open the main page of BH3 extension
2. Second Step,enter any chapter of the comic

### Expected behavior
This should have happened was the normal display of comic information after entering the comic chapter.

### Actual behavior
This happens instead the stable ver. show a "unexpected url"messege and that beta ver. show a "Invalid url"messege.This makes it impossible for the extension to work properly.

### Other details
beta version actual display information is 
tachiyomi: Invalid URL port:"enterBookApp"('Chapter Name','"

Stable v0.85 actual display information is Tachiyome：unexpected url:https//comic.bh3.comjavascript:enterBookApp('Chapter Name','/book/1001')/get_chapter

remark:I've also tested other extension with the same version (1.2.1 and above), and they all work.

**Comment by happywillow0** [comment]
Found it. They changed the url link to prevent people from right clicking or copying the link or something similar.

`<a href="javascript:enterBookApp('樱花追忆篇','/book/1002')">`

**Comment by MisakaSakura** [comment]
@happywillow0 Are you saying that changes in the information on the site itself caused the extension to fail?In fact, I tried to use the stable v0.8.4 version and still couldn't read the comics properly.On the other hand, I asked other people if he could still read the comics, but he said that only a few chapters couldn't be read properly, and the rest was fine.
