### ISSUE TITLE
[Bug] Kissmanga : page list is empty and extension not working 

### ISSUE THREAD

**Issue by Samk19** [inorichi/tachiyomi-extensions#2612]
### Device information
* Tachiyomi extension version: 1.2.13
* Tachiyomi version: r1974 (bff927c6)
* Android version: 9.0

## Steps to reproduce
Open any chapter of any title from kissmanga 
Shows error “page list is empty”

Also when opening source tab > kissmanga> ‘no result found’

When opening thru webview displays a black background with white top line

### Actual behaviour
1.open chapter results  in ‘page list is empty’.
2.opening form sources results in ‘no result found’ error.
3.In webview displays a black background with white top line

### Other details
Screenshots added
![D6DB7D81-E387-49AD-9621-58D33CAA543C](https://user-images.githubusercontent.com/36104528/78725502-54c71f80-794d-11ea-8dd6-3217d02ecd6e.jpeg)
![C655367C-2F71-4D53-B111-4E2C7A04BFE0](https://user-images.githubusercontent.com/36104528/78725505-585aa680-794d-11ea-8562-582b176d73bd.jpeg)
![278F208E-7ED6-46ED-80AD-0A91DE988B23](https://user-images.githubusercontent.com/36104528/78725508-58f33d00-794d-11ea-9e90-31267bc71549.jpeg)

**Comment by arkon** [comment]
See #2496
