### ISSUE TITLE
[Bug] madara : 1kissmanga download not working

### ISSUE THREAD

**Issue by samanta-widjaja** [inorichi/tachiyomi-extensions#2620]
### Device information
* Tachiyomi extension version: madara 1.2.66
* Tachiyomi version: 0.8.5
* Android version: 7.1.1 

## Steps to reproduce
1. Dowload chapter such reborn 80000 year chapter 40 
2. Open it via app 

Not download and don't show image but retry. I tried using opera browser and it's fine

Help. Thanks

**Comment by E3FxGaming** [comment]
I'm having trouble recreating your problem. (it works fine for me)

First of all could you confirm that downloading chapters works as expected with other extensions and sources? Just want to make sure that your Tachiyomi app in general has the permission to read and write media files on your phone.

If other extensions work fine:

Would you happen to have an app installed that allows you to browse the files of your Android phone?

When you open the Tachiyomi settings > Downloads > directly at the top it should say "Downloads directory" and then below that some path (e.g. /storage/emulated/0/Tachiyomi/downloads).

Could you use another app to check the content of this directory? Downloading your 80000 year chapter 40 from 1st Kiss should create the following file structure below "downloads": 1st Kiss (EN) > Reborn 80000 years > Chapter 40. This directory should contain a .nomedia binary file as we

Similarly downloading chapters from other extensions + sources should create file structures in your downloads folder too.

**Comment by samanta-widjaja** [comment]
Yes. Suddenly it's downloading fine now. Though there's some manga name that's suddenly dissapear. Perhaps they have maintenance. Thanks
