### ISSUE TITLE
[Bug] Mangadex : Unwanted language description still shows up

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi-extensions#2630]
App version: Dev r1986
Ext version: 1.2.88

Previously reported in issue #2540 , description still showed up in Russian language for the manga _Ijiranaide, Nagatoro-san._

![screenshot_20200409-214505_tac](https://user-images.githubusercontent.com/34897862/78955361-1183c280-7aad-11ea-8eaa-d3ba59da86ef.jpg)

**Comment by arkon** [comment]
Just going to close this since it's already a best effort attempt against MangaDex's very non-standardized descriptions.
