### ISSUE TITLE
Most of soruces aren't working.

### ISSUE THREAD

**Issue by efmavmim** [inorichi/tachiyomi-extensions#264]
Mangafox, Mangahere, Kissmanga, Mangago etc. aren't working.

**Comment by efmavmim** [comment]
Kissmanga is working now. But others not. Actually I'm sure you know this and trying doing something about this so good work to you. (And good luck.)

**Comment by CarlosEsco** [comment]
All sources are working, and you have provided no detail.  Please provide more information  but my guess is your either being blocked because of your location or something along those lines 
 https://github.com/inorichi/tachiyomi/wiki/Source-problems
