### ISSUE TITLE
[Bug] MangaDex (EN) : "No chapters found" for certain manga

### ISSUE THREAD

**Issue by pranau97** [inorichi/tachiyomi-extensions#2645]
### Device information
* Tachiyomi extension version: 1.2.88
* Tachiyomi version: 0.8.5
* Android version: 10, Nokia 7 plus

### Steps to reproduce
1. Open a manga (I've tried with Dr. Stone and Dr. Stone Reboot: Byakuya)
2. The app attempts to load the chapter list before displaying the error message - "No chapters found"

### More details
Strangely, this error seems to be occurring only with these 2 mangas. Every other manga I tried loading on MangaDex seems to load the chapter list correctly. On opening the manga page in a webview, I'm able to see that there are chapters in English for it despite which I'm getting the "No chapters found" error. Any help in resolving this appreciated!

### Screenshots
![error](https://user-images.githubusercontent.com/12474765/79047962-72d79d00-7c37-11ea-9e27-e2837fddb190.jpg)
![normal](https://user-images.githubusercontent.com/12474765/79047970-7703ba80-7c37-11ea-941b-aded25a885ee.jpg)
![webview](https://user-images.githubusercontent.com/12474765/79047974-79feab00-7c37-11ea-8df4-261d793a6be8.jpg)

**Comment by arkon** [comment]
MangaPlus chapters are intentionally not shown because they just redirect to the official website.

Maybe we could throw a better message.

**Comment by pranau97** [comment]
The workaround for this would be to install the MangaPlus extension, right?

**Comment by arkon** [comment]
Yes, although there's the caveat the the app doesn't automatically handle MangaDex entries for you. There's also the limitation of what MangaPlus shows (usually the first 3 and latest 3 chapters).

**Comment by pranau97** [comment]
Ah, gotcha. I'm leaving this issue open in case you want to expand on the error message for Manga Plus manga. Let me know otherwise.
Thanks for the help!
