### ISSUE TITLE
[English] Tapastic Premium episodes that require login

### ISSUE THREAD

**Issue by Xeiniac** [inorichi/tachiyomi-extensions#265]
Tachiyomi version: V7.0.0
Whenever I try to download something after downloading few chapters I get a 'Page list is empty' error and I can't read the chapters online that got that error.
So far I've gotten it for Adonis and They say I was Born A King's Daughter.

**Comment by null-dev** [comment]
Those episodes are not free and must be unlocked with coins. Maybe we have to write a login mechanism for this source?

**Comment by null-dev** [comment]
Those episodes are not free and must be unlocked with coins. Maybe we have to write a login mechanism for this source?

**Comment by happywillow0** [comment]
Due to our ability to use webview to login, I think we can close this one.
