### ISSUE TITLE
[Bug] Madara "Hiperdex" : No Chapter Found

### ISSUE THREAD

**Issue by N9402** [inorichi/tachiyomi-extensions#2653]
### Device information
* Tachiyomi extension version: madara 1.2.68
* Tachiyomi version: v8.4.5-EH
* Android version: 6.0.1 Redmi 3x

## Steps to reproduce
1.  Open VPN (due to my country block the site)
2.  Open TachiyomiEH and open any manga on hiperdex and I get this "No chapter found".

### Other details
Past 2 days and today, hiperdex doesn't have any chapter was found but when I tried open directly to the website I can see the chapter.

**Comment by samanta-widjaja** [comment]
The same happen with 1stkissmanga on the same extension
