### ISSUE TITLE
[site protected ] Source Name : mangaswat

### ISSUE THREAD

**Issue by cool0987** [inorichi/tachiyomi-extensions#2654]
can you please fix this eror it's says that site is protected open web view is there no solution ?😭😭

**Comment by arkon** [comment]
Have you tried opening it in the webview...?

**Comment by cool0987** [comment]
yes i opened through google chrome it's working but through tochiyomi doesn't work , i will really appreciate it if u can find a solution

**Comment by arkon** [comment]
Webview isn't the same thing as an external browser like Chrome. Open it from the catalogue's menu.

**Comment by cool0987** [comment]
i was using old version of tochiyomi that's why i couldn't find webview thank you guys for ur work
