### ISSUE TITLE
[Bug] IsekaiScan.com : No Chapter Found

### ISSUE THREAD

**Issue by rexthunderbolt** [inorichi/tachiyomi-extensions#2657]
### Device information
* Tachiyomi extension version:1.2.68
* Tachiyomi version: r2028
* Android version: 9

## Steps to reproduce
1. Open any manga from IsekaiScan.com sources
2. Pull to refresh manga chapter

### Expected behavior
No/New Chapter appear

### Actual behavior
No Chapter Found

**Comment by SnakeDoc83** [comment]
@arkon This was also fixed by #2655
