### ISSUE TITLE
[Bug] Toonily: unparseable date: "2 days ago" 

### ISSUE THREAD

**Issue by Infiziert90** [inorichi/tachiyomi-extensions#2659]
### Device information
* Tachiyomi extension version: 1.2.3
* Tachiyomi version: 0.8.5
* Android version: 10

## Steps to reproduce
1. Use the search and open "My wife is a demon queen" from toonily
2. Go to the chapters page

### Expected behavior
List of all Chapter 

### Actual behavior
Error: unparseable date "2 days ago" 

### Other details
Other Mangas from Toonily work.

**Comment by SnakeDoc83** [comment]
The Toonily extension is no longer supported.  You can find a working version in Madara instead.
