### ISSUE TITLE
[Bug] Mangakawaii : cloudflare error 1020 / error 403

### ISSUE THREAD

**Issue by aerodomigue** [inorichi/tachiyomi-extensions#2665]
### Device information
* Tachiyomi extension version: 1.2.4
* Tachiyomi version: 0.8.4 -> 0.8.5
* Android version: 9.0

## Steps to reproduce
1. Read manga on mangakawaii web view: error 1020
2. Read manga in tachiyomi app : error 403

### Other details
I tested with vpn, clean cache and cookies, restart phone.

I can go to the website with internal
Navigator.

Error 1020 
I use vpn
![Screenshot_20200413-224226_Tachiyomi](https://user-images.githubusercontent.com/43935382/79159864-25933100-7dd9-11ea-986a-67cdea808a62.jpg)

Error 403
![Screenshot_20200413-225217_Tachiyomi](https://user-images.githubusercontent.com/43935382/79160068-7c006f80-7dd9-11ea-88b9-dd721cfb84ff.jpg)

**Comment by arkon** [comment]
Try updating the app first.

**Comment by aerodomigue** [comment]
Same error in 0.8.5
