### ISSUE TITLE
[Bug] MangaFox : Can't browse / search MangaFox

### ISSUE THREAD

**Issue by reaperux86** [inorichi/tachiyomi-extensions#2669]
### Device information
* Tachiyomi extension version: 1.2.3
* Tachiyomi version: 0.8.5
* Android version: 9

## Steps to reproduce
1. Go to catalogues
2. Tap 'Browse' next to MangaFox / Search.

### Expected behavior
Results from MangaFox show up.

### Actual behavior
It loads for a bit before giving the message: "No results found".

### Other details
Opening MangaFox in web view and searching there works. But since the search/browse don't work in-app I can't add any manga from that source.
Also - adding any filters after hitting 'Browse' will show "HTTP error 400" instead of "No results found".

**Comment by SnakeDoc83** [comment]
MangaFox was removed as a source last year.  Uninstall it and use a different source.

**Comment by reaperux86** [comment]
That kinda sucks. Thanks for letting me know!
