### ISSUE TITLE
[Bug] Japscan : Pages don't load

### ISSUE THREAD

**Issue by amar33** [inorichi/tachiyomi-extensions#2670]
### Device information
* Tachiyomi extension version: Japscan 1.2.20
* Tachiyomi version: 0.8.5
* Android version: 9.0

### Actual behavior
I can't read any manga of japscan. The pages don't load. 

### Other details
![Screenshot_2020-04-14-14-15-18-952_eu kanade tachiyomi](https://user-images.githubusercontent.com/56921708/79223851-67b08700-7e5a-11ea-8362-16d4eb3b798a.jpg)

**Comment by arkon** [comment]
Duplicate of #2535

**Comment by amar33** [comment]
It's not only on webtoon . And everything worked Yesterday.

**Comment by arkon** [comment]
Add info the existing issues then.
