### ISSUE TITLE
[Bug] Mangahasu: HTTP error 400

### ISSUE THREAD

**Issue by mawee16** [inorichi/tachiyomi-extensions#2684]
### Device information
* Tachiyomi extension version: ?
* Tachiyomi version: ?
* Android version: ?

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
When opening the source catalog the manga/manhwa will be displayed.

### Actual behavior
It kept on showing Http error 400

**Comment by SnakeDoc83** [comment]
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/2521 and https://github.com/inorichi/tachiyomi-extensions/issues/2193
