### ISSUE TITLE
Mangahere: Non-existent last page

### ISSUE THREAD

**Issue by adklco** [inorichi/tachiyomi-extensions#2689]
Downloads fail because tachiyomi attempts to download a non-existent last page. Tried with multiple titles and they all had the same issue (e.g., Usogui).

**Additional Notes:**
- The same chapters on mangahere.cc have one fewer page than what's displayed in tachiyomi
- The chapter can be read without downloading it, but the "last page" (the fake one) fails to load

tachiyomi version: **0.8.5**
mangahere version: **1.2.13**

**Comment by SnakeDoc83** [comment]
This was previously an issue with their webtoon reader, looks like it may have become one with their regular reader now.  Page count seems fine for Usogui though, but the last image is broken.

**Comment by adklco** [comment]
Oh yeah you're right. I'm now seeing broken last pages for other titles on mangahere.cc, too.

This wasn't the case a few hours ago, but it seems like it may be an issue on mangahere's side and not tachiyomi's.
