### ISSUE TITLE
[Bug] WP-Comics : Manhua Plus Yuan Zun

### ISSUE THREAD

**Issue by Riztard** [inorichi/tachiyomi-extensions#2693]
### Device information
* Tachiyomi extension version: 1.2.3
* Tachiyomi version: r2034
* Android version: Pie

## Steps to reproduce
1. go to Manhua plus
2. Search Yuan Zun
3. choose chapter

### Expected behavior
open chapter

### Actual behavior
Page list is empty

### Other details
i tried another title but seems normal

**Comment by SnakeDoc83** [comment]
This wordpress theme is so janky.
