### ISSUE TITLE
HTTP 422 Error Kitsu Tracking

### ISSUE THREAD

**Issue by patboy2008** [inorichi/tachiyomi-extensions#27]
Version: 0.5.1
Devices: NVIDIA Shield K1 (7.0, stock, unrooted), Nexus 6P (7.1.2, stock, unrooted)

When trying to update chapter read manually, there is a HTTP 422 error that pops up briefly and it doesn't update. With auto sync after reading chapters on, it still doesn't update and no error comes up. Also can't change status or rating either.

If I update the chapter on the Kitsu website and refresh, it shows the updated information. But only when I try to update to Kitsu do I get an error.

**Comment by j2ghz** [comment]
This issue seems to be related to the app rather than a specific source, so it should be in the main repository.
