### ISSUE TITLE
[Source Request] Scantrad-Union (FR)

### ISSUE THREAD

**Issue by o01210o** [inorichi/tachiyomi-extensions#2701]
### Source Website
Website can be found at https://scantrad-union.com/projets/.

### Other Details
- scanlation group, not a "aggregator"
- to have a alternative to Japscan (because of recent instability)

![GIF2](https://user-images.githubusercontent.com/45663409/79669507-fc342580-8189-11ea-8c0f-beab57c5a160.gif)

**Comment by SnakeDoc83** [comment]
Closed by https://github.com/inorichi/tachiyomi-extensions/pull/3945
