### ISSUE TITLE
[Source Request] KR ManyToon.Club

### ISSUE THREAD

**Issue by Chaotiic28** [inorichi/tachiyomi-extensions#2705]
### Source Website
Website can be found at <https://manytoon.club>.

### Other Details
KR. Requesting for this extension as it has many Raws available.

Thanks!

**Comment by desmondteoh11** [comment]
May I know under which extension added manytoon.club?

**Comment by SnakeDoc83** [comment]
Madara

**Comment by desmondteoh11** [comment]
The one in madara is manytoon.com not manytoon.club..

**Comment by SnakeDoc83** [comment]
They're both in Madara. For manytoon.club look under the Korean language sources.

**Comment by desmondteoh11** [comment]
Got it man. Thanks!!
