### ISSUE TITLE
[Traditional Chinese] tw.manhuagui.com

### ISSUE THREAD

**Issue by windflare** [inorichi/tachiyomi-extensions#271]
Like to request http://tw.manhuagui.com/ as a source for Traditional Chinese Manga - currently most translation groups are using traditional Chinese, for readers in Hong Kong, Taiwan, China, and worldwide, as many do not read simplified Chinese. Current Chinese source existing on extensions, dmzj, is only simplified Chinese.

Thanks!

**Comment by windncloud** [comment]
Not to mention dmzj is not working anymore, at least for me (error 403) even with the new update

**Comment by yshui** [comment]
@windncloud Works for me fine

**Comment by arkon** [comment]
@feilongfl Not sure if you'd want to update it to also support zh-TW?

**Comment by feilongfl** [comment]
I've check https://tw.manhuagui.com,and I found that this website only change the language at title and some manga infos,they use same manga picture.
so if you visit tw.manhuagui.com, you will see same manga in Simplified Chinese.

![image](https://user-images.githubusercontent.com/10269596/59154273-295f7400-8aa1-11e9-951c-2c33e9814362.png)
