### ISSUE TITLE
[Bug] LectorManga/TuMangaOnline: HTTP Error 503 / pages not loading

### ISSUE THREAD

**Issue by dnmodder** [inorichi/tachiyomi-extensions#2714]
### Device information
* Tachiyomi extension version: 1.2.11
* Tachiyomi version: 0.8.5
* Android version: 6.0.1

## Steps to reproduce
1. Go to "Catalogue"
2. Explore in LectorManga

### Expected behavior
See a list of mangas

### Actual behavior
A message appears saying "HTTP Error 503"

### Other details
The same thing happens when trying to check for updates in already added manga, and it also happens with the TuMangaOnline extension.
![Screenshot_2020-04-19-19-07-40](https://user-images.githubusercontent.com/12377383/79702207-2d3b5580-8271-11ea-9463-d379abe66ced.png)

**Comment by MerradOklom** [comment]
Es un dolor de cabeza pero han aumentado la seguridad en la página web. 
LectorManga:
Presiona los tres puntos en la parte superior derecha de la pantalla que muestras en la captura de pantalla, una vez hecho eso elige Abrir en Web View (o vista web), probablemente te aparezca un mensaje de Cloudflare pidiendo que esperes 5 segundos. Una vez pasado el mensaje vuelve atrás y debería aparecerte el catálogo. Ahora, si al intentar leer un capítulo te aparece "HTTP error 403" es porque debes resolver un captcha, desde la info del manga presionas los tres puntos y nuevamente eliges Abrir en Web View, intenta abrir un capítulo desde allí y entonces debería salirte el captcha, una ves lo resuelvas ya deberías poder leer con normalidad.
TuMangaOnline:
Lo mismo que LectorManga, aunque esta extensión sí es posible que necesite ser reparada porque no cargan las imágenes ni aún resolviendo el captcha.

**Comment by dnmodder** [comment]
Lo he intentado pero no ha funcionado

**Comment by MerradOklom** [comment]
A mis amigos y a mí nos funciona bien luego de seguir los pasos que ya mencioné. Prueba yendo a Extensiones > LectorManga y cambia el 'Método de obtención de imágenes' a Paginado, luego ve a Configuraciones > Avanzado y limpia la caché de capítulos y la "redundancia de la base de datos", seguidamente vuelve a intentar leer un capítulo.
Como última alternativa usa otra extensión ya que el tema del captcha no puede ser resuelto automáticamente por la aplicación, imagino que lo único que se puede hacer es detectar cuándo aparece y anunciarle al usuario mediante un mensaje que debe resolverlo.

**Comment by dnmodder** [comment]
Yo creo que el problema en mi caso no es el captcha, sólo lo vi una sóla vez, ahora sólo me aparece el cloudflare, y el error 503 es justo de cloudflare, veo que al parecer otras extensiones tienen soporte para saltar el cloudflare pero estas dos no.

**Comment by MerradOklom** [comment]
En realidad la opción de Abrir en WebView fue añadida como una alternativa para poder pasar la pantalla intermitente de Cloudflare cuando el interceptor falla (también sirve para iniciar sesión en páginas que así lo requieran, resolver el ya mencionado captcha y otras cosas más que requieren interacción del usuario).

**Comment by edgarMejia** [comment]
> Yo creo que el problema en mi caso no es el captcha, sólo lo vi una sóla vez, ahora sólo me aparece el cloudflare, y el error 503 es justo de cloudflare, veo que al parecer otras extensiones tienen soporte para saltar el cloudflare pero estas dos no.

Solo tienes que abrirlo en webview y esperar a que cargue, es lo mismo que en MangaMX.
Sino esperas a que cargue obviamente no va a funcioanar.

**Comment by dnmodder** [comment]
> > Yo creo que el problema en mi caso no es el captcha, sólo lo vi una sóla vez, ahora sólo me aparece el cloudflare, y el error 503 es justo de cloudflare, veo que al parecer otras extensiones tienen soporte para saltar el cloudflare pero estas dos no.
> 
> Solo tienes que abrirlo en webview y esperar a que cargue, es lo mismo que en MangaMX.
> Sino esperas a que cargue obviamente no va a funcioanar.

Eso lo estoy haciendo desde el comienzo.

**Comment by dnmodder** [comment]
No se cual es el problema pero esta solución no me funciona, y se que debería funcionar porque se como funciona el cloudflare y he escrito bypass en Python pero acá nada, también he borrado cookies a ver y nada, de momento usaré otra extensión o usaré MiMangaNu

**Comment by edgarMejia** [comment]
También ya esta TuMangaOnline disponible nuevamente

**Comment by dnmodder** [comment]
Tenía WebView desactualizado, por eso no me funcionaba la solución que me plantearon, pero considero que esto sigue siendo un bug así que lo dejaré abierto.

**Comment by cvalenciaec** [comment]
Hay que llegar hasta la opcion de leer el manga en WebView, se va a abrir una pagina con dominio followmanga, luego de eso puedes ya leer el capitulo en la app normalmente.

**Comment by toshio-tempest** [comment]
Ya no funciona el método de abrir WebView
Osea si quita el error 405 pero no cargan las páginas, solo aparece "reintentar" en cada página
Alguien me puede ayudar?

**Comment by toshio-tempest** [comment]
> Hay que llegar hasta la opcion de leer el manga en WebView, se va a abrir una pagina con dominio followmanga, luego de eso puedes ya leer el capitulo en la app normalmente.

Ahora sale reintentar en cada página y no carga

**Comment by dnmodder** [comment]
Ese es un fallo nuevo, con LectorManga, TuMangaOnline sigue funcionando aunque me cargan muy lento las paginas, estoy usando NineMangaEs mientras en algunas series mientras.

**Comment by SnakeDoc83** [comment]
Extensions updated by https://github.com/inorichi/tachiyomi-extensions/pull/3779, this issue may no longer be relevant.

**Comment by JuanJuanes** [comment]
![Screenshot_20210211-204718](https://user-images.githubusercontent.com/78931713/107691548-dabda080-6cab-11eb-9423-1faafea48f4f.png)
Ayuda
