### ISSUE TITLE
request to add https://mangadex.org/

### ISSUE THREAD

**Issue by Pizz001** [inorichi/tachiyomi-extensions#272]
(CATALOGUE) SOURCE REQUESTS:

 I'd like to request adding https://mangadex.org/ to the app as it seems to be the replacement to bota.to 
as a lot of the old scan groups are releasing on this site now ie the ones without their own sites just like the way bato used to work 

it also lets you import you old bato info etc, i think thier is a second site that also trying to replace bato , but I haven't fully tested that as of yet
I've been testing this one for the last 2 weeks to see how it runs and also checking the release groups that are using it etc and there are lot's of the known old groups on it now ,
 so far I've noticed no problems, unless someone else has but if you have please leave a reply as well, as it's always best to get extra info 

Thanks

**Comment by CarlosEsco** [comment]
This already exists

**Comment by Pizz001** [comment]
sorry i miss have missed a update  and thanks :)

**Comment by wopian** [comment]
Its available as an extension within the app from `0.7.0` and above.
