### ISSUE TITLE
[Bug] Bato.to : filter not work

### ISSUE THREAD

**Issue by VeganCzech** [inorichi/tachiyomi-extensions#2730]
### Device information
* Tachiyomi extension version: Mangatensei (and others) Version 1.2.6
* Tachiyomi version: J2K stable build
* Android version: 10

Problem with filter manga as I trying filter by chapters (100-199, 50+,100+,200+, ..) 
Its work last time and now not. Can you fix it? ¨
Thank you :)

**Comment by SnakeDoc83** [comment]
Looks in working order to me.  I think the issue is a hiccup with the site or perhaps too many requests in a short period.  If it happens again, wait a minute and try again, it should work.
