### ISSUE TITLE
[Bug] Mangasy.com: load chapter problem

### ISSUE THREAD

**Issue by VeganCzech** [inorichi/tachiyomi-extensions#2731]
### Device information
* Tachiyomi extension version: MADARA (multiple sources)  version 1.2.72
* Tachiyomi version: J2K stable
* Android version: 10

I try loadind manga  "Into The Bones Of Warm Marriage", but furst 6 chapters have problem load. I se only "RETRY"... In mobile web browser or in computer I dont have problem loading Chapter 0,1,2 ... Problem is with other manga in this site... 
Can you fix this problem?
Thank you :)

**Comment by mekodke** [comment]
This problem is from mangasy itself as some chapters become invalid with time, so add a report to mangasy about this problem, not about tachiyomi or your phone  and you can watch "Into The Bones Of Warm Marriage" from another source like 1st kiss in the name of "Warm Wedding".and thank you
