### ISSUE TITLE
[Bug] Kiss manga :  Page list is Empty

### ISSUE THREAD

**Issue by Kush-Patel** [inorichi/tachiyomi-extensions#2736]
### Device information
* Tachiyomi extension version: 1.2.13
* Tachiyomi version: 0.8.5
* Android version: 

## Steps to reproduce
1. Read or download any chapter of any manga

### Expected behavior
Should be able to read or download

### Actual behavior
"Page list is Empty" error

**Comment by arkon** [comment]
#2496

**Comment by Kush-Patel** [comment]
Bug not fixed for me in version 1.2.17
Instead it got worse now library updates & catalogue  are also not working for kissmanga
