### ISSUE TITLE
[Feature Request] MangaPark: Chapter List Source needs a flag to disable checking of missing chapters

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [inorichi/tachiyomi-extensions#2739]
### What feature should be added to this source?
Mangapark having the option to select the list source is great but I am noticing that it doesn't work correctly when the chapter names of the different sources are wildly different. On looking through the code, I have noticed that the extension tries to look for missing chapters from other sources even when we select a particular source or select "Source with most chapters". Imo this is slightly misleading and I found the actual working of this feature only on seeing the comments in the code. 

As such, a flag option to disable checking other sources would be greatly appreciated to be prevent mixing up of chapters due to varying chapter names. 

Let me know if this is something that I can take up.

**Comment by SnakeDoc83** [comment]
The intention of the code, as it is, is to cut down on duplicate chapters but not at the cost of filtering out good chapters.  If source A has chapters 1-5 and source B has chapters 3-6, the user should see 6 chapters regardless of settings.  Here source A would have the most chapters but misses chapter 6, not showing that 6th chapter shouldn't be an option.  In practice this isn't perfect, but it's better than showing everything.

**Comment by SayakMukhopadhyay** [comment]
Yeah, I realize the intention of this option and hence I am not asking to change it. I am instead asking if soothe option can be added that can optionally disable this check, especially because many titles have sources who name their chapters very differently and this is proving to be an hindrance, at least to me.

Moreover, I am certain of this but a quick look at some titles gives an impression that the source with the most chapters usually have all of them.

**Comment by SayakMukhopadhyay** [comment]
Also this new option can have a default value so that the existing implementation doesn't break.

**Comment by SayakMukhopadhyay** [comment]
Closing as the new chapter parsing has improved a lot making this option not really necessary at this point.
