### ISSUE TITLE
[Source Request]  HTTP://READCOMICSONLINE.RU

### ISSUE THREAD

**Issue by almozayaf** [inorichi/tachiyomi-extensions#274]
This is the readble edition of getcomic 
https://getcomics.info/news/alert-readcomics-website-downtime/

it have nothing to do with http://readcomiconline.to/ (It better but i think it good thing to have another Comicbook surce just in case

**Comment by null-dev** [comment]
Yeah, it looks like readcomics.website changed their domain. I'll fix this in the CMS shortly.
