### ISSUE TITLE
Mangakakalot Timeout

### ISSUE THREAD

**Issue by Hongsworth** [inorichi/tachiyomi-extensions#2742]
### Device information
* Tachiyomi extension version: 1.2.18
* Tachiyomi version: 0.8.5
* Android version: 10.3.2

## Steps to reproduce
1. Open mangakakalot catalogue or any mangakakalot manga

### Expected behavior
Working chapters and catalogue

### Actual behavior
Long loading time followed by a timeout.

### Other details
Other extensions work except mangakakalot.

**Comment by SnakeDoc83** [comment]
Their website has been unreachable for hours, we can't fix that for them.

**Comment by Hongsworth** [comment]
I see, is this like a IP ban issue similar to kissmanga?

**Comment by SnakeDoc83** [comment]
No, they're overloaded or are having technical issues, that's not something they're doing intentionally.  Kissmanga is intentionally blocking people.

**Comment by Hongsworth** [comment]
Oh ok thanks.
