### ISSUE TITLE
[Bug] mangasee: not working at all

### ISSUE THREAD

**Issue by stnm12brX2** [inorichi/tachiyomi-extensions#2745]
Android 10
* Tachiyomi extension version: 1.2.6
* Tachiyomi version: 8.5
* Android version: 10

## Steps to reproduce
1. Click browse
2. See it not load-same with loading chapters directly and search

### Expected behavior
It should load
### Actual behavior
Error: timeout.
Thank You!

**Comment by SnakeDoc83** [comment]
Their site is broken at the moment, we can't fix that for them.

**Comment by stnm12brX2** [comment]
> Their site is broken at the moment, we can't fix that for them.

Should have checked the site before requesting a fix, thanks for the quick response.
