### ISSUE TITLE
[Bug] Kiss Manga : Page List empty for all manga downloads.

### ISSUE THREAD

**Issue by RMX911** [inorichi/tachiyomi-extensions#2751]
### Device information
* Tachiyomi extension version: 1.2.13
* Tachiyomi version: 0.8.5
* Android version: 9

## Steps to reproduce
1. Download any manga from kissanime as the source

### Expected behavior
Manga should have started to download

### Actual behavior.
Shows page list empty for all chapters.

**Comment by loocool2** [comment]
you've been IP banned for using tachiyomi

**Comment by RMX911** [comment]
Tried  Using a VPN, issue still not resolved.

**Comment by RMX911** [comment]
Hi,
I was expecting that it to be IP ban and then tried to use VPN as well.
But still there was error.

**Comment by pervertkirito** [comment]
#2496 
Kissmanga is blocking Tachiyomi user from accessing the website.
move your manga to other source.
