### ISSUE TITLE
[Bug] Japscan : Short Description

### ISSUE THREAD

**Issue by Adam935** [inorichi/tachiyomi-extensions#2755]
### Device information
* Tachiyomi extension version: 1.2.20
* Tachiyomi version: 0.8.5
* Android version: 10 QKQ1.190825.002

## Steps to reproduce

1. Access the catalog after clicking on explore, or click on recent

2. Choose any manga

### Expected behavior
See the manga page to read them

### Actual behavior
Retry for all pages

![Screenshot_2020-04-22-13-30-02-871_eu kanade tachiyomi](https://user-images.githubusercontent.com/50600860/79977337-686e9c00-849e-11ea-95c1-e36b8bc17d09.jpg)

**Comment by arkon** [comment]
#2535
