### ISSUE TITLE
[Bug] Hentai2Read : All values(Title/Artist) are unknown even though in other site it has Info

### ISSUE THREAD

**Issue by Raeven421** [inorichi/tachiyomi-extensions#2758]
### Device information
* Tachiyomi extension version: Hentai2Read 1.2.6
* Tachiyomi version: TachiyomiEH v8.4.5-EH & TachiyomiAz v8.4.9-AZ
* Android version: 10

## Steps to reproduce
1. Go to Galleries
2. Go to Hentai2Read extension -> Latest
3. Click any title

### Expected behavior
You will be able to see the title and in some cases also the Artist/Author

### Actual behavior
You can't see the title, artist and author. They are written as unknown. Swiping from right to left to view the chapters and you can see that it has correct title in the chapter title description

### Other details
It seems like when clicking the latest, i cannot see the title but when i go to the Browse portion it can load up all of the info just fine although it is not chronologically ordered, even clearing app data will still yield the same result.

**Comment by SnakeDoc83** [comment]
This is an issue with the site.  For whatever reason they're lacking information for some of their newer manga.
