### ISSUE TITLE
[Bug] Isekaiscan.com : http error 403

### ISSUE THREAD

**Issue by Gjalarhorn** [inorichi/tachiyomi-extensions#2765]
### Device information
* Tachiyomi extension version: 0.8.5
* Tachiyomi version: ?
* Android version: 8.1.0

## Steps to reproduce
1. Open on Isekaiscan source get http error 403
2. Refresh the same source get same result 

### Expected behavior
Show the manga and update

### Actual behavior
Get http error 403 when open and refresh isekaiscan.com

**Comment by AbdullahM0hamed** [comment]
Unable to reproduce this. Does it work for you via webview/browser?

**Comment by Gjalarhorn** [comment]
Nope, it just 403 forbidden I don't know what its mean so do I have to use vpn?

**Comment by Gjalarhorn** [comment]
When I use vpn it will work but sometime won't like the aource unstable

**Comment by SnakeDoc83** [comment]
Nothing we can do about that.

@arkon This can be closed.
