### ISSUE TITLE
[Bug] Questionable Content cover art is always blank

### ISSUE THREAD

**Issue by effcol** [inorichi/tachiyomi-extensions#2777]
### Device information
* Tachiyomi extension version: 1.2.4
* Tachiyomi version: 0.9.82
* Android version: 10

## Steps to reproduce
1. Install the QC extension and add the comic to library.

2. To reproduce a replacement image not being applied;
3. Press the Info button on the Info tab of the comic
4. Press on the blank line where the cover image should be (very difficult to press, repeatedly tap)
5. Select replacement image, and Save

### Expected behavior
Cover art should be loaded when looking at the comic in the catalogs, and then downloaded when added to library.

After that, when editing the comic's metadata, you should be able to select a downloaded image and apply it as the cover and apply that instead of the default cover.

### Actual behavior
No image is loaded at any point and the area an image should be is left blank, even when trying to apply a custom cover image.

### Other details
I'm also presuming the other metadata for the comic should also be loaded, such as Author, Artist, Status, etc should be loaded but that is also left blank, although author and artist info can be added manually.

**Comment by SnakeDoc83** [comment]
Extension seems to load a thumbnail perfectly fine for me.  The URL is hardcoded, maybe it was unreachable at the time you added QC to your library.  Try refreshing (pull down on the info page).

If you have issue with manually changing the cover that's a j2k or main app issue.  The metadata is also loading fine; if you have issue with editing it that's a j2k issue.

**Comment by effcol** [comment]
Tried refreshing in the info page but it's still not appearing. 

I am running j2k, but the exact same issue with the cover not loading was happening on the non j2k version when I had that installed. I uninstalled and reinstalled the QC app between installing the two different versions, so I would have thought that wouldn't be linked to it, but not sure.

**Comment by SnakeDoc83** [comment]
If it's saved in your library right now, try "refresh libary metadata" in settings.  If that doesn't work, remove it from your library then "clear chapter cache" and "clear database."  That should totally clear all QC info (including chapter count; so make sure you know where you left off) and make it like you're seeing it for the first time when you load it from the catalog again.

**Comment by effcol** [comment]
That worked, thank you :)
