### ISSUE TITLE
[Bug] Source Name : Short Description

### ISSUE THREAD

**Issue by Ekka-i** [inorichi/tachiyomi-extensions#2779]
Samsung S6 Edge

Tachiyomi extension version: Kissmanga 1.2.17
Tachiyomi version: r2096 (b3611eef)

Android version: 5.1.1

I was planning to read some manga on Kissmanga and so I went and there was no manga. Went to Google and saw that opening on WebView might work. 

So I went to WebView and... It doesn't work. I tried "Open in Browser". The website itself works but when I returned to Tachiyomi, it's still blank. It's the same with my other phone. I don't know what's happening. The guides told me that opening it in Web View would fix it and that I would only need to verify the CAPTCHA. But how would I verify it if there was nothing to verify in the first place?

The screen on Web View is all black except there's a white bar on top, placed horizontally. When opening it on browser, it sends me directly to the KissManga homepage. I tried logging in to the website and returned to Tachiyomi but it's not working at all.
![Screenshot_2020-04-24-02-05-10](https://user-images.githubusercontent.com/64222454/80135872-78d46300-85d3-11ea-8572-21fa70f0c84b.png)

**Comment by CarlosEsco** [comment]
#2496
