### ISSUE TITLE
[Bug] Source Name : Short Description

### ISSUE THREAD

**Issue by lordgrim1313** [inorichi/tachiyomi-extensions#2780]
### Device information
* Tachiyomi extension version: MyReadingManga version 1.2.33
* Tachiyomi version: J2K ver 0.9.82
* Android version: 9

### Expected behavior
This is how it was in the Web view
![Screenshot_20200424_032017](https://user-images.githubusercontent.com/64225966/80142051-6587b000-855f-11ea-8d5d-dca7cff7588f.jpg)

### Actual behavior
The extension on the app is not updating like the mangas (when you open the extension) are different from the one from the webview. Its not updating its contents.
![Screenshot_20200424_032021](https://user-images.githubusercontent.com/64225966/80142222-ae3f6900-855f-11ea-9d2d-8ec590e69038.jpg)

Please helppppp 😭😭😭

**Comment by SnakeDoc83** [comment]
If you want to see their new stuff, tap "latest" instead of "browse."
