### ISSUE TITLE
[Bug] madara : isekai scan 403 error

### ISSUE THREAD

**Issue by samanta-widjaja** [inorichi/tachiyomi-extensions#2781]
### Device information
* Tachiyomi extension version: 1.2.74
* Tachiyomi version: 0.8.5 
* Android version: 7.1.1 

1. Open isekai scan in web view and download chapter both result 403 forbidden 
2. But when i open through web browser such as opera, it is fine

Help please

**Comment by SnakeDoc83** [comment]
Sounds like an issue with your device.  Maybe you've got something on it that's causing an issue (adblocker or some other app) or the network it connects to blocks the website.

**Comment by ItzPoutingGoogle** [comment]
Hello! Isekaiscan does not work for me. This is not an isolated issue therefore I kinda want it opened. Though, visiting the site in Chrome, it is also spitting out 403 Forbidden errors

**Comment by samanta-widjaja** [comment]
Have you try to use VPN and choose another country in it?

**Comment by ItzPoutingGoogle** [comment]
> Have you try to use VPN and choose another country in it?

Not yet, I will do it later

**Comment by ItzPoutingGoogle** [comment]
> > Have you try to use VPN and choose another country in it?
> 
> Not yet, I will do it later

So I have looked into it, Other countries do receive data from isekaiscan. I tested the US and Amsterdam VPNs, and I can receive data from them. It might be because IsekaiScan is banning locations outside of their intended reach, or maybe they are pulling up a KissManga and banning Adblock users.

Area: SEA, Philippines

**Comment by ItzPoutingGoogle** [comment]
> Sounds like an issue with your device. Maybe you've got something on it that's causing an issue (adblocker or some other app) or the network it connects to blocks the website.

definitely not a device issue and more like geo blocking

**Comment by C0nvert** [comment]
Site changed to .tk instead of .com
