### ISSUE TITLE
[Feature Request] Download Tray/Viewable Chapter tray

### ISSUE THREAD

**Issue by cievee** [inorichi/tachiyomi-extensions#2792]
### What feature should be added to this source?
1. I would like it if there is something like a download tray like this 
![IMG_20200424_144135](https://user-images.githubusercontent.com/64214774/80182625-e6b37580-8639-11ea-9cc2-65ff4ce5a109.JPG)
so that i wont have to manually search for the mangas i downloaded

2. I also notice that when i want to go to a certain chapter i would have to close the chapter i'm currently reading and go back to the chapter section so i woulf have to memorize the chapter i'm reading. So i would like it if the dev adds a feature like this one
![IMG_20200424_143650](https://user-images.githubusercontent.com/64214774/80182484-963c1800-8639-11ea-8c88-f1a66af73f3c.JPG)
![IMG_20200424_143930](https://user-images.githubusercontent.com/64214774/80182498-a0f6ad00-8639-11ea-880c-937080236c56.JPG)

**Comment by bbtora** [comment]
1. You can filter the manga in your library.
read https://tachiyomi.org/help/guides/my-library/#my-library

2. Closing the current chapter will display the page-number you were at, in the chapter list (unless you're at the first page)

Let me know if this helps.

**Comment by cievee** [comment]
I found it thank you I'm new to this app so it's a little bit confusing to me anyways thank you
