### ISSUE TITLE
[Source Request] Mangago.me

### ISSUE THREAD

**Issue by cievee** [inorichi/tachiyomi-extensions#2793]
### Source Website
Website can be found at http://www.mangago.me/

### Other Details
This site contains many queer manga unlike some other sites I saw. Although it has some annoying ads when you opened a chapter

**Comment by SnakeDoc83** [comment]
Not going to happen.

**Comment by cievee** [comment]
> Not going to happen.

Why??

**Comment by SnakeDoc83** [comment]
There used to be an extension but it was too much of a pain to maintain because they obfuscate their manga making it hard to scrape.

**Comment by cievee** [comment]
> There used to be an extension but it was too much of a pain to maintain because they obfuscate their manga making it hard to scrape.

Oh okay thank you for the clarification
