### ISSUE TITLE
[Bug] tachiyomi mangaOnl extension error http 404

### ISSUE THREAD

**Issue by LycNeptune** [inorichi/tachiyomi-extensions#2797]
### Device information
* Tachiyomi extension version: 8.5.0
* Tachiyomi version:  i dont know the source because maybe its on the multiple extension
* Android version:  9

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Open normally

### Actual behavior
Http 404

**Comment by SnakeDoc83** [comment]
Website's borked right now and in general has been iffy the last couple days.  We can't fix their website for them.

**Comment by LycNeptune** [comment]
> Website's borked right now and in general has been iffy the last couple days. We can't fix their website for them.

Well yesterday i can open it after all.. so i ask again now

**Comment by SnakeDoc83** [comment]
Okay, and right now the website is down.

**Comment by LycNeptune** [comment]
> Okay, and right now the website is down.

Ok maybe we will wait for 1 day first? Can you tell me what webstite that come from?

**Comment by SnakeDoc83** [comment]
mangaonl.com

**Comment by LycNeptune** [comment]
> 
> 
> mangaonl.com

maybe i need to wait again..

**Comment by arkon** [comment]
There's an option in the app to open the catalogue in webview. Check that first before opening issues.
