### ISSUE TITLE
[Bug] MangaBox (Mangakakalot and others) : Mangakakalot moved to new domain - others broken too

### ISSUE THREAD

**Issue by E3FxGaming** [inorichi/tachiyomi-extensions#2798]
### Device information
* Tachiyomi extension version: 1.2.18
* Tachiyomi version: 0.8.5
* Android version: 9.1

## Steps to reproduce
1. Install MangaBox extension
2. Try to do anything with the any source added by this extension

### Expected behavior
Sources work as expected

### Actual behavior
HTTP error 404 

Mangakakalot moved from https://mangakakalot.com/ to https://mangakakalots.com/.
Either the crawlers of major search engines is slow, or they don't want to be found anymore, because they don't show up in search results anymore.
Mangakakalots.com still has the Mangakalot banner on the website.

Other websites included in this extension 

- https://manganelo.com (website doesn't work anymore at all)
- https://mangabat.com (website has huge error banners)
- https://mangaonl.com (website doesn't work anymore at all)
- https://chaptermanga.com (cloudflare reports Host connection error)

were semingly somehow attached to the old Mangakakalot and were not prepared for this change either. Maybe those websites moved to other domains too, but I wouldn't even know where to start looking for them (as I said, search engines aren't helpful).

I don't know it this change will be only temporary, there are no information given on the https://mangakakalots.com/ website.

**Comment by arkon** [comment]
Mangakakalots is not the same website as far as we know. It's been around for a while.

**Comment by E3FxGaming** [comment]
But https://mangakakalots.com/ has a banner in the top left corner saying "Mangakalot". Where did the original https://mangakakalot.com/ go and why are all the other sources added by this extension so broken?

**Comment by darscute03** [comment]
All bookmarks now says http 404. 😔. I hope this gets fix soon.

**Comment by E3FxGaming** [comment]
Update:
- https://mangakakalot.com/ is back online and usable
- https://mangakakalots.com/ is unusable now (website loads but has no manga content)

I'm still convinced those websites are somehow connected (same site layout with only nuanced differences, e.g. in queries for a particular tag mangakakalot uses tag numbers while mangakakalots used tag names)

The other 4 mentioned sources still have broken websites and therefore don't work. Mangabat doesn't show proper website content anymore (showed error banners before).

**Comment by gojizeo** [comment]
mangabat and mangaonl websites still say no input file basically they still dont work

**Comment by arkon** [comment]
Added in #2810
