### ISSUE TITLE
[Meta] Remove Mangaworld.tv

### ISSUE THREAD

**Issue by CarlosEsco** [inorichi/tachiyomi-extensions#2800]
At request of site owner

**Comment by MarioVerdino** [comment]
I don't want to sound rude, but why would you comply with their request? They're the same as Kissmanga, but for Italian scanlations. If Kissmanga asked you to remove its extension, would you accept? I understand when you accept requests from the scanlators to remove their sites, but I don't think you've ever accepted requests to remove aggregators. Again, I'm not complaining, I'm just asking for an insight on how you make decisions about this kind of things.

**Comment by CarlosEsco** [comment]
yes
