### ISSUE TITLE
KissManga Syntax error :parse error 

### ISSUE THREAD

**Issue by Radixtrator** [inorichi/tachiyomi-extensions#281]
Hi guys, 
Since this morning all of my KissManga manga suddenly stopped working. It doesn't matter which series I want to read, I always get a syntax error (parse error:line1) on them and it won't open. 
Anyone have a solution?

**Comment by arkon** [comment]
What version of Tachiyomi are you using?

What source/manga/chapter is it happening for?

**Comment by Radixtrator** [comment]
It's happening on 7.1.
As I said before, it's happening on KissManga, with everything. So all manga and all chapters

**Comment by CarlosEsco** [comment]
Can you access through browser?  I have no issues accessing

**Comment by Radixtrator** [comment]
Works absolutely fine through the browser..

**Comment by hakapoid** [comment]
This issue has occurred to me at this present point, anyone know how to fix it?
