### ISSUE TITLE
[Bug] Net Truyen : get "Retry" button almost manga

### ISSUE THREAD

**Issue by haruki-takeshi** [inorichi/tachiyomi-extensions#2819]
* Tachiyomi extension version: Net Truyen 1.2.5
* Tachiyomi version: 0.9.82
* Android version: 10

I try to load some manga with Net Truyen extension but only show "Retry" button as below: 
![Screenshot_20200425-171000_Tachiyomi](https://user-images.githubusercontent.com/15504010/80277446-2bfaa480-8719-11ea-81a9-b429fd06b805.jpg)

I tried to open with web viewer for same manga and same chapter, it shows totally okay. 
![Screenshot_20200425-171049_Tachiyomi](https://user-images.githubusercontent.com/15504010/80277496-85fb6a00-8719-11ea-994a-716570590964.jpg)

It happened many times with some manga in this extension/source as well.

Please help to verify and fix. 

This source have another free VIP url: http://nhattruyen.com
You can verify and use for alternative option.

**Comment by SnakeDoc83** [comment]
The website for this source is forwarding to the other one you mention, and that one is being added to WP-Comics in https://github.com/inorichi/tachiyomi-extensions/pull/2829

@arkon Until (if) the original website is available again there's nothing else to do here.
