### ISSUE TITLE
[Source Request] Source Name

### ISSUE THREAD

**Issue by alegaab** [inorichi/tachiyomi-extensions#2825]
Mangaworld the best italian repo is now obsolete please reupload it :)

**Comment by AbdullahM0hamed** [comment]
@alegaab the mangaworld extension was removed at the behest of the owner. Request an alternative site instead.

It also may be worth noting that you will likely still be able to use the extension you already have, if you ignore the "obsolete" warning, but it will receive no updates henceforth.
