### ISSUE TITLE
[Bug] Mangabat: Source defective

### ISSUE THREAD

**Issue by AlbedoSuzuki** [inorichi/tachiyomi-extensions#2827]
### Device information
* Tachiyomi extension version: 1.2.19
* Tachiyomi version: 0.8.5
* Android version: 8.1.0

### Source information
* Source name: Mangabat
* Source extension version: 1.2.19

## Steps to reproduce
1. I was trying to read something and all of a sudden it just stopped.
2. I reinstalled tachiyomi and it still didn't work.

### Expected behavior
normal reading and more chapters of my favourite mangas

### Actual behavior
Me: tap on the desired manga
Manga: Open ... Closed
Message: HTTP error 404
<img width="600" alt="Screenshot_20200425-232723" src="https://user-images.githubusercontent.com/61992892/80291479-1ce21980-874e-11ea-85e0-50c957525275.png">

**Comment by SnakeDoc83** [comment]
Bad bot.  Also, the site is down right now; so, nothing we can do here.

**Comment by Prinnny** [comment]
> ### Device information
> * Tachiyomi extension version: 1.2.19
> * Tachiyomi version: 0.8.5
> * Android version: 8.1.0
> 
> ### Source information
> * Source name: Mangabat
> * Source extension version: 1.2.19
> 
> ## Steps to reproduce
> 1. I was trying to read something and all of a sudden it just stopped.
> 2. I reinstalled tachiyomi and it still didn't work.
> 
> ### Expected behavior
> normal reading and more chapters of my favourite mangas
> 
> ### Actual behavior
> Me: tap on the desired manga
> Manga: Open ... Closed
> Message: HTTP error 404
> <img alt="Screenshot_20200425-232723" width="600" src="https://user-images.githubusercontent.com/61992892/80291479-1ce21980-874e-11ea-85e0-50c957525275.png">

Source is not defective. There have been many solutions listed if you even went to search for them. You have to open Chrome or Safari, go to the website, and do the captcha. If there is no captcha then go to your chapter on the website and refresh the page manually. I use Mangabat and that's how you fix it.

**Comment by AlbedoSuzuki** [comment]
It doesn't work for me, when I try to open it with browser it doesn't even load the website
Here are 2 pictures once from:
Open in browser
And second:
Open in web view
![Screenshot_20200427-002307](https://user-images.githubusercontent.com/61992892/80321479-a57bbb00-881d-11ea-870a-934fce39c675.png)
![Screenshot_20200427-002327](https://user-images.githubusercontent.com/61992892/80321483-a6ace800-881d-11ea-98c9-6adfdc1fdbaf.png)

**Comment by Prinnny** [comment]
It seems mangabat is having trouble connecting to your device. I also read this manhua, but I read it using 1st Kiss which can be found from the Madara extension. I also seem to be experiencing problems from Mangabat from time to time. Although it's not a solution for Mangabat, but an alternative, I hope it does solve your issue.

**Comment by AlbedoSuzuki** [comment]
Thanks for the feedback, and I've already started reading on other extensions but I have a few hundred mangas and I honestly don't want to switch them all to another source.
