### ISSUE TITLE
[Bug] Mangabat : Source defective

### ISSUE THREAD

**Issue by AlbedoSuzuki** [inorichi/tachiyomi-extensions#2828]
### Device information
* Tachiyomi extension version: 1.2.19
* Tachiyomi version: 0.8.5
* Android version: 8.1.0

### Source information
* Source name: Mangabat
* Source extension version: 1.2.19

## Steps to reproduce
1. I was trying to read something and all of a sudden it just stopped.
2. I reinstalled tachiyomi and it still didn't work.

### Expected behavior
normal reading and more chapters of my favourite mangas

### Actual behavior
tap on the desired manga
the Manga Opened and then Closed almost immediately
and the Message: "HTTP error 404" popped up

<img width="600" alt="Screenshot_20200425-232723" src="https://user-images.githubusercontent.com/61992892/80291581-ff617f80-874e-11ea-8e60-9426df1142dc.png">

**Comment by arkon** [comment]
Yeah sorry idk why it's closing it. I reopened #2827.

**Comment by AlbedoSuzuki** [comment]
Entschuldigung für die anderen versuche die ich gestartet habe, da dieser versuch nicht funktionierte
