### ISSUE TITLE
[Bug] FMReader's Hanascans (RawQQ) : Source down only in app?

### ISSUE THREAD

**Issue by natsukagami** [inorichi/tachiyomi-extensions#2830]
### Device information
* Tachiyomi extension version: FMReader 1.2.8
* Tachiyomi version: 0.8.5
* Android version: Android 10 on OnePlus 6

### Source information
* Source name: FMReader / HanaScan (RawQQ)
* Source extension version: 1.2.8

## Steps to reproduce
- Open any manga and any chapter.

### Expected behavior
Manga should be readable 

### Actual behavior

- All pages do not load on any manga. Shows only "Retry" button.
- Webview: I can access the manga's info page, but any click/scroll beyond that shows a blank page.
- Browser works fine.

### Other details

Also tried on my other phone, with VPN/Wifi/mobile network.

**Comment by edison0354** [comment]
Already updated to 1.2.9, but the issue is still there for me. Anyone else has tried?

**Comment by SnakeDoc83** [comment]
Looks like they changed their header requirements again.  I'll open another PR for it sometime today but who knows if they'll start employing stronger measures to dissuade scraping.
