### ISSUE TITLE
[Bug] Source Name : Manhua Es missing chapter

### ISSUE THREAD

**Issue by baynur** [inorichi/tachiyomi-extensions#2831]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.8.5)
- I have updated all extensions
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/inorichi/tachiyomi
- I have searched the existing issues for duplicates
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions/

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

### Device information
* Tachiyomi extension version: 0.8.5
* Tachiyomi version: ?
* Android version: ?

### Source information
* Source name: WP comic
* Source extension version: ?

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened

### Actual behavior
Missing Chapter
![Screenshot_2020-04-26-05-43-12-picsay](https://user-images.githubusercontent.com/64335013/80292475-28026d00-8781-11ea-879f-dbf4d09ecd20.jpg)

**Comment by arkon** [comment]
That's all the website has.

https://manhuaes.com/comics/daddy-from-hell/
