### ISSUE TITLE
All mangas of hentai2read not being shown

### ISSUE THREAD

**Issue by dragneel152** [inorichi/tachiyomi-extensions#2837]
### Device information
* Tachiyomi version: v.8.4.9-AZ
* Android version: 9 
* Device: Redmi Note 8 pro

### Source information
* Source name: Hentai2read
* Source extension version: 1.2.7

## Steps to reproduce
1. First step - Open the gallery or the source to search. 
2. Second step - well for example - search "mama club" by tukisiro saya the result says not found
3. Third step - Now open in web view or browser and search for mama club in the site or search by the author you will find it. 

## Issue/Request
All the Mangas present on the website are not being shown through the app

## Other details
Additional details and attachments.

**Comment by Chaotiic28** [comment]
Having the same issue. Really annoying.
