### ISSUE TITLE
[Bug] Mangakakalot : Isekai tag error

### ISSUE THREAD

**Issue by Applewubs** [inorichi/tachiyomi-extensions#2840]
In the Mangakakalot extension, there is a rather curious and annoying error that causes after a few seconds of searching to start repeating the same manga over and over again.

---

### Device information
* Tachiyomi extension version: ?
* Tachiyomi version: 0.8.5-2112
* Android version: 10

### Source information
* Source name: Mangabox (Mangakakalot and others)
* Source extension version: 1.2.19

## Steps to reproduce
1. Open Mangakakalot and search specifically for Isekai (I don't know if it happens with other extensions of mangabox)
2. Just keep scrolling down and the same group of manga will keep repeating itself.
![Screenshot_20200426-021549812](https://user-images.githubusercontent.com/59571080/80300826-83266680-8765-11ea-9b50-ec8d91c75085.jpg)

### Expected behavior
There should be more different manga.

### Actual behavior
Same group of manga everytime

### Other details
Dunno if it happens with other sub-extensions of the mangabox extension, but it's annoying, I can't search manga with this.

**Comment by SnakeDoc83** [comment]
It's just the last page that's repeating, you've already seen everything at that point.  Should still be fixed though.

**Comment by Applewubs** [comment]
Yeah, I tried with the unofficial one, there's about 4 more manga there, but the last page keeps appearing.
