### ISSUE TITLE
[Meta] Range selection when dowloading multiple chapters

### ISSUE THREAD

**Issue by Vaturobi** [inorichi/tachiyomi-extensions#2844]
###  Why/Project's Benefit/Existing Problem
Range selection when downloading multiple chapters
i.e. if a manga/manhwa/manhua has 500 chapters and i want to download chapter 300-450 I just select those two and it automatically selects everything in between and i don't have to individually select said chapters

**Comment by CarlosEsco** [comment]
Wrong repo and if you are on preview long press the two chapters to select all between
