### ISSUE TITLE
[Source Request] Multiple one comic sources

### ISSUE THREAD

**Issue by Fooftilly** [inorichi/tachiyomi-extensions#2847]
### SMBC
Website can be found at https://www.smbc-comics.com/

### Other Details
None
______________________________________________________________________________________________________
###Dinosaur Comics
Website can be found at http://www.qwantz.com/index.php

### Other Details
None
______________________________________________________________________________________________________
### lunarbaboon
Website can be found at http://www.lunarbaboon.com/

### Other Details
None
______________________________________________________________________________________________________
### Nerdoid
Website can be found at http://nedroid.com/

### Other Details
None
______________________________________________________________________________________________________
### Hark, a vagrant
Website can be found at http://www.harkavagrant.com/

### Other Details
None
______________________________________________________________________________________________________
### Dead Philosophers in Heaven
Website can be found at http://www.dead-philosophers.com/

### Other Details
None
______________________________________________________________________________________________________
### User Friendly
Website can be found at http://www.userfriendly.org/

### Other Details
None
______________________________________________________________________________________________________
### Sluggy Freelance
Website can be found at http://sluggy.com/

### Other Details
None
______________________________________________________________________________________________________
### Penny arcade
Website can be found at https://www.penny-arcade.com/comic/hub

### Other Details
None
______________________________________________________________________________________________________
### Nuklear Power
Website can be found at http://www.nuklearpower.com/2001/03/02/episode-001-were-going-where/

### Other Details
None
______________________________________________________________________________________________________
### MegaTokyo
Website can be found at https://megatokyo.com/

### Other Details
None
______________________________________________________________________________________________________
### unicorn Jelly
Website can be found at http://unicornjelly.com/uni001.html

### Other Details
None
______________________________________________________________________________________________________
### Bruno the bandit
Website can be found at http://brunothebandit.com/d/19980720.html

### Other Details
None
______________________________________________________________________________________________________
### Sabrina Online
Website can be found at http://www.sabrina-online.com/archive.html

### Other Details
None

Sorry for the big list. I think it's better this way that to open 20 new issues.

**Comment by CarlosEsco** [comment]
Hate to be the dick but search to make sure there are no duplicate requests. And 1 ticket per issue.
