### ISSUE TITLE
[Bug] SeriManga - Previous episodes

### ISSUE THREAD

**Issue by Agayev033** [inorichi/tachiyomi-extensions#2856]
### Device information
* Tachiyomi extension version: 1.2.2
* Tachiyomi version: 0.8.5
* Android version: 10

### Source information
* Source name: SeriManga
* Source extension version: 1.2.2

### Problem
when I enter a manga it doesn't show the previous episodes
![Screenshot_20200426-225011](https://user-images.githubusercontent.com/30019351/80316780-cc7fc000-8810-11ea-9725-2d6c50d313ad.png)

**Comment by AbdullahM0hamed** [comment]
Rip, didn't know some manga had chaps on seperate pages. Will work on it.

**Comment by Agayev033** [comment]
> Rip, didn't know some manga had chaps on seperate pages. Will work on it.

Sorry bro. İ give you so many problem :(
