### ISSUE TITLE
[Bug] Mangabox (manganelo) : when trying browse it just shows no result found

### ISSUE THREAD

**Issue by Vaturobi** [inorichi/tachiyomi-extensions#2868]
---

### Device information
* Tachiyomi version: 0.8.5
* Android version: 8.0

### Source information
* Source name: Mangabox
* Source extension version: 1.2.20

## Steps to reproduce
1. Go to manganelo in catalogue
2. Click browse

### Expected behavior
Manga list should appear

### Actual behavior
It just says no result found

**Comment by SnakeDoc83** [comment]
This is a source issue, the website was misbehaving but is now working.  You may experience intermittent issues but there's nothing we can do about it.
