### ISSUE TITLE
[Bug] AllPornComic: Http Error 403

### ISSUE THREAD

**Issue by throwaway56545853** [inorichi/tachiyomi-extensions#2869]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 10

### Source information
* Source name: AllPornComic
* Source extension version: 1.2.80

## Steps to reproduce
1. Bring up the AllPornComic Catalogue.

### Expected behavior
Able to see entries

### Actual behavior
No manga/comic entries
Http Error 403 alert

**Comment by SnakeDoc83** [comment]
Source has turned on a captcha for their site, you need to solve it in webview.

**Comment by throwaway56545853** [comment]
I was unable to find a captcha during my runthrough of the site.
Can you tell me how you were able to get the captcha?

**Comment by throwaway56545853** [comment]
> Source has turned on a captcha for their site, you need to solve it in webview.

**Comment by SnakeDoc83** [comment]
On APC's browse screen tap the 3 dots at the top then open in webview.

**Comment by throwaway56545853** [comment]
Ahh I see. Thank you
