### ISSUE TITLE
[Bug] Mangabat: HTTP error 404

### ISSUE THREAD

**Issue by PlebeianDev** [inorichi/tachiyomi-extensions#2870]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 7.1.1

### Source information
* Source name: Mangabat (EN)
* Source extension version: N/A (included with other sources, under another name). All my sources are updated to LATEST.

## Steps to reproduce
1a. Open Mangabat from Catalogue.
1b. Open any chapter from any manga from Mangabat source.

### Expected behavior
Expected to open/load the chapter or the source's preview

### Actual behavior
Returning: HTTP error 404

### Other details
While this happens within the app, the actual mangabat site can be reached using any browser on android or computer and works properly.

**Comment by SnakeDoc83** [comment]
@arkon The source's website is back up and seems to be working fine in Tachi.

**Comment by PlebeianDev** [comment]
I'm still getting the same error from the source's mangas though.

**Comment by SnakeDoc83** [comment]
When browsing the catalog or from manga you've favorited?

**Comment by PlebeianDev** [comment]
Via my bookmarks/favorites

**Comment by PlebeianDev** [comment]
Looking up the source again today (yesterday was not accessible), mangas on my library are not marked as favorites on mangabat source. Could you shed some light on that ?

**Comment by PlebeianDev** [comment]
Before I kill anybody's time I found a sort of a quick fix. I guess that after the source got live again the bookmarks in your library need to be massively migrated. So what I did is:
My library --> (top right, 3 vertical dots) Source migration --> Mangabat (select) --> You'll see a list of every manga you "watch" from mangabat source --> open each and everyone and select again mangabat.
After go back to your library list, refresh/update your library and you should be fine.
And with that I'm closing the issue.

**Comment by SnakeDoc83** [comment]
>Could you shed some light on that ?

Similar situation to Mangakakalot where they changed the URLs for their manga.  Migrating like you did was what people had to do for that source as well.
