### ISSUE TITLE
[Source Request] mangawindow.club

### ISSUE THREAD

**Issue by AriaMoradi** [inorichi/tachiyomi-extensions#2871]
### Source Website
Website can be found at **https://mangawindow.club/**.

### Other Details

it is different from https://mangawindow.net/

**Comment by AriaMoradi** [comment]
looks like the images a being loaded from mangapark.net
but as weird as it gets mangawindow has newer chapters(which mangapark doesnt have) but the images are still loaded from mangapark

**Comment by AriaMoradi** [comment]
some of the manga links are redirected to http://manganelos.com/

**Comment by AriaMoradi** [comment]
looks like both websites are using the same front end javascript source: readmanga.js
https://mangawindow.club/frontend/chapter/js/readmanga.min.js
http://manganelos.com/frontend/chapter/js/readmanga.min.js

which the way it works is really simple: 
`picArry = $("#arraydata").text().split(",")`

there is a tag in the html source code that exposes all the download links for the images like this one:
```
<p id=arraydata style=display:none>
https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/1.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/2.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/3.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/4.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/5.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/6.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/7.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/8.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/9.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/10.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/11.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/12.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/13.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/14.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/15.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/16.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/17.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/18.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/19.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/20.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/21.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/22.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/23.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/24.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/25.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/26.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/27.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/28.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/29.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/30.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/31.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/32.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/33.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/34.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/35.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/36.jpg,https://s8.mkklcdnv8.com/mangakakalot/u1/uaxz925974686/chapter_63/37.jpg
</p>
```

so there are two results:
1- writing the code for this extension will be really easy
2- the extention can be multi-source becasue these two websites are pretty much the same with a different css theme.

**Comment by AriaMoradi** [comment]
I'm going to start coding this extension and I'm going to name it `MangaWindow.club` and the package name will be `MangaWindow (and MangaNelo)`
if there are any suggestions for better naming, shoot

**Comment by AriaMoradi** [comment]
also help with the extension `ic_launcher.png` is needed.
here's links to both websites favicon:
http://manganelos.com/frontend/images/favico12.png
https://mangawindow.club/frontend/imgs/favico.jpg

I think the icons are too detailed too look good, on the other hand since this will be a multi-source extension maybe design a new one?

**Comment by SnakeDoc83** [comment]
The two sites look a bit different, are you sure they're the same theme?

Also, manganelos.com uses the theme Paprika was made for and could be added there.

**Comment by AriaMoradi** [comment]
@SnakeDoc83 
from the css, mangawindow uses a variation of this theme: http://enduser.id/member/product/emanga-wordpress-theme

and about manganelo I didn't understand what you said

**Comment by SnakeDoc83** [comment]
Sources are grouped together in a multi-source extension when their websites are similar.  There's an extension called Paprika that currently supports https://ir2me.com and https://www.mangatensei.com.  If you look at those two websites you'll see that they use the same theme as manganelos.com does; so it should be added to that extension.

**Comment by AriaMoradi** [comment]
wow
you cracked the code!
yes you are correct they all are using the same javascript frontend code(https://ir2me.com/ seems to not work right now? cant load any chapters)
well mangatensei used to be the same as bato.to but since it broke and changed, but all and all yes, they are the same

**Comment by AriaMoradi** [comment]
i'd like to do some more investigation before closing the case for this source.

**Comment by AriaMoradi** [comment]
so I added both sites to paprika and tested the code
* mangawindow doesnt work
* manganelo works and loads chapters, but covers dont wrork

**Comment by AriaMoradi** [comment]
so, it looks like manganelo can be added to the extension (maybe they are mirrors for the same site?)

**Comment by AriaMoradi** [comment]
I'm going to work on paprika from now on, if that's okay?

**Comment by SnakeDoc83** [comment]
You may need to override a function or two to get Manganelos working.  Don't try to force Mangawindow in if it doesn't fit.

**Comment by AriaMoradi** [comment]
the original mangatensei `ic_launcher.png` is much better than the current one
