### ISSUE TITLE
[Source Request] mangarockteam.com

### ISSUE THREAD

**Issue by Oblivia8** [inorichi/tachiyomi-extensions#2872]
# Source Website
@ https://mangarockteam.com

# Other Details
Its a website that so far has the best catalog closest to the original https://mangarock.com/, it also has the most ordered chapters of Apotheosis.

**Comment by joseph619** [comment]
This appears to be another random Madara site with Manga Rock name

**Comment by Oblivia8** [comment]
What would be the closest catalog to it?
