### ISSUE TITLE
[Feature Request] <source name>: <short description>so i was wondering if you could add a source for a certain website. the link to the website in question is earlymanga.website . aslo this is my first time requesting so i apologise in advance if i did anything wrong 

### ISSUE THREAD

**Issue by retrded1** [inorichi/tachiyomi-extensions#2873]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.8.5)
- I have updated all extensions
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/inorichi/tachiyomi
- I have searched the existing issues for duplicates
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions/

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

**Comment by CarlosEsco** [comment]
#2728
