### ISSUE TITLE
[Bug] Mangapark : Chapter List Source not working

### ISSUE THREAD

**Issue by cvalenciaec** [inorichi/tachiyomi-extensions#2883]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 7.0

### Source information
* Source name: Mangapark
* Source extension version: 1.2.12

## Steps to reproduce
1. Configure Mangapark extension to any of valid values for Chapter List Source

### Expected behavior
For example, If we select Source with most chapter, should only shows one source (the one with most chapters)

### Actual behavior
Shows all sources with all chapters, there is no chapter filtering according to Chapter List Source setting.

**Comment by CarlosEsco** [comment]
are you swipe refreshing the chapter list after you set this?

**Comment by cvalenciaec** [comment]
Yes, swiping down refresh the chapter list but it doesn't show list as according the parameter set in configuration.

**Comment by CarlosEsco** [comment]
sample manga?

**Comment by cvalenciaec** [comment]
you can use Kaguya-sama as example or any manga with different sources and a lot of chapters.

**Comment by CarlosEsco** [comment]
Seemed fine for me. Can you provide screens

**Comment by cvalenciaec** [comment]
Sorry, seems that Kaguya works fine, but you can try with Fairy Tail, it shows 1473 chapters unread when configuring "Source with most chapters"

**Comment by CarlosEsco** [comment]
yea that seems to be bugged

**Comment by SnakeDoc83** [comment]
Related to https://github.com/inorichi/tachiyomi-extensions/issues/2541, volume numbers are causing the issue.
