### ISSUE TITLE
Kissmanga error (multiple) 

### ISSUE THREAD

**Issue by metroxx** [inorichi/tachiyomi-extensions#289]
Xiaomi Redmi note 4 (miui global 9.5)
Android version 7.0

Half of the downloads fail. In app it says it's downloaded, but when i check the download folder all i see is a 0 b size file. 
Right now i can't even open any of the manga online in the app saying "page list empty". I can read it on the site just fine. 
Tried tge advanced options and reinstalling the app too. Other source seems to work fine. (i try to use them those in the time being.)

**Comment by arkon** [comment]
What version of the app do you have installed?

**Comment by metroxx** [comment]
0.7.2
Manga i had this problem: Suki x Suki (HIBARU Shunsuke)

How to replicate
It seems like it always did when i started to download more than 1 chapter

**Comment by metroxx** [comment]
The page list empty part was probably only problem here. 
But the download problem still exists.

**Comment by SnakeDoc83** [comment]
This could probably be closed, more than a year old and around 5 versions old.
