### ISSUE TITLE
[Bug] Source Name : Short Description

### ISSUE THREAD

**Issue by noxipoop** [inorichi/tachiyomi-extensions#2898]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 10

### Source information
* Source name: KissManga
* Source extension version: 1.2.17

## Steps to reproduce
1. Open catalogues and try to look at KissManga.
2. Says no results found.

### Expected behavior
This should have happened
1. Shows catalogues

### Actual behavior
This happens instead
2. Shows no results found

### Other details
Tried to uninstall the app, Resinstalling app, clearing cache, reloading database, etc.
Uninstalled extension, reinstalling the extension
Did the opening kissmanga on the browser after clearing the cache and reopening app trick.

**Comment by CarlosEsco** [comment]
#2496

**Comment by noxipoop** [comment]
I already tried what you wrote in that thread. Different error as well. I don't get the error code just says "No results found."

**Comment by noxipoop** [comment]
Also the kissmanga site works fine on the browser for me so I'm not banned from the site

**Comment by CarlosEsco** [comment]
then its broken, but extension is not being actively supported anymore

**Comment by noxipoop** [comment]
Works perfectly fine for my other friend though so hoping for someone who knows a fix for it :/

**Comment by CarlosEsco** [comment]
#2909
