### ISSUE TITLE
[Bug] Nettruyen cannot read

### ISSUE THREAD

**Issue by vudoanbinhminh** [inorichi/tachiyomi-extensions#2899]
The manga via nettruyen source is currently not readable (  have to go to nettruyen before, then return to the app to read it )

---

### Device information
* Tachiyomi version: 0.8.5
* Android version: 10

### Source information
* Source name: nettruyen
* Source extension version: 1.2.5

## Steps to reproduce
1. Read some manga from nettruyen
2. Read chapter

### Expected behavior
Read chapter

### Actual behavior
app say "Reload"

**Comment by SnakeDoc83** [comment]
The source is messing with their website, recently they were forwarding to a new domain, now they changed CMS.  They have a currently more stable version called NhatTruyen in the WP-Comics extension.
