### ISSUE TITLE
Vietnamese Source

### ISSUE THREAD

**Issue by ThangBK2009** [inorichi/tachiyomi-extensions#29]
I added

**Comment by j2ghz** [comment]
(CATALOGUE) SOURCE REQUESTS: One source per issue, create more issues if you have more websites Check for duplicates, use search (in issues, not the global one) Put the name of the site as Title, replace this text with clickable link to the site

**Comment by inorichi** [comment]
Closing issues that do not follow the guidelines. Feel free to open a new one that complies with them.
