### ISSUE TITLE
[Meta] Kissmanga is broken and/or you are IP banned

### ISSUE THREAD

**Issue by CarlosEsco** [inorichi/tachiyomi-extensions#2909]
Kissmanga has decided to start IP banning people for using Tachiyomi aka not viewing their ads.
The extension since then has broken and there are no plans to maintain this extension anymore.

Migrate your manga to a new source

**Comment by vu1canic** [comment]
So, by somehow making my own working version there is no way to contribute?

**Comment by CarlosEsco** [comment]
Assuming it's.com the others are fake and you can prove that you don't get IP banned then it's possible message me on the discord channel
