### ISSUE TITLE
[MangaDex] Some kind of JSON parsing error

### ISSUE THREAD

**Issue by BlackSynder** [inorichi/tachiyomi-extensions#291]
[Getting this error](https://i.imgur.com/gG3hiMn.png)

**Comment by CarlosEsco** [comment]
K will look into when I got a chance

**Comment by bbtora** [comment]
I got this error too. 

![screenshot_2018-04-13-12-09-48-756_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/23010526/38720397-bca3c516-3f13-11e8-8b8d-2424cd3bc517.png)

**Comment by Ramon20000** [comment]
Same stuff.
![image](https://user-images.githubusercontent.com/37456831/38730714-03c4ba48-3eee-11e8-9786-6bdf1aeb001c.png)

**Comment by CarlosEsco** [comment]
issue was resolved on mangadex end
