### ISSUE TITLE
[Source Request] Manga Zip [AR]

### ISSUE THREAD

**Issue by dzotaku66** [inorichi/tachiyomi-extensions#2916]
### Other Details
Manga zip is an Arabic source which contains Manga, manhwa and manhua series
Please add it. (^^)
Check it here :  
https://mangazip1.blogspot.com/?m=0

**Comment by E3FxGaming** [comment]
I don't speak Arabic, but after taking a look at this with the google translator I'd say this is one of the sources we can't add.

- They claim to provide chapters in batches as zipped mediafire downloads.
- I didn't find any download links

The Tachiyomi extensions I've worked with so far do web scrapping to pull manga pages from websites. I haven't seen a single extension that downloads an archive from a file sharing website, unpacks the archive and makes use of the archive content to parse it into readable manga.

I'd also say it's a little bit of a security risk to download who knows what from a file sharing website.

With web scraping we basically rely on finding links to pictures on websites, pictures which are fairly safe to download and display. The content of downloaded archives on the other hand shouldn't be trusted. In the best of the worst cases it just doesn't work, in the worst of the worst cases we put something malicious on people's phones.
