### ISSUE TITLE
[Source Request] Black Hat Team [AR]

### ISSUE THREAD

**Issue by dzotaku66** [inorichi/tachiyomi-extensions#2918]
#2472 # Source Website
Website can be found at **put website URL here*http://blackhateam1.blogspot.com/?m=1*.
### Other Details
Black hat is a blog which contains a lot of manga series
Add it please ^_^

**Comment by AbdullahM0hamed** [comment]
Issue already exists for this: https://github.com/inorichi/tachiyomi-extensions/issues/2646
