### ISSUE TITLE
[Bug] LectorManga : Pages not loading

### ISSUE THREAD

**Issue by MerradOklom** [inorichi/tachiyomi-extensions#2927]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 4/6/7.1

### Source information
* Source name: LectorManga
* Source extension version: 1.2.11

## Steps to reproduce
1. Select a chapter
2. Wait for the pages to load

### Expected behavior
Pages load normally

### Actual behavior
Pages aren't loading, wild Retry button appears

### Other details
Extension
![Picture_20200429_100805](https://user-images.githubusercontent.com/43864503/80600555-f26cb680-8a02-11ea-8f12-3999ecef96c4.png)

Website
![Picture_20200429_100619](https://user-images.githubusercontent.com/43864503/80600610-07e1e080-8a03-11ea-843c-e9a4cb52d8da.png)

**Comment by arkon** [comment]
Closing in favour of #2714
