### ISSUE TITLE
[Bug] manganelo source : downloads renamed and missing in chapter list

### ISSUE THREAD

**Issue by Crzyadian** [inorichi/tachiyomi-extensions#2930]
Bug
App version r2190
Manganelo extensions version: mangabox 1.2.20
Android version 7.1.2

When I refresh the chapters in my manganelo library 
It renamed a few chapters in folder 
And they went missing/show as undownloaded in chapter list

 ![](https://i.imgur.com/1hLk14h.png)![](https://i.imgur.com/z2lEtB5.png)

**Comment by SnakeDoc83** [comment]
I think this would be due to nelo re-uploading those chapters.

**Comment by Crzyadian** [comment]
Actually this might be due to the preview app
 Cause I got the same error with mangadex too

**Comment by CarlosEsco** [comment]
If chapter names change then downloads are going to be not seen.

**Comment by Crzyadian** [comment]
They are shown in folder
But not in chapter list
And they add to download count

**Comment by Crzyadian** [comment]
Also I saw this error with Manga dex too maybe it was due too preview app

**Comment by CarlosEsco** [comment]
yea they show in the folder cause the name of the chapter changed from when you downloaded them to where they are now.  just edit the downloaded folder using a file explorer to match the current chapter names

**Comment by Crzyadian** [comment]
I'll do that now
And
If it happens with j2k or not

**Comment by CarlosEsco** [comment]
it happens with every version of tachiyomi.  If a source renames the chapter its considered removed

**Comment by Crzyadian** [comment]
I tested with j2k,it works fine with it 
Just the preview built was giving that error

**Comment by arkon** [comment]
Preview (and stable) only use the chapter name for the downloads. This would imply they had a chapter named that at one point.

This seems to be working as intended.

**Comment by Crzyadian** [comment]
Well it might my device specific
Or maybe just happened that one time I guess
Anyway I'm gonna stay on j2k 
And wait for md2 i guess
