### ISSUE TITLE
[Feature Request] Custom Source: FoolSlide

### ISSUE THREAD

**Issue by brettcol** [inorichi/tachiyomi-extensions#2935]
### What feature should be added to this source?
Would it be possible to add to the FoolSlide extension (eu.kanade.tachiyomi.extension.all.foolslide) an option to add custom sources?

For example, I run my own Foolslide instance on shared hosting for my own reading - and would like to use Tachiyomi to read it while on my phone. 

Thank you.

**Comment by SnakeDoc83** [comment]
Have you looked in to LANraragi or Komga?  Both have extensions for Tachi.  You'd just have to setup a server using their applications instead of a FoolSlide server.
