### ISSUE TITLE
[Source Request] Fan Fox (based on MangaFox)

### ISSUE THREAD

**Issue by shashank-p** [inorichi/tachiyomi-extensions#2936]
## Source Website
https://fanfox.net/

### Other Details
has a good number of manga it will give users more options to read manga. as it's not official i think we can add it to tachiyomi.

**Comment by SnakeDoc83** [comment]
It used to be an extension but was removed.

**Comment by CarlosEsco** [comment]
It was removed as the site was becoming to hard to attempt to maintain
