### ISSUE TITLE
[Source Request] https://onepiece-online-manga.com/

### ISSUE THREAD

**Issue by ArunMistry** [inorichi/tachiyomi-extensions#2937]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.8.5)
- I have updated all extensions
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/inorichi/tachiyomi
- I have searched the existing issues for duplicates
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions/

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

### Source Website
Website can be found at **put website URL here**.

**Comment by CarlosEsco** [comment]
May I ask why?  Usually we don't add single comic extensions unless they are from the scanlator themselves or originals.  This can be found on any aggregator.

**Comment by SnakeDoc83** [comment]
MangaKomi (in Madara) has it.

**Comment by ArunMistry** [comment]
Most  aggregators don't have updated versions, and are heavily lagging behind. But I have found MangaLife(EN) that does have it. Sorry to open this issue prematurely.
