### ISSUE TITLE
Extension Request: Manga Byte

### ISSUE THREAD

**Issue by lzypnda** [inorichi/tachiyomi-extensions#2940]
Extension Request: Manga Byte

Edit: link [https://mangabyte.com/](https://mangabyte.com/)

**Comment by SnakeDoc83** [comment]
Bruh, if you can't even be bothered to include a link....

**Comment by lzypnda** [comment]
> Bruh, if you can't even be bothered to include a link....

Sorry Bruh, I didn't know, this is the first time I've used GitHub and made a request.
