### ISSUE TITLE
 [Bug]Lector Manga : Not Loading list and not update manga chapters(Spanish)

### ISSUE THREAD

**Issue by faritvidal** [inorichi/tachiyomi-extensions#2952]
### Device information
* Tachiyomi version: "v8.4.5-EH"
* Android version: "6.0" and "9.0.17" and "10" and "Fire HD 8"

### Source information
* Source name: Lector Manga
* Source extension version: 1.2.11

## Steps to reproduce
1. Download App
2. Install extension "Lector Manga"
3. Try to open any manga from that source

### Expected behavior
Manga not load pages
Manga Library

### Actual behavior
Nothing is working

### Other details
Downgrade extension, recovery function off update library extension "1.2.10" bout not avaible to read manga.

**Comment by MerradOklom** [comment]
This has been already reported #2927
