### ISSUE TITLE
[Bug] Mangapark : Sources Bug

### ISSUE THREAD

**Issue by JennieGucci** [inorichi/tachiyomi-extensions#2956]
### Device information
* Tachiyomi version: Preview r2210 (e2a9c095)
* Android version: Android 10 (realme x2 pro with realme ui v1.0, and android 10)

### Source information
* Source name: Mangapark 
* Source extension version: 1.2.12

## Steps to reproduce
1. First Step : I go to Browse > Extensions > Mangapark > Details > Chapter List Source > Prioritize Source: Rock
2. Second Step : I Browse Mangapark's mangalist and download the chapters

### Expected behavior
I expected that I only see Rock Source

### Actual behavior
This happens instead, I see every chapters from all sources available to mangapark. Duck, Rock, Mini, Fox, etc. Instead of seeing one.

### Other details
Everytime I prioritize not just rock but other sources available to mangapark, it still shows all, I already cleared cache and it doesn't work. Hope you could fix this asap.
![1](https://user-images.githubusercontent.com/54570455/80793347-7b354f00-8bc9-11ea-805f-fe321767fa00.jpg)
![2](https://user-images.githubusercontent.com/54570455/80793357-80929980-8bc9-11ea-9de1-9abd05a037e0.jpg)

**Comment by CarlosEsco** [comment]
After you change do you swipe the chapter list to refresh?

**Comment by JennieGucci** [comment]
> After you change do you swipe the chapter list to refresh?

Yes. I also tried cclear cache or close Tachiyomi and then open. It has been happening for 3 days now.

**Comment by CarlosEsco** [comment]
I just verified and it works fine. Change the source and in the manga you need to swipe refresh the chapter list. The reason being is the chapters are stored in db and do not clear when you change the prioritization.

**Comment by CarlosEsco** [comment]
Also if prioritizes that type not shows only. For example if there is not chapter of Panda for a manga but there is for fox. It will still show the fox one.

**Comment by JennieGucci** [comment]
It works n

> Also it prioritizes that type not shows only. For example if there is not chapter of Panda for a manga but there is for fox. It will still show the fox one.

It works now. Thank you!
