### ISSUE TITLE
[Meta] Remove JuinJutsuReader

### ISSUE THREAD

**Issue by CarlosEsco** [inorichi/tachiyomi-extensions#2958]
Italians hate Tachiyomi

**Comment by AbdullahM0hamed** [comment]
F

**Comment by Asdamp** [comment]
Why it was removed? It was perfectly working, and so useful

**Comment by arkon** [comment]
As requested.

**Comment by Asdamp** [comment]
Requested by JuinJutsu? So basically if a source requests a remove, it's removed? There's nothing we can do about it? 
Because I feel a lot of sources don't want a tachiyomi extension, there will be a lot of removal request

**Comment by CarlosEsco** [comment]
Take it up with them.

**Comment by Asdamp** [comment]
I'm not blaming you, just to be clear. You all do an amazing job.

**Comment by ToroLoco94** [comment]
False. Italy love tachiyomi. Thank you so much tachiyomi's devs for your job 💚🤍❤️
