### ISSUE TITLE
[Mangadex] Searching for non or only R18+ manga will results as first page loop

### ISSUE THREAD

**Issue by atmazzerexe** [inorichi/tachiyomi-extensions#296]
Extension Version: 1.2.18
Tachiyomi Version: 0.7.2-1397
OS: Android 5.1
How to Reproduce:
[Video](https://my.mixtape.moe/eusoud.mp4).
(The manga addition to library are only for marking purpose to show where it's looping)

The bug will occur for both non-R18+ and R18+ only search.

**Comment by Vesnyx** [comment]
There's another bug that may be linked with this. Tachiyomi says something along the lines of

"Attempt to invoke virtual method 'java.lang.String..." when I try to search on the MangaDex extension.

**Comment by CarlosEsco** [comment]
@Vesnyx what version are you using. Paging issue I knew but this one I haven't heard before

**Comment by Vesnyx** [comment]
Well, I was on r1397 on Lollipop (5.0) using extension version 1.2.18. 

For some reason, I'm no longer getting that string error, but now I'm getting no results found for anything.

**Comment by CarlosEsco** [comment]
Can you verify you aren't IP banned by going to the browser and then mangadex website

**Comment by Vesnyx** [comment]
Yep, works fine in browser. I also tried clearing cookies, but the issue persists.

**Comment by CarlosEsco** [comment]
I would go on discord and ask support
