### ISSUE TITLE
Turkısh manhwa site 

### ISSUE THREAD

**Issue by Nurullahgrlk** [inorichi/tachiyomi-extensions#2962]
**PLEASE READ THIS**
Please add this site to the application
https://mangawow.com/manga-tag/manhwa-oku/?m_orderby=rating

**Comment by Agayev033** [comment]
Bro. MangaWow added Tachiyomi.

**Comment by Agayev033** [comment]
Kardeşim MangaWow çoktan eklendi Tachiyomiye. Eklentilerden Madara eklentisini indir onda var. Ve bu yazıyı kapatirsan sevinirim :)

**Comment by AbdullahM0hamed** [comment]
As it already exists, this should be closed.
