### ISSUE TITLE
[Bug] MyReadingManga : Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by AshLynAsh** [inorichi/tachiyomi-extensions#2969]
### Device information
* Tachiyomi version: Stable 0.9.1
* Android version: 5.1

### Source information
* Source name: MyReadingManga
* Source extension version: 1.2.33

## Steps to reproduce
1. Browse
2. Sources
3. Latest/Browse

### Expected behavior
This should have happened: show available manga latest updates

### Actual behavior
This happens instead: java.lang.Exception: Failed to bypass Cloudflare

**Comment by SnakeDoc83** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/3475
