### ISSUE TITLE
[Bug] Not Exact Chapters - 1stkiss, Mangatoon

### ISSUE THREAD

**Issue by ChristianCarvs** [inorichi/tachiyomi-extensions#2972]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.8.5)
- I have updated all extensions
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/inorichi/tachiyomi
- I have searched the existing issues for duplicates
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions/

---

###  Why/Project's Benefit/Existing Problem
(explain why this should be added)
The problem of the other sources is broken or fast forward manga chapters like ive read today im reading Apotheosis but many chapter are missing others are moving forward that shouldent have not exact chapter episodes

**Comment by ChristianCarvs** [comment]
i read chapter 325 but when in chapter 326 it change not continue in the exact chapter

**Comment by arkon** [comment]
You didn't mention what source this is. Did you check their website?

**Comment by ChristianCarvs** [comment]
> You didn't mention what source this is. Did you check their website?

ohh sorry i forgot to add, its 1stkiss and Mangatoon yeahh i already visit their sites but it completely fine their

**Comment by hjdrm** [comment]
Mangatoon chapters differ from scanalation counter part

**Comment by SnakeDoc83** [comment]
What's the issue? Is it that what's on 1st Kiss's website doesn't match what's shown in Tachi or that what's on 1st Kiss doesn't match what's on Mangatoon?

**Comment by ChristianCarvs** [comment]
maybe the source link have an issues, sometimes i cant access

**Comment by ChristianCarvs** [comment]
> What's the issue? Is it that what's on 1st Kiss's website doesn't match what's shown in Tachi or that what's on 1st Kiss doesn't match what's on Mangatoon?

sometimes the chapter i read has an another chapter appearing from another source

**Comment by SnakeDoc83** [comment]
So, as an example, you might be reading chapter 1 of some manga on 1st Kiss and you can tell it's from Mangatoon because it's watermarked by them but then you go to chapter 2 and it's not from Mangatoon?

**Comment by samanta-widjaja** [comment]
There's even a case where like chapter 67 and 68 is the same (chapter 67). But even in the web is the same.

**Comment by arkon** [comment]
Sounds like the source has issues.
