### ISSUE TITLE
[Bug] Mangakakalot : Latest Mangas don't load 

### ISSUE THREAD

**Issue by Milkyboo** [inorichi/tachiyomi-extensions#2977]
Whenever I open up on latest, I'm unable to scroll past more than just a few mangas. Before the update, I was able to scroll indefinitely. 

### Device information
* Tachiyomi version: 0.9.1
* Android version: 8.0.0

### Source information
* Source name: Mangakakalot
* Source extension version: 1.2.20

### Expected behavior
Scroll through as much mangas as wanted. 

### Actual behavior
Unable to scroll past after just a few mangas.

**Comment by SnakeDoc83** [comment]
It's a source issue, their website is acting wonky again. Sometimes their pages load, sometimes they don't.

**Comment by SnakeDoc83** [comment]
@arkon This can be closed.
