### ISSUE TITLE
[Bug]Mangaleno source not working on Mangabox extension.

### ISSUE THREAD

**Issue by Sajeeb97** [inorichi/tachiyomi-extensions#2978]
### Device information
* Tachiyomi version: 
 0.9.1
* Android version: 
8.1 oreo

### Source information
* Source name: Manganelo
* Source extension version: Mangabox 1.2.20

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
It should load

### Actual behavior
It doesnt load

### Other details
![Screenshot_Tachiyomi_20200503-000816](https://user-images.githubusercontent.com/62636945/80872393-28c76180-8ca1-11ea-82cb-7bd8a852d538.png)
![Screenshot_Tachiyomi_20200503-000823](https://user-images.githubusercontent.com/62636945/80872398-35e45080-8ca1-11ea-8be0-8b0a8b956de5.png)
Manganelo web is working fine.But on the app it shows no result.

**Comment by SnakeDoc83** [comment]
This is also a source issue, the page being scraped wasn't loading manga.  It's working now but may occur again (the MangaBox sources have been unstable recently).
