### ISSUE TITLE
[MangaDex] Non-Adult Pre-Filter

### ISSUE THREAD

**Issue by Vesnyx** [inorichi/tachiyomi-extensions#298]
Right now, the browse page displays all results, adult included. I'd personally prefer to not have to see this and go through the sidebar search everytime, so i wanted to request an option that allows us to set the parameter for this. The dropdown on the side also causes a search, which doesn't support the same infinite scroll that is on the main page.

**Comment by CarlosEsco** [comment]
Not possible until extensions can use properties

**Comment by CarlosEsco** [comment]
https://www.strawpoll.me/15527485
