### ISSUE TITLE
[Source Request] Nani?

### ISSUE THREAD

**Issue by TigerUppercut** [inorichi/tachiyomi-extensions#2981]
With the MangaCards extension being removed, there is no longer a source for Nani? Scans. Can someone please add it in to theirs?

### Source Website
https://naniscans.xyz/

Thanks!

**Comment by SnakeDoc83** [comment]
It's on my todo list but for now you can read them on MangaDex. There's a 24 hour delay, but that's not too bad to live with in the meanwhile.
