### ISSUE TITLE
[Bug] MangaDenizi - Not Showing Chapters and thumbnails

### ISSUE THREAD

**Issue by Agayev033** [inorichi/tachiyomi-extensions#2983]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.9.2)
- I have updated all extensions
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/inorichi/tachiyomi
- I have searched the existing issues for duplicates
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions/

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

### Device information
* Tachiyomi version: Preview
* Android version: 10

### Source information
* Source name: MangaDenizi
* Source extension version: 1.2.1

## Problem
![Screenshot_20200503-041853](https://user-images.githubusercontent.com/30019351/80895399-91d8c480-8cf5-11ea-9ba3-d499ab6cd2a1.png)
![Screenshot_20200503-041916](https://user-images.githubusercontent.com/30019351/80895409-9a30ff80-8cf5-11ea-993a-6ac3a0f75223.png)

**Comment by AbdullahM0hamed** [comment]
I've downloaded 0.9.2 to compare and all the covers are broken (as compared to only some breaking in J2K).

I am however unable to reproduce unable to reproduce the Unparseable date issue with the same manga.

**Comment by Agayev033** [comment]
![Screenshot_20200503-044255](https://user-images.githubusercontent.com/30019351/80895683-96eb4300-8cf8-11ea-894b-d40727ae63f7.png)
Tachiyomi Version : 0.9.2

**Comment by AbdullahM0hamed** [comment]
That's strange, it works fine for me:
![Screenshot_20200503-014515_Tachiyomi](https://user-images.githubusercontent.com/25087116/80895726-e2452780-8cdf-11ea-8e73-65f8236fb61f.jpg)

**Comment by Agayev033** [comment]
Says Unparseable fare :(

**Comment by Agayev033** [comment]
Date

**Comment by SnakeDoc83** [comment]
@AbdullahM0hamed You probably need to add a Locale to SimpleDateFormat. Each of you have a different locale that the device is assuming because it wasn't set in the code; your locale works but his causes an error.  And in `mangaDetailsParse` the thumbnail should be made absolute.
