### ISSUE TITLE
[Feature Request] be able to select all mangas and Mark them as read 

### ISSUE THREAD

**Issue by nekoboy69** [inorichi/tachiyomi-extensions#2985]
As far as I can see there is no way to select the mangas and mark them all read I can do it to each of the mangas one by one but that is very annoying and long process to do

**Comment by Ksetrar** [comment]
This is already added in newer version

**Comment by CarlosEsco** [comment]
Wrong repo and selecting all in library view it not being added

**Comment by nekoboy69** [comment]
If I picked a manga chapters yes but I’m not able to do it with each and every mangas when I select all my mangas that I have
