### ISSUE TITLE
[Bug] Mangakakalot Extension 

### ISSUE THREAD

**Issue by Ksetrar** [inorichi/tachiyomi-extensions#2986]
### Device information
* Tachiyomi version: Latest
* Android version: Oreo 

### Source information
* Source name: mangakakalot
* Source extension version: mangakakalot

## Issue
Sometimes it shows white page and now showing more manga

White Page
https://1drv.ms/v/s!AqxLXy2e8tMWl2TC_QxF7rT9qtwk?e=CdlE2t

Manga not showing [scrolling down issue]
https://1drv.ms/v/s!AqxLXy2e8tMWl2HlKJx2mibRBsk-?e=U3PBwC

**Comment by SnakeDoc83** [comment]
This is a source issue. The site is unstable and sometimes doesn't return results.

**Comment by Ksetrar** [comment]
But it the white page was not coming before the major update
