### ISSUE TITLE
[Bug] Source Name : HentaiVN

### ISSUE THREAD

**Issue by Sehai1** [inorichi/tachiyomi-extensions#2987]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.9.2)
- I have updated all extensions
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/inorichi/tachiyomi
- I have searched the existing issues for duplicates
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions/

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

### Device information
* Tachiyomi version: 0.9.2
* Android version: 9

### Source information
* Source name: HentaiVN
* Source extension version: 1.2.5

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened

### Actual behavior
This happens instead

**Comment by arkon** [comment]
Didn't even describe the bug.
