### ISSUE TITLE
Sources Request

### ISSUE THREAD

**Issue by JudiciousVick** [inorichi/tachiyomi-extensions#2988]
### Device information
* Tachiyomi version: latest
* Android version: 9
* Device: Oneplus 6t

### Source information
* Source name: ?
* Source extension version: ?

## Steps to reproduce
1. First step
2. Second step

## Issue/Request
Expansion Request For Isekaiscans , It has many manga and it is fast

## Other details
Additional details and attachments.

**Comment by SnakeDoc83** [comment]
Already a part of Madara.
