### ISSUE TITLE
[Source Request] Google Drive

### ISSUE THREAD

**Issue by Zhonecage** [inorichi/tachiyomi-extensions#2989]
Hello, how do you like the idea of adding Google Drive support to Tachiyomi? This is for people who want to read their own manga collection but don't have much space in their phones to store them locally.
Basically you create a manga folder somewhere in your google drive and Tachiyomi treats that folder like if it was a website and reads manga from it.

Thank you for your consideration.

**Comment by CarlosEsco** [comment]
wrong thread and not planned. Use a file explorer that has sync built in

**Comment by Zhonecage** [comment]
How is the thread wrong? I was forwarded here from **your very own** extensions request section https://tachiyomi.org/help/faq/#general

Using a file explorer with sync built in works differently than reading manga from own external sources because using a file explorer with sync built in **downloads** the manga first, which **defeats the point** of an online manga reader.

**Comment by CarlosEsco** [comment]
This is for extension issues. You should be opening app issues on the GitHub app page. And I will just close it there to cause there are no plans for this feature

**Comment by Zhonecage** [comment]
Well, keep closing then. Thanks anyways.

**Comment by CarlosEsco** [comment]
you can follow along here 
https://github.com/inorichi/tachiyomi/issues/912
