### ISSUE TITLE
[Bug] Japscan : Pages not loading

### ISSUE THREAD

**Issue by Cripix** [inorichi/tachiyomi-extensions#2990]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 10

### Source information
* Source name: Japscan 
* Source extension version: 1.2.20

## Steps to reproduce
1. Select a chapter
2. Wait for the pages to load

### Expected behavior
Pages load normally

### Actual behavior
Pages aren't loading, wild Retry button appears

**Comment by arkon** [comment]
#2535
