### ISSUE TITLE
[Bug] ItaScan

### ISSUE THREAD

**Issue by raffybest94V01** [inorichi/tachiyomi-extensions#2995]
simple itascan site is down = impossible to see, i know in italy language you put the "mangaeden" but is not update good ( not the extension i mean the site is slow and force to log-in to see some manga ) can you please replace itascan extension with https://mangaworld.tv ? thanks a lot for you'r jobs, but for italy language is a little impossible to read =(

**Comment by AbdullahM0hamed** [comment]
> can you please replace itascan extension with https://mangaworld.tv ?
#2800
