### ISSUE TITLE
[Catalogue] Adding request: French sources

### ISSUE THREAD

**Issue by Eeveel** [inorichi/tachiyomi-extensions#3]
Hi,
Can you add some French sources?
Here some sources:
scan-manga.com
japscan.com
manga-sanctuary.com
mangaKawaii.com
mangapedia.fr
mymanga.io

Thanks ;)

**Comment by Horoneru** [comment]
Hey ! 
I'm thinking of adding some of these sources. Did you check the source of the existing catalogs implementation to see if you can add them yourself ? 
I'll try japscan.com as it was already requested by a collaborator of the french translation that I initiated. Will see about the others later. Check back pull requests in a few days !

**Comment by Horoneru** [comment]
After some checking done on the existing implementations and the french websites, here's what I found.
Unfortunately, Japscan doesn't support cover pictures. Only the featured mangas have those, and even then there's only 5 "hot" mangas available, so a popularMangaRequest is also out of the question. 
That would mean that some features wouldn't be available on that source, which could mean working on a better source would be the best solution overall IMO.
Still, if there's still a demand, we'll see. 
As for the other sources, well, manga-sanctuary seems to use flash (ugh) for reading and doesn't seems to be a reading source per-se, so it seems troublesome...

I'm currently looking into mymanga and mangaKawaii as these seem the most complete sources while being the (subject to change) easiest to parse.
Mangapedia seems like a possible option too.
Will certainly contribute to the doc/how-to if I successfully add these sources, too, so people can continue contributing.
What are your thoughts ? @Eeveel , @M2ck

**Comment by Eeveel** [comment]
Mymanga and mangaKawaii are very complete sources, Any news for this implementations? I can try to implement this with th doc/howto but I not verry fluence in comuting or programming! but I will take a try!

**Comment by Horoneru** [comment]
Yes, that's what I found. I'm working slowly on MangaKawaii.
If anyone wants me to push the fork early, just tell me :)

**Comment by meradoou** [comment]
Hello,
[mangapedia.fr](http://mangapedia.fr)

**Comment by inorichi** [comment]
Closing issues that do not follow the guidelines. Feel free to open a new one that complies with them.
