### ISSUE TITLE
[Bug] Italy scan

### ISSUE THREAD

**Issue by raffybest94V01** [inorichi/tachiyomi-extensions#3004]
in italy language we have only 2 extensions right now for manga ( not hentai, hentai work good xD )

ItaScan is completly down by the owner site, you can check on the website

the another is "MangaEden" but not all working good, so many manga give the error

"Page list is empy"

because mangaeden requires a login to view the content

and please don't close this report, I don't know if I did well to report it correctly saying it is a bug, I kindly ask you only to add at least other sources for the Italian language for normal manga ( because hentai source work good )

**Comment by CarlosEsco** [comment]
Please provide a specific site.  If there is more than 1 open an issue for each one.  I will not close this but edit it to be a specific request

**Comment by raffybest94V01** [comment]
itascan extension I think it refers to the only site currently closed ( https://itascan.info ) in fact when you try to open any manga you get cartoons that say to buy the manga

maybe you can replace itascan for https://mangaworld.tv  it's free, no login request or other similar things

**Comment by AbdullahM0hamed** [comment]
#2800 
> https://mangaworld.tv

**Comment by CarlosEsco** [comment]
Closing open an issue with a valid website that wasn't removed
