### ISSUE TITLE
Foolslide issue

### ISSUE THREAD

**Issue by CarlosEsco** [inorichi/tachiyomi-extensions#301]
@null-dev 

http://mangaichiscans.mokkori.fr  

Browse and latest doesnt work

everything else does

**Comment by NerdNumber9** [comment]
Hmm, I can't replicate this issue. Does it work when you visit the web page in your phone's browser?

**Comment by null-dev** [comment]
Hmm, I can't replicate this issue. Does it work when you visit the web page in your phone's browser?

**Comment by xChickens** [comment]
This is a pretty late bump, but I was checking some individual FoolSlide sources and this also occurs for me on browse and latest on the latest Tachiyomi version.

**Comment by einstein95** [comment]
Doesn't occur for me

**Comment by CarlosEsco** [comment]
Maybe it's location based?

**Comment by SnakeDoc83** [comment]
This can be closed, they no longer have a site.
