### ISSUE TITLE
[Source Request] Mangatoon

### ISSUE THREAD

**Issue by shashank-p** [inorichi/tachiyomi-extensions#3013]
### Source Website
- Name: Mangatoon
- Link: https://mangatoon.mobi/
- Language(s): EN

### Other Details
I checked in extensions sheet couldn't find it so requesting to be added

**Comment by SnakeDoc83** [comment]
It has its own extension.  Note: you can only read their free chapters, not their locked ones.

**Comment by shashank-p** [comment]
I found extension.
