### ISSUE TITLE
[bug] team x download error 

### ISSUE THREAD

**Issue by Natsu-raw** [inorichi/tachiyomi-extensions#3015]
Device information
• Tachiyomi version: 1.0.2
• Android version: 10
• Device: xiaomi mi 8

Steps to reproduce
1. Choose chapter to download
2. Start the download

Expected behavior

The download should start without any problems

Actual behavior

I Get the error message after just under a second " Expected URL scheme 'http' or 'https' no colon was found"

Manhwa: master of gu ch 93

**Comment by shipoxx** [comment]
Me to
Also manga.ae (مانغا العرب) Change his domain name

**Comment by arkon** [comment]
#2975
