### ISSUE TITLE
[Source Request] Onma (Arabic)

### ISSUE THREAD

**Issue by shipoxx** [inorichi/tachiyomi-extensions#3018]
### Source Website
- Name: onma ( مانغا اونلاين = manga online)
- Link: https://onma.me
- Language(s): Arabic

### Other Details
This website is like gmanga he so famous and have big library.
+ They have a app in Play store, but his so bad ^^
Link: https://play.google.com/store/apps/details?id=zxc.laitooo.onmanga

**Comment by SnakeDoc83** [comment]
It's in the My Manga Reader CMS extension.

**Comment by shipoxx** [comment]
> It's in the My Manga Reader CMS extension.

But, it's not working (i open webview to)

**Comment by AbdullahM0hamed** [comment]
@shipoxx then you should label it as bug instead of source request, and fill out the bug report template.

**Comment by shipoxx** [comment]
Update: i change my IP address and it's working now!
