### ISSUE TITLE
option to toggle off R18 content in mangadex catalogue

### ISSUE THREAD

**Issue by uenoshita** [inorichi/tachiyomi-extensions#302]
BUGS:
Version 1397
Feature request to have mangadex extension have an option to toggle R18 content from it's catalogue as default. It's annoying looking in the catalog then suddenly beeing shown a futa dick while in public.

**Comment by CarlosEsco** [comment]
Not possible currently without extensions supporting properties.  I'm closing this but will open a poll today and let users vote if they want show all or show none by default.  An easy solution for you though is switch to list view for browsing for now

**Comment by CarlosEsco** [comment]
https://www.strawpoll.me/15527485

**Comment by drac0300** [comment]
hum, sorry if I am wrong, but 
https://github.com/inorichi/tachiyomi/issues/1007
and the presence of app/src/main/java/eu/kanade/tachiyomi/source/ConfigurableSource.kt
made me think properties for extensions were already implemented… are they not ?
