### ISSUE TITLE
[Source Request] ohmanhua.com

### ISSUE THREAD

**Issue by samanta-widjaja** [inorichi/tachiyomi-extensions#3022]
### Source Website
- Name: ohmanhua.com
- Link: www.ohmanhua.com
- Language(s): Chinese, i think

**Comment by SnakeDoc83** [comment]
Same CMS as onemanhua. Not sure if it's their new domain or they just share the same CMS.

**Comment by samanta-widjaja** [comment]
I don't know about that. But I can't reach onemanhua at all

**Comment by manga98** [comment]
I think they have changed the website link! I used onemanhua login details is suscessful for ohmanhua login

**Comment by samanta-widjaja** [comment]
My friend say it's the same. They used the same login and it's worked
