### ISSUE TITLE
[Bug] LANraragi : Missing from Browse Source tab

### ISSUE THREAD

**Issue by MystifyingShadow** [inorichi/tachiyomi-extensions#3024]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 10

### Source information
- Name: LANraragi
- Extension version: 1.2.1

## Steps to reproduce
1. Add Extension
2. Open Browse Tab

### Expected behavior
There should be a source for LANraragi on the Sources tab.

### Actual behavior
The LANraragi source is missing from the Sources tab.

**Comment by arkon** [comment]
You need to enable it from the "All" section in the filters section (top right 3 lines icon).

**Comment by raining1123** [comment]
> You need to enable it from the "All" section in the filters section (top right 3 lines icon).

a bit strange... but it works after all !
