### ISSUE TITLE
[Feature Request] Tapas: provide configuration for login

### ISSUE THREAD

**Issue by igalic** [inorichi/tachiyomi-extensions#3026]
with  #1852 we have added an icon indicating whether a chapter on Tapas is 🔒 locked.

Locked, except for paying members that is.

so it would be nice to provide configuration options to unlock those chapters by logging in

**Comment by AbdullahM0hamed** [comment]
Question out of curiosity: Does logging in via webview currently not work?

**Comment by SnakeDoc83** [comment]
Also covered by #3202, as best as it can be. Set your extension preference, log in via webview, and try it out.
