### ISSUE TITLE
HentaiVN extension doesn't work

### ISSUE THREAD

**Issue by Sehai1** [inorichi/tachiyomi-extensions#3033]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 9
* Device: Xiaomi Mi 8 Lite

### Source information
* Source name: HentaiVN
* Source extension version: 1.2.5

## Issue/Request
The extension doesn't work but the webview still works

**Comment by SnakeDoc83** [comment]
In what way does it not work? It seems fine to me.

**Comment by Sehai1** [comment]
i only can read on webview. i want to download to read later

**Comment by SnakeDoc83** [comment]
Do you see manga when you're in the browse or latest view?  Do you see a chapter list when you go in to a manga?  Does the chapter fail to load when you open it?  Are you getting an error of some kind?  The more specific you can be the better.  I've checked a few manga and they load fine for me.  I can't keep opening random manga hoping to find where an error occurs.

**Comment by Sehai1** [comment]
It doesn't load anything.

**Comment by SnakeDoc83** [comment]
So you tap on browse and all you get is a blank screen--no manga, no error message, nothing?

**Comment by Sehai1** [comment]
If i find a manga on hentaivn extension, it still works but have no chapter

**Comment by SnakeDoc83** [comment]
Still can't reproduce this. You'll need to post a specific example, screenshots, or video.

**Comment by SnakeDoc83** [comment]
Don't need 3 open issues about the same thing. https://github.com/inorichi/tachiyomi-extensions/issues/3623
