### ISSUE TITLE
Team X pages not loading

### ISSUE THREAD

**Issue by redbayoub** [inorichi/tachiyomi-extensions#3037]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 7.0
* Device: huawei gr5 2017

### Source information
* Source name: Team X
* Source extension version: ?

## Steps to reproduce
1. First step
2. Second step

## Issue/Request
manga pages not loading

**Comment by SnakeDoc83** [comment]
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/2975

**Comment by redbayoub** [comment]
Didn't notice it, because it's not a feature request
