### ISSUE TITLE
[Bug] WP Manga : Kick me out app (Crashed)

### ISSUE THREAD

**Issue by shipoxx** [inorichi/tachiyomi-extensions#3039]
### Device information
- Tachiyomi version: 0.9.0
- Android version: 6.01

### Source information
- Name: mangaswat (WP Ex)
- Extension version:  1.2.8

#other details
• so i installed the extension, and open [mangaswat] in webreview then it's open.. but when i search or add manga to my library, tachiyomi kick me out and he stop work every time.!! I don't know what happened?

**Comment by shipoxx** [comment]
![Screenshot_2020-05-06-18-01-20](https://user-images.githubusercontent.com/61906880/81211903-96d29800-8fc3-11ea-9485-5cf46e3e0d50.jpg)

**Comment by shipoxx** [comment]
@CarlosEsco

**Comment by arkon** [comment]
Duplicate of #2711

**Comment by shipoxx** [comment]
> Duplicate of #2711

Not working i waiting for loading tum but it's close before!

**Comment by CarlosEsco** [comment]
Duplicate means the issue has already been reported.

**Comment by shipoxx** [comment]
I know @CarlosEsco 
But what's the solution? ^^
