### ISSUE TITLE
[Bug] Mangabox : Mangakakalot or/and manganelo

### ISSUE THREAD

**Issue by Riztard** [inorichi/tachiyomi-extensions#3045]
### Device information
- Tachiyomi version: Prev r2252 & J2K 1.0.2
- Android version: 9

### Source information
- Name: Mangakakalot
- Extension version: 1.2.20

## Steps to reproduce
1. browse mangakakalot/manganelo
2. for example search "Peerless Battle Spirit" 
3. open chapter 59 (older chapter seems fine)

### Expected behavior
shows chapter

### Actual behavior
not showing chapter

### Other details
it can be opened by web view

**Comment by Andryj98** [comment]
Mangabox extention won't load any images from sources and the chapters that are in library won't load any chapters

**Comment by LinhDoan1904** [comment]
I have the same issue with riztard. i cannot read any manga which is browsed from mangakakalot & manganelo starting from 15.30 pm this afternoon. But i can read normally on the web. 
![96101865_246409746578010_564640070296928256_n](https://user-images.githubusercontent.com/64967331/81309104-c4474080-90ac-11ea-8b23-59b5185213b5.jpg)
![96150308_243180513556945_2216353285382602752_n](https://user-images.githubusercontent.com/64967331/81309120-c7dac780-90ac-11ea-8114-81e0149446f6.jpg)
![96239729_1090049731367848_3039387792321806336_n](https://user-images.githubusercontent.com/64967331/81309125-c9a48b00-90ac-11ea-81e2-f1f78d1a03b2.jpg)
![96280965_2624600401089292_697187751803486208_n](https://user-images.githubusercontent.com/64967331/81309130-cb6e4e80-90ac-11ea-979b-0a66393c721d.jpg)

**Comment by benoit-decorte** [comment]
Hello,
I do have the same issue. Older chapter worked fine due to the chapter cache, and logically do not after a cache reset.
![Screenshot_20200507-191323_Tachiyomi](https://user-images.githubusercontent.com/61902954/81324298-0d8c9580-9097-11ea-9a85-6d533a115590.jpg)

**Comment by Fullfail** [comment]
It seems like every Chapter uploaded before 19.04. Cant be  read. I testet on several manga and it always happened that obly chapter uploaded on 19.04. Or after loaded earlier chapter didnt

**Comment by zhi-end** [comment]
Mangakaklot catalogue won't load any images from any manga. but it does show the thumbnails of the chapter or I can browse the chapters from webview but when trying to open it does not load any image and gets stuck in the retry button. I have checked others catalogues like manganelo works fine.  I have cleared cache, cookes. uninstalled and reinstalled, used vpn nothing seems to work.

**Comment by CarlosEsco** [comment]
There's an obvious issue no need for more responses unless the status has changed.

**Comment by sppoyw** [comment]
It also happened  to me. I tried to use mangadex, as an alternative siurce, fortunatelt the chapters load perfectly. Plsss fix this issue asap!

**Comment by gr8falcon** [comment]
Did anyone have solve the problem ??

**Comment by DaniFrost97** [comment]
The problem persists here

**Comment by Riztard** [comment]
@gr8falcon @DaniFrost97  update your MangaBox extension
