### ISSUE TITLE
[Bug] Union Mangás (Portuguese) : Chapter does not open for reading.

### ISSUE THREAD

**Issue by Deku2k** [inorichi/tachiyomi-extensions#3050]
### Device information
- Tachiyomi version: Stable 0.9.2
- Android version: 8.0.0

### Source information
- Name: Union Mangás (Portuguese)
- Extension version: 1.2.13

## Steps to reproduce
1. Open manga **Shijou Saikyou Orc-san no Tanoshii Tanetsuke Harem Zukuri**.
2. I select **Cap. 02 V2**.

### Expected behavior
Open the chapter for reading.

### Actual behavior
Chapter does not open for reading, with the error:
**Unable to resolve host "unionleitor.tophttps ": No address associated with hostname**

### Other details
Most of the chapters with problems are those that contain V2, V3 etc. In the name of the chapter.

On the original website, the webview works normally, now the extension is "Unable to resolve host "unionleitor.tophttps": No address associated with hostname".

**Comment by alessandrojean** [comment]
Will take a look!
