### ISSUE TITLE
HOW TO FIX THIS PROBLEM?? 

### ISSUE THREAD

**Issue by jassendy** [inorichi/tachiyomi-extensions#3053]
![Screenshot_20200507_215053](https://user-images.githubusercontent.com/64973805/81312571-5c4b2700-90b9-11ea-9253-4780a83aaa95.jpg)

**Comment by arkon** [comment]
#3045, probably. You provided no useful information.

**Comment by jassendy** [comment]
I dont get i, what do you mean no useful information?  😊

**Comment by jassendy** [comment]
> #3045, probably. You provided no useful information.

I dont get it, what do you mean no useful information?  😊
