### ISSUE TITLE
[Bug] Mangabox Extension : Download issues

### ISSUE THREAD

**Issue by KennenLernen** [inorichi/tachiyomi-extensions#3057]
### Device information
- Tachiyomi version:  0.92
- Android version: 9

### Source information
- Name: Mangabox
- Extension version: English 1.2.20

## Steps to reproduce
1. First Step: Add new Manga to Library
2. Second Step: Update

### Expected behavior
New Chapter Download

### Actual behavior

Page List is empty or
"Expected URL scheme "http" or "https" but no colon was found"

### Other details

WEBVIEW works

**Comment by CarlosEsco** [comment]
#3045
