### ISSUE TITLE
Error retry tachiyomi

### ISSUE THREAD

**Issue by gr8falcon** [inorichi/tachiyomi-extensions#3059]
The images are not clear instead these are blank and by opening manga chapter the error says retry

**Comment by CarlosEsco** [comment]
please provide more details

**Comment by gr8falcon** [comment]
![Screenshot_20200508-010756](https://user-images.githubusercontent.com/64985473/81337335-77716300-90c8-11ea-9d8c-13a93bb5fad8.png)

**Comment by gr8falcon** [comment]
![Screenshot_20200508-010808](https://user-images.githubusercontent.com/64985473/81337395-89530600-90c8-11ea-875c-58baa5223956.png)

**Comment by gr8falcon** [comment]
This is mostly on mangakakalot

**Comment by gr8falcon** [comment]
I have also tried the older version
The stable and preview version
And also tried it re-installing it..
But the problem doesn't solve

**Comment by arkon** [comment]
#3045

**Comment by gr8falcon** [comment]
@Riztard, thanx, for telling us, the manga are opening now, but the cover image of manga is still not showing..

**Comment by SnakeDoc83** [comment]
Clear your database in settings.

**Comment by gr8falcon** [comment]
Well, it still doesn't solved the problem..😣😣😔😔

**Comment by SnakeDoc83** [comment]
Are you talking about covers in the catalog or covers in your library?

**Comment by gr8falcon** [comment]
Cover in the library

**Comment by SnakeDoc83** [comment]
Oh, then refresh library metadata instead.

**Comment by gr8falcon** [comment]
Well, I have tried everything, I just again try it by re-installing..
It is a very amazing app, I just want to solve it, everything it takes..

**Comment by gr8falcon** [comment]
Wow, finally it's working, thanks everyone..

**Comment by Campstantine** [comment]
How did you get manga to open? Mine is stuck at retry

**Comment by barunaniket** [comment]
Same goes for me too with the extension mangalife and mangasee.......
Please suggest me how to resolve this error
