### ISSUE TITLE
[Bug] Source Name : i cant read its always showing retry or empty page list

### ISSUE THREAD

**Issue by nn21n** [inorichi/tachiyomi-extensions#3066]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.9.2)
- I have updated all extensions
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/inorichi/tachiyomi
- I have searched the existing issues for duplicates
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions/

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

### Device information
- Tachiyomi version: ?
- Android version: ?

### Source information
- Name: ?
- Extension version: ?

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened

### Actual behavior
This happens instead

**Comment by arkon** [comment]
You didn't fill out any of the required information.
