### ISSUE TITLE
[Source Request] El Goonish Shive

### ISSUE THREAD

**Issue by effcol** [inorichi/tachiyomi-extensions#3069]
### Source Website
- Name: El Goonish Shive
- Link: https://www.egscomics.com/
- Language(s): English

**Comment by effcol** [comment]
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/4599904/ic_launcher.zip)

Also, I made some icons for it that could be used for it and hopeful might be useful, unfortunately the rest is over my head.

**Comment by dawidsowa** [comment]
It's available in Hiveworks extension
