### ISSUE TITLE
[Bug] goldenmangas : Numbers instead of Title

### ISSUE THREAD

**Issue by nicker7** [inorichi/tachiyomi-extensions#3073]
Instead of the manga title appearing, its classification number appears.  Which is a line or two below the actual title, looking through the manga page on the website.

---

### Device information
- Tachiyomi version: TachiyomiJK2 1.0.2
- Android version: 9

### Source information
- Name: goldenmangas
- Extension version: 1.2.3

## Steps to reproduce
1. First Step
Go to the source Goldenmangas, then choose any random manga, and then add it to your library.

2. Second Step
Go to the library and look for the manga you added there.

### Expected behavior
The name of the manga should have appeared.
Example: Akumetsu

### Actual behavior
But instead, a classification number appears.  Example: #9.00 3 Votos

### Other details
Sometimes you don’t even need to add it to the library, just wait to load the information and it’s happening.

Causing new chapter notifications to appear in numbers instead of the title. Causing the migration to not work because of a mismatched title. Download lost in manual migration.

**Comment by alessandrojean** [comment]
I will take a look and try to fix it.
