### ISSUE TITLE
[Bug] Mangabox : Failed to bypass cloudfare/Page list is empty/Retry

### ISSUE THREAD

**Issue by aoiaoiaoi1** [inorichi/tachiyomi-extensions#3074]
### Device information 
- Tachiyomi version: v.1.0.2
- Android version: 6.0

### Source information
- Name: Mangabox (Mangakakalot, Manganelo, etc.)
- Extension version: 1.2.21

## Steps to reproduce
1. First Step
Open latest chap (page list is empty/retry)
2. Second Step
Refresh tracking/library metadata; clear cache/cookies. The same issue

### Expected behavior
This should have happened
That the chap will now fix

### Actual behavior
This happens instead
That i cant read any manga using source mangabox 
### Other details
I let myself loosen my reading habit for 3 days but i cant take it, it keeps me hanging please fix this please thank you.

**Comment by herrsa1** [comment]
I've been having this issue the past few days as well. my extension is on the latest update and so is tachiyomi

**Comment by aoiaoiaoi1** [comment]
Yes, but today i also have the same issues with Mangahasu. Please look up to it as well sir/maam. Thank yoyy

**Comment by aoiaoiaoi1** [comment]
Another problem with this extension again today..

**Comment by SnakeDoc83** [comment]
It kind of just is what it is. The MangaBox sources have been unstable the last month or so. You can weather the storm or use a different source but I haven't seen any issues directly caused by the extension itself.
