### ISSUE TITLE
[Bug] Source Name : Comicake

### ISSUE THREAD

**Issue by vipzzx** [inorichi/tachiyomi-extensions#3077]
### Device information
- Tachiyomi version: j2k 1.0.2. checked on 0.9.2 has the same issue
- Android version: Note9, Android 10

### Source information
- Name: ComiCake
- Extension version: 1.2.7

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Tap to open webview, will open to scanlation website directly to manga. Happens to LetItGo Scans, ProjectTime Scans, and WhimSubs.

### Actual behavior
error log

### Other details
[Screen_Recording_20200508-211945.zip](https://github.com/inorichi/tachiyomi-extensions/files/4602469/Screen_Recording_20200508-211945.zip)

**Comment by SnakeDoc83** [comment]
That's not an error log, that's JSON from the source's API.

**Comment by CarlosEsco** [comment]
Could probably have the 2 urls one for the website and one of the API that's used. I know a couple sources do that
