### ISSUE TITLE
[Bug] Mangakawaii: Can't load cover on browsing

### ISSUE THREAD

**Issue by Mitia99** [inorichi/tachiyomi-extensions#3085]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 9

### Source information
- Name: Mangakawaii
- Extension version: 1.2.9

## Steps to reproduce
1. Browse extensions
2. Open mangakawaii catalog

### Expected behavior
Show manga's cover

### Actual behavior
Broken manga cover
![Screenshot_20200509_220801_eu kanade tachiyomi](https://user-images.githubusercontent.com/56766778/81482781-300ee200-9242-11ea-9168-7c71344c50fe.jpg)

**Comment by AbdullahM0hamed** [comment]
Unable to replicate, covers work fine for me. Have you tried clearing cache?

**Comment by Mitia99** [comment]
> Unable to replicate, covers work fine for me. Have you tried clearing cache?

Yes,I've already clear tahiyomi and the extension's cache but still having the same issue.

**Comment by SnakeDoc83** [comment]
Did you try "clear database"?

**Comment by Mitia99** [comment]
> Did you try "clear database"?

Fixed after database clearing.Thanks
