### ISSUE TITLE
[Modification] change http to https in source base URL

### ISSUE THREAD

**Issue by shashank-p** [inorichi/tachiyomi-extensions#3095]
I came across some source extension using http rather than https for base URL which I think might cause some errors like http 400 and for security purpose also I think we should change it to https

**Comment by CarlosEsco** [comment]
To be fair you can't change it if the site doesn't support https

**Comment by CarlosEsco** [comment]
Also which source?

**Comment by shashank-p** [comment]
mangahasu is one of them i'll check others manually later

**Comment by SnakeDoc83** [comment]
@shashank-p Mangahasu doesn't seem to support https. If you find some extensions that do support https but they aren't using it let us know and we'll fix them. Until then I'm closing this because there are no specifics to act on.
