### ISSUE TITLE
[Bug]Hiperdex Source broken

### ISSUE THREAD

**Issue by Sajeeb97** [inorichi/tachiyomi-extensions#3100]
# Device information
- Tachiyomi version: ?
 0.9.2
- Android version: ?
 8.1 oreo

### Source information
- Name: Hiperdex
- Extension version: Madara 1.2.90

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
The source should load the Library.

### Actual behavior
 It shows error.

### Other details
![Screenshot_Tachiyomi_20200510-191256](https://user-images.githubusercontent.com/62636945/81500893-94728580-92c4-11ea-8e3e-994db3d56f38.png)
![Screenshot_Tachiyomi_20200510-191307](https://user-images.githubusercontent.com/62636945/81500903-a05e4780-92c4-11ea-8ac9-aaddee7676e8.png)
Hiperdex source shows 404 error.But when u tap webview it loads the site without any captcha.

**Comment by Sajeeb97** [comment]
Just for confirmation. They changed their url to info.I thinks thats why it doesnt load

**Comment by shashank-p** [comment]
url has been changed to https://hiperdex.info/
