### ISSUE TITLE
[Source Request] All webtoons in other languages

### ISSUE THREAD

**Issue by realicejoanne** [inorichi/tachiyomi-extensions#3104]
### Source Website
- Name: Webtoons (other languages)
- Link:
https://www.webtoons.com/zh-hant/ (Traditional Chinese)
https://www.dongmanmanhua.cn/ (Simplified Chinese) (already done)
https://www.webtoons.com/th/ (Thai)
https://www.webtoons.com/id/ (Indonesian)
https://www.webtoons.com/es/ (Espanol)
https://www.webtoons.com/fr/ (French)

### Other Details
The existing Webtoons extension is only for the official English and Webtoon Translations extension is only for the fanmade translations from the official English webtoons. I haven't seen anyone requesting this so is it possible to add these languages too? There are some official webtoons in other languages that aren't available in the official English. It will help other speakers too to find the official translations. I know this is ridiculous because we can install the Webtoons app by ourselves but if there's one for English, it won't hurt to add these too right?
Anyway, thank you for the team's hard work!

**Comment by AbdullahM0hamed** [comment]
Traditional Chinese, Thai, and Indonesian also seem to be already done: https://github.com/inorichi/tachiyomi-extensions/blob/d418ae93b2b87689ceb85918a99911a650dba13c/src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsFactory.kt#L12-L14

**Comment by realicejoanne** [comment]
ohh I see, maybe I should check the filter then. I thought it will be in different extension. Let me check it first.

**Comment by realicejoanne** [comment]
Found it. Apparently since I'm using tachiJ2k, it doesn't show up so I download the latest official Tachiyomi app and yeah got it. I should close this issue then.
