### ISSUE TITLE
[Bug] Source Name : Mangadex filter issue

### ISSUE THREAD

**Issue by vipzzx** [inorichi/tachiyomi-extensions#3108]
### Device information
- Tachiyomi version: j2k 1.0.3
- Android version: Note9/Android 10

### Source information
- Name: Mangadex
- Extension version: 1.2.89

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
When I search a scanlation name in the filter, their mangas will show up. Then I reset the filter, try to search for a different manga, it will only shows the one scanlation groups manga only.
Happens when I search in all source too.

### Actual behavior
When the filter is reset, the user should be able to search for other mangas outside of the previously searched scanlation group.

### Other details

[screen-recording-20200510-193247_0zyWKNZb.compressed.zip](https://github.com/inorichi/tachiyomi-extensions/files/4606947/screen-recording-20200510-193247_0zyWKNZb.compressed.zip)

**Comment by SnakeDoc83** [comment]
Oh, yeah, I remember noticing this before. Instead of pressing reset delete the filter yourself (as in tap in the field and backspace away) before doing another search. Not great that you need to do that, but it'll get you going again.

**Comment by vipzzx** [comment]
> Oh, yeah, I remember noticing this before. Instead of pressing reset delete the filter yourself (as in tap in the field and backspace away) before doing another search. Not great that you need to do that, but it'll get you going again.

Oh that is annoying lol. I held it for a good 5 seconds just in case and its back and running. Thanks.
Is it possible to fix or since not enough people use it, its kinda pointless to.

**Comment by SnakeDoc83** [comment]
I think you're the first person to mention this after I added that search function in however many months ago; so I kind of think not a lot of people use it. I don't know if it can be fixed.

**Comment by vipzzx** [comment]
No worries then. Because usually I would go into webview and look through there. Not gonna lie, there was a lot of copying and pasting happening. 
Only until today did i even think about using the filter, i felt so dumb because i use the filter on the website too lol
