### ISSUE TITLE
[Bug] Manga-TR: HTTP 403 Status Code

### ISSUE THREAD

**Issue by kondanta** [inorichi/tachiyomi-extensions#3109]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 9

### Source information
- Name: FMReader's Manga-TR
- Extension version: 1.2.13

## Steps to reproduce
- Add FMReader extension.
- Switch back to `Sources` tab
- Tap on either Manga-TR `LATEST` or `BROWSE`

### Expected behavior
Tapping on  `LATEST` or `BROWSE` should list available manga.

### Actual behavior
HTTP error 403.

### Other details
It looks like web site uses some sort of DDoS protection software. Hence the 403 error.

**Comment by SnakeDoc83** [comment]
Yup, open in webview then backout and retry.

**Comment by kondanta** [comment]
> Yup, open in webview then backout and retry.

This solves the issue but because of this app crashed couple of times as well. If I can find  a way to reproduce it, gonna open a new issue.
