### ISSUE TITLE
MangaRock not loading pages 

### ISSUE THREAD

**Issue by HereticWilson** [inorichi/tachiyomi-extensions#311]
App version:
R1399, mangarock extension version 1. 0.2
Issue/Request:
Source not loading pages 
Steps to reproduce (if applicable)

Other details:
Can browse titles at source and even load information pages for individual titles but if I try to start reading said title it gives the message "Image could not be loaded. Try changing the image decoder or with one of the options below" and then below the message are a retry button and an open in browser button. Retry does not work neither does the open in browser button, instead it just attempts to download a .mri file to my device.

**Comment by LakotaGray** [comment]
Click somewhere about the text about image cant' be loaded in the black center of page. The border menu will appear. In upper right corner click the gear icon and change the image decoder to a different one. That will resolve the images loading in Manga Rock extension

**Comment by HereticWilson** [comment]
Nice, that did the trick.
