### ISSUE TITLE
[Source Request] GoComics

### ISSUE THREAD

**Issue by littlebabyboo** [inorichi/tachiyomi-extensions#3111]
- Name: GoComics
- Link: gocomics.com
- Language(s): English

**Comment by arkon** [comment]
Duplicate of #1343

**Comment by littlebabyboo** [comment]
can you tell me which extension gocomics is? @arkon

**Comment by muekoeff** [comment]
@littlebabyboo There's no extension yet. But somebody has already requested one before you.
