### ISSUE TITLE
[Bug] Manganelo : Browse gave no result

### ISSUE THREAD

**Issue by Zenothia** [inorichi/tachiyomi-extensions#3113]
### Device information
- Tachiyomi version: J2K 1.0.4
- Android version: 10

### Source information
- Name: Manganelo
- Extension version: Mangabox 1.2.21

## Steps to reproduce
1. Tap the source for browse
2. There is no result

### Expected behavior
It should shows the manga. 

### Actual behavior
There is no result.

### Other details
View Latest shows result, here is the vid:
https://cdn.discordapp.com/attachments/657923584811073566/709358212498980934/Screen_Recording_20200511-175452.mp4

**Comment by SnakeDoc83** [comment]
This is a source issue, the page we scrape for manga is broken at the moment. It's happened a few times recently, manganelo will fix it eventually.
