### ISSUE TITLE
[Bug] MangaYabu : By having changed the website layout, the extension is no longer working.

### ISSUE THREAD

**Issue by GabriellPT** [inorichi/tachiyomi-extensions#3114]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 8.1.0

### Source information
- Name: MangaYabu
- Extension version: 1.2.2

## Steps to reproduce
1. Go to the Browse tab.
2. Click the "Latest"/"Browse" buttons from this extension.
3. The page is completely black or it says "No results found"

### Expected behavior
When clicking "Latest", it should display the latest mangas.
When clicking "Browse", it should display the most popular mangas.

### Actual behavior
When clicking "Latest", nothing appears. Just a black screen.
When clicking "Browse", it says "No results found".

### Other details
Recently, the website changed its layout. This may happen due to that.
(I reinstalled the extension and nothing changed.)

**Comment by alessandrojean** [comment]
Will take a look.
