### ISSUE TITLE
[Bug] Mangatensei : No results found/pages not loading 

### ISSUE THREAD

**Issue by Cryptozoologist** [inorichi/tachiyomi-extensions#3122]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 7.1.2

### Source information
- Name: Mangatensei (and others)
- Extension version: 1.2.6

## Steps to reproduce
1. Browse sources
2. Click "latest" or "browse"

### Expected behavior
show available manga

### Actual behavior
- Doesn't show any manga
-  Click open in webview, manga appears as normal but the URL change automatically to **_isekaimanga.net_**

### Screenshot
![Screenshot_2020-05-12_054958](https://user-images.githubusercontent.com/65199237/81622825-3953a680-941c-11ea-8bd2-9a3ac6feac92.jpg)

**Comment by SnakeDoc83** [comment]
The site's down, has been for a little while (2 weeks maybe?). Nothing we can do, try bato.to or mangawindow--they're basically clones.

**Comment by Cryptozoologist** [comment]
@SnakeDoc83 thank you for the replay, i still don't understand why when i open in webview, the URL  (mangatensei URL) redirect automatically to isekaimanga.net ?
are they change their domain or URL ?

**Comment by SnakeDoc83** [comment]
Mangatensei's URL is mangatensei.com, normally it doesn't forward to a different URL. Normally it looks like this [snapshop](https://web.archive.org/web/20200103070956/https://www.mangatensei.com/). You're being forwarded to a different URL with a different layout and a different name.

**Comment by Cryptozoologist** [comment]
@SnakeDoc83 so should i close this thread because this issue is not a bug?

**Comment by SnakeDoc83** [comment]
Yes.

**Comment by Cryptozoologist** [comment]
Ok then
