### ISSUE TITLE
[Bug] Source Name : Ninemanga extention issue blank page

### ISSUE THREAD

**Issue by earlan123** [inorichi/tachiyomi-extensions#3126]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 9

### Source information
- Name: ninemanga
- Extension version: 1.2.10

## Steps to reproduce
1. I open the extension
2. Blank page and not showing any manga 

### Expected behavior
List of manga supposed to appear

### Actual behavior
It show blank page.
No manga found/just black screen

### Other details
When i click the newest manga it show blank page and when i click explore it also show blank page,when i choose to open the web view it show other link. Their site is redirecting me to gardenmanage.com

**Comment by SnakeDoc83** [comment]
You don't need to spam discord and github with messages all over the place, it's less than helpful.  NineManga has not changed address; gardenmanga.com doesn't even have manga so why would we try to change the extension to that?

Which language are you using in the NineManga extension?

**Comment by earlan123** [comment]
> You don't need to spam discord and github with messages all over the place, it's less than helpful. NineManga has not changed address; gardenmanga.com doesn't even have manga so why would we try to change the extension to that?
> 
> Which language are you using in the NineManga extension?

I'm using english

**Comment by SnakeDoc83** [comment]
It seems fine to me. Try using a different data connection (cellular/wifi/VPN).

**Comment by earlan123** [comment]
> It seems fine to me. Try using a different data connection (cellular/wifi/VPN).

![IMG_20200512_162127](https://user-images.githubusercontent.com/65069801/81666948-e35b1f00-946c-11ea-8cdb-fae74ba1e830.jpg)
![IMG_20200512_162204](https://user-images.githubusercontent.com/65069801/81666981-ed7d1d80-946c-11ea-97b5-7fda8cab7169.jpg)
![IMG_20200512_162236](https://user-images.githubusercontent.com/65069801/81667015-f968df80-946c-11ea-8ade-c5ee567aa37a.jpg)
 No matter what i've done it still blank page like this and when i click webview it redirecting to some other website

**Comment by CarlosEsco** [comment]
if you try to access the site directly through your normal web browser are you able to?

**Comment by earlan123** [comment]
Yes i can when i open the site in my web browser,but when in tachiyomi when i click webview the en.ninemanga.com  it redirect to some kind of garden something website.please help me if you can

**Comment by CarlosEsco** [comment]
@earlan123 can you check on your phones chrome browser

http://en.ninemanga.com
vs
https://en.ninemanga.com

**Comment by earlan123** [comment]
It has the same result,it's normal

**Comment by earlan123** [comment]
Please someone who can help me fix this issue.i have so many manga,manhwa,and manhua to read in this extension.it's annoying if i need to migrate all those comics to another resources

**Comment by CarlosEsco** [comment]
as mentioned before don't spam.  The issue is open.  Someone will look into if they have time and fix is possible.

**Comment by SnakeDoc83** [comment]
@earlan123 If this is still an issue for you, clearing your cookies should fix this (been told by 2 users that works).
