### ISSUE TITLE
[Bug] MangaDex: searching doesn't show any results

### ISSUE THREAD

**Issue by Jirash** [inorichi/tachiyomi-extensions#3128]
### Device information
- Tachiyomi version: Stable 0.9.2
- Android version: 7.0

### Source information
- Name: MangaDex
- Extension version: 1.2.89

### Expected behavior
Searching for titles should show proper results.

### Actual behavior
Searching for titles doesn't show anything. Same goes for source migration (different source to MD). Tried it with manga from the "latest" list, but it still wouldn't show anything, like there's no manga with such title.

### Other details
Screenshots:
1. https://i.imgur.com/0eFZ4YV.jpg
2. https://i.imgur.com/0xKALfy.jpg

**Comment by SnakeDoc83** [comment]
Did you log in to MangaDex?
https://tachiyomi.org/help/faq/#mangadex

**Comment by Jirash** [comment]
Dang, I completely forgot to log in after updating the app, sorry about that.
