### ISSUE TITLE
[Bug] hentaivn doesn't work

### ISSUE THREAD

**Issue by Sehai1** [inorichi/tachiyomi-extensions#3130]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 9

### Source information
- Name: hentaivn
- Extension version: 1.2.5

### Expected behavior
It shows manga

### Actual behavior
It doesn't show anything. But webview still works

**Comment by SnakeDoc83** [comment]
You already have an issue open for this, don't open another.
