### ISSUE TITLE
[Feature Request] Information of the extensions

### ISSUE THREAD

**Issue by realicejoanne** [inorichi/tachiyomi-extensions#3132]
### What feature should be added to this source?
We have the details page on each extensions we installed. Why don't we use that page to describe the extension? At least I need the list of the extensions for some multi sources extension like Madara, Mangatensei, etc. along with the resource link. We can also add the details page before we install the extensions though, so we could know what's the extension for.

There is this [document](https://docs.google.com/spreadsheets/d/1TyJEUg78WWH4zgnf3g6M2lkbWpBWbd40FYiPVQhW8IU/edit#gid=0) for helping add the description.

**Comment by CarlosEsco** [comment]
current infrastructure for extensions does not provide extra data option and this would required a massive change

this will probably be addressed in a future 1.x release when extensions  need reworked
