### ISSUE TITLE
[Bug] Mangasee : loading issues

### ISSUE THREAD

**Issue by 1reeper** [inorichi/tachiyomi-extensions#3138]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 8

### Source information
- Name: Mangasee
- Extension version: 1.2.6

## Steps to reproduce
1. Open any manga chapter from Mangasee

### Expected behavior
Manga opens and loads normally

### Actual behavior
2 or 3 pages load in, then no more pages load and I get a retry error (which works after another loading period).  If I back out of the manga, and re-read the chapter, the same error occurs but the previously loaded pages are no longer loaded.

The relevant point is that if I open any manga in WebView or in any browser, the Mangasee website loads fine, the chapter loads fine in both single and all page views, so it's not a server problem.
 
### Other details
I've tried uninstalling and reinstalling the extension, clearing the cache, clearing cookies, refreshing everything in the advanced settings.  Browsing the Mangasee catalog is also fine with no loading required.

**Comment by SnakeDoc83** [comment]
Just downloaded a chapter of Tower of God as a test and it worked, painfully slow, but it worked. That's kind of how it's been the last few weeks; try downloading instead of streaming.

**Comment by 1reeper** [comment]
The problem is that I'm getting loading errors, rather than slow loading.  The couple of pages that load are fast, then it just stops.  The site also works fine for me (chapters load near instantly on all pages view).  So the servers aren't an issue.

**Comment by SnakeDoc83** [comment]
I'll take a look at trying something, but you may want to temper your hopes.
