### ISSUE TITLE
[Bug] Source Name : Mangatensei not working due to website change 

### ISSUE THREAD

**Issue by vipzzx** [inorichi/tachiyomi-extensions#3139]
### Device information
- Tachiyomi version: J2K 1.0.5
- Android version: Android 10/Note9

### Source information
- Name: Mangatensei (and others)
- Extension version: 1.2.6

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Be able to view manga in the source.

### Actual behavior
Mangatensei.com redirects to mangaseinen.com when you do webview.

**Comment by SnakeDoc83** [comment]
Mangatensei has been down for at least 2 weeks. They've been forwarding their URL to a different address since then, up until yesterday it was isekaimanga.net they forwarded to. Use a different source (Bato.to and Mangawindow are basically clones).

**Comment by vipzzx** [comment]
Got it thanks.
