### ISSUE TITLE
[Indonesian] Komikcast.com

### ISSUE THREAD

**Issue by yoonamarceline** [inorichi/tachiyomi-extensions#315]
Site Request
Please Add Indonesian Manga :
http://komikcast.com

Thanks

**Comment by 1001menghilangkanjerawat** [comment]
site request
please add a health website
[http://jurnalku.me/](http://jurnalku.me/)

**Comment by CarlosEsco** [comment]
@1001menghilangkanjerawat make a new issue

**Comment by CarlosEsco** [comment]
@wand09 make a new issue

**Comment by yanto13** [comment]
And my website too, please Paket Kuota Internet [](https://www.kuotainternetgue.com)

**Comment by yanto13** [comment]
And my website too, please Paket Kuota Internet [https://www.kuotainternetgue.com](https://www.kuotainternetgue.com)

**Comment by yanto13** [comment]
Give me solution for my health website [https://www.sehatinstan.com](https://www.sehatinstan.com)

**Comment by Muclaz** [comment]
Please add Indonesian plugin
