### ISSUE TITLE
[Question] Where can I find sourceID of an extension?

### ISSUE THREAD

**Issue by Mark-Joy** [inorichi/tachiyomi-extensions#3150]
Hello,
I am doing some manga list migrations from my old fanfox and manganelo websites to tachiyomi.
For example the sourceID of MangaRock ext is '1554176584893433663', how can I can get this number  (from source code maybe or anything)?
I can get manganelo sourceID by bookmark a manga on tachiyomi and then export the json backup.
But since fanfox ext is obsolete, I am not able to bookmark anything on tachiyomi app.

How to obtain this number from source code or do you have a list of these numbers?

**Comment by Mark-Joy** [comment]
I tried to search the number on this github to no avail...

**Comment by CarlosEsco** [comment]
The id is generated there is no way to find it in code.

**Comment by CarlosEsco** [comment]
Future backups have the scanlator in the backup in addition

**Comment by Mark-Joy** [comment]
Thank you
Does the scanlator read the ID of installed extensions and export the ID list?

**Comment by arkon** [comment]
I think he means the source IDs, not scanlator. Backups in the preview version of the app, and newer versions of the J2K and Neko forks include that data.
