### ISSUE TITLE
[Bug] Mangahasu

### ISSUE THREAD

**Issue by aofukai7** [inorichi/tachiyomi-extensions#3151]
![Screenshot_2020-05-14-20-09-07-31_5901a79de973a50c74cff4cbb6149856](https://user-images.githubusercontent.com/64181165/81938187-cebe8880-961e-11ea-906c-bbe8ccf8c3f5.png)
![Screenshot_2020-05-14-20-09-14-36_5901a79de973a50c74cff4cbb6149856](https://user-images.githubusercontent.com/64181165/81938215-d54d0000-961e-11ea-8c16-eb15cb3d923a.png)

Error

**Comment by mrskizzex** [comment]
Happens to me as well, clearing cookies in the advanced tab fixes this but it's annoying to do every week this happens. Especially when you also have to login in web view on mangadex afterwards.
