### ISSUE TITLE
[Deletion Request] Delete Mangastein

### ISSUE THREAD

**Issue by fearthemonster** [inorichi/tachiyomi-extensions#3152]
### Source Website
- Name: Mangastein
- Link: https://mangastein.com
- Language(s): Turkish

### Other Details

I wish to delete my website from here. It added here without my permission and I want you to delete my website from here. Thanks.

**Comment by arkon** [comment]
Please DM a mod on Discord with proof of ownership.

**Comment by fearthemonster** [comment]
can u send me ur discord link? I can't find it...

**Comment by Flat** [comment]
https://discord.gg/tachiyomi

**Comment by Soitora** [comment]
I can confirm I've recieved proof of ownership.
