### ISSUE TITLE
[Bug] Madara : All Porn Comic 404 error

### ISSUE THREAD

**Issue by Miellenials** [inorichi/tachiyomi-extensions#3159]
### Device information
- Tachiyomi version: r2289
- Android version: 9

### Source information
- Name: Madara
- Extension version: All Porn Comic

## Steps to reproduce
1. Open it
2. Error, always need to bypass captcha

### Expected behavior
Can directly browse

### Actual behavior
404 error must open in webview and solve captcha

**Comment by SnakeDoc83** [comment]
....you expect Tachiyomi to solve captchas for you?

**Comment by CarlosEsco** [comment]
Not attempting to add auto captcha to app

**Comment by Miellenials** [comment]
No, i use browser and its not getting captcha. Only when i open it via tachiyomi

**Comment by Miellenials** [comment]
Im afraid it has something to do with madara/tachiyomi mechanism to browse it
