### ISSUE TITLE
[Bug] Source Name : mangaae

### ISSUE THREAD

**Issue by baytout00** [inorichi/tachiyomi-extensions#3160]
http://mangaae.com
is not working

Arabic source

**Comment by SnakeDoc83** [comment]
Don't know what your issue is, it loaded fine for me.

**Comment by arkon** [comment]
Try opening it in webview first.

**Comment by baytout00** [comment]
I'm using the version  0.8.4 of the app.
And there's no webview in it.

The problem I face can be explained in this picture.

https://drive.google.com/open?id=1P1Gz0GJ_o7M-fnKvEhWGArJeF8ohUmmY

**Comment by joseph619** [comment]
Update your app, your version is 15 months old.

**Comment by baytout00** [comment]
That's the problem because i have **android** version 4.4.4  kitkat
And the new versions don't work on it.

**Comment by joseph619** [comment]
Join the Discord server for assistance, we no longer support pre 0.9.0 versions.

**Comment by arkon** [comment]
0.8.4 has webview. Regardless, you need to update to at least 0.8.5.

**Comment by baytout00** [comment]
Tanks
