### ISSUE TITLE
[Source Request] TAPAS

### ISSUE THREAD

**Issue by BrownIndianGuy** [inorichi/tachiyomi-extensions#3166]
### Source Website
- Name: Tapas
- Link: https://m.tapas.io/
- Language(s):  En(? )

### Other Details
got some  mangas which are not available  in others.... 
![Screenshot_20200515-211049](https://user-images.githubusercontent.com/54560621/82069267-aef79500-96f0-11ea-89c1-7123452df865.png)

**Comment by arkon** [comment]
It already exists.

**Comment by BrownIndianGuy** [comment]
> It already exists.

Which  extension???

**Comment by AbdullahM0hamed** [comment]
The extension is called Tapas, which is the result you get if you search it in-app. Here is a direct link, though: https://github.com/inorichi/tachiyomi-extensions/raw/repo/apk/tachiyomi-en.tapastic-v1.2.8.apk
