### ISSUE TITLE
[Feature Request] ComicExtra: Add genre tags

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi-extensions#3168]
ComicExtra is the second most popular comic source, and currently the extension is missing genre tags. Please add them, thanks.

**Comment by SnakeDoc83** [comment]
I'm not seeing the title issue.

**Comment by joseph619** [comment]
Here's an example

![20200515_165837](https://user-images.githubusercontent.com/34897862/82095672-83af7e80-96cd-11ea-8285-6cde68c29b31.jpg)

**Comment by SnakeDoc83** [comment]
Which version of Tachi is that from? Seems like it might be a j2k issue unless j2k is using a different version of JSoup.

**Comment by joseph619** [comment]
I was using Sy which is on the latest version of Preview
