### ISSUE TITLE
[Bug] Mangasee : Downloaded chapters are scrambled

### ISSUE THREAD

**Issue by Vaturobi** [inorichi/tachiyomi-extensions#3179]
### Device information
- Tachiyomi version: 8.5
- Android version: 4.4

### Source information
- Name: Mangasee
- Extension version: 1.2.7

## Steps to reproduce
1. Download a manga (ex. Vinland saga)
2. Read, notice pages are scrambled

### Expected behavior
All pages should be in order

### Actual behavior
Pages are scrambled 

### Other details
Might be a new security feature of the site where downloading auto scrambles pages

**Comment by SnakeDoc83** [comment]
I just compared Vinland Saga chapter 171 on Tachiyomi vs what's on the website and they matched.

**Comment by Vaturobi** [comment]
Dont know abouy the latest try downloading 160-165/170 since thats where find them scrambled

**Comment by SnakeDoc83** [comment]
Just checked 160 and 161, Tachi matches what's on the website. If they're out of order that's the source's fault.

**Comment by Vaturobi** [comment]
Ok thanks

**Comment by AxezCore** [comment]
Can confirm I have the same issue on my tab3, maybe some kind of tachiyomi protection.

**Comment by emrexemre** [comment]
i have the same problem on my tablet too. i have newest version of tachiyomij2k on my phone and in that version it works normal but in my tab which has the 0.8.5 version of normal tachiyomi pages are scrambled both reading online and downloaded chapters

**Comment by SnakeDoc83** [comment]
They've recently completely changed their website; so this will no longer be applicable going forward.
