### ISSUE TITLE
Please add Manga world to the extensions

### ISSUE THREAD

**Issue by CarotaMan** [inorichi/tachiyomi-extensions#3183]
* Tachiyomi version: 0.9.2
* Android version: 9
* Device: Xiaomi Redmi Note 8t

## Issue/Request
Please add Manga world to the extensions because there are some manga that I can't read on Mangaeden, Manga world were there a few months ago but now no more, so please add it, Manga world in the italian language, thanks.

**Comment by CarlosEsco** [comment]
If a source was there and now is not. There obviously Is a reason search GitHub issues and you will see why
