### ISSUE TITLE
[Issue] Unparseable Date

### ISSUE THREAD

**Issue by VeganHentai** [inorichi/tachiyomi-extensions#319]
Tachiyomi - v 0.7.3
MangaDex Extension - v 1.2.9

Browsing the catalog for MangaDex returns no results. Browsing by latest shows manga, but when selecting one the unparseable date error shows like in the included screenshot.

![screenshot_20180505-231225](https://user-images.githubusercontent.com/25962087/39677715-a7de7a4e-514d-11e8-8f94-2cfcc39b3d5a.png)

**Comment by CarlosEsco** [comment]
Update your extension 1.2.9 is months old
