### ISSUE TITLE
[Bug] Mangas.pw : Search doesn't work

### ISSUE THREAD

**Issue by MerradOklom** [inorichi/tachiyomi-extensions#3192]
---

### Device information
- Tachiyomi version: 0.8.5/0.9.2
- Android version: 4/6/7.1

### Source information
- Name: Mangas.pw (MMRCMS)
- Extension version: 1.2.38

## Steps to reproduce
1. Open Browse
2. Search a manga

### Expected behavior
The manga searched should appear

### Actual behavior
Throws HTTP error 500

### Other details
![OmaeWaMouShindeiru](https://user-images.githubusercontent.com/43864503/82132191-897f8f80-97b3-11ea-9888-dc3cab074c3f.png)

**Comment by SnakeDoc83** [comment]
The site's using Google to search instead of their own engine, which is kind of lame.
