### ISSUE TITLE
[Bug] Tapas : Chapters are locked and HTTP error 404

### ISSUE THREAD

**Issue by LunaEden** [inorichi/tachiyomi-extensions#3197]
### Device information
- Tachiyomi version: 1.0.5
- Android version: 9

### Source information
- Name: Tapas
- Extension version: 1.2.8

## Steps to reproduce
1. Select manga title
2. Select chapter

### Expected behavior
Chapter opens

### Actual behavior
Chapter doesn't open and message appears saying to login and refresh.

### Other details
Also on some of the titles an HTTP error 404 appears.

**Comment by asdkant** [comment]
This is still broken functionality for the non-paying users, this should behave the same as webtoon (if I don't pay, I don't see the paywalled chapters).
