### ISSUE TITLE
ReadComicOnline : All of the comics are empty

### ISSUE THREAD

**Issue by sydeskroll** [inorichi/tachiyomi-extensions#3206]
### Device information
- Tachiyomi version: Stable 0.9.2
- Android version: 6.0 MRA58K

### Source information
- Name: ReadComicOnline
- Extension version: 1.2.8

### Expected behavior
Comics should be readable

### Actual behavior
Comics are empty, unreadable, and undownloadable

**Comment by SnakeDoc83** [comment]
Are you getting a "Page List is Empty" error or something else? Which comic and chapter? Can you open it in webview?

**Comment by SnakeDoc83** [comment]
Closing, can't reproduce and not enough information to act on.
