### ISSUE TITLE
Bug lot of chapter (NineManga/Japscan)

### ISSUE THREAD

**Issue by AidenPe4rce** [inorichi/tachiyomi-extensions#3211]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 10
* Device: S20 +
### Source information
* Source name: NineManga/Japscan
* Source extension version: ?

## Steps to reproduce
Radiant Chapters  93 -100 (NineManga)
Rikudou Chapters  187-196 (Japscan)
And more..

## Issue/Request
image Chapter :
![Screenshot_20200517-181523_Tachiyomi](https://user-images.githubusercontent.com/55485568/82154284-0f134600-986d-11ea-8970-f449ee654b27.jpg)

**Comment by SnakeDoc83** [comment]
The NineManga images are scrambled on the site itself, presumably they scraped and uploaded them that way. Can't fix those.

Japscan has known issues https://github.com/inorichi/tachiyomi-extensions/issues/2219 and https://github.com/inorichi/tachiyomi-extensions/issues/2535
