### ISSUE TITLE
[Feature Request] NineManga: Add missing filters

### ISSUE THREAD

**Issue by MerradOklom** [inorichi/tachiyomi-extensions#3227]
---

### What feature should be added to this source?
As the title says, it would be nice to have the missing filters. Currently you can only filter by gnre, but there are more filtering options in the website (http://en.ninemanga.com/search/?type=high):
• Author
• Artist
• Manga Status (Complete, Ongoing, Either)

**Comment by AMZMA** [comment]
hi, again Merad 😃 

remember the ninemanga issue before?
I found that nineanime much better than taadd (ninemanga).
it has further latest updated manga list, less duplicate tittle.
and Ninemanga still regularly give me error "http ....".

I used to request for [taadd/ninemanga](https://github.com/inorichi/tachiyomi-extensions/issues/81) back at 2017. I hope my [new request](https://github.com/inorichi/tachiyomi-extensions/issues/3267) is granted. 💖
