### ISSUE TITLE
[Source Request] Madara: Renascense Scans

### ISSUE THREAD

**Issue by Hyoretsu** [inorichi/tachiyomi-extensions#3232]
### Source Website
- Name: Renascans
- Link: https://new.renascans.com/
- Language(s): English

### Other Details
You guys already have this extension, but the group changed websites and have stopped uploading to the old link you have. The new site's now made with Madara

**Comment by SnakeDoc83** [comment]
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/3194
