### ISSUE TITLE
[Bug] <madara:WordRain translation>: <wont open>

### ISSUE THREAD

**Issue by Slowxzy** [inorichi/tachiyomi-extensions#3236]
---

Device information
- Tachiyomi version: stable 0.9.2 
- Android version: android 10

 Source information
- Name: WordRain translation (madara)
- Extension version: 1.2.94

## Steps to reproduce
1. Open WordRain translation 

Expected behavior
 Be able to open the extension 

Actual behavior
 Showed me "HTTP error 404: check website in WebView"

Other details
 It works normally if you opened it from the webview

**Comment by SnakeDoc83** [comment]
As far as I can tell they're no longer hosting manga, only novels. This can stay open for now as a reminder to remove them from Madara. Meanwhile, you may as well start migrating to a different source.
