### ISSUE TITLE
[Source Request] Toonkor Bz

### ISSUE THREAD

**Issue by aofukai7** [inorichi/tachiyomi-extensions#3242]
M
![Screenshot_2020-05-20-00-05-12-61](https://user-images.githubusercontent.com/64181165/82356353-a0311b00-9a2d-11ea-9abb-9c787fac1414.png)

The best site for manhwa raw include manhwa18 genre or manhwa adult

**Comment by SnakeDoc83** [comment]
There's also requests for toonkor.ws and toonkor.red, are they all the same source using multiple domains or copycats?

**Comment by aofukai7** [comment]
I dont know the raw manhwa adult that i search found in that web 

But when i check that .ws web it's same with my request the web UI the logo 

I can't check .red since its blocked for me

You can choose those 2 website

.ws or .bz

Let me know if its already added
