### ISSUE TITLE
[Bug] Madokami: sometimes images won't load

### ISSUE THREAD

**Issue by crisalis2** [inorichi/tachiyomi-extensions#3245]
### Device information
- Tachiyomi version: r2331
- Android version: 10

### Source information
- Name: Madokami
- Extension version: 1.2.1

### Description
Sometimes, images won't load for certain files. Tachiyomi just says "retry". It's the case for links like:
1. https://manga.madokami.al/Manga/C/CH/CHAI/Chainsaw%20Man/%21Chainsaw%20Man%20%5BVIZ%20Media%5D/Chainsaw%20Man%20-%20c053-061%20%28web%29%20%5BViz%5D%20%5BIntervenci%C3%B3n%5D.zip
(File "Chainsaw Man - c053-061 (web) [Viz] [Intervención].zip" inside the folder "!Chainsaw Man [VIZ Media]" inside https://manga.madokami.al/Manga/C/CH/CHAI/Chainsaw%20Man/ )
2. https://manga.madokami.al/Manga/N/NO/NORA/Noragami/%21Noragami%20%5BHexer-Empire%20%2B%20danke%20%2B%20FG%20Manga%5D%7BHD%7D/Noragami%20-%20Stray%20God%20v01%20%282014%29%20%28Digital%29%20%28Hexer-Empire%29.cbz
(File "Noragami - Stray God v01 (2014) (Digital) (Hexer-Empire).cbz" inside the folder "!Noragami [Hexer-Empire + danke + FG Manga]{HD}" inside https://manga.madokami.al/Manga/N/NO/NORA/Noragami )

At first I thought it had to do with the presence of certain characters in the path (for the file in "1.", the "ó" in "Intervención"; for the file in "2.", the "+" in the folder name), but it doesn't look to be exactly like that because, for example, inside the already mentioned "!Noragami [Hexer-Empire + danke + FG Manga]{HD}" folder, which adds the "suspicious" "+" to the path, none of the Hexer-Empire files load but other files inside the folder do load.

Another thing I noticed is that Tachiyomi says (just says, nothing is actually shown) these Hexer-Empire files have double the images they actually have (for the file "Noragami - Stray God v01 (2014) (Digital) (Hexer-Empire).cbz", already mentioned in the "2." above, that's 392 instead of 196). Strangely enough, this "duplication" doesn't happen for example for the also unable to load "Chainsaw Man - c053-061 (web) [Viz] [Intervención].zip" that I already mentioned in the "1." above.

One last comment. This is unrelated and I'm not sure if it's actually a bug, but sometimes the extension orders the files inside a given directory in a reversed way. This means that, for example in the folder "!Noragami [Hexer-Empire + danke + FG Manga]{HD}", when you finish reading volume 18, Tachiyomi takes you to volume 17 instead of 19.

By the way, thank you very much for making Madokami work, @tesu .

**Comment by crisalis2** [comment]
It doesn't seem to be related to certain characters at all. Inside "Bleach [Viz]", LostNerevarine-Empire files don't work, but the rest do. There's no suspicious character here.

It doesn't look like character length either, since "Noragami - Stray God v16 (2016) (Digital) (Hexer-Empire).cbz" doesn't work, but "Noragami - Stray God v18 (2017) (Digital) (danke-Empire).cbz" does.

Nor file size.

By the way, the files that don't work with Tachiyomi do work with Madokami's "Read" option.

**Comment by tesu** [comment]
I figured it out, it was because in the Hexer-Empire archives, the files were named "noragami etc etc [,] vol 1", and the commas in the filenames were tripping up the (badly implemented) page splitting.

The issue with the chainsawman chapter is what you expected, the special character was the problem in that case, but changing the way the page data was parsed fixed that too.

I checked if this commit fixed the Bleach stuff, and it seems to work fine, so I think the not-loading/retry bug should be completely fixed by commit 5e0106d.

Thanks for the tag, by the way, I appreciate that other people are finding the extension useful.

Now to see if I can do anything about the chapter orderings...

**Comment by crisalis2** [comment]
Thank you!

**Comment by tesu** [comment]
Just wanted to follow up on the ordering issue. Does this come up for *every* manga i.e. always goes up the file list instead of down? What I am considering is to reverse the order of how chapters are currently handled, but I am not sure if that would screw up the ordering for any other manga.

**Comment by crisalis2** [comment]
> Does this come up for every manga 
As far as I've seen, I think that's actually the case.
