### ISSUE TITLE
Mangadex new Data Saver option

### ISSUE THREAD

**Issue by 1reeper** [inorichi/tachiyomi-extensions#3251]
Mangadex just announced their implementation of a data saver option in the site settings (opt-in, so not on by default).

https://mangadex.org/thread/252554

I was curious if activating it through WebView would be sufficient?  Or does the extension need an update to take advantage of it?

Sorry if this isn't the right place to ask.

**Comment by Code027** [comment]
I think that the data saver immediately works upon enabling it on WebView. I don't know if it's just my eyes but I can see compression artifacts the same on a browser and the app itself. Can only do so little testing since it's not very fast on SEA so I hope that someone can ascertain this.

**Comment by CarlosEsco** [comment]
yep if you enable in mangadex settings in in webview or outside of app they will return the data-server urls

**Comment by katarai** [comment]
Data saver was just changed on the Mangadex side (https://mangadex.org/thread/253605), and it appears to make the setting not stick in Tachiyomi when enabling it via the browser.

**Comment by CarlosEsco** [comment]
Yea you would need to logout to get it work.  An extension change will be needed

**Comment by CarlosEsco** [comment]
Latest version has option in app the use data saver
