### ISSUE TITLE
[Bug] Manganelo : View latest library is not working for Manganelo source but there is no issue with the webview results

### ISSUE THREAD

**Issue by Goku003** [inorichi/tachiyomi-extensions#3255]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 10

### Source information
- Name: Manganelo
- Extension version: Mangabox 1.2.21

## Steps to reproduce
1. View latest in the Extension source section

### Expected behavior
The list of manga should have shown with latest updated order

### Actual behavior
Empty screen

### Other details
Main page is working fine(Clicking the source instead of view latest) and webview for view latest is working fine

**Comment by Goku003** [comment]
Just now checked and could see the feeds are getting loaded as expected.

**Comment by SnakeDoc83** [comment]
The MangaBox sources have been kind of unstable lately, this issue comes and goes. You just have to wait it out when it happens.
