### ISSUE TITLE
'Page List is Empty' with Mangadex

### ISSUE THREAD

**Issue by Jadomonkey** [inorichi/tachiyomi-extensions#326]
Tachiyomi 0.7.4, Mangadex 1.2.22

I'm getting the 'Page list is empty' error on seemingly random chapters. Roughly 4/10 chapters of various series don't load, the rest work. I've followed the steps to help fix the error: clearing data, using different networks, etc. I still have the problems.

Clearing data does change the chapters which are having issues though. Gakuen Babysitters 4, 6, 8 and 9 were erroring, but after clearing cache, the affected chapters are 1, 2, 5, 6, 7, 9. When choosing to download the affected chapters, only chapter 2 errored while the others downloaded fine.

**Comment by CarlosEsco** [comment]
Hmm this is a really weird error.  I am unable to repulicate

**Comment by CarlosEsco** [comment]
you still having this issue?

**Comment by QuDu43bChhiONNVlgkoy** [comment]
Tachiyomi version r1414, Mangadex version 1.2.2

Same problems.

**Comment by CarlosEsco** [comment]
@QuDu43bChhiONNVlgkoy any particular manga or chapters

**Comment by Jadomonkey** [comment]
Yes, still having the issue. It started out of the blue about a week ago, but I didn't issue since it was inconsistent and the problem had a history of dead ends. I was looking into their issues with FMD and unintentional ip bans a while ago though and figured I should report this, in case.

**Comment by Jadomonkey** [comment]
I switched through the first 10 chapters of Gakuen Babysitters from 'open in browser' on the tachiyomi series page and in my regular web browser with no problems. Of those, 4, 8 and 9 are giving 'page list is empty' just after checking them in browsers. Now clearing chapter cache, cookies and database in advanced options, chapters 4, 6 and 9 are erroring while 8 now loads.

**Comment by Jadomonkey** [comment]
Just to be thorough, I cleared app data cache in phone options and checked again. Chapters 1, 3, 4 and 7 are affected now.

**Comment by CarlosEsco** [comment]
Does the pagelist error happen right when you open? Are these downloaded or streamed chapters.  I went 1-9 on series and no error..

**Comment by CarlosEsco** [comment]
Does it happen on wifi and phone data?

**Comment by Jadomonkey** [comment]
Right after I start Tachiyomi? No, I can go read from working sources for a while, check back and the same chapters won't work. The same chapters too, I checked now and it's still 1, 3, 4 and 7 with the page list error. The only time it changes is when clearing chapter cache, specifically. Did that now and only 5 and 9 have the page list error.

Different wifi networks don't affect the problem and I just checked phone data now and it's the same.

**Comment by CarlosEsco** [comment]
Can you download latest dev

**Comment by Jadomonkey** [comment]
Ok, the same issue is present in the dev version.

Also, sorry I didn't answer before, but these are streamed chapters. The affected chapters will often be able to be downloaded, but then some download attempts will return the page index error.

I'll test it on the dev version and give stream and download results...

**Comment by Jadomonkey** [comment]
On Tachiyomi r1414 Gakuen Babysitters ch. 1 - 10:
Streamed - ch. 5, 8 and 9 return page index empty, other chapters fine.
Downloaded - ch. 3, 5, 6 and 8 errored, other chapters downloaded fine.

Sorry for the trouble, I might just have to read in browser for mangadex.

**Comment by CarlosEsco** [comment]
Is the manga in your library?

**Comment by Jadomonkey** [comment]
The chapters I downloaded went to my library, yes. And then I was able to read 9, which had errored on stream.

Sheesh! I was trying to test slowness of pages in browser compared to trouble chapters in reader, but now 15.1 was the only chapter of 40 I just now quickly checked with the error. I browsed a bit more than I have before to test speed in browser before clearing cache for a fresh sample of errors, but it seems that may have helped?

**Comment by CarlosEsco** [comment]
i have no clue im just grasping at straws lol.  I cant replicate this issue at all.

**Comment by Jadomonkey** [comment]
Suddenly, I can't replicate it either. It being later in the morning and my flipping through pages a bunch through the browser is the only difference.

**Comment by CarlosEsco** [comment]
going to close now.  Open again if you run into the issue.
