### ISSUE TITLE
[Bug] Mangadex : Settings icon on Website can't be accessed from Webview

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi-extensions#3268]
### Device information
- Tachiyomi version: 2331
- Android version: 10

### Source information
- Name: Mangadex
- Extension version: 1.2.90

## Steps to reproduce
1. Open site in Webview
2. Click on Settings icon on top right

### Expected behavior
Settings should pop up

### Actual behavior
Nothing happens

### Other details
Works fine on browser

**Comment by arkon** [comment]
Scroll down, it's an issue with Android WebView, not the app
