### ISSUE TITLE
[Bug] mangaSusu: manga image does not appear

### ISSUE THREAD

**Issue by nizarschecter** [inorichi/tachiyomi-extensions#3270]
[Bug] mangaSusu: manga image does not appear

**Comment by SnakeDoc83** [comment]
Provide an example.

**Comment by nizarschecter** [comment]
The picture does not come out and also in each chapter the picture does not appear

**Comment by SnakeDoc83** [comment]
Can't reproduce your issue.

**Comment by SnakeDoc83** [comment]
Changed domain in #3678
