### ISSUE TITLE
[Source Request] Tenmanga

### ISSUE THREAD

**Issue by Phenix-Feedback** [inorichi/tachiyomi-extensions#3275]
- Name: Tenmanga
- Link: http://www.tenmanga.com/
- Language(s): English

It has manga that other don't have. For example 14-sai no Koi up to date.

**Comment by SnakeDoc83** [comment]
>It has manga that other don't have.

I shake my head sometimes when people comment this on requests. A quick google shows Mangakakalot has it, they even posted the most recent chapter 5 months before Tenmanga did. I'm not rejecting your request, but you might want to try some more extensions.

**Comment by Phenix-Feedback** [comment]
> 
> 
> > It has manga that other don't have.
> 
> I shake my head sometimes when people comment this on requests. A quick google shows Mangakakalot has it, they even posted the most recent chapter 5 months before Tenmanga did. I'm not rejecting your request, but you might want to try some more extensions.

My bad, it showed chapter 49 and posted here before reading it, while it's chap 37.5. Not needed, sorry.
