### ISSUE TITLE
Syntax error when downloading or trying to view from kissmanga

### ISSUE THREAD

**Issue by noah-smith0921** [inorichi/tachiyomi-extensions#328]
When trying to download or view chapters from kissmanga, I get an error saying "SyntaxError: parse error (line 1)".  This has been an issue with both 0.7.3 and 0.7.4.  I tried reinstalling as well to no avail.

**Comment by CarlosEsco** [comment]
Try clearing cache and cookies.  I had no issue viewing a random chapter of a random manga

**Comment by noah-smith0921** [comment]
I cleared both and I still get the same error.

**Comment by CarlosEsco** [comment]
Is it a particular series or all?

**Comment by noah-smith0921** [comment]
All series I tried to download from KissManga.  I'm able to view it online perfectly fine though.

**Comment by Nic007** [comment]
I have version 0.7.4, I have cleared cache and cookies and I also can't use sources coming from KissManga.

**Comment by pokemonsta433** [comment]
0.7.4 

just had the same problem start ocvuring yesterday. No clue what triggered it

**Comment by pokemonsta433** [comment]
did another test and kissmanga was online and working. It could be a problem with their API though. The first line in any script is usually an include so if their API is the first include, then it's all their fault

**Comment by DaemonPhoenix42** [comment]
Also experiencing this. I got through 40 chapters of berzerk before this became an issue.
All the following entries are stuck as queued even after flooding cache, etc.

**Comment by QuietusWolfe** [comment]
same issuse. running 0.8. Reintalling the extension worked to clear the error once, but not a send time.
