### ISSUE TITLE
[Source Request] Manga Mutiny

### ISSUE THREAD

**Issue by Samk19** [inorichi/tachiyomi-extensions#3292]
### Source Website
- Name: Manga mutiny
- Link: https://mangamutiny.org/
- Language(s): English

**Comment by IP555** [comment]
No thanks

**Comment by E3FxGaming** [comment]
> No thanks

@IP555 May I ask what you're trying to say?

**Comment by SnakeDoc83** [comment]
Closed via #3498 

@E3FxGaming Pretty sure that's a bot or compromised account.

**Comment by Samk19** [comment]
@SnakeDoc83 is the source added ? cannot find it anywhere

**Comment by Samk19** [comment]
Thanks 

So it a complete seprate app 

Thanks for working on it
