### ISSUE TITLE
[Bug] <>: <All manga in the mangadex extension taking a long time to load >

### ISSUE THREAD

**Issue by simpleapplepi** [inorichi/tachiyomi-extensions#3295]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 9

### Source information
- Name: MangaDex
- Extension version: 1.2.92

## Steps to reproduce
1. Click on desired manga
2.  Wait for the Manga to load

### Expected behavior
Should load the page and subsequent pages in a couple of seconds

### Actual behavior
The manga that I want to view is taking 1+ minutes to load just for a single page.

**Comment by arkon** [comment]
MangaDex is having issues. You can ask them about it in their Discord.

**Comment by simpleapplepi** [comment]
Alright, thanks
