### ISSUE TITLE
[Bug] <Source Name>: <short description>

### ISSUE THREAD

**Issue by dodonko** [inorichi/tachiyomi-extensions#3298]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.9.2)
- I have updated all extensions
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/inorichi/tachiyomi
- I have searched the existing issues for duplicates
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions/
- I will fill out the title and the information in this template

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

### Device information
- Tachiyomi version: 0.9.2
- Android version: 10

### Source information
- Name: Maid-manga
- Extension version: 1.2.2

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened

### Actual behavior
This happens instead

### Other details

![Screenshot_20200524-205717](https://user-images.githubusercontent.com/65858378/82756000-7eef7680-9e01-11ea-9e92-8ddd91e32b1d.jpg)
![Screenshot_20200524-205726](https://user-images.githubusercontent.com/65858378/82756003-8151d080-9e01-11ea-8403-379e0b24026f.jpg)

**Comment by arifmamon** [comment]
Give Title of This Issue or it'll be closed
