### ISSUE TITLE
[Site Request] readcomicbooksonline.net

### ISSUE THREAD

**Issue by strugler** [inorichi/tachiyomi-extensions#33]
Can you please add http://readcomicbooksonline.net/ as a catalogue?

C

**Comment by strugler** [comment]
Will this one and the other comics one i requested, will they be added? If so how would i know that they have been added and how to use the extensions once available?

Thanks

**Comment by j2ghz** [comment]
- Maybe, if a someone willing and able is found.
- If you create an issue, you should get notifications from github on any activity on that issue, if not you can use the Subscribe button. If the extension is added the issue will be closed.
- There is currently no in-app method to get extensions (planned), but you can use https://github.com/inorichi/tachiyomi/wiki/FDroid-for-dev-versions

**Comment by arkon** [comment]
Already in MMRCMS.
