### ISSUE TITLE
[mangaworld] <mangaworld>

### ISSUE THREAD

**Issue by AndreaGrillo04** [inorichi/tachiyomi-extensions#3302]
### Source Website
- Name: mangaworld
- Link: https://mangaworld.tv/ 
- Language(s): italian

### Other Details
A few days ago, this extension was in the app but actually i can't fond it and it isn't in the extensions list

**Comment by SnakeDoc83** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/2800

**Comment by lucazag** [comment]
Please add  again the follow extenction
Name: mangaworld
Link: https://mangaworld.tv/
Language(s): italian

**Comment by HasanAbdelAziz** [comment]
The url has changed now the link is: https://mangaworld.cc/

can you guys please change, thx

**Comment by CrepeTF** [comment]
> The url has changed now the link is: https://mangaworld.cc/
> 
> can you guys please change, thx

read #2800
