### ISSUE TITLE
[Bug] Hiperdex: URl changed

### ISSUE THREAD

**Issue by shashank-p** [inorichi/tachiyomi-extensions#3309]
Hiperdex URL has been reverted back to https://hiperdex.com/ which is causing library updates to fail

**Comment by shashank-p** [comment]
Issue Resolved

**Comment by AbdullahM0hamed** [comment]
In future you should probably wrote: Closes #3309 in your PR - so it automatically closes it.

**Comment by shashank-p** [comment]
Ok
