### ISSUE TITLE
[Bug] Renascence Scans(Renascans): HTTP error 404

### ISSUE THREAD

**Issue by CerealKiller7** [inorichi/tachiyomi-extensions#3315]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 7.1.1

## Source information
* Source name: Renascence Scans(Renascans)
* Source extension version: 1.2.3

## Steps to reproduce
1. First Step: Open the extension to browse manga

### Expected behavior
I should be able to open and read chapters

### Actual behavior
When you open the extension it says HTTP error 404

### Other details
You can open the extension on web view and it works fine

**Comment by SnakeDoc83** [comment]
It's just been moved to Madara.
