### ISSUE TITLE
[Source Request] Mangaowl

### ISSUE THREAD

**Issue by vipzzx** [inorichi/tachiyomi-extensions#3319]
### Source Website
- Name: Mangaowl
- Link: https://mangaowl.net/
- Language(s): English

**Comment by SnakeDoc83** [comment]
There's already a MangaOwl extension.

**Comment by vipzzx** [comment]
I can't seem to find it in the Google sheets

**Comment by vipzzx** [comment]
Nevermind. Carlos helped me. Ignore my dumbass.
