### ISSUE TITLE
[Source Request] Drope Scan

### ISSUE THREAD

**Issue by Eduardo1809** [inorichi/tachiyomi-extensions#3326]
### Source Website
- Name: Drope Scan
- Link: https://dropescan.com
- Language(s): Portuguese (Brazil)

**Comment by alessandrojean** [comment]
I will take a look on this.

**Comment by SnakeDoc83** [comment]
Should be able to add to Madara with some tweaks.

**Comment by alessandrojean** [comment]
Oh, I haven't noticed it uses Madara. I already tried once to do add a source to Madara but I haven't succeeded. Can you add this, @SnakeDoc83?

**Comment by SnakeDoc83** [comment]
I'll get to it in a little bit if you're not going to give it a try.
