### ISSUE TITLE
[Source Request] Multporn

### ISSUE THREAD

**Issue by CerealKiller7** [inorichi/tachiyomi-extensions#3334]
### Source Website
- Name: Multporn
- Link: multporn.net
- Language(s): English

### Other Details
It is a hentai/18+ comic site but mainly it is focused on comics

**Comment by CarlosEsco** [comment]
#3182

**Comment by CerealKiller7** [comment]
> #3182

Should I close the thread since there is an ongoing thread?

**Comment by CarlosEsco** [comment]
i already closed this one

**Comment by CerealKiller7** [comment]
Ok

**Comment by as280093** [comment]
Use this Icon:
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/4987700/ic_launcher.zip)
