### ISSUE TITLE
just a question about a source

### ISSUE THREAD

**Issue by mangalover420** [inorichi/tachiyomi-extensions#3337]
I have the latest version of tachiyomi (0.9.2) and my phone is up to date(version 10).i just wanted to ask if the Bato.to source get deleted completely or if it's hopefully coming back, it was one of my faves.

Source information:

name- Bato.to
website- https://bato.to/

**Comment by CarlosEsco** [comment]
![image](https://user-images.githubusercontent.com/2092019/83055113-665da700-a021-11ea-8756-dec93ee0f770.png)

for future news join the discord

**Comment by mangalover420** [comment]
THANK YOU SO MUCH CARLOS ❤️
