### ISSUE TITLE
xkcd: alt text not loading

### ISSUE THREAD

**Issue by yambadr** [inorichi/tachiyomi-extensions#334]
Tachiyomi 0.7.4
xkcd 1.2.4

Alt text (2nd page) is not loading at all. I tried downloading the comics but it diplays "error" in the comic list.

**Comment by einstein95** [comment]
fakeimg.pl is down. The extension should really render the text in-app...

**Comment by CarlosEsco** [comment]
@einstein95 feel free to design a solution that fits the current extension structure that can render the text in app

**Comment by j2ghz** [comment]
looked for alternatives, didn't find anything. There are some, but none wraps: http://via.placeholder.com/300?text=Our+customers+keep+sending+us+their+personal+information,+even+though+we%27ve+repeatedly+asked+them+to+stop.+The+EU+told+me+I%27m+the+heir+to+some+ancient+European+throne+that+makes+me+exempt+from+the+GDPR,+but+we+should+probably+still+try+to+fix+that.

**Comment by CarlosEsco** [comment]
Yea I couldn't find any either. I wish xkcd api just made it a PNG like the comic portion

**Comment by SynderBlack** [comment]
could always look into some other solution using fakeimg since it's [Open Source](https://github.com/Rydgel/Fake-images-please)

**Comment by j2ghz** [comment]
It will be back up: https://github.com/Rydgel/Fake-images-please/issues/15

**Comment by CarlosEsco** [comment]
looks like its up now
