### ISSUE TITLE
[Bug] Mangabox (Manganelo) : Pages only load up until page 2

### ISSUE THREAD

**Issue by Azeraider16** [inorichi/tachiyomi-extensions#3340]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 10
* Device: Huawei P30 Lite

### Source information
* Source name: MangaBox
* Source extension version: 1.2.22

## Steps to reproduce
1. Choose any manga at Manganelo
2. Read up to page 3 of that particular manga

## Issue/Request
ISSUE: It is always says retry for the whole chapter and it doesn't even load, the only pages that are being read is up to page 3 only. 

## Other details
Additional details and attachments.

**Comment by SnakeDoc83** [comment]
Looks fine now. More than likely this was a site issue; they've been unstable for a while and things like this happen, you just have to wait it out.
