### ISSUE TITLE
[Bug] manhuadui: domain changed

### ISSUE THREAD

**Issue by atomicink** [inorichi/tachiyomi-extensions#3341]
### Source information
- Name: manhuadui
- Extension version: 1.2.6

## Steps to reproduce
manhuadui.com  changed to manhuabei.com 

### Other details
![·](https://user-images.githubusercontent.com/5206363/83152877-e3c40d00-a130-11ea-85e2-63e7fb9452d8.png)

**Comment by shashank-p** [comment]
extension name and language?

**Comment by atomicink** [comment]
> extension name and language?


tachiyomi-zh.manhuadui-v1.2.6.apk

Chinese
