### ISSUE TITLE
[Bug] Golden Mangás (pt-BR): HTTP Error 503

### ISSUE THREAD

**Issue by Deku2k** [inorichi/tachiyomi-extensions#3348]
### Device information
- Tachiyomi version: Stable 0.9.2 
- Android version: 8.0.0

### Source information
- Name: Golden Mangás
- Extension version: 1.2.4

## Steps to reproduce
1. Go to extensions
2. Open Golden Mangás (pt-BR)

### Expected behavior
Open list mangas

### Actual behavior
HTTP Error 503

[Screenshot](https://i.imgur.com/frPJZXY.jpg)
[Screenshot 2](https://i.imgur.com/A8fRI7W.jpg)

**Comment by alessandrojean** [comment]
I will take a look on this.
