### ISSUE TITLE
New Mangago Obfuscation ?

### ISSUE THREAD

**Issue by LakotaGray** [inorichi/tachiyomi-extensions#335]
In both 0.7.4 and updated dev version, Mangago correctly loads series covers, and populates series info as well as chapter lists. But when going into a chapter, the correct number of pages is displayed but every page will shows a retry button. When downloading a chapter it posts error, and up above in notifications it give a message, “unexpected website and a series of random characters.

**Comment by einstein95** [comment]
Crypto library: http://www.mnggo.net/mobi/js/crypto.js

`/hwtb:.ea9gmpncaailgrl.eoy/cmmfilgsihea/ee_venlhrlm_nocam_aoyp0n5/0.0/p0g.hnt` turns into `http://iweb9.mangapicgallery.com/imgfiles/heaven_hell_roman_company/0.5/001.png`

Eval'd code in the first line of the library: https://hastebin.com/owatovipur.js

**Comment by fatimagrace015** [comment]
Uhm pardon me but may I ask what it means? And will it be unable to download mangago source?

**Comment by einstein95** [comment]
Mangago links to the page images by obfuscating the URLs, and using Javascript to decode them. Until we find out the codes to deobfuscate them ourselves, they can't be figured out.

**Comment by fatimagrace015** [comment]
Aww😭 mangago is one of the best sources out there😭 hope you can deobfuscate it😭😭

**Comment by Th3-822** [comment]
https://hastebin.com/fujemibuhe.js

**Comment by KoyLyria** [comment]
I've the same problem.
How can we fix it?
I really love this app and mangago too 
Please help  !

**Comment by joseph619** [comment]
I would like Mangago to be fixed as well, it's the only manga source I care about apart from Mangadex.

**Comment by bboyz269** [comment]
@Th3-822 's deobfuscate script is working. I tested and mango is working again. Will we have official update soon?

Also, I attached the built `apk` that works for me. (please change the extention from `txt` to `apk`)
[tachiyomi-en.mangago-v1.2.1-debug.txt](https://github.com/inorichi/tachiyomi-extensions/files/2061311/tachiyomi-en.mangago-v1.2.1-debug.txt)

**Comment by fatimagrace015** [comment]
OMYGAAASSSSHHH! THANK YOOOUUU!! I'LL WAIT FOR IT!!!!! THANK YOU SO MUCH

**Comment by joseph619** [comment]
I changed the extension name from txt to apk, but it doesn't install.

**Comment by joseph619** [comment]
Can't install the apk :( Says "App not installed".

**Comment by fatimagrace015** [comment]
Mine too :3

**Comment by bboyz269** [comment]
@joseph619 Weird, It worked for me. Have you tried uninstall old one or enable developer mode, untrusted apk installation or something?  
Sorry, I don't have any experience in android either. You should look this issue up on google while waiting for the official updates.

**Comment by joseph619** [comment]
Yes, I tried both uninstalling this one, as well as installing update to the existing application. Neither worked. What did you do?

**Comment by bboyz269** [comment]
@fatimagrace015 @joseph619 Sorry, no luck. The apk should be compatible for your android version as well. Look like there's other problems with app signing or something. Again, I don't have any experience with android. Guess you guys have to wait for the official.

**Comment by HierraHills** [comment]
It worked for me!. Thank you so much @bboysz269

**Comment by fatimagrace015** [comment]
@HierraHills what'd you do?😭

**Comment by johnna012** [comment]
Thank You so much @bboyz269 you save us 😄😊

**Comment by fatimagrace015** [comment]
Thank you so much @bboyz269 thank you so muuccch! And to youu too @johnna012 XD

**Comment by CarlosEsco** [comment]
@bboyz269 why not open a pull request if you fixed it?

**Comment by ayamafujoshi** [comment]
@bboyz269 A huge thankssss!!! 😀

**Comment by quinnjet** [comment]
Thanks so much @bboyz269. If you don't mind, would you be willing to share how you were able to run the script for the apk. Just for future reference, in case it happens again.

**Comment by happymermaid** [comment]
It worked thank you so much!!! Omg 😭

**Comment by aeeriinn** [comment]
Running on an old android 5.0 and it worked for me. Thank you so much.

**Comment by einstein95** [comment]
@bboyz269 Please submit your code changes as a PR.

**Comment by NoodleMage** [comment]
Fixed #339

**Comment by wopian** [comment]
@KoyLyria it was fixed in 1.2.2 of the Mangago extension.
