### ISSUE TITLE
[Source Request] Hasta Reader 

### ISSUE THREAD

**Issue by Hazyfade** [inorichi/tachiyomi-extensions#3359]
#2509 # Source Website
- Name: Hasta Reader
- Link: https://hastareader.com/slide/
- Language(s): Italian

### Other Details
There are two sections: latest publications and list of series

**Comment by arkon** [comment]
See #115

**Comment by Hazyfade** [comment]
What sad news. I'm sorry, I had search if there was already a request about it, but I didn't found nothing, I should have looked more deeply.
