### ISSUE TITLE
[Source Request] Mandrasoft

### ISSUE THREAD

**Issue by rickevans86** [inorichi/tachiyomi-extensions#3360]
# Source Website
- Name: Mandrasoft
- Link: https://app.mandrasoft.org/
- Language(s): English

**Comment by shashank-p** [comment]
It's loading chapter images from https://readm.org so you should better of using **readm** extension

**Comment by AbdullahM0hamed** [comment]
He is right. Of all its sources, the only one we don't have is a French source called JapanRead - so it really wouldn't be that useful for English users considering that it's only English source is ReadM (when I last checked) and there's already an extension for that.

**Comment by rickevans86** [comment]
Installed readm plugin
Thanks
