### ISSUE TITLE
[Source Request] Remangas (pt-BR)

### ISSUE THREAD

**Issue by Deku2k** [inorichi/tachiyomi-extensions#3365]
### Source Website
- Name: Remangas
- Link: https://remangas.top/
- Language(s): Português (Brasil)

**Comment by WhallasSilva** [comment]
Solicita também uma extensão para o https://mundohentaioficial.com/

E avisa que o all.foolslide
leitura.baixarhentai.net está off já faz uma semana e o site está on, funcionando normalmente. Vlw kk

**Comment by alessandrojean** [comment]
I will take a look and try to make a extension.

**Comment by SnakeDoc83** [comment]
@alessandrojean Looks like this could be added to MMRCMS.
