### ISSUE TITLE
[Bug] Madara - isekaiscan.com error via tachiyomi &the webview only, opening in browser directly isekaiscan.com not error

### ISSUE THREAD

**Issue by gembulzzzz** [inorichi/tachiyomi-extensions#3368]
### Device information
- Tachiyomi version: 2373
- Android version: 9

### Source information
- Name: madara
- Extension version: 1.2.101

## Steps to reproduce
1. Open any manga or catalog from isekaiscan.com
2. Or open in webview

### Expected behavior
Open normally, like in browser
![Screenshot_20200601-044930](https://user-images.githubusercontent.com/66224080/83363395-4e8c7700-a3c3-11ea-811c-a27adf4a74e2.png)

### Actual behavior
Tachiyomi
![Screenshot_20200601-044959](https://user-images.githubusercontent.com/66224080/83363411-6fed6300-a3c3-11ea-9f4a-eaaa341803fa.png)

Webview tachiyomi
![Screenshot_20200601-040710](https://user-images.githubusercontent.com/66224080/83363361-26047d00-a3c3-11ea-82ac-9d478b0f867d.png)

**Comment by arkon** [comment]
Do the pages actually load in your browser?

**Comment by dominhhieu1405** [comment]
You can share for me Extensions for Madara Theme? My email: dominhhieu145@gmail.com Thanksa you!
