### ISSUE TITLE
[Bug] IsekaiScan: images don't open

### ISSUE THREAD

**Issue by warcayac** [inorichi/tachiyomi-extensions#3369]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 5.0.2

### Source information
- Name: all.madara
- Extension version: 1.2.101

## Steps to reproduce
1. From today, 31 May 2020, I cannot see any images for any manga/manwha from IsekaiScans, I get this error message "The image couldn't be loaded", when opening the image in webview, webpage shows this message "Domain suspended or not configured". The problem is with images only, new chapters are recognized, and I can open those new chapters from IsekaiScan.com without problem. I've previously cleaned cookies, cache, etc.

### Expected behavior
Image is displayed correctly.

### Actual behavior
Image cannot be loaded from source (IsekaiScan)

**Comment by SnakeDoc83** [comment]
It's the source's fault that images are broken; we can't fix that for them.

**Comment by Vayner** [comment]
From what I can see, the problems that IsekaiScan had should now be resolved.
