### ISSUE TITLE
[Source Request] <Neox Scanlator (pt-br)>

### ISSUE THREAD

**Issue by SonnyTK** [inorichi/tachiyomi-extensions#3382]
### Source Website
- Name: Neox Scanlator
- Link: https://neoxscans.com/
- Language(s): Português (Brazil)

**Comment by alessandrojean** [comment]
It's on the Madara extension.

**Comment by WhallasSilva** [comment]
need to update the domain. https://neoxscan.com/newsite for https://neoxscan.com/

**Comment by alessandrojean** [comment]
I will update.

**Comment by cApitaoP** [comment]
Olá teria como atualizar a extensão? https://neoxscans.com

**Comment by alessandrojean** [comment]
@cApitaoP o domínio que você informou redireciona para o https://neoxscans.net, que já é o utilizado pela extensão atualmente.
