### ISSUE TITLE
[Source Request] <Kuma Translation>

### ISSUE THREAD

**Issue by Cwavs** [inorichi/tachiyomi-extensions#3393]
### Source Website
- Name: Kuma Translation/Raw Kuma
- Link: https://rawkuma.com/
- Language(s): English

**Comment by SnakeDoc83** [comment]
1. Kuma Translation isn't the same thing as Raw Kuma.
2. Rawkuma.com seems to be for raws, not English scans.
3. There's already an extension for rawkuma.com.

Closing because this doesn't make sense.

**Comment by Cwavs** [comment]
Hm sorry, thats the link they provided on mangadex for their website
