### ISSUE TITLE
[Source Request] <Hiperdex and Toonily>

### ISSUE THREAD

**Issue by Mizora15** [inorichi/tachiyomi-extensions#3397]
# Source Website
- Name: Hipedex and Toonily
- Link: https://hiperdex.com and https://toonily.com/
- Language(s): English

### Other Details
These websites are great places where you can read manhwas and webtoons that aren't available at certain apps or other websites.

**Comment by AbdullahM0hamed** [comment]
Both of them are already in the Madara extension.
