### ISSUE TITLE
[Source Request] <Hitomi.la>

### ISSUE THREAD

**Issue by Mizora15** [inorichi/tachiyomi-extensions#3400]
### Source Website
- Name: Hitomi.la
- Link: https://hitomi.la
- Language(s): Multi-languages

### Other Details
It's a good website with vast library of Doujinshi and Original hentai mangas each with different languages you can choose.

**Comment by CarlosEsco** [comment]
#94

**Comment by Mizora15** [comment]
> #94

Is there already hitomi.la in the app? Which extension is it?
