### ISSUE TITLE
[Bug] <Mangahasu>: <Failed to bypass Cloudflare>

### ISSUE THREAD

**Issue by Drimakus** [inorichi/tachiyomi-extensions#3402]
### Device information
- Tachiyomi version: 0.9.2-2373 (standart, 6ee69ef4, 45)
- Android version: 10 (SDK 29)

### Source information
- Name: Mangahasu
- Extension version: 1.2.8

## Steps to reproduce
1. Tried to clean chapter cache, cookies ahd database. No result
2. Tried to clean data and cache from device settings. No result
3. Tried to open in webview. Page opens, but I cant access to chapters (they did not open)

### Other details
Then I access source and manga from chrome on device, I can see and read it. But inside tachiyomi it did not work. Also then I update the library, I can see the updates from Mangahasu
Example of error
![Screenshot_20200604-140552_Tachiyomi](https://user-images.githubusercontent.com/44806934/83751484-98998500-a66f-11ea-96d0-b7bdd1f1196a.jpg)

**Comment by mrsfn** [comment]
Same problem, but when I try to access chapters from web view Cloudflare opens. But I can't pass it cause when I check "I'm human" nothing happens. Also I can pass Cloudflare just fine if I go from web view to open manga in browser.

**Comment by raziel100** [comment]
Same problem here, I could make work by just putting the chapter to download. After 2 to 3 tries it start to work just fine. Is better than nothing.

**Comment by E3FxGaming** [comment]
@mrsfn Actually you can pass the hcapatcha test. It's not pretty by any means, but as far as I can tell, at least for one session, you only have to do it once.

By debugging the hcapatcha webview with the desktop Google Chrome application I found this:
![image](https://user-images.githubusercontent.com/8276268/84015099-aacf3800-a97b-11ea-8e5e-134c89daa83a.png)

The debugger has a stupid resolution, but maybe you can somewhat recognize that the stuff in the top is where you ticked the "I'm human" checkbox and in the middle there actually are the pictures where you need to select some. You just have to scroll down by swiping up a whole bunch, until you finally see the pictures.

After you passed the hcapatcha with the webview you'll be forwarded to the manga website. At that point you can close the webview and select the manga normally (how you would usually select manga in Tachiyomi).

**Comment by RhakieVenice** [comment]
It works for me after I opened the manga in webview and then open it in browser, you must use chrome for it and select the desktop version and wait for the captcha and solve it. You can try as many times if it still won't work and go back to tachiyomi and download.

**Comment by mrsfn** [comment]
@E3FxGaming thx, that helped.

**Comment by SnakeDoc83** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/3475
