### ISSUE TITLE
[Source Request] <Rawdevart>

### ISSUE THREAD

**Issue by Mizora15** [inorichi/tachiyomi-extensions#3409]
### Source Website
- Name: Rawdevart
- Link: https://rawdevart.com/
- Language(s): Japanese

### Other Details
A good website that provides raw mangas especially for those who can't wait for updates and read japanese.

**Comment by SnakeDoc83** [comment]
There's already an extension for it.

**Comment by Mizora15** [comment]
Really? Which one?
