### ISSUE TITLE
[Feature Request] FMReader: remove manga titles from chapter names

### ISSUE THREAD

**Issue by AriaMoradi** [inorichi/tachiyomi-extensions#3420]
### What feature should be added to this source?
with this manga from LHT: https://lhtranslation.net/manga-shikkaku-mon-no-saikyou-kenja.html
one chapter name looks like this: 
`SHIKKAKU MON NO SAIKYOU KENJA - SEKAI SAIKYOU NO KENJA GA SARA NI TSUYOKUNARU TAME NI TENSEI SHIMASHITA Chapter 34`
the only real useful information is `Chapter 34`, but it's out of reach because the chapter name is so damn long that even in landscape mode you couldnt read it
this redundancy should be removed.

**Comment by WhallasSilva** [comment]
just change in preview mode / font title> Chapter number

**Comment by NorseFenris** [comment]
If you press the 3 dots in the upper corner when viewing the chapter list, then go to "Display mode" and choose "Chapter number", you will get exactly what you asked for.

**Comment by AriaMoradi** [comment]
I was not aware of this feature, but all and all sometimes there's just not the chapter number that is unreachable, is some cases actual chapter titles are not visible due to the same problem
