### ISSUE TITLE
[Meta] CONTRIBUTING.md: more sophisticated documentation

### ISSUE THREAD

**Issue by AriaMoradi** [inorichi/tachiyomi-extensions#3423]
###  Why/Project's Benefit/Existing Problem
- `Useful knowledge` is really poorly written and is missing some really vital information, yet:
   - it just throws some hints about things, I had to deliberately break existing code and debug the app to uncover some of the api
    -   some of the extension api is not explained at all, i.e. clinet , chapter, manga
    -   extension workflow(how and when methods are called) is not explained well, and only having stubs to work with doesnt hep at all
- there should be a general template for a extension, reading and copying other extensions is not really usefull 

## final thoughts 
I was able to contribute to `Paprika` because I had to just change a few links and selectors, if i where to write an extension from scratch it would never be possible

**Comment by arkon** [comment]
A PR for updated documentation would be helpful.

**Comment by AriaMoradi** [comment]
I'm going too collect some thoughts and information here, then maybe compose them in a meaningful  manner

**Comment by AriaMoradi** [comment]
## general info
- the bridge between the app and you extension is the [extention-lib](https://github.com/inorichi/tachiyomi-extensions-lib), but it only contains stubs and the actual implementations are in the [app](https://github.com/inorichi/tachiyomi) inside `eu.kanade.tachiyomi.source` package, reading the code inside there will help you in writing your extension.
- you are encouraged to clone the app itself and make your own debug build so you can attach android-studio to the app, then you can print logs in the code and debug your code from inside `Logcat`, directly debugging your extension(steeping through your extension code) is not possible, but if you keep both projects open in android studio, you can debug the app itself.
- your `extClass`(inside `build.gradle`) class should be inherited from either `SourceFactory` or one of `Source` children: `CatalogueSource` or `HttpSource` or `ParsedHttpSource`. you mostly want to use one of the last two.
- `HttpSource` as in it's name is for a online http(s) source, but `ParsedHttpSource` has a good model of work which makes writing scrapers for normal aggregator websites much easier and streamlined. (you can find the implementation of the stubs in the app as mentioned above)  

## extension workflow

**Comment by AriaMoradi** [comment]
## extension workflow

**Comment by CarlosEsco** [comment]
nothing should be using CatalogueSource.  It should be ParsedHttpSource 99.9% of time

**Comment by AriaMoradi** [comment]
> nothing should be using CatalogueSource. It should be ParsedHttpSource 99.9% of time
noted.

**Comment by AriaMoradi** [comment]
I think pretty much I gathered what's needed here.
moving to pull request phase.
comment any changes and opinions on there

**Comment by AriaMoradi** [comment]
@arkon thanks for the merge
There still a few things I'd like to add:
- Filter(also if documentation code is written in the app that would be nice, so maybe open an issue there)
- ConfigurableSource
- Manga.initialized

**Comment by AriaMoradi** [comment]
going to accumulate my points and added them sometime in the future
