### ISSUE TITLE
[Source Request] Erofus

### ISSUE THREAD

**Issue by IRohit789** [inorichi/tachiyomi-extensions#3424]
---

### Source Website
- Name: Erofus
- Link: https://www.erofus.com/
- Language(s): English

### Other Details
Collection of western adult comics along with hentai.

**Comment by AriaMoradi** [comment]
I checked the site and the structure is quite complex, even I think each section may need a separate extension

**Comment by AriaMoradi** [comment]
IMO the structure doesn't quite fit the current extension model
