### ISSUE TITLE
[Bug] <MANGA Plus by SHUEISHA>: <Manga status bug>

### ISSUE THREAD

**Issue by NorseFenris** [inorichi/tachiyomi-extensions#3427]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 9

### Source information
- Name: MANGA Plus by SHUEISHA
- Extension version: 1.2.7

## Steps to reproduce
1. Add completed manga from source.
2. Check status under info tab.

### Expected behavior
Status should be "Completed".

### Actual behavior
Status shows ""Ongoing".

**Comment by alessandrojean** [comment]
As far as I know, the MangaPlus API and website does not provide the status information. Since almost all mangas from the service are simulpubs, the extension mark the titles as ongoing, as there is no way to determine that.

**Comment by NorseFenris** [comment]
![Anteckning 2020-06-07 050555](https://user-images.githubusercontent.com/66540317/83959378-a6702580-a87c-11ea-81a6-5c91e3c838d0.png)

The website definitely does provide that info. I don't know about the API though.

**Comment by alessandrojean** [comment]
Oh, this should be a recent modification on the website, so probably the API have this info too.

I will take a look if this can be implemented in the extension.
