### ISSUE TITLE
[Bug] onma (arabic) not working

### ISSUE THREAD

**Issue by alucardlucilfer** [inorichi/tachiyomi-extensions#3430]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 10

### Source information
- Name: CMS (onma) ( مانغا اونلاين = manga online)
 Extension version: 1.2.42

## Steps to reproduce
1. Open Onma
2. Choose a manga

### Expected behavior
Showing manga

### Actual behavior
Source not working Failed to bypass cloudflare

### Other details
Failed to bypass cloudflare

**Comment by SnakeDoc83** [comment]
Open in webview, wait for captcha to load, solve captcha, reload onma.

**Comment by alucardlucilfer** [comment]
Thanks it is working
