### ISSUE TITLE
[Source Request] <smackjeeves>

### ISSUE THREAD

**Issue by sohilsayed** [inorichi/tachiyomi-extensions#3431]
### Source Website
- Name: SmackJeeves
- Link: https://www.smackjeeves.com/
- Language(s): English and Spanish

### Other Details
They Have Comico Comics like Kakao 79% and Relife in english

**Comment by SnakeDoc83** [comment]
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/3079
