### ISSUE TITLE
[Source Request] Bato.to

### ISSUE THREAD

**Issue by avitari14** [inorichi/tachiyomi-extensions#3436]
### Source Website
- Name: Batoto
- Link: bato.to
- Language(s): English

### Other Details
Before Mangatensei's extension cease to exist, it came along with Batoto as a source which I find quite useful for its library. But ever since the extension not existing anymore I can't open all the bookmarked manga/manhwa from Batoto anymore, I hope you can re-add the source as it contain a lot of series that mostly doesn't exist in other sources.

**Comment by SnakeDoc83** [comment]
It's in the Emerald extension now.

**Comment by avitari14** [comment]
> It's in the Emerald extension now.

Thanks for telling, I didn't know if the extension changed its name
