### ISSUE TITLE
mangago.me (EN) Source Request

### ISSUE THREAD

**Issue by skyfall448** [inorichi/tachiyomi-extensions#3439]
---

### Device information
* Tachiyomi version: Latest
* Android version: 10
* Device: Samsung Galaxy Tab 6 Lite (and it looks freakin' amazing)

## Issue/Request
Just wondering if you could add the website mangago to the list of sources.
English translations, has a lot of variety of all types of eng manga but also larger variety of shoujo and bl and yaoi stuff

## Other details
website link is here: http://www.mangago.me/

Thank you for your services!

**Comment by CarlosEsco** [comment]
#988
