### ISSUE TITLE
[Meta] general extension template

### ISSUE THREAD

**Issue by AriaMoradi** [inorichi/tachiyomi-extensions#3440]
as I said in #3423 there should be a general extension template, lets talk about it here.

**Comment by AriaMoradi** [comment]
I think making a [cookiecutter](https://github.com/cookiecutter/cookiecutter) may not be a bad idea.
what do others think?

**Comment by CarlosEsco** [comment]
1.  a general extension template doesn't work for most sources.
2.  not a fan of adding a 3rd application to generate a template

**Comment by ObserverOfTime** [comment]
The stubs in [tachiyomi-extensions-lib](https://github.com/inorichi/tachiyomi-extensions-lib/tree/master/library/src/main/java/eu/kanade/tachiyomi/source/online) are basically extension templates.
