### ISSUE TITLE
[Bug] unable bypass couldflare

### ISSUE THREAD

**Issue by hostkit** [inorichi/tachiyomi-extensions#3442]
### Device information
- Tachiyomi version: preview r2402
- Android version: 9

### Source information
- Name: wp manga stream
- Extension version: 1.2.14

Sometime unable access chapter because unable bypass couldflare. We must open via browser tachiyomi to continue reading chapter after bypass cloudflare

**Comment by SnakeDoc83** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/3475
