### ISSUE TITLE
[Bug] <Mangabox-Mangakakalkt>: <I am unable to search in Mangakakalot>

### ISSUE THREAD

**Issue by Jdoe1990** [inorichi/tachiyomi-extensions#3444]
A few hours ago I lost the ability to search for manga on mangakakalot from the Mangabox extention. Anything I search outputs no results. Currently it's just the mangakakalot source that is giving this issue. Help would be appreciated 

---

### Device information
- Tachiyomi version: 0.9.2
- Android version: 10

### Source information
- Name: Mangabox
- Extension version: 1.2.22

## Steps to reproduce
1. Click browse mangakakalot
2. Search for anything and it says no results. 

### Expected behavior
I should be able to find manga using search

### Actual behavior
The search outputs no results

**Comment by SnakeDoc83** [comment]
Closed by https://github.com/inorichi/tachiyomi-extensions/pull/3449
