### ISSUE TITLE
[Source Request] Mangago

### ISSUE THREAD

**Issue by N3K0N1** [inorichi/tachiyomi-extensions#3448]
# Source Website
- Name: Mangago
- Link: http://www.mangago.me/
- Language(s): English

### Other Details
It has many good mangas and webtoons and updates them regularly.

**Comment by SnakeDoc83** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/988

**Comment by AbdullahM0hamed** [comment]
We had this once upon a time, and it was really difficult to maintain (as I'm told). I'm not feeling optimistic about this one.

**Comment by N3K0N1** [comment]
That's too bad :'(
