### ISSUE TITLE
Stance on support for Japanese official sites

### ISSUE THREAD

**Issue by chocolatkey** [inorichi/tachiyomi-extensions#345]
What is the stance here on making extensions for official Japanese sites? For example, I'd like to add support for all of hatena's gigaviewer sites (https://shonenjumpplus.com, https://tonarinoyj.jp/, https://pocket.shonenmagazine.com etc.) in the future, but don't want to do this if it's against some sort of rules.

**Comment by CarlosEsco** [comment]
As long as it's a free source I don't see any issue.

**Comment by NoodleMage** [comment]
No worries. Good luck on implementing :)

**Comment by chocolatkey** [comment]
Thanks. One more question if I may ask: What is the general stance on adding intents (a.k.a. click on the Japanese viewer link in browser, offers to open with the app) and requiring credentials for certain sites (in the future)?
Interested in the intents because some of the Japanese platforms don't have real latest + search + directory concepts, so offering to open with the app would be a compromise.
Interested in the credentials because many of the Japanese sites are also stores, so would want to allow reading purchased content with e.g. PUBLUS platforms

**Comment by inorichi** [comment]
> What is the general stance on adding intents (a.k.a. click on the Japanese viewer link in browser, offers to open with the app) and requiring credentials for certain sites (in the future)?

I've already done this on the 1.x branch, but I don't think it'll reach the 0.x releases. I don't know how long it will take for the first 1.x release, though.

**Comment by chocolatkey** [comment]
Well that's great news. Does 1.x run well enough to develop for it?

**Comment by CarlosEsco** [comment]
no.  Its not at that stage yet.

**Comment by chocolatkey** [comment]
OK. I'll try and add as much as I can that doesn't need those capabilities and hope 1.x comes around in the near future. Thanks for the replies

**Comment by as280093** [comment]
@arkon mark this source request or should it be closed
