### ISSUE TITLE
[Source Request] Fakku.net

### ISSUE THREAD

**Issue by DiabloPiotr** [inorichi/tachiyomi-extensions#3460]
### Source Website
- Name: Fakku
- Link: https://www.fakku.net/
- Language(s): English

**Comment by CarlosEsco** [comment]
will leave open for @SnakeDoc83  to address.  But probably will be closed as its paid subscription site? 
https://github.com/inorichi/tachiyomi-extensions/issues/209

**Comment by AriaMoradi** [comment]
I was waiting for someone to ask for this!

**Comment by DiabloPiotr** [comment]
I was surprised that noone asked so far. I checked three times to make sure that there's no extension already.

**Comment by SnakeDoc83** [comment]
As far as I can tell there's ~25 free doujinshi (that would require login to read) and a free 2 week trial but beyond that you'd need to buy a subscription.  If you have a subscription you'd be better off using their app; what's free doesn't amount to enough to outweigh the hassle an extension would bring.  

I think there are some extensions that have Fakku content already, use one of those or find a site that has their content and request that.
