### ISSUE TITLE
[Bug] xkcd: missing Cover

### ISSUE THREAD

**Issue by keinezeit8** [inorichi/tachiyomi-extensions#3461]
### Device information
- Tachiyomi version: J2K 1.0.7
- Android version: 10 June Patch

### Source information
- Name: xkcd
- Extension version: 1.2.6

## Steps to reproduce
1. Install xkcd extension
2. Subscribe to xkcd

### Expected behavior
The Cover should be shown in the library

### Actual behavior
The cover is just black and cannot be changed

### Other details
Similar to #3317 
I also tried reinstalling the extension

**Comment by AriaMoradi** [comment]
fix: implement fetchMangaUpdate
