### ISSUE TITLE
[Bug] Kill Six Billion Demons: Only The First Page Showing Up. 

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi-extensions#3462]
### Device information
- Tachiyomi version: r2402
- Android version: 6.0.1

### Source information
- Name: Kill Six Billion Demons.
- Extension version: 1.2.1.

## Steps to reproduce
1. Open a chapter from the source.
2. Glance through the pages.

### Expected behavior
All the pages of the chapter show up, like it usually would.

### Actual behavior
Only the first page of a chapter shows up for every page, i.e, it's all just page 1s.

### Other details
None.

**Comment by AriaMoradi** [comment]
Wow i can't believe how things broke!
I Even have a whole book downloaded
