### ISSUE TITLE
My Anime List free manga

### ISSUE THREAD

**Issue by Cwavs** [inorichi/tachiyomi-extensions#3466]
# Source information
* Source name: My Anime List Free Manga
* Source extension version: 1.2.1

## Steps to reproduce
1. Browse Manga

## Issue/Request
It seems mal free manga has quietly dissapeared, as such this extension no longer works and should be removed

## Other details
Wasn't sure what to put this under so I just put it in a blank file.

**Comment by alessandrojean** [comment]
That's sad :(

I will submit a PR later to remove the extension then.
