### ISSUE TITLE
[Bug] mangadex: Data saver not working

### ISSUE THREAD

**Issue by heksagen** [inorichi/tachiyomi-extensions#3467]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 8,0

### Source information
- Name: mangadex
- Extension version: 1.2.92

## Steps to reproduce
1. Enable data saver
2. Open any chapter

### Expected behavior
should load a compressed image of the chapter

### Actual behavior
The original uncompressed image is loaded instead of the compressed image

### Other details
I tried reading on mangadex website and the data saver is working fine, i think this is supposed to be an extension bug

**Comment by CarlosEsco** [comment]
Mangadex disabled data saver while they are rolling out md@home. Keep it enabled and when they bring back server side it will work again
