### ISSUE TITLE
[Bug] NineAnime: Can't read any chapter

### ISSUE THREAD

**Issue by AMZMA** [inorichi/tachiyomi-extensions#3476]
### Device information
- Tachiyomi version: J2K 1.0.7
- Android version: 10

### Source information
- Name: NineAnime
- Extension version: 1.2.2

### Other details
Cant read any chapter from any manga.

Error when open any chapter
![Screenshot_2020-06-10-15-54-43-346_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/1856088/84243463-cf224480-ab34-11ea-8bbb-65fae6f289e7.jpg)

All fine on web view
![Screenshot_2020-06-10-15-55-14-492_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/1856088/84243556-f416b780-ab34-11ea-9400-e2454cf2f6c3.jpg)

**Comment by SnakeDoc83** [comment]
Can't reproduce. Try clearing cache and database and then check again.

**Comment by AMZMA** [comment]
it isnt work either.
video (clearing cache, etc)
https://puu.sh/FUY8Y.mp4

I found that, it will work if I turned off my VPN and then cleared cookies.
I do not know why this extension refuse to work with VPN even though it's all fine in webview. I tried 2 different VPN, still wont work.
All other extensions works flawlessly with VPN.

**Comment by SnakeDoc83** [comment]
There's going to be an update, it may or may not help. Unfortunately if it doesn't help I don't think there will be anything more we can do on this end; you'll just have to avoid using this extension with a VPN.
