### ISSUE TITLE
[Bug] Mangasee: Not able to browse source or read chapters

### ISSUE THREAD

**Issue by radus1682** [inorichi/tachiyomi-extensions#3491]
Cannot browse Mangasee sourse and the manga chapters in the library from Mangasee source are not loading.
---

### Device information
- Tachiyomi version: Stable 0.9.2
- Android version: 9

### Source information
- Name: Mangasee
- Extension version: 1.2.7

**Comment by SnakeDoc83** [comment]
Seems fine to me. What happens when you try to browse or open a chapter?

**Comment by radus1682** [comment]
Was not working the whole day, now it seems fine. I'll close the issue.

**Comment by radus1682** [comment]
It looked okay then, but I'm having the same issue again. I tried reinstalling the extension and even the app. It's not working still.
![Recording_2020-06-12-15-14-05(1)](https://user-images.githubusercontent.com/42824894/84490646-14737d00-acc1-11ea-8955-8b4061404d23.gif)

**Comment by CarlosEsco** [comment]
Is it working for you in webview?

**Comment by radus1682** [comment]
Webview is working fine.

**Comment by radus1682** [comment]
Sources other than Mangadex are not working. Found this just now. I use Mangasee and Mangadex primarily, so I didn't check others.

**Comment by amagura** [comment]
Just installed Mangasee; it isn't even showing up in the list of sources.

**Comment by radus1682** [comment]
> Just installed Mangasee; it isn't even showing up in the list of sources.  

Check the filter, it may be hidden.

**Comment by amagura** [comment]
> > Just installed Mangasee; it isn't even showing up in the list of sources.
> 
> Check the filter, it may be hidden.

Thanks, that was it.  >.>

**Comment by radus1682** [comment]
I don't know what happened, why it happened, I didn't do anything or anyone else did for that matter, but this issue got resolved on its own today.
