### ISSUE TITLE
[Bug] MangaMx: Pages not loading

### ISSUE THREAD

**Issue by MerradOklom** [inorichi/tachiyomi-extensions#3492]
---

### Device information
- Tachiyomi version: 0.9.2
- Android version: Oreo

### Source information
- Name: MangaMx
- Extension version: 1.2.7

## Steps to reproduce
1. Open a manga's chapter

### Expected behavior
Pages load normally

### Actual behavior
Somehow the reader only grabs 1 page and try to load it infinitely.

### Other details
![olakease](https://user-images.githubusercontent.com/43864503/84380810-6089c900-abbe-11ea-9753-6627ec2bce71.png)

**Comment by E3FxGaming** [comment]
I give up trying to fix this, maybe someone else can fix it.

Here my notes/what I found so far:

- The website moved a javascript function (from which we previously retrieved the pages information) from the website which we load into a separate lector.js file

- okhttp can't evaluate the javascript, jsoup doesn't do it and duktape is not embedded enough to do it. The page we load makes it look like there is only one page and real browsers only populate the pages selector after the html loaded with the javascript function

- This is probably something for someone who knows how to do it with webview
