### ISSUE TITLE
[Site Request] Kisscomic.us

### ISSUE THREAD

**Issue by strugler** [inorichi/tachiyomi-extensions#35]
Can you please add http://kisscomic.us/  as an english catalogue for comics?

**Comment by CarlosEsco** [comment]
Does this website still work for you?  I just get cloudflare just a moment and it nevers moves on

**Comment by arkon** [comment]
It was replaced by readcomiconline, I believe.

**Comment by AmineI** [comment]
Just checked in Kiss Community's Discord (see the archive channel), and arkon is right, that was confirmed to be replaced by readcomiconline, hence this address being down
