### ISSUE TITLE
Question: Plan to move all tachiyomi sources to extensions?

### ISSUE THREAD

**Issue by captn3m0** [inorichi/tachiyomi-extensions#350]
The various sources at https://github.com/inorichi/tachiyomi/tree/master/app/src/main/java/eu/kanade/tachiyomi/source/online are not part of this repo.

Is there any plan to move them here?

I'm planning to work on a [tachiyomi-headless](https://github.com/captn3m0/ideas#tachiyomi-headless) app which would run without Android on my server and it would be much more easier to build if all the sources were in a single place and in the same format

**Comment by wopian** [comment]
All of the sources in that link already have an extension. Sources still built into Tachiyomi will be overrided if you install their extension.

**Comment by captn3m0** [comment]
Thanks! Should have looked more closely before asking.
