### ISSUE TITLE
[Meta] empty fetchSearchManga helper

### ISSUE THREAD

**Issue by AriaMoradi** [inorichi/tachiyomi-extensions#3502]
###  Why/Project's Benefit/Existing Problem
Apparently when for some reason a source doesn't have searching functionality, the standard way of telling the app "we don't do that here" is  doing this code:
```Kotlin
override fun fetchSearchManga(page: Int, query: String, filters: FilterList): Observable<MangasPage> = Observable.just(MangasPage(emptyList(), false))
```
how about making a little helper function to make it easier?
added to `HttpSource.kt`:
```Kotlin
fun emptySearchManga(): Observable<MangasPage> = Observable.just(MangasPage(emptyList(), false))
```
so we could write this kind of code:
```Kotlin
override fun fetchSearchManga(page: Int, query: String, filters: FilterList): Observable<MangasPage> = emptySearchManga()
```

**Comment by arkon** [comment]
That's not going to happen since it needs to stay compatible with 0.8.5.

That said, 0.8.5 contains the fix for handling search exceptions, so I think it should be fine if that method just throws an exception now.
