### ISSUE TITLE
[Bug] Mangalib: can't download or read

### ISSUE THREAD

**Issue by Im1not2your3toy** [inorichi/tachiyomi-extensions#3509]
### Device information
- Tachiyomi version: stable 0.9.2
- Android version: 9

### Source information
- Name: Mangalib
- Extension version: 1.2.18

## Steps to reproduce
1. Add last chapter of this title https://mangalib.me/nanen-doel-nomid to download queue
2. Retry downloading it

### Expected behavior
The chapter downloads

### Actual behavior
Error occurs com.google.gson.stream.MalformedJsonExc...

### Other details
The source opens in web-view just fine but when you try to read the chapter you're faced with endless loading image. Happened with this title as well https://mangalib.me/tensei-shitara-slime-datta-ken but at first it did download in .htm format (ofc not readable though)

**Comment by SnakeDoc83** [comment]
Merged https://github.com/inorichi/tachiyomi-extensions/pull/3501 after you posted.
