### ISSUE TITLE
NHentai

### ISSUE THREAD

**Issue by SKYARKA** [inorichi/tachiyomi-extensions#351]
https://nhentai.net/tags/popular
BUGS:tachi 0.7.4/////NHentai 1.2.0
error 403

**Comment by LakotaGray** [comment]
So a note on Nhentai... this has happened before. And like last time, anything already saved to library, even if not downloaded can still be viewed. Or when you go to source and error pops up at the bottom, type in a search and it still works. It seems only the initial catalogue view isn’t working

**Comment by arkon** [comment]
@CarlosEsco This can be closed. It's an intermittent issue with their API (which we no longer use anyway).
