### ISSUE TITLE
[Bug] Neox Scanlator: Chapters doesn't show in Updates List

### ISSUE THREAD

**Issue by maz1no** [inorichi/tachiyomi-extensions#3511]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 8.1.0

### Source information
- Name: Neox Scanlator (Madara's multiple sources)
- Extension version: 1.2.107

## Steps to reproduce
1. Adding the title to the library
2. New chapters come, but they doesn't show in the Updates List

### Other details
Although I can see the new chapters going manually in the Library
Also, chapters don't have dates

**Comment by alessandrojean** [comment]
I don't know if new chapters not showing up in the Updates List have any relation to dates not showing up in the Chapter List, but probably it will be fixed by #3512.

**Comment by maz1no** [comment]
Both fixed, thank you guys.
