### ISSUE TITLE
[Bug] <nhentai.net>: <i can't login to my nhentai account on web view>

### ISSUE THREAD

**Issue by Yukiharuyuu217** [inorichi/tachiyomi-extensions#3516]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 6.0.1

### Source information
- Name: nhentai.net
- Extension version: 1.2.21

### Expected behavior
I thought i can saw my favourite nhentai list
### Actual behavior
When i click the menu to see the option for login, they won't show up

### Other details
![IMG_20200613_180319](https://user-images.githubusercontent.com/66869884/84567042-3d1e7400-ada0-11ea-9fd5-ba2280203df9.jpg)

**Comment by arkon** [comment]
This will be fixed for the next stable app release.
