### ISSUE TITLE
[Bug] NetTruyen: Error loading chap

### ISSUE THREAD

**Issue by Noname-noragami** [inorichi/tachiyomi-extensions#3517]
### Device information
- Tachiyomi version: 9.2
- Android version: 7.0

### Source information
- Name: NetTruyen
- Extension version: 1.2.5

## Steps to reproduce
1. Go-to the manga
2. Second Step open old chapter

### Expected behavior
Load successful

### Actual behavior
Old chap don't load, always say reload.

### Other details
 Chapter can read at website

**Comment by SnakeDoc83** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/2899
