### ISSUE TITLE
[Source Request] mê đọc truyện

### ISSUE THREAD

**Issue by Noname-noragami** [inorichi/tachiyomi-extensions#3519]
### Source Website
- Name: mê đọc truyện, vnstory
- Link: https://www.medoctruyentranh.net/
- Link 2: https://m.www.medoctruyentranh.net/
- Link 3: www.vnstory.xyz
- Language(s): VI,VN

**Comment by SnakeDoc83** [comment]
Already exists.

**Comment by Noname-noragami** [comment]
But it only 50 chap
