### ISSUE TITLE
IuTruyenTranh and TruyenTranhLh not recognized by the app

### ISSUE THREAD

**Issue by Jendrej** [inorichi/tachiyomi-extensions#352]
The two extensions don’t show up in the extensions list or in the catalogues menu after installing.

App version: r1419
Extension version: 1.0.1 for both

**Comment by CarlosEsco** [comment]
@inorichi.  Not near computer this weekend but I'm guessing this is main app issue?

**Comment by inorichi** [comment]
Package name doesn't match the extensions pattern.

**Comment by CarlosEsco** [comment]
I'll adjust it later then
