### ISSUE TITLE
Missing pages + Page list is empty in MyReadingManga

### ISSUE THREAD

**Issue by missimperfect** [inorichi/tachiyomi-extensions#353]
Tachiyomi version: 0.7.4
MyReadingManga version: 1.2.1

I'm not sure if I'm the only facing this problem but some(?) of the chapters of the manga I'm reading are missing few pages (be it it's the credit/cover/the manga pages itself). In addition, when I tried to open a chapter the response the app gave me is 'Page list is empty' and doesn't show the content of the chapter at all whereas the actual website itself has the chapter available to be read. Hope this will be solved soon. Thank you!

**Comment by missimperfect** [comment]
Ok, I'm not sure if I'm doing this correctly or not. So: **The first image is of MRM in Tachiyomi**
![screenshot_2018-06-20-05-08-01](https://user-images.githubusercontent.com/40125698/41665535-623ac724-74d2-11e8-9be2-e8b9de768be1.png)

**The second and third image is how the chapter in the MRM website is supposed to be**
![screenshot_2018-06-20-05-14-34](https://user-images.githubusercontent.com/40125698/41665885-4d40c5fc-74d3-11e8-84ef-1703b68dc649.png)
![screenshot_2018-06-20-05-13-17](https://user-images.githubusercontent.com/40125698/41665886-4d783730-74d3-11e8-8c19-9268996a4037.png)

The first 3 images is about the **missing pages**. While the next pictures are about **'Page list is empty'** problem:

**MRM in Tachiyomi**
![screenshot_2018-06-20-05-17-27](https://user-images.githubusercontent.com/40125698/41665995-9e709268-74d3-11e8-99f9-c97bb660c3c3.png)

**The chapter in MRM website**
![screenshot_2018-06-20-05-20-02](https://user-images.githubusercontent.com/40125698/41666030-ba2301f8-74d3-11e8-901c-8e19980f066a.png)

The **'Page list is empty'** happens only for the **7th chapter** when I clicked on it. I haven't really clicked on every chapter of the manga, except the ones that I have clicked has no problem loading the chapter at all.

In addition, this is just something that I found yesterday:
![screenshot_2018-06-20-06-10-40](https://user-images.githubusercontent.com/40125698/41666180-14e70878-74d4-11e8-9f6b-f88f264bae5a.png)

I have tried to change the **Image decoder** to every option possible but it still won't load the images of the next chapter nor when I clicked on the chapter itself.

Thank you.

**Comment by CarlosEsco** [comment]
still have this issue?

**Comment by missimperfect** [comment]
@CarlosEsco Hi, I'm still having the same issues. I've updated Tachiyomi to version 0.8.0, and after that I've updated my MRM extensions to version 1.2.8. But I'm still facing the same problem when I tried to read the chapters that I've screenshot above. Not sure if I'm the only one who's facing these issues.

**Comment by CarlosEsco** [comment]
What manga

**Comment by CarlosEsco** [comment]
pushed new build make sure to clear cache, cookies, db. if manga is in your library already swipe to refresh chapters and manga info.  

Also i hate how this site is setup.  Why cant they have a page per a manga like normal sites

**Comment by missimperfect** [comment]
@CarlosEsco Sorry in replying so late. I've tried to clear the cache, cookies, db and swipe to refresh as well and I've updated my extension of MRM to 1.2.9 while I can already access the chapters that has 'Page list is empty' option but I'm encountering this problem instead:

![screenshot_2018-10-16-03-16-26](https://user-images.githubusercontent.com/40125698/46974461-40a2b900-d0ee-11e8-8840-6ad5b900a054.png)

I have **double pages** for each chapter. And it's either an immediate the next page is the same page or:

![screenshot_2018-10-16-03-10-46](https://user-images.githubusercontent.com/40125698/46974544-83649100-d0ee-11e8-80a8-2f286c57f084.png)
![screenshot_2018-10-16-03-10-58](https://user-images.githubusercontent.com/40125698/46974550-85c6eb00-d0ee-11e8-84f9-e3d6515912ab.png)

And using the the same above picture, another problem which is the **missing pages** that I've mentioned:

![screenshot_2018-10-16-03-13-42](https://user-images.githubusercontent.com/40125698/46974669-e2c2a100-d0ee-11e8-9918-66601a2cf393.png)
![screenshot_2018-10-16-03-13-51](https://user-images.githubusercontent.com/40125698/46974676-e6eebe80-d0ee-11e8-89ca-35a62bfb15df.png)

And this still occurs for one of the chapters of Honto Yajuu:

![screenshot_2018-10-16-03-19-30](https://user-images.githubusercontent.com/40125698/46974734-0f76b880-d0ef-11e8-917f-1d2ea51bcd15.png)

Am I doing any step wrong, or should I just uninstall and install Tachiyomi again? Thanks for all the help though

**Comment by CarlosEsco** [comment]
What's the manga and chapter

**Comment by missimperfect** [comment]
@CarlosEsco Double pages: Hana to Junketsu: chapters 1-7, but most of the manga that's in MRM are double in pages.

Missing pages: Deichuu no Hasu chapter 5 and 6 (not sure about others).

'Retry': Honto Yajuu - volume 8 chapter 2

Thanks

**Comment by CarlosEsco** [comment]
Latest update fix this?

**Comment by missimperfect** [comment]
@CarlosEsco Yes it did. Thank you very much :))
