### ISSUE TITLE
[Bug] manga plus: can't download chapters

### ISSUE THREAD

**Issue by pajiraw** [inorichi/tachiyomi-extensions#3536]
- Tachiyomi version: 0.9.2
- Android version: 8.1
- Extension version: 1.2.9

after the latest update, im tapping the download button many times. but nothing is happening.

**Comment by alessandrojean** [comment]
That's weird. 

Can you read the chapters without download or access the site in WebView or browser?

**Comment by pajiraw** [comment]
yes to both

**Comment by pajiraw** [comment]
ok i see the problem. the chapter was already downloaded, but tachiyomi is not indicating that it is downloaded.
That means that I will have to delete all the chapters then download them again so that tachiyomi displays them correctly as downloaded which is insane (download directory did not change).
also the download badges are not showing for all the manga i had in my library from this source.

**Comment by alessandrojean** [comment]
That's really weird. Did you have any thoughts, @arkon?

**Comment by pepe1987** [comment]
Same here MANGA PLUS V1.2.9 I can't download new chapters, deleting the folder doesn't solve the problem, I got an error "downloadsDir ...y(getMangaDirName(manga)) must not be null"

**Comment by arkon** [comment]
If you did manage to redownload something, did any of the folder names differ?

**Comment by arkon** [comment]
For those that already had downloaded content, try this:

1. Close Tachiyomi.
1. Rename your existing `Manga Plus by Shueisha` to something like `Manga Plus by Shueisha 2`.
1. Rename that again to `MANGA Plus by SHUEISHA`.
1. Try seeing if your downloads show up in Tachiyomi.

**Comment by alessandrojean** [comment]
Is there any possible fix to this issue in the main app, or is it better to change the source name to the old one?

**Comment by pepe1987** [comment]
the new folder is MANGA Plus by SHUEISHA (ES), still cant download anything

**Comment by SnakeDoc83** [comment]
Deleting the folder fixes it.

**Comment by arkon** [comment]
I'll wait to see if someone can actually confirm my suspicion.

**Comment by arkon** [comment]
@pepe1987 Did you do what I suggested with renaming the original folder, or do you have both?

**Comment by pepe1987** [comment]
Restarting my device fixed it. Now i can download from shueisha.

@arkon No, as I mentioned before, I had deleted the folder.

**Comment by pajiraw** [comment]
> For those that already had downloaded content, try this:
> 
> 1. Close Tachiyomi.
> 2. Rename your existing `Manga Plus by Shueisha (EN)` to something like `Manga Plus by Shueisha (EN) 2`.
> 3. Rename that again to `MANGA Plus by SHUEISHA (EN)`.
> 4. Try seeing if your downloads show up in Tachiyomi.

nope. if anything, it removed the "downloaded" indication for the chapter that i deleted and downloaded again ie reset everything to how it was after the extension update.

**Comment by arkon** [comment]
Did you restart your phone too?

**Comment by pajiraw** [comment]
no. will try

**Comment by pajiraw** [comment]
ok just force close tachiyomi made it work. but still one must edit the name manually. i really hate this. really unnecessary change in the first place.

**Comment by Sekuiya** [comment]
Also wanted to inform that had the bug, but force stopping the app and renaming the folder as instructed fixed it.
All the downloaded showed up again and able to download.

**Comment by SnakeDoc83** [comment]
Going to close this but leave it pinned for a while.
