### ISSUE TITLE
Self-claiming of ComiCake extension

### ISSUE THREAD

**Issue by chocolatkey** [inorichi/tachiyomi-extensions#354]
Hi, just wanted to let people who write extensions know that I'm already working on an extension for my new reader (in development). The reader has been implemented over at whimsubs.xyz and will be replacing foolslide2 in a weeks over at jaiminisbox.com.

I do have a question though regarding dev: When getting latestUpdates from a source, tachiyomi wants a MangasPage, which is basically a container for a list of SManga. Problem with this though is that when fetching latest chapters from the api at `/api/chapters.json`, because they're chapters, just chapter data is returned:
```json
{
    "id": 64,
    "manifest": "/r/read/5b51fe81-470d-436d-b6d3-5551d8a6d98e/manifest.json",
    "comic": 12,
    "name": "A Summoner's Sage Skills",
    "chapter": 15,
    "subchapter": 0,
    "title": "Chapter 15: A Summoner's Sage Skills",
    "protection": null,
    "uniqid": "5b51fe81-470d-436d-b6d3-5551d8a6d98e",
    "volume": 0,
    "team": [1],
    "language": "en",
    "published_at": "2018-05-27T10:14:28-07:00",
    "modified_at": "2018-05-27T12:11:53.280321-07:00"
}
```
The manga is only referenced by an ID, so for each manga with a new chapter you would have to fetch that manga's details at `/api/comics/${id}.json`, which would result in quite a few API requests. The next-best option I see is to just prefetch all comic metadata as well from `/api/comics.json?page=${page}`, but I'm not sure. Suggestions?

**Comment by CarlosEsco** [comment]
So latest updates in tachiyomi doesn't care about the specific chapters that we're updated.  All it needs is the url to the manga, the title of the manga, and the  hq image (if you want to  reduce API calls)  So options that could work. 
1.  The latest API returns a list of manga which contains the latest chapter (tachiyomi would just ignore the chapter)
2.  API returns the chapter list but the title and manga id/url is also in the Json object. 
3.  Don't support latest. Tachiyomi extension can just have the Boolean false and throws not implemented for the latest update sections

**Comment by chocolatkey** [comment]
Hmm
1. On the server/DB side, the reasoning for the API is with `chapters.json` you ONLY involve the chapter table/model, with comics.json you ONLY involve the comic table/model. So sorting can happen, but only with regards to the contents of that table, meaning I can sort comics:
![image](https://user-images.githubusercontent.com/13407784/41197811-197148b8-6c1e-11e8-9192-f13c57fa1616.png)
and chapters:
![image](https://user-images.githubusercontent.com/13407784/41197814-25a0bc72-6c1e-11e8-93c3-a1bdfd660838.png)
but I can't easily order comics with regards to latest chapters without a big change in the backend.
2. Sounds like what I might have to go with, make `"comic": 12` become `"comic": {"id": 12, "title": "The comic", "thumbnail": "comic.jpg"}, but unfortunately, that will involve more DB calls, which I guess I'll have to live with.
3. No, must have latest to be the greatest

Thanks for the help, I might end up asking a few other questions as a noob

**Comment by CarlosEsco** [comment]
Regarding the chapter json API.  Wouldn't the website when using the reader API want to show the title and cover anyways?  If not it feels like it would provide a bad ui if all the reader did when it showed latest was showed chapters that user has no clue what they belong to

**Comment by chocolatkey** [comment]
The website does not use the API for the most part, except for search autocomplete and the reading interface. For latest a carousel is rendered on home page and a latest page much like that of Foolslide exists

**Comment by chocolatkey** [comment]
@CarlosEsco solved problem, have an option to expand the comic field to produce chapter output like this:
```json
{
    "id": 11,
    "manifest": "/r/read/f231ed70-62ec-46ed-b4d1-0e11f4d9446d/manifest.json",
    "comic": {
        "id": 1,
        "name": "Koi ni Hizu",
        "uniqid": "211691c2-e764-4534-ad58-fe9aef2121f1",
        "slug": "koi-ni-hizu",
        "alt": "恋ニ非ズ",
        "cover": "http://localhost:8000/static/media/211691c2-e764-4534-ad58-fe9aef2121f1/13932016480029269956-8b52ad82fac28f568f40cf7ea5c50c5a.png"
    },
    "name": "不義",
    "chapter": 4,
    "subchapter": 0,
    "title": "Chapter 4: 不義",
    "protection": null,
    "uniqid": "f231ed70-62ec-46ed-b4d1-0e11f4d9446d",
    "volume": 0,
    "team": [
        1
    ],
    "language": "ja",
    "published_at": "2018-05-21T00:35:00-07:00",
    "modified_at": "2018-06-05T23:55:02.420780-07:00"
},
```
and it works :)

**Comment by einstein95** [comment]
@chocolatkey Was there any progress on this? One previous source that used FoolSlide (ChampionScans) has moved to using ComiCake.

**Comment by chocolatkey** [comment]
@einstein95 Hi, I recently made some large changes to the comicake code, and I was waiting to do that before continuing work on the extension, since it also involved updating the webpub spec to the latest version (API fields). I'll get to it now, thanks for reminding me.

**Comment by chocolatkey** [comment]
Great, I accidentally wiped all my modifications when updating. Expect delay while I either miraculously find a backup or redo everything

**Comment by chocolatkey** [comment]
@CarlosEsco for the chapterListRequest, an API call looks like this: `https://whimsubs.xyz/api/chapters.json?comic=19&ordering=volume%2Cchapter%2Csubchapter&n=1000` . The SManga is passed for that function, but the only identifier in it is the url (e.g. `/comics/19.json`). Is there a better way to get back the comic's identifier besides filtering it back out of that url string?

**Comment by CarlosEsco** [comment]
@chocolatkey dont know exactly what you need but look at boredsociety extension as it is an extension with an api also might show you some other methods you can overwrite instead.

**Comment by chocolatkey** [comment]
@CarlosEsco Boredom has the chapters as an child of the comics in the JSON, which makes is simple, like the other API implementations I've seen. The function the farthest up the chain it seems I could override is the `fetchChapterList(manga: SManga): Observable<List<SChapter>>`, but that still uses an SManga, which still only has the `url` property to hold an identifier. Maybe I'll just stores the ID in the URL field, but that seems like an ugly solution.

**Comment by CarlosEsco** [comment]
Curious if you have manga url how are you finding the chapters?

**Comment by chocolatkey** [comment]
@CarlosEsco work in progress, but:
```kotlin
package eu.kanade.tachiyomi.source.online.english

import android.os.Build
import android.util.Log
import eu.kanade.tachiyomi.BuildConfig
import eu.kanade.tachiyomi.source.model.*
import eu.kanade.tachiyomi.source.online.HttpSource
import okhttp3.Headers
import okhttp3.Request
import okhttp3.Response
import eu.kanade.tachiyomi.network.GET
import kotlinx.coroutines.experimental.newCoroutineContext
import org.json.JSONArray
import org.json.JSONObject
import java.util.*
import rx.Observable
import java.net.URI
import java.net.URL
import java.text.SimpleDateFormat
import java.time.Instant
import java.time.OffsetDateTime
import java.time.format.DateTimeFormatter
import kotlin.collections.ArrayList

const val COMICAKE_API_PAGE_SIZE = 25
const val COMICAKE_API_ENDPOINT = "/api" // Highly unlikely to change
const val COMICAKE_READER_ENDPOINT = "/r" // Can change based on CC config

class WhimSubs : HttpSource() {
    override val name = "WhimSubs"

    open val useCDN = true // Fast sites can disable this to not use the Photon Image CDN
    override val versionId = 1
    override val baseUrl = "https://whimsubs.xyz"
    val readerUrl = baseUrl + COMICAKE_READER_ENDPOINT
    val apiUrl = baseUrl + COMICAKE_API_ENDPOINT
    override val lang = "en"
    override val supportsLatest = true

    private val userAgent = "Mozilla/5.0 (" +
            "Android ${Build.VERSION.RELEASE}; Mobile) " +
            "Tachiyomi/${BuildConfig.VERSION_NAME}"

    override fun headersBuilder() = Headers.Builder().apply {
        add("User-Agent", userAgent)
    }

    override fun popularMangaRequest(page: Int): Request {
        Log.w("request", "$apiUrl/comics.json?ordering=-created_at&page=$page")
        return GET("$apiUrl/comics.json?ordering=-created_at&page=$page") // Not actually popular, just latest added to system
    }

    override fun popularMangaParse(response: Response): MangasPage {
        val res = response.body()!!.string()
        return getMangasPageFromComicsResponse(res)
    }

    private fun getMangasPageFromComicsResponse(json: String) : MangasPage {
        var response = JSONObject(json)
        var results = response.getJSONArray("results")
        val mangaJson = ArrayList<JSONObject>(results.length())

        // TODO combine these two loops
        for (i in 0 until results.length()) {
            mangaJson.add(results.getJSONObject(i))
        }
        val mangas = ArrayList<SManga>(mangaJson.size)
        for (obj in mangaJson) {
            mangas.add(parseComicJson(obj))
        }
        return MangasPage(mangas, if (response.getString("next").isNullOrEmpty() || response.getString("next") == "null") false else true)
    }

    override fun mangaDetailsRequest(manga: SManga): Request {
        return GET("$apiUrl/comics/${manga.url}.json")
    }

    override fun mangaDetailsParse(response: Response): SManga {
        val comicJson = JSONObject(response.body()!!.string())
        return parseComicJson(comicJson, true)
    }

    private fun parseComicJson(obj: JSONObject, human: Boolean = false) =  SManga.create().apply {
        if(human) {
            url = "$readerUrl/series/${obj.getString("slug")}/"
        } else {
            url = obj.getInt("id").toString() // Yeah, I know... Feel free to improve on this
        }
        title = obj.getString("name")
        thumbnail_url = obj.getString("cover")
        author = parseListNames(obj.getJSONArray("author"))
        artist = parseListNames(obj.getJSONArray("artist"))
        description = obj.getString("description")
        genre = parseListNames(obj.getJSONArray("tags"))
        status = SManga.UNKNOWN
    }

    private fun parseListNames(arr: JSONArray) : String {
        var hold = ArrayList<String>(arr.length())
        for(i in 0 until arr.length())
            hold.add(arr.getJSONObject(i).getString("name"))
        return hold.sorted().joinToString(", ")
    }

    override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request {
        // TODO filters
        return GET("$apiUrl/comics.json?page=$page&search=$query")
    }

    override fun searchMangaParse(response: Response): MangasPage {
        TODO("TODO")
    }

    override fun latestUpdatesRequest(page: Int): Request {
        return GET("$apiUrl/chapters.json?page=$page&expand=comic")
    }

    override fun latestUpdatesParse(response: Response): MangasPage {
        return MangasPage(ArrayList<SManga>(0), false);
    }

    private fun parseChapterJson(obj: JSONObject) = SChapter.create().apply {
        name = obj.getString("title") // title will always have content, vs. name that's an optional field
        chapter_number = (obj.getInt("chapter") + (obj.getInt("subchapter") / 10.0)).toFloat()
        Log.w("chapnum", chapter_number.toString())
        val x = OffsetDateTime.parse(obj.getString("published_at"), DateTimeFormatter.ISO_DATE_TIME)
        date_upload = Date.from(Instant.from(x)).time
        // TODO scanlator field by adding expand team in CC
        url = obj.getString("manifest")
    }

    override fun chapterListRequest(manga: SManga): Request {
        return GET("$apiUrl/chapters.json?comic=${manga.url}&ordering=-volume%2C-chapter%2C-subchapter&n=1000", headers) // There's no pagination in Tachiyomi for chapters so we get 1k chapters
    }

    override fun chapterListParse(response: Response): List<SChapter> {
        val chapterJson = JSONObject(response.body()!!.string())
        var results = chapterJson.getJSONArray("results")
        val ret = ArrayList<SChapter>()
        for (i in 0 until results.length()) {
            ret.add(parseChapterJson(results.getJSONObject(i)))
        }
        return ret
    }

    override fun pageListParse(response: Response): List<Page> {
        val webPub = JSONObject(response.body()!!.string())
        val readingOrder = webPub.getJSONArray("readingOrder")
        val ret = ArrayList<Page>();
        for (i in 0 until readingOrder.length()) {
            var pageUrl = readingOrder.getJSONObject(i).getString("href")
            if(useCDN) {
                val url = URL(pageUrl)
                pageUrl = "https://i${i % 3}.wp.com/${url.host}/${url.path}?strip=all&quality=95"
            }
            ret.add(Page(i, "", pageUrl))
        }
        return ret
    }

    override fun imageUrlParse(response: Response) = throw UnsupportedOperationException("This method should not be called!")
}
```
Chapter ID as chapter URL is working fine for now

**Comment by chocolatkey** [comment]
@CarlosEsco Will be committing soon anyway for a preliminary version. Any suggestions for de-duplicating series in the latest list?

**Comment by CarlosEsco** [comment]
When you are creating the new list. Add the url to set of strings if it already exists don't add the new manga

**Comment by chocolatkey** [comment]
@CarlosEsco but since latest is paginated into mangapages, how should one mangapages be aware of the contents of the previous/next one when finding duplicates?

**Comment by CarlosEsco** [comment]
Just let it show duplicate?

**Comment by arkon** [comment]
Why are there even duplicates in the first place? Is it just on the off chance that something shifts to the next page while you're browsing?

**Comment by chocolatkey** [comment]
@arkon because due to the nature of comicake's API, you can't just "get and sort comics by one with the most recently released chapter". Instead, I'm doing "get and sort chapters by recency" and getting the comics from there. In fact I don't get why tachiyomi's "latest" feature doesn't want chapters, but manga. I'm going to go with the what @CarlosEsco said and just let there be duplicates across mangapages, since at least it will be less noticeable than now

**Comment by chocolatkey** [comment]
@mat-dr thanks for the suggestion for de-duplication.

I think I have a hunch for that error: You're running a version of Android with the Java 6 version of SimpleDateFormat (what android version *are* you running?), that doesn't have `X` as a format character yet. I'll have to figure out a workaround for that

**Comment by mat-dr** [comment]
Android 4.1. It works by replacing
```kotlin
date_upload = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssXXX").parse(obj.getString("published_at")).time
```
with
```kotlin
date_upload = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ").parse("(\\d\\d):(\\d\\d)$".toRegex().replace(obj.getString("published_at"), "$1$2")).time
```

**Comment by chocolatkey** [comment]
@mat-dr Thanks for that. As for the "open in browser issue", I'm pretty sure according to other issues here that it's a known issue with sources that aren't `ParsedHttpSource`s, because that uses the SManga's URL property, which is not the one intended for humans when using an API vs. parsing webpages

**Comment by chocolatkey** [comment]
I was going to apply mat-dr's fix, but he deleted his comments (with the code) for no apparent reason... Anyone remember what he did? I remember regex and not using modern timezone formatter

**Comment by arkon** [comment]
Not sure if this is still relevant since the extension already exists.
