### ISSUE TITLE
[Bug] <zh.manhuagui>: <cover not loaded nor able to customize, f12 detail provided>

### ISSUE THREAD

**Issue by 29988122** [inorichi/tachiyomi-extensions#3546]
### Device information
- Tachiyomi version: J2k latest version
- Android version: 9.0

### Source information
- Name: https://github.com/inorichi/tachiyomi-extensions/tree/master/src/zh/manhuagui
- Extension version: latest version

## Steps to reproduce
1. Search for any comics of this source
2. Add it to lib, no cover, can't be customized either.

### Expected behavior
Cover showing normally.

### Actual behavior
No cover.

### Other details
![圖片](https://user-images.githubusercontent.com/5474709/84774651-b58b6c00-b010-11ea-8159-590091c8caed.png)
Here's the located cover address.
Comic URL: https://tw.manhuagui.com/comic/23411/

No idea how it behaved, I know nothing about css.
I tried to check a few similar bug, but I have no idea how to fix that, sorry!
https://github.com/inorichi/tachiyomi-extensions/pull/3472/files
https://github.com/inorichi/tachiyomi-extensions/pull/3307/files

@SnakeDoc83 Thank you for taking your time maintaining these extensions!

**Comment by SnakeDoc83** [comment]
I think the website blocked me while I was testing changes (-.-)

Hopefully I'll get access again in a while.

**Comment by SnakeDoc83** [comment]
Closed via https://github.com/inorichi/tachiyomi-extensions/pull/3556

**Comment by Oldwangtouchtouchdoge** [comment]
新版的漫画柜插件（1.2.2版）应该能正确处理漫画的缩略图了，但还有一种可能是你的IP地址被漫画柜屏蔽了，你可以在任意漫画柜的漫画详情页面点击浏览器图标（下图），使用内置浏览器测试一下，如果页面一直是空白那可能性就很大了。你可以等几天再试一下看看有没有解封。
![图片](https://user-images.githubusercontent.com/18094567/85102068-69217580-b236-11ea-8fb4-bc913edd2af3.png)

**Comment by 29988122** [comment]
Confirmed working, thank you so much!
