### ISSUE TITLE
[Source Request] Alfie by Buttsmithy

### ISSUE THREAD

**Issue by emidelgado01** [inorichi/tachiyomi-extensions#3578]
### Source Website
- Name: Alfie (by buttsmithy)
- Link: https://buttsmithy.com/
- Language(s): English

**Comment by magicisreals1234** [comment]
bump, it's also on E-hentai /ex, you can use tachiyomiAZ for it

**Comment by AbdullahM0hamed** [comment]
Duplicate of #2257
