### ISSUE TITLE
[Indonesian] otakufile.com

### ISSUE THREAD

**Issue by kuuhaku23** [inorichi/tachiyomi-extensions#358]
Please can you add indonesia source from site https://otakufile.com/

Thank

**Comment by CarlosEsco** [comment]
Please edit the title to match other request [language] source

**Comment by as280093** [comment]
Here the icons
[otakufile.zip](https://github.com/inorichi/tachiyomi-extensions/files/3615270/ic_launcher.2.zip)

**Comment by arifr007** [comment]
i think this issue can be closed :D

https://github.com/inorichi/tachiyomi-extensions/pull/1615
