### ISSUE TITLE
[Bug] MangaDex: "Unknown" in status for cancelled titles

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi-extensions#3586]
### Device information
- Tachiyomi version: 0.9.2-2447
- Android version: 10

### Source information
- Name: MangaDex
- Extension version: 1.2.94

"Unknown" shown in status in manga info for cancelled titles

![Screenshot_20200621-215602_Tachiyomi](https://user-images.githubusercontent.com/23010526/85229946-87d86580-b40a-11ea-9813-247eb08468e5.jpg)

![image](https://user-images.githubusercontent.com/23010526/85229962-a0488000-b40a-11ea-8b0e-99407f567126.png)

**Comment by CarlosEsco** [comment]
Cancelled doesn't exist in tachiyomi so unless @arkon wants to add it as a status then this is not going to be changed

**Comment by arkon** [comment]
Would it be considered as completed?

**Comment by CarlosEsco** [comment]
I would say yes if we are not adding that status

**Comment by vengiare** [comment]
"Completed" would be misleading tho. It's good to see if a manga is Cancelled (Discontinued would be a better name imo) so that you don't end up wasting time reading a manga that you thought was completed.

**Comment by arkon** [comment]
Completed or unknown are your only choices given the existing API.

**Comment by vengiare** [comment]
Personally I would rather keep the Unknown status than have it show a misleading Completed status then. I think that's the safest option (you don't end up reading a manga you thought was "Completed") and it also encourages people to search for the actual status of the manga. But well, that's just my own opinion.

**Comment by CarlosEsco** [comment]
good i agree
