### ISSUE TITLE
[Bug] ReManga: error of titles that have prereleases of chapters

### ISSUE THREAD

**Issue by IvanKing12** [inorichi/tachiyomi-extensions#3592]
---
### Device information
- Tachiyomi version: 0.9.2
- Android version: 10

### Source information
- Name: ReManga
- Extension version: 1.2.5

## Steps to reproduce
1. In the search on the reader, enter: "A Harem in the Fantasy World Dungeon"(without "")
2. Go to the title and knocks out an error.

### Expected behavior
There should have been chapters that are available and that are not available, but with a lock Emoji.

### Actual behavior
Returns a 401 error when switching to the title, and then when switching to the list of chapters, it returns a code error.

Error text: java.lang.IllegalStateExeption Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 57 path $.content .

### Other details
I think this happens with those titles that have chapters that are not available for viewing to users who did not buy them(there is a function of beta chapters for money, prerelease)

**Comment by SnakeDoc83** [comment]
Were you logged in?

**Comment by IvanKing12** [comment]
> Were you logged in?

At the time of writing the report, no. The problem was this, but still I would like to display all the titles, 18+ is hidden by default.

**Comment by SnakeDoc83** [comment]
From what I've seen, the API doesn't return chapter information for manga that require login; so can't create a chapter list for those manga until the user has logged in.  I'll make that a bit clearer, but can't do more than that.
