### ISSUE TITLE
[Bug] Madara - AdonisFansub - No Chapters found again

### ISSUE THREAD

**Issue by Agayev033** [inorichi/tachiyomi-extensions#3605]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 10

### Source information
- Name: AdonisFansub
- Extension version: 1.2.113

![Screenshot_20200624-150436](https://user-images.githubusercontent.com/30019351/85544794-648d0080-b62c-11ea-9ae7-001f2a629f05.png)

**Comment by SnakeDoc83** [comment]
It's due, at least in part, to them turning on hcaptcha. I think the issue is with cookies, but I need to look in to it more.

**Comment by SnakeDoc83** [comment]
Closed by https://github.com/inorichi/tachiyomi-extensions/pull/3615

Apparently hcaptcha is strict about what user-agent it'll accept as valid.
