### ISSUE TITLE
[Bug] <komikTap>: <The domain has changed to https://komiktap.us>

### ISSUE THREAD

**Issue by nizarschecter** [inorichi/tachiyomi-extensions#3606]
### Device information
- Tachiyomi version: ?
- Android version: ?

### Source information
- Name: komikTap
- Extension version: ?

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened

### Actual behavior
This happens instead

### Other details

Language : bahasa indonesia

**Comment by SnakeDoc83** [comment]
Don't open a second issue for something just because it wasn't addressed right away.
