### ISSUE TITLE
[Feature Request] Hide certain chapters

### ISSUE THREAD

**Issue by Suni23** [inorichi/tachiyomi-extensions#3612]
Some websites, especially MangaDex in particular, have an issue where multiple translators will upload their version of the same chapter of a manga. A neat feature would be being able to select a chapter and hide it, so as you're reading the manga you don't end up seeing the same chapter again, and possibly a selection in the hamburger menu to see the hidden chapters to add them back or view them if you want.

**Comment by CarlosEsco** [comment]
Wrong repo and https://github.com/inorichi/tachiyomi/issues/2542
