### ISSUE TITLE
[Bug] <Naver Comic>: <No Results Found>

### ISSUE THREAD

**Issue by littlebabyboo** [inorichi/tachiyomi-extensions#3614]
---

### Device information
- Tachiyomi version: v0.9.2
- Android version: 9

### Source information
- Name: Naver Comic
- Extension version: 1.2.2

## Steps to reproduce
1. Click on browse on Naver Webtoon source
2. Search a webtoon in korean name.

### Expected behavior
The webtoon should have showed up when you search it.

### Actual behavior
It didn't showed up and says "No Results Found"

### Other details
I know the webtoon was there because you can see it on the list. (as seen on the picture)

![20200625_154212](https://user-images.githubusercontent.com/64119966/85679089-ab95f700-b6fb-11ea-9a0c-aaae3a9ecf67.jpg)

But everytime you search a webtoon, it just doesn't show up and says "No Results Found".

![20200625_154234](https://user-images.githubusercontent.com/64119966/85679155-bb154000-b6fb-11ea-8ac0-55761cf1852b.jpg)

**Comment by SnakeDoc83** [comment]
Seems to work for me. 

![Screenshot_1593142763](https://user-images.githubusercontent.com/51273546/85818259-3697e100-b73e-11ea-8f34-3c623aff83b1.png)

**Comment by littlebabyboo** [comment]
Ah i figured it out. I copied the korean name on mangaupdates and it didnt work but when i copied the korean name on manga dex, it worked. i wonder why?

**Comment by SnakeDoc83** [comment]
Some kind of quirk to their website I guess. Even though on mangaupdates the Korean name looks right in a browser, if you copy-paste it to notepad it doesn't come out right.
