### ISSUE TITLE
[Bug] nhentai ID search DOWN 

### ISSUE THREAD

**Issue by baraa272** [inorichi/tachiyomi-extensions#3622]
Issue : nhentai Id search DOWN
So it Seems nhentai turned off thier id search off which make a bit of problem here since tachiyomi uses id search to get destination nhentai titles when opened or called by nhentai link
And now it gives me blank page inside tachiyomi when it tries to parse nhentai link
So if it appropriate maybe change the id search for this extension to parsing the (name) first then do the process of nhentai link?
S7 edge sm-g935F Exynous 
Android 7.0

**Comment by arkon** [comment]
Works fine for me.

**Comment by rama982** [comment]
Works fine for me too.

**Comment by DiabloPiotr** [comment]
All good on my device

**Comment by baraa272** [comment]
Yeah it seems it's related to cloudflare problem

**Comment by SnakeDoc83** [comment]
ID search works on their site and links seem to work, don't think there's anything to change in the extension to help you out.  You could try clearing cookies or removing NHentai as a default app and then re-add it as a link handler. Nuclear option is to make a backup, clear data from Android settings, and then import your backup for a fresh start. No guarantees it'd help but sometimes a clean slate is the only way.
