### ISSUE TITLE
[Feature Request] nhentai: Filter title using regex

### ISSUE THREAD

**Issue by ngomile** [inorichi/tachiyomi-extensions#3627]
### What feature should be added to this source?
nhentai can return hentai search results with multiple languages, this feature would let the user specify using regular expressions that they just want the English scans since the title usually indicates the language.

**Comment by SnakeDoc83** [comment]
Can you give an example where this would be useful? There's already some filtering being done, curious where it might be failing.

**Comment by ngomile** [comment]
My bad, silly oversight.
