### ISSUE TITLE
[Bug] HentaiNexus: pages failing to load

### ISSUE THREAD

**Issue by DiabloPiotr** [inorichi/tachiyomi-extensions#3630]
### Device informatio
- Tachiyomi version: 0.9.2
- Android version: 8.1.0

### Source information
- Name: HentaiNexus
- Extension version: 1.22

## Steps to reproduce
1. Open any manga
2. Try to read
Or try to open web view of manga

### Expected behavior
Ability to load pages and normal web view

### Actual behavior
Pages failing to load. Web view different than actual site.

**Comment by SnakeDoc83** [comment]
Try clearing your cookies and reload.

**Comment by DiabloPiotr** [comment]
Daym thanks. Didn't know that it works like that. Still web view looks different

**Comment by SnakeDoc83** [comment]
It's a fairly rare issue.
