### ISSUE TITLE
[Bug] <xoxo comic>: <not all chapters downloading >

### ISSUE THREAD

**Issue by jedimasterlink** [inorichi/tachiyomi-extensions#3631]
---

### Device information
- Tachiyomi version: 0.9.2
- Android version: 9

### Source information
- Name: wp-comic 
- Extension version: 1.2.8

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
 expected to download chapters

### actual Behavior
Download some but not all chapters

### Other details
Extension might need to be updated so that it can download all chapters from source

**Comment by SnakeDoc83** [comment]
Post an example of a comic that's not working.

**Comment by jedimasterlink** [comment]
![Screenshot_20200630-232244_Tachiyomi](https://user-images.githubusercontent.com/67525884/86206036-ab955d00-bb28-11ea-98be-a1e0fe4aefad.jpg)

**Comment by jedimasterlink** [comment]
I I tried the retry link and it will not load it does this on a lot of the comics that I read on xoxo comic

**Comment by SnakeDoc83** [comment]
Check the chapter in webview, you'll see there aren't any images--meaning it's an issue with the website, not the extension.
