### ISSUE TITLE
[Bug] MangaPark : doctype of java.lang.String cannot be converted to JSONArray

### ISSUE THREAD

**Issue by Kush-Patel** [inorichi/tachiyomi-extensions#3634]
---

### Device information
- Tachiyomi version: 0.9.2 
- Android version: 9 

### Source information
- Name: MangaPark 
- Extension version: 1.2.15 

## Steps to reproduce
1. Try to read or download a chapter of source Version Rock

### Expected behavior
Should be able to read or download the chapter

### Actual behavior
Value <!doctype of java.lang.String cannot be converted to JSONArray

**Comment by SnakeDoc83** [comment]
Post an example where you received that error.

**Comment by Kush-Patel** [comment]
https://mangapark.net/manga/ultimiter

**Comment by fawadkhan121** [comment]
Yes and i have to go to web view every time i went to manga park or want to update the library
