### ISSUE TITLE
[Meta] AllPornComic: Add genre filters

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi-extensions#3636]
Currently, genre filters are missing from the extension but available on the website. I have attached screenshot below to show the list of  some of the available genre tags in the source 

![screenshot_20200628-133055_tac](https://user-images.githubusercontent.com/34897862/85954204-cc508d80-b943-11ea-8967-439f15abbc61.jpg)

**Comment by SnakeDoc83** [comment]
So, there's 472 tags; I feel like that'd be a bit much if I added them all.

**Comment by joseph619** [comment]
Just add these ones then (it's on website under more)

![Webp net-resizeimage](https://user-images.githubusercontent.com/34897862/85961668-ffae0f00-b979-11ea-843d-f31081fc5e8b.jpg)

Around 17/18 here
