### ISSUE TITLE
[Bug] MangaDex 'ES' Version will only pull chapters from ES-SPAIN

### ISSUE THREAD

**Issue by Darkmaster006** [inorichi/tachiyomi-extensions#3637]
So, basically, I'm not sure if this is a 'bug' per se, but maybe it has been overlooked. While trying to look for chapters in 'Spanish', I realised that only the ES-SPAIN versions are available. The problem is that MangaDex has two Spanish languages: LATAM and SPAIN. So it seems that Tachiyomi is only recognising ES-SPAIN as the ES language, when ES-LATAM should, too, be recognised and their chapters be available to read. Otherwise it seems like no chapters are available in Spanish even when there actually are chapters available. I hope this can be fixed.

---

### Device information
- Tachiyomi version: 0.9.2
- Android version: 8.0.0

### Source information
- Name: MangaDex
- Extension version: 1.2.94

## Steps to reproduce
1. Use MangaDex ES Extension
2. Check chapters of manga with ES-LATAM version.

### Expected behavior
Should have shown me chapters since there exists a ES version.

### Actual behavior
No chapters are shown because ES-LATAM version seem not to be recognised.

**Comment by MerradOklom** [comment]
The extension does support ES-LATAM, if you can't see it then you need to enable it:

![Picture_20200628_160443](https://user-images.githubusercontent.com/43864503/85956079-7d155780-b959-11ea-8e7f-8b06252d44af.png)

**Comment by Darkmaster006** [comment]
Thanks, I realised it hours after I made the post haha. Closed.
