### ISSUE TITLE
[New Website Tracking] <Anime-Planet>

### ISSUE THREAD

**Issue by shipoxx** [inorichi/tachiyomi-extensions#3641]
### cand you guys adding a new website to track Manga.. it's good and have big library!

• Website:
https://www.anime-planet.com

**Comment by shipoxx** [comment]
Why i said that, bcs have manhwa and novel, manga, anime... Its like mal but better in my op.

**Comment by CarlosEsco** [comment]
Wrong repo and its already been requested before
