### ISSUE TITLE
[Bug] <Hentaivn>: the extension does not redirect after passing cloudflare

### ISSUE THREAD

**Issue by Sehai1** [inorichi/tachiyomi-extensions#3647]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 9

### Source information
- Name: HentaiVN
- Extension version: 1.2.5

both main page and latest page don't load after passing cloudflare , it may work if you are using filter to search , I have tried to clear cookies but it;s still not working. Webview still ok
![Screenshot_2020-06-30-13-57-20-134_eu kanade tachiyomi](https://user-images.githubusercontent.com/64726925/86093845-cf7d8200-bad9-11ea-8e7b-f78e89490f81.jpg)
![Screenshot_2020-06-30-13-57-25-400_eu kanade tachiyomi](https://user-images.githubusercontent.com/64726925/86093848-d1474580-bad9-11ea-9bea-487b4ff4edc2.jpg)

**Comment by SnakeDoc83** [comment]
Don't need 3 open issues about the same thing. https://github.com/inorichi/tachiyomi-extensions/issues/3623
