### ISSUE TITLE
Request for updating mangasee extension

### ISSUE THREAD

**Issue by FDmZ** [inorichi/tachiyomi-extensions#3654]
---

### Device information
* Tachiyomi version: 0.9.2
* Android version: 9.0
* Device: Samsung Galaxy Note 8

### Source information
* Source name: mangasee
* Source extension version: 1.2.7

## Issue/Request
So mangasee has updated their site, causing a change from mangaseeonline.us to mangasee123.com
Could anyone please update the extension so that it can access the new mangasee site? Thanks

## Other details
Additional details and attachments.

**Comment by arsora** [comment]
Hope there will be a fix for mangasee,  love mangasee
