### ISSUE TITLE
[Bug] <MyReadingManga>: <cant read any manga - when you click on any chapter it just says "Page List Empty">

### ISSUE THREAD

**Issue by FeuilleDePapier** [inorichi/tachiyomi-extensions#3668]
### Device information
- Tachiyomi version: 0.8.5
- Android version: 8.0.0

### Source information
- Name: MyReadingManga
- Extension version: 1.2.34

## Steps to reproduce
1. Click on any manga
2. Click on chapter

### Expected behavior
This should have happened - chapter opens

### Actual behavior
This happens instead - error message "Page List is Empty" and chapter closes

**Comment by SnakeDoc83** [comment]
Closed by https://github.com/inorichi/tachiyomi-extensions/pull/3667
