### ISSUE TITLE
[Bug] <MangaRaw>: <Does not work>

### ISSUE THREAD

**Issue by DanielSN19** [inorichi/tachiyomi-extensions#3671]
I### Device information
- Tachiyomi version: 0.9.2
- Android version: 6.0.0

### Source information
- Name: MangaRaw
- Extension version: 1.2.1

### Other details
does not open, error "handshake failed".
![IMG_20200702_031325_976](https://user-images.githubusercontent.com/55334921/86323562-9570c500-bc2c-11ea-9b26-8cc0fc1244fc.jpg)

**Comment by SnakeDoc83** [comment]
Should be fixed if you use the preview version of Tachiyomi. https://github.com/inorichi/tachiyomi-extensions/issues/3233
