### ISSUE TITLE
MangaRaw (Manga1001) Handshake Failed

### ISSUE THREAD

**Issue by OhTalkWho** [inorichi/tachiyomi-extensions#3674]
MangaRaw seems to not be working. Whenever I load a chapter it get a Handshake Failed error. It was working fine up until recently. I checked the to make the sure that the source site was still up and working, and it is. 

### Device information
- Tachiyomi version: 0.9.2
- Android version: 9.0.11

### Source information
- Name: MangaRaw
- Extension version: 1.2.1

## Steps to reproduce
1. Go to desired manga chapter page
2. Try to load any chapter. 

### Expected behavior
Manga Should open 

### Actual behavior
Receive message "Handshake Failed"

**Comment by SnakeDoc83** [comment]
See known issues in #3475.
