### ISSUE TITLE
[Source Request Arabic] <Manga Arab Team>

### ISSUE THREAD

**Issue by mohalimoh14** [inorichi/tachiyomi-extensions#3679]
- Name: Manga Arab Team
- Link: https://mangaarabteam.com/
- Language(s): Arabic

**Comment by SnakeDoc83** [comment]
Already in Madara.

**Comment by mohalimoh14** [comment]
Where is it, I did not find it

**Comment by SnakeDoc83** [comment]
Install the Madara extension and make sure you have Arabic enabled for sources.

**Comment by mohalimoh14** [comment]
![٢٠٢٠٠٧٠٣_١٠٤٠٤٧](https://user-images.githubusercontent.com/67778555/86444661-c1b63f80-bd19-11ea-9f7f-687a945426b0.jpg)

Seems there is a problem with the beta version that I didn't find !!

**Comment by SnakeDoc83** [comment]
On the extensions screen tap the magnifying glass and search for "Madara" without quotes. Install that extension.

**Comment by mohalimoh14** [comment]
From my heart, thank you thank you❣❣❣❣
