### ISSUE TITLE
Mangago Obfuscation... again

### ISSUE THREAD

**Issue by LakotaGray** [inorichi/tachiyomi-extensions#368]
Just like the last time Mangago source had problems due to a new obfuscation method closed issue #355, they’ve done it again. The error message is similar which makes it look like the coding was altered but overall method looks the same. Either way it would need to be changed to adapt to new set.

**Comment by LakotaGray** [comment]
Looks like they’ve since adjusted the obfuscation method to not properly fetch the page count for chapters. The unexpected url issue remains the same but chapter count now displays 1/1 only.

**Comment by joseph619** [comment]
Same issue here. Screenshot attached below
![screenshot_20180622-130948_tachiyomieh](https://user-images.githubusercontent.com/34897862/41789592-d85f8a2e-761d-11e8-8fd8-4ed3becb4fea.jpg)

**Comment by Mystique0414** [comment]
I can't download manga using mangago source too 😭

**Comment by Th3-822** [comment]
https://codepen.io/Th3-822/pen/BVVVGW/

**Comment by einstein95** [comment]
^ JS code to decrypt the manga URLs

**Comment by rj452** [comment]
does this mean mangago is good now?

**Comment by joseph619** [comment]
@rj452, no it's not fixed yet

**Comment by Mystique0414** [comment]
There are some other apps too with the same issue about the mangago source, developer said that the mangago change their URL so I guess it will be decoding 😅 but I hope it will be fix soon 😔 I really like this app 💓

**Comment by quinnjet** [comment]
@arkon or anyone that's knowledgeable, I'm a newbie to this but I'm curious, how does one actually implement the JS code posted above? I searched Google for hours, but I couldn't find a definitive answer.

**Comment by arkon** [comment]
@quinnjet Do you mean how to use it within the app, or how that JS is written?

**Comment by arkon** [comment]
@quinnjet You basically just need a JavaScript engine to execute the code. This app in particular uses [Duktape](https://github.com/square/duktape-android), which you can see its usage [here](https://github.com/inorichi/tachiyomi-extensions/blob/master/src/en/mangago/src/eu/kanade/tachiyomi/extension/en/mangago/Mangago.kt#L163-L169) as an example.

**Comment by quinnjet** [comment]
@arkon, It took a little bit, but I think I'm slowly getting the hang of it, thank you for the help.

**Comment by darkness66** [comment]
@arkon sorry if this started to bother you but Please tell me you're going to fix mangago issue Soon ₩^₩

**Comment by Th3-822** [comment]
3 new "deskeys": https://hastebin.com/ecavofikur.js
that should fix the scrambled images

**Comment by CarlosEsco** [comment]
#374

**Comment by yasnil** [comment]
Is mangago already working?

**Comment by einstein95** [comment]
Yes

**Comment by CarlosEsco** [comment]
Did you actually update the extension?

**Comment by AmuChii** [comment]
It's working now after the update! Thank you so much for all the hard work! Time to catch up to those missed chapters. 😄

**Comment by fatimagrace015** [comment]
The updates in mangago are jumbled. Yep, I did just update the mangago
extension

**Comment by arkon** [comment]
#377
