### ISSUE TITLE
[Bug] Webtoon: Page list empty error for some webtoons

### ISSUE THREAD

**Issue by psychopomp9** [inorichi/tachiyomi-extensions#3680]
### Device information
- Tachiyomi version: 0.9.2 stable
- Android version: 9

### Source information
- Name: Webtoon
- Extension version: 1.2.17

### Expected behavior
Chapters should have been loaded rather than showing an error.

### Actual behavior
When trying to read some mangas from webtoon source it shows an error 'page list is empty'. i.e. 'shriek' or 'chiller'

**Comment by SnakeDoc83** [comment]
Briefly looked in to them and found that they're "motiontoons" which are partially animated and/or have sound playing as you read them. Unlike the regular webtoons, the URLs for the motiontoons images are determined by JavaScript.

**Comment by psychopomp9** [comment]
okay. I should start reading it on the site! Thanks.
