### ISSUE TITLE
Newtoki not working

### ISSUE THREAD

**Issue by JudiciousVick** [inorichi/tachiyomi-extensions#3681]
### Device information
- Tachiyomi version: 0.9.2-2476 (standard, ec6dba1, 45)
- Android version: 9

### Source information
- Name: Newtoki
- Extension version: 1.2.11
![Screenshot_20200703-135501__01](https://user-images.githubusercontent.com/59502042/86449695-2a131a00-bd36-11ea-87aa-bbd9d5d6c18b.jpg)

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened

### Actual behavior
This happens instead

**Comment by SnakeDoc83** [comment]
Go the the extensions screen and tap the New Toki extension to pull up extension settings. Use the override baseurl option and change the default to https://newtoki66.net or whatever the current number is. Restart Tachi and go back to browse.
