### ISSUE TITLE
[Bug] Mangahasu: http 400 when attempting to read or webview

### ISSUE THREAD

**Issue by SeriouslyErnest** [inorichi/tachiyomi-extensions#3684]
Device information
Tachiyomi version: 0.92
Android version: 9
Source information
Name: Mangahasu
Extension version: 1.2.8
Steps to reproduce
Attempt to read -> http error 400
Attempt to download -> error
Webview -> 400 bad request "request header or cookie too large" nginx/1.16.1
Open in browser: loads -> cloudflare challenge -> able to view comic

Expected behavior
Attempt to read / download / webview should succeed

Actual behavior
400 bad request "request header or cookie too large" nginx/1.16.1

Other details

**Comment by arkon** [comment]
You need to clear your cookies (More > Settings > Advanced > Clear cookies).
