### ISSUE TITLE
[Source Request] <MangaDisk>

### ISSUE THREAD

**Issue by betengQ** [inorichi/tachiyomi-extensions#3685]
### Source Website
- Name: MangaDisk
- Link: https://mangadisk.web.id/
- Language(s): indonesian

**Comment by as280093** [comment]
**Theme Used:**
**Name**: MangaReader
**Link:** https://themesia.com/mangareader-wordpress-theme

If other sources use this making a Factory Extension

**Comment by SnakeDoc83** [comment]
There's a request for Komikmama that uses this theme. https://github.com/inorichi/tachiyomi-extensions/issues/4007

Bacakomik.co might be the same theme but I can't access to check for certain. I may have seen some other sources with this theme but I can't recall any other names.

**Comment by CarlosEsco** [comment]
Support won't be added for this.  Proof was provided by owner #4429
