### ISSUE TITLE
[Bug] <Super Mangás (PT-BR)>: <Chapters do not appear>

### ISSUE THREAD

**Issue by LeonardoTds** [inorichi/tachiyomi-extensions#3686]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 7.0

### Source information
- Name: "Super Mangás (PT-BR)" and "Super Hentais (PT-BR)"
- Extension version: 1.2.1

## Steps to reproduce
1. Install the extension "Super Mangás (PT-BR)"
2. Open the extension "Super Mangás (PT-BR)" or "Super Hentais (PT-BR)", search, and open any manga.

### Expected behavior
Open any manga and the synopsis and chapters load.

### Actual behavior
Open any manga and the synopsis and chapters do not appear.

### Other details
This happens only in the extensions "Super Mangás (PT-BR)" and "Super Hentais (PT-BR)", the other extensions in PT-BR are working.
This happens with ALL manga.
The "WebView" and the website for both extensions are working normally.
The names and pictures of all the manga are appearing normally.
The message "Not a JSON Object: null" was appearing until a while ago, currently it does not appear to me, but the text box appears.

![c3c628cd-ba37-452e-bc98-8422ccaec917](https://user-images.githubusercontent.com/67779461/86525203-88d1b400-be5a-11ea-9210-d236dd6c1174.png)

**Comment by alessandrojean** [comment]
I will take a look and try to fix it.
