### ISSUE TITLE
[Bug] <INKR>: <URL of this source is changed>

### ISSUE THREAD

**Issue by Mehshan31** [inorichi/tachiyomi-extensions#3688]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 8.1.0

### Source information
- Name: INKR
- Extension version: 1.2.2

## Steps to reproduce
1. Install the extension INKR. 
2. Open the extention, search, open a manga, open a chapter. 

### Expected behavior
Open any manga and the synopsis and chapters load.

### Actual behavior
Every comics is invalid. One can browse these titles but can't read

### Other details
Web view for this extension doesn't work. 
The url of this extension is changed.

**Comment by SnakeDoc83** [comment]
As far as I can tell, INKR is now app-only (meaning their app). Unless that changes, this isn't fixable.

**Comment by AbdullahM0hamed** [comment]
It was always app-only😭😭😭. I'm having trouble figuring out the new stuff, so that's gonna take a while, rip.

**Comment by SnakeDoc83** [comment]
My mistake, thought Inkr was previously viewable by browser too. Well, it's all you @AbdullahM0hamed, keep the meme alive.

**Comment by AbdullahM0hamed** [comment]
Well, I, for whatever reason cannot seem to get the values I need from json (despite everything looking correct), so I'm not gonna be able to do it rip
