### ISSUE TITLE
Mangago Source Not Working!

### ISSUE THREAD

**Issue by rj452** [inorichi/tachiyomi-extensions#369]
App version: Tachiyomi v.0.7.4

Issue/Request: I know this issue has been addressed and resolved before but it reoccurred just now, or maybe a few hours ago. Whenever I try to download a manga, some error code shows up instead of the progress (e.g. htijeet/:7/mwnba---). Other extensions have no such issues.

Steps to reproduce (if applicable)

Other details:

By:Rikuo-g

**Comment by LakotaGray** [comment]
#368
