### ISSUE TITLE
[Bug] Wutopia (EN): Only first page loads

### ISSUE THREAD

**Issue by UWNG99** [inorichi/tachiyomi-extensions#3690]
### Device information
- Tachiyomi version: J2K 1.0.7
- Android version: Android 9

### Source information
- Name: Wutopia
- Extension version: English 1.2.1

## Steps to reproduce
1. First Step: Enter any recent chapter (Older chapters load normally)
2. Second Step: Open it

### Expected behavior
Chapter fully loaded

### Actual behavior
Chapter only loads first page

### Other details
Chapters that fail to load completly are chapters behind a paywall in the site, however, it should be loading even if locked according to #2086 in which SnakeDoc83 informs that "Their API allows access to chapters that are locked on their website....", this leads me to believe the API may have been updated. This has happened before which leads me to believe is Fixable.

**Comment by SnakeDoc83** [comment]
Seems they caught on and tightened up their API.

**Comment by UWNG99** [comment]
What a shame, whelp it was good while it lasted, thanks
