### ISSUE TITLE
[Bug] MANGA Plus by SHUEISHA: double pages are split even if setting is disabled

### ISSUE THREAD

**Issue by mattiadr** [inorichi/tachiyomi-extensions#3694]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 9

### Source information
- Name: MANGA Plus by SHUEISHA
- Extension version: 1.2.9

## Steps to reproduce
1. Disable "Split double pages" setting
2. Open a manga with double pages (I found this while reading "Chainsaw Man")

### Expected behavior
Double pages should not be split

### Actual behavior
Double pages are split in two different pages

**Comment by alessandrojean** [comment]
As the setting description explains, not all titles from their service support this option, in fact, only a little selection supports it. One of the titles, at least in the first chapter, is "Moon Land".

**Comment by mattiadr** [comment]
My bad, I read that incorrectly, I thought that splitting was not always supported, not disabling the setting.
Closing this, since it is not a bug.

**Comment by alessandrojean** [comment]
I will try to clarify better the setting description in a next extension update.
