### ISSUE TITLE
[Bug] <Mangaku (ID)>: <Url changed>

### ISSUE THREAD

**Issue by Schiffer10** [inorichi/tachiyomi-extensions#3697]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 9

### Source information
- Name: Mangaku (ID)
- Extension version: 1.2.1

## Steps to reproduce
1. Change the url
2. Second Step

### Expected behavior
Showung manga

### Actual behavior
Didnt show manga

**Comment by SnakeDoc83** [comment]
Larger issue: https://github.com/inorichi/tachiyomi-extensions/issues/3697

**Comment by Schiffer10** [comment]
> Larger issue: #3697

What do you mean?

**Comment by SnakeDoc83** [comment]
My fault, meant to link https://github.com/inorichi/tachiyomi-extensions/issues/2530

**Comment by Schiffer10** [comment]
> My fault, meant to link #2530

Thanks bro
