### ISSUE TITLE
How Do We actually use this?

### ISSUE THREAD

**Issue by jasterph** [inorichi/tachiyomi-extensions#37]
Do we compile this by itself or do we combine it with the main program then compile?

**Comment by j2ghz** [comment]
It is meant to be compiled, then install the apks you want. The sources are working, there's just no UI for downloading in the main app now.
They are also available using https://github.com/inorichi/tachiyomi/wiki/FDroid-for-dev-versions

**Comment by jasterph** [comment]
I downloaded the complete test from that link but how do I enable the other sources? all i am seeing are the normal one

**Comment by j2ghz** [comment]
Don't use the complete test, I forgot to remove it. If you have main app install just grab any source e.g. `Tachiyomi: en.readcomiconline` and after installation it should show up in catalogue

**Comment by jasterph** [comment]
do i need to use one of the Dev versions? I get CTD when I try to open readcomics

**Comment by j2ghz** [comment]
It should work with 0.5.2, right now 0.5.2 is the same as dev version.
ReadComics.tv? The site is down, but you should get a warning `No address associated with hostname`. If it's really crashing you should report it.

**Comment by jasterph** [comment]
sorry meant readcomicsonline it will open in the dev version on f droid, but the app crashes out on the main version

**Comment by j2ghz** [comment]
the main meaning v0.5.2?

**Comment by jasterph** [comment]
yep

**Comment by jasterph** [comment]
I do have both of them installed could that be causing a conflict?

**Comment by j2ghz** [comment]
I have no idea, you could create an issue in the main repo.

**Comment by inorichi** [comment]
https://github.com/inorichi/tachiyomi/commit/f88794c75219c35629b6f10b183936dd2c4cddd5

Proguard was stripping some fields used by the extensions.
