### ISSUE TITLE
[Bug] MangaDex: MD@Home issues, old chapters not loading. etc.

### ISSUE THREAD

**Issue by columna1** [inorichi/tachiyomi-extensions#3702]
### Source information
- Name: MangaDex
- Extension version: 1.2.94

## Steps to reproduce
1. First Step
Open an old chapter > ~1-2 months with a decent amount of pages
2. Second Step
Wait for about 5 mins then start turning pages

### Expected behavior
Load all pages properly
### Actual behavior
Fails to load pages, reloads don't help. Relaunching app doesn't help.
### Other details
Due to the new rollout of MD@H certain aspects of fetching manga have changed. This is leading to some unexpected behavior and disruption to readers in tachiyomi.
There are few bugs here in play, First and most important is that Manga links for manga from MD@H now have tokens that expire embedded into URLs given to readers by the main server. With the way tachiyomi/MangaDex extension work they grab those links at the start of reading a chapter and save them for grabbing later. This poses a problem. If the reader tries to grab a page after it expires the node will then return a 403 and won't serve an image. 

This can be solved in a few ways:
* First, and I believe the best solution would be to mirror the MangDex website reader and pre-grab all the pages in a chapter at once, this gets around the 5 minute Expiration of tokens in most cases.
* Second I believe that the api now returns an alternate link in the json response to grab from should the first one fail.
* Third, and probably not a very good idea is to remove the token from the link altogether and instead of requesting from {token}/data(-saver)/{chapter}/{image}, just grab from /data(-saver)/{chapter}/{image}. This is not recommended because although it works for now, policies are likely to change and tokens may be enforced as a requirement in the future.

Another issue we have run into is the ```Referer``` header. As a security measure we would like to check the ```Referer``` header to make sure the request is originating from one of our domains, ```https://mangadex.org``` or ```https://mangadex.network```. Currently tachiyomi doesn't set this header and as a consequence tachiyomi readers were almost totally denied access. We request that you set this header to ```https://mangadex.org``` to avoid possible future interruption.

As a request from us at MD@H we also kindly ask that after grabbing from an MD@H endpoint that a POST request is submitted to the endpoint ```https://api.mangadex.network/report``` with the json payload
```
{
  "url":     string  //URL for the image
  "success": boolean //If the request for the image was a success or not
  "bytes":   number  //size of image in bytes
}
```
This is used for stats and quality reporting of each node and helps us weed out un-friendly nodes in our network and provide a better end-user experience for all.

**Comment by AviKav** [comment]
It should be noted that while the official implementation and spec now accepts blank or non-empty `Referer`s, it may be a good idea to set it anyway

**Comment by ZaneHannanAU** [comment]
Indeed. That, or use a custom tachiyomi://{debug,release,j2k_release,j2k_debug}/mangadex/chapter/{id} Referer.

In fact, why not have a list of prefixes for referer headers, for better overall understanding of the user base.

**Comment by AviKav** [comment]
Those will be rejected

**Comment by columna1** [comment]
referer checks are hard coded at the moment and nodes aren't easy to unilaterally update. If we want information on who is connected we can currently collect that from other sources such as user-agent

**Comment by CarlosEsco** [comment]
user agent is already set to Tachiyomi.  Though i should change that for Neko since it can distinguish

**Comment by ZaneHannanAU** [comment]
Which is why I recommend a prefix list.

**Comment by CarlosEsco** [comment]
The prefix list you are mentioning isn't really something feasible unless every app goes in and hardcodes a mangadex specific change, which none of them do currently as this extension is meant to work across all forks

**Comment by arkon** [comment]
It doesn't really matter what the referer is so long as MangaDex can get what they need from the overall headers, all of which can be easily spoofed anyway.

**Comment by ZaneHannanAU** [comment]
Yeah.

**Comment by CarlosEsco** [comment]
I have Neko posting results, am working on the dex extension.  As for the other stuff we are are still discussing

**Comment by carbotaniuman** [comment]
Hello, MD@Home Dev here. Please don't call the `/report` endpoint, it's still unstable. And you can omit the `Referer` header to not run into any issues, if it doesn't exist you will not get blocked (it exists primarily to defend against agg sites, where browser inserts `Referer` automatically).

Only issue right now is tokens, we can increase the timeout to a larger number, or do something else?

**Comment by CarlosEsco** [comment]
A 30 minute token would be good. The urls are requested when a user clicks into a manga. So as long as they read within that time frame. They shouldn't get anymore errors.

**Comment by ZaneHannanAU** [comment]
Another potential could be token per domain, but is just a hmac key to link with user-agent

**Comment by CarlosEsco** [comment]
closing for now since its working with tokens.  If reports are wanted in the future please open a new ticket
