### ISSUE TITLE
[Source Request] Add TruyenChon.com source

### ISSUE THREAD

**Issue by haruki-takeshi** [inorichi/tachiyomi-extensions#3703]
### Source Website
- Name: TruyenChon
- Link: https://truyenchon.com
- Language(s): Vietnamese

### Other Details
It is using as alternative for nettruyen.com with fastest update daily 👍

Thanks,
Haruki.

**Comment by SnakeDoc83** [comment]
Closed by https://github.com/inorichi/tachiyomi-extensions/pull/3704
