### ISSUE TITLE
[Bug] E-Hentai: not showing all results available.

### ISSUE THREAD

**Issue by Panda7272** [inorichi/tachiyomi-extensions#3705]
After the newest E-Hentai update, less has shown up in searches and some titles/galleries are missing all together. However, when I search on the website, using mobile, pc, or in app webview, I am able to find what I'm looking for without issue.
---

### Device information
- Tachiyomi version: 0.9.2
- Android version: 10

### Source information
- Name: E-Hentai
- Extension version: 1.2.12

## Steps to reproduce
1. Tried multiple tags and filters configs to locate specific titles
2. Opened website on pc and copied all tags and title

### Expected behavior
When I find a title/gallery on my pc, I would like to be able to find and add it to my library.

### Actual behavior
When searching for titles or just browsing the selection is limited or not even there.

**Comment by SnakeDoc83** [comment]
Post an example (title or link but not screenshots) of what you can't find.

**Comment by Panda7272** [comment]
> Post an example (title or link but not screenshots) of what you can't find.

Any of the "bowsette collection" in the image set category. There are at least 15 galleries from the uploader j1os9e that can easily be found on the website but not the app.

https://e-hentai.org/?f_cats=991&f_search=Bowsette+collection

**Comment by SnakeDoc83** [comment]
It's probably because none of those galleries are tagged with a language tag. On the sources screen if you enable the "Other" or "None" language you can find a version of E-Hentai that doesn't filter languages. I might do something to return the English (and other language versions) to something like the old functionality, but you could use that until then.

**Comment by Panda7272** [comment]
Thank you very much, I didnt realize that it was now broken up into the various languages. Now that I know, there is no rush to change it if you are planning to.
