### ISSUE TITLE
[Bug] <Mangahasu is no longer working>: <The site works if we go to it from chrome but is showing http error 400 in tachiyomi and webview isn't working either. Pls fix>

### ISSUE THREAD

**Issue by kakkarot2** [inorichi/tachiyomi-extensions#3706]
### Device information
- Tachiyomi version: App version: 0.9.2
- Android version: 9

### Source information
- Name: Mangahasu
- Extension version: 1.2.8

## Steps to reproduce
1. First Step: Opened the browse menu of extension and tried read mangas already in library
2. Second Step: Tried to open webview

### Expected behavior
Manga should have oped and the site page should have shown in webview

### Actual behavior
http error 400 come when trying to read and browse manga and "400 bad request Request header or cookie too large" comes when webview is opened 

### Other details
The site is working normally in chrome but isn't working in tachiyomi since yesterday

**Comment by joseph619** [comment]
Clear your cookies and try again

**Comment by kakkarot2** [comment]
> Clear your cookies and try again

It worked tysm
