### ISSUE TITLE
[Bug] Nhentai: Missing Titles

### ISSUE THREAD

**Issue by sethazazel** [inorichi/tachiyomi-extensions#3709]
### Device information
- Tachiyomi version: r2493
- Android version: 9.1

### Source information
- Name: Nhentai
- Extension version: 1.2.26

## Steps to reproduce
1. Add manga to favorite
2. open library

### Expected behavior
the name of the manga (doujinshi) appears bottom of the cover

### Actual behavior
only cover no name

### Other details
In the library some of mangas names are missing.
In details pane it says unknown for name.
for example: 130781, 173925

**Comment by SnakeDoc83** [comment]
Can't duplicate your issue.

Remove the affected manga, go in to settings and tap "clear database", re-add the manga to your library.

**Comment by sethazazel** [comment]
Nhentai setting > Display manga titles as > "Short Title"

I reinstalled tachhiyomi. And i remembered there was a setting for titles.

Can you try with this settings please?

**Comment by SnakeDoc83** [comment]
Hmm, okay, I can duplicate it now.

**Comment by SnakeDoc83** [comment]
v.1.2.27 should fix the issue, but won't directly fix any manga you've already favorited. After you've installed it you'll need to do what I mentioned in the earlier post if you want to fix those manga.
