### ISSUE TITLE
[Bug] <TuMangaOnline>: <I can't read any manga from that extension>

### ISSUE THREAD

**Issue by koyomin11** [inorichi/tachiyomi-extensions#3713]
### Device information
- Tachiyomi version: Stable v. 0.9.2
- Android version: 8.0

### Source information
- Name: TuMangaOnline
- Extension version: 1.2.26
![Screenshot_20200707-031412](https://user-images.githubusercontent.com/67764678/86746480-b5bfcb80-c000-11ea-8bc8-be1f8dbaf082.png)

### Other details
So basically I was reading a manga and when I change from chapter the message from the screenshot apareció

**Comment by SnakeDoc83** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/2714

Long story short, TMO & LectorManga have issues and are a pain to maintian.
