### ISSUE TITLE
[Bug] LectorManga: String must be empy

### ISSUE THREAD

**Issue by rangeljc90** [inorichi/tachiyomi-extensions#3715]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 9

### Source information
- Name: LectorManga
- Extension version: 1.2.11

## Steps to reproduce
1. Open library and find a manga

2. Open a chapter, this not open and get pop up message "String must be empy"

### Expected behavior
This should have happened

### Actual behavior
This happens instead

**Comment by koyomin11** [comment]
I got the same problem, in TuMangaOnline

**Comment by pepe1987** [comment]
Same with TuMangaOnline 1.2.26.
The pop up shows **"String must not be empy"**

I want to add the sort chapters in TuMangaOnline (newest to oldest or oldest to newest) also doesn't work.

Tachiyomi version: 0.9.2
Android version: 5.0.2

**Comment by Roagr** [comment]
Procedo con lo mismo en tuMangaOnline, lleva así desde la mañana y la verdad me gustaría saber si es un problema persistente, para migrar los mangas que me interesan

**Comment by MerradOklom** [comment]
![IMG_202007189_043657](https://user-images.githubusercontent.com/43864503/86833736-4f729180-c070-11ea-9775-a3f7a0b9ae2f.png)

**Comment by edgarMejia** [comment]
TMO cada cierto tiempo realiza cambios para prevenir que aplicaciones como Tachiyomi tomen "su contenido" básicamente mueven cosas y a veces regresan a como estaban antes, así que por experiencia sabemos que con ellos es mejor esperar a que hagan sus movidas para luego nosotros poder ajustar la extensión.

Les recomiendo usar MangaMX y tener TMO como segunda opción.

**Comment by edgarMejia** [comment]
> Lástima que no hay otra buena alternativa o no lo conozco que tenga muchos mangas como TMO.

MangaMX ...

**Comment by koyomin11** [comment]
Mangamx está igual en tachiyomi? Por qué tengo capítulos descargados en tumangaonline y sería un pedo volver a descargarlos con otra extensión

**Comment by edgarMejia** [comment]
Para qué los vas a descargar de nuevo??

Simplemente descarga las nuevas series que quieres leer desde otra fuente, además no es que TMO no vaya a funcionar nuevamente, es cuestión de tiempo para que se vuelva a adaptar.

**Comment by koyomin11** [comment]
Por qué no me cargan los capítulos...
Pero tienes razón me esperaré a q se arregle y por lo mientras lo leo en otro, ya q este bien, descargo los q hayan salido
