### ISSUE TITLE
Mangago source is not working 

### ISSUE THREAD

**Issue by Katsukiforov** [inorichi/tachiyomi-extensions#372]
App version: Tachiyomi v.0.7.4

Issue/Request: When I opened the source, it works finely. All of the genres are there, etc. But when I wanted to read the mangas, It just wont load and always showed up the retry button. The pages in the mangas also showed '1/1'. It didn't tell what kind of error was it so I don't know what to do. I've tried searching for the solution but none of it works. Other extensions have no such issues.

Steps to reproduce (if applicable)

**Comment by LakotaGray** [comment]
Issue #368 already opened for this
