### ISSUE TITLE
[Bug] <mangahub>: <time out keeps happening>

### ISSUE THREAD

**Issue by zero100101** [inorichi/tachiyomi-extensions#3720]
### Device information
- TachiyomiJ2K version: 1.0.7
- Android version: 7.1.2

### Source information
- Name: mangahub
- Extension version: 1.2.6

## Steps to reproduce
1. Open mangahub
2. Open mangahub

### Expected behavior
Should load and display manga

### Actual behavior
Time out

### Other details
After opening in webview sometimes works but if I try to search anything same thing happens!
It worked fine first few days.
I can read manga already in my library .

**Comment by SnakeDoc83** [comment]
Looks like they're having server issues.
