### ISSUE TITLE
[Source Request]  Universo Yuri

### ISSUE THREAD

**Issue by AndreaS4D** [inorichi/tachiyomi-extensions#3723]
### Source Website
- Name: Universo Yuri
- Link: https://universoyuri.com/
- Language(s): Spanish/Español

### Other Details
This website has only yuri/Girls love mangas/manwhuas. Some of their updates are in TuMangaOnline Source, but many of them are only available in their own website.

**Comment by SnakeDoc83** [comment]
It's in My Manga Reader CMS.
