### ISSUE TITLE
[Bug] MangaSee: Last Checked Library Glitch

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi-extensions#3724]
### Device information
- Tachiyomi version: r2493
- Android version: 6.0.1

### Source information
- Name: MangaSee.
- Extension version: 1.2.9

## Steps to reproduce
1. Choose the "last checked" sorting.
2. Refresh the library.

### Expected behavior
Manga which have new chapters appear to the top of the list.

### Actual behavior
Expected behaviour happens, but manga added from MangaSee with **no** new chapters **also**  appear at the top.

### Other details
This issue was discovered only after the last MangaSee update.

**Comment by SnakeDoc83** [comment]
Doesn't "last checked" sort by when manga were last checked, not by when they last received a new chapter? Wouldn't "latest chapter" be the actual sort to use if you want the behavior you're describing?

**Comment by MercerBoi** [comment]
> Doesn't "last checked" sort by when manga were last checked, not by when they last received a new chapter? 

Sorting by "last checked" also sorts my manga by when they were last added to my library, and since a "last added" sorting doesn't exist, this was very convenient for me. 

Both "last checked" and "latest chapter" sorting seemed to serve the same function, so it was like hitting two birds with one stone. The difference emerged with this MangaSee "glitch", if it can be called that. This doesn't occur for other sources.

> Wouldn't "latest chapter" be the actual sort to use if you want the behavior you're describing?

This is true, yes. The solution is as simple as changing to the "latest chapter" sorting, but it also sacrifices the "last added" pseudo-benefit (lol), besides, I suppose this new trend in the last checked sorting was worth reporting, since I haven't faced it before.

**Comment by SnakeDoc83** [comment]
Well, there's nothing we can do to the extension that's going to lower where your MangaSee manga show up in the "last checked" sort.
