### ISSUE TITLE
[Bug] <9hentai and allporncomics>: <not working>

### ISSUE THREAD

**Issue by shirlulu007** [inorichi/tachiyomi-extensions#3732]
The search function on 9hentai is not working while allporncomic can't be found(not working)

**Comment by SnakeDoc83** [comment]
* Problem with multiple sources? Open separate issues.
* Use the form or at least be more descriptive. I tried searching for a word and by tag and they both worked for NineHentai; so I don't know what you mean by it not working.
* No idea what "allporncomic can't be found means." It's not in your source list? It's not loading browse/latest? Something else?

Please follow guidelines. Vague reports are hard to resolve.
