### ISSUE TITLE
[Bug] MangaPark: Site works on webview but tachi gives Error 503

### ISSUE THREAD

**Issue by jimc404** [inorichi/tachiyomi-extensions#3734]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 10

### Source information
- Name: MangaPark
- Extension version: 1.2.15

## Steps to reproduce
1. Browse the catalogue of the extension (touch browse in extension list)
2. Open the site in webview and confirm if it's accessible
3. Close webview and refresh the catalogue  

### Expected behavior
List/Grid of mangas should be visible

### Actual behavior
Error 503 (even after bypassing cloudflare in webview)

### Other details
- Reinstall of app does not fix this
- Reinstall of extension does not fix this
- Cleared cache and cookies; didn't fix this

**Comment by picklejuiceenthusiast** [comment]
Having the same issue

**Comment by dafalagi** [comment]
I have tried the steps, but it did nothing.

**Comment by Jdoe1990** [comment]
I am getting the same error message but it works fine in webview

**Comment by intwernetexplorer** [comment]
I'm getting the same error message and have tried opening webview only to go back to catalogue and have the same issue
