### ISSUE TITLE
[Bug] <Mangapark>: <HTTP error 503 is observed>

### ISSUE THREAD

**Issue by Jdoe1990** [inorichi/tachiyomi-extensions#3736]
I am able to read the favorite manga in my library from mangapark. I cannot browse mangapark's manga selection. I opened the webview and completed the captcha but it still didnt fix my problem. 

### Device information
- Tachiyomi version: 0.92(stable) 
- Android version: 10

### Source information
- Name: MangaPark
- Extension version: 1.2.15

## Steps to reproduce
1. Go to browse
2. Click on mangapark

### Expected behavior
This should have sent me to the manga list 

### Actual behavior
This displays "HTTP error 503:Check website in webview"

**Comment by CarlosEsco** [comment]
#3734
