### ISSUE TITLE
[Error in ninemanga] <dominio wrong>: <ninemanga change his domino and now can't use>

### ISSUE THREAD

**Issue by laib2000** [inorichi/tachiyomi-extensions#3739]
### Device information
- Tachiyomi version: 9.2
- Android version: 5.1.1

### Source information
- Name: ninemanga
- Extension version: 1.2.12

## Steps to reproduce
1. Open ninemanga extension 
2. Open webview 

### Expected behavior
Normal funcion

### Actual behavior
Non show any manga

### Other details
Now, whe open in webview the page that show is gardenmanage

**Comment by SnakeDoc83** [comment]
Clear your cookies.
