### ISSUE TITLE
[Source Request] <Nakama Mangas>

### ISSUE THREAD

**Issue by SonnyTK** [inorichi/tachiyomi-extensions#3740]
### Source Website
- Name: Nakama Mangas
- Link: http://nakamamangas.com/
- Language(s): Portuguese (PT-BR)

**Comment by alessandrojean** [comment]
They do have a lot of stuff, but unfortunately all of their content is only available to download, and to make an extension the site has to have a online reader. As I can see, a lot of their projects are available at Union Mangás, so you can use the Union extension to read them instead.

**Comment by SonnyTK** [comment]
> Eles têm muitas coisas, mas infelizmente todo o seu conteúdo está disponível apenas para download e, para fazer uma extensão, o site precisa ter um leitor on-line. Como posso ver, muitos de seus projetos estão disponíveis na Union Mangás, então você pode usar a extensão da União para lê-los.

I see, thank you very much!
