### ISSUE TITLE
[Source Request] mangaworld 

### ISSUE THREAD

**Issue by zero9417** [inorichi/tachiyomi-extensions#3747]
Name: mangaworld
Link: https://www.google.com/url?sa=t&source=web&rct=j&url=https://mangaworld.tv/&ved=2ahUKEwiy47LWw8LqAhUHEpoKHV2DADYQFjAAegQICBAB&usg=AOvVFF22
Language: italian

**Comment by CarlosEsco** [comment]
#2800
