### ISSUE TITLE
Manga Rock: images are saved as wav files

### ISSUE THREAD

**Issue by Jendrej** [inorichi/tachiyomi-extensions#375]
All images saved by holding them and choosing save are saved with a .wav extension. Renaming the file with an image extension fixes it, making it usable.
The images saved by downloading a chapter have a .webp extension as they should.

Tachiyomi: r1422
Manga Rock: 1.0.2

**Comment by arkon** [comment]
I'll look into this.

**Comment by arkon** [comment]
[This line](https://github.com/inorichi/tachiyomi/blob/bff329a3299ce98f85e4bfc75067e4dc8a0d2bcd/app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt#L573) returns a MIME type of `audio/x-wav`. Seems like it can't actually guess `webp` anyway based on [this StackOverflow post](https://stackoverflow.com/a/34722480).

Not sure if there's a straightforward way to solve this. We could:
- Convert to JPEG or PNG in the MangaRock extension (would solve the image decoder issue too, but it's slower and harder on older versions of Android)
- Guess the MIME type based on the URL extension, and handle `.mri`
- ???

**Comment by arkon** [comment]
This is fixed in Tachiyomi 0.8.0.
