### ISSUE TITLE
[Bug] <Super Hentais>: <Not a JSON a object: null>

### ISSUE THREAD

**Issue by SonnyTK** [inorichi/tachiyomi-extensions#3751]
### Device information
- Tachiyomi version: 0.9.2-2493 (standard, 16fc58bd, 45)
- Android version: 6.0

### Source information
- Name: Super Mangás (extension name)
- Extension version: 1.2.2
- Source site: https://www.superhentais.com/

## Steps to reproduce
1. Enter the extension
2. Choose a hentai

### Expected behavior
The chapters available for reading appear without any error

### Actual behavior
When clicking on the hentai some do not load the chapter and the message "Not a JSON a object: null" appears

**Comment by alessandrojean** [comment]
Their chapter pagination is broken at their website. In titles with more than one page, if you go to the second page and try to go back to the first one, it gives an error.

I am working on a temporary solution.
