### ISSUE TITLE
[Cover thumbnails are broken in browse] <Mangasee>: <The cover thumbnails don't show up when I use browse. It's replaced by a broken symbol>

### ISSUE THREAD

**Issue by Pentillum** [inorichi/tachiyomi-extensions#3757]
### Device information
- Tachiyomi version: Preview r2493 (16fc58bd)
- Android version: 9

### Source information
- Name: Mangasee
- Extension version: 1.2.9

## Steps to reproduce
1. Open Browse tab.
2. Under Sources tab click the "BROWSE" button of Mangasee.

### Expected behavior
The cover thumbnails of all available series should show.

### Actual behavior
A broken symbol replaces the cover thumbnail

### Other details
Attached is a screen shot of actual behavior
![photo_2020-07-11_00-58-23](https://user-images.githubusercontent.com/59666465/87217758-6801d680-c312-11ea-946a-74fa31021215.jpg)

**Comment by SnakeDoc83** [comment]
Go to settings and tap "clear database." It's normal to see a few broken covers but not that many.
