### ISSUE TITLE
[Source Request][Spanish] Plot Twist No Fansub

### ISSUE THREAD

**Issue by Xtikma** [inorichi/tachiyomi-extensions#3759]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 6.0
* Device: Samsung J7 (SM-700)

### Source information
* Source name: Madara (Plot Twist no Fansub)
* Source extension version: 1.2.116

## Steps to reproduce
1. Enter any manga
2. Error: No chapters found

## Issue/Request
Any manga, Error: No chapters found

## Other details
The domain they used in the extension is `www.plottwistscan.com`, this fansub also uses the following domain `www.plot-twistnf-scans.com` and apparently it is the one that receives updates and improvements

**Comment by SnakeDoc83** [comment]
Their new site doesn't use Madara's them; so it's going to be removed from the Madara extension. Changing this issue to a source request.

**Comment by Xtikma** [comment]
Sorry for the inconvenience, Thank you very much
