### ISSUE TITLE
[Bug] <mangapark>: <error 503/ cloudflare problem>

### ISSUE THREAD

**Issue by denitaker** [inorichi/tachiyomi-extensions#3760]
Device information
Tachiyomi version: stable 0.9.2
Android version: nougat (7.1.2 N2G47H)

Source information
Name: mangapark
Extension version: 1.2.16

Steps to reproduce:
First Step: open the source from mangapark like usual or manga library from mangapark
Second Step: try browse from the source or try to read the manga

Expected behavior:
It should have worked with all the the updates that i have done

Actual behavior:
It keep showing error massage "java.lang.exception"

Other details
Before i update, the issues was "error 503", just like everyone experienced. But after i update the mangapark source the issues changed to "java.lang.exception cannot bypass clodflare" i tried opening the webview to solve the captcha but it won't let me checklist the captcha box and keep going into endless loading. I also have already tried the preview version and it have the same issues

**Comment by SnakeDoc83** [comment]
What you described was not unexpected. Clear your cookies and try again (also see info about Cloudflare under known issues in #3475). If tapping retry doesn't work, try webview second and let the captcha load for a long time (2+ minutes if necessary). If absolutely nothing works, you'll have to wait until the source stops forcing Cloudflare checks or change sources.
