### ISSUE TITLE
[Bug] <ManhuPlus>: <Error updating manga and manga list not showing and having error>

### ISSUE THREAD

**Issue by ItsMeMaiku** [inorichi/tachiyomi-extensions#3761]
### Device information
- Tachiyomi version: J2K 1.0.7
- Android version: 10

### Source information
- Name: WP-Comics : ManhuaPlus
- Extension version: 1.2.9

## Steps to reproduce
1. Already did view the source in webview and it can be view
![Screenshot_2020-07-11-12-32-59-87_5901a79de973a50c74cff4cbb6149856](https://user-images.githubusercontent.com/40876388/87218000-936fda00-c381-11ea-8415-b7732f76d44a.jpg)
2. Try to manual update an manga but gives a error message
![Screenshot_2020-07-11-14-10-37-04_5901a79de973a50c74cff4cbb6149856](https://user-images.githubusercontent.com/40876388/87217996-894ddb80-c381-11ea-9719-d11342135fdf.jpg)

### Expected behavior
It should update and can be view the list of manga available in the source manhuaplus

### Actual behavior
This is what happening and errors
![Screenshot_2020-07-11-12-32-59-87_5901a79de973a50c74cff4cbb6149856](https://user-images.githubusercontent.com/40876388/87218025-c1551e80-c381-11ea-8973-7cd1fe7b6f0c.jpg)
![Screenshot_2020-07-11-14-10-37-04_5901a79de973a50c74cff4cbb6149856](https://user-images.githubusercontent.com/40876388/87218026-c74aff80-c381-11ea-9c64-0f3df1efbd85.jpg)

### Other details
It seems the source manhuaplus updated their site and redesign it.

**Comment by Riztard** [comment]
it seems they change to madara style

**Comment by ItsMeMaiku** [comment]
> it seems they change to madara style

Hope the source will be fix soon
