### ISSUE TITLE
[Error of dominio] <ninemanga>: <wrong url when open ninemanga>

### ISSUE THREAD

**Issue by laib2000** [inorichi/tachiyomi-extensions#3768]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 5.1.1

### Source information
- Name: ninemanga
- Extension version: 1.2.12

## Steps to reproduce
1. Open ninemanga extension
2. Open webview

### Expected behavior
Normal function 

### Actual behavior
Non show any manga

### Other details
When open webview of ninemanga the page that show is garden manege

**Comment by SnakeDoc83** [comment]
Clear your cookies.
