### ISSUE TITLE
Mangago: Page sorting is broken on (at least) one server

### ISSUE THREAD

**Issue by einstein95** [inorichi/tachiyomi-extensions#377]
Tachiyomi version: 0.7.4
Mangago version: 1.2.5

The image sorting is handled by Mangago's chapter.js, and isn't handled by the extension, leading to pages being out of order in the chapter view.

For example, From Points of Three, ch. 39:

On http://www.lady-first.me/c/31326/441407/1/ (when decrypted), the image URLs are
```
http://iweb7.mangapicgallery.com/r/cspiclink/from_points_of_three/441407/93dd4de5cddba2e2169a4bfd805e9aa21d3112d498d68cc733c65f233097f05a.png
http://iweb9.mangapicgallery.com/imgfiles/from_points_of_three/39/000.png
http://iweb9.mangapicgallery.com/imgfiles/from_points_of_three/39/004.png
http://iweb9.mangapicgallery.com/imgfiles/from_points_of_three/39/007.png
http://iweb9.mangapicgallery.com/imgfiles/from_points_of_three/39/006.png
...
```

On http://www.fashionlib.net/c/31326/441407/1/ (when decrypted), the image URLs are
```
http://iweb9.mangapicgallery.com/imgfiles/from_points_of_three/39/000.png
http://iweb7.mangapicgallery.com/r/cspiclink/from_points_of_three/441407/dc5c7986daef50cf5baf770212313f5e9532ec5e6103b611e02ab09b442ee34f.png
http://iweb7.mangapicgallery.com/r/cspiclink/from_points_of_three/441407/93dd4de5cddba2e2169a4bfd805e9aa21d3112d498d68cc733c65f233097f05a.png
http://iweb9.mangapicgallery.com/imgfiles/from_points_of_three/39/003.png
http://iweb9.mangapicgallery.com/imgfiles/from_points_of_three/39/004.png
...
```

**Comment by megaerairae** [comment]
+1

**Comment by LakotaGray** [comment]
So it means this issue is NOT something that is wrong with Tachiyomi, but the site itself. Just FYI everyone

**Comment by fatimagrace015** [comment]
Uhm, I want to pull a request (extensions) but I dont know how so uhm
pardon me if I did it here.

Put tags in myreadingmanga source.

Is it too much? or too hard? if it is, you can close and delete this..
thank you so much.

**Comment by CarlosEsco** [comment]
Why did you comment here for it?  If you know how to program you can add them and open a PR if not open an issue requesting them. Don't reply to a not related issue asking other questions

**Comment by NoorHooda** [comment]
So isn't there some kind of a solution for this problem , I mean for the chapters being jumbled ? :(

**Comment by Mystique0414** [comment]
there are also some mangas that I downloaded yesterday but most of the chapters are scrambled up :(

**Comment by NoorHooda** [comment]
@mystique0414 I have the same problem , the chapters are out of order and sometimes the downloading won't work :'(

**Comment by joseph619** [comment]
Is this for all mangas/webtoons or just a select few? I haven't found any problem yet.

**Comment by NoorHooda** [comment]
@joseph619 it's happening actually in like the manga "royal servant" , " how sweet os a sugar daddy" , "doridosim" :/ and a lot more mostly the webtoons one :'(

**Comment by rj452** [comment]
Yeah they mostly happen on webtoons 😭 try checking "Cherry Blossoms after Winter" all the chapters are scrambled...

**Comment by Mystique0414** [comment]
@joseph619  there are some mangas that is in order but most of the manga and webtoons that i downloaded yesterday images are scrambled i have to delete it and wait for the next update of the source

**Comment by fatimagrace015** [comment]
Most of updates mangas (even webtoon) are jumbled, such as TGre, Shokugeki no souma etc

**Comment by yasnil** [comment]
Are the pictures already fix?

**Comment by Th3-822** [comment]
It seems that i can get the random pages on the browser too after blocking the "_m_superu=1" cookie (and quickly opening chapter tabs), adding it on the requests may help to fix this issue

**Comment by darkness66** [comment]
Yesssss same here every Manga/webtoons page's missed up !! Only in mangago the other sources working fine tho it's really such a mess :(

**Comment by NoorHooda** [comment]
So can't this be fixed ? It's such a shame :'(

**Comment by yambadr** [comment]
Workaround: Clearing the cookies and cache before loading a chapter seems to make pages load in order.
Credit goes to agenericusername#0226 from Tachi discord.

**Comment by fatimagrace015** [comment]
@yambadr is it safe to do that? wont be the saved and downloaded mangas disappear?

**Comment by CarlosEsco** [comment]
Cookies and cache just clear non library info. It's perfectly fine. Though you have to do it between every chapter

**Comment by fatimagrace015** [comment]
I just cleared the cookies, looked unto blanc mangago and mangadex sources and damn it loads pages in order, but im not that sure due to my turtle connection

**Comment by fatimagrace015** [comment]
So means its safe to clear 'CLEAR CHAPTER CACHE' ?????

**Comment by marinadl** [comment]
+1.
I see you've found a workaround, but clearing cookies and cache every time I want to read a new chapter is troublesome

**Comment by CarlosEsco** [comment]
Nobody plans to fix find a new sourcr

**Comment by joseph619** [comment]
Mangago is actively blocking all scrapers, I use HakuNeko manga downloaded on PC and it doesn't work with Mangago (only site it has issue with). I can still download favorite manga on Tachiyomi however. If anybody wants to read Yaoi, it's better to try Myreadingmanga instead.

**Comment by joseph619** [comment]
Mangago has finally stopped working it seems.
