### ISSUE TITLE
[Bug] <manhwa 18>: <could not bypass cloud flare>

### ISSUE THREAD

**Issue by fawadkhan121** [inorichi/tachiyomi-extensions#3784]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.9.2)
- I have updated all extensions
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/inorichi/tachiyomi
- I have searched the existing issues for duplicates
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions/
- I will fill out the title and the information in this template

### Device information
- Tachiyomi version: 0.9.2
- Android version: 10

### Source information
- Name: Manhwa 18
- Extension version: FM Reader

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened

### Actual behavior
This happens instead

**Comment by arkon** [comment]
https://github.com/inorichi/tachiyomi/issues/3455
