### ISSUE TITLE
[Bug] <Manhuadui>: <Can't watch and download chapters>

### ISSUE THREAD

**Issue by aylz10** [inorichi/tachiyomi-extensions#3787]
### Device information
- Tachiyomi version: r2511
- Android version: 10

### Source information
- Name: Manhuadui
- Extension version: 1.2.7

## Steps to reproduce
1. First Step
Choose to open a comic
2. Second Step
Open or download chapter

### Expected behavior
This should have happened
watch and download chapters
### Actual behavior
This happens instead
Can't watch and download chapters

**Comment by zzy94269664** [comment]
网站加密密码更新 : var key = CryptoJS.enc.Utf8.parse("1231994MHB123456");
var iv = CryptoJS.enc.Utf8.parse('ABCDEF1G34123412');

**Comment by aylz10** [comment]
> 网站加密密码更新 : var key = CryptoJS.enc.Utf8.parse("1231994MHB123456");
> var iv = CryptoJS.enc.Utf8.parse('ABCDEF1G34123412');
感谢
厉害了，我的哥，
