### ISSUE TITLE
[Bug] <Newtoki Ext.>: <All ch. Redirects to blue exorcist>

### ISSUE THREAD

**Issue by napplebun** [inorichi/tachiyomi-extensions#3794]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 9

### Source information
- Name: Newtoki
- Extension version: 1.2.11

## Steps to reproduce
1. View any chapter from newtoki68.com on tachiyomi app.

### Expected behavior
View selected newtoki manhwa chapter 

### Actual behavior
Shows only Ch. 96 Blue Exorcist in Kr. No matter what manhwa you choose.

### Other details
When looking in webview, it sends me to the right manhwa landing page and the chapters are all fine on the site. This only seems to occur on the tachiyomi app.

As far as I know, this wasn't a problem last night (abt 12 hrs ago)

I have tried updating tachiyomi to its current build and cleared cache.

**Comment by SnakeDoc83** [comment]
They made a change on their website; the webtoons are now loaded by JavaScript. So, that needs to be figured out.

**Comment by christofferson** [comment]
"Loaded by JavaScript" seems to be an understatement. There's a script that writes another script into the page that's originally obfuscated as an encoded string of chars which creates a function to deobfuscate a massive `html_data` variable which is created as a string of dot-separated hexadecimal numbers that represent UTF-16 code units that get passed to `String.fromCharCode` which finally results in the pages HTML which the original script then inserts into the document.

Seems they've set up a number of hoops to prevent people from viewing webtoons outside of a browser, which makes sense seeing as they have so many flashing ads on every given page that just trying to inspect the HTML gave me a headache.

**Comment by dingdonng22** [comment]
IS THERE NO WAY TO SOLVE IT?

**Comment by christofferson** [comment]
If that's directed at me, I'm honestly not sure. I don't any experience in Kotlin and I'm not set up for Android development but I'm familiar enough with web development to know roughly what they're doing on their end. If I were in Java or Python it'd be theoretically possible to do it by parsing the obfuscated JavaScript, deobfuscating the string it builds and then further parsing the resulting HTML string for the image URLs.

That being said I wouldn't know if that's a reasonable or even possible thing to try and do in Kotlin or if these new changes make Newtoki now fall under the category of "Sources that won't be added as an extension" (see #3475), namely the part that says:
`sources that require cracking some app's source code (realistically, no one's going to put in the effort to do it)`
