### ISSUE TITLE
[Source Request] <JuinJutsu Team>

### ISSUE THREAD

**Issue by DrPraxi** [inorichi/tachiyomi-extensions#3797]
- Name: Juinjutsu team 
- Link: https://www.juinjutsureader.ovh/
- Language(s): Italian

### Other Details
I have the j2k versione of the app, is this important?

**Comment by AbdullahM0hamed** [comment]
#2958, I'm afraid this won't be added.

**Comment by DrPraxi** [comment]
Why?

**Comment by AbdullahM0hamed** [comment]
It was removed at the behest of the owners.

**Comment by DrPraxi** [comment]
Oh ok
