### ISSUE TITLE
[Bug] Mangá Host: website redesign, doesn't show any manga

### ISSUE THREAD

**Issue by Sam-Oak** [inorichi/tachiyomi-extensions#3799]
## Device information
- Tachiyomi version: Preview r2511 (e33cacf6)
- Android version: 9.0 Pie

### Source information
- Name: Mangá Host
- Extension version: 1.2.9

## Steps to reproduce
1. Go to Browse
2. Click on "Mangá Host" browse button

### Expected behavior
Show all manga from this source.

### Actual behavior
Shows a message saying "No results found".
Site: https://mangahost2.com

**Comment by alessandrojean** [comment]
I will take a look.
