### ISSUE TITLE
[Bug] ehentai: can't browse/search ehentai JP

### ISSUE THREAD

**Issue by PrivatePP** [inorichi/tachiyomi-extensions#3802]
You can't browse or search ehentai (jp), as tachiyomi gives you a blank page with no results found. Ehentai (eng) works just fine, but the japanese one only lets you browse latest.

I'm logged, I've tried to reinstall the extension and clear cookies/cache.

On a side note, I've heard there's a Exhentai extension but I can't seem to find it in the library... ?

---

### Device information
- Tachiyomi version: Stable v0.92
- Android version: 8

### Source information
- Name: ehentai
- Extension version: 1.2.12

**Comment by SnakeDoc83** [comment]
If you want to use ExHentai, you need to use one of the forks (TachiyomiAZ or TachiyomiSY). https://tachiyomi.org/forks/
