### ISSUE TITLE
[Bug] Webtoon extension update

### ISSUE THREAD

**Issue by shashank-p** [inorichi/tachiyomi-extensions#3805]
With latest version 1.2.18 of Webtoon extension when we search in Webtoon browse even bookmarked manga is shown as not bookmarked but it's present in library

**Comment by AbdullahM0hamed** [comment]
Perhaps it's related to https://github.com/inorichi/tachiyomi-extensions/issues/3134#issuecomment-627527713? What happens if you add the one that shows up as not in library to the library?

**Comment by SnakeDoc83** [comment]
Yeah, same issue.

**Comment by shashank-p** [comment]
If i add same one as bookmarked it will create another duplicate entry. I tried migrating from same source (from - to) but it didn't work out.
