### ISSUE TITLE
[Bug] <Hentai2read>: <Source is not showing latest updates>

### ISSUE THREAD

**Issue by zuvba** [inorichi/tachiyomi-extensions#3806]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 10

### Source information
- Name: hentai2read
- Extension version: hentai2read

## Steps to reproduce
Clicking the latest update shows that no new manga have been updated since 7/10/20

### Expected behavior
Clicking the latest updates should show all recent updates 

### Actual behavior
The source hasn't been updating for the past 6 days

**Comment by SnakeDoc83** [comment]
Latest is scraped from this page: https://hentai2read.com/hentai-list/all/any/all/last-updated. Results seem to be what they should be.

**Comment by zuvba** [comment]
Oh I see what I did wrong, when I looked at website I checked newest instead of lastest updates and was thinking something was wrong
