### ISSUE TITLE
[Bug] Webtoonxyz not updating new chapters

### ISSUE THREAD

**Issue by Sajeeb97** [inorichi/tachiyomi-extensions#3818]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 8.1

### Source information
- Name: Webtoonxyz
- Extension version: Madara 1.2.118

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
New chapters should update when pull down

### Actual behavior
This happens instead

### Other details
![Screenshot_Tachiyomi_20200717-152938](https://user-images.githubusercontent.com/62636945/87783896-dff56280-c824-11ea-9eb2-677a780a757c.png)
When I pull down the manga it doesnt load new chapters.Instead it shows no chapter found whereas I can see there are new chapters on the webview.

**Comment by arkon** [comment]
#3816
