### ISSUE TITLE
[Source Request Arabic] <azora manga/>

### ISSUE THREAD

**Issue by REDAKUN** [inorichi/tachiyomi-extensions#3823]
---

### Source Website
- Name: ? Agora Manga 
- Link: ? https://www.azoramanga.com/
- Language(s): ? Arabic

**Comment by arkon** [comment]
Also in Madara.

Please do the due diligence of actually checking instead of just opening requests.

**Comment by REDAKUN** [comment]
Did I did something wrong ?
Cuz Arabic Manga web site have weird name? Or something else 
And thank u❤
