### ISSUE TITLE
[Source Request Arabic] <shqqaa>

### ISSUE THREAD

**Issue by REDAKUN** [inorichi/tachiyomi-extensions#3825]
---

### Source Website
- Name: ? Shqqaa
- Link: ? https://www.shqqaa.com/
- Language(s): ? Arabic

**Comment by AbdullahM0hamed** [comment]
Already exists https://raw.githubusercontent.com/inorichi/tachiyomi-extensions/repo/apk/tachiyomi-ar.shqqaa-v1.2.2.apk
