### ISSUE TITLE
[Bug] mangairo: slow in tachiyomi

### ISSUE THREAD

**Issue by evo85210** [inorichi/tachiyomi-extensions#3835]
### Device information
- App version: 0.9.2-2511 (standard, e33cacf6, 45)
- Android version: 10 (SDK 29)

### Source information
- Name: mangairo
- Extension version: mangabox 1.2.24

## Steps to reproduce
1. Open any manga from mangairo
2. Image loading takes forever 
3. Open in web using the globe shortcut, images loads instantly
4. Open in tachiyomi again, all images are instantly loaded.

### Expected behavior
Images to load instantly the first try

### Actual behavior
Takes forever to unload without loading it from the web first

### Other details
Also happens on others sources from mangabox extension

**Comment by SnakeDoc83** [comment]
Speed may vary, but using webview to make pages load quicker is more than likely a placebo effect. There's already [this request](https://github.com/inorichi/tachiyomi-extensions/issues/2720) to use alternate image servers; beyond that there isn't really anything else that can be done.
