### ISSUE TITLE
[Bug] <ComicLatest>: <Search and Author fitler keeps repeating>

### ISSUE THREAD

**Issue by TheWrightStuff1994** [inorichi/tachiyomi-extensions#3839]
###Device information
- Tachiyomi version: r2511
- Android version: Kindle Fire OS

### Source information
- Name: ComicLatest
- Extension version: WP-Comics 1.2.12

## Steps to reproduce
1. Search for comic and the list just repeats over and over. It also does this to the filters as well

### Expected behavior
List shows all pages and not page 1 of comics

### Actual behavior
Infinite loop of the same page

**Comment by AbdullahM0hamed** [comment]
Looking at chapter 1 of Claymore (the first comic in browse), the pages seem to be distinct. Could you tell us what particular manga this issue occurs on?

**Comment by AbdullahM0hamed** [comment]
Oh nvm, read the title.
