### ISSUE TITLE
Mangadex: HTML uncode group names

### ISSUE THREAD

**Issue by einstein95** [inorichi/tachiyomi-extensions#384]
Mangadex version: 1.2.31
Tachiyomi version: 0.7.4 and dev r1425

When displaying the scanlation group for manga such as [Ijiranaide, Nagatoro-san](https://mangadex.org/manga/22631/ijiranaide-nagatoro-san), groups with non-ASCII characters are displayed with the symbols HTML-encoded.

Taking Ijiranaide, Nagatoro-san as an example, `Fangéd Scans` displays as `Fang&eacute;d Scans`

**Comment by arkon** [comment]
@CarlosEsco This can be closed, right?

**Comment by CarlosEsco** [comment]
No. This is in the beta pull still
