### ISSUE TITLE
[Bug] <ComicLatest>: <Comics Don't have all issues>

### ISSUE THREAD

**Issue by TheWrightStuff1994** [inorichi/tachiyomi-extensions#3843]
###Device information

Tachiyomi version: r2511
Android version: Kindle Fire OS

Source information
Name: ComicLatest
Extension version: WP-Comics 1.2.13

Steps to reproduce
Check a comic and scroll through

Expected behavior
Comics have all of there issues

Actual behavior
100 Bullets a comic that has 100 issues only has 51 issues showing

Other details
Sorry if I'm a bit nit picking about this source

**Comment by AbdullahM0hamed** [comment]
![Screenshot_20200719-215125_TachiyomiJ2K](https://user-images.githubusercontent.com/25087116/87884966-0aecdb80-ca0a-11ea-8e22-577fdc0b1d3e.jpg)

Strange, I seem to have 100 issues for "100 Bullets Comic"

**Comment by TheWrightStuff1994** [comment]
> ![Screenshot_20200719-215125_TachiyomiJ2K](https://user-images.githubusercontent.com/25087116/87884966-0aecdb80-ca0a-11ea-8e22-577fdc0b1d3e.jpg)
> 
> Strange, I seem to have 100 issues for "100 Bullets Comic"

Scroll to the bottom of that page

**Comment by AbdullahM0hamed** [comment]
![Screenshot_20200720-003512_TachiyomiJ2K](https://user-images.githubusercontent.com/25087116/87887908-0d0e6480-ca21-11ea-9ed4-bb641641c4ee.jpg)

It starts from the first chapter and goes to 100 with no breaks that I can see. Maybe it would more helpful if you sent a screenshot of what you're seeing?

**Comment by TheWrightStuff1994** [comment]
Sorry you are right I guess my version of the app didn't show the rest for me but now it does. Sorry for the inconvenience...

**Comment by AbdullahM0hamed** [comment]
No worries.
