### ISSUE TITLE
[Bug] PT-br sources are not displayed

### ISSUE THREAD

**Issue by Shankusuu** [inorichi/tachiyomi-extensions#3849]
When I add any pt-br extension, it doesn't show on "sources", but other languages works normal.
I tried to re-install the app, delete and install extensions again, but doesn't seem to work.

**Comment by arkon** [comment]
Enable the locale from the filter menu at the top right.

**Comment by Shankusuu** [comment]
> Enable the locale from the filter menu at the top right.

It's already enabled, i can see and download all the extensions, but after it, they dont appear in "sources" :(

**Comment by arkon** [comment]
You need to do it in the filter menu at the top right **of the sources screen**, not the extensions one.

**Comment by Shankusuu** [comment]
> You need to do it in the filter menu at the top right **of the sources screen**, not the extensions one.

WoW, felling kinda dumb now, it worked thanks man.
