### ISSUE TITLE
[Bug] NHentai filtering issue

### ISSUE THREAD

**Issue by joeasis** [inorichi/tachiyomi-extensions#3851]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 7.0

### Source information
- Name: nhentai
- Extension version: All 1.2.26

## Steps to reproduce
1. Filter
2. Sort by: Recent

### Expected behavior
List sorted to latest by descending order

### Actual behavior
shows featured content from weeks or months ago

### Other details
only tags section of filter tested, no issue there.

**Comment by SnakeDoc83** [comment]
Are you using any of the other inputs or are you literally just changing "Sort By" to recent and nothing else?

**Comment by MercerBoi** [comment]
Facing the same issue here, the "recent" ones don't appear, with or without any tags given.

**Comment by MercerBoi** [comment]
Just for clarification, the  `Sort By: Recent` filter is the option to use if I want to see the *latest* entries with a particular tag/artist/etc. right? If yes, it still doesn't work. However, I can circumvent this issue by mentioning the upload date manually, but I thought I'd let you know since it's still a minor bug.

**Comment by SnakeDoc83** [comment]
This issue has come up before. Since the first time it was mentioned a
number of people chimed in and most people said it worked fine while a
couple have had a problem. I've tried tweaking it a few ways so that it
works for everybody but I guess it's just not happening.

**Comment by vengiare** [comment]
Someone else had the same issue, hmm.

The last time, I tried it in TachiyomiJ2K and it worked so, maybe this is an issue with the main app? Not really sure.
