### ISSUE TITLE
[Bug] <mangabox>: <series reappearing as new>

### ISSUE THREAD

**Issue by Void2258** [inorichi/tachiyomi-extensions#3852]
### Device information
- Tachiyomi version: stable 0.9.2
- Android version: 10

### Source information
- Name: mangakakalot
- Extension version: 1.2.24

## Steps to reproduce
1. Check for new chapters of Manaa you are already reading. Must be done one at a time; full library update check gives no error or indication of issue.

### Expected behavior
Manga updated (for all if full refresh)

### Actual behavior
Many manga not updated with no error message if full library refresh.
For individual manga refresh, Error message "source url has changed", no updates possible

### Other details
Manga reappears as brand new manga with identical name that must be resubscribed to after manually finding it again in the catalog. No message or error except in individual manga subscriptions, so you have to manually check every single manga to see which have this issue. Refreshing the entire library does not show any indication of this issue. All progress details lost. Downloaded chapters recognized by new subscription. Old subscription must be manually removed. Must manually mark read up to point.

**Comment by SnakeDoc83** [comment]
Under More > Settings > Library is a toggle to "Show update errors notifications." If you had that on, you more than likely would have gotten an error stating "Source URL has changed" for the manga you've had issue with. Mangakakalot changed some of the URLs for their manga making them appear as new/separate from the manga you had favorited. There's nothing we can do, you have to migrate those manga. Check discord's FAQ about Mangakakalot duplicate URLs or ask in the support channel if you want further details.

**Comment by Void2258** [comment]
The described option `More > Settings > Library is a toggle to "Show update errors notifications."` does not exist.

**Comment by SnakeDoc83** [comment]
If it's not there then I guess it was added after the latest stable release.
