### ISSUE TITLE
[Bug] Mangahub Extension: Chapters not loading

### ISSUE THREAD

**Issue by ItzRaze** [inorichi/tachiyomi-extensions#3855]
### Device information
- Tachiyomi version: stable 0.9.2
- Android version: 7 Nougat 

### Source information
- Name: Mangahub
- Extension version: 1.2.6

## Steps to reproduce
1.Open Mangahub
2.Tap any manga
3.Try to read any chapter of said manga

### Expected behavior
Manga Chapter open, images load

### Actual behavior
Images do not load, "RETRY" displayed

### Other details
![FB_IMG_15952371276443374](https://user-images.githubusercontent.com/68539202/87922202-8f277900-ca73-11ea-9606-b8d9403b907e.jpg)
![FB_IMG_15952371305022283](https://user-images.githubusercontent.com/68539202/87922211-9189d300-ca73-11ea-9aa4-4e9a78740d99.jpg)

**Comment by SnakeDoc83** [comment]
It's working for me. You've tried multiple different manga and none load?

**Comment by psychopomp9** [comment]
there's an official source(Webtoon) out there for TOG! why would you read it from mangahub? just saying!

**Comment by psychopomp9** [comment]
i tried to load the same chp and it worked!

**Comment by ItzRaze** [comment]
> there's an official source(Webtoon) out there for TOG! why would you read it from mangahub? just saying!

It's not just Tower of God, that's an example


> It's working for me. You've tried multiple different manga and none load?

Wahhhh??? It's still not working for me, It's been like this for months

**Comment by ItzRaze** [comment]
> i tried to load the same chp and it worked!

Okay, This ain't funny, why just me?

**Comment by SnakeDoc83** [comment]
Things to try: clear cookies, use a different data connection (wifi, cellullar), turn off any VPN or adblocker you might be using.

Also, do the images load when you open a chapter in webview?

**Comment by ItzRaze** [comment]
> Things to try: clear cookies, use a different data connection (wifi, cellullar), turn off any VPN or adblocker you might be using.
> 
> Also, do the images load when you open a chapter in webview?

No, they don't 
![Screenshot_20200721-133648](https://user-images.githubusercontent.com/68539202/88055683-4b0da480-cb57-11ea-86e3-632583306874.png)

**Comment by SnakeDoc83** [comment]
Seems like you're being blocked by the image host, your ISP, or something. I don't think there's anything we can change that'll help you out with that.
