### ISSUE TITLE
[Bug] Shonen Jump+: HTTP Error 404

### ISSUE THREAD

**Issue by Donnie-B** [inorichi/tachiyomi-extensions#3856]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 9

### Source information
- Name: Shonen Jump+
- Extension version: 1.2.1

## Steps to reproduce
1. Browse any manga title under Shonen Jump+
2. Get HTTP Error 404 when try to open the chapter

### Expected behavior
Should be able to view the chapter normally

### Actual behavior
Get HTTP error 404

**Comment by alessandrojean** [comment]
I will take a look.
