### ISSUE TITLE
Kissmana source error

### ISSUE THREAD

**Issue by Syborg49** [inorichi/tachiyomi-extensions#386]
I'm having issues with Kissmana source. It's gives me the error "SyntaxError : Parse error (line 1). Please see the attached image for more clarification. Tachiyomi version is Tachiyomi dev r1425 Build time Jul 1 2018. 
![screenshot_20180706-172932](https://user-images.githubusercontent.com/14856809/42377133-c9614892-8143-11e8-92ba-2d23e319c7c4.png)

**Comment by CarlosEsco** [comment]
Dupes of others. Look through the other issues I posted a potential solution that works for most.

**Comment by Syborg49** [comment]
I'm sorry, I couldn't find one. Can you please repeat what the solution is? @carlosEsco ?

**Comment by CarlosEsco** [comment]
- In Tachiyomi go to settings advanced  and clear cookies
- Opened chrome go to website that is causing the issue
- click a random comic/manga and click a chapter, let it load
- Open Tachiyomi
- go to catalouges and click the browse button the source that is having the issue
-it should work, if it does not click the retry button after a couple retry attempts it should work
-If still isn’t working, close Tachi, swipe away from recents, and restart app

now you can go back to your library and read your chapters/download
