### ISSUE TITLE
[Meta] Combining this application with other downloaders for wider coverage

### ISSUE THREAD

**Issue by DonaldTsang** [inorichi/tachiyomi-extensions#3860]
###  Why/Project's Benefit/Existing Problem

In order to increase the amount of websites that could be included into tachiyomi, without adding too much workload, it is possible to us https://github.com/manga-py/manga-py or https://github.com/manga-download/hakuneko to add more sites. The other alternative would be to individually add support for each site, and use the source code of these repos as a reference for downloading.

**Comment by SnakeDoc83** [comment]
If you're suggesting either of those projects would be a simple plug-and-play to work with Tachiyomi--no. We're also not going to try to add every source those projects cover. If someone wants to request a source, that's fine; but if you're suggesting we add every source they cover just for the sake of more sources, then that's also a no. We have 400+ sources, we're not dying for lack of them.
