### ISSUE TITLE
[Source Request] toonily>

### ISSUE THREAD

**Issue by Slowxzy** [inorichi/tachiyomi-extensions#3866]
---

### Source Website
- Name: toonliy
- Link: https://toonily.net
- Language(s): English 

### Other Details
There is another website with the same in madara and it is toonilv.com

**Comment by jobobby04** [comment]
Already a part of Madara

**Comment by AbdullahM0hamed** [comment]
The toonily in Madara is toonily.com and not toonily.net which this issue requests
