### ISSUE TITLE
[Bug] Dmzj cannot read any chapters.

### ISSUE THREAD

**Issue by pzy2222** [inorichi/tachiyomi-extensions#3867]
### Device information
* Tachiyomi version: 0.9.2
* Android version: 10
* Device: Redmi Note 5

### Source information
* Source name: Dmzj
* Source extension version: 1.2.9

## Steps to reproduce
1. Enter any chapters.
2. Be forced to exit automatically, and a toast says "HTTP error 500".

## Issue/Request
I wish the developer could find the problem and fix it so that users can read manga as past.

## Other details
No other details yet.

**Comment by pzy2222** [comment]
The bug vanished, I guess this bug is from the website altering.

**Comment by SnakeDoc83** [comment]
It's not a bug. An HTTP error 500 means there was a problem with their server. Just wait for them to fix their stuff when that happens.
