### ISSUE TITLE
[Bug] <Golden Mangás>: java.lang.Exception: Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by dkzerah** [inorichi/tachiyomi-extensions#3868]
### Device information
- Tachiyomi version: 0.9.2-2543 (standard, 0cef05dd, 45)
- Android version: 8.0.0

### Source information
- Name: Golden Mangás
- Extension version: 1.2.5

## Steps to reproduce
1. I try to update any "Golden Mangás" manga
2. java.lang.Exception: Failed to bypass Cloudflare

### Other details
Log: https://pastebin.com/p3hBeH6G

**Comment by AbdullahM0hamed** [comment]
Have you tried going to the Golden Mangás source, and opening in webview?

**Comment by dkzerah** [comment]
Yes, I went to the webview I did Captcha, but after doing it it is "Checking your browser before accessing goldenmangas.top" and then immediately goes back to Captcha and stays in this cycle forever.

**Comment by alessandrojean** [comment]
I tried here and after two or three times passing through the captcha it loads the site in WebView, so when I closed and clicked on Retry it worked fine.

You can try to do the captcha more times again and see if it works. If not, you can try to update your WebView or check if the WebView used in your system is the Chrome one, it tends to work better.
