### ISSUE TITLE
[Bug] mangatown: updates not showing at all

### ISSUE THREAD

**Issue by theoscat** [inorichi/tachiyomi-extensions#3871]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 

### Source information
- Name: mangatown
- Extension version: 1.2.4

## Steps to reproduce
1. First Step - open the ''updates'' tab
2. Second Step - pull to refresh

### Expected behavior
This should have updated the list with newest chapters from my favs

### Actual behavior
No updates, last chapters is 2 days old even though there's a lot of newer chapter on the website.

### Other details
I have only one extension, i've been using mangatown from the start.

**Comment by SnakeDoc83** [comment]
So your chapter lists are inaccurate? Post an example.

**Comment by theoscat** [comment]
![Screenshot_20200722_104437_eu kanade tachiyomi](https://user-images.githubusercontent.com/18569964/88159118-296ef480-cc0d-11ea-85a8-82965a6695fc.jpg)

I'm talking about this list

**Comment by SnakeDoc83** [comment]
Right, but my question still stands. I checked their website and GOMA's last chapter was 117.3 on the 20th and Eternal's last chapter was 236 on the 19th. So, which of your favorited manga has new chapters in the last two days? I want you to give me an example of a manga that you've favorited that has had new chapters on their website in the last two days that aren't showing up in Tachiyomi (in other words, an inaccurate chapter list).

**Comment by bbtora** [comment]
One user gave an example of such occurrence in the discord server.

**A Returner's Magic Should be Special**

**Comment by theoscat** [comment]
Okay,
Here's a few example 
![Screenshot_20200722_114147](https://user-images.githubusercontent.com/18569964/88161620-7ef8d080-cc10-11ea-9654-e97005d8e4dd.jpg)
![Screenshot_20200722_114128](https://user-images.githubusercontent.com/18569964/88161624-7f916700-cc10-11ea-9a96-aaae8639955c.jpg)
![Screenshot_20200722_114110](https://user-images.githubusercontent.com/18569964/88161626-8029fd80-cc10-11ea-9cd1-03b6033c3866.jpg)

Maybe this info will help as well: when i browse the latests from the source, there's no new chapters since 2 days. 
![Screenshot_20200722_114210_eu kanade tachiyomi](https://user-images.githubusercontent.com/18569964/88161825-c7b08980-cc10-11ea-8771-e17156118d78.jpg)

It seems that the app is not able to crawl the source anymore. 
I've noticed that on web, the latest tab from mangatown is not updated aswell, but on mobile there's no problem.
See www.mangatown.com/latest vs www.m.mangatown.com/latest

**Comment by theoscat** [comment]
> One user gave an example of such occurrence in the discord server.
> 
> **A Returner's Magic Should be Special**

it was me

**Comment by SnakeDoc83** [comment]
Their mobile version of the site is getting new chapters but not their desktop version. That's dumb.

**Comment by SnakeDoc83** [comment]
It seems like they've mostly fixed their desktop version and you should be getting new chapters again. I had taken a look at switching to their mobile site for scraping, but the chapter names are different. I'd rather not switch if we don't have to; so I'm going to leave it as is.
