### ISSUE TITLE
[Bug] Yaoi Toshokan: no pages load, but info and chapters load normally

### ISSUE THREAD

**Issue by Sam-Oak** [inorichi/tachiyomi-extensions#3873]
### Device information
- Tachiyomi version: Preview r2511 (e33cacf6)
- Android version: 9.0 Pie

### Source information
- Name: Yaoi Toshokan
- Extension version: Madara (multiple sources)

## Steps to reproduce
1. Click on Yaoi Toshokan in Browse
2. Open any manga and start reading

### Expected behavior
the pages I'm reading loads normally

### Actual behavior
No pages load. shows the "retry" button on all pages almost immediately

### Other details
The site works fin. this happens in all manga, only the pages give an error
Site: https://www.yaoitoshokan.com.br

**Comment by alessandrojean** [comment]
I will take a look.
