### ISSUE TITLE
Readcomicsonline's search function doesn't work, cant search for anything, only the popular browsing works.

### ISSUE THREAD

**Issue by borouj-rashid-UOIT** [inorichi/tachiyomi-extensions#388]
(CATALOGUE) SOURCE REQUESTS:
  One source per issue, create more issues if you have more websites
  Check for duplicates, use search (in issues, not the global one)
  Put the name of the site as Title, replace this text with clickable link to the site
BUGS:
  Provide tachiyomi version as well as version of source the report is about

**Comment by CarlosEsco** [comment]
#387 just waiting for version code change

**Comment by arkon** [comment]
Should this be closed?
