### ISSUE TITLE
[Bug] <MangaRaw>: <Handshake failed>

### ISSUE THREAD

**Issue by Sereinxon** [inorichi/tachiyomi-extensions#3881]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 9

### Source information
- Name: MangaRaw
- Extension version: 1.2.1

## Steps to reproduce
1. First Step
Select from Source

### Expected behavior
This should have happened
Show Page
### Actual behavior
This happens instead
Handshake failed
### Other details
I use translation software.
This is why I can't write in detail.
![81331](https://user-images.githubusercontent.com/62329071/88363667-b9eb3780-cdbb-11ea-990b-5d817cbe531c.jpg)

**Comment by arkon** [comment]
This is fixed in the preview builds. It will be part of the next stable release.
