### ISSUE TITLE
[Bug] <manhwa time >: <400 error>

### ISSUE THREAD

**Issue by fawadkhan121** [inorichi/tachiyomi-extensions#3882]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.9.2)
- I have updated all extensions
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/inorichi/tachiyomi
- I have searched the existing issues for duplicates
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions/
- I will fill out the title and the information in this template

### Device information
- Tachiyomi version: 0.9.2
- Android version: 10

### Source information
- Name: manhwa time 
- Extension version: madara 

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened
Manhwa time should load properly
### Actual behavior
This happens instead
Giving 400 error saying check web view but webview is working but not showing and saying check web view

**Comment by fawadkhan121** [comment]
@SnakeDoc83

**Comment by SnakeDoc83** [comment]
They changed their website theme (no longer using Madara).

Also, you really don't need to tag me any time you open an issue.

**Comment by fawadkhan121** [comment]
Ok sorry for the tag though
