### ISSUE TITLE
[Bug] Mangahasu: Malformed JSON

### ISSUE THREAD

**Issue by Kavboy** [inorichi/tachiyomi-extensions#3884]
### Device information
- Tachiyomi version: r2543
- Android version: 8.0

### Source information
- Name: Mangahasu
- Extension version: 1.2.8

## Steps to reproduce
Try to open any chapter of any manga

### Expected behavior
Loads the pages of the chapter

### Actual behavior
Shows a malformed JSON error

**Comment by SnakeDoc83** [comment]
Do you get any messages about cloudflare when you use Mangahasu?  Try opening a manga in webview, open a chapter (from that webview page), solve the captcha if you get one; then close webview and try to open a chapter like you would normally. Anything different?

**Comment by Kavboy** [comment]
That is the first thing I do when I can´t open a chapter from Mangahasu and until yesterday that procedure worked. But since yesterday I get the malformed JSON error.
![image](https://user-images.githubusercontent.com/24781933/88455747-43603f80-ce78-11ea-8b3e-83f918a7ddce.png)

**Comment by Kavboy** [comment]
Seems like now only chapter 59 of the manga "A Pretty´s Super Zombie" is the Problem. Because there seem to be no images.
Don´t now why other mangas also had problems but now their working, so I´m closing this issue.
