### ISSUE TITLE
[Bug] MangaDex: MangaDex Only works in English Language

### ISSUE THREAD

**Issue by LenKiMo** [inorichi/tachiyomi-extensions#3890]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 10

### Source information
- Name: MangaDex
- Extension version: 1.2.95

## Steps to reproduce
1. Register a MangaDex account, and set `Filter chapter languages` for `Chinese(Simp)` and `Chinese(Trad)`, set `User interface language` for `Chinese(Simp)`
2. Login MangaDex via Tahiyomi's Webview, and check the language setting as above.
3. Search any Manga which has Chinese and English language.

### Expected behavior
It should only list Chinese language chapters.

### Actual behavior
It only display English language chapters, if the manga only have Chinese language, it would reply No Chapter.

### Other details
Though MangaDex extension has multiple languages setting, it would only added as MangaDex(EN), but can't cover other language.

**Comment by LenKiMo** [comment]
Found where went wrong.

**Comment by yury-o** [comment]
> Found where went wrong.

hey, could you tell me how you solved it? I'm having the same issue.

**Comment by LenKiMo** [comment]
> > Found where went wrong.
> 
> hey, could you tell me how you solved it? I'm having the same issue.

You should go to Language Filter or something like that, find your language's MangaDex and turn it on.
I am using TachiJ2K, and the filter locate in up-right corner.

**Comment by yury-o** [comment]
It worked. thank you so much
