### ISSUE TITLE
[Source Request] <Gmanga>

### ISSUE THREAD

**Issue by motsouzumaki** [inorichi/tachiyomi-extensions#3899]
Source Website

- Name: gmanga
- Link: https://gmanga.me
- Language(s): arabic

Other Details
The largest arabic manga library....I hope that you fulfill my request and thank you for your efforts

**Comment by SnakeDoc83** [comment]
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/117

**Comment by motsouzumaki** [comment]
> Duplicate of #117

Oh no problem
