### ISSUE TITLE
[Bug] MangaSee/MangaLife: Browse and Search Non-Functional

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi-extensions#3904]
### Device information
- Tachiyomi version: Dev r2543
- Android version: 6.0.1

### Source information
- Name: MangaSee and MangaLife.
- Extension version: 1.2.11 and 1.2.8 respectively.

## Steps to reproduce
1. Open these sources.
2. Browse them or search in them.

### Expected behavior
Browsing should load the cover, manga information and chapter list of any manga I'm viewing, and searching should come up with the manga I'm searching for.

### Actual behavior
When opening either of these sources, none of the covers load, and neither do the chapter lists. Searching results in infinite loading. Sometimes it results in infinite loading for browsing too, and I can see that no data is being used at that point for some reason. 

### Other details
Both websites are working normally in webview/browser. My network is also working normally for everything else.

**Comment by CarlosEsco** [comment]
Have you tried clearing the db in advanced settings. They are working fine for me

**Comment by MercerBoi** [comment]
The issue seems to have been fixed by using the `refresh library manga covers` option under Advanced Settings. My apologies.
