### ISSUE TITLE
[Bug] <Mangá Host>: problems with chapters and covers

### ISSUE THREAD

**Issue by Sam-Oak** [inorichi/tachiyomi-extensions#3914]
### Device information
- Tachiyomi version: Preview r2569 (e95a5be2)
- Android version: 9.0 Pie

### Source information
- Name: Mangá Host
- Extension version: MangaHost

## Steps to reproduce
1. Click on Mangá Host on browse
2. Open any manga and click on any chapter

### Expected behavior
show the pages of this chapter

### Actual behavior
returns to the manga information screen and shows an empty floating message (see the image below)

### Other details
the manga covers don't load unless I click on one and go back.

![Screenshot_20200726212452](https://user-images.githubusercontent.com/62823895/88493481-cc19d100-cf87-11ea-9480-8ea63163a195.jpg)

**Comment by alessandrojean** [comment]
Should be fixed by #3913.
