### ISSUE TITLE
[Bug] <Manhuagui>: <regexp syntax error>

### ISSUE THREAD

**Issue by 29988122** [inorichi/tachiyomi-extensions#3924]
### Device information
- Tachiyomi version: J2K latest version
- Android version: 8

### Source information
- Name: Manhuagui
- Extension version: 1.2.3

## Steps to reproduce
1. Open any manga
2. This toast message appears:
![2020-07-27 22 11 06](https://user-images.githubusercontent.com/5474709/88552451-b0313080-d056-11ea-8a05-74639a2fe10f.png)

It's the same for every manga.
IP not blocked, working normally in webview.

### Other details
Revert to version 1.2.2 doesn't work. This error only happened recently(<weeks or a month), so I assume that it's not because of this extension update.

Thank you, SnakeDoc83!

**Comment by SnakeDoc83** [comment]
Closed by https://github.com/inorichi/tachiyomi-extensions/pull/3926
