### ISSUE TITLE
[Bug] <bato.to>: <failed to baypass cloudflare>

### ISSUE THREAD

**Issue by Okaklaaaa** [inorichi/tachiyomi-extensions#3933]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 7.1.1

### Source information
- Name: bato.to
- Extension version: emerald 1.2.1

## Steps to reproduce
1. Open bato.to
2. Try any (and all) Chapter List sources

### Expected behavior
I could view and download mangas from extension source

### Actual behavior
I get "No Results" on 'latest' and 'browse' tabs, cannot search for manga either.

### Other details
Webview pulls up the site just fine. Not sure why nothing lets me view manga through this extension.

![Screenshot_20200728-120942](https://user-images.githubusercontent.com/68888116/88622278-fd7ec380-d091-11ea-8e23-c39cb43f419b.jpg)

**Comment by CarlosEsco** [comment]
So when you click that open in webview. Let it load then back out it doesn't work?

**Comment by arkon** [comment]
See #3475 regarding Cloudflare.
