### ISSUE TITLE
Can't access Twinscomic

### ISSUE THREAD

**Issue by john1991albert** [inorichi/tachiyomi-extensions#3934]
### Device information
* Tachiyomi version: 0.9.2
* Android version: Nougat
* Device: Xiaomi Mi Max 2

### Source information
* Source name: Twinscomic
* Source extension version: 1.2.3

## Steps to reproduce
1. First step
2. Second step

## Issue/Request
I cant read comic on twinscomic

## Other details
Additional details and attachments.

**Comment by SnakeDoc83** [comment]
Their website is down.
