### ISSUE TITLE
[Bug] ReadManhwa: NSFW flag

### ISSUE THREAD

**Issue by alraun3** [inorichi/tachiyomi-extensions#3936]
### Device information
- Tachiyomi version: 0.9.2
- Android version: 10

### Source information
- Name: ReadManhwa
- Extension version: 1.2.3

### Other details

ReadManhwa has a new flag which is false by default `nsfw=false` resulting on some titles not appearing on Tachiyomi. Can we make this flag true by default? Or other changes are necessary?

**Comment by edgar1016** [comment]
Device information
Tachiyomi version: 0.10.3
Android version: 9
Source information
Name: ReadManhwa
Extension version: 1.2.5
Other details
Not sure of something else has changed but ticking `show NSFW` on this extension still has all the NSFW manhwa hidden for me. When it's ticked on and I filter by the Adult genre I get no results found.
