### ISSUE TITLE
[Bug] Manhwatime : HTTP Error 404 (Madara)

### ISSUE THREAD

**Issue by Thoasty** [inorichi/tachiyomi-extensions#3944]
This Madara source hasn't been working for the last couple of days.

[https://manhwatime.xyz/](url)

Thank you.

---

### Device information
- Tachiyomi version: Stable 0.9.2

### Source information
- Name: Madara
- Extension version: All 1.2.124

**Comment by SnakeDoc83** [comment]
Was removed days ago, it has its own extension now.

**Comment by Thoasty** [comment]
Thanks! I didn't find change with search function here.
