### ISSUE TITLE
[Bug] <Readmanhwa>: <NSFW flag is false by default>

### ISSUE THREAD

**Issue by Zedefex** [inorichi/tachiyomi-extensions#3950]
#3945 # Device information
- Tachiyomi version: 0.9.2
- Android version: 9

### Source information
- Name: ReadManhwa
- Extension version: 1.2.4

### Expected behavior
Usually the first page shows the most viewed NSFW and bookmarked NSFW mangas from the source can be read normally.

### Actual behavior
Now the NSFW flag is false by default resulting in missing NSFW mangas as well as a HTTP Error 404 message when attempting to open a bookmarked NSFW manga from that source. 

### Other details
I noticed this bug was fixed yesterday after updating the extension but it somehow returned to the original problem again today.

**Comment by SnakeDoc83** [comment]
They changed their site again; so it broke again.

**Comment by Thoasty** [comment]
It looks like this issue is broken again.
