### ISSUE TITLE
[Bug] Mangasee: extreme loading times

### ISSUE THREAD

**Issue by BlackIceFire** [inorichi/tachiyomi-extensions#3954]
### Device information
- Tachiyomi version: 1.0.7
- Android version: 10

### Source information
- Name: Mangasee
- Extension version: 1.2.11

### Expected behavior
Catalogue and Latest Updates should load 

### Actual behavior
Catalogue and Latest Updates take ages to load the manga and don't load most covers at all.
![20200730_145629](https://user-images.githubusercontent.com/68996853/88925512-e9df8280-d274-11ea-9f5c-2d8e0f38e12d.jpg)
![20200730_145618](https://user-images.githubusercontent.com/68996853/88925513-e9df8280-d274-11ea-992a-2f172f9a6766.jpg)

**Comment by CarlosEsco** [comment]
The cloudflare issue nothing we can really do about it.  You have to wait till the site fixes itself or migrate to different source

**Comment by BlackIceFire** [comment]
> The cloudflare issue nothing we can really do about it. You have to wait till the site fixes itself or migrate to different source

Ahhh I see. Thank you very much for the explanation
