### ISSUE TITLE
[Bug] <Myreadingmanga>: <certain chapters will not load>

### ISSUE THREAD

**Issue by prestonpirateking** [inorichi/tachiyomi-extensions#3958]
---

### Device information
- Tachiyomi version: Stable o.9.2.
- Android version: 8.1.0

### Source information
- Name: Myreadingmanga
- Extension version: ?

## Steps to reproduce
1. Open myreadingmanga
2. View "edgy wedgie "

###Expected behaviour
Manga should have loaded

### Actual behavior
Manga does not load

**Comment by SnakeDoc83** [comment]
What exactly happens?

**Comment by SnakeDoc83** [comment]
Well, I'm going to assume it was a Cloudflare issue because it loads for me.
