### ISSUE TITLE
[Source Request] <ReadSololeveling>

### ISSUE THREAD

**Issue by Warcrors** [inorichi/tachiyomi-extensions#3959]
## Source Website
- Name: ReadSololeveling 
- Link: https://readsololeveling.org
- Language(s): English

### Other Details
- none

**Comment by AbdullahM0hamed** [comment]
What does this offer compared to just reading at an existing source?

**Comment by arkon** [comment]
These kind of single-entry sources have been turned down before. Use an aggregator or the actual source if available.

**Comment by scb261** [comment]
It's seems that they have several sites with similar layout and they publish chapters faster. When the issue was opened, I didn't found last chapters of solo leveling in my sources while they were on the requested source. They also have chapter 196 of Kaguya now, while guya.moe doesn't have it yet

**Comment by CarlosEsco** [comment]
Still no plans. You can find who's actual scanning and use their extension. Or wait a couple hours and it's everywhere.

**Comment by scb261** [comment]
Ok, if someone interested: they post SL on reddit via imgur, so either read it there, or wait for other sources as suggested above if you want to read it in Tachiyomi.

**Comment by Warcrors** [comment]
okay. Thank you for responses
