### ISSUE TITLE
[Feature Request] Madara: Custom sources like FoolSlide's

### ISSUE THREAD

**Issue by emrexemre** [inorichi/tachiyomi-extensions#3969]
### What feature should be added to this source?

Ability to add custom sources like FoolSlide's. But unlike FoolSlide, not one website please. Multiple websites would be more beneficial.

**Comment by SnakeDoc83** [comment]
No, that's silly and not practical.

**Comment by emrexemre** [comment]
I asked this because there are websites who removed themselves from Tachiyomi. So custom sources would be the only way to add them but okay.
