### ISSUE TITLE
Mangago source can't update

### ISSUE THREAD

**Issue by NoorHooda** [inorichi/tachiyomi-extensions#397]
Well I know it's really bothersome but we really love this source and these days it's facing many problems such : the mangas from mangago source can't be updated even though they are already updated on mangago website , plus some webtoons pages are a big mess and out of order :'( so I hope guys you help us to solve this problem , thanks in advance .

**Comment by CarlosEsco** [comment]
I just verified updates are fine.  as for page sorting there already is an issue open
