### ISSUE TITLE
[Bug] Source with different languages

### ISSUE THREAD

**Issue by psychopomp9** [inorichi/tachiyomi-extensions#3975]
### Device information
- Tachiyomi version: 0.10.1
- Android version: 9

### Source information
- Name: Genka, Madara, Webtoon
- Extension version: latest for all

### Expected behavior
Sources which have more than one language should only be active for selected language (as per previous version)

### Actual behavior
Active for all languages

### Other details
In last version of Tachiyomi, sources are shown only for the application language, but now it's showing every single language and it's enabled rather than disabled so I've to disable them one by one! It might because of the application version update

**Comment by SnakeDoc83** [comment]
You would need to bring this up on the main repo.
