### ISSUE TITLE
[Bug] <Bacakomik>: "Bacakomik" extension for Indonesian source problem

### ISSUE THREAD

**Issue by willyreza** [inorichi/tachiyomi-extensions#3978]
### Device information
- Tachiyomi version: 0.10.1
- Android version: Lollipop

### Source information
- Name: Bacakomik
- Extension version: 1.2.2
![Screenshot_2020-07-26-06-07-29-1](https://user-images.githubusercontent.com/3974476/89118817-57b7c400-d498-11ea-8e76-e9fa626cc072.png)
![Screenshot_2020-07-26-06-08-37-1](https://user-images.githubusercontent.com/3974476/89118830-7ddd6400-d498-11ea-8cfe-2508cd3bff0d.png)
![Screenshot_2020-07-26-06-08-48](https://user-images.githubusercontent.com/3974476/89118835-89308f80-d498-11ea-86d4-3d0e5ac0666a.png)

**Comment by SnakeDoc83** [comment]
You already opened an issue about this. 
https://github.com/inorichi/tachiyomi-extensions/issues/3895

**Comment by willyreza** [comment]
Ok😊
