### ISSUE TITLE
[Bug] Scantrad (FR) : Html tags in synopsis

### ISSUE THREAD

**Issue by o01210o** [inorichi/tachiyomi-extensions#3986]
### Source information
- Name: Scantrad
- Extension version: 1.2.5

![image](https://user-images.githubusercontent.com/45663409/89134389-cd507e00-d4f2-11ea-97e9-d05a1cbe4ffa.png)
On the website : https://scantrad.net/act-age

Act-age is only for illustration. It's apply on all mangas.

**Comment by SnakeDoc83** [comment]
Not seeing this when I open a manga, may have been a temporary issue. Try refreshing your metadata by enabling it in more > settings > library > automatically refresh metadata and then check again after your library has been updated.

**Comment by o01210o** [comment]
Oh my bad. Yes it disappears 🙇
