### ISSUE TITLE
[Bug] kumanga: Freeze app

### ISSUE THREAD

**Issue by pepe1987** [inorichi/tachiyomi-extensions#3989]
### Device information
- Tachiyomi version: 0.10.2
- Android version: 5.0.2

### Source information
- Name: kumanga
- Extension version: 1.2.2

## Steps to reproduce
1. Install kumanga(spanish extension)
2. Forze close app
3. Open app

### Expected behavior
See manga list

### Actual behavior
Freeze on logo at start

**Comment by jobobby04** [comment]
Its possible the issue is here, maybe it needs to be lazily instantiated
https://github.com/inorichi/tachiyomi-extensions/blob/master/src/es/kumanga/src/eu/kanade/tachiyomi/extension/es/kumanga/Kumanga.kt#L48
