### ISSUE TITLE
[Feature Request] Filter Option in Manga Extensions

### ISSUE THREAD

**Issue by cievee** [inorichi/tachiyomi-extensions#3993]
### What feature should be added to this source?
Filter option on genre,updated manga, old, latest and alphabetical order on the extension tab so that its easy to find the manga that i like. This feature is missing on the new update its located before on the lower right but i can't find it now. I'm using r2601

**Comment by arkon** [comment]
Tap the row rather than "Latest" specifically.

**Comment by cievee** [comment]
![Screenshot_20200803_224748](https://user-images.githubusercontent.com/64214774/89195617-94d89f00-d5db-11ea-8a60-c4d638fcdbbe.jpg)
There is like no filter option in other version there is one but in the latest update its gone and the search button is also gone or Am I too blind to find where is it 😅😅

**Comment by CarlosEsco** [comment]
stop clicking the latest button on the previous screen.  click the name of the source.  latest has never had a filter

**Comment by arkon** [comment]
> Tap the row rather than "Latest" specifically.

**Comment by cievee** [comment]
![received_294354891637896](https://user-images.githubusercontent.com/64214774/89197675-ad968400-d5de-11ea-950a-880fb7ee7814.jpeg)
Ive screenshot this on version of r2543 this feature is missing or is it relocated somewhere?

**Comment by arkon** [comment]
I'm not sure if you're even reading our responses. Tap here:

![Screenshot_20200803-111621](https://user-images.githubusercontent.com/4098258/89198224-e4d34980-d57a-11ea-8d54-2b3bff13c693.jpg)

**Comment by cievee** [comment]
Ohhhhh sorry english is sometimes too hard for me to understand thank you for the reply 😅
