### ISSUE TITLE
[Bug] <Japscan [FR]>: <Unable to read from this source>

### ISSUE THREAD

**Issue by ZealTOSEINA** [inorichi/tachiyomi-extensions#3995]
### Device information
**- Tachiyomi version:** Weekly Preview r2601
**- Android version:** Android 10 (crDroid 6.7 S9 Exynos)

### Source information
**- Name:** Japscan
**- Extension version:** 1.2.20

## Steps to reproduce
**1. First Step:** Select any manga from this source
**2. Second Step:** Click on any chapter and then an error occurs "Retry"

### Expected behavior
Reading from this source **should work**.

### Actual behavior
Reading from this source **doesn't work**.

### Other details
*My theory* on why we are unable to read from this source would be the number of **ads and trackers** on the site.

**Comment by arkon** [comment]
#2535
