### ISSUE TITLE
[Bug] manganelo: webname include d on chapter name

### ISSUE THREAD

**Issue by samanta-widjaja** [inorichi/tachiyomi-extensions#3999]
### Device information
- Tachiyomi version: 0.10.2
- Android version: 7.1.1

### Source information
- Name: mangabox
- Extension version: 1.2.24

 I downloaded chapter on manganelo and it show manganelo. Com_chaptername

Could anyone remove the duplicate webname on chapter name just like before? It's already separated by source folder anyway. 

Thanks for the help

**Comment by arkon** [comment]
This is intentional.

https://github.com/inorichi/tachiyomi/pull/3513
