### ISSUE TITLE
[Source Request] Woopread

### ISSUE THREAD

**Issue by sam7028** [inorichi/tachiyomi-extensions#4004]
**Source Website**
Name: Woopread
Link: https://woopread.com
Language(s): English

**Comment by as280093** [comment]
@SnakeDoc83  A novel Site Close this

**Comment by SnakeDoc83** [comment]
Mostly novels, but they do have some manhwa.

 https://woopread.com/?s=&post_type=wp-manga&genre%5B%5D=manhua&genre%5B%5D=manhwa

**Comment by sam7028** [comment]
It has both novel and manhwa

**Comment by sam7028** [comment]
plz add https://woopread.com/series/god-of-cooking-manhwa @SnakeDoc83
