### ISSUE TITLE
[Source Request] <18comic>

### ISSUE THREAD

**Issue by XeroxV** [inorichi/tachiyomi-extensions#4005]
Source Website
 Name: 18comic
 Link: https://18comic.vip/
 Language(s): Chinese / Japanese

Other Details
Alternate website : https://18comic.org/

This site has lots of doujins ( chinese/japanese ), manhwas from Toptoon.net, Toomics, Lezhin. It's a really good site for 18+ stuffs.

**Comment by SnakeDoc83** [comment]
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/3598
