### ISSUE TITLE
[Source Request] Multi comic *** source

### ISSUE THREAD

**Issue by Noname-noragami** [inorichi/tachiyomi-extensions#4010]
### Source Website
- Name: 8muses
- Link: https://8muses.io/category
- Language(s): en

- Name: ilikecomix
- Link: https://ilikecomix.com/
- Language(s): en

- Name: erofus
- Link: https://www.erofus.com/
- Language(s): en

**Comment by SnakeDoc83** [comment]
1. One source per request.
2. Search before you open a request, they've all been requested already (8muses.io seems to be a broken clone of 8muses.com).
