### ISSUE TITLE
[Feature Request] request for add a new feature

### ISSUE THREAD

**Issue by hecate0211** [inorichi/tachiyomi-extensions#4013]
I just want to suggest my idea for tachiyomi
1. Add new feature while reading manga can jump to other chapter
![Screenshot_20200804-133423_TachiyomiJ2K.jpg](https://user-images.githubusercontent.com/23187927/89326180-7bf3ea80-d6bc-11ea-8570-736a858ab0ff.jpg)

2. In list of chapter, please add maybe like blue text or something for our last read chapter

![Screenshot_2020-08-05-01-40-27-919_com.webtoon.mangazone.jpg](https://user-images.githubusercontent.com/23187927/89326316-a9d92f00-d6bc-11ea-9cec-a9d9e425013e.jpg)
Thanks

**Comment by SnakeDoc83** [comment]
This would need to be a request to the main repo.
I don't see the usefulness of your request or maybe I'm misunderstanding it, if you mark previously read chapters as read, then pressing the resume button takes you to the first unread chapter. If you mean something else, go to the main repo, search for any similar open requests, then open one if you don't find any.
