### ISSUE TITLE
[Source Request] <Komikgo.co.id>

### ISSUE THREAD

**Issue by willyreza** [inorichi/tachiyomi-extensions#4021]
### Source Website
- Name: Komikgo.co.id
- Link: http://www.komikgo.co.id
- Language(s): Indonesian

### Other Details

Komikgo.com and Komikgo.co.id is different😊

**Comment by SnakeDoc83** [comment]
It seems like a majority of their chapters have broken images and the chapters that were readable were mostly taken from sources we have extensions for. Unless they fix their site, I don't think this is worth adding.

**Comment by willyreza** [comment]
Ok😊
