### ISSUE TITLE
[Enhancement] Use gzip request while scraping - for all sources

### ISSUE THREAD

**Issue by Akianonymus** [inorichi/tachiyomi-extensions#4022]
This will greatly improve the speed when scraping. html scraping or api requests, gzip header shouldn't have a problem.

Reference: https://github.com/inorichi/tachiyomi/commit/40a959501234179da726f42805a869dae3cc0a0a

**Comment by SnakeDoc83** [comment]
Take it up at the main repo; it'd be easier to make a global change there than it would to update every extension.

**Comment by Akianonymus** [comment]
@SnakeDoc83 [Done](https://github.com/inorichi/tachiyomi/issues/3628)
