### ISSUE TITLE
[Bug] Mangafreak : Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by dondeepak** [inorichi/tachiyomi-extensions#4025]
### Device information
- Tachiyomi version: App version: 0.10.1-2601 (standard, 0d15cbe3, 47)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020 release-keys
Device brand: vivo
Device manufacturer: vivo
Device name: 1951
Device model: vivo 1951
Device product name: 1951

### Source information
- Name: Mangafreak
- Extension version: 1.2.2

Update library always give error Failed to bypass Cloudflare

Ao No Exorcist Action Fantasy Shounen Supernatural (Mangafreak (EN)): java.lang.Exception: Failed to bypass Cloudflare
Arifureta Shokugyou de Sekai Saikyou Action Adventure Fantasy Harem (Mangafreak (EN)): java.lang.Exception: Failed to bypass Cloudflare
Auto Hunting (Mangafreak (EN)): java.lang.Exception: Failed to bypass Cloudflare
Battle Through The Heavens Action Adventure Comedy Fantasy Martial Arts Romance (Mangafreak (EN)): java.lang.Exception: Failed to bypass Cloudflare

**Comment by kikuKeii** [comment]
Have you opened the web view before?
https://tachiyomi.org/help/guides/source-problems/#everyone-is-having-this-problem

**Comment by dondeepak** [comment]
> Have you opened the web view before?
> https://tachiyomi.org/help/guides/source-problems/#everyone-is-having-this-problem

Yes but still keep getting this error

**Comment by arkon** [comment]
See #3475 regarding Cloudflare.
