### ISSUE TITLE
[Bug] <Mangayu>: New update nothing

### ISSUE THREAD

**Issue by willyreza** [inorichi/tachiyomi-extensions#4034]
### Device information
- Tachiyomi version: 0.10.3
- Android version: 5.0

### Source information
- Name: Mangayu

Please fix it! :)

![Screenshot_2020-08-07-17-06-52-1](https://user-images.githubusercontent.com/3974476/89635457-8538af00-d896-11ea-9c86-493a4d1d0e2d.png)

**Comment by SnakeDoc83** [comment]
Tap "MangaYu" or somewhere in the containing area to browse.
