### ISSUE TITLE
[quality of Chap] <Manga SWAT>:

### ISSUE THREAD

**Issue by shipoxx** [inorichi/tachiyomi-extensions#4038]
![sketch-1596823855601](https://user-images.githubusercontent.com/61906880/89675564-0cf7db00-d8e2-11ea-9655-b8d3074dd2c1.png)

### Device information
- Tachiyomi version: 0.10.3
- Android version: 6.1

### Source information
- Name: wp mangastream (all source)
- Extension version: 1.2.20

### Other details

When I'm read some chapter especially from (manga swat) the quality of chapter is so low, but when I'm use website in Bros it's normal.. i talk with the website owner he said everything normal, so i guess problem from tachiyomi ?

• another problem I can't use menu inside chap like change (like in screenshot) it's short

**Comment by shipoxx** [comment]
![Screenshot_2020-08-07-18-39-43](https://user-images.githubusercontent.com/61906880/89673743-d10f4680-d8de-11ea-8d87-f83424b2a621.jpg)

**Comment by shipoxx** [comment]
![Screenshot_2020-08-07-19-03-49](https://user-images.githubusercontent.com/61906880/89674934-ef764180-d8e0-11ea-90e4-f08dd7fedba9.jpg)

From tachiyomi: low quality and menu is short

**Comment by shipoxx** [comment]
> ![Screenshot_2020-08-07-19-03-49](https://user-images.githubusercontent.com/61906880/89674934-ef764180-d8e0-11ea-90e4-f08dd7fedba9.jpg)
> 
> From tachiyomi: low quality and menu is short


From website from browser
![Screenshot_2020-08-07-19-04-52](https://user-images.githubusercontent.com/61906880/89674997-146ab480-d8e1-11ea-87e6-d39686bfb9e3.jpg)

**Comment by shipoxx** [comment]
![Screenshot_2020-08-07-19-08-51](https://user-images.githubusercontent.com/61906880/89675456-e0dc5a00-d8e1-11ea-8dfa-fa0b7f1ebf01.jpg)

**Comment by shipoxx** [comment]
@CarlosEsco 
Please chek (when i chose full page in new update this happened).

**Comment by SnakeDoc83** [comment]
Check your extension settings, WP Mangastream has a setting that changes image quality (poorly named "Default thumbnail quality"). I took a look at the website and code and I don't think there's anything there that would cause this other than that setting.
