### ISSUE TITLE
[Edited category] <why u removed button>

### ISSUE THREAD

**Issue by shipoxx** [inorichi/tachiyomi-extensions#4039]
### What feature should be added to this source?
Please return THE EDITED CATEGORY BUTTON, THANKS

![sketch-1596822994177](https://user-images.githubusercontent.com/61906880/89674254-c3a68c00-d8df-11ea-9688-bf574c0e427b.png)

**Comment by arkon** [comment]
To make space. As you pointed out, it's in the menu or you can long press "In library".

**Comment by shipoxx** [comment]
> To make space. As you pointed out, it's in the menu or you can long press "In library".

Fair enough,, thanks
