### ISSUE TITLE
[Bug] <mangalife>: <the site liading us slow>

### ISSUE THREAD

**Issue by sohilsayed** [inorichi/tachiyomi-extensions#4040]
### Source information
- Name: mangalife
- Extension version: the latest

## Steps to reproduce
1. Open the extension
2. Load the manga

### Expected behavior
All the mangas in the site loads

### Actual behavior
Nothing loads 

### Other details
After opening it with wrbview the mangas load but there data doesn't load

**Comment by SnakeDoc83** [comment]
Loads for me at a decent speed, clear your cookies and cache then try again. If it's still too slow, use a different source.
