### ISSUE TITLE
[Bug] <portugueses extensions install but dont show>: <all portugueses extensions install but dont show in navegation menu, only englishs.>

### ISSUE THREAD

**Issue by jigsaw9999** [inorichi/tachiyomi-extensions#4049]
### Device information
Xiaomi mi 9
- Tachiyomi version: 0.10.3
- Android version: 10

### Source information
- Name: mangá host
- Extension version: 1.2.11

## Steps to reproduce
1. First Step: Download extension
2. Second Step Go to navegation but portugueses extensions dont show, Just english extensions.

### Expected behavior
Extension show in navegation menu

### Actual behavior
Install all portugueses extesions but dont show in navegation menu

**Comment by SnakeDoc83** [comment]
On the sources screen tap the filter button on the top right and enable the correct language (Portugues or Portugues (Brasil)).
