### ISSUE TITLE
[Bug] ReadManhwa : NSFWs just vanished

### ISSUE THREAD

**Issue by leeyan69** [inorichi/tachiyomi-extensions#4050]
### Device information
- Tachiyomi version: App version: 0.10.3 (standard, 0c07e05a2, 49)
- Android version: 5.0.2 (SDK 21)

### Source information
- Name: ReadManhwa
- Extension version: 1.2.5

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Should show all Manhwas (including NSFWs)

### Actual behavior
Suddenly not showing just the NSFWs manhwas others are working well

### Other details
 unable to see any NSFW manhwa in the ReadManhwa extension. I went through all the troubleshooting steps reinstalled and all to no avail. Show NSFW is checked and when filtering by adult it shows no results found. Everything is working well om webview and NSFWs are also showing on it but not on tachiyomi itself.

**Comment by SnakeDoc83** [comment]
Closed by https://github.com/inorichi/tachiyomi-extensions/pull/4051
