### ISSUE TITLE
[Source Request] <Hitomi la>

### ISSUE THREAD

**Issue by boybeast** [inorichi/tachiyomi-extensions#4056]
#3945 # Source Website
- Name: Hitomi la
- Link: https://hitomi.la/
- Language(s): MULTI

the most complete site for hentai content, and there is no extension that has as many languages ​​as this site, languages ​​like Portuguese, Spanish, Korean and even Thai among many others.  The most complete and updated site, being more updated than Nhentai which is the best extension so far (but limited).

**Comment by arkon** [comment]
Duplicate of #94
