### ISSUE TITLE
[Bug] <manhuadui>: <Decryption failed>

### ISSUE THREAD

**Issue by HXLH50K** [inorichi/tachiyomi-extensions#4064]
### Device information
- Tachiyomi version: 0.10.2
- Android version: 10 (MIUI 12.0.1)

### Source information
- Name: manhuadui
- Extension version: 1.2.10

## Steps to reproduce
1. select any manga in "manhuadui", open to the introduction page
2. select any chapter

### Expected behavior
Open chapter and start reading

### Actual behavior
after loading completed, it return to the introduction page, and system show a message: "Tachiyomi: Decryption failed"

### Other details
after I tap any chapter, it will like this pic
![TIM图片20200809194254](https://user-images.githubusercontent.com/19921233/89731304-89242700-da78-11ea-9515-be76001b39bb.jpg)

**Comment by zzy94269664** [comment]
你好 ,原网站的加密密码更新了,我已向官方提交新的密码,马上发布的新版本就会解决,还望阁下耐心等待

**Comment by HXLH50K** [comment]
> 你好 ,原网站的加密密码更新了,我已向官方提交新的密码,马上发布的新版本就会解决,还望阁下耐心等待

感谢您的回答。
