### ISSUE TITLE
[Bug] <MangaBox>: <Page 3+ does not load>

### ISSUE THREAD

**Issue by J-Stutzmann** [inorichi/tachiyomi-extensions#4066]
# Device information
- Tachiyomi version: Stable 0.10.3
- Android version: 10

### Source information
- Name: MangaBox
- Extension version: 1.2.24

## Steps to reproduce
1. Open any manga in any subsource of MangaBox
2. Attempt to load third or later pages

### Expected behavior
Page loads as normal.

### Actual behavior
Page fails to load.

### Other details
No error message, just the retry button. Error seems to happen before even attempting to load an image, given how quickly it happens.

**Comment by SnakeDoc83** [comment]
Can't replicate, likely either a temporary issue or something on your end.
