### ISSUE TITLE
[Bug] FoolSlide > Kangaryu (FR) : HTTP error 404

### ISSUE THREAD

**Issue by o01210o** [inorichi/tachiyomi-extensions#4070]
### Source information
- Name: FoolSlide > Kangaryu
- Extension version: 1.2.51

The website has been updating, but always use FoolSlide.
HTTP error 404 in source and in chapter list.
Impossible to access to the catalog and updating manga list.

**Comment by SnakeDoc83** [comment]
It doesn't look like they're using FoolSlide any more.

**Comment by SnakeDoc83** [comment]
Removing them from FoolSlide; they'll have their own extension.  Once you install it you'll need to migrate your current favorited manga to the new extension.

**Comment by o01210o** [comment]
Oh, thank you !
