### ISSUE TITLE
[Bug] <skymanga >: <403 error>

### ISSUE THREAD

**Issue by fawadkhan121** [inorichi/tachiyomi-extensions#4076]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.4)
- I have updated all extensions
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/inorichi/tachiyomi
- I have searched the existing issues for duplicates
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions/
- I will fill out the title and the information in this template

## Device information
- Tachiyomi version: 0.10.4
- Android version: 10

## Source information
- Name: skymanga
- Extension version: madara

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened
Skymanga should load properly 
### Actual behavior
This happens instead
Giving 403 error but webview is working fine

**Comment by SnakeDoc83** [comment]
Site's dead right now, seems like maybe they got hacked. Open a new issue when they come back online (if they do and you still get a 403).

**Comment by fawadkhan121** [comment]
Ok thanks
