### ISSUE TITLE
[Bug] Dmzj: Chapter info API used in SChapter.url returned HTTP status 500

### ISSUE THREAD

**Issue by erinacio** [inorichi/tachiyomi-extensions#4086]
## Device information
- Tachiyomi version: 0.10.4
- Android version: 10

## Source information
- Name: Dmzj
- Extension version: 1.2.9

## Steps to reproduce
1. Try to read any chapter that was not downloaded and not in cache.
2. "HTTP error 500"

### Expected behavior
Show manga pages as usual.

### Actual behavior
"HTTP error 500"

## Other details

The actual chapter info data may now be embedded in manga view page, in a `<script>` block starting with `window.__INITIAL_STATE__=`. For example, try:

```bash
curl -sS -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 Tachiyomi/1.0' \
         -H 'Referer: http://www.dmzj.com/' \
         https://m.dmzj.com/views/40135/105759 \
    | grep -oE '<script>window\.__INITIAL_STATE__=[^<]+</script>' \
    | sed -e 's|</\?script>||g' -e 's/^window.__INITIAL_STATE__=//'
```

and you will get the json data required by `chapterListParse`.The old api `https://m.dmzj.com/chapinfo/${cid}/${chapter_id}.html` seems to be deprecated and broken now.

**Comment by saasddsaasdd** [comment]
same bug，pls help fix it

**Comment by erinacio** [comment]
Got a naive fix that works. I know little about Kotlin, and the fix may be sub-optimal, so I'm not going to submit a new PR. `git diff` here as a reference for anyone willing to submit a PR about it:

```patch
diff --git a/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt b/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
index 775ebd37..08748480 100644
--- a/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
+++ b/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
@@ -26,6 +26,8 @@ class Dmzj : HttpSource() {
     override val name = "动漫之家"
     override val baseUrl = "http://v3api.dmzj.com"
 
+    private val pattern = Regex("""<script>window\.__INITIAL_STATE__=(\{.*\})</script>""", RegexOption.DOT_MATCHES_ALL)
+
     private fun cleanUrl(url: String) = if (url.startsWith("//"))
         "http:$url"
     else url
@@ -161,7 +163,7 @@ class Dmzj : HttpSource() {
                     name = "$prefix: ${chapter.getString("chapter_title")}"
                     date_upload = chapter.getString("updatetime").toLong() * 1000 // milliseconds
                     // V3API url = "/chapter/$cid/${chapter.getString("chapter_id")}.json"
-                    url = "http://m.dmzj.com/chapinfo/$cid/${chapter.getString("chapter_id")}.html" // From m_readerBg.js
+                    url = "https://m.dmzj.com/views/$cid/${chapter.getString("chapter_id")}"
                 })
             }
         }
@@ -171,8 +173,11 @@ class Dmzj : HttpSource() {
     override fun pageListRequest(chapter: SChapter) = GET(chapter.url, headers) // Bypass base url
 
     override fun pageListParse(response: Response): List<Page> {
-        val obj = JSONObject(response.body()!!.string())
-        val arr = obj.getJSONArray("page_url")
+        val match = pattern.find(response.body()!!.string())
+        val obj = JSONObject(match!!.groups[1]!!.value)
+        val viewsImg = obj.getJSONObject("viewsImg")
+        val chapter = viewsImg.getJSONObject("chapter")
+        val arr = chapter.getJSONArray("page_url")
         val ret = ArrayList<Page>(arr.length())
         for (i in 0 until arr.length()) {
             ret.add(Page(i, "", arr.getString(i)))
```

**Comment by erinacio** [comment]
> Got a naive fix that works. I know little about Kotlin, and the fix may be sub-optimal, so I'm not going to submit a new PR. `git diff` here as a reference for anyone willing to submit a PR about it:
> 
> ```diff
> diff --git a/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt b/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
> index 775ebd37..08748480 100644
> --- a/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
> +++ b/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
> @@ -26,6 +26,8 @@ class Dmzj : HttpSource() {
>      override val name = "动漫之家"
>      override val baseUrl = "http://v3api.dmzj.com"
>  
> +    private val pattern = Regex("""<script>window\.__INITIAL_STATE__=(\{.*\})</script>""", RegexOption.DOT_MATCHES_ALL)
> +
>      private fun cleanUrl(url: String) = if (url.startsWith("//"))
>          "http:$url"
>      else url
> @@ -161,7 +163,7 @@ class Dmzj : HttpSource() {
>                      name = "$prefix: ${chapter.getString("chapter_title")}"
>                      date_upload = chapter.getString("updatetime").toLong() * 1000 // milliseconds
>                      // V3API url = "/chapter/$cid/${chapter.getString("chapter_id")}.json"
> -                    url = "http://m.dmzj.com/chapinfo/$cid/${chapter.getString("chapter_id")}.html" // From m_readerBg.js
> +                    url = "https://m.dmzj.com/views/$cid/${chapter.getString("chapter_id")}"
>                  })
>              }
>          }
> @@ -171,8 +173,11 @@ class Dmzj : HttpSource() {
>      override fun pageListRequest(chapter: SChapter) = GET(chapter.url, headers) // Bypass base url
>  
>      override fun pageListParse(response: Response): List<Page> {
> -        val obj = JSONObject(response.body()!!.string())
> -        val arr = obj.getJSONArray("page_url")
> +        val match = pattern.find(response.body()!!.string())
> +        val obj = JSONObject(match!!.groups[1]!!.value)
> +        val viewsImg = obj.getJSONObject("viewsImg")
> +        val chapter = viewsImg.getJSONObject("chapter")
> +        val arr = chapter.getJSONArray("page_url")
>          val ret = ArrayList<Page>(arr.length())
>          for (i in 0 until arr.length()) {
>              ret.add(Page(i, "", arr.getString(i)))
> ```

Aaand it's broken again. Now we should append ".html" to chapter url.

**Comment by rawfh** [comment]
@erinacio v3api works, just uncomment this line.
https://github.com/inorichi/tachiyomi-extensions/blob/56198e2661240a8b24eab209fe430d54ac5a82d2/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt#L163

**Comment by erinacio** [comment]
> @erinacio v3api works, just uncomment this line.
> https://github.com/inorichi/tachiyomi-extensions/blob/56198e2661240a8b24eab209fe430d54ac5a82d2/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt#L163

@rawfh I tried to compile your branch and installed the generated APK, then got "Expected URL scheme 'http' or 'https' but no colon was found". Am I missing something?

**Comment by rawfh** [comment]
> > @erinacio v3api works, just uncomment this line.
> > https://github.com/inorichi/tachiyomi-extensions/blob/56198e2661240a8b24eab209fe430d54ac5a82d2/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt#L163
> 
> @rawfh I tried to compile your branch and installed the generated APK, then got "Expected URL scheme 'http' or 'https' but no colon was found". Am I missing something?

You are right, but it really worked when I debugged it.
I also find that official dmzj apk has the same problem.

**Comment by erinacio** [comment]
> > > @erinacio v3api works, just uncomment this line.
> > > https://github.com/inorichi/tachiyomi-extensions/blob/56198e2661240a8b24eab209fe430d54ac5a82d2/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt#L163
> > 
> > 
> > @rawfh I tried to compile your branch and installed the generated APK, then got "Expected URL scheme 'http' or 'https' but no colon was found". Am I missing something?
> 
> You are right, but it really worked when I debugged it.
> I also find that official dmzj apk has the same problem.

@rawfh `pageListRequest` is overridden in line 171, which drops `baseUrl`, only uses `chapter.url` as request url. That seems to be the cause.

**Comment by rawfh** [comment]
@erinacio Sorry, I  apk version while testing, and the reason 

> > > @erinacio v3api works, just uncomment this line.
> > > https://github.com/inorichi/tachiyomi-extensions/blob/56198e2661240a8b24eab209fe430d54ac5a82d2/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt#L163
> > 
> > 
> > @rawfh I tried to compile your branch and installed the generated APK, then got "Expected URL scheme 'http' or 'https' but no colon was found". Am I missing something?
> 
> You are right, but it really worked when I debugged it.
> I also find that official dmzj apk has the same problem.



> > > > @erinacio v3api works, just uncomment this line.
> > > > https://github.com/inorichi/tachiyomi-extensions/blob/56198e2661240a8b24eab209fe430d54ac5a82d2/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt#L163
> > > 
> > > 
> > > @rawfh I tried to compile your branch and installed the generated APK, then got "Expected URL scheme 'http' or 'https' but no colon was found". Am I missing something?
> > 
> > 
> > You are right, but it really worked when I debugged it.
> > I also find that official dmzj apk has the same problem.
> 
> @rawfh `pageListRequest` is overridden in line 171, which drops `baseUrl`, only uses `chapter.url` as request url. That seems to be the cause.

Sorry, It looks like I mistook apk version while testing. I have fixed it in the pull request.

**Comment by erinacio** [comment]
> @erinacio Sorry, I apk version while testing, and the reason
> 
> > > > @erinacio v3api works, just uncomment this line.
> > > > https://github.com/inorichi/tachiyomi-extensions/blob/56198e2661240a8b24eab209fe430d54ac5a82d2/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt#L163
> > > 
> > > 
> > > @rawfh I tried to compile your branch and installed the generated APK, then got "Expected URL scheme 'http' or 'https' but no colon was found". Am I missing something?
> > 
> > 
> > You are right, but it really worked when I debugged it.
> > I also find that official dmzj apk has the same problem.
> 
> > > > > @erinacio v3api works, just uncomment this line.
> > > > > https://github.com/inorichi/tachiyomi-extensions/blob/56198e2661240a8b24eab209fe430d54ac5a82d2/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt#L163
> > > > 
> > > > 
> > > > @rawfh I tried to compile your branch and installed the generated APK, then got "Expected URL scheme 'http' or 'https' but no colon was found". Am I missing something?
> > > 
> > > 
> > > You are right, but it really worked when I debugged it.
> > > I also find that official dmzj apk has the same problem.
> > 
> > 
> > @rawfh `pageListRequest` is overridden in line 171, which drops `baseUrl`, only uses `chapter.url` as request url. That seems to be the cause.
> 
> Sorry, It looks like I mistook apk version while testing. I have fixed it in the pull request.

Tested the latest commit and it works without any issue. Thank you.

**Comment by SnakeDoc83** [comment]
Closed by https://github.com/inorichi/tachiyomi-extensions/pull/4115
