### ISSUE TITLE
Please fix Japscan for good

### ISSUE THREAD

**Issue by amar33** [inorichi/tachiyomi-extensions#4094]
## Device information
* Tachiyomi version: 0.10.4
* Android version: 9
* Device: Xiaomi Redmi Note 5

## Source information
* Source name: Japscan
* Source extension version: 1.2.20

## Issue/Request
Tokyo Revengers chapters 100+ don't work. Identic for Nanatsu no Taizai ans a lot of others manga. This is really annoying because this sources works 2 days per week and i'm tired. I love tachiyomi so much so please help us. Japscan is the biggest french source.

**Comment by SnakeDoc83** [comment]
There are already issues open about Japscan

https://github.com/inorichi/tachiyomi-extensions/issues/2535
https://github.com/inorichi/tachiyomi-extensions/issues/2219
