### ISSUE TITLE
[Site Request] http://www.dm5.com

### ISSUE THREAD

**Issue by GhotingGoad** [inorichi/tachiyomi-extensions#41]
As previously requested but a brand new issue.

(Probably) 2nd best website to read Chinese manhwa.

**Comment by as280093** [comment]
close this issue as [https://www.manhuaren.com/)](https://www.manhuaren.com/) & [http://www.dm5.com/download/](http://www.dm5.com/download/ )(extension name **Manhuaren** ) provide same application so they are or can be same
