### ISSUE TITLE
[Bug] Hitomi.la : Not All Manga are Visible/missing in search 

### ISSUE THREAD

**Issue by uuc110** [inorichi/tachiyomi-extensions#4106]
##Device information
- Tachiyomi version: 0.10.4
- Android version: 7.1.1

## Source information
- Name: Hitomi.la
- Extension version: 1.2.2

## Steps to reproduce
1. Search for your manga through Search or By Using Tag like Characters : ( character of series )
2. Simply search and find ( if u can find same result as web what u r searching for )

### Expected behavior
You may Expect to get the same Result as web or I Installed especially TachiyomiAZ for check Inbuid Hitomi.la Source it work fine

### Actual behavior
The MANGA's are not visibile / missing after searching for perticular Manga in Tachiyomi 0.10.4, Hitomi.la 1.2.2 
## Other details
After i search same manga in TachiyomiAZ its available in Build in feature of Hitomi.la but not in External source of Tachiyomi ( 0.10.4 )

**Comment by SnakeDoc83** [comment]
The extension filters by language. If you want a version that shows all results, enable the "other" language and use "Hitomi.la unfiltered."

**Comment by uuc110** [comment]
As u can see no result even after all language on and unfiltered in
Hitomi.la settings

**Comment by uuc110** [comment]
> The extension filters by language. If you want a version that shows all results, enable the "other" language and use "Hitomi.la unfiltered."

As u can see no result even after all language on and unfiltered in
Hitomi.la settings
![Screenshot_20200813-115504](https://user-images.githubusercontent.com/44457947/90101719-d9db9e80-dd5c-11ea-8d5f-851b08f8a5b2.png) for Privacy pourpose i remove What i was searching 😅

**Comment by SnakeDoc83** [comment]
I just tried searching for something and I get results. I don't know how you're getting that.
