### ISSUE TITLE
[Source Request] Manhwa18

### ISSUE THREAD

**Issue by D3xron** [inorichi/tachiyomi-extensions#4117]
## Source Website
- Name: Manhwa18
- Link: https://manhwa18.com/
- Language(s): English & Korean(RAW chapters)

**Comment by AbdullahM0hamed** [comment]
![emoji](https://user-images.githubusercontent.com/25087116/90201144-e77f3b80-ddd1-11ea-9608-d4471f964c71.png)

**Comment by D3xron** [comment]
Shit happend xD

**Comment by SnakeDoc83** [comment]
It's already in FMReader.

**Comment by D3xron** [comment]
Try, ty
