### ISSUE TITLE
[Source Request] <evamanhua.com>

### ISSUE THREAD

**Issue by mekodke** [inorichi/tachiyomi-extensions#4122]
Please add this source to madara extension

**Comment by FrigusBellator** [comment]
Hello, there is a very good website that does several transactions from manhuwas to Portuguese, which is really very good and very frequented by several people, it would be really cool if it had an extension for the app.
Link: https://neoxscans.com/

**Comment by SnakeDoc83** [comment]
@FrigusBellator 

1. It's already in Madara
2. Before requesting a source, you should have made sure it wasn't already available or requested
3. Don't make a different request on someone else's issue

**Comment by SnakeDoc83** [comment]
@mekodke The domain is forwarding to another site that's already in Madara.
