### ISSUE TITLE
[Source Request] <Source Name>

### ISSUE THREAD

**Issue by ZauberBlau** [inorichi/tachiyomi-extensions#4124]
---

## Source Website
- Name: Epik Manga
- Link: https://epikmanga.com/
- Language(s): Turkish

## Other Details
-

![](https://cdn.discordapp.com/attachments/349436576037732355/743893955791421512/Screenshot_20200814-192518_Tachiyomi.jpg)

![](https://cdn.discordapp.com/attachments/349436576037732355/743893956508516503/Screenshot_20200814-192525_Tachiyomi.jpg)

![video](https://user-images.githubusercontent.com/37742385/90281337-10a4d800-de75-11ea-96f6-a8a318bf5869.gif)

**Comment by AbdullahM0hamed** [comment]
This request is an illusion ~github-actions

**Comment by AbdullahM0hamed** [comment]
Also epikmanga already exists in the FMReader extension
