### ISSUE TITLE
[Source Request] <manhwamanga.net>

### ISSUE THREAD

**Issue by fawadkhan121** [inorichi/tachiyomi-extensions#4129]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.4)
- I have updated all extensions
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/inorichi/tachiyomi
- I have searched the existing issues for duplicates
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions/
- I will fill out the title and the information in this template

## Source Website
- Name: manhwamanga.net
- Link: https://manhwamanga.net/
- Language(s): english

## Other Details
?

**Comment by fawadkhan121** [comment]
There are many new manhwa on this site

**Comment by SnakeDoc83** [comment]
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/3136

**Comment by fawadkhan121** [comment]
But its Been three months

**Comment by SnakeDoc83** [comment]
Doesn't mean you should open another issue.

**Comment by fawadkhan121** [comment]
I didn't knew that another request was open sorry though

**Comment by KruxA1** [comment]
update on this source please. Thanks!
