### ISSUE TITLE
[Bug] <Dmzj>: <The quality of the images has been reduced>

### ISSUE THREAD

**Issue by pzy2222** [inorichi/tachiyomi-extensions#4132]
Some manga get a lower quality while being read or downloaded, which is the same on the dmzj app.
And these images should have been recompressed compared with those on the website in PC mode.
This would not happen on dmzj 1.2.9 and before.

---

## Device information
- Tachiyomi version: 10.4
- Android version: 10

## Source information
- Name: dmzj
- Extension version: 1.2.10

## Steps to reproduce
1. Download a chapter of manga, id: 51439 e.g.
2. Save the images on the website. You can get them on 
https://manhua.dmzj.com/biezhaganwoashangrenxiaojie.

### Expected behavior
Each image we download with tachiyomi has the same size and quality compared with the one on the web.

### Actual behavior
These images downloaded with tachiyomi get recompressed, then we have a bad copy of the original.

## Other details
Not all of the manga on dmzj get a lower equality.

**Comment by rawfh** [comment]
You are right. In v3api, dmzj uses [imgsmall.dmzj.com](imgsmall.dmzj.com) as its new image server.

**Comment by pzy2222** [comment]
> You are right. In v3api, dmzj uses [imgsmall.dmzj.com](imgsmall.dmzj.com) as its new image server.
Is there any way to access the images on PC website? Some manga have been hidden on the web, I can read them only on dmzj app or on tachiyomi, in several hours per day (8 p.m. to 6 a.m. in China) .

**Comment by pzy2222** [comment]
@SnakeDoc83 A large number of manga are hidden on the website due to government's bans, which makes reading them impossible on tachiyomi now. Maybe there is a method for us to load images from the PC website when they're accessible on the web, and to use v3api to read those being hidden on the web? (Sorry for my poor English.)
