### ISSUE TITLE
[Source Request] <Japanread>

### ISSUE THREAD

**Issue by ZealTOSEINA** [inorichi/tachiyomi-extensions#4135]
## Source Website
- Name: Japanread
- Link: https://www.japanread.cc/
- Language(s): French only

## Other Details
They also have their own application, but I think it would be nice to add this site as an extension because I prefer to read all my manga on Tachiyomi.
I totally understand if you don't find it necessary to add this extension, even if it would be a good addition for us, French reader!

**Comment by SnakeDoc83** [comment]
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/3106
