### ISSUE TITLE
[French] scantrad.fr

### ISSUE THREAD

**Issue by kou2s** [inorichi/tachiyomi-extensions#414]
scantrad.fr is a great French source !

**Comment by AmineI** [comment]
It's the same as #145 (Was called mangapedia, now switched to scantrad.fr, and mangapedia.fr now redirects to scantrad.fr. The old request may need to be renamed if this one is deleted though)

**Comment by Rediowz** [comment]
https://scantrad.fr/ 
Here's the link, i think it would be great to add this source because the main french one (japscan) is having some issues lately, and i think they're trying to block Tachiyomi too so another one would be really cool.
