### ISSUE TITLE
[Source Request] Genshin Impact

### ISSUE THREAD

**Issue by yuukiw** [inorichi/tachiyomi-extensions#4143]
## Source Website
- Name: Genshin Impact Manga
- Link: https://genshin.mihoyo.com/en/manga
- Language(s): English, GErman, French, Japanese (among others)

## Other Details
its maybe possible to use the Honkai Impact 3rd addons as a base

**Comment by AbdullahM0hamed** [comment]
Why not just read at existing sources?

**Comment by yuukiw** [comment]
cause those "manga" arent hostet anywhere else?

**Comment by AbdullahM0hamed** [comment]
X Doubt

All it has is one manga, and for English - it's available in the WebToons extension.

**Comment by yuukiw** [comment]
ah thx, i looked for it a while ago but google didnt show any other results.
Webtoon hasnt all language but english is good enough i guess.
