### ISSUE TITLE
[Source Request] lelscan-vf.com

### ISSUE THREAD

**Issue by Bamaraj09** [inorichi/tachiyomi-extensions#4146]
On tachiyomi Japscan is the only provider who having a lot of manga with all their chapters from A to Z. Unfortunately the provider doesn't work very well anymore so we can't read any more Manga in vf on tachiyomi and the other french provider are very poor in manga. 

"Lelscan" is the biggest competitor to Japscan of manga in French version (VF) so if someone could make it an extension it would be really cool.

**Comment by SnakeDoc83** [comment]
It's already in My Manga Reader CMS.
