### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by hulkman16** [inorichi/tachiyomi-extensions#416]
I have problems downloading extensions off the latest version of the app. It always says Parse Error and then returns back to the extension catalogue. I am not able to download any of the extensions as it shows the said error when I try to. Any help?

**Comment by CarlosEsco** [comment]
Make sure you don't have an adblocker enabled.  Also try on a different network wifi vs cellular

**Comment by CarlosEsco** [comment]
Download them directly then. https://github.com/inorichi/tachiyomi-extensions/tree/repo/apk

**Comment by hulkman16** [comment]
Oh, hey man! That worked! Thanks for helping me out, I'm not really well versed in these sort of things. Thank you!
