### ISSUE TITLE
[Bug] <risensteam>: <After updating the site, the extension stopped working>

### ISSUE THREAD

**Issue by szkill** [inorichi/tachiyomi-extensions#4167]
## Device information
- Tachiyomi version: ?
- Android version: ?

## Source information
- Name: risensteam
- Extension version: 1.2.1

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened

### Actual behavior
This happens instead

**Comment by SnakeDoc83** [comment]
Due to changes in their API old favorites won't be compatible and will need to be migrated to the new extension after you update.
