### ISSUE TITLE
Myreadingmanga error but loads next page

### ISSUE THREAD

**Issue by fatimagrace015** [inorichi/tachiyomi-extensions#417]
I tried downloading but it said this: unexpected url: data:image/gif;base then various numbers and letters. When I open a chap, first page error next page loads third page error. Alternate error and loading pages

Tachiyomi ver: 0.7.4
Myreadingmanga ver: 1.2.2.

**Comment by CarlosEsco** [comment]
Can you verify on their website that the chapter doesn't contain gifs?  Tachi doesn't support gifs currently

**Comment by fatimagrace015** [comment]
Its the same chap as above but on mrm website: https://myreadingmanga.info/nakamura-asumiko-blanc-eng/2/
No gifs or various # and letters

**Comment by fatimagrace015** [comment]
Nope. No gifs

**Comment by rj452** [comment]
Cover page also won't load... TT
![screenshot_20180730-201050](https://user-images.githubusercontent.com/20613912/43396649-c8961e66-9434-11e8-95e1-119d8231079a.jpg)
![screenshot_20180730-201047](https://user-images.githubusercontent.com/20613912/43396651-c8e736de-9434-11e8-95de-02982c6f8523.jpg)
![screenshot_20180730-200920](https://user-images.githubusercontent.com/20613912/43396655-cae213a0-9434-11e8-91d2-75ab645b36c4.jpg)

**Comment by fatimagrace015** [comment]
My friend said she uninstalled and installed mrm source then it worked as before. Ehm, wont be my downloaded mangas in mrm disappear if I do that?

**Comment by fatimagrace015** [comment]
As said one source per issue (though this one's closed already) but how
bout the covers? I uninstalled and installed mrm but still not loads the
cover though the pages are fine😁

**Comment by CarlosEsco** [comment]
Open a new issue. One issue per a source is for requests for new soruces only
