### ISSUE TITLE
[Bug] <MangaOwl>: <Search/Browse Function Broken>

### ISSUE THREAD

**Issue by dr-Jess** [inorichi/tachiyomi-extensions#4170]
## Device information
- Tachiyomi version: Stable 0.10.4
- Android version: 9

## Source information
- Name: MangaOwl
- Extension version: 1.2.6

## Steps to reproduce
Search for any manga using Tachiyomi's Browse/Search Function

### Expected behavior
Should display correct search results of manga from MangaOwl.

### Actual behavior
Actually displays a random assortment of manga from the frontpage of Mangaowl.net

## Other details
N/A

**Comment by HarumaRitsu** [comment]
It reall doesn't work even now.. Please fix 🤧
