### ISSUE TITLE
[Bug] <MangaHasu>: <Failed to bypass Cloudflare>

### ISSUE THREAD

**Issue by Lawthos** [inorichi/tachiyomi-extensions#4171]
## Device information
- Tachiyomi version: 0.10.4
- Android version: 10.0.0

## Source information
- Name: MangaHasu
- Extension version: 1.2.8

## Steps to reproduce
1. Open any manga chapter in MangaHasu extension.
2. Receive error 'java.lang.Exception: Failed to bypass Cloudflare'.

### Expected behavior
Manga chapter opens and loads all images normally.

### Actual behavior
Receive error mentioned above, chapter does not open or load images.

## Other details
Chrome and Android System WebView are up to date.
Sometimes the error can be randomly circumvented by repeatedly opening the chapter until it loads.

![Screenshot_20200820-070828_Tachiyomi](https://user-images.githubusercontent.com/69940319/90697563-05f9a100-e2c2-11ea-95d4-acc112534b9c.jpg)

**Comment by SnakeDoc83** [comment]
See #3475, you'll probably need to open a chapter in webview to bypass Cloudflare; then the extension should work normally (for a while).

**Comment by keyjeyelpi** [comment]
Try checking the DNS over HTTPS (Cloudflare) on settings > advanced. That fixed my bug.
