### ISSUE TITLE
[Source Request] LoveHeaven

### ISSUE THREAD

**Issue by dominhhieu1405** [inorichi/tachiyomi-extensions#4175]
---

## Source Website
- Name: Lh Scan (Love Heaven)
- Link: https://loveheaven.net
- Language(s): english

**Comment by namnguyen51** [comment]
It's Japanese site not English.
There's an extension for this site: RawLH

**Comment by dominhhieu1405** [comment]
> It's Japanese site not English.
> There's an extension for this site: RawLH

Can't search

**Comment by dominhhieu1405** [comment]
Không thấy bạn ơi

**Comment by scb261** [comment]
*RawLH* is source inside of *FMReader* extension, don't forget to turn on Japanese sources. Next time use [this sheet](https://docs.google.com/spreadsheets/d/e/2PACX-1vTaiDdEuWJvEaoZZd1zXuCS79P4qMkj-xYmMrA3-ZZm2GO_pdoGucSpZPOG5SOylE9fSE0f1JeprbEq/pubhtml) for multisource extensions.
