### ISSUE TITLE
ReadComicWebsite "No result found"

### ISSUE THREAD

**Issue by Generator** [inorichi/tachiyomi-extensions#418]
ReadComicWebsite still not working properly, when try to catalog only show "No result found"

**Versions:**
Tachiyomi - 0.7.4
ReadComicWebsite - 1.0.3

**Comment by 0klux** [comment]
It actually works, but only the "latest" section. But it renders the source unusable unless you're reading that are being updated on the site.

**Comment by 12waffles** [comment]
A new update on the extension appears to have fixed this issue.

**Comment by Generator** [comment]
> A new update on the extension appears to have fixed this issue.

Is the last release
**ReadComicWebsite - 1.0.3**

Tested on a different phone with same result  _"No result found"_

**Comment by 12waffles** [comment]
Oops sorry, I didn't realize they were different. I had the same problem with the other extension before so I thought it was the same.

**Comment by arkon** [comment]
For some reason this website is part of the [My Manga Reader CMS](https://github.com/inorichi/tachiyomi-extensions/blob/dbf7ebd65d22b1571e51922e31200e310f5b141e/src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/Generator.kt#L203) generator as well as [its own extension](https://github.com/inorichi/tachiyomi-extensions/blob/253c7afb6b8edb4e642541da0c895cca2aa2a988/src/en/readcomictv/src/eu/kanade/tachiyomi/extension/en/readcomictv/Readcomictv.kt).

Do you know which one you're using?

**Comment by Generator** [comment]
@arkon that's correct, using My Manga Reader CMS solves the issue. ReadComicWebsite is a duplicated extension.

**Comment by CarlosEsco** [comment]
do as arkon/generator said.  I have deleted this old one.
