### ISSUE TITLE
[Source Request] ShoujoHearts

### ISSUE THREAD

**Issue by negativewoman** [inorichi/tachiyomi-extensions#4181]
## Source Website
- Name: ShoujoHearts
- Link: http://shoujohearts.com/
- Language(s): English

## Other Details
The reader is Madara-based.

Link to the reader: http://shoujohearts.com/reader/

**Comment by SnakeDoc83** [comment]
Closed by https://github.com/inorichi/tachiyomi-extensions/pull/4206
