### ISSUE TITLE
[Bug] <zh.manhuadui>: <AES encryption key update, please modify the key and iv of the source code>

### ISSUE THREAD

**Issue by ZongerZY** [inorichi/tachiyomi-extensions#4193]
private const val DECRYPTION_KEY = "KA58ZAQ321oobbG1"
private const val DECRYPTION_IV = "A1B2C3DEF1G321oo"

**Comment by AbdullahM0hamed** [comment]
It looks to me like you should open a PR

**Comment by Haleydu** [comment]
DECRYPTION_KEY  = KA58ZAQ321oobbG8
DECRYPTION_IV  = A1B2C3DEF1G321o8


Updates are too frequent

**Comment by SnakeDoc83** [comment]
Ideally we would determine the key and IV programmatically.
