### ISSUE TITLE
[Bug] Mangakyo: Couldn't Open The Extension

### ISSUE THREAD

**Issue by ReyVnD** [inorichi/tachiyomi-extensions#4195]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.4)
- I have updated all extensions
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/inorichi/tachiyomi
- I have searched the existing issues for duplicates
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions/
- I will fill out the title and the information in this template

---

## Device information
- Tachiyomi version: 0.10.4
- Android version: 10

## Source information
- Name: Mangakyo
- Extension version: 1.2.2

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened

### Actual behavior
This happens instead

**Comment by Riztard** [comment]
it seems now they use MANGASTREAM

**Comment by SnakeDoc83** [comment]
Uninstall the extension and use WP Mangastream for a working version of Mangakyo.
