### ISSUE TITLE
[Site Request] http://www.dmzj.com

### ISSUE THREAD

**Issue by rouji4256** [inorichi/tachiyomi-extensions#42]
As previously requested but on a single thread.

(Probably) best source to read Chinese manhwa

**Comment by ThePreviousOne** [comment]
I am willing to do this but as I don't speak any form of Chinese I will need help, or have translation questions

**Comment by ThePreviousOne** [comment]
I am willing to do dm5 as well fyi

**Comment by JokerQyou** [comment]
@ThePreviousOne So what are these translation questions necessary for you to start? I'm very much interested in this Chinese source support. Since I don't write Kotlin, I might help you with these translation things.

**Comment by CarlosEsco** [comment]
#218
