### ISSUE TITLE
[Feature Request] Filter out what's already been added to library for all sources when searching

### ISSUE THREAD

**Issue by vongdong** [inorichi/tachiyomi-extensions#4202]
Is it possible to add a filter to all sources that filters out titles that have already been added to your library when searching? It makes life that bit easier when looking for new titles in a sea of already added titles. I think I've seen it in an extension before.

**Comment by scb261** [comment]
The feature should be added to the app, not separate sources. And there is already opened issue about this https://github.com/inorichi/tachiyomi/issues/2941

**Comment by vongdong** [comment]
Ah okay. Just thought it would be for extension since all extensions have different search options/filters. April sure was a while ago.

**Comment by SnakeDoc83** [comment]
At the extension level an extension can't tell what's already in your library.

**Comment by vongdong** [comment]
Okay. Before I decide to open another issue in the future here, can you please tell me exactly what ype of things I can request?

**Comment by scb261** [comment]
Here you can request sources / bug fixes for sources / features for existing sources, everything that related to separate sources/extensions. Everything else in https://github.com/inorichi/tachiyomi. As for what features exactly can be added, it's hard to tell, just open it and it will be closed if it won't be implemented. Just search existing issues before this to not create duplicates.

**Comment by joseph619** [comment]
On this repo, you can

1) Request new source/extension
2) Report source bug  
3) Ask source to be removed 

Everything else goes to main repo
