### ISSUE TITLE
[Bug] MangaDex: error HTTP 500

### ISSUE THREAD

**Issue by ChrisN6** [inorichi/tachiyomi-extensions#4203]
## Device information
- Tachiyomi version: 1.0.8
- Android version: 11

## Source information
- Name: MangaDex
- Extension version: 1.2.95

## Steps to reproduce
1. Update library
2. Finish update and get error.
3. Open log
4. HTTP error 500 from some mangadex titles

### Expected behavior
Update normally

### Actual behavior
Error while trying to update. Open the Log and it shows Http 500

## Other details
This is not the only source where it happens

**Comment by SnakeDoc83** [comment]
They're having server issues, will hopefully be resolved with their upgrade.
