### ISSUE TITLE
Tencent Comics (腾讯动漫)

### ISSUE THREAD

**Issue by XeroxV** [inorichi/tachiyomi-extensions#4204]
Source Website
- Name: Tencent Comics (腾讯动漫)
- Link: https://ac.qq.com/
- Language(s): Chinese

Other Details
It's an official site for manhua and manga. Some require coins to read them but there are also free to read manhua as well

**Comment by SnakeDoc83** [comment]
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/412
