### ISSUE TITLE
[Source Request] Saytruyen

### ISSUE THREAD

**Issue by binpro0248** [inorichi/tachiyomi-extensions#4207]
## Source Website
- Name: Saytruyen
- Link: https://saytruyen.com
- Language(s): Vietnamese

## Other Details
This is a good site to read manhwa with Vietnamese subtitles

**Comment by kiriya-aoi** [comment]
Saytruyen is already in the FMReader extension.

**Comment by binpro0248** [comment]
> Saytruyen is already in the FMReader extension.

Ok, thank you
