### ISSUE TITLE
[Bug] <Mangalib>: <Latest chapters error>

### ISSUE THREAD

**Issue by EnckyOff** [inorichi/tachiyomi-extensions#4210]
## Device information
- Tachiyomi version: 0.10.4
- Android version: 10

## Source information
- Name: Mangalib
- Extension version: 1.12.19

## Steps to reproduce
1. Select "Latest" in browse
2. Get an error message " attempt to invoke virtual method java lang string"

### Expected behavior
Open latest chapter at mangalib

### Actual behavior
A virtual method error

**Comment by Watashis** [comment]
<details>
<summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/22397077/91662484-c3bb3580-eaf3-11ea-9fa2-5bb213685dd4.jpg" alt="Screenshot"/>
</details>

[Link ](https://mangalib.me/wo-de-bingdu-nuyou)  to the problematic title

**Comment by SnakeDoc83** [comment]
Closed by https://github.com/inorichi/tachiyomi-extensions/pull/4259

**Comment by Pavkazzz** [comment]
@EnckyOff You should login to site throw webview, cause mangalib always response 401 for unauth user for now
