### ISSUE TITLE
[Bug] <mangareader (EN)>: <chapters not loading>

### ISSUE THREAD

**Issue by foRRRv** [inorichi/tachiyomi-extensions#4213]
## Device information
- Tachiyomi version: 0.10.4
- Android version: 9

## Source information
- Name: mangareader (EN)
- Extension version: 1.2.6

## Steps to reproduce
1. Trying to open the unread chapters 
2. Waiting for it to load

### Expected behavior
Unread chapters should be loading

### Actual behavior
Unread chapters cannot be loaded even after using the "retry"-button. There is no error mesaage.

## Other details
Even reinstalling the extension or the app itself unread chapters cannot be loaded.

**Comment by SnakeDoc83** [comment]
It appears to be an issue with the source.
