### ISSUE TITLE
[Bug] JapScan  : Doesn't work

### ISSUE THREAD

**Issue by JeezLF** [inorichi/tachiyomi-extensions#4215]
## Device information
- Tachiyomi version: 0.10.4

## Source information
- Name: JapScan
- Extension version: 1.2.20

## Steps to reproduce
1. Search a manga (Shingeki per exemple)
2. Try to read a chapter
        -> Nothing appear, only a retry button
3. Try to download the chapter
        -> Download doesn't start and stay block to 0%

**Comment by CarlosEsco** [comment]
#2535
