### ISSUE TITLE
[Bug] MangaDex: Downloaded chapters not showing as downloaded

### ISSUE THREAD

**Issue by Mymiano** [inorichi/tachiyomi-extensions#4216]
## Device information
- Tachiyomi version: 0.10.4-2671
- Android version: 10 (SDK 29) 

## Source information
- Name: MangaDex
- Extension version: 1.2.95

## Steps to reproduce
1. Download chapters of `Battle in 5 seconds after meeting` (chap 66-67). It will show downloaded
2. Close app (kill)

### Expected behavior
Download count/status should still be there even if the app was closed

### Actual behavior
It will not indicated as downloaded but can read it as downloaded manga

## Other details
The reason I put it in extension:
* The name of dir of chapters are different from other like it contains also the scanlator's name
* It only happen in this extension

**Comment by scb261** [comment]
I suppose they renamed chapter, in most cases it's *Vol.8* part. Go to file manager and compare names

**Comment by Mymiano** [comment]
I remove manga in library and clear database. I added it again and downloaded and it's working now. I will close this now
