### ISSUE TITLE
[Source Request] readmanhwa

### ISSUE THREAD

**Issue by vipzzx** [inorichi/tachiyomi-extensions#4218]
## Source Website
- Name: ReadManhwa
- Link: readmanhwa.com
- Language(s): English

## Other Details
Want to have this to replace getmanhwa.co that just died

**Comment by SnakeDoc83** [comment]
Well, if you want it, install it, because it already exists.

**Comment by vipzzx** [comment]
> Well, if you want it, install it, because it already exists.

Thanks sorry about that. Is it possible to add the extensions that are one source only onto the google spreadsheet so it makes it easier to find?

**Comment by SnakeDoc83** [comment]
Sorry, I won't be doing that. I know it's a bit inconvenient to search for a source in 2 places, but adding them would go beyond the original purpose of the sheet.

**Comment by joseph619** [comment]
You search for Extension name first, then  use spreadsheet. Don't request sources without doing both first.

**Comment by AbdullahM0hamed** [comment]
You can also search here on github

**Comment by vipzzx** [comment]
Thanks again. Just going to say sorry in advance just in case I do something like this again in the future
