### ISSUE TITLE
[Meta]  Mangaku & Komiktap

### ISSUE THREAD

**Issue by kikuKeii** [inorichi/tachiyomi-extensions#4221]
simple issue...
##  mangaku (id)
- update the domain https://mangaku.in/ to https://mangaku.pro/

##  komiktap (wpmangastream)
- Please fix the nextpageselector
- and fix popular manga
- add filter 

## Other Details
thank you :)

**Comment by adyyyyyyy** [comment]
Thankss..

**Comment by SnakeDoc83** [comment]
Mangaku has other problems besides needing a domain name update. There's an open issue on it you can comment on. https://github.com/inorichi/tachiyomi-extensions/issues/2530
