### ISSUE TITLE
[Bug] MangaDex: HTTP ERROR 600

### ISSUE THREAD

**Issue by marcos123123** [inorichi/tachiyomi-extensions#4231]
## Device information
- Tachiyomi version: 0.10.4
- Android version: 5.1.1

## Source information
- Name: Mangadex
- Extension version: 1.2.95

## Steps to reproduce
1. Search mangas via ID:##### or open mangas hosted on MangaDex

### Expected behavior
Search via ID should show the manga with said ID number, opening a manga chapter should be readable

### Actual behavior
ID search doesn't show anything, manga chapters are unreadable due to HTTP Error 600

## Other details
The extension worked fine a few months ago, this might be a problem with Mangadex servers itself but I can't find anything regarding HTTP Error 600. Any answer will be appreciated

**Comment by CarlosEsco** [comment]
Their site was done and is still rebooting. Nothing we can do but wait
