### ISSUE TITLE
[Deletion Request] Delete KnightNoScanlation, AhStudios

### ISSUE THREAD

**Issue by knightnoscanlation** [inorichi/tachiyomi-extensions#4240]
### Source Websites

> Name: KnightNoScanlation, AhStudios
> Link: http://knightnoscanlation.com, https://ahstudios.net
> Language(s): Spanish

### Other Details
I wish to delete my websites from here. It was added here without my permission and I want you to delete my websites from here. Thanks.

**Comment by arkon** [comment]
Please provide proof of ownerships to a mod on Discord (https://discord.gg/tachiyomi).

**Comment by Soitora** [comment]
Proof of Ownership confirmed through DMs.

**Comment by SnakeDoc83** [comment]
Closed by https://github.com/inorichi/tachiyomi-extensions/pull/4214
