### ISSUE TITLE
[Deletion Request] Delete Plot Twist No Fansub

### ISSUE THREAD

**Issue by gansu18** [inorichi/tachiyomi-extensions#4242]
Source Websites
Name: Plot Twist no Fansub
Link: https://www.plot-twistnf-scans.com/
Language(s): Spanish

Other Details
I wish to delete my website from here. It was added here without my permission and I want you to delete my website from here. Thanks.

**Comment by SnakeDoc83** [comment]
Contact a mod on discord (https://discord.gg/tachiyomi) with proof of ownership.

**Comment by CarlosEsco** [comment]
proof has been provided
