### ISSUE TITLE
[Source Request] manwhas.men

### ISSUE THREAD

**Issue by devilo-dot** [inorichi/tachiyomi-extensions#4246]
well cuz secret class and other good 18+ manhwa is more fast for new chp so i hope tachi can add this site to madara extension make a new extension 
## Source Website
- Name: manhwa.men
- Link: https://manhwas.men/
- Language(s): english ,raw,spanish

**Comment by gospodinh** [comment]
When its gonna release

**Comment by scb261** [comment]
@gospodinh when someone will want to work on it. It's open source project, anyone can contribute

**Comment by whyimdoingthis** [comment]
As @scb261 recommended I added ManhwasMen support and created the pull request.
I hope maintainers could assist with releasing the extension update.

**Comment by fawadkhan121** [comment]
Is manhwa.men added on tachi if so than in which extension??

**Comment by CrepeTF** [comment]
@fawadkhan121 
Refer to the spreadsheet:
https://tachiyomi.org/extensions-spreadsheet
