### ISSUE TITLE
[Source Request] MangaZone.cc

### ISSUE THREAD

**Issue by Mekelia** [inorichi/tachiyomi-extensions#4247]
## Source Website
- Name: MangaZone
- Link: https://mangazone.cc
- Language(s): English

**Comment by SnakeDoc83** [comment]
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/2622

**Comment by ANETAIII** [comment]
I asked this site too
It's not added? We can't have hope for it? This site is very useful!

**Comment by Mekelia** [comment]
They said there was an error with it but that was months ago so I don't know if they figured it out
