### ISSUE TITLE
[Bug] <MangaDex>: <can't load more manga>

### ISSUE THREAD

**Issue by s03ki** [inorichi/tachiyomi-extensions#4254]
![Screenshot_20200830_081207_eu kanade tachiyomi](https://user-images.githubusercontent.com/70456820/91648990-c9376200-ea98-11ea-95d3-cd07a139ca1c.jpg)

## Device information
- Tachiyomi version: Stable 0.10.4
- Android version: 10

## Source information
- Name: MangaDex
- Extension version: All 1.2.95

## Steps to reproduce
1. Open MangaDex
2. Scroll through

### Expected behavior
More mangas loaded

### Actual behavior
Only some mangas listed

## Other details
Already did re-install MangaDex extension, sometimes it loads more mangas, other times no. Tried opening MangaFreak, it keeps loading, even mangas for 4 days ago.

**Comment by CarlosEsco** [comment]
There is a limit on what the provide in the latest button. Click the name of the source and not the latest button.
