### ISSUE TITLE
Missing manhwa on Woopread 

### ISSUE THREAD

**Issue by sam7028** [inorichi/tachiyomi-extensions#4264]
Extension-Madara
Source-Woopread
plz add https://woopread.com/series/god-of-cooking-manhwa 

_Originally posted by @sam7028 in https://github.com/inorichi/tachiyomi-extensions/issues/4004#issuecomment-683278327_

**Comment by SnakeDoc83** [comment]
I'd set it to request manhwa and manhua from their site so that novels wouldn't show up when people browse it; I don't know why that one doesn't show. To fix it I'll have to change the request; so their novels are going to show up when you browse. Lame, wish their site was a bit better.
