### ISSUE TITLE
[Bug] hentai2read: Missing title names

### ISSUE THREAD

**Issue by vongdong** [inorichi/tachiyomi-extensions#4265]
So when browsing I saw a quite a few titles didn't have any names for them and when opening them, their titles are just called 'unknown'. Not sure if it's an isolated issue or not since my other device shows the names for them.

**Comment by SnakeDoc83** [comment]
It's just your device, you probably browsed h2r before at a point when titles were broken. You can probably fix it by using "clear database" in the advanced settings menu.

**Comment by vongdong** [comment]
That fixed about half of them.

**Comment by vongdong** [comment]
Got them fixed. Had to remove from library and clear the database.
