### ISSUE TITLE
[Bug] <TimelessLeaf>: New Chapters Not Showing On "Library Updates" Tab

### ISSUE THREAD

**Issue by sam7028** [inorichi/tachiyomi-extensions#4268]
### Device information

- Tachiyomi version: 0.10.4

- Android version: 10

### Source information

- Extension: TimelessLeaf

- Extension version: 1.2.2

### Steps to reproduce

1. Add Title To Library

2. When New chapters are available, updates doesn't show in the Updates Tab 
### Other details
I can see the new chapters going manually in the Library
Also,Chapters don't have dates

**Comment by SnakeDoc83** [comment]
On the website chapters don't have an upload date; so there's no date for the extension to set. Chapters without dates don't show up in the updates tab. I'm not in to arbitrarily setting chapter dates as a "fix"; so you're kind of stuck with this. 

If it really bothers you check the main app's repo and see if there's an open issue about the updates tab (this has happened with other extensions); if there isn't one yet open an issue and maybe something will be done about it at that level.
