### ISSUE TITLE
[Bug] MangaOwl: Duplicate pages, pages not loading

### ISSUE THREAD

**Issue by alanali** [inorichi/tachiyomi-extensions#4270]
#3981  Device information
- Tachiyomi version: Stable 0.10.4
- Android version: Android 10

## Source information
- Name: MangaOwl
- Extension version: English 1.2.7

## Steps to reproduce
1. Browse MangaOwl
2. Click any manga, there will be over 100 pages of repeating content and pages that don't load

### Expected behavior
Pages shouldn't be repeating

### Actual behavior
Each page is repeated around 5 times, causing the total number of pages per chapter to jump into the hundreds

## Other details
Extension was working fine yesterday

**Comment by SnakeDoc83** [comment]
You'll need to post an example, the chapters I've checked look fine to me.

**Comment by alanali** [comment]
Issue is resolved! Not sure what changed but it works fine now
