### ISSUE TITLE
[Bug] BoomManga, ManManga, TwinComics: Connect timed out

### ISSUE THREAD

**Issue by alan-ford** [inorichi/tachiyomi-extensions#4272]
## Device information
- Tachiyomi version: 0.10.4
- Android version: 7.1.2

## Source information
- Name: BoomManga, ManManga, TwinComics
- Extension version: 1.2.3

## Steps to reproduce
1. Browse all mangas

### Expected behavior
Get list of all mangas

### Actual behavior
Connect timed out

## Other details
N/A

**Comment by SnakeDoc83** [comment]
The websites are unreachable; in fact, they may be dead. Either way, not something that's fixable on our end.
