### ISSUE TITLE
[Meta] Remove Japscan extension

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi-extensions#4277]
##  Why/Project's Benefit/Existing Problem
Broken extension, hard to maintain. Also alternative Elimanga is coming

**Comment by ran17nee** [comment]
Excuse me, it works just fine for me. Also, some of the manga I'm reading exist "only" there (since they're JapScan exclusive), I don't see how Elimanga can replace it.

**Comment by AbdullahM0hamed** [comment]
Elimanga scrapes japscan (and now we scrape them😎) - so there shouldn't be a problem of exclusivity, but maintaining the japscan extension is more trouble than it's worth.

**Comment by ran17nee** [comment]
I get it now, thank you for explaining. Also, thank you for your hard work!

**Comment by king07-0** [comment]
Unfortunately, Mandra announce on discord that Elimanga will not be fix anymore (14/09), and japscan just change there domain from .co to .se. So the japscan source cannot be used in Tachiyomi for now.

**Comment by CarlosEsco** [comment]
Japscan support has been dropped go learn english, find a new french source, or read on their website
