### ISSUE TITLE
[Bug] LANraragi: Broken

### ISSUE THREAD

**Issue by AbyssalMonkey** [inorichi/tachiyomi-extensions#4278]
## Device information
- Tachiyomi version: 0.10.4
- Android version: 8.0.0

## Source information
- Name: LANraragi
- Extension version: 1.2.1

## Steps to reproduce
1. Point at server hostname. Give API key.
2. Open source.

### Expected behavior
I see my library.

### Actual behavior
![Screenshot_20200831-165244](https://user-images.githubusercontent.com/29171166/91767842-caf14a80-ebaa-11ea-9a79-8f5506893f71.png)

**Comment by Difegue** [comment]
For information:  
Some of the API endpoints used in this extension have been removed as of v.0.7.1 of LANraragi.  
See https://github.com/Difegue/LANraragi/releases/tag/v.0.7.1.  

![image](https://user-images.githubusercontent.com/8237712/94349060-67d7c400-0041-11eb-9aa1-db765fc16e69.png)

I don't write much kotlin so I can't fix this myself, but from a quick glance here's what you'd have to do:  

- Change the authentication from a `key` query parameter to an Authentication Header
- Change the API endpoints: This uses `extract`, `search`, and `thumbnail` from what I can see.  
This isn't necessary right now as 0.7.1 and its hotfix have shims for those endpoints, but I plan on removing this in a later release.
