### ISSUE TITLE
Union manga is not loading any manga

### ISSUE THREAD

**Issue by gabrielmartt** [inorichi/tachiyomi-extensions#428]
When I read some manga it's on the "retry" screen but when I press it, nothing happens

I do not think it's a problem on the site because it's working fine.
I've tested the source in other apps and it's working fine too

**Comment by CarlosEsco** [comment]
#424

**Comment by gabrielmartt** [comment]
I already checked and it did not help

**Comment by CarlosEsco** [comment]
Are you saying you are able to go to the union manga website?  Cause from that post i linked it's down. So that means tachiyomi can't access either

**Comment by gabrielmartt** [comment]
Yes, I able

**Comment by CarlosEsco** [comment]
I'll leave other issue open then
