### ISSUE TITLE
Union mangás (the only pt source) not working. 

### ISSUE THREAD

**Issue by gyoneres** [inorichi/tachiyomi-extensions#429]
Union mangá is not working again, but this time is only the pages/images that doesn't load (screenshot, all pages are like that). The manga catalogue and the manga chapter list works fine. 
![whatsapp image 2018-08-03 at 2 39 14 pm](https://user-images.githubusercontent.com/42074012/43657096-214768fa-972b-11e8-9a1e-510f9b50b8eb.jpeg)
 
Other sources works fine here. 
Tachiyomi ver 0.7.4 
Union mangás source ver 1.2.2

**Comment by masgritz** [comment]
I've been trying to fix this for the past couple of days, seems like the either changed something on how the images are stored in their website or introduced something in their server to prevent images from being downloaded.

I don't think I can fix this on my own as I'm not really well-versed Kotlin and writing an extension. If some better Dev can help, I would appreciate it.

**Comment by masgritz** [comment]
To add, the issue is likely on these lines:
UnionMangas.kt
`override fun pageListParse(document: Document): List<Page> {
        val pages = document.select("img.img-responsive.img-manga")

        return pages
                .filter { it.attr("src").contains("leitor") }
                .mapIndexed { i, element -> Page(i, "", "http://" + element.attr("src")) }
    }`
As far as I can tell, the extension is able to parse the pages list and return the exact same number of pages in the website, so either `.filter` or `.mapIndexed` are the ones to blame. 

I'm not sure if they changed the `class` section to something that could prevent the images from being download, I can't remember if it was like this before.
`<img src="http://unionmangas.site/leitor/mangas/One Piece/906/01.png" class="img-responsive img-manga pag_3 active" pag="3" alt="Ler mangá One Piece - Capítulo 906 online" style="display: inline; opacity: 1;">`

Does anyone has any suggestions on how should I tackle this?

**Comment by gyoneres** [comment]
Please, guys. Don't let this source die. tot

**Comment by TemptingBadger** [comment]
Today Union Mangás source no working yet. Please, fix this.

**Comment by gabrielmartt** [comment]
I hope they fix this, in other apps the source works normally but I prefer to read in tachiyomi

**Comment by Lexdl** [comment]
They launched a new reworked app in play store a few days ago. Maybe something changed because of this?

**Comment by arkon** [comment]
It probably has something to do with the prepending of `http://`, but the website is so slow that I can't even check.

**Comment by masgritz** [comment]
Thanks, @arkon. That might be it. Seems they're having yet another server maintenance today. Pages aren't even loading on the website. I updated the code on my end, going to try it tomorrow morning if it stabilizes.

**Comment by masgritz** [comment]
So turns out the issue was the website all along. I tried to access various series today through the untouched extension and they all worked, except for the 3 latest chapters (those also aren't available in the website as of now). No changes to the extension are required.

**Comment by gabrielmartt** [comment]
There is a possibility of putting another brazilian source? for use when the union has these problems

**Comment by arkon** [comment]
MangaDex has PT stuff too.

**Comment by CarlosEsco** [comment]
That's also up to a developer who can and want to make an extension and speaks Portuguese.  It's open source app so anyone can make an extension and open a pull request

**Comment by gyoneres** [comment]
There's no better brazilian's source than Union Mangás. Turns out that they are having maintenence right now. So let's wait till it gets normal so you guys can do your test @arkon @masgritz .

Also, thank you guys for helping us. really appreciate it.

**Comment by gabrielmartt** [comment]
I saw the MangaDex, it's missing some manga but it will help until the union normalizes

**Comment by gyoneres** [comment]
@arkon @masgritz site seems to be back to normal but tachiyomi is still not loading the manga's images. http://unionmangas.site/

**Comment by masgritz** [comment]
![screenshot_20180814-134155](https://user-images.githubusercontent.com/3949428/44105400-f92c05e2-9fc7-11e8-9b3e-cf6f60513d52.png)
Still broken for me.

**Comment by TemptingBadger** [comment]
![image](https://user-images.githubusercontent.com/31442758/44107937-4e594da2-9fcf-11e8-8628-8230e76ccc45.png)
It's kinda working, but not 100% fixed. The tachiyomi error is related that site error?

**Comment by arkon** [comment]
If the site doesn't work, the Tachiyomu extension won't work either.

**Comment by followthedamntrainCJ** [comment]
now the site is working, I tested tokyo ghoul re 179 and my hero academia
but in tachiyomi is not loading yet

**Comment by TemptingBadger** [comment]
Yes, I was wondering why Mangá Host isn't a source. And I was thinking in develop a extention to this, but as I a novice developer, I'm not sure that I can do that.

**Comment by arkon** [comment]
There's an open issue requesting Mangá Host: #49

**Comment by TemptingBadger** [comment]
Wow, that's nice.

**Comment by Lexdl** [comment]
![screenshot_20180816-073832_tachiyomi](https://user-images.githubusercontent.com/42210004/44204201-1c475200-a128-11e8-9aa3-23abdb6b42e2.jpg)
![screenshot_20180816-073857_tachiyomi](https://user-images.githubusercontent.com/42210004/44204202-1c475200-a128-11e8-8a71-f22dceb7348b.jpg)
![screenshot_20180816-074138_chrome](https://user-images.githubusercontent.com/42210004/44204203-1c475200-a128-11e8-91f1-bb66384e9fe9.jpg)
![screenshot_20180816-074143_chrome](https://user-images.githubusercontent.com/42210004/44204204-1cdfe880-a128-11e8-86c6-1b5f302ab6f3.jpg)

It's working on Chrome. on tachiyomi the catalogue works fine, but when select a manga... 😕

**Comment by CarlosEsco** [comment]
Did you update a release just got merged

**Comment by masgritz** [comment]
Thanks a lot for the help, @arkon

**Comment by Lexdl** [comment]
It's working perfect guy's, thanks a lot! 🎉

**Comment by TemptingBadger** [comment]
Yey! It's working 100% for me, tks everyone so much, you're awesome!

**Comment by gyoneres** [comment]
Yeah, working perfectly! Thank you guys <3
