### ISSUE TITLE
[Bug] MangaLib: Pages not loading

### ISSUE THREAD

**Issue by Hell13Cat** [inorichi/tachiyomi-extensions#4291]
## Device information
- Tachiyomi version: Prewiev r2676
- Android version: MiUi 11/Android 9

## Source information
- Name: MangaLib
- Extension version: 1.2.20

## Steps to reproduce
1. Start reading manga

### Expected behavior
Chapter opening

### Actual behavior
The error takes off

## Other details
![Screenshot_2020-09-02-11-40-05-421_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/46496367/91960022-0d816700-ed12-11ea-93ad-351330baa905.jpg)

**Comment by keke0202** [comment]
Привет))) А у тебя работает кнопка Последняя в Mangalib? У меня уже месяц как ошибку пишет. А сегодня вообще не обновляет ничего.

**Comment by Hell13Cat** [comment]
**Found a temporary solution**
Perform authorization through the WebView.

It is required to issue a warning about the need for authorization!

**Comment by SnakeDoc83** [comment]
Closed by https://github.com/inorichi/tachiyomi-extensions/pull/4289
