### ISSUE TITLE
[Bug] <OneManHua>: <Unable to match for imgPath>

### ISSUE THREAD

**Issue by AstralSpace** [inorichi/tachiyomi-extensions#4292]
## Device information
- Tachiyomi version: v0.10.4
- Android version: 10

## Source information
- Name: OneManHua
- Extension version: 1.2.4

## Steps to reproduce
Open any manga

### Expected behavior
Load manga for reading

### Actual behavior
Error shown "Unable to match imgPath"

## Other details
Nil

**Comment by AstralSpace** [comment]
![IMG_20200902_214445](https://user-images.githubusercontent.com/44399660/91991583-a55c7080-ed65-11ea-8b88-f582f8d0fdf2.jpg)
Current error shown. Different from starting error.

**Comment by Gallardo26** [comment]
Yea I get the same imgPath error when I'm trying to view or download any OH漫画 chapters.

**Comment by Yuiling** [comment]
Same issue

**Comment by lmk1988** [comment]
Fix is pending merge

Those who wish to test it earlier can try out the pre-release

https://github.com/lmk1988/tachiyomi-extensions/releases

Will require to enable in tachiyomi since it will marked as unofficial
