### ISSUE TITLE
Isekaiscans Chapters Bug

### ISSUE THREAD

**Issue by JudiciousVick** [inorichi/tachiyomi-extensions#4296]
## Device information
- Tachiyomi version: r2674
- Android version: 10

## Source information
- Name: Isekaiscans
- Extension version: Latest

## Steps to reproduce
1. First Step - When open the manga click on any chapter.
2. Second Step - Then read till the end and then it shows no Latest chapter

### Expected behavior
When open a manga then start reading it should change its chapter from 30-31 Automatically

### Actual behavior
When reading once chapter finishs it directly puts the next lastest chapter. eg i was reading 23 chapter and once i finished the chapter it automatically open 90 . I have read till 89 but i wanna read it again but this is happenings only in Isekaiscans 

## Other details
![Screenshot_20200903-000108](https://user-images.githubusercontent.com/59502042/92023242-20c81d00-ed7a-11ea-8dd1-c12f01ce311b.jpg)
![Screenshot_20200903-000122](https://user-images.githubusercontent.com/59502042/92023259-26bdfe00-ed7a-11ea-8889-63e899335897.jpg)
First images is of 29th chapter and there are total 93 chapter but look at what it shows at the bottom

**Comment by scb261** [comment]
More > Settings > Reader > Skip chapters marked read

**Comment by JudiciousVick** [comment]
It's working now but i never turned it on.
