### ISSUE TITLE
[Bug] <MangaLib doesn't work>: < Doesn't open chapters. The last chapters button does not work>

### ISSUE THREAD

**Issue by keke0202** [inorichi/tachiyomi-extensions#4302]
---

## Device information
- Tachiyomi version: 0.10.4
- Android version: 10

## Source information
- Name: MangaLib
- Extension version: 1.2.21

## Steps to reproduce
1. Start reading manga
2. I press the button "Latest"

### Expected behavior
Chapter opening. Clicking on the "Latest" button opens a list of the latest manga

### Actual behavior
The error takes off

## Other details
![image](https://user-images.githubusercontent.com/70511296/92081213-68c36000-edcb-11ea-85ee-ee0e5543741b.png)
![image](https://user-images.githubusercontent.com/70511296/92081257-77117c00-edcb-11ea-83eb-f594bc62cd89.png)

**Comment by Makishima** [comment]
Not only the last one. Also same error at some downloads
![изображение](https://user-images.githubusercontent.com/5548003/93073642-e6b91e00-f68b-11ea-9d67-3cca64c08c1a.png)
Aiki, Dorohedoro and others

**Comment by arkon** [comment]
Probably fixed by #4325
