### ISSUE TITLE
[Bug] <ohmanhua>: <unable to match imgpath>

### ISSUE THREAD

**Issue by lamlam1926** [inorichi/tachiyomi-extensions#4305]
## Device information
- Tachiyomi version: App version: 0.10.4 (standard, 65b32ddeb, 50)
- Android version: 10 (SDK 29)

## Source information
- Name: ohmanhua
- Extension version: 1.2.4

## Steps to reproduce
1. Click on chapter

### Actual behavior
Doesn't open, error "unable to match imgpath"

**Comment by Yuiling** [comment]
I have same issue also

**Comment by SnakeDoc83** [comment]
Duplicate of https://github.com/inorichi/tachiyomi-extensions/issues/4292
