### ISSUE TITLE
[Source Request] manhuase

### ISSUE THREAD

**Issue by pacmansa** [inorichi/tachiyomi-extensions#4322]
---

## Source Website
- Name: manhuase
- Link: https://manhuaes.com/
- Language(s): English 

## Other Details
it's a greats source for manhua since it have more chapters then most of the other sites out there

**Comment by AbdullahM0hamed** [comment]
https://github.com/inorichi/tachiyomi-extensions/blob/b4e171b52ad02247c5611ab067196476cc907183/src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComicsFactory.kt#L21

**Comment by AbdullahM0hamed** [comment]
:/ - you can close this now, and get yourself that WPComics extension

**Comment by pacmansa** [comment]
That extension doesnt have the series I am looking for so I will just use
the website then

**Comment by AbdullahM0hamed** [comment]
That's strange, the extension has the site you are requesting as one of its sources - perhaps you should make a bug report instead, mentioning the series in question?

**Comment by pacmansa** [comment]
That extension is webcomics that's the on one I found
