### ISSUE TITLE
[Source Request] <Hentai Cafe>

### ISSUE THREAD

**Issue by Feliciafoundsmiling** [inorichi/tachiyomi-extensions#4333]
---

## Source Website
- Name: Hentai Cafe
- Link: https://hentai.cafe/
- Language(s): English

## Other Details
?

**Comment by MercerBoi** [comment]
Already available under Foolslide.

**Comment by Feliciafoundsmiling** [comment]
@MercerBoi where is that foolslide? i'm sorry i'm just new to this app so i dont know where.

**Comment by MercerBoi** [comment]
@Feliciafoundsmiling Go to Browse (bottom bar), then Extensions. You will find FoolSlide there. Install it and HentaiCafe will appear on your Sources list.
