### ISSUE TITLE
[Bug] Madara: Chibi Manga HTTP 400 error

### ISSUE THREAD

**Issue by KaoticOblivion** [inorichi/tachiyomi-extensions#4342]
## Device information
- Tachiyomi version: 0.10.4
- Android version: 10

## Source information
- Name: Madara/Chibi Manga
- Extension version: 1.2.132

## Steps to reproduce
1. Open Chibi Manga under 'sources'
2. Use 'latest' or 'search' to find manga

### Expected behavior
Manga results appear

### Actual behavior
'HTTP error 400: Check website in webview' appears and no manga is accessible
![image](https://user-images.githubusercontent.com/8932192/92594031-2e950b00-f270-11ea-9eea-d9c358a7bd33.png)

## Other details
When opened in web view, the site is displayed fine, manga may be accessed. There is no cloudflare and refreshing the cache does not allow access in regular Tachiyomi search.

**Comment by jadoff630** [comment]
I've also noticed this. I will add that even with the error message you can search for manga and it will pull them up, but when it does it always shows the error "no chapters found"
