### ISSUE TITLE
[Bug] <Mangafast>: <Unparseable date>

### ISSUE THREAD

**Issue by kktuin** [inorichi/tachiyomi-extensions#4346]
#3793  Device information
- Tachiyomi version: j2k 1.0.8
- Android version: 8.1

## Source information
- Name: Mangafast
- Extension version: 1.2.2

## Steps to reproduce
1. First Step. open any manga from magafast
2. Second Step try refresh for new charapter and get msg error. Unparseable date "Scheduled PDF"

### Expected behavior
add new chatapters to the list

### Actual behavior
get error msg and miss new charapters

## Other details

![Screenshot_20200910-035618_TachiyomiJ2K](https://user-images.githubusercontent.com/44927390/92694115-900eb580-f314-11ea-9e4e-c25e638f9b85.jpg)

**Comment by druppelt** [comment]
Another affected user here. I think I found the issue: The table of chapters now sometimes has an element for an upcoming episode with an optional spoiler / teaser. This element can't properly be parsed. The HTML that is probably attempted to be parsed:
````
<tr itemprop="hasPart" itemscope="" itemtype="http://schema.org/ComicIssue">
  <td class="jds">
    <a href="https://mangafast.net/my-girlfriend-is-a-zombie-spoiler/" title="My Girlfriend Is A Zombie Chapter 148" itemprop="url">
      Chapter <span itemprop="issueNumber">148</span>
    </a>
    <br />
    <span style="font-size: 14px; margin-left: 10px">Spoiler &amp; Release Date</span>
  </td>
  <td class="tgs">Scheduled</td>
  <td class="tgs"><a href="/pdf/905310" target="_blank">PDF</a></td>
</tr>
````
If you concat the content of both td.tgs you get the "Scheduled PDF" from the error message.
The solution probably is to either change the selector or skip an element if date is not parsable.

**Comment by inisloko** [comment]
#

> Another affected user here. I think I found the issue: The table of chapters now sometimes has an element for an upcoming episode with an optional spoiler / teaser. This element can't properly be parsed. The HTML that is probably attempted to be parsed:
> 
> ```
> <tr itemprop="hasPart" itemscope="" itemtype="http://schema.org/ComicIssue">
>   <td class="jds">
>     <a href="https://mangafast.net/my-girlfriend-is-a-zombie-spoiler/" title="My Girlfriend Is A Zombie Chapter 148" itemprop="url">
>       Chapter <span itemprop="issueNumber">148</span>
>     </a>
>     <br />
>     <span style="font-size: 14px; margin-left: 10px">Spoiler &amp; Release Date</span>
>   </td>
>   <td class="tgs">Scheduled</td>
>   <td class="tgs"><a href="/pdf/905310" target="_blank">PDF</a></td>
> </tr>
> ```
> 
> If you concat the content of both td.tgs you get the "Scheduled PDF" from the error message.
> The solution probably is to either change the selector or skip an element if date is not parsable.

So is there no fix for this?

**Comment by joseph619** [comment]
@druppelt Can you open a pull request with fix?

**Comment by druppelt** [comment]
@joseph619 I'll try. I'm not really familiar with Android or Kotlin, but the change seems small enough to be doable.
