### ISSUE TITLE
[Source Request] <MangáLivre>

### ISSUE THREAD

**Issue by Deed021** [inorichi/tachiyomi-extensions#4350]
## Source Website
- Name: MangáLivre
- Link: mangalivre.net
- Language(s): PT-BR

## Other Details
?

**Comment by AbdullahM0hamed** [comment]
Already exists: https://github.com/inorichi/tachiyomi-extensions/blob/b891ee94be9212c14634f62aa573e8ff63c01212/src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProjectFactory.kt#L27
