### ISSUE TITLE
[Source Request] <SocialComics>

### ISSUE THREAD

**Issue by Deed021** [inorichi/tachiyomi-extensions#4351]
## Source Website
- Name: SocialComics
- Link: socialcomics.com.br
- Language(s): PT-BR

## Other Details
It's a paid comic source, so I don't know if it will be possible to implement it in the app

**Comment by alessandrojean** [comment]
Usually, extensions of paid websites are only created if there's some free content available, and the paid ones are not listed in the app.

**Comment by Deed021** [comment]
Oh, ok, I understand.
 But anyway, thanks for responding.
