### ISSUE TITLE
[Bug] <Disaster Scans>: <403 error yet web view works>

### ISSUE THREAD

**Issue by FaTe-code** [inorichi/tachiyomi-extensions#4355]
## Device information
- Tachiyomi version: J2K 1.0.8
- Android version: 9

## Source information
- Name: Disaster Scans (Madara)
- Extension version: 1.2.132

### Expected behavior
Open chapters normally

### Actual behavior
403 error even tho web view shows chapters

**Comment by scb261** [comment]
From discord:
1. Also happens on 0.10.4
2. Screenshot where it also happens on webview
![Screenshot_2020-09-12-23-01-43-892_eu kanade tachiyomi](https://user-images.githubusercontent.com/65343233/93001419-7b5e3780-f537-11ea-9f0a-d48e6bd22841.jpg)

**Comment by Riztard** [comment]
it work, so close issue?
