### ISSUE TITLE
[Bug] Mangá Host: covers only load if I click on a series

### ISSUE THREAD

**Issue by Sam-Oak** [inorichi/tachiyomi-extensions#4356]
## Device information
- Tachiyomi version: 0.10.4
- Android version: 9

## Source information
- Name: MangaHost
- Extension version: 1.2.12

## Steps to reproduce
1. Go to Browse
2. Click on Mangá Host source

### Expected behavior
the cover of all series should be displayed

### Actual behavior
the manga covers don't load unless I click on one series and go back.

## Other details
![image](https://user-images.githubusercontent.com/62823895/93002595-805ac100-f50e-11ea-93ea-d2ebaaff860d.png)

**Comment by alessandrojean** [comment]
I will take a look.
