### ISSUE TITLE
[Bug] Golden Mangás: "No results found"

### ISSUE THREAD

**Issue by Sam-Oak** [inorichi/tachiyomi-extensions#4357]
## Device information
- Tachiyomi version: 0.10.4
- Android version: 9

## Source information
- Name: Golden Mangás
- Extension version: 1.2.7

## Steps to reproduce
1. Go to Browse
2. Click on Golden Mangás source

### Expected behavior
Show all manga from this source.

### Actual behavior
Shows a message saying "No results found".

## Other details
the same with #3373

**Comment by alessandrojean** [comment]
I will take a look.
