### ISSUE TITLE
Newtoki extension not working

### ISSUE THREAD

**Issue by olutoyevictor** [inorichi/tachiyomi-extensions#4364]
---

## Device information
* Tachiyomi version: v0.10.4)
* Android version: 9
* Device: itel s15

## Source information
* Source name: newtoki
* Source extension version: 1.2.14

## Issue/Request
Unable to resolve host"newtoki 77.com": no address associated with hostname

## Other details
Additional details and attachments.

**Comment by arkon** [comment]
You can manually update the URL in the extension settings when it changes.
