### ISSUE TITLE
[Source Request] Zinmanga

### ISSUE THREAD

**Issue by Mekelia** [inorichi/tachiyomi-extensions#4367]
## Source Website
- Name: Zinmanga
- Link: https://zinmanga.com
- Language(s): English

**Comment by AbdullahM0hamed** [comment]
Exists:

https://github.com/inorichi/tachiyomi-extensions/blob/0c72bdb6e8d47b8dfda6014011eb1d48bd1241dc/src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt#L165
