### ISSUE TITLE
[Bug] <Asura Scans>: HTTP Error 400: Check Website In Webview

### ISSUE THREAD

**Issue by sam7028** [inorichi/tachiyomi-extensions#4368]
### Device information
Tachiyomi version: 0.10.5
Android version: 10
### Source information
Name: Asura Scans (Madara)
Extension version: 1.2.132
### Expected behavior
Open chapters normally

### Actual behavior
403 error, web view shows chapters

**Comment by psychopomp9** [comment]
They just created a new site: https://asurascans.com/
And uploading chapter again!
Webview is working but it's not showing up in general search!

**Comment by ZEXERJK** [comment]
The website is now the same style as the ones in the "WP Mangastream" extension, so I think it needs only to be moved to that extension 👍
