### ISSUE TITLE
[Bug] <Mangapark>: <no chapters found>

### ISSUE THREAD

**Issue by weeb420blazeit** [inorichi/tachiyomi-extensions#4370]
---

## Device information
- Tachiyomi version: 0.10.5
- Android version: 9.0

## Source information
- Name: Mangapark
- Extension version: 1.2.17

## Steps to reproduce
1. Go to browse section
2. Choose Mangapark
3. Choose any manga and try to update it 

### Expected behavior
It should show new chapters

### Actual behavior
It shows no chapters found

## Other details
Tried the webview and it works fine for manga that i havent read at all the latest shows 0 chapters but for mangas that i read the last available chapters stop at about 2 days ago.

**Comment by weeb420blazeit** [comment]
So either the bug fixed itself or upgrading to android 10 fixed it. Might still be worth it to look into it.

**Comment by arkon** [comment]
The website probably caches pages more aggressively, nothing to really do on our end.
