### ISSUE TITLE
[Bug] Mangazuki.online 'no chapters found' error

### ISSUE THREAD

**Issue by ArzuHrpt** [inorichi/tachiyomi-extensions#4391]
## Device information
- Tachiyomi version: 0.10.4-2688 (standard, c0789cd6, 50)
Android version: 10 (SDK 29)
Device brand: samsung
Device model: SM-N960F

##Source information
- Name: Madara/Mangazuki.online
- Extension version: 1.2.132

##Steps to reproduce
1. Open any manga/manhwa
2. Tap on the chapter and read

##Expected behavior
Tap on manga chapters and read without any problems

##Actual behavior
When i try to open a chapter i get no chapters found error. Mind you that i can see the chapters, i get the error when i try to open and read it. I get the same error with updating the chapters, same warning shows as the reason of failure.

##Other details
I checked the website and every single manga/manhwa has chapters, available for reading. I also checked other manga in mangazuki.online extension itself in app and it isn't just the manga i bookmarked, none of the chapters any manga have are available.

**Comment by arkon** [comment]
Closing in favour of #4535
