### ISSUE TITLE
[Source Request] https://manhuaplus.com

### ISSUE THREAD

**Issue by 10lalib** [inorichi/tachiyomi-extensions#4394]
---

## Source Website
- Name: ManhuaPlus
- Link: https://manhuaplus.com
- Language(s): English

## Other Details

Mostly Chinese Manhua. Didn't check for possible Japanese Manga.
Have better chapter compared to others (like no missing pages and more chapters available).

**Comment by AbdullahM0hamed** [comment]
https://github.com/inorichi/tachiyomi-extensions/blob/016653bdc0f0da500819437d2698af4d4c1aacf7/src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt#L1204
