### ISSUE TITLE
[Bug] Mangá Host: not search

### ISSUE THREAD

**Issue by AngeloInfinity** [inorichi/tachiyomi-extensions#4395]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 10 QKQ1.190910.002

## Source information
- Name: Mangá Host
- Extension version: 1.2.13

## Steps to reproduce
1. Brower
2. magnifying glass
3. type Kanojo, Okarishimasu

### Expected behavior
Show matched mangas or light novels based in search "Kanojo, Okarishimasu"

### Actual behavior
Keeping searching for a long time and shows nothing

## Other details
Update is the same problem

**Comment by alessandrojean** [comment]
I will take a look.

**Comment by alessandrojean** [comment]
There's a issue regarding the thumbnails of the results not showing (I will fix it), but the search (at least for me) it's working as expected and I am not able to reproduce this problem (I can even find the manga you specified).

What do you mean by "It shows nothing"? If you search directly in the source, does it gives any error or something like that?

**Comment by Slide123** [comment]
The search does not appear, when I click on a source to search for the manga the search does not appear

![Screenshot_20200919-042948](https://user-images.githubusercontent.com/71538025/93658219-8d594200-fa31-11ea-9e31-c04f81d276a2.png)

**Comment by Sam-Oak** [comment]
dont click on latest, click on the name/icon of the source

**Comment by Slide123** [comment]
Thanks it's work

**Comment by Sam-Oak** [comment]
this issue can be closed since the extension has already been fixed
