### ISSUE TITLE
[Bug] Elimangas: Stuck downloads

### ISSUE THREAD

**Issue by Mitia99** [inorichi/tachiyomi-extensions#4398]
## Device information
- Tachiyomi version: TachiJ2K 1.0.9
- Android version: 9

## Source information
- Name: Japscan (via Elimangas)
- Extension version: 1.2.1

## Steps to reproduce
1. Download kimetsu no yaiba chapters 122,175,166,203

Other chapters are well downloaded![Screenshot_20200919_083514_eu.kanade.tachiyomi.j2k.jpg](https://user-images.githubusercontent.com/56766778/93660019-893e1c00-fa53-11ea-8e91-1ec713ba7a62.jpg)

### Expected behavior
Downloaded chapters

### Actual behavior
Stuck download

**Comment by Bamaraj09** [comment]
Eli manga ferme a la fin du mois les serveurs aussi les chapitres ne sont donc plus mis a jour alors ca ne sert plus a rien d'utiliser l'ext

**Comment by Mitia99** [comment]
@Bamaraj09 Who said that?

**Comment by Mitia99** [comment]
Since a new Japscan extension update is available,I'll close this issue.
