### ISSUE TITLE
[Source Request] <Manga Gecesi>

### ISSUE THREAD

**Issue by kadiranul** [inorichi/tachiyomi-extensions#4399]
**PLEASE READ THIS**

This manga site very popular if you want tachiyomi is develop, I think you should bring this site. please bring. I like tachiyomi
 I want develop

## Source Website
- Name: Manga gecesi
- Link: https://mangagecesi.com/
- Language(s): Turkish (türkçe) (TR)

## Other Details
?

**Comment by AbdullahM0hamed** [comment]
F https://github.com/inorichi/tachiyomi-extensions/issues/2980. Won't be added.
