### ISSUE TITLE
[Source Request] <Epik Manga>

### ISSUE THREAD

**Issue by kadiranul** [inorichi/tachiyomi-extensions#4400]
**PLEASE READ THIS**

This manga site very popular. if you want tachiyomi is develop, I think you should bring this site. please bring. I like tachiyomi
I want develop
---

## Source Website
- Name: Epik Manga
- Link: https://epikmanga.com/
- Language(s): turkish/türkçe (TR)

## Other Details
?

**Comment by AbdullahM0hamed** [comment]
Already exists https://github.com/inorichi/tachiyomi-extensions/blob/016653bdc0f0da500819437d2698af4d4c1aacf7/src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt#L255
