### ISSUE TITLE
[Source Request] DragonBall-Tube

### ISSUE THREAD

**Issue by jopejoe1** [inorichi/tachiyomi-extensions#4409]
## Source Website
- Name: DragonBall-Tube
- Link: [dragonball-tube.com](http://dragonball-tube.com/)
- Language(s): German

## Other Details
- #4406 #4407 #4408 same

**Comment by arkon** [comment]
We do not add single manga sources unless they're only available on that site. Use an aggregator site.

**Comment by jopejoe1** [comment]
Oky, did not know that and it wasn't saying anything about that anywhere where i looked.
