### ISSUE TITLE
[Feature Request] Mangago (Obsolete) : WebView feature

### ISSUE THREAD

**Issue by kaononymous** [inorichi/tachiyomi-extensions#4420]
Hi, 

So I totally understand that Mangago is encrypted and it's difficult/impossible to get it to work in Tachiyomi which I am completely ok with... 

But

I recently redownloaded the last version of Tachiyomi: Mangago and have been able to use it with the WebView feature.

I am totally happy with how it is right now so thought I would share this for other users if they are happy with using it this way as I can still bookmark manga and get updates as well as direct links to open the manga in mangago through the WebView feature

However

It would be nice if the extension could be brought back and the Tachiyomi webview for Mangago was improved. Now I am not the most tech savvy person but my understanding is that Tachiyomi has it's own sort of browser for the WebView feature and when I click on it for mangago it doesn't load the page properly kinda looks like a html. I would attach a screenshot but I can because of the security policy. But I can still open it in chrome in tachiyomi (the chrome in-app browser thing) 

Hope that made sense. If you think it's worth checking out please do, if not, thanks anyways.

**Comment by CarlosEsco** [comment]
There are no plans to have webview only extensions.
