### ISSUE TITLE
[Bug] <Kiryuu (id)>: <java.lang.string...... on a null object reference>

### ISSUE THREAD

**Issue by AzzFar** [inorichi/tachiyomi-extensions#4428]
---

## Device information
- Tachiyomi version: v0.10.5
- Android version: 8.1

## Source information
- Name: kiryuu (id)
- Extension version: v1.2.2

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
refresh new chapter and show chapter

### Actual behavior
i tried backup and restore but error it's happen to all manga
![Screenshot_2020-09-23-20-42-57-08](https://user-images.githubusercontent.com/71803304/94095158-51681780-fe4b-11ea-81ec-b057955990fd.png)
 

## Other details
before this bug,have another bug = new chapter didn't show on Updates

**Comment by lizze-p** [comment]
Komiktap wpmamgastream is also the same problem. I think it's a Mangastream theme update. But not all Mangastream theme extensions have the same problem, .

**Comment by Riztard** [comment]
sekte komik wpmangastream too and many other

**Comment by Gungperd** [comment]
Still not solve yet
