### ISSUE TITLE
[Request] unsupport my website :(

### ISSUE THREAD

**Issue by Dhanamerdeka** [inorichi/tachiyomi-extensions#4429]
Hello admin or anyone reading this....
recently i see this #3685
can you unsupport my website?
mangadisk?
i just small translator... that earn small amount of money from website
i use that money to pay bill of the server and my domain....

so if my website can be read from external app... and my ads no longer earn some money for paid my server and domain... i can't continue this again....

i hope the admin can do something and make my website never can be read by tachiyomi
thanks again for reading my report.....
i hope you guys can do that... :(

**Comment by CarlosEsco** [comment]
please dm an admin on the discord server proof.

**Comment by Dhanamerdeka** [comment]
@CarlosEsco which admin?
are you mean... all staff that available?

**Comment by CarlosEsco** [comment]
Dark Green Staff or Blue Admins.

**Comment by CarlosEsco** [comment]
Proof has been provided

**Comment by Dhanamerdeka** [comment]
Thanks :)
