### ISSUE TITLE
MangaDex not loading

### ISSUE THREAD

**Issue by Sarkazein** [inorichi/tachiyomi-extensions#443]
Tachiyomi version: r1428 (Jul 29, 2018 4:07 PM)
MangaDex version: 1.2.32

I'm having several issues with the MangaDex, which I'm guessing are related to the new site overhaul launched today: https://mangadex.org/thread/20750

Trying to browse or search the MangaDex source returns no results, and I'm getting a variety of errors on library titles sourced from MangaDex, usually 404, but some 5XX errors.  Trying to load chapters just shows empty pages with a Retry button.

**Comment by joseph619** [comment]
Same. It says 'No results found' for me.

**Comment by arkon** [comment]
It's a known issue and is being worked on.

**Comment by CarlosEsco** [comment]
update to latest

**Comment by Sarkazein** [comment]
Wow, that was fast.  Thanks guys!
