### ISSUE TITLE
[Bug] <manhuagui>: <wrong icon>

### ISSUE THREAD

**Issue by zxhdmx** [inorichi/tachiyomi-extensions#4436]
Why does manhuagui(unofficial) use the icon of [Tencent Comics](ac.qq.com)(official)? is it a mistake? 
These are two different websites. 

Where is the expansion of Tencent Comics? is there any extension before or not?

**Comment by arkon** [comment]
> is it a mistake?

I don't know, but feel free to submit a PR to change it.

> Where is the expansion of Tencent Comics?

#412

**Comment by zxhdmx** [comment]
@arkon I don’t know how to do that.
 I searched the repo but didn’t find it may be mixed with manhuagui
