### ISSUE TITLE
[Source Request] <toonei>

### ISSUE THREAD

**Issue by boybeast** [inorichi/tachiyomi-extensions#4441]
#3793  Source Website
- Name: Toonei
- Link: https://toonei.com/
- Language(s): portuguese

## Other Details
currently the best morning and WEEBTOON site in Portuguese, with no problems in the chapters like mangaslivre and leitor.net and which brings updates faster than those previously found.

**Comment by alessandrojean** [comment]
Since it's a mirror of LeitorNet and MangaLivre, it can be added to the extension. I will do it later.
