### ISSUE TITLE
Asura Scans

### ISSUE THREAD

**Issue by pegasus0112** [inorichi/tachiyomi-extensions#4442]
Can you Do an extension for asura scans?

**Comment by scb261** [comment]
It's in *WP Mangastream* extension now. Also I just noticed that there is an error in the extension's name *WP Mang**a**stream*
https://github.com/inorichi/tachiyomi-extensions/blob/15c6ade5fbe023db0963e53ae442fe9b78e5bf06/src/all/wpmangastream/build.gradle#L5

**Comment by arkon** [comment]
@scb261 you can submit a PR to fix that
