### ISSUE TITLE
[Bug] Japscan extension not working

### ISSUE THREAD

**Issue by Bamaraj09** [inorichi/tachiyomi-extensions#4443]
- Tachiyomi version: v0.10.5
- Android version: 10

- Source name: Japscan
- Source extension version: v1.2.21

ISSUE : 

- Chapters doesn't work (load indefinitely)

- Thumbnails doesn't appear

![dfd](https://user-images.githubusercontent.com/69487106/94365843-6a372e00-00d4-11eb-8ddc-73407259acbd.jpg)
![dg](https://user-images.githubusercontent.com/69487106/94365847-6dcab500-00d4-11eb-81cc-952bece93d5d.jpg)

**Comment by Bamaraj09** [comment]
btw I had read that there would be no more japscan extension ?

**Comment by zbhoy** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/4277

**Comment by Bamaraj09** [comment]
> #4277

apparently the man who made the new japscan extension "az" 
just released the extension a few hours ago according to tachiyomi discord.
and the extension don't really work

**Comment by Bamaraj09** [comment]
and it's weird cause a 
I saw on twitter people where the japscan extension works perfectly

**Comment by az4521** [comment]
fuck off sizz

**Comment by Bamaraj09** [comment]
?

**Comment by az4521** [comment]
#4447 eat my ass sizz
