### ISSUE TITLE
[Bug] <Japscan>: <Thumbnails must be manually loaded>

### ISSUE THREAD

**Issue by Zealest** [inorichi/tachiyomi-extensions#4451]
## Device information
- Tachiyomi version: Preview r2734
- Android version: 10

## Source information
- Name: Japscan
- Extension version: 1.2.22

### Expected behavior
The thumbnails should be automatically loaded when you scroll down

### Actual behavior
The thumbnails must be manually loaded to display them.

**Comment by Mitia99** [comment]
@Zealest Go to settings>>Advanced>>Clear database.It will fix the issue.
