### ISSUE TITLE
[Bug] Bato.to >: <Unable to load extension>

### ISSUE THREAD

**Issue by xxJanelauxx** [inorichi/tachiyomi-extensions#4455]
## Device information
- Tachiyomi version: Tachiyomi v0.10.5
- Android version: 10QKQ1.191014.001

## Source information
- Name: Bato.to
- Extension version: 1.2.1

### Expected behavior
This should have happened I open the Tachiyomi go to extension Bato.to latest I can see many manga and I can go thru which I want to see. 

### Actual behavior
This happens instead I open the Tachiyomi go to extension Bato.to latest it shows error please try again or go to webview. I keep having this error for Bato.to

## Other details
Before update latest Tachiyomi is will show Error message try again or webview after update it show blank page without any words.
![Screenshot_2020-09-28-21-18-17-296_eu kanade tachiyomi](https://user-images.githubusercontent.com/72034247/94458553-ab206700-01e8-11eb-8698-ed896e2e175b.jpg)

**Comment by AjikaHan** [comment]
Same case here. Hopefully the bug will be resolved soon.

**Comment by xxJanelauxx** [comment]
The issue is not solved why is it closed?

**Comment by arkon** [comment]
It works fine for me after the extension update. Open another issue if it still doesn't work.

**Comment by ANETAIII** [comment]
I don't have this source what should I do?
