### ISSUE TITLE
[Source Request] <silence scan>

### ISSUE THREAD

**Issue by Douglasimav** [inorichi/tachiyomi-extensions#4457]
Source Website
- Name: Silence Scan
- Link: https://www.silencescan.net/
- Language(s): Portuguese Brazil

**Comment by alessandrojean** [comment]
Their website does not have an online reader, it just provides links to download or to read in other sources, so an extension can not be created.

The links they provide to other sources such as Union, Tsuki and MangaDex already have extensions, so you can use them to read the mangas they translated instead.

**Comment by Douglasimav** [comment]
thank you for the explanation

**Comment by Douglasimav** [comment]
I'm very happy, the site has been renovated and is now compatible, but it is in the initial phase, the manga is being uploaded.

**Comment by alessandrojean** [comment]
I will add it to the WPMangaStream extension.
