### ISSUE TITLE
[Source Request] <mundo mangá kun>

### ISSUE THREAD

**Issue by Paulovicbr** [inorichi/tachiyomi-extensions#4460]
Source Website

- Name: mundo mangá kun
- Link: https://mundomangakun.com.br
- Language(s): Portuguese Brazil

**Comment by alessandrojean** [comment]
I will take a look into it.

**Comment by Paulovicbr** [comment]
Thank again my friend

**Comment by Douglasimav** [comment]
where is the extension located?

**Comment by alessandrojean** [comment]
The code is not merged yet.

You have to wait until it gets merged for the extension appear in the app.

**Comment by Douglasimav** [comment]
oh ok
