### ISSUE TITLE
[Bug] <Mangapark>: <Crashes the tachiyomi app when opening manga>

### ISSUE THREAD

**Issue by MrQuietGuy** [inorichi/tachiyomi-extensions#4466]
## Device information
- Tachiyomi version: v0.10.5
- Android version: 10

## Source information
- Name: MangaPark
- Extension version: 1.2.17

## Steps to reproduce
1. First Step 
Open up Tachiyomi
2. Second Step
Press Mangapark and open up any manga
### Expected behavior
Manga loads in and then I can read

### Actual behavior
Loads for a bit then crashes

## Other details
Webview and browser works fine. I also made an account and did the captcha. Also other sources work.

**Comment by jobobby04** [comment]
Try uninstalling and then reinstalling it

**Comment by MrQuietGuy** [comment]
The source? I tried reinstalling multiple times

**Comment by jobobby04** [comment]
You sure your on 0.10.5 then? This sounds like the issue that caused 0.10.5 to be released

**Comment by MrQuietGuy** [comment]
Yes sir I double checked and even downloaded the app again

**Comment by MrQuietGuy** [comment]
Reinstalled it 3 more times and it just worked? Sorry for the inconvenience
