### ISSUE TITLE
[Bug] Madara: Manga-scantrad down?

### ISSUE THREAD

**Issue by Mitia99** [inorichi/tachiyomi-extensions#4468]
## Source information
- Name: Madara
- Extension version: 1.2.134

## Steps to reproduce
1. Open Manga-scantrad(French)

### Expected behavior
Display manga

### Actual behavior
Error 403 or 404![Screenshot_20200930_162115_eu.kanade.tachiyomi.j2k.jpg](https://user-images.githubusercontent.com/56766778/94691037-825bb700-0339-11eb-9769-cfd18caa6403.jpg)

**Comment by scb261** [comment]
If site is down (and it is), nothing tachi can do. Wait until the site will be up or migrate to another source.
> Tachiyomi is **not** hosting any content, we are not affiliated with or responsible for any source that is: slow, down, missing chapters, or has subpar image quality.

**Comment by Mitia99** [comment]
@scb261 Thank you for the response.No problem I'll switch to an other sources.I think that Manga-scantrad need to be removed from Madara.

**Comment by Mitia99** [comment]
@scb261 The site is not down.It seems like it was a temporary issue![Screenshot_20200930_170728_eu.kanade.tachiyomi.j2k.jpg](https://user-images.githubusercontent.com/56766778/94696252-825eb580-033f-11eb-8923-92b89021453c.jpg)
