### ISSUE TITLE
Magadex extension seems to be broken.

### ISSUE THREAD

**Issue by Elpsyk** [inorichi/tachiyomi-extensions#447]
On MangaDex 1.2.34 and Tachiyomi 0.7.4, it seems that MangaDex has updated their website, and by also breaking the extension. Opening a manga chapter using the extension seems to givecom.google.gson.MalformedJsonException error.

**Comment by Elpsyk** [comment]
Just saw another post that already addressed the issue, whoops.

**Comment by amarpersaud** [comment]
Not sure if it was actually addressed, but if you are still having this issue on a particular manga (might happen from time to time), it is likely due to stale cached data. Pull down to refresh with the manga open and it should work (it did for me).
