### ISSUE TITLE
[Source Request] HeroScan

### ISSUE THREAD

**Issue by DieSmilePN** [inorichi/tachiyomi-extensions#4476]
## Source Website
- Name: HeroScan
- Link: heroscan.com
- Language(s): English

## Other Details
Just please put it under **FMReader**, because it is affiliated with **ManhuaScan** and **ManhwaSmut**.

**HeroScan** is like the contents are Action, Fantasy and Adventure.
**ManhuaScan** is like on Yaoi or BL contents.
**ManhwaSmut** is like hentai.

So please add **HeroScan**

**Comment by DieSmilePN** [comment]
I noticed they added heroZscan.com. its still **BIG** difference with what I request

**Comment by jobobby04** [comment]
And you will also notice we have not closed your issue, that addition is not related to your request, if someone wants to add HeroScan, they can, as long as they make a working extension for it. This is a community based app, people can add what they want, we dont force anyone to make extensions.

**Comment by riyukuro** [comment]
I believe this source is a version of FMReader. _(Could be wrong since it looks slightly off)_

**Comment by riyukuro** [comment]
_edit/repost since I'm a idiot and didn't read extra:_ 
Most people won't do PRs for a multi-extension that they weren't the original 'creator' of as well. _(although it is just a few lines to add)_

**Comment by AbdullahM0hamed** [comment]
Unless that multi-extension is Madara😭😭😭😭
