### ISSUE TITLE
[Bug] <Team X: Team X source from madara extension doesn't work in app, works fine in we view>

### ISSUE THREAD

**Issue by kuroBi99** [inorichi/tachiyomi-extensions#4479]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 10

## Source information
- Name: Team X
- Extension version: 1.2.135

## Steps to reproduce
1. Enable Team X in  arabic language
2. Open latest in Team X

### Expected behavior
Latest manga update be shown
### Actual behavior
HTTP error 404

**Comment by arkon** [comment]
There is no Team X in Madara.

**Comment by Bmswad1** [comment]
It exists but in another extension
Extension name team x
Extension version: 1.2.7
