### ISSUE TITLE
[Feature Request] E-Hentai: Implement URL Intent if possible.

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi-extensions#4484]
For easier access to the content in-app when clicking on links associated with this source. This feature is already available for MangaDex, Tsumino and nhentai.

**Comment by ObserverOfTime** [comment]
Wasn't this implemented in #2789?

**Comment by MercerBoi** [comment]
> Wasn't this implemented in #2789?

Oh. Yes, you're right.
