### ISSUE TITLE
Manga rock - HTTP Error 502 

### ISSUE THREAD

**Issue by TheMiziko** [inorichi/tachiyomi-extensions#449]
When trying to download One Piece manga from manga rock, I get HTTP Error 502
Any idea why ?

**Comment by arkon** [comment]
What chapter(s)?

**Comment by TheMiziko** [comment]
@arkon all of them. If it would be a specific one it would be much simpler issue

**Comment by TheMiziko** [comment]
@arkon Of course. Without any anti-bot checks or spam protection

**Comment by arkon** [comment]
Is it just One Piece? Do other manga work?

Can you read it normally, or does it just give the error when you try to download it?

**Comment by TheMiziko** [comment]
@arkon I just tested it and it seems like yes, it applies to all manga via this extension

**Comment by AmineI** [comment]
Are you still running into that issue ?

**Comment by TheMiziko** [comment]
@Aminel Yes

**Comment by AmineI** [comment]
Did you try another network ? Which version of the app/extension do you use ? I don't have the issue either, neither in the stable version nor the development one, I'm trying to reproduce it to help :/ .

P.S : Oh, I should do something about that username of mine, it's an i at the end, not an L

**Comment by TheMiziko** [comment]
@AmineI I tried latest 2 beta releases and 3 stable ones. I was waiting for a pretty long time for it to be fixed in future updates, but unfortunately it didn't happen 
I also tried port forwarding and other connection-related solutions, they didn't work either

**Comment by CarlosEsco** [comment]
Main app isn't going to change mangarock

**Comment by AmineI** [comment]
@TheMiziko You didn't told me about the extension version though

**Comment by jpmc** [comment]
I'm using Mangarock 1.0.5 on stable 0.8.0  and getting 502 errors when fetching any manga as well.

**Comment by arkon** [comment]
@jpmc Can you access [this link](http://api.mangarockhd.com/query/web401/info?oid=mrs-serie-100177863) from your browser?

**Comment by jpmc** [comment]
Yeah, I get a bunch of JSON.

**Comment by robbato** [comment]
Me too.
I can access the link but still getting error 502.
tachiyomi dev r1463
mangarock 1.0.5

**Comment by robbato** [comment]
nvm i can access it now
