### ISSUE TITLE
[Bug] <Kiryuu>: <unable to get manga chapter and manga information>

### ISSUE THREAD

**Issue by nizarschecter** [inorichi/tachiyomi-extensions#4496]
## Device information
- Tachiyomi version: 0.8.5
- Android version: 4.4.2

## Source information
- Name: Kiryuu
- Extension version: 1.2.2

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened

### Actual behavior
This happens instead

**Comment by scb261** [comment]
Duplicate of #4428

**Comment by nizarschecter** [comment]
> Duplicate of #4428

still unable to

**Comment by arkon** [comment]
Do not open duplicate issues.
