### ISSUE TITLE
[Bug] <MangaHost>: <The source does not update to the most recent chapters>

### ISSUE THREAD

**Issue by Deed021** [inorichi/tachiyomi-extensions#4508]
## Device information
- Tachiyomi version: Most recent
- Android version: 7.0

## Source information
- Name: MangaHost (PT-BR)
- Extension version: Most recent

## Steps to reproduce - *I did not understand*
1. First Step 
2. Second Step

### Expected behavior
This should have happened:
-The most recent chapters should appear

### Actual behavior
This happens instead:
-newer chapters do not appear

```

## Other details
This has been happening for 2 days

**Comment by alessandrojean** [comment]
I will take a look.

**Comment by alessandrojean** [comment]
I am not able to reproduce this issue.

All the chapters are showing in the app to me, including the most recent ones.

<img width="300" src="https://user-images.githubusercontent.com/14254807/95017229-9b60b280-062e-11eb-82d9-bce4431e8ffc.png"><img width="300" src="https://user-images.githubusercontent.com/14254807/95017253-afa4af80-062e-11eb-96ba-ff84f6d122cd.png">

> - Extension version: Most recent

"Most recent" is not a version number. Are you using the 1.2.14?

> -newer chapters do not appear

Elaborate more, please.

They do not appear when you browse the source and open a manga that is not in your library or when you pull to refresh the chapter list of a manga that is in your library?
