### ISSUE TITLE
[Bug] Rawkuma: Does not load chapters (index:0, Size:0)

### ISSUE THREAD

**Issue by ptoump** [inorichi/tachiyomi-extensions#4509]
## Device information
- Tachiyomi version: r2703
- Android version: 9

## Source information
- Name: Rawkuma
- Extension version: 1.2.3

## Steps to reproduce
1. Go to any manga

### Expected behavior
Load/show Chapter list

### Actual behavior
Empty chapter list, returns (index:0, size:0).

**Comment by arkon** [comment]
Didn't get very far into looking at this, but for whoever picks it up, looks like the site uses WPManga.
