### ISSUE TITLE
Mangago issue.

### ISSUE THREAD

**Issue by Reraru** [inorichi/tachiyomi-extensions#451]
![img_20180812_074729](https://user-images.githubusercontent.com/40790144/43998372-764b0fce-9e05-11e8-967e-98d982cda4d5.png)
I first used the site it worked fine. 
Then I used the app and read one chapter of a manga then when I opened next chapter it stopped working. Then I opened the Mangago site and the cover images are broken, and manga won't load (broken images as well)

I got the message as shown in the pic.

![screenshot_2018-08-12-07-49-55-2](https://user-images.githubusercontent.com/40790144/43998392-d1f3f002-9e05-11e8-88cf-68c8ff5c69f9.png)

And when I pressed okay it gave me this message.

I hope it can be fixed.

**Comment by KoyLyria** [comment]
Same exact thing.

**Comment by fatimagrace015** [comment]
Is it fixed on you?

**Comment by arkon** [comment]
Duplicate of #377
