### ISSUE TITLE
[Bug] <emerald>: <batoto JSONArray cannot be converted to JSONObject>

### ISSUE THREAD

**Issue by jadoff630** [inorichi/tachiyomi-extensions#4524]
## Device information
- Tachiyomi version: SY 1.3.1 (based on stable 0.10.5)
- Android version: 10

## Source information
- Name: batoto (Emerald)
- Extension version: 1.2.2

## Steps to reproduce
1. Open Lost Princess from Batoto source (emerald extension)
2. select latest chapter
3. instead of loading chapter normally, error message should desplay
4. NOTE: should be reproducible for any chapter uploaded to batoto after yesterday afternoon

### Expected behavior
Chapter images should load in viewer

### Actual behavior
Value [image urls] of type org.json.JSONArray cannot be converted to JSONObject error message appeared 
![Screenshot_20201005-085200_TachiyomiSY](https://user-images.githubusercontent.com/25085973/95093173-1937c300-06ee-11eb-8775-49c0b1e281f5.jpg)

**Comment by kaononymous** [comment]
Related error message: Value document.domain of type java.lang.string cannot be converted to JSONObject

**Comment by vipzzx** [comment]
Having same error. But for some reason Dokebi Cafe Ch 74 works. Not sure if this information will help

**Comment by Dragoon91786** [comment]
Reproduced by me. See: https://github.com/inorichi/tachiyomi-extensions/issues/4635

**Comment by Dragoon91786** [comment]
Any ideas yet of the cause?

I expected that it may be a result of bato.to changing something on their end—possibly, something related to ads.

Has anyone checked with a previous version of Bato.to?

I've had similar issues in the past with this site in particular with this type of problem, however, there appears to have been an effective workaround.
