### ISSUE TITLE
[BUG] Bato.to: Whenever I try to open any manga under the bato.to source, it doesn't open and shows the same message.

### ISSUE THREAD

**Issue by wimterseason** [inorichi/tachiyomi-extensions#4534]
## Device information
- Tachiyomi version: 1.0.9
- Android version: 10

## Source information
- Name: Bato.to
- Extension version: 1.2.2

## Steps to reproduce
1. Open manga
2. Click read chapter

### Expected behavior
It should've just opened and allowed access to read

### Actual behavior
It doesn't open and shows this message:
![tachiyomi bug](https://user-images.githubusercontent.com/72458693/95226102-201a1f00-082f-11eb-827e-e0b89811d2d3.jpg)
jic: it says Value document.domain of type java.lang.String cannot be converted to JSONObject

## Other details
I'm quite sure bato.to isn't down. I also checked a couple of the manga on my pc and the chapters loaded fine.

**Comment by jobobby04** [comment]
Duplicate https://github.com/inorichi/tachiyomi-extensions/issues/4524
