### ISSUE TITLE
[Bug] <OH漫画>: <unable to read using app>

### ISSUE THREAD

**Issue by tsunaliew** [inorichi/tachiyomi-extensions#4539]
## Device information
- Tachiyomi version: Stable 0.10.5
- Android version: Android Version 10

## Source information
- Name: OH漫画 (OhManhua/OneManHua)
- Extension version: 1.2.5

## Steps to reproduce
Opening a chapter

### Expected behavior
Chapter opens

### Actual behavior
Black page with retry button

## Other details
Tried retrying multiple times but failed to show any pictures. Able to show pictures when using WebView.
Affecting all chapters in OH漫画 extension. Other extensions functioning as normal.

OH漫画 (OhManhua/OneManHua) url in the past: https://www.ohmanhua.com/
Current OH漫画 (OhManhua/OneManHua) url: https://www.cocomanhua.com/

![Screenshot_20201007-043025_Tachiyomi](https://user-images.githubusercontent.com/8689637/95260198-e828d100-085a-11eb-989d-47dbc6122dad.jpg)
![Screenshot_20201007-044245_Tachiyomi](https://user-images.githubusercontent.com/8689637/95260200-e8c16780-085a-11eb-88f0-521d22219880.jpg)

**Comment by tsunaliew** [comment]
OH漫画 (OhManhua/OneManHua) url in the past: https://www.ohmanhua.com/
Current OH漫画 (OhManhua/OneManHua) url: https://www.cocomanhua.com/

**Comment by lamlam1926** [comment]
same issue

**Comment by JudiciousVick** [comment]
The name itself change to https://www.cocomanhua.com/

**Comment by AbdullahM0hamed** [comment]
The name isn't the problem, it redirects to coco manhua just fine. 

The problem seems to lie in:

https://github.com/inorichi/tachiyomi-extensions/blob/016653bdc0f0da500819437d2698af4d4c1aacf7/src/zh/onemanhua/src/eu/kanade/tachiyomi/extension/zh/onemanhua/Onemanhua.kt#L176-180 

where it picks up some Chinese name, which is then encoded here:

https://github.com/inorichi/tachiyomi-extensions/blob/016653bdc0f0da500819437d2698af4d4c1aacf7/src/zh/onemanhua/src/eu/kanade/tachiyomi/extension/zh/onemanhua/Onemanhua.kt#L198

So the final URL looks somewhat like this: https://img.cocomanhua.com/comic/12202/%E4%BB%80%E4%B9%88%E5%8A%9F%E6%B3%95%EF%BC%9F/0006.jpg, which returns a 404.

It should look something like: https://img.cocomanhua.com/comic/12202/cEhCekxtSXNnTWRsWGpnenU5a2hIUT09/0004.jpg, but I couldn't find cEhCekxtSXNnTWRsWGpnenU5a2hIUT09 in the decrypted data - so not sure where that's coming from

**Comment by akshayc231** [comment]
![Screenshot_2020-10-07-14-43-32-31](https://user-images.githubusercontent.com/70152497/95311723-a2e0bf80-08ab-11eb-8049-7dcf58ac4d1b.jpg)
Don't know whether it will help,here a screenshot of traffic captured using adguard from "onemanhua" look like they changed the format of image.wonder if that's the problem?

**Comment by loafer-daddy** [comment]
> ## Device information
> - Tachiyomi version: Stable 0.10.5
> - Android version: Android Version 10
> 
> ## Source information
> - Name: OH漫画 (OhManhua/OneManHua)
> - Extension version: 1.2.5
> 
> ## Steps to reproduce
> Opening a chapter
> 
> ### Expected behavior
> Chapter opens
> 
> ### Actual behavior
> Black page with retry button
> 
> ## Other details
> Tried retrying multiple times but failed to show any pictures. Able to show pictures when using WebView.
> Affecting all chapters in OH漫画 extension. Other extensions functioning as normal.
> 
> OH漫画 (OhManhua/OneManHua) url in the past: https://www.ohmanhua.com/
> Current OH漫画 (OhManhua/OneManHua) url: https://www.cocomanhua.com/
> 
> ![Screenshot_20201007-043025_Tachiyomi](https://user-images.githubusercontent.com/8689637/95260198-e828d100-085a-11eb-989d-47dbc6122dad.jpg)
> ![Screenshot_20201007-044245_Tachiyomi](https://user-images.githubusercontent.com/8689637/95260200-e8c16780-085a-11eb-88f0-521d22219880.jpg)
> 

404 is due to change in extension of image to ".webp"

**Comment by lmk1988** [comment]
Urls have changed in weird ways.

There's technically 3 different ways it processes image urls but we're only processing 2 of them.
(Because the last way does not seem to be properly implemented yet for any manga I've browsed. The parameter doesn't exist in C_DATA)

Here's the pre-release apk for testing

https://github.com/lmk1988/tachiyomi-extensions/releases/tag/v1.2.6-prerelease

**Comment by tsunaliew** [comment]
> Urls have changed in weird ways.
> 
> There's technically 3 different ways it processes image urls but we're only processing 2 of them.
> (Because the last way does not seem to be properly implemented yet for any manga I've browsed. The parameter doesn't exist in C_DATA)
> 
> Here's the pre-release apk for testing
> 
> https://github.com/lmk1988/tachiyomi-extensions/releases/tag/v1.2.6-prerelease

Installed and trusted but it show this instead.
![Screenshot_20201008-025535_Tachiyomi](https://user-images.githubusercontent.com/8689637/95375296-01d91f80-0912-11eb-93b9-b379d180cc96.jpg)

**Comment by lmk1988** [comment]
> 
> 
> > Urls have changed in weird ways.
> > There's technically 3 different ways it processes image urls but we're only processing 2 of them.
> > (Because the last way does not seem to be properly implemented yet for any manga I've browsed. The parameter doesn't exist in C_DATA)
> > Here's the pre-release apk for testing
> > https://github.com/lmk1988/tachiyomi-extensions/releases/tag/v1.2.6-prerelease
> 
> Installed and trusted but it show this instead.
> ![Screenshot_20201008-025535_Tachiyomi](https://user-images.githubusercontent.com/8689637/95375296-01d91f80-0912-11eb-93b9-b379d180cc96.jpg)

Yeah, was trying to find a manga like that. Do you have a url to that?

Does it happen to all manga or only that manga?

**Comment by tsunaliew** [comment]
> > > Urls have changed in weird ways.
> > > There's technically 3 different ways it processes image urls but we're only processing 2 of them.
> > > (Because the last way does not seem to be properly implemented yet for any manga I've browsed. The parameter doesn't exist in C_DATA)
> > > Here's the pre-release apk for testing
> > > https://github.com/lmk1988/tachiyomi-extensions/releases/tag/v1.2.6-prerelease
> > 
> > 
> > Installed and trusted but it show this instead.
> > ![Screenshot_20201008-025535_Tachiyomi](https://user-images.githubusercontent.com/8689637/95375296-01d91f80-0912-11eb-93b9-b379d180cc96.jpg)
> 
> Yeah, was trying to find a manga like that. Do you have a url to that?
> 
> Does it happen to all manga or only that manga?

Happen to all manga that belong to this extension. Not sure if you what url you want but i am sure WebView have it.

**Comment by lmk1988** [comment]
@tsunaliew 

My bad, uploaded old apk.

Try again with tachiyomi-zh.onemanhua-v1.2.6-release2.apk

https://github.com/lmk1988/tachiyomi-extensions/releases/tag/v1.2.6-prerelease

**Comment by tsunaliew** [comment]
> @tsunaliew
> 
> My bad, uploaded old apk.
> 
> Try again with tachiyomi-zh.onemanhua-v1.2.6-release2.apk
> 
> https://github.com/lmk1988/tachiyomi-extensions/releases/tag/v1.2.6-prerelease

It works now, thank you guys. So i have to migrate all the manga i have in ohmanga to cocomanga?

**Comment by lmk1988** [comment]
> 
> 
> > @tsunaliew
> > My bad, uploaded old apk.
> > Try again with tachiyomi-zh.onemanhua-v1.2.6-release2.apk
> > https://github.com/lmk1988/tachiyomi-extensions/releases/tag/v1.2.6-prerelease
> 
> It works now, thank you guys. So i have to migrate all the manga i have in ohmanga to cocomanga?

Nope, it should work fine, the ID of the extension did not change
Just that when it is merged, you might need to reinstall the official merged version again

**Comment by tsunaliew** [comment]
i realized that some manga are still black page with retry button but some manga are working fine with the new apk installed.

**Comment by lmk1988** [comment]
> 
> 
> i realized that some manga are still black page with retry button but some manga are working fine with the new apk installed.

I had that issue before, think it is due to cache.

Try clearing your database cache
Settings -> Advanced -> Clear database

**Comment by tsunaliew** [comment]
> > i realized that some manga are still black page with retry button but some manga are working fine with the new apk installed.
> 
> I had that issue before, think it is due to cache.
> 
> Try clearing your database cache
> Settings -> Advanced -> Clear database

It worked, once again thank you guys. Much appreciated.
