### ISSUE TITLE
[Source Request] <Source Name>

### ISSUE THREAD

**Issue by Ploter4815** [inorichi/tachiyomi-extensions#4551]
## Source Website
- Name: 拷贝漫画
- Link: https://www.copymanga.org
- Language(s): 中文 Chinese

## Other Details
更新快，加载也快，就是要挂vpn
Fast update, fast loading, just need to hang vpn.（Translated by Google）

**Comment by AbdullahM0hamed** [comment]
I mean the request was auto-closed, but I'm not about to miss the opportunity to make a bad joke:

Looks like this request was copymanga'd from #3795. 

I'll see myself out now.
