### ISSUE TITLE
[Bug] Foolslide : Hardcoded DNS-over-Https

### ISSUE THREAD

**Issue by egar3427** [inorichi/tachiyomi-extensions#4556]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 10

## Source information
- Name: Foolslide
- Extension version: 1.2.54

## Steps to reproduce
1. Enable DNS-over-TLS (Private DNS) in the system level
2. Disable DNS-over-HTTPS in Tachiyomi

### Expected behavior
The sites should be accessible from Tachiyomi because its using system wide DoT as it was accessible from the normal browser.

### Actual behavior
The sites not accessible in Tachiyomi if DoH is disabled in Tachiyomi settings. This is because its already hardcoded to use DoH, so it can't use system wide DoT.
![W7IFVSP](https://user-images.githubusercontent.com/18672175/95462277-7c9d4b80-09a1-11eb-98ff-b1c577ee6750.png)

## Other details
So I'm using DNS-over-TLS both in my router and phone. But still can't access this site in tachiyomi. Whereas I could access it normally in the browser. I need to enable DoH option in Tachiyomi. This should not be hardcoded to use DoH.

**Comment by arkon** [comment]
>  This is because its already hardcoded to use DoH, so it can't use system wide DoT.

Wat?

**Comment by egar3427** [comment]
So, I'm using android Private DNS which is using DNS-over-TLS protocol. But I'm unable to open that manga site in Tachiyomi while I can open it normally in the browser.

Then if I enable "Use DNS-over-HTTPS" in Tachiyomi settings, I was able to open that manga site in Tachiyomi. What is causing this?

**Comment by ObserverOfTime** [comment]
Isn't that what you would normally expect? It shouldn't use DoH if it's disabled in settings.

**Comment by egar3427** [comment]
Yes. It seems my wording was so bad, sorry. Let me break it down.

That site is blocked in my country, I bypass it by using DoT in my phone so then I can open that site perfectly in my browser or other manga apps. The problem is I couldn't open that site in Tachiyomi. I should be able to open that site in Tachiyomi because I'm already using DoT to bypass the site blocking.

The only way for me to access that site was to enable DoH in tachiyomi. This is kinda wasteful because I'm already using DoT in my device and should be able to open it in tachiyomi.

My assumption is Foolslide extensions was hardcoded to only use DoH in tachiyomi? Am I correct? Because as seen in the image above, Its requesting 0.0.0.0:443 which is DoH port. 
If its correct, then please remove that.

**Comment by arkon** [comment]
No extensions hardcode DoH usage. Port 443 is used by DoH, but it's also just the normal HTTPS port, so the error would just mean you can't connect to the site. I don't think DNS-level errors get exposed to users.

I don't know why it doesn't work for you, but the extension itself doesn't do anything special with regards to networking.

**Comment by arkon** [comment]
Anyway, I'm not entirely sure why it's not working for you, but it's definitely unrelated to the DoH stuff in the app.
