### ISSUE TITLE
[Bug] AsuraScans: Release date not available in chapter lists

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi-extensions#4565]
## Device information
- Tachiyomi version: 0.10.5-2763
- Android version: 10

## Source information
- Name: AsuraScans
- Extension version: WP MangaStream 1.2.25

Manga chapter lists don't have release dates.

**Comment by AbdullahM0hamed** [comment]
That is to be expected, since the site doesn't have it either:
![Screenshot_20201009-185448_Chrome](https://user-images.githubusercontent.com/25087116/95615978-ff391000-0a60-11eb-9080-006c4c16dddb.jpg)

**Comment by bbtora** [comment]
So this will not be addressed? What about the chapter updates in Library Updates? Those will be invisible as well.

**Comment by CrepeTF** [comment]
¯\_(ツ)_/¯ can't add what's not there

**Comment by AbdullahM0hamed** [comment]
> So this will not be addressed? What about the chapter updates in Library Updates? Those will be invisible as well.

This will not be addressed because it can't be addressed. If that bothers you, migrate your manga. As for the latter portion of your message - if you are worried about manga in the library not being updated due to the lack of a release date, then don't - they should still update fine

**Comment by bbtora** [comment]
Yeah, it can't be helped if it can't be fixed. 
As for the second part, I was referring to the Library Updates section. The chapter won't show up there.

**Comment by CrepeTF** [comment]
It won't show up there because it depends on the release date, which isn't provided on site, you could just add a separate category for the mangas in this souece

**Comment by bbtora** [comment]
> What about the chapter updates in Library Updates? Those will be invisible as well.

Lol, that's what I said in my first reply as well.
Anyways, the issue won't be solved so it doesn't matter now.

**Comment by AbdullahM0hamed** [comment]
> Lol, that's what I said in my first reply as well.

....you are quoting yourself.

**Comment by bbtora** [comment]
I don't want to make this thread any longer by using it as a chat group so tag me in the discord server for any further clarifications. 

Thanks.
