### ISSUE TITLE
Cocomanhua. Thumbnail Not Loading.

### ISSUE THREAD

**Issue by JudiciousVick** [inorichi/tachiyomi-extensions#4566]
## Device information
- Tachiyomi version: Preview r2763
- Android version: 10

## Source information
- Name: cocomanhua
- Extension version: 1.2.6

## Steps to reproduce
1. First Step - Opening the cocomanhua and the images are not loading until click on specific one and reload it then the image appears
### Expected behavior
This should have happened

### Actual behavior
This happens instead

## Other details
![Screenshot_20201009-231117](https://user-images.githubusercontent.com/59502042/95615289-9adc7780-0a85-11eb-9372-75936933ac44.jpg)
![Screenshot_20201009-231110](https://user-images.githubusercontent.com/59502042/95615297-9e6ffe80-0a85-11eb-8f94-3295e15167a2.jpg)

**Comment by AbdullahM0hamed** [comment]
They load fine for me. Does clearing cache/database work?

**Comment by JudiciousVick** [comment]
Yes it started working again thanks
