### ISSUE TITLE
[Bug] New Dead sources

### ISSUE THREAD

**Issue by keinezeit8** [inorichi/tachiyomi-extensions#4575]
## Device information
- Tachiyomi version: J2K 1.0.9
- Android version: 11

New dead sites:
Madara - Hero Manhua - "hello world"
Madara - Luxy Scans - down
Madara - NinjaScans - down
Genkan - Kraken Scans - Invalid SSL certificate

I believe that Luxy- and NinjaScans both rebranded/merged into other groups.

**Comment by Riztard** [comment]
madara - Hero Manhua work again
