### ISSUE TITLE
[Feature Request] Komga: trust self signed ssl certificates

### ISSUE THREAD

**Issue by Kawaizombi** [inorichi/tachiyomi-extensions#4581]
Hi,

Background:
I run komga server in my local network, it sits behind nginx with https(self signed certificate) enabled. But when I try to open komga source in tachiyomi app I get error
`java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

Is it possible to add an option in source setting to trust self signed certificates, or file input where certificate for source can be placed?

**Comment by arkon** [comment]
Have you tried adding it to the system-level trust store? I'd rather not add this kind of thing to app since it's pretty niche, and it opens up a security hole to the uneducated masses.

**Comment by Kawaizombi** [comment]
Yeap, I added my self signed certificate as user trusted, but it did not help. And to install it as `system trusted` requires root access(that I don't have). 
Also while searching came across this doc https://gist.github.com/luciopaiva/aa9cb30863804fb2ac3ed1ccd11c95c7 as I understand if app targets android api version >= 24 it will ignore user installed certificates, by default. But this behavior can be changed through manifest file.

**Comment by arkon** [comment]
Thanks for digging. I added that to the app, so you can try it in next week's preview build.
