### ISSUE TITLE
[Source Request] <Library Genesis>

### ISSUE THREAD

**Issue by sys-3** [inorichi/tachiyomi-extensions#4585]
---

## Source Website
- Name: Library Genesis
- Link: https://libgen.lc/comics/
- Language(s): Mainly English. There are other languages though :).

## Other Details
There are many mirrors/links for Library Genesis, I just linked the .lc one because I noticed it has a good comic section, there is also a manga one I haven't tried. If anyone takes on the task of creating an extension for this it should be a multiple source one with a bunch of Library Genesis links (in my opinion). Since they like to go down a lot.

**Comment by curche** [comment]
I checked the site, and there was no option to read from the website. So, an extension might not be possible.

The site does allow you to download comics though
You can download and read in tachiyomi using the local source

Supported chapter formats are folder with pictures inside (such as .jpg, .png, etc), ZIP/CBZ, RAR/CBR and EPUB.
You can read up more about it here: https://tachiyomi.org/help/guides/reading-local-manga/

**Comment by CarlosEsco** [comment]
closing since there is no online reader
