### ISSUE TITLE
[Bug] Asura Scans (java.lang.string) Error

### ISSUE THREAD

**Issue by sam7028** [inorichi/tachiyomi-extensions#4593]
### Device information

Tachiyomi version: 0.10.5

Android version: 10

### Source information

Name: Asura Scans 

Extension: WPMangastream 1.2.25

### Steps To Reproduce

1.Go to Browse Section

2.Choose Asura Scans

3.Choose any manga and try to update it

### Expected behavior

It should show new chapters

### Actual behavior
It shows java.lang.string Error
![Screenshot_2020-10-12-22-33-20-731_eu kanade tachiyomi](https://user-images.githubusercontent.com/69104545/95773474-2c452700-0cdc-11eb-8355-4c56a6709a5e.jpg)

### Other details

Webview works fine

**Comment by scb261** [comment]
The same bug appears for some other WP MangaStream sources #4461 #4428
