### ISSUE TITLE
[Source Request] <Gekkou Scan>

### ISSUE THREAD

**Issue by Paulovicbr** [inorichi/tachiyomi-extensions#4595]
## Source Website
- Name: Gekkou Scan
- Link: http://leitor.gekkouscans.com.br
- Language(s): Portuguese Brazil

**Comment by CrepeTF** [comment]
Dupe of #4458

**Comment by AbdullahM0hamed** [comment]
@CrepeTF when I came here to say that and you already beat me to it😔
