### ISSUE TITLE
[Source Request] <Mangas.in>

### ISSUE THREAD

**Issue by kitkateeya** [inorichi/tachiyomi-extensions#4597]
## Source Website
- Name: Mangas.in
- Link: https://mangas.in/
- Language(s): Español/Spanish

## Other Details
?

**Comment by scb261** [comment]
https://github.com/inorichi/tachiyomi-extensions/blob/016653bdc0f0da500819437d2698af4d4c1aacf7/src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/Generator.kt#L255
Maybe it should be renamed to *Mangas.in (Mangas.pw)* as it is on the site? Related issue when the domain was changed #2378

**Comment by kitkateeya** [comment]
I'm sorry, I don't understand what this list is about. I can't find this source in the app :(

**Comment by AbdullahM0hamed** [comment]
@kitkateeya he means that mangas.in used to be mangas.pw - a source we once had which is now either broken or gone due to changing to mangas.in (haven't verified myself, but mangas.pw no longer exists, so it is probably true)

**Comment by scb261** [comment]
It's working in the app. It's in *My Manga Reader CMS* extension, *Mangas.pw* source. When domain was changed, extension was updated, but the source's name wasn't.

**Comment by AbdullahM0hamed** [comment]
My bad, didn't see that - it was even in the code snippet😭😭😭😭

**Comment by jobobby04** [comment]
If you change the source name, the id will be reshuffled, make sure to override the id if you are changing the source name

**Comment by kitkateeya** [comment]
thank you all for your help, I already found it in the app 😊
