### ISSUE TITLE
[Bug] <Mangabox>: <some manga from mangakakalot not updated>

### ISSUE THREAD

**Issue by billybale** [inorichi/tachiyomi-extensions#4599]
---

## Device information
- Tachiyomi version: TachiJ2K 1.0.9
- Android version: 9.0

## Source information
- Name: Mangabox
- Extension version: 1.2.24

### Expected behavior
Some manga didn't update such as boku no hero academia since July

**Comment by scb261** [comment]
Open the site in webview, they didn't upload any chapter for Boku No Hero Academia since July
> Tachiyomi is **not** hosting any content, we are not affiliated with or responsible for any source that is: slow, down, missing chapters, or has subpar image quality.
