### ISSUE TITLE
[Source Request] <HeroScan> theres hero manhua but its sooo DIFFERENT

### ISSUE THREAD

**Issue by HeyYow08** [inorichi/tachiyomi-extensions#4606]
## Source Website
- Name: HeroScan
- Link: heroscan.com
- Language(s): English

## Other Details
Just please put it under **FMReader**, because it is affiliated with **ManhuaScan** and **ManhwaSmut**.

**HeroScan** is like the contents are Action, Fantasy and Adventure.
**ManhuaScan** is like on Yaoi or BL contents.
**ManhwaSmut** is like hentai.

So please add **HeroScan**

**Comment by jobobby04** [comment]
Duplicate https://github.com/inorichi/tachiyomi-extensions/issues/4476
