### ISSUE TITLE
[Bug] Multiple Sources: All My sources seems to be broken, only mangahere is working

### ISSUE THREAD

**Issue by Basha0** [inorichi/tachiyomi-extensions#4611]
## Device information
- Tachiyomi version: I am Using Tachiyomij2k v 1.0.9(latest)
- Android version: 10

## Source information
![extensions](https://user-images.githubusercontent.com/12910214/95987376-a2a27000-0e27-11eb-86f4-85219344beaa.jpg)
![source](https://user-images.githubusercontent.com/12910214/95987557-e4331b00-0e27-11eb-880d-436f1da8bcbc.jpg)

## Steps to reproduce
Not sure to be honest. The only thing i did was adding like 8 Mangas of the series Mahouka from multiple sources on sunday. and on monday nothing was working, only Mangahere
the issue is opening a chapter from any Source beside Manga Here is displaying a endless loading screen. No error is displayed, just a loading screen.

### Expected behavior
Displaying the Images

### Actual behavior
Endless loading screen

## Other details
None.

**Comment by scb261** [comment]
I tried *Mangakakalot* from *MangaBox* and *ReadMangaToday*, both work fine for me. Try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/), check if it works on [vanilla Tachiyomi](https://tachiyomi.org/download/).

**Comment by Basha0** [comment]
Restarting my phone did the job. Seems like there is probably an issue with the caching?

**Comment by arkon** [comment]
Open an issue in the J2K repo if it persists.
