### ISSUE TITLE
[Source Request] <Nuxscans>

### ISSUE THREAD

**Issue by Warcrors** [inorichi/tachiyomi-extensions#4619]
---

## Source Website
- Name: nuxscans 
- Link: https://nuxscans.blogspot.com
- Language(s): en

## Other Details
**Please add ASAP**

**Comment by AbdullahM0hamed** [comment]
> **Please Add ASAP**

Sorry to break it to you, but this will almost certainly never happen. No-one who has added sources seems to have been interested in adding any blogspot.com site.

Here's a list of open blogspot requests that no-one is working on to shatter your hopes, though:
#2117
#4236
#4009
#2635
#3635
#3384
#3257
#1871
#1331
#1579
