### ISSUE TITLE
[Bug] <mangasee>: <internal_error>

### ISSUE THREAD

**Issue by oxsi91** [inorichi/tachiyomi-extensions#4625]
## Device information
- Tachiyomi version: j2k 1.0.9
- Android version: 8

## Source information
- Name: mangasee
- Extension version: 14

It show internal_error, webview working, bookmarked manga also working. After app clear cache it working with no cover img, but after reopen the app it show internal_error again

**Comment by sainAk** [comment]
Try enabling dns over https 
Or use a vpn

**Comment by oxsi91** [comment]
I always use dns over https and vpn on my phone.

**Comment by arkon** [comment]
Can't reproduce this, and haven't heard any similar reports.

Try using a different version of Tachiyomi to see if it still persists and if so, please open up another issue referencing this one.
