### ISSUE TITLE
[Bug] Dilbert v1.22: Can't Download

### ISSUE THREAD

**Issue by taextuser** [inorichi/tachiyomi-extensions#4634]
## Device information
- Tachiyomi version: AZ latest
- Android version: 5

## Source information
- Name: Dilbert
- Extension version: 1.22

## Steps to reproduce
1. Update list
2. Fail to download strips

### Expected behavior
Strips should download

### Actual behavior
Endless loop, no downloading happens. 

## Other details
Dilbert's js loader seems to have changed, takes longer, if you use the webview you can watch the actual page and read the strips, but downloasding fails still. Also, there's a autoban happening if you download too many strips, ie try to download or just list several years in quick succession.

**Comment by scb261** [comment]
Tempban also happened to me once, when I tried to open several years one after another. Rate limit should be added to the extension

**Comment by ardittristan** [comment]
#1733

**Comment by scb261** [comment]
They described two issues: 
1. Extension stopped loading pages recently at all
2. You can get ip banned

Should first one be added to #1733 or this issue should be reopened?

**Comment by CarlosEsco** [comment]
I assume them being rate limited by the site was why it was slow.  Is anyone else able to replicate it being slower?

**Comment by scb261** [comment]
They say that it's slower in webview and fails to download in the app. I can reproduce not loading pages in the app. I wouldn't say it's slow in webview, works fine in webview for me.
