### ISSUE TITLE
[Feature Request] MangaDex: Implementation of `/report` endpoint

### ISSUE THREAD

**Issue by lflare** [inorichi/tachiyomi-extensions#4640]
Hello, I'm one of the few MangaDex@Home developers.

As was previously mentioned in the issue of tokens for MangaDex @ https://github.com/inorichi/tachiyomi-extensions/issues/3702#issuecomment-654348123, the `/report` endpoint is now stable enough to be implemented into Tachiyomi. As a general overview, the `/report` endpoint is used to report back to the backend on various metrics including the currently-serving node's availability. Currently, a good bulk of traffic from Tachiyomi to Mangadex goes unreported, which we would like to change, to allow the backend to more swiftly react to any network instability.

For network integrity and metrics, I hope this can be achieved as soon as possible. I would do it myself, but I'm no Tachiyomi developer :/. This should not take too much work, Neko has it already implemented at https://github.com/CarlosEsco/Neko/blob/278c6c89c5046d231ec9166684130bb59642575a/app/src/main/java/eu/kanade/tachiyomi/source/online/MangaDex.kt#L181

P.S: I think this counts as a [Feature Request]?

CC: @carbotaniuman

**Comment by arkon** [comment]
@CarlosEsco

**Comment by arkon** [comment]
> This should not take too much work

A bold assumption, to be sure.

@CarlosEsco has pointed out that regular extensions cannot override the `fetchImage` function, so we can't adopt the same approach as Neko.

We could potentially do this via a network interceptor based on URLs? Is there a standard format to the server URL prefixes? If so, we could check for that plus image extensions (e.g. URLs that end with `.jpg`, `.png`, etc.) to tell if something's a page. We could also potentially jankily set a header on the requests that we'd internally use within the extension just to flag something as a page (as opposed to a cover, for example).

**Comment by lflare** [comment]
> > This should not take too much work
> 
> A bold assumption, to be sure.
> 
> @CarlosEsco has pointed out that regular extensions cannot override the `fetchImage` function, so we can't adopt the same approach as Neko.
> 
> We could potentially do this via a network interceptor based on URLs? Is there a standard format to the server URL prefixes? If so, we could check for that plus image extensions (e.g. URLs that end with `.jpg`, `.png`, etc.) to tell if something's a page. We could also potentially jankily set a header on the requests that we'd internally use within the extension just to flag something as a page (as opposed to a cover, for example).

I am not entirely sure what you would require for successful implementation, but we do have a reference client implementation on the clients [GitLab](https://gitlab.com/mangadex-pub/mangadex_at_home/-/wikis/Formal-Specification-for-Custom-Clients#tokenized).

All our Mangadex@Home URLs always roll with the `https://{random_alphanumeric_string}.{random_alphanumeric_string}.mangadex.network` URL prefix.
