### ISSUE TITLE
[Bug] <WP MangaStream - Shea Manga>: <http error 400>

### ISSUE THREAD

**Issue by nizarschecter** [inorichi/tachiyomi-extensions#4643]
## Device information
- Tachiyomi version: 0.8.5
- Android version: 8.1.0

## Source information
- Name: WP MangaStream - Shea Manga
- Extension version: 1.2.26

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened

### Actual behavior
This happens instead

**Comment by Riztard** [comment]
it works for me READ this and try them all https://tachiyomi.org/help/guides/troubleshooting-problems/
first your app outdated
second your ext outdated
third fill form properly
