### ISSUE TITLE
[Bug] <Madara & WP MangaStream>: <extension cannot be installed>

### ISSUE THREAD

**Issue by nancysavchenkoo** [inorichi/tachiyomi-extensions#4647]
## Device information
- Tachiyomi version: 0.8.5
- Android version: 8.1.0

## Source information
- Name: Madara & WP MangaStream
- Extension version: madara (1.2.145) & WP MangaStream (1.2.28)

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
This should have happened

### Actual behavior
This happens instead

## Other details
extension cannot be installed

**Comment by scb261** [comment]
Update your app https://tachiyomi.org/download/

**Comment by nancysavchenkoo** [comment]
> Update your app https://tachiyomi.org/download/

still the same :(

**Comment by scb261** [comment]
Try to install from here https://tachiyomi.org/extensions/

**Comment by nancysavchenkoo** [comment]
> Try to install from here https://tachiyomi.org/extensions/

still the same sir :(

**Comment by scb261** [comment]
Try to install them with this https://play.google.com/store/apps/details?id=com.aefyr.sai&hl=en_US&gl=US
If it also won't help - tell what error it gives you

**Comment by arkon** [comment]
Try the suggested step above. If it still doesn't work, open an issue in the main repo.
