### ISSUE TITLE
[English] timelessleaf.com

### ISSUE THREAD

**Issue by thu2468** [inorichi/tachiyomi-extensions#467]
Site Request https://timelessleaf.com/
English

**Comment by thu2468** [comment]
So can anyone sdd this

**Comment by null-dev** [comment]
Should we even considering adding this? It doesn't even look like a source, more like just a blog-ish thing.

The format of the posts are not consistent either. E.g: https://timelessleaf.com/lan-chi-2/ . The first link contains multiple chapters and links to an external source. The rest of the links are properly done and link to images hosted on the blog itself.

**Comment by CarlosEsco** [comment]
Agree with null
