### ISSUE TITLE
[Source Request] BestManhua

### ISSUE THREAD

**Issue by Kzls** [inorichi/tachiyomi-extensions#4673]
## Source Website
- Name: Bestmanhua
- Link: https://bestmanhua.com/
- Language(s): English

## Other Details
Thanks for your work again ❤️

**Comment by joseph619** [comment]
This website just has 3 manhua, I am pretty sure you can find all these 3 manhua on any other site present currently.

**Comment by Kzls** [comment]
Absolutely not... And It's a shame. Exept MadCat who took The Supreme Emperor System they are only on youtube and youtube is shit :(...

**Comment by joseph619** [comment]
Clearly you didn't not look hard enough, all these 3 manhua are available on Manhuaus source in Madara. There is no point adding this source.

https://manhuaus.com/manga/trample-on-the-immortals-river/
https://manhuaus.com/manga/the-supreme-emperor-system/
https://manhuaus.com/manga/my-body-is-a-sword/

**Comment by Kzls** [comment]
Yes but Manhuaus is stealing the work of BestManhua and they are always behind them because if you steal you don't care if you go to the website 1 day or 2 day later for picking the newest chapter.

**Comment by joseph619** [comment]
Fair enough, we do allow original scanlation site
