### ISSUE TITLE
hatigarmscans http error

### ISSUE THREAD

**Issue by thu2468** [inorichi/tachiyomi-extensions#468]
Opening catalogfor hatigarmscans show a error. 
Dev version r1427

**Comment by arkon** [comment]
https://github.com/inorichi/tachiyomi-extensions/blob/5d669e79a3e00a37648141f3b5f109bac99156cc/src/all/foolslide/src/eu/kanade/tachiyomi/extension/en/foolslide/FoolSlideFactory.kt#L102

**Comment by arkon** [comment]
I think they've moved to WPManga?

**Comment by SnakeDoc83** [comment]
This can be closed, it's in mmrcms.
