### ISSUE TITLE
[Bug] <team1x1.com>: <page list is empty>

### ISSUE THREAD

**Issue by REDAKUN** [inorichi/tachiyomi-extensions#4686]
---

## Device information
- Tachiyomi version: ? 0.10.5
- Android version: ? 9

## Source information
- Name: ? team1x1.com
- Extension version: ? team1x1.com

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Manga load normally

### Actual behavior
Page not working or page list is empty

**Comment by arkon** [comment]
Can't reproduce. Open another issue if it's still persisting and provide actual steps to reproduce (specific manga, chapters, etc.).
