### ISSUE TITLE
[Bug] Dmzj: chapter list HTTP error 429

### ISSUE THREAD

**Issue by erinacio** [inorichi/tachiyomi-extensions#4687]
## Device information
- Tachiyomi version: v0.10.5
- Android version: 10

## Source information
- Name: Dmzj
- Extension version: 1.2.12

## Steps to reproduce
1. Refresh chapter list of manga (i.e. invoke manga chapter list api).

### Expected behavior
Works like before.

### Actual behavior
"HTTP error 429".

## Other details
Only chapter list api seems broken, latest updated manga list / manga searching / page list api all still seems working.

**Comment by scb261** [comment]
Works for me, any specific manga?

**Comment by CrepeTF** [comment]
Error 429 means "too many requests" it's client side, you're being rate limited by the website.

**Comment by erinacio** [comment]
> Works for me, any specific manga?

All mangas failed.

> Error 429 means "too many requests" it's client side, you're being rate limited by the website.

Changing IP by switching to cellular network doesn't solve this problem. Dmzj extension doesn't store any cookie AFAIK, so changing IP should be sufficient.

**Comment by erinacio** [comment]
Clearing cookies really works, although dmzj extension doesn't use cookies explicitly.

Maybe cookies are automatically handled by the extension framework, and local cookies contained some bad data that makes requests fail, during auto chapter updating. Issue closed.
