### ISSUE TITLE
[Bug] hitomi.la extension : i cant read or download chapters

### ISSUE THREAD

**Issue by dannygaray60** [inorichi/tachiyomi-extensions#4692]
## Device information
- Tachiyomi version: 0.10.15
- Android version: 7.1.1

## Source information
- Name: Hitomi.la
- Extension version: 1.2.3

## Steps to reproduce
1. read a chapter or download on spanish

### Expected behavior
This should have happened: load the spanish chapter or download

### Actual behavior
This happens instead: i got a message "retry" if i select download will never work

**Comment by arkon** [comment]
#4679
