### ISSUE TITLE
BUG Madara Extension Neox Scanlator.

### ISSUE THREAD

**Issue by fabriciobusiness** [inorichi/tachiyomi-extensions#4693]
Neox Scanlator dont show thumnails.
![Screenshot_20201023-001247_Tachiyomi](https://user-images.githubusercontent.com/48425465/96952168-915f0080-14c4-11eb-955d-6e4e0d05ee7d.jpg)

**Comment by scb261** [comment]
Works for me, try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/)

**Comment by Riztard** [comment]
work for me as well, should be closed
