### ISSUE TITLE
Webtoon - Fan translation

### ISSUE THREAD

**Issue by MartassCZ** [inorichi/tachiyomi-extensions#471]
Hello, Sorry if i post it in the wrong place, but would be possible to add function, that i could read fan translation from webtoons?

**Comment by CarlosEsco** [comment]
I'm not familiar with webtoon what is fan translation?

**Comment by MartassCZ** [comment]
webtoon is site where you can read webtoon with original translate, or you can read it with fan translation in your language, so if you are from Germany, and someone from fans translate it to German, you can read it in German.
