### ISSUE TITLE
[Bug] MANGA Plus by SHUEISHA: Can't access or update manga

### ISSUE THREAD

**Issue by Presac** [inorichi/tachiyomi-extensions#4722]
## Device information
App version: 0.10.5-2790 (standard, 832a4fa6, 51)
Android version: 5.1.1 (SDK 22)
Android build ID: LMY47X.P600XXSDRI1
Device brand: samsung
Device manufacturer: samsung
Device name: lt03wifi
Device model: SM-P600
Device product name: lt03wifixx 

## Source information
- Name: MANGA Plus by SHUEISHA
- Extension version: 1.2.13

## Steps to reproduce
Updating from the library screen

### Expected behavior
The titles should update with new chapters

### Actual behavior
Getting "An unknown field for index 868357376" for every title

## Other details
When trying to access a chapter, I instead get "An unknown field for index 1997694816" for every title. 
The extension works fine in the stable release installed on the device.

**Comment by ChrRubin** [comment]
I'm having the same issue.

Updated to Preview r2804 and the error message changed to the following:
![error](https://cdn.discordapp.com/attachments/349436576037732355/772883692594004009/IMG_20201103_020146.png)

My Android version is 6.0.1. I can also confirm the same extension works fine on stable v0.10.5.

**Comment by Presac** [comment]
Updated to Preview r2804 and get that same message now too.

**Comment by alessandrojean** [comment]
It's probably related to the Android version, since I am not able to reproduce this issue on my Android 9 phone. I will take a look and try to fix, but I can't promise anything.

**Comment by Presac** [comment]
It works now. Thanks for the fix.
