### ISSUE TITLE
[Bug] <Bato.to>: Duplicate entries

### ISSUE THREAD

**Issue by sam7028** [inorichi/tachiyomi-extensions#4724]
### Device Information

Tachiyomi version: stable 0.10.5
Android version: 10

### Source information

Name: Emerald (bato.to)
Extension Version: 1.2.4

### Steps to reproduce   

- Open Bato.to

- Search for any manga

### Expected Behavior

There should not be Duplicate entries

### Actual Behavior

There are multiple duplicate entries

**Comment by scb261** [comment]
The site has duplicates, so it's not app's or extension's fault. Example https://bato.to/search?word=horimiya 
1) it has duplicates for the same language (English for example: [one](https://bato.to/series/12339), [two](https://bato.to/series/21251), [three](https://bato.to/series/23203) and there is more)
2) it doesn't allow filtering when searching by text, so you'll also see entries with different languages
