### ISSUE TITLE
[Source Request] <SK Scans>

### ISSUE THREAD

**Issue by piecewalk** [inorichi/tachiyomi-extensions#4729]
- Name: Sk Scans
- Link: https://skscans.com/home
- Language(s): English

## Other Details
Using same layout as Genkan (multiple sources)

**Comment by CrepeTF** [comment]
Already exists in Genkan.
They're called Sleeping Knight Scans

**Comment by piecewalk** [comment]
@CrepeTF Never know what meaning of SK is. Anyways thanks for reply.
