### ISSUE TITLE
[Bug] <My Manga Reader CMS: MangaYu>: <HTTP error 404>

### ISSUE THREAD

**Issue by HaruSasaki** [inorichi/tachiyomi-extensions#4738]
## Device information
- Tachiyomi version: Stable 0.10.5
- Android version: 8.1.0

## Source information
- Name: MangaYu in My Manga Reader CMS
- Extension version: 1.2.51

## Other details
![Screenshot_20201029-040630](https://user-images.githubusercontent.com/73406832/97497594-54e84480-199d-11eb-9dc5-0a5df807ae7b.png)

Work fine in webview…

**Comment by Riztard** [comment]
i think they change theme
