### ISSUE TITLE
[Source Request] <Yaoi Toshokan>

### ISSUE THREAD

**Issue by scorbies** [inorichi/tachiyomi-extensions#4741]
## Source Website
- Name: Yaoi Toshokan 
- Link: https://www.yaoitoshokan.com.br
- Language: portuguese

## Other Details
yaoi source

**Comment by scb261** [comment]
Already exists, check [the sheet for multi-source extensions](https://tachiyomi.org/extensions-spreadsheet) next time
https://github.com/inorichi/tachiyomi-extensions/blob/d4cc20335a89d16fe415c9746bd93ed7a75e9e5a/src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt#L793
