### ISSUE TITLE
[Feature Request] MangaDex: Add 'on cellular' option to data saver

### ISSUE THREAD

**Issue by ClammyMantis488** [inorichi/tachiyomi-extensions#4742]
## What feature should be added to this source?
The ability for the extension to automatically switch to data saver when using cell data and turn off data saver when back on wifi.

**Comment by arkon** [comment]
That kind of device information isn't available to extensions and it's not really worth the effort to modify the app to allow for that sort of usecase given it being pretty niche and competing priorities.
