### ISSUE TITLE
[Source Request] GetComics

### ISSUE THREAD

**Issue by alfaazian** [inorichi/tachiyomi-extensions#4743]
## Source Website
- Name: GetComics
- Link: getcomics.info
- Language(s): English

**Comment by scb261** [comment]
See #906, when you click *Read online*, it just redirects to readcomicsonline.ru that already exists in *My Manga Reader CMS*
https://github.com/inorichi/tachiyomi-extensions/blob/016653bdc0f0da500819437d2698af4d4c1aacf7/src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/Generator.kt#L237
