### ISSUE TITLE
[Source Request] <LoveHeaven>

### ISSUE THREAD

**Issue by dingdonng22** [inorichi/tachiyomi-extensions#4748]
## Source Website
- Name: LoveHeaven
- Link: https://loveheaven.net/
- Language(s): JP

## Other Details
Uploads Japanese manga raw.

**Comment by scb261** [comment]
Already exists, check [the sheet for multi-source extensions](https://tachiyomi.org/extensions-spreadsheet) next time
https://github.com/inorichi/tachiyomi-extensions/blob/016653bdc0f0da500819437d2698af4d4c1aacf7/src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt#L94
