### ISSUE TITLE
mangaid.me

### ISSUE THREAD

**Issue by einstein95** [inorichi/tachiyomi-extensions#475]
https://mangaid.me

Was a part of CMS as mangaid.co, but has now gone to use wp-manga. This may not work with the current implementation by @CarlosEsco as it is currently, as a couple things are different.

Most popular page is `https://mangaid.me/daftar-manga/?order=popular`.
Searching is `https://mangaid.me/?s=<query>&post_type=manga`, not `post_type=wp-manga` as the latter gives the chapters and not manga.

**Comment by wand09** [comment]
Will there be an improvement?

**Comment by arkon** [comment]
Seems to be dead.

**Comment by einstein95** [comment]
Server is returning 404 which is odd if they're dead. I'd give them a week.

**Comment by arkon** [comment]
Still seems dead. Feel free to reopen this if they ever come back online.
