### ISSUE TITLE
[Bug] No Title in new manga

### ISSUE THREAD

**Issue by Gungperd** [inorichi/tachiyomi-extensions#4753]
![Screenshot_2020-10-31-17-04-05-129_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/72451318/97775820-998efe00-1b9e-11eb-99ca-25e53d002d42.jpg)

No title in new manga from Hent2read

**Comment by AriaMoradi** [comment]
I can't reproduce this, also i checked the code and selectors are fine, this is the exact same manga
![Screenshot_20201111-003345_Tachiyomi](https://user-images.githubusercontent.com/8719233/98733467-cbca0800-23b5-11eb-8451-b6fa011901ab.jpg)

**Comment by AriaMoradi** [comment]
I think this can be closed, It must have been a netwok issue and not connected to the app.
