### ISSUE TITLE
[Source Request] <Tappytoon>

### ISSUE THREAD

**Issue by seaharbour** [inorichi/tachiyomi-extensions#4764]
## Tappytoon
- Name: Tappytoon
- Link: https://www.tappytoon.com
- Language(s): English, French, Dutch

**Comment by CrepeTF** [comment]
Duplicate of [#1342](https://github.com/inorichi/tachiyomi-extensions/issues/1342)

**Comment by seaharbour** [comment]
What do I do with the icons?

**Comment by Soitora** [comment]
> What do I do with the icons?

They're for the source request, not for you.

**Comment by Osama-Ezz** [comment]
> Duplicate of [#1342](https://github.com/inorichi/tachiyomi-extensions/issues/1342)

If you want me to remove it i will do it.
