### ISSUE TITLE
[Bug]Tsuki-mangás appearing message JSON

### ISSUE THREAD

**Issue by joao917** [inorichi/tachiyomi-extensions#4768]
## Device information
* Tachiyomi version: 0.10.5
* Android version: 10

## Source information
* Source name: Tsuki Mangás (PT-BR)
* Source extension version: 1.2.2

## Steps to reproduce
1. open the extension
2. open any manga

## Upon opening the message appears
Not a JSON Array:{"manga":
[{"RELACIONADOS":"","IDANILIS":"0"
IDMAL":"0","CAPITULOS":27,'VIEWS":
745,"NOTAS":"8.3","TOTALNOTAS":"
3","CAPA":"the-red-king.jpg","ID":
585,"ARTISTA":"Heylenne","AUTOR
27 ca":"Heylenne","GENEROS":"Aventura,
Fantasia, Mistério","SINOPSE":"Ser
jovem, rico e bonito nem sempre lhe traz
Cop. felicidade. Pergunte a Ivan, a ovelha
22/09 negra de sua família
. Se ele não estivesse
ocupado bebendo, festejando e sendo
um verdadeiro desastre, ele poderia
COD. 2 estar construindo uma carreira no vasto
31/07 negócio de seu pai. Como se a volátil
dinâmica familiar de Ivan não pudesse
piorar, ele acidentalmente ajuda uma
Cop. 2 entidade sobrenatural a roubar um
25/07 segredo que poderia afundar todo o seu
império corporativo.","STATUS":"Hiato
"I'TITULO":"The Red King","TITULOA":"
COD. 21URL":"the-red-king":"URLCAPA":"the
21/07/-red-king-capa.jpg"}]"relacionado”:
[]}
![Screenshot_20201102-123148_Tachiyomi](https://user-images.githubusercontent.com/69521431/97913844-af7ef900-1d2d-11eb-8807-bbba397fd133.jpg)

**Comment by alessandrojean** [comment]
I will take a look.
