### ISSUE TITLE
[Bug] <WP Manga Stream: Kaisar Komik>: <Unterminated Object>

### ISSUE THREAD

**Issue by HaruSasaki** [inorichi/tachiyomi-extensions#4771]
## Device information
- Tachiyomi version: Stable 0.10.5
- Android version: 8.1.0

## Source information
- Name: Kaisar Komik from WP Manga Stream extension
- Extension version: 1.2.31

### Expected behavior
Can read manga

### Actual behavior
Can't read manga

## Other details
![Screenshot_20201103-043319](https://user-images.githubusercontent.com/73406832/97923010-ed146e00-1d8f-11eb-92b7-5816c8d9a8ed.png)

I think is not valid.

In picture looks like this:
[{
		"@type": "ReadAction",
		"target": ["https://kaisarkomik.com/to-be-the-castellan-king-chapter-225-bahasa-indonesia/"]

I thought it should be like this:
[{
	"@type": "ReadAction",
	"target": ["https://kaisarkomik.com/to-be-the-castellan-king-chapter-225-bahasa-indonesia/"]
}]

**Comment by Riztard** [comment]
its not happening on all chapter, some chapter work just fine
