### ISSUE TITLE
[Bug] <Madara : Wakascan [FR]>: <Impossible to bypass Cloudflare>

### ISSUE THREAD

**Issue by Zealest** [inorichi/tachiyomi-extensions#4774]
## Device information
- Tachiyomi version: Preview r2804
- Android version: 10 | crDroid 6.7

## Source information
- Name: Wakascan [FR] in Madara (multiple sources) ext.
- Extension version: 1.2.149

## Steps to reproduce
Open the extension then see what happens.

### Expected behavior
The manga of the extension should display correctly as well as the chapters of the manga already present in our library.

### Actual behavior
The extension doesn't even load there's a Cloudflare error and it's the same thing when I try to read a chapter of a manga from the Wakascan extension already present in my library.

## Other détails
I don't use any VPN // AdAway // Adguard or anything.

**Comment by scb261** [comment]
Open the source in [webview](https://tachiyomi.org/help/guides/troubleshooting-problems/#solving-a-captcha) to bypass the cloudflare

**Comment by Zealest** [comment]
it worked!! tysm for the tip
