### ISSUE TITLE
[Source Request] <مانجا العاشق>

### ISSUE THREAD

**Issue by Holy2D** [inorichi/tachiyomi-extensions#4778]
## Source Website
- Name: مانجا العاشق
- Link: https://3asq.org/
- Language(s): Arabic

**Comment by scb261** [comment]
Already exists, check [the sheet for multi-source extensions](https://tachiyomi.org/extensions-spreadsheet) next time
https://github.com/inorichi/tachiyomi-extensions/blob/d4cc20335a89d16fe415c9746bd93ed7a75e9e5a/src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt#L426
