### ISSUE TITLE
[Bug] <Hitomi.la>: <Error loading the chapter>

### ISSUE THREAD

**Issue by boybeast** [inorichi/tachiyomi-extensions#4780]
# Device information
  - Tachiyomi version: 0.10.5
  - Android version: 10

  ## Source of information
  - Name: Hitomi.la
  - Extension version: 1.2.3

  ## Steps to reproduce
  1. Open the Hitomi.la extension (any language, especially those that have been tested) and select the title of your choice
  2. After selecting, choose the chapter and open the reader

  ### Expected behavior
  -the images should load

  ### Real behavior
  - "try again" appears and the image does not load

  ## Other details
- when opening the title in the browser, the gallery loads normally
- the site apparently updated your reader which caused the error to occur in almost all titles in all languages
- even installing the app from scratch on a new device the error persists
- and  the app updates the titles normally but does not load your galleries
-I tested the following galleries: Japanese, English, Portuguese, Spanish and Chinese and they all presented the same error

**Comment by arkon** [comment]
#4679
