### ISSUE TITLE
[Feature Request] <wherever it may apply>: <Sauce numbers in the search>

### ISSUE THREAD

**Issue by Kzitold** [inorichi/tachiyomi-extensions#4784]
Wanna get to a manga/doujin by its number.

```
mangadex.org/title/<sauce>
tsumino.com/entry/<sauce>
```
`nhentai.net/g/<sauce>`, but nhentai already done this feature themselves.

**Comment by scb261** [comment]
On both mangadex and tsumino you can search *id:number*

**Comment by Kzitold** [comment]
> On both mangadex and tsumino you can search _id:number_

I never knew that.
