### ISSUE TITLE
[Bug] <Bato.to>: <No Pages Found>

### ISSUE THREAD

**Issue by OmarH2** [inorichi/tachiyomi-extensions#4796]
## Device information
- Tachiyomi version: App version: 0.10.5-2804 (standard, 6675508b, 51)
- Android version: 10 (SDK 29)

## Source information
- Name: Bato
- Extension version: emerald 1.2.4

Can't open any chapters, says "No Pages Found".

**Comment by Riztard** [comment]
have you logged in? if NO, next time try [troubleshoot ](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis)first 
![image](https://user-images.githubusercontent.com/16263232/98235559-5ebb0a80-1f90-11eb-9eb0-87dfa5be92bf.png)

**Comment by joseph619** [comment]
This is also not a bug, it's a temporary website issue. Ticket should be closed.
