### ISSUE TITLE
DNS

### ISSUE THREAD

**Issue by AgWln** [inorichi/tachiyomi-extensions#4806]
## Device information
* Tachiyomi version: 0.10.5
* Android version: Android 10
* Device: Samsung Galaxy 6+

## Issue/Request
DNS
## Other details
when I use DNS, my network sometimes gets lost. I don't know why since using DNS over https (Cloudflare) the network sometimes disappears by itself, even though I've turned off DNS, the network also sometimes disappears

**Comment by scb261** [comment]
> even though I've turned off DNS, the network also sometimes disappears

So, *DNS over HTTPS* isn't the problem. It looks like the problem is with your connection, not the app.

Also, wrong repository, this one is for source bugs/requests. Next time use https://github.com/inorichi/tachiyomi for issues that aren't related to a source

**Comment by AgWln** [comment]
Thanks for info
