### ISSUE TITLE
[Source Request] Centinni

### ISSUE THREAD

**Issue by sam7028** [inorichi/tachiyomi-extensions#4813]
### Source Website

Name: Centinni

Link: https://www.centinni.com/novel-genre/manhua

Language(s): English

**Comment by CrepeTF** [comment]
Madara novel site
:Harold:

**Comment by sam7028** [comment]
Mostly novels, but they do have some manhwa

**Comment by RealKC** [comment]
Does this one madara website offer a single manhwa not available in the 150+ websites available in the Madara extension

**Comment by AbdullahM0hamed** [comment]
0 chance of that lol

**Comment by arkon** [comment]
Please reopen if there isn't actually another site that doesn't have the same content.
