### ISSUE TITLE
zero scans

### ISSUE THREAD

**Issue by jimbob1986** [inorichi/tachiyomi-extensions#482]
zero scan page list empty
wpmanga is the source

**Comment by briaeros** [comment]
I have the same problem with this site.
What I don't understand is that the parser seems ok.
The page list (for example : https://zeroscans.com/manga/peerless-alchemist/chapter-38/?style=list ) give us a list of page-break, so pageListParse must works.: 


`<div class="page-break">
           <img id="image-1" src="https://zeroscans.com/wp-content/uploads/WP-manga/data/manga_5ade6d6fdc399/chapter-38/0Credits.png" class="wp-manga-chapter-img">
        </div>`

`<div class="page-break">
           <img id="image-2" src="https://zeroscans.com/wp-content/uploads/WP-manga/data/manga_5ade6d6fdc399/chapter-38/0message.png" class="wp-manga-chapter-img">
       </div>`

`<div class="page-break">
            <img id="image-3" src="https://zeroscans.com/wp-content/uploads/WP-manga/data/manga_5ade6d6fdc399/chapter-38/01.png" class="wp-manga-chapter-img">
       </div>`


I've tried to get the page with another user-agent , but I've got no trouble.
Except for ident, I see no difference with the trashscanlations.com site (which works).

So I don't understand why the parser doesn't work anymore.

**Comment by bbtora** [comment]
Yup, having the same problem here.

**Comment by tblader** [comment]
S a m e
