### ISSUE TITLE
[Source Request] <HanaScan> & <Mangairo>

### ISSUE THREAD

**Issue by comizomi** [inorichi/tachiyomi-extensions#4825]
- Name: HanaScan
- Link: https://hanascan.com/
- Language(s): Japanese

-Name: Mangairo
-Link: https://h.mangairo.com/
-Language(s): English

**Comment by CrepeTF** [comment]
- Only 1 Source Request per issue
- Both sources already exist, check spreadsheet[Spreadsheet](https://tachiyomi.org/extensions-spreadsheet)
