### ISSUE TITLE
[Bug] <Zahard>: <URL Change/404>

### ISSUE THREAD

**Issue by sshawnsamuell** [inorichi/tachiyomi-extensions#4829]
## Device information
- Tachiyomi version: 10.5
- Android version: 10

## Source information
- Name: Zahard
- Extension version: 1.2.1

## Other details
URL is different.
Zahard.win is now zahard.top

**Comment by sshawnsamuell** [comment]
Updated to 1.2.2, series are all showing up, but chapters do not pull up. Gives error, "For Input String: Chapter ##" " (## being whatever the latest chapter for that series is) 
![Screenshot_20201111-130526](https://user-images.githubusercontent.com/1341030/98848368-a1149980-241f-11eb-93b4-19736730b1b2.jpg)

**Comment by AriaMoradi** [comment]
@sshawnsamuell open a new issue please
