### ISSUE TITLE
[Bug] PM Scans: HTTP Error 400

### ISSUE THREAD

**Issue by sam7028** [inorichi/tachiyomi-extensions#4830]
### Device information

Tachiyomi version: 0.10.5
Android version: 10
### Source information

Name: PM Scans / Madara (multiple sources)
Extension version: 1.2.150
### Steps to reproduce

- Go to "Browse" tab

- Click on "PM Scans" 

### Expected behavior

Show all manga from this source.

### Actual behavior

Shows a message saying "HTTP error 400: check website in WebView".

**Comment by CrepeTF** [comment]
Webview seems to be having trouble with the website

**Comment by Matakor** [comment]
I can open it in webview, but it is slow to pick up. Still 400 on the extension browse page though.
