### ISSUE TITLE
[Bug] The Property of Hate: needs icons

### ISSUE THREAD

**Issue by AriaMoradi** [inorichi/tachiyomi-extensions#4838]
The extension needs icons. I used the one from Kill Six Billion Demons.

**Comment by CarlosEsco** [comment]
Why didnt you say that when you took WIP off...  @as280093  Can you whip something up?

**Comment by AriaMoradi** [comment]
@as280093
just mentioning your name, if you want to make icons for this.

**Comment by AriaMoradi** [comment]
> Why didnt you say that when you took WIP off... @as280093 Can you whip something up?

sorry, I forgot...

**Comment by as280093** [comment]
On it

**Comment by CarlosEsco** [comment]
@AriaMoradi open a new pull request after the icons are attached here.

**Comment by AriaMoradi** [comment]
We also could provide a nice cover for the comic entry
Here is the current cover
![](https://dummyimage.com/768x994/000/ffffff.jpg&text=The%20Property%20of%20Hate)

I found these two on the net
![](https://images.smackjeeves.com/legacy/title/x/j/xjf869ei7Cr0W.jpg)
![](https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1528065952l/40365695._SX318_.jpg)

what's your opinions?

**Comment by AriaMoradi** [comment]
also the first page of the first chapter
![](http://jolleycomics.com/comics/tpoh_547dfae6a2683.jpg)

**Comment by as280093** [comment]
@AriaMoradi  Here

[ic_launcher .zip](https://github.com/inorichi/tachiyomi-extensions/files/5519534/ic_launcher.1.zip)

**Comment by AriaMoradi** [comment]
![](https://pbs.twimg.com/media/DOBCcMiWkAA8Hvu.jpg)
I'm going with this

**Comment by AriaMoradi** [comment]
@as280093 the icon is really cool I must say
