### ISSUE TITLE
[Bug] is traviscibot broken?

### ISSUE THREAD

**Issue by AriaMoradi** [inorichi/tachiyomi-extensions#4840]
last update to the repo branch was 2 days ago and a bunch of extensions are updated... 
I'm opening this since I assume it is automatic

**Comment by arkon** [comment]
https://travis-ci.org/github/inorichi/tachiyomi-extensions/builds

**Comment by AriaMoradi** [comment]
it's just busy huh?

**Comment by arkon** [comment]
Yes: https://www.traviscistatus.com/#month

I'll migrate it off of Travis by EOY.
