### ISSUE TITLE
[Feature Request] Zahard: latest manga

### ISSUE THREAD

**Issue by AriaMoradi** [inorichi/tachiyomi-extensions#4847]
## What feature should be added to this source?
building upon #4846, It's possible to implement a half broken latest manga feature.

on `https://zahard.top/fastpass?page={pageNum}` the site puts the last added chapters, it's possible to scrape the chapters, filter out the duplicates and get a list of manga names and manga thumbnail_urls. but to get the manga url we need to scrape the chapter url too. 

It's going to be a request-heavy feature but should work.

**Comment by AriaMoradi** [comment]
opinions everyone?
@arkon

**Comment by arkon** [comment]
They don't even have that many series, it's fine if there's no latest section.

**Comment by AriaMoradi** [comment]
> They don't even have that many series, it's fine if there's no latest section.

It's because (from what i gather) they rebooted the site
