### ISSUE TITLE
[Source Request] <3asq>

### ISSUE THREAD

**Issue by isoo224** [inorichi/tachiyomi-extensions#4853]
## Source Website
- Name: 3asq
- Link: https://3asq.org/
- Language(s): Arabic 

## Other Details
please someone do it all the extensions for Arabic are not working or olny have like 30manga which is really sucks so please 🙇‍♂️🙇‍♂️🙇‍♂️

**Comment by scb261** [comment]
Already exists, check [the sheet for multi-source extensions](https://tachiyomi.org/extensions-spreadsheet) next time

https://github.com/inorichi/tachiyomi-extensions/blob/950e2a67ebeff2c151b513a18cc1a5a248a82f4e/src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt#L441
