### ISSUE TITLE
[Bug] Gufengmh: All chapter failed to load & download

### ISSUE THREAD

**Issue by black-999** [inorichi/tachiyomi-extensions#4854]
## Device information
- Tachiyomi version: 10.5
- Android version: Android 11

## Source information
- Name: Gu feng mh
- Extension version: 1.2.3

## Steps to reproduce
1. First Step
Open any manhua in gu feng
2. Second Step
Click on any chapter. then all not failed to load

### Expected behavior
All pages should be able to load & download

### Actual behavior
Not able to load at any pages. all failed to load the image, and show `retry`
download also fail.

**Comment by scb261** [comment]
Pages are broken on the site itself

**Comment by black-999** [comment]
> Pages are broken on the site itself

That is weird. the m site seem working for me. https://m.gufengmh8.com/manhua/henchunhenaimei/83432-2.html

**Comment by scb261** [comment]
The page you sent doesn't work for me. Are you sure you can see the image?
![1](https://user-images.githubusercontent.com/65343233/99065006-6a6d8900-25af-11eb-9489-24864e7c4584.png)

**Comment by black-999** [comment]
I try again on phone webview, no longer working. 
only left laptop chrome (incognito) is working. so weird, they are using same network.
<img width="1435" alt="Screenshot 2020-11-13 at 8 31 33 PM" src="https://user-images.githubusercontent.com/74367596/99074088-1932b900-25f2-11eb-8372-84a50b783df4.png">

**Comment by scb261** [comment]
It doesn't for me in both webview and browser, maybe it's cached in your browser
