### ISSUE TITLE
Kiryuu Extension Problem.

### ISSUE THREAD

**Issue by ReyVnD** [inorichi/tachiyomi-extensions#4861]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.5)
- I have updated all extensions
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/inorichi/tachiyomi
- I have searched the existing issues for duplicates
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions/

---

## Device information
* Tachiyomi version: 0.10.5
* Android version: 10
* Device: Xiaomi MI 8

## Source information
* Source name: Kiryuu
* Source extension version: 1.2.2

## Steps to reproduce
1. Search Manga in Kiryuu Extension
2. Open The Manga

## Issue/Request
Couldn't see The Manga Chapter List

## Other details
Additional details and attachments.
![Screenshot_2020-11-13-18-56-31-687_eu kanade tachiyomi](https://user-images.githubusercontent.com/70132787/99065530-7cb4ea80-25e2-11eb-82e5-aebb03a670bf.jpg)

**Comment by Riztard** [comment]
@ReyVnD just use the one from WP MangaStream Extension.
pake yang di ekstensi lean aja gan tinggal migrate

**Comment by ReyVnD** [comment]
> @ReyVnD just use the one from WP MangaStream Extension.
> pake yang di ekstensi(WP MangaStream) laen aja gan tinggal migrate, kiryuu juga

Thx infonya gan.

**Comment by ReyVnD** [comment]
> @ReyVnD just use the one from WP MangaStream Extension.
> pake yang di ekstensi(WP MangaStream) laen aja gan tinggal migrate, kiryuu juga

**Comment by ReyVnD** [comment]
> @ReyVnD just use the one from WP MangaStream Extension.
> pake yang di ekstensi(WP MangaStream) laen aja gan tinggal migrate, kiryuu juga

Thx infonya gan.
