### ISSUE TITLE
[Bug] Emerald: Search results looped

### ISSUE THREAD

**Issue by jadoff630** [inorichi/tachiyomi-extensions#4872]
## Device information
- Tachiyomi version: Preview r306 (6e8ac9cc1)
- Android version: 10

## Source information
- Name: Emerald
- Extension version: 1.2.6

## Steps to reproduce
Search results loop continually
1. Search for a title, for instance "A Villainess for a Tyrant"
2. Bato.to has 20 results that match this
3. After these 20 results, bato.to repeats the same results continually

### Expected behavior
Search results should show results then be done. 

### Actual behavior
As step 3 in Steps to reproduce says, results repeat themselves instead of ending. See video for example. https://vimeo.com/478642022

**Comment by AriaMoradi** [comment]
this is caused by `Emerald.kt` line 146, the query string for page is not passed

**Comment by jadoff630** [comment]
> this is caused by `Emerald.kt` line 146, the query string for page is not passed

Is there a fix for that?
