### ISSUE TITLE
[Feature Request] <delete Team X

### ISSUE THREAD

**Issue by otaku4ever** [inorichi/tachiyomi-extensions#4875]
Plz just delete www.team1x1.com from yours links and we will thankfull

**Comment by CarlosEsco** [comment]
done#4877

**Comment by Bm12347** [comment]
It seems like you are the owner of team x
I'm sorry 😞 😐 for any inconvenience
I've caused you
I found out that it wasn't working well so I reported it
Please don't take it seriously
Again I'm sorry my friend

**Comment by Bm12347** [comment]
And I'm also sorry to say that your hopes of seeing gmanga extension are slim because it seems quite hard
As that issue is opened since 2017
