### ISSUE TITLE
[Source Request] <mangasco.com>

### ISSUE THREAD

**Issue by monMusu** [inorichi/tachiyomi-extensions#4880]
## Source Website
- Name: **MANGASCO**
- Link: https://mangasco.com
- Language(s): English

## Other Details

**A clean and neat Manga site. Please add this to Tachiyomi.** 
![DG7kXrL1cR](https://user-images.githubusercontent.com/70755549/99156741-71001b80-26e9-11eb-8aff-4a1fbe2b0715.png)

**Comment by scb261** [comment]
I doubt it has something unique to other madara sources 
![1](https://user-images.githubusercontent.com/65343233/99156907-9da63a00-26cd-11eb-9cc0-5cff4c217086.png)

**Comment by monMusu** [comment]
> I doubt it has something unique to other madara sources
It always good to have more choices for sources to either migrate or browse because every now and then sites go kaput because of DMCA.  The latest being Readcomiconline.org.

**Comment by joseph619** [comment]
There are over 200 Madara sources, no need to worry about them being taken down.
