### ISSUE TITLE
[Bug] Mangabat: url changed to https://m.mangabat.com/homepage, slow to load chapters

### ISSUE THREAD

**Issue by miakiat** [inorichi/tachiyomi-extensions#4885]
## Device information
* Tachiyomi version: 0.10.5
* Android version: 9

## Source information
* Source name: mangabox
* Source extension version: 1.2.24

## Steps to reproduce
1. Select a chapter or search manga

## Issue/Request
Mangabat change URL: https://m.mangabat.com/homepage
Slow to load. Probably due to slow redirect to new URL.

**Comment by Riztard** [comment]
work just fine for me, try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis)

**Comment by miakiat** [comment]
I tried clearing cache, cookies and database. And swapping to DNS over HTTPS.

When loading a manga for the first time, it takes a long time to load. However, pressing back and reselecting the same chapter will load it quickly as per usual. Subsequent chapters will also load fast. Other mangas also load fast after the first manga loaded.

I suspect that clearing the cache/cookies might have reset the website redirect causing Tachiyomi to get stuck pulling the manga. However, after that it's fine.

I will continue to do more test on other devices as well to make sure it's not just mine.

**Comment by miakiat** [comment]
I've tested on other device and it seems to work fine. Looks like it's specific to my device. It's just a minor issue so I think we can close this.
