### ISSUE TITLE
[Bug] hentainexus: cannot load pages, stuck on retry

### ISSUE THREAD

**Issue by bugreportanon** [inorichi/tachiyomi-extensions#4888]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 10

## Source information
- Name: hentainexus
- Extension version: 1.2.3

## Steps to reproduce
1. Add the english version of
* Automatic Girl
* The Inari Deity
* Ghost Girl's Wish
to the library
2. Attempt to read chapter
3. Entire chapter is stuck on "retry" screen with no pages loading

### Expected behavior
Pages should load and chapter is readable.

### Actual behavior
Entire chapter is stuck on "retry", pages refuses to load.

## Other details
I don't know if this is the same as #4679 but this happened to me recently, the pages load fine on the web but seems to be broken with the extension. This seems to have affected every manga on hentainexus, not sure what's wrong.

**Comment by montesat** [comment]
This is also happening on mangapark and mangahere extensions, with exact behavior as reported above.

**Comment by scb261** [comment]
@montesat mangapark and mangahere are unrelated to hentainexus. I just checked and both mangahere and mangapark work fine for me. Try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/) first, and if it won't help - create new issue and specify what manga/chapters you have problem with.

**Comment by zaydendavis69** [comment]
I’ve been having this issue as well. Everything loads in webview but I get the same retry error when trying to load normally.

**Comment by kevin01523** [comment]
Same with me it has the expected https or http but no colon was found error if i try to download

**Comment by k7rie** [comment]
Same issue here. I just want to fap pls

**Comment by MoistSac** [comment]
Welp, they changed it again. I don't think this kind of cat-and-mouse is going to be useful.

**Comment by Aaaaa020** [comment]
Same here can't open the web

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/3475

**Comment by Aaaaa020** [comment]
Why hentainexus web cant open

**Comment by CarlosEsco** [comment]
we are not supporting this extension anymore.  read the issue i previously sent.
