### ISSUE TITLE
[Source Request] Webtoon.XYZ

### ISSUE THREAD

**Issue by Sorex25** [inorichi/tachiyomi-extensions#4889]
---

## Source Website
- Name: Webtoon.XYZ 
- Link: webtoon.xyz
- Language(s): English

## Other Details
Manhwas containing mature content, updates fast than any other ones. Not affiliated with the original Webtoon site.

**Comment by CarlosEsco** [comment]
please search the repo before asking. Its in Madara

https://github.com/inorichi/tachiyomi-extensions/search?q=webtoon.xyz
