### ISSUE TITLE
[Bug] <HentaiNexus>: <Can't Load Images and Pages>

### ISSUE THREAD

**Issue by S-eann** [inorichi/tachiyomi-extensions#4897]
I saw this issue back in Mar 31, but now it's now closed so I think I can post this now. The extension itself looks fine at first and it still updates its content, but when I click on one and try to read it, it doesn't load and I also can't download the content because it says there is an error.
![Screenshot_2020-11-20-19-39-19-19](https://user-images.githubusercontent.com/74749485/99796340-463e1900-2b68-11eb-913a-9960b4a2fd1f.jpg)
Yesterday it was fine, but now I can't even open one.

**Comment by S-eann** [comment]
> I saw this issue back in Mar 31, but now it's now closed so I think I can post this now. The extension itself looks fine at first and it still updates its content, but when I click on one and try to read it, it doesn't load and I also can't download the content because it says there is an error.
> ![Screenshot_2020-11-20-19-39-19-19](https://user-images.githubusercontent.com/74749485/99796340-463e1900-2b68-11eb-913a-9960b4a2fd1f.jpg)
> Yesterday it was fine, but now I can't even open one.

If anyone knows a way to fix it please tell me.

**Comment by scb261** [comment]
Duplicate of #4888
