### ISSUE TITLE
Problema com a extençao do tsuki mangas

### ISSUE THREAD

**Issue by GODDEATH1** [inorichi/tachiyomi-extensions#4898]
Ao tentar abrir um capítulo de um mangá no tsuki mangas , o capítulo não carrega
![Capture+_2020-11-20-16-01-33](https://user-images.githubusercontent.com/74791666/99839581-b7220880-2b49-11eb-8d6e-fb55c7763c27.png)

**Comment by joao917** [comment]
Ainda não resolveu ;-;

**Comment by alessandrojean** [comment]
Eu mandei um PR com uma nova atualização agora pouco que deve resolver (precisa esperar ela ser aceita ainda), mas não sei por quanto tempo vai durar. Se depois disso eles alterarem algo no site de novo e a extensão parar de funcionar, significa que eles estão tentando querer bloquear aplicativos como o Tachiyomi de ler o conteúdo no site deles, então não tem muito o que fazer neste caso, só migrar para uma outra fonte mesmo.

**Comment by joao917** [comment]
> Eu mandei um PR (#4907) com uma nova atualização agora pouco que deve resolver (precisa esperar ela ser aceita ainda), mas não sei por quanto tempo vai durar. Se depois disso eles alterarem algo no site de novo e a extensão parar de funcionar, significa que eles estão tentando querer bloquear aplicativos como o Tachiyomi de ler o conteúdo no site deles, então não tem muito o que fazer neste caso, só migrar para uma outra fonte mesmo.

Blz, vlw tu é um **mito**

**Comment by joao917** [comment]
Agora esta carregando certinho vlw mito

**Comment by alessandrojean** [comment]
Vamos ver quanto tempo continua funcionando...

**Comment by joao917** [comment]
Ja parou novamente, realmente é oque você disse não tem oque fazer vou mudar de fonte, vlw mito!
