### ISSUE TITLE
[MyMangaReaderCMS] Broken cover images for Read Comics Online

### ISSUE THREAD

**Issue by WiseMMO** [inorichi/tachiyomi-extensions#490]
Covers in both the catalogue for the website and my library (which contains elements from the catalogue) have broken covers.

All new comics that came out today all have the covers showing correctly, but as soon as you open one it breaks and going back it still shows as broken. This also happens with all older elements.

![1](https://user-images.githubusercontent.com/33370380/45454594-c349ea00-b6e4-11e8-817c-2513eb8d1d2c.gif)
 

So I have to reopen this. At first it seemed like it was fixed, but the issue is back. I tried clearing cache, reinstalling the extension, but even on multiple devices it just breaks all covers. If you don't have the cached they won't even show from the start.

![ezgif com-optimize](https://user-images.githubusercontent.com/33370380/45590221-02ba4580-b934-11e8-9cf5-15ffd48bfda7.gif)

**Comment by WiseMMO** [comment]
This seems like it was fixed

**Comment by CarlosEsco** [comment]
If its not issue anymore it must have been issue on their side.  Please close if you aren't seeing anymore
