### ISSUE TITLE
[Bug] My Manga Reader CMS: MangaYu

### ISSUE THREAD

**Issue by gospodinh** [inorichi/tachiyomi-extensions#4901]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 10

## Source information
- Name: My Manga Reader CMS (MangaYu)
- Extension version: 1.2.52

## Steps to reproduce
1. Open MangaYu
2. Http error 404

### Expected behavior
Show all manga from this source

### Actual behavior
Shows a message saying "HTTP error 404: check website in WebView".

**Comment by CrepeTF** [comment]
Try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis)

**Comment by Riztard** [comment]
Mangayu have its own extension, try search in extension, but it will not work if you not uninstall mmrcms
MangaYu in "My Manga Reader CMS" should be removed to fix this bug
