### ISSUE TITLE
[add mangaword.cc exstesion] <Mangaword>: <add this exstesion>

### ISSUE THREAD

**Issue by shady1919** [inorichi/tachiyomi-extensions#4904]
•Name: mangaworld
•Link: https://www.mangaworld.cc/
•Language(s): italian

--------------------------------------------------------------------------------------
Why this exstesion Is obsolete? Please fix this and add this exstesion on list.

**Comment by CrepeTF** [comment]
#2800

**Comment by sbarrusa** [comment]
I solved it by uninstalling this app and installing a much more useful one, just write mangaworld on the app store, it's one of the first apps, I don't write the name ...
