### ISSUE TITLE
[Add Mangaword ITA] <www.mangaworld.cc>

### ISSUE THREAD

**Issue by shady1919** [inorichi/tachiyomi-extensions#4905]
Name: mangaworld
•Link: https://www.mangaworld.cc/
•Language(s): italian

---------------------------------------------------------------------------------------------

Why this exstesion Is obsolete? Please fix this and add this exstesion on list.

**Comment by CrepeTF** [comment]
Don't make double post for the same issue.
I've already answered in #4904
