### ISSUE TITLE
[Source Request] <MangaWord ITA>

### ISSUE THREAD

**Issue by shady1919** [inorichi/tachiyomi-extensions#4906]
Name: mangaworld
•Link: https://www.mangaworld.cc/
•Language(s): italian

---------------------------------------------------------------------------------------------

Add this exstesion please, a few mouths ago this application became obsolete and and now  It does not work anymore.
Please how i can fix this?

**Comment by joseph619** [comment]
The source has been removed at the request of site owner and will not be added back. Don't open any more tickets.

#2800

**Comment by sbarrusa** [comment]
I solved it by uninstalling this app and installing a much more useful one, just write mangaworld on the app store, it's one of the first apps, I don't write the name ...
