### ISSUE TITLE
[mangago] Image isn't displaying correctly

### ISSUE THREAD

**Issue by Nihisil** [inorichi/tachiyomi-extensions#491]
**App version:** 
0.7.4 (F-droid)
mangago 1.2.5

**Issue/Request:** 

The image isn't displaying correctly.

![photo_2018-09-13_16-47-41](https://user-images.githubusercontent.com/475367/45477720-c12f6c00-b774-11e8-9035-30964ffacb07.jpg)

**Steps to reproduce**

 1. Open this manga http://www.mangago.me/read-manga/tetsunaki_no_kirinji_kabukichou_seiatsu_hen/
 2. Chapter 67, page 2. It looks like on the screenshot.
 3. If you open the same page on the manga source website, it looks fine.
 4. I tried do delete and download chapter again, it didn't help.
 5. There are 3-5 pages like this in the 3-4 latest chapters of this mange (but I didn't read a lot of manga on this device, it could be more).

**Other details:** Device is OnePlus 5t (screen 1080 x 2160).

**Comment by CarlosEsco** [comment]
If you can I would use a different source. Mangago actively tries to prevent readers so most contributors have given up on making it work in tachiyomi

**Comment by Nihisil** [comment]
Got it! I didn't know that. Thank you for information.
