### ISSUE TITLE
Tsuki mangás : situação.

### ISSUE THREAD

**Issue by yexiusama** [inorichi/tachiyomi-extensions#4912]
Olá, sou o dono e programador do site Tsuki mangás, recentemente o site passou por uma situação bem complicado e felizmente conseguimos resolver.
Agora ao que interessa, não tive a intenção de afetar o aplicativo da tachiyomi e com isso quero me desculpar e pedir o desbloqueio.
Única coisa que venho pedir é um header específico para que eu use como referência para não acontecer novamente.
Fiquei sabendo dessa situação por conhecidos meus que usavam a extensão e em nosso discord.
Um bom sábado a todos.

**Comment by alessandrojean** [comment]
Oi, eu que programei a extensão e acabei por mandar o PR para retirá-la depois.

Sem problemas, eu posso reverter e adicioná-la com um novo PR novamente. :)

Qual header você precisa que seja enviado nas requisições? Seria um User-Agent específico do Tachiyomi?

**Comment by yexiusama** [comment]
Me envia um user-agent específico de vocês.
Resolverei isso assim que você o fizer.

**Comment by alessandrojean** [comment]
Tem o que é usado na extensão do MangaDex.

```kotlin
"Tachiyomi " + System.getProperty("http.agent")
```

E tem também o usado normalmente quando não é especificado nenhum na biblioteca.

```kotlin
"Mozilla/5.0 (Windows NT 6.3; WOW64)"
```

Acredito que o primeiro seja mais específico e explícito. Eu já computo o valor dele completo (incluindo o que é dinâmico, como a versão do Android) e coloco aqui.

**Comment by yexiusama** [comment]
Pode enviar o primeiro. 
 Me parece mais saudável.

**Comment by alessandrojean** [comment]
Desculpa a demora. Eu computei aqui, e completo fica assim:

```
Tachiyomi Dalvik/2.1.0 (Linux; U; Android 10; Android SDK built for x86 Build/QSR1.190920.001)
```

Sendo os conteúdos nos parênteses dinâmicos, como a versão do Android e as outras coisas.

Eu testei localmente a extensão com esse User-Agent e já parece estar funcionando normalmente, então vou submeter um PR para adicionar ela novamente ao repositório.

Também peço desculpas eu ter interpretado errado e ter submetido um PR para remover a extensão, é que já houve alguns casos similares a este anteriormente.

**Comment by yexiusama** [comment]
Muito obrigado novamente.
Todos tem o direito de escolher entre ler em um aplicativo ou em um website.
Qualquer problema q venha ocorrer estou a disposição tanto no discord da tachiyomi quanto em minha github.

**Comment by alessandrojean** [comment]
Se precisar que algo seja mudado futuramente (como adicionar alguma header adicional ou alterar o User-Agent), fique a vontade para abrir uma nova Issue para que possa ser resolvido.

**Comment by yexiusama** [comment]
Entrarei em contato caso precise.
