### ISSUE TITLE
[Bug] <Komiku>: <Moved to new domain>

### ISSUE THREAD

**Issue by HaruSasaki** [inorichi/tachiyomi-extensions#4913]
## Device information
- Tachiyomi version: Stable 0.10.5
- Android version: 8.1.0

## Source information
- Name: Komiku
- Extension version: 1.2.3

### Actual behavior
No chapter found

## Other details
Old domain: komiku.co.id
New domain: komiku.id

**Comment by Riztard** [comment]
some part of their site still use old domain, so if we change it, it will broke some thing.
look like their website doesnt use "baseurl" thing but hardcode, i think.
maybe this will work for now #4921 (if merged)

**Comment by Kyrieze** [comment]
The chapters updated, but when opened, it says "no pages found", when I open it via Web View it's normal

**Comment by Riztard** [comment]
> The chapters updated, but when opened, it says "no pages found", when I open it via Web View it's normal
its different issue, create new issue i think

**Comment by Kyrieze** [comment]
Ok, I'll open new issue
