### ISSUE TITLE
[Bug] SuperMangas: chapters and search doesn't work

### ISSUE THREAD

**Issue by Shironep** [inorichi/tachiyomi-extensions#4917]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 10

## Source information
- Name: SuperMangas
- Extension version: 1.2.4

## Steps to reproduce
1. try to open any manga or search for one

### Expected behavior
Manga should show all chapters and search should show what u searched for.

### Actual behavior
Search doesn't work and don't show any warning, and mangas doesn't show chapters

## Other details
Searching a manga doesn't actually show an error, but if you open a manga it will show an error

**Comment by alessandrojean** [comment]
I will take a look later.

**Comment by alessandrojean** [comment]
I managed to fix the search, but I can't do anything about the chapters not loading because the chapter pagination is broken on the site, so nothing can be done on the extension side for now.

**Comment by Shironep** [comment]
> I managed to fix the search, but I can't do anything about the chapters not loading because the chapter pagination is broken on the site, so nothing can be done on the extension side for now.

hello again! looks like pagination was fixed, i'm one of the uploaders of this website and i can contact the developer, if it's still broken, pls let me know

**Comment by alessandrojean** [comment]
Looks like it's working now. I will check if the extension is working as expected in this part and submit the search fix.
