### ISSUE TITLE
[Source Request] <Silence Scan>

### ISSUE THREAD

**Issue by trik0** [inorichi/tachiyomi-extensions#4922]
## Source Website
- Name: Silence Scan
- Link: https://silencescan.net
- Language(s): Portuguese

**Comment by alessandrojean** [comment]
Already present on WPMangaStream extension.

**Comment by scb261** [comment]
[The sheet](https://tachiyomi.org/extensions-spreadsheet) is outdated, bur you still can search github issues or github code (as it said in the acknowledgment section) to find that it's in WP MangaStream #4457
https://github.com/inorichi/tachiyomi-extensions/blob/3c473ea28d05e90d3c52070ec258c90f37fb9983/src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt#L700

**Comment by Riztard** [comment]
need to be closed :whip:

**Comment by trik0** [comment]
Closed
