### ISSUE TITLE
[Bug] <Komiku>: <No Pages Found>

### ISSUE THREAD

**Issue by Kyrieze** [inorichi/tachiyomi-extensions#4927]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 7.1.1

## Source information
- Name: Komiku 
- Extension version: 1.2.5

## Steps to reproduce
1. Updated the Chapter list 
2. Opening new chapter 

### Expected behavior
The pages open, and start to read

### Actual behavior
It's says "No Pages Found"
![Screenshot_2020-11-23-15-49-45-33](https://user-images.githubusercontent.com/74162654/99946003-390f6d00-2da8-11eb-8d81-7fc373adfb04.png)

## Other details
The pages shows up on webview
![Screenshot_2020-11-23-15-50-21-40](https://user-images.githubusercontent.com/74162654/99946041-4a587980-2da8-11eb-8ac3-60d28838bacf.png)

**Comment by Riztard** [comment]
old chapter work just fine, they seems change something

**Comment by Kyrieze** [comment]
Sure, forgot to mention it, it's just affecting new chapter on every tittle I got on the library

**Comment by Riztard** [comment]
not sure what happen but it work again, either their new domain messed up(they seems use the old domain again #4913) or something else. hmm

**Comment by Kyrieze** [comment]
Yeah maybe, saved titles are available to read for now, but when I browse new title, the chapter list isn't showing every opening new titles tho, here's an example
![Screenshot_2020-12-02-22-10-25-54](https://user-images.githubusercontent.com/74162654/100890853-44227580-34eb-11eb-86a8-261cc52ffc75.png)
![Screenshot_2020-12-02-22-10-12-48](https://user-images.githubusercontent.com/74162654/100890860-471d6600-34eb-11eb-853a-abcf56cc3aba.png)
![Screenshot_2020-12-02-22-10-18-10](https://user-images.githubusercontent.com/74162654/100890874-4ab0ed00-34eb-11eb-80fd-d53dbcea1080.png)

**Comment by Kyrieze** [comment]
As usual, when I open it via webview it's normal without problems, just gonna wait until everything back to normal I guess, I'll inform later if I got new info!
Thanks!

**Comment by Riztard** [comment]
itu bug laen #4996 tunggu update setengah jam an paling

**Comment by Riztard** [comment]
jadi paling ntar close ini kalo udah bisa lagi, kalo gak, kasi contoh mana yang gabisa lagi

**Comment by Kyrieze** [comment]
Ok siap ditunggu, thanks!

**Comment by Kyrieze** [comment]
Done!

**Comment by Kyrieze** [comment]
![Screenshot_2020-12-11-08-49-32-97](https://user-images.githubusercontent.com/74162654/101851302-dda5f300-3b8d-11eb-880c-0a35ac64dd05.png)
![Screenshot_2020-12-11-08-49-21-92](https://user-images.githubusercontent.com/74162654/101851310-e0a0e380-3b8d-11eb-881b-4908fd798c1e.png)

Balik lagi kaya kemaren min, bingung ama Komiku haha, no chapters found + no pages found, di webview seperti biasa work as usual

**Comment by JoyBoy666** [comment]
Iya nih, padahal minggu lalu masih bisa pake komiku, minggu ini malah bermasalah lagi
