### ISSUE TITLE
[Webtoon.xyz] <webtoon.xyz>

### ISSUE THREAD

**Issue by GSX-52** [inorichi/tachiyomi-extensions#4928]
## webtoon.xyz
- Name: webtoon.xyz
- Link: https://www.webtoon.xyz
- Language(s): English

**Comment by scb261** [comment]
Already exists, check [the sheet for multi-source extensions](https://tachiyomi.org/extensions-spreadsheet) or search github next time
https://github.com/inorichi/tachiyomi-extensions/blob/950e2a67ebeff2c151b513a18cc1a5a248a82f4e/src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt#L1140
