### ISSUE TITLE
[Source Request] <Mangaworld> 

### ISSUE THREAD

**Issue by AeonDave** [inorichi/tachiyomi-extensions#4929]
## Source Website
* Name: Mangaworld
* Link: [www.mangaworld.cc](https://www.mangaworld.cc)
* Language(s): IT

**Comment by scb261** [comment]
#3475

**Comment by sbarrusa** [comment]
I solved it by uninstalling this app and installing a much more useful one, just write mangaworld on the app store, it's one of the first apps, I don't write the name ...
