### ISSUE TITLE
[Bug] Missing/Removed Manga

### ISSUE THREAD

**Issue by cievee** [inorichi/tachiyomi-extensions#4930]
## Source information
- Name: Poco X3
- Extension version: r2827

### Expected behaviour
My manga's stayed at my library

### Actual behaviour
The manga's that I have read and bookmarked keeps on getting removed in my categories and my library. The chapter that i left on also dissapeared and I don't know what chapter I'm in when I discovered the removed manga. I have tried to clear the cache and reinstall the app but it still kept on happening. I thought the bug disappeared on that last update but I guess its not fixed.

## Other details
Most of the manga that I have save in my library is from manghasu, mangadex and manga here sources

**Comment by Riztard** [comment]
maybe your filter is on?

**Comment by arkon** [comment]
1. Wrong repo.
2. This is unactionable without consistent reproduction steps.

**Comment by cievee** [comment]
Some scenarios that happened to me is when I checked solo leveling it been remove in my library even though Its been added to library because its one of my favourite manga's and all of the chapters has been unread and my bookmark disappeared also. My filter is not activated though
