### ISSUE TITLE
[Bug] hentainexus: toIndex (X) is greater than size (X) error on select manga

### ISSUE THREAD

**Issue by bugreportanon** [inorichi/tachiyomi-extensions#4938]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 10

## Source information
- Name: hentainexus
- Extension version: 1.2.4

## Steps to reproduce
1. Attempt to read
* Twin Healing
* Upside Down Puzzle
* Don't Be So hard on Yourself
* Gratitude Recipie
* Innocent Couple
* Pastoral Reunion
2. Chapter fails to load with toIndex (X) is greater than size (X) message

### Expected behavior
Able to load and read chapter.

### Actual behavior
Chapter fails to load with toIndex (X) is greater than size (X) message.

## Other details
Not sure why this happens, some manga load fine but some doesn't.

**Comment by S-eann** [comment]
The same thing happens to me now, I updated it and it was fine at first, but after a few hours this happened.

**Comment by einstein95** [comment]
HentaiNexus updated the page decoding shit. Here's the current code ported to Python:
```python
body = bytearray(b64decode('VBq/ZzHoY+qX2DWod66Ie5aLGL6W19zR+P+ewn24aTJRMMbdDeR+729hQdR+Qsw28ipPFEAYcRGhxpOWoiS9BBS0RcCG05r5V15SNmUHdTrOFrpKrHVB9efD/ALATVnjSq+MQqPbS+TxxgKEwSguTbbYUNNF239FMZ6Ck1/rbdl4yVK7bZzEHbhr6ZFQPG7Bict8HSf+TVcl7Lh1YjUhuv9Hf1L3GWlrMr88DFJRSxJYri16f0WXa5VDQAOxLByKR+pLlB8QCH6/Du7rWCxDWa4Bkif/623x7eHSxsSp/0oC7X9KlFOjkVzwat5nyBOiaqGvfKZ097d027+C92ZVqGaPNjEZnxTKh8DQX5CbOXeVHbkLr8li0fZUjCJqLqhBtL4tNQfEGxORJv8ar6P5YA=='))

buf = body[:64]
data = [i for i in range(256)]
b = 0

for i in range(256):
  b = (b + data[i] + buff[i % len(buf)]) % 256
  tmp = data[i]
  data[i] = data[b]
  data[b] = tmp

s = ''
b = 0
for a in range(len(body)-64):
  i = (i + 1) % 256
  b = (b + data[i]) % 256
  tmp = data[i]
  data[i] = data[b]
  data[b] = tmp
  s += chr(body[a + 64] ^ data[(data[i] + data[b]) % 256])

print(s)
```

**Comment by bugreportanon** [comment]
Probably not the right place to ask but why?
Does this improve how the pages load?

**Comment by CarlosEsco** [comment]
> 
> 
> Probably not the right place to ask but why?
> Does this improve how the pages load?

They are probably trying to stop scraping

**Comment by Louie08213** [comment]
> The same thing happens to me now, I updated it and it was fine at first, but after a few hours this happened.

it worked great last night and now, I get this error too.

**Comment by CarlosEsco** [comment]
It's broken again, no need to keep adding comments

**Comment by MoistSac** [comment]
Since they're probably trying to conserve bandwidth in the rona era, I won't make a pull request, but heres the new decodePages for anyone who wants to do it manually:

```
    private fun decodePages(code: String): List<String> {
        val bin:  ByteArray = Base64.decode(code, Base64.DEFAULT)
        val head: ByteArray = bin.sliceArray(0..63)
        var arr = ByteArray(256) { it.toByte() }
        var num: Int = 0
        var tmp: Byte

        for (i in 0..255) {
            num = (num + arr[i] + head[i % head.size] + 256) % 256
            tmp = arr[i]
            arr[i] = arr[num]
            arr[num] = tmp
        }
        var i = 0
        num = 0
        val buf = StringBuilder()

        for (j in 0..bin.size-65) {
            i = (i + 1) % 256
            num = (num + arr[i] + 256) % 256
            tmp = arr[i]
            arr[i] = arr[num]
            arr[num] = tmp
            buf.append((bin[j + 64] xor arr[(arr[i] + arr[num] + 256) % 256]).toChar())
        }

        val json = JsonParser().parse(buf.toString()).asJsonObject

        val base = json.get("b").asString
        val folder = json.get("r").asString
        val id = json.get("i").asString
        return json.get("f").asJsonArray.map { it ->
            val page = it.asJsonObject
            "${base}${folder}${page.get("h").asString}/${id}/${page.get("p").asString}"
        }
    }
```

**Comment by Rein-del** [comment]
> Since they're probably trying to conserve bandwidth in the rona era, I won't make a pull request, but heres the new decodePages for anyone who wants to do it manually:
> 
> ```
>     private fun decodePages(code: String): List<String> {
>         val bin:  ByteArray = Base64.decode(code, Base64.DEFAULT)
>         val head: ByteArray = bin.sliceArray(0..63)
>         var arr = ByteArray(256) { it.toByte() }
>         var num: Int = 0
>         var tmp: Byte
> 
>         for (i in 0..255) {
>             num = (num + arr[i] + head[i % head.size] + 256) % 256
>             tmp = arr[i]
>             arr[i] = arr[num]
>             arr[num] = tmp
>         }
>         var i = 0
>         num = 0
>         val buf = StringBuilder()
> 
>         for (j in 0..bin.size-65) {
>             i = (i + 1) % 256
>             num = (num + arr[i] + 256) % 256
>             tmp = arr[i]
>             arr[i] = arr[num]
>             arr[num] = tmp
>             buf.append((bin[j + 64] xor arr[(arr[i] + arr[num] + 256) % 256]).toChar())
>         }
> 
>         val json = JsonParser().parse(buf.toString()).asJsonObject
> 
>         val base = json.get("b").asString
>         val folder = json.get("r").asString
>         val id = json.get("i").asString
>         return json.get("f").asJsonArray.map { it ->
>             val page = it.asJsonObject
>             "${base}${folder}${page.get("h").asString}/${id}/${page.get("p").asString}"
>         }
>     }
> ```

How to use?

**Comment by yooman1213** [comment]
So no fixes?

**Comment by joseph619** [comment]
> So no fixes?

You are welcome to fix it yourself
