### ISSUE TITLE
[Source Request] <Mangaworld>

### ISSUE THREAD

**Issue by HasanAbdelAziz** [inorichi/tachiyomi-extensions#4948]
## Source Website
- Name: mangaworld
- Link: https://www.mangaworld.cc/
- Language(s): italiano

**Comment by CrepeTF** [comment]
#2800

**Comment by sbarrusa** [comment]
I solved it by uninstalling this app and installing a much more useful one, just write mangaworld on the app store, it's one of the first apps, I don't write the name ...
