### ISSUE TITLE
[mangaworld] <mangaworld>

### ISSUE THREAD

**Issue by sbarrusa** [inorichi/tachiyomi-extensions#4955]
Source Website
Name: mangaworld
Link: https://mangaworld.cc/
Language(s): italian
Other Details
About a week ago the site changed some things on an aesthetic level and since then on tachiyomi, when trying to open a chapter, it gives the error message "the page list is empty".

**Comment by Riztard** [comment]
if the previous one was mangaworld.tv then read #3475

**Comment by sbarrusa** [comment]
the site is developed with madara, and until a week ago chapters could be read thanks to the madara extension.

**Comment by scb261** [comment]
The extension was removed at request of the site owner some time ago. You used obsolete extension and it won't be fixed

**Comment by sbarrusa** [comment]
the site is available thanks to the extension of madara on tachiyomi updated to the latest version

**Comment by scb261** [comment]
> the site is available thanks to the extension of madara on tachiyomi updated to the latest version

If you see the mangaworld source, then your madara extension is outdated. I checked both in the app and in the code, it's not there. Install madara extension 1.2.150 to be up to date. I don't see any reason to try to prove it to you or to repeat again that it won't be fixed, so I'm not gonna answer anymore.

For reference: pinned issue about sources that won't be added #3475

**Comment by sbarrusa** [comment]
and what about the mangaworld extension, can't it be updated? for the Italian community it is practically the only resource that allows you to read manga, without it we cannot read anything on smartphones ...

**Comment by sbarrusa** [comment]
So a site that steals scans from various sites and doesn't put anything of its own can ask you to remove the extension from tachiyomi? I really hope he fails, you can't read manga on his site, full of porn ads ...

**Comment by arkon** [comment]
Then use a different site.
