### ISSUE TITLE
[Bug] ReadComicOnline (FMReader) incorrect domain extension

### ISSUE THREAD

**Issue by AdvantageQuirky** [inorichi/tachiyomi-extensions#4960]
##  Device information
- Tachiyomi version: 0.10.5
- Android version: 10

### Expected behavior
From FMReader, ReadComicOnline URL should be "ReadComicOnline.to"

### Actual behavior
ReadComicOnline URL is "ReadComicOnline.org"

**Comment by scb261** [comment]
readcomiconline.to has its own extension called readcomiconline
