### ISSUE TITLE
[Bug] <Zahard >: <404 error>

### ISSUE THREAD

**Issue by sshawnsamuell** [inorichi/tachiyomi-extensions#4968]
## Device information
- Tachiyomi version: 10.5
- Android version: 10

## Source information
- Name: Zahard
- Extension version: 1.2.4

## Details
Zahard.top went down for some time. It came back up with the same URL, so it works in web viewer, but 404s in app. The website looks to be completely overhauled.

**Comment by AriaMoradi** [comment]
They changed their generator site.
Now zahard is a part of mmrcms.
