### ISSUE TITLE
[Source Request] <100kanojo.com>

### ISSUE THREAD

**Issue by RatchetNine76** [inorichi/tachiyomi-extensions#4974]
- Name: 100Kanojo
- Link: 100Kanojo.com
- Language(s): English

## Other Details
This site is only for the recent popular harem manga:  The 100 Girlfriends Who Really, Really, Really, Really, Really Love You.
I would ask a request for this as most manga sites are incomplete or missing chapters because of the shutdown of jaiminisbox.com

**Comment by scb261** [comment]
Single-manga sources were rejected before and this one doesn't even scanlate the manga
