### ISSUE TITLE
[Bug] Tsumino: Failed to connect to www.tsumino.com

### ISSUE THREAD

**Issue by simakover** [inorichi/tachiyomi-extensions#4983]
## Device information
- Tachiyomi version: 0.10.5

## Source information
- Name: Tsumino extension
- Extension version: 1.2.3

## Steps to reproduce
1) go for search
2) choose tsumino library
3) get error Failed to connect to www.tsumino.com/2606:4700:3038::6815:edb7:443

### Expected behavior
normal working library

**Comment by arkon** [comment]
Does it work in WebView?

**Comment by simakover** [comment]
> Does it work in WebView?

no, it doesnt work. 
Found problem, sorry for this issue. It start work if app was running under VPN, tsumino is blocked via internet provider
