### ISSUE TITLE
[Korean] toonkor.cab

### ISSUE THREAD

**Issue by Reraru** [inorichi/tachiyomi-extensions#499]
https://toonkor.red/

Please add this site if you can, for Korean raws.

**Comment by Reraru** [comment]
Please look at this ;_;

**Comment by jaywyeee** [comment]
Marumaru.in would be nice as well.

**Comment by joseph619** [comment]
Requesting this as well, it has almost every single raw webtoon ever published and stable website, don't have to change the domain every few months.

**Comment by andrizmitnick** [comment]
Up, any news regarding this site?

**Comment by Reraru** [comment]
Please add this. It's the same as Newtoki, but Newtoki isn't usable anymore.
