### ISSUE TITLE
Viz shonen jump thumbnails disappear after backup

### ISSUE THREAD

**Issue by gingerboboh** [inorichi/tachiyomi-extensions#4991]
## Device information
* Tachiyomi version: 0.10.5
* Android version: 11
* Device: pixel 4 xl

## Source information
* Source name: Viz Shonen Jump
* Source extension version: 1.2.4

## Steps to reproduce
1. Favorite manga
2. Create backup
3. Restore backup

## Issue/Request
when restoring backup, favorite manga lose their covers. Other manga in the catalogue show covers still. Refavoriting, clearing cache, reinstalling extension do not work. Any new favorites retain the covers until backed up.

**Comment by scb261** [comment]
Try *More > Settings > Advanced > Refresh library manga covers*

**Comment by alessandrojean** [comment]
If I remember correctly, in the manga page at the website there's no way to get the cover, so it's not set at `mangaDetailsParse`.

I will try to do a workaround with this later.

**Comment by gingerboboh** [comment]
> Try _More > Settings > Advanced > Refresh library manga covers_

The refresh did not work sadly.
