### ISSUE TITLE
[Source Request] asurascans

### ISSUE THREAD

**Issue by MxxS07** [inorichi/tachiyomi-extensions#4993]
##  Why/Project's Benefit/Existing Problem
They scan and translate manhwas .

## Other Details
Pleas add asurascans extension.

**Comment by scb261** [comment]
Read acknowledgment section before removing it. It already exists, search [the spreadsheet for multi-source extensions](https://tachiyomi.org/extensions) or github next time.
https://github.com/inorichi/tachiyomi-extensions/blob/3c473ea28d05e90d3c52070ec258c90f37fb9983/src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt#L83

**Comment by Riztard** [comment]
already exist, read the instruction nextime
- check here
spreadsheet: https://tachiyomi.org/extensions
or this github
