### ISSUE TITLE
Neox Scanlator madara extension

### ISSUE THREAD

**Issue by Douglasimav** [inorichi/tachiyomi-extensions#4997]
the manga link has been changed, for example the solo leveling manga is not loading the page, showing error 404.
![Screenshot_20201202-141205_Tachiyomi](https://user-images.githubusercontent.com/72045485/100906853-647d1080-34a8-11eb-9bb9-60b3018bac16.png)

**Comment by Riztard** [comment]
next time fill out the information

i can open just fine, which chapter youre talking about

if you cant open it in webview as well then disclaimer
![image](https://user-images.githubusercontent.com/16263232/100910688-d84b0780-3500-11eb-9ae2-0cbade90d709.png)

**Comment by Douglasimav** [comment]
> da próxima vez preencha as informações
> 
> posso abrir muito bem, de qual capítulo você está falando
> 
> se você não puder abri-lo no webview também, isenção de responsabilidade
> ![imagem](https://user-images.githubusercontent.com/16263232/100910688-d84b0780-3500-11eb-9ae2-0cbade90d709.png)

chapter 129, the webview works well, i believe the reason for this error is that the manga address is changed

**Comment by scb261** [comment]
Try to migrate from Neox Scanlator to Neox Scanlator (on manga page tap three dots and select Migrate). If doesn't help, try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis) as well

**Comment by Douglasimav** [comment]
> Tente migrar do Neox Scanlator para o Neox Scanlator (na página do mangá, toque três pontos e selecione Migrar). Se não ajudar, tente [solucionar o problema](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis) também

ok

**Comment by Douglasimav** [comment]
it worked, I migrated and updated now
