### ISSUE TITLE
[Source Request] <MangaPill>

### ISSUE THREAD

**Issue by zatchbell04** [inorichi/tachiyomi-extensions#4998]
Hey buddy,I want to request a source which I guess opens recently.The website name is mangapill.If this is already there then sorry for the inconvenience and wasting your time.Thanks for your hard work.
## Source Website
- Name: MangaPill
- Link: https://mangapill.com/
- Language(s): English

## Other Details
It actually is a decent site.It pull the ongoing manga from mangadex.And donot know about finished manga.Thanku
![IMG_20201203_022532](https://user-images.githubusercontent.com/71206003/100930289-e30c9900-350e-11eb-8611-7421db515741.jpg)

**Comment by CrepeTF** [comment]
Dupe #4689

**Comment by zatchbell04** [comment]
Ok sorry for this mistake this will never happen again.I will check it very clearly then request for source.Thanku
