### ISSUE TITLE
Madokami

### ISSUE THREAD

**Issue by Ketchup901** [inorichi/tachiyomi-extensions#5]
Adopting this from https://github.com/inorichi/tachiyomi/issues/140.

**Comment by Horoneru** [comment]
As of now, the API isn't ready for login sources (see [#4](https://github.com/inorichi/tachiyomi-extensions/issues/4#issuecomment-275216334)) . I believe Inorichi will work it out later on if there's demand, but for now, we should try to work on implementing new sources.
Again, maybe looking at Batoto's previous implementation in the current Tachiyomi repo would help, as it's another login source

**Comment by bobobo1618** [comment]
So I have this working on my device. I achieved it by:

- Copying `LoginSource` from the main app repo to `tachiyomi-extensions-lib`.
- Adding a new `Madokami` source to this repo, inheriting from `LoginSource` and `HttpParserSource`.
- Modifying the main app (`createExtensionSources` in `SourceManager`) to identify `LoginSource` sources, grab their username and password from `PreferencesHelper` and call `login()` if either a username or password is saved.

If that sounds fine I can send some PRs.

**Comment by Kovaelin** [comment]
Any chance this will be made into an extension?

**Comment by lostering** [comment]
@bobobo1618 , Any chance you can share the code for this. With bato.to down it's time to look for a new home page

**Comment by bobobo1618** [comment]
This is far from homepage worthy but here's what I did:

- https://github.com/inorichi/tachiyomi-extensions-lib/pull/4
- https://github.com/inorichi/tachiyomi/pull/1184
- https://github.com/inorichi/tachiyomi-extensions/pull/156

**Comment by Xeiniac** [comment]
Any update on this?

**Comment by shogunreaper** [comment]
i'd also like to know if theres any updates

**Comment by bobobo1618** [comment]
Please don't ask for updates on Github issues unless you're actively working on something and blocked by the issue. It sends email notifications to everyone on the thread which is really annoying.

If there's work being done, you'll see commits and discussion on the issue automatically.

**Comment by as280093** [comment]
Here the icons
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3615411/ic_launcher.7.zip)
