### ISSUE TITLE
[Source Request] <MangaGecesi>

### ISSUE THREAD

**Issue by onursedef** [inorichi/tachiyomi-extensions#5006]
## Source Website
- Name: MangaGecesi
- Link: https://mangagecesi.com
- Language(s): Turkish

## Other Details

It has so many manga, mahwa and manhua translated to Turkish. And it's not like small series, some of them has a huge fan like The Beginning After The End or Ranker Who Lives a Second Time. There are a lot of fans in Turkey. So if you add this website as a extention it will pretty easy to find and read these series on this app. Thank you and have a good day.

**Comment by scb261** [comment]
Removed by request of the site owner #2980
