### ISSUE TITLE
[Bug] <Bato.to>: <Browse & Latest lists do not show items in library>

### ISSUE THREAD

**Issue by jadoff630** [inorichi/tachiyomi-extensions#5009]
## Device information
- Tachiyomi version: Preview r313(f1a6218a4)
- Android version: 10

## Source information
- Name: Emerald
- Extension version: 1.2.7

## Steps to reproduce
1. Open Bato.to extension
2. Select Browse -or- latest (issue happens in both)

### Expected behavior
Titles that are already in your library should have their covers grayed out and when you select them, it should say "In Library"

### Actual behavior
Titles that were in your library before yesterday are no longer grayed out and do not say "in library" but titles that I added since the bug began are grayed out and say "in library"

![Capture](https://user-images.githubusercontent.com/25085973/101107661-5b6b6c80-3598-11eb-9416-c02231d7354f.PNG)

(Here is a screenshot showing that one of the titles I said is in my library is actually there, just for proof 😄)
<img src="https://user-images.githubusercontent.com/25085973/101107285-9caf4c80-3597-11eb-9ad0-06e804c31cd4.jpg" width ="55%" height="55%">

**Comment by arkon** [comment]
You probably need to "migrate" to the same source as the site likely replaced the entry with something else, which the app doesn't really handle well.

Side note, this fake bato.to is clearly a subpar source given you're having this issue.

**Comment by jadoff630** [comment]
Thanks @arkon. That is a bit annoying but oh well, what ya gonna do. I will say that another bug (#4882) makes it a bit challenging to find some of these as there seems to be a bug when searching in bato's extension. 

Curiosity question re:side note: I know that bato was gone for a while and this is a revived version, is that what makes it fake?

**Comment by arkon** [comment]
AFAIK it's just using the name since it was well known, which is a relatively common tactic used by these kind of sites.

Anyway, closing this since there's no action to be taken for this particular issue.
