### ISSUE TITLE
[Bug] <BestManhua>: HTTP Error 400:Check Website in Webview

### ISSUE THREAD

**Issue by sam7028** [inorichi/tachiyomi-extensions#5013]
### Device information

Tachiyomi version: 0.10.5
Android version: 10
Source information

Name: BestManhua (Madara)
Extension version: 1.2.151
### Expected behavior

Open chapters normally
### Actual behavior

403 error, web view shows chapters

**Comment by Riztard** [comment]
seems they change to another website theme, and no longer use madara

**Comment by CarlosEsco** [comment]
Moved into the WP Manga

**Comment by Riztard** [comment]
oh the one in madara should be removed so it wont overlaped and bugged
