### ISSUE TITLE
[Bug] FMReader - RawLH: Latest List only 1 Manga

### ISSUE THREAD

**Issue by Donnie-B** [inorichi/tachiyomi-extensions#5019]
---

## Device information
- Tachiyomi version: 0.10.5
- Android version: 9

## Source information
- Name: FMReader - RawLH
- Extension version: 1.2.22

## Steps to reproduce
1. Click RawLH Latest Button on the Browse tab
2. Only found 1 Manga: "Kuroi Kusushi to Shiroki Ryuuhime"

### Expected behavior
Should have listed much more latest manga list

### Actual behavior
Only found 1 Manga: "Kuroi Kusushi to Shiroki Ryuuhime"

## Other details
LHTranslation is showing just fine, also opening in the web also showing the whole latest list just fine as well

**Comment by Riztard** [comment]
latest work just fine for me, try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/)

**Comment by Donnie-B** [comment]
I checked right after you respond and now it's working just fine.
I don't even do any of the troubleshooting steps.

**Comment by Riztard** [comment]
then close
