### ISSUE TITLE
[Bug] <HentaiNexus>: <Manga not opening>

### ISSUE THREAD

**Issue by Zaretno** [inorichi/tachiyomi-extensions#5022]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.5)
- I have updated all extensions
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/inorichi/tachiyomi
- I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another open iss

---

## Device information
- Tachiyomi version: 0.10.5
- Android version: 10

## Source information
- Name: Hentainexus
- Extension version: 1.2.5

## Steps to reproduce
1. Open HentaiNexus manga
2. Tap on chapter

### Expected behavior
Manga is loaded and chapters are readable 

### Actual behavior
String line appears: com.google.gson.stream.MalformedJsonException:Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 6 path $

## Other details
the column # changes every time you open a chapter whether it's the same or different manga on the string.

Tried various different Manga from HentaiNexus. None is openable so far.

**Comment by newstostory** [comment]
I think this is not a error it is some kind of bug or website deleted by owner.

**Comment by CarlosEsco** [comment]
why are you commenting on a closed ticket? @newstostory

**Comment by newstostory** [comment]
Recently reading about is so i found this thread
