### ISSUE TITLE
[Bug] <HentaiNexus>: <Unable to read chapters>

### ISSUE THREAD

**Issue by Sivoroth** [inorichi/tachiyomi-extensions#5027]
---

## Device information
- Tachiyomi version: 0.10.5
- Android version: 10

## Source information
- Name: HentaiNexus
- Extension version: 1.2.6

## Steps to reproduce
1. Read any manga from source
2. Open the chapter of manga

### Expected behavior
Image of manga pages appear

### Actual behavior
Line "Index: 1, Size: 1" appears and chapter is not opened.

## Other details
There are some mangas that doesn't have the line appear but the images are not loaded no matter how many times the retry button is pressed.

**Comment by Blatzar** [comment]
They're definetly monitoring the PR:s on here as they changed the url from https://hentainexus.com/read/0000/001 to  https://hentainexus.com/read/0000#001 right after recent change.

Changing https://github.com/inorichi/tachiyomi-extensions/blob/master/src/en/hentainexus/src/eu/kanade/tachiyomi/extension/en/hentainexus/HentaiNexus.kt#L201-L203
to something like 
```
        return chapter.url.split("!").let { list ->
            // repeat() turns 1 -> 001 and 10 -> 010
            Observable.just(listOf(1..list[1].toInt()).flatten().map { Page(it, list[0] + "#${"0".repeat(maxOf(3 - it.toString().length, 0))}$it") })
```
and changing the selector on line [189](https://github.com/inorichi/tachiyomi-extensions/blob/master/src/en/hentainexus/src/eu/kanade/tachiyomi/extension/en/hentainexus/HentaiNexus.kt#L189) to 
`url = "${response.request().url().toString().replace("/view/", "/read/")}!"`

Is probably sufficent for it to work again, but I'm not making another PR.

**Comment by sprth** [comment]
> They're definetly monitoring the PR:s on here as they changed the url from https://hentainexus.com/read/0000/001 to https://hentainexus.com/read/0000#001 right after recent change.
> 
> Changing https://github.com/inorichi/tachiyomi-extensions/blob/master/src/en/hentainexus/src/eu/kanade/tachiyomi/extension/en/hentainexus/HentaiNexus.kt#L201-L203
> to something like
> 
> ```
>         return chapter.url.split("!").let { list ->
>             // repeat() turns 1 -> 001 and 10 -> 010
>             Observable.just(listOf(1..list[1].toInt()).flatten().map { Page(it, list[0] + "#${"0".repeat(maxOf(3 - it.toString().length, 0))}$it") })
> ```
> 
> and changing the selector on line [189](https://github.com/inorichi/tachiyomi-extensions/blob/master/src/en/hentainexus/src/eu/kanade/tachiyomi/extension/en/hentainexus/HentaiNexus.kt#L189) to
> `url = "${response.request().url().toString().replace("/view/", "/read/")}!"`
> 
> Is probably sufficent for it to work again, but I'm not making another PR.

Hi, I applied non pr fixes from the last bug once. I'm able to build an apk but tachiyomi marked it as unofficial. I built it  by just building  that entire "en" folder, I'm not familiar with Android/ Studio so how can I build apk with just HentaiNexus extension? Thanks.

**Comment by MoistSac** [comment]
Aaaand they replaced it with an even more complicated obfuscator. Welp, that's a probem for tomorrow's me.

**Comment by MoistSac** [comment]
New decoder:

```kt
    override fun pageListParse(document: Document): List<Page> {
        return document.select("script:containsData(initreader)").first().data()
            .substringAfter("initReader(\"")
            .substringBefore("\", ")
            .let(::decodePages)
            .mapIndexed { i, image -> Page(i, "", image) }
    }

    private fun decodePages(code: String): List<String> {
        val bin:  ByteArray = Base64.decode(code, Base64.DEFAULT)

        var array1 = BooleanArray(256) { false }
        var array2 = ByteArray(16)

        var i = 2
        var j = 0
        while (j < 16) {
            if (!array1[i]) {
               array2[j] = i.toByte()
                ++j
                for (k in (i*2)..255 step i) array1[k] = true
            }
            ++i
        }

        var num1 = 0
        for (i in 0..63) {
            num1 = num1 xor bin[i].toInt()
            for (j in 0..7) {
                num1 = (if (num1 and 1 == 1) num1 ushr 1 xor 12 else num1 ushr 1) % 255
            }
        }

        var array3 = ByteArray(256) { it.toByte() }

        var num2 = 0
        for (i in 0..255) {
            num2 = (num2 + array3[i] + bin[i % 64] + 256) % 256
            val tmp = array3[i]
            array3[i] = array3[num2]
            array3[num2] = tmp
        }

        val buf = StringBuilder()
        var num3: Byte = 0
        var num4 = 0
        val num5 = array2[num1]
        i = 0
        num2 = 0
        for (j in 0..bin.size-65) {
            i = (i + num5 + 256) % 256
            num2 = (num4 + array3[(num2 + array3[i] + 256) % 256] + 256) % 256
            num4 = (num4 + i + array3[i] + 256) % 256
            val tmp = array3[i]
            array3[i] = array3[num2]
            array3[num2] = tmp

            num3 = array3[(num2 + array3[(i + array3[(num3 + num4 + 256) % 256] + 256) % 256] + 256) % 256]
            buf.append((bin[j + 64] xor num3).toChar())
        }
       
        val json = JsonParser().parse(buf.toString()).asJsonObject

        val base = json.get("b").asString
        val folder = json.get("r").asString
        val id = json.get("i").asString
        return json.get("f").asJsonArray.map { it ->
            val page = it.asJsonObject
            "${base}${folder}${page.get("h").asString}/${id}/${page.get("p").asString}"
        }
    }
```

No PR, if you don't know what to do with this, just use the web browser.

**Comment by joseph619** [comment]
Perhaps it's best not to pursue this any longer, for now? Tachiyomi is just straining their server which is already hammered by covid traffic.

**Comment by arkon** [comment]
Superseded by #5035
