### ISSUE TITLE
[Bug] <Hentainexus>: <chapter pages do not load>

### ISSUE THREAD

**Issue by AwesomeQuest** [inorichi/tachiyomi-extensions#5031]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 9

## Source information
- Name: Hentainexus
- Extension version: 1.2.6

## Steps to reproduce
1. Open any doujinshi
2. Open chapter

### Expected behavior
Page image should load

### Actual behavior
Page does not load. Can see page navigation and swipe through pages but none load. Just shows the retry button.

## Other details
Covers load just fine. Webview work fine as well

**Comment by AwesomeQuest** [comment]
Is this something that happened with the extension update or did hentainexus change something?
It's been problem after problem the last few days.

**Comment by CrepeTF** [comment]
#5027
