### ISSUE TITLE
[Bug] <ReadComicOnline>: <Comics just won't load. None of them. I can't read anything.>

### ISSUE THREAD

**Issue by sabaqobalia** [inorichi/tachiyomi-extensions#5044]
---

## Device information
- Tachiyomi version: Stable 0.10.5

- Android version: 7.0

## Source information
- Name: ReadComicOnline
- Extension version: 1.2.8

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
The comics should load.

### Actual behavior
The comics don't load.
## Other details
It just says "No pages found" when my internet connection is pretty strong.

**Comment by scb261** [comment]
Duplicate of #2874, but it works fine for me. You can try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems)
