### ISSUE TITLE
[Bug] <Tsuki Mangás >: < HTTP error 404>

### ISSUE THREAD

**Issue by Vitor1782** [inorichi/tachiyomi-extensions#5050]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 10

## Source information
- Name: Tsuki Mangás
- Extension version: 1.2.6

## Steps to reproduce
1. Open any mangá 
2. error message appears

**Comment by Vitor1782** [comment]
Entrei em qualquer manga o tachiyomi me deu esse link:https://tsukimangas.com/manga/haite-kudasai-takamine-san

Dai falei com um cara do servidor ele me deu esse link:https://tsukimangas.com/obra/43/haite-kudasai-takamine-san

Mudou um pouco do endereço eu acho ksksk

**Comment by matheuswr89** [comment]
@alessandrojean dá uma olhadinha aí

**Comment by alessandrojean** [comment]
Vou dar uma olhada, mas já adianto que provavelmente as obras na biblioteca vão ter que serem migradas (no caso, da Tsuki para a própria Tsuki, para atualizar o endereço).

**Comment by Deed021** [comment]
> Vou dar uma olhada, mas já adianto que provavelmente as obras na biblioteca vão ter que ser migradas (no caso, da Tsuki para a própria Tsuki, para atualizar o endereço).

Tem como migrar todos os mangás dessa source de uma vez ou vou ter que ir migrando um por um? Pergunto isso porque não sei se dá para migrar tudo para a mesma extensão

**Comment by alessandrojean** [comment]
@Deed021 Eu creio que tem que ser um por um mesmo, infelizmente.

**Comment by Vitor1782** [comment]
So no fork j2k da pra fazer tudo de uma vez
