### ISSUE TITLE
[Bug] CopyManga / 拷贝漫画: No Results Found or Null Object Reference

### ISSUE THREAD

**Issue by LenKiMo** [inorichi/tachiyomi-extensions#5055]
## Device information
- Tachiyomi version: TachiJ2K 1.0.9 (Based on Tachiyomi)
- Android version: Android 10

## Source information
- Name:  CopyManga / 拷贝漫画
- Extension version: 1.2.3

## Steps to reproduce
Open random manga chapters list page or reading random manga chapter

### Expected behavior
The list/manga should load perfectly.

### Actual behavior
```
Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.attr(Java.lang.string)' on a null object reference
```

![](https://i.loli.net/2020/12/08/8nu6paPA5w21VxK.png)
![](https://i.loli.net/2020/12/08/vfk78YSFLJMEydx.jpg)

## Other details
Proxy used, and manga can load perfectly in Webview.

When met this error, the full manga list for the site (Enter by clicking source) would back "No Results Found" error, and Webview can access without any problem in the meantime.

This situation may occur intermittently. When the connection is smooth, you can read it normally. When you encounter this error or you cannot load the comic list, you may be able to rebuild the connection by repeatedly retrying.

When this happens, the comic global search will not return the results, and entering the comic source page alone may improve the situation.

**Comment by sunbeams001** [comment]
What is your ISP, and what if not using proxy?

**Comment by LenKiMo** [comment]
I am using China Mobile. Without using proxy seems works fine, but it occurs randomly I cna't figure it out soon.
I was wondered whether mainland IP can access all mangas on it or not. So I add it to proxy from start. Is this actually needed?

**Comment by sunbeams001** [comment]
@LenKiMo My ISP is CUCC, and it seems that copymanga has no IP restriction for now.
Is such error happens on certain mangas or certain time?

**Comment by LenKiMo** [comment]
Nope, randomly in the main, no certain time, no certain manga, and still can view in Webview page in the meantime.
If there is not any IP restriction, I would try to remove it from proxy list and keep an eye on it next few days, then check if this would heapen again.

**Comment by LenKiMo** [comment]
Since the situation doesn't appear after move site out from proxy list, close the iuuse at this time.

**Comment by LenKiMo** [comment]
I noticed that even I add `copymanga.com` into no-proxy list, it still may met this error when using Japan IP.
Therefore I guess there are some domain used in the site other than `copymanga.com`, could you please check if there any CDN or Image Server domain?

**Comment by sunbeams001** [comment]
@LenKiMo Seems there is IP restriction with Japan users for copyright reason.
![image](https://user-images.githubusercontent.com/3478170/102439811-ef8a0900-4059-11eb-8ba2-e727cce699f1.png)

**Comment by LenKiMo** [comment]
Yes, it is. I think might need to add `mangafanc.fun` too but might need take some time to take effects.
