### ISSUE TITLE
mangawww reader is not working

### ISSUE THREAD

**Issue by aprilxxx** [inorichi/tachiyomi-extensions#506]
it worked fine maybe like a month ago and now it completely stopped working

![img_20180922_190842](https://user-images.githubusercontent.com/43500472/45919480-57167580-be9e-11e8-91aa-ca770475b129.png)

tachiyomi 0.7.4

**Comment by CarlosEsco** [comment]
Website is not working. Might be gone for good

**Comment by arkon** [comment]
Maybe we should keep this open until it's removed from the extension?
