### ISSUE TITLE
[Bug] Neox Scanlator: Change of Domain

### ISSUE THREAD

**Issue by maz1no** [inorichi/tachiyomi-extensions#5066]
## Device information
- Tachiyomi version: 0.10.5
- Android version: 8.1.0

## Source information
- Name: Neox Scanlator (Madara Multi-sources)
- Extension version: 1.2.154

### Actual behavior
Neox Scanlator just changed their domain to neoxscans.net and it needs to be updated to work again

## Other details
Just this:
![Screenshot_20201209-042934](https://user-images.githubusercontent.com/38970314/101599447-89a5dd80-39d8-11eb-986b-c8e68196ca9f.png)

**Comment by Douglasimav** [comment]
has not changed the domain, the site is down for maintenance.

**Comment by matheuswr89** [comment]
Wrong, the site has changed domain, the new domain is https://neoxscans.net/

**Comment by matheuswr89** [comment]
![Screenshot_20201209-120700~2](https://user-images.githubusercontent.com/44068234/101647141-26876b80-3a17-11eb-8704-9e0cb4d23413.png)
The old site still works, but the site in general has been moved

**Comment by Douglasimav** [comment]
open the skit again

**Comment by maz1no** [comment]
Lol bro I also included the new domain and you say I'm wrong... lol

**Comment by Douglasimav** [comment]
> Rsrs mano Eu também incluí o novo domínio e você diz que estou errado ... rsrs

foi mal, o site anterior tava dizendo que tava em manutenção kk

**Comment by Vitor1782** [comment]
So o alessandro pode nos salvar

**Comment by matheuswr89** [comment]
@alessandrojean dá uma olhadinha aí
