### ISSUE TITLE
[Source Request] manhwa18.net

### ISSUE THREAD

**Issue by shortbach** [inorichi/tachiyomi-extensions#5083]
---

## Source Website
- Name: manhwa18
- Link: manhwa18.net
- Language(s): English

## Other Details
it has +18 contents

**Comment by CrepeTF** [comment]
Already exists.
Refer to the spreadsheet:
https://tachiyomi.org/extensions-spreadsheet

**Comment by shortbach** [comment]
> 
> 
> Already exists.
> Refer to the spreadsheet:
> https://tachiyomi.org/extensions-spreadsheet

I see, but it has multiple source. Could I please just have this 1 extension for this source?

**Comment by CarlosEsco** [comment]
at this time, no.
