### ISSUE TITLE
[Bug] <Mangalib: <nothing is loading>

### ISSUE THREAD

**Issue by Kugumin** [inorichi/tachiyomi-extensions#5092]
## Device information
- Tachiyomi version: 1.3.1 (SY)
- Android version: 10

## Source information
- Name: Mangalib
- Extension version: 1.2.24

## Steps to reproduce
1. Open source
2. Choose any manga, manhwa, etc.
3. Try to read/download it

### Expected behavior
It should have loaded and showed a page/downloaded it

### Actual behavior
It doesn't load it at all.

## Other details
Reading from the source itself is fine, only in app it's broken

**Comment by VlasovRoman** [comment]
I confirm. Manga pages don't loads.
