### ISSUE TITLE
[Source Request] <KoMBatch>

### ISSUE THREAD

**Issue by ReyVnD** [inorichi/tachiyomi-extensions#5094]
**PLEASE READ THIS**

I acknowledge that:

- I have checked that the extension does not already exist:
  - In the list of existing extensions in the application
  - In the multi-source spreadsheet: https://tachiyomi.orextensions
  - By searching the GitHub repository for the extension and verify it does not appear in the code base
- I have searched the existing GitHub issues and this extension does **NOT** have an open request
- I will fill out the title and the information in this template

---

## Source Website
- Name: KoMBatch
- Link: https://kombatch.com/
- Language(s): Indonesian

## Other Details
The fastest Tensura translator.

**Comment by Riztard** [comment]
already added, next time read acknowledgment.  
check in acknowledgment list
