### ISSUE TITLE
[Source Request] <Bacamanga>

### ISSUE THREAD

**Issue by willyreza** [inorichi/tachiyomi-extensions#5106]
## Source Website
- Name: Bacamanga
- Link: https://bacamanga.cc
- Language(s): Indonesian

## Other Details
👍👍👍

**Comment by AriaMoradi** [comment]
duplicate?

**Comment by CarlosEsco** [comment]
It already exists https://github.com/inorichi/tachiyomi-extensions/pull/5088

**Comment by CarlosEsco** [comment]
Or is that a different indonesian baca site?

**Comment by Riztard** [comment]
its different

**Comment by willyreza** [comment]
Diffrent site
