### ISSUE TITLE
[Bug] <extension MangaLib 1.2.25>: <stopped loading pages.>

### ISSUE THREAD

**Issue by ybapabeu** [inorichi/tachiyomi-extensions#5110]
## Device information
App version: 0.10.5 (standard, 2769e27a2, 51)
Android version: 10 (SDK 29)
Android build ID: QKQ1.190910.002 V11.0.17.0.QDIMIXM
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: jasmine_sprout
Device model: Mi A2
Device product name: jasmine

## Expected behavior
Updated the MangaLib extension to version 1.2.25 and again stopped loading pages

**Comment by Kugumin** [comment]
Yep, it's still dead!

**Comment by arkon** [comment]
#5112
