### ISSUE TITLE
[Source Request] <Webtoon.xyz>

### ISSUE THREAD

**Issue by ErenYeagar** [inorichi/tachiyomi-extensions#5114]
Please add this source it's really good for all kind of manhwa

## Source Website
- Name: Webtoon.xyz
- Link: https://www.webtoon.xyz/
- Language(s): English

## Other Details
?

**Comment by arkon** [comment]
It's in Madara.

**Comment by ErenYeagar** [comment]
> It's in Madara.

Thank you 😄
