### ISSUE TITLE
[Bug] <Manhuaren>: <The cover of the manga was cut inappropriately>

### ISSUE THREAD

**Issue by History-exe** [inorichi/tachiyomi-extensions#5117]
## Device information
- Tachiyomi version: Stable 0.10.5
- Android version: Android 7.1.2

## Source information
- Name: Manhuaren
- Extension version: 1.2.7

## Steps to reproduce
1. First Step
To search for comics globally, it is normal to preview comic covers under the search results of comics.
2. Second Step
Then click to enter the comic details interface, which should also be the cover, as shown in the figure.
![photo_2020-12-13_17-01-55](https://user-images.githubusercontent.com/33642965/102008893-ad697a80-3d6e-11eb-8a35-956593c69856.jpg)

### Expected behavior
The cover of the comic details interface should be exactly the same as the cover of the search interface, without any cropping.

### Actual behavior
But after clicking to enter the comic details interface, the comic cover was cut very inappropriately. As shown.
![photo_2020-12-13_17-02-01](https://user-images.githubusercontent.com/33642965/102008928-fc171480-3d6e-11eb-9405-d3eb0a93a1b9.jpg)

## Other details
Now this problem is not the case with every comic, but only a small part of it is normal, and most of them are displayed abnormally. The cover of the detail interface looks like it has been enlarged and cropped.

**Comment by arkon** [comment]
1. Wrong repo.
2. Both are cropped for consistency.
3. There's an existing issue to be able to preview the cover.

**Comment by History-exe** [comment]
I'm very sorry, but I still want to ask, the covers of the two interfaces of this source are inconsistent. Can this be resolved?

The cover of the details interface now looks terrible.

**Comment by History-exe** [comment]
>     1. Wrong repo.
> 
>     2. Both are cropped for consistency.
> 
>     3. There's an existing issue to be able to preview the cover.

I'm very sorry, but I still want to ask, the covers of the two interfaces of this source are inconsistent. Can this be resolved?

The cover of the details interface now looks terrible.
