### ISSUE TITLE
[Source Request] <manhwa.men>

### ISSUE THREAD

**Issue by fawadkhan121** [inorichi/tachiyomi-extensions#5126]
**PLEASE READ THIS**

I acknowledge that:

- I have checked that the extension does not already exist:
  - In the list of existing extensions in the application
  - In the multi-source spreadsheet: https://tachiyomi.org/extensions
  - By searching the GitHub repository for the extension and verify it does not appear in the code base
- I have searched the existing GitHub issues and this extension does **NOT** have an open request
- I will fill out the title and the information in this template

## Source Website
- Name: manhwa.men
- Link: https://manhwas.men/
- Language(s): english 

## Other Details
18 + manhwas
Please add it in madara extension thanks

**Comment by scb261** [comment]
Read the acknowledgment section, you can find it by searching in the spreadsheet or github.
https://github.com/inorichi/tachiyomi-extensions/blob/a239a5856236f3281460185f539871b44b294cfe/src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/Generator.kt#L240

And why would you want it in madara extension, it doesn't use the madara theme.

**Comment by fawadkhan121** [comment]
Ok sorry for the trouble and thanks for the assist and please check ok mangajb source request please
