### ISSUE TITLE
Mangaseeonline changed domain

### ISSUE THREAD

**Issue by thecbass2** [inorichi/tachiyomi-extensions#516]
Mangasee url changed form mangaseeonline.net to mangaseeonline.us. 

As is you an w3

Tachiyomi version is 0.7.4

**Comment by CarlosEsco** [comment]
Install the extension 1.2.2 this already fixed

**Comment by thecbass2** [comment]
Sorry what is the extension 1.2.2 and where can I find that to install it?

**Comment by CarlosEsco** [comment]
On the side menu in app click extensions then find mangasee and install

**Comment by thecbass2** [comment]
Ahhhhh well that was derp of me. Thank you very much! :)
