### ISSUE TITLE
[Question] Module inheritance

### ISSUE THREAD

**Issue by hey-red** [inorichi/tachiyomi-extensions#518]
[Mangalib](https://github.com/inorichi/tachiyomi-extensions/blob/master/src/ru/mangalib/src/eu/kanade/tachiyomi/extension/ru/mangalib/Mangalib.kt) and [Yaoilib](https://github.com/inorichi/tachiyomi-extensions/blob/master/src/ru/yaoilib/src/eu/kanade/tachiyomi/extension/ru/yaoilib/Yaoilib.kt) use same engine(and actually have one database). 
What I want to do is just inherit mangalib in yaoilib module and override 3 properties. 
I can do this?

**Comment by CarlosEsco** [comment]
Yes but I would refector it all to something similar to like foolslide extension

**Comment by hey-red** [comment]
@CarlosEsco Ok, thanks. If I correctly understood, that I can leave mangalib extension and add yaoilib as a Source?

**Comment by CarlosEsco** [comment]
Yes but I would just make a common extension called like libManga. Then have both mangalib and yaolib extend it like the foolslide extension. Look at it for an example

**Comment by Pavkazzz** [comment]
Same one for [MintManga](http://mintmanga.com), [SelfManga](http://selfmanga.ru), [ReadManga](http://readmanga.ru). Literally same sites
