### ISSUE TITLE
Sources for Marvel/DC comics?

### ISSUE THREAD

**Issue by cacamarena42** [inorichi/tachiyomi-extensions#53]
(CATALOGUE) SOURCE REQUESTS:
  One source per issue, create more issues if you have more websites
  Check for duplicates, use search (in issues, not the global one)
  Put the name of the site as Title, replace this text with clickable link to the site
BUGS:
  Provide tachiyomi version as well as version of source the report is about

**Comment by j2ghz** [comment]
en.readcomiconline and en.readcomictv already exist. If you have a concrete site in mind, post that.

**Comment by pokemontotalwar** [comment]
@j2ghz en.readcomictv is dead, I'm getting no links on the app or with a browser. Why is it still here?

**Comment by strugler** [comment]
The following all a great sources for new extensions, i just hope you guys implemenet them to replace readcomics.tv

http://readcomicbooksonline.net/

http://readcomics.website/

http://www.comicextra.com/

**Comment by j2ghz** [comment]
@strugler In issue template it says how to ask for a site to be added
```
(CATALOGUE) SOURCE REQUESTS:
  One source per issue, create more issues if you have more websites
  Check for duplicates, use search (in issues, not the global one)
  Put the name of the site as Title, replace this text with clickable link to the site
```

**Comment by j2ghz** [comment]
This issue should be closed
