### ISSUE TITLE
[Portuguese] baixarhentai.net

### ISSUE THREAD

**Issue by mrdroops** [inorichi/tachiyomi-extensions#537]
Hello, can you add this site?

https://baixarhentai.net/

Thank You.

**Comment by as280093** [comment]
Here the Icons
[baixarhentai.net.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614853/baixarhentai.net.zip)

**Comment by alessandrojean** [comment]
I think it's very hard to create an extension for this site. Besides they do have an API for search and stuff like that, the links to the chapters use redirectors that can't be skipped.

They have a bunch of self hosted sites using FoolSlide, so its too hard to unite them to even do some kind of search. So, in the way they work now, nothing can be done unfortunately.

If some day they change the website and remove the redirectors, an extension can be created.

**Comment by SnakeDoc83** [comment]
Opened a PR to add this to Foolslide.  If there are doujins you can find through their website that aren't in their Foolslide reader (because they're hosted on a different domain) open a separate issue.
