### ISSUE TITLE
request for readcomiconline.to

### ISSUE THREAD

**Issue by H3rmit** [inorichi/tachiyomi-extensions#540]
(CATALOGUE) SOURCE REQUESTS:
  One source per issue, create more issues if you have more websites
  Check for duplicates, use search (in issues, not the global one)
  Put the name of the site as Title, replace this text with clickable link to the site
BUGS:
  Provide tachiyomi version as well as version of source the report is about
id really like to see this source added 
readcomiconline.to

**Comment by CarlosEsco** [comment]
As we discussed on discord the .ru is redirecting to .to so closing this
