### ISSUE TITLE
[English][R18+] 8muses.com

### ISSUE THREAD

**Issue by Xeiniac** [inorichi/tachiyomi-extensions#542]
**Source Request**

I want to request an **English** source:
www.8muses.com

Thanks in advance :D

**Comment by joseph619** [comment]
Requesting this as well, it has a huge amount of 18+ western comics not found on ehentai or other hentai sites.

**Comment by gediefedilo1123** [comment]
I request this source as well the're some good 18+ wetern comics out there that e-hentai can't upload

**Comment by joseph619** [comment]
8muses will be available on TachiyomiEh soon

**Comment by as280093** [comment]
Here the icons
[8muses.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614845/8muses.zip)

**Comment by AriaMoradi** [comment]
I don't think the structure of the site would work with tachi's current extension model;
the site exposes countless sources within itself, and some sources are nested(source withing source).

maybe by crawling the site and concatenating source names and manga names It would be possible to make a flat list, but I don't think it's worth/practical.

Maybe circumstances would change with the release of rewrite's model but for the foreseeable future n

**Comment by joseph619** [comment]
@AriaMoradi You can check TachiyomiEh's implementation of it below, since nulldev already added the source to his fork. 

https://github.com/NerdNumber9/TachiyomiEH/commit/d69dc375a3f222e72dac39031eac40519cb5b794
