### ISSUE TITLE
MyReadingManga not working 

### ISSUE THREAD

**Issue by ccrowles** [inorichi/tachiyomi-extensions#544]
It won't load chapters nor Manga covers. 

Tachiyomi dev build r1427, all extensions updated

**Comment by ccrowles** [comment]
Most of the manga still don't load, and the covers are broken.
![screenshot_20181012-004606](https://user-images.githubusercontent.com/12866474/46868392-744cbd00-ce28-11e8-8ba0-d2e30f2602b0.png)
![screenshot_20181012-140744](https://user-images.githubusercontent.com/12866474/46868408-8169ac00-ce28-11e8-9e90-48944631b96f.png)

**Comment by CarlosEsco** [comment]
So search covers seem broken now. They weren't when I tested. For the covers during browse you need to clear DB in settings this will delete the saved urls and chapter urls for manga not in library. Then you will see covers and chapters working.  I verified your 2ns screen shot and it loads for me

**Comment by ccrowles** [comment]
I cleared the database in settings, but the covers are still broken and chapters still do not load.

**Comment by CarlosEsco** [comment]
it looks like they change again.. will look to push a new build

**Comment by CarlosEsco** [comment]
yw sorry didnt realize chapters were broken when i pushed the build.

**Comment by Loiue** [comment]
My reading manga not working. Keep saying error 521
