### ISSUE TITLE
Mangadex broken

### ISSUE THREAD

**Issue by tidux** [inorichi/tachiyomi-extensions#553]
The Mangadex catalogue is broken and shows as empty when I try to browse it.  O can also not use search or update new chapters.

**Comment by CarlosEsco** [comment]
Can you get on discord and ask for help in the support channel. Mangadex is working fine so someone in channel can help you debug

**Comment by tidux** [comment]
Update: looks like it was an issue resulting from an Android OS upgrade 7.x->8.x.  Clearing Tachiyomi's cache and reinstalling the Mangadex extension worked.
