### ISSUE TITLE
Have a way to remove extensions from the repo

### ISSUE THREAD

**Issue by arkon** [inorichi/tachiyomi-extensions#557]
Removing an extension involves removing the code, but it'll still exist in the list of available extensions/APKs.

We should have a better way to remove things, potentially automated (remove everything if the code is gone), or some script.

**Comment by CarlosEsco** [comment]
Unrelated but Ideally what I would love is if testing framework was setup somehow that would verify each extension. If it failed would either add source broken text to json. Then in extensions page of main app it could populate a text view mentioning it was broken.

**Comment by arkon** [comment]
I guess removing things is pretty rare so it's fine to do it manually.
