### ISSUE TITLE
[Spanish] https://tumangaonline.com/

### ISSUE THREAD

**Issue by scese250** [inorichi/tachiyomi-extensions#56]
Spanish source: https://tumangaonline.com/

**Comment by edgarMejia** [comment]
I would also like this source.
There's not yet one for Spanish.

**Comment by mauricioMart9** [comment]
Please, add this source.
Thanks in advance!

**Comment by Irvineflon** [comment]
I just did some research on this one last weekend. I just don't have the time right now, but this should be a easy one. They have a rest API, all responses as JSON, no HTML parse needed.

**Comment by arkon** [comment]
I'll work on this.

**Comment by edgarMejia** [comment]
Hi arkon, I'm working on this source but I have some bugs and I can't fix it.

Te extension is 95% complete.

Please contact me if you like to help me.
My email: edgar13155@gmail.com

https://github.com/edgarMejia/tachiyomi-extensions/blob/TuMangaOnline/src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt

**Comment by arkon** [comment]
@edgarMejia Awesome! Sent you an email.
