### ISSUE TITLE
[TMO] http error 504/503

### ISSUE THREAD

**Issue by MerradOklom** [inorichi/tachiyomi-extensions#561]
First than nothing thank you for adding TuMangaOnline extension. I tried reading a manga but I got a message saying "http error 503", went back and selected the same chapter and pages loaded normally, then in the next chapter I got a "http error 504", and I'm getting the same in all the mangas I choose to read (I must clarify thus I got only when selecting the chapters, everything else is working fine).

**Comment by arkon** [comment]
Which manga? Does this happen consistently on different networks?

**Comment by edgarMejia** [comment]
Prueba cargando TMO desde el navegador de tu dispositivo, luego ve a tachiyomi > configuraciones avanzadas > limpia el cache y las cookies. Cierra y vuelve a abrir la aplicación.

**Comment by MerradOklom** [comment]
@arkon I'm using WiFi, I don't have a data plan so I can't tell if it is the same or not, but I get this this message in every manga: https://ibb.co/mnbAd0

@edgarMejia Ya lo intenté pero aún me aparece el mismo mensaje, aunque desde el navegador puedo acceder sin problemas

**Comment by MerradOklom** [comment]
@CarlosEsco

**Comment by CarlosEsco** [comment]
why are you pinging me?

**Comment by MakuSensei** [comment]
try this if it works for TMO https://github.com/raulhaag/MiMangaNu/blob/hybrid_plugin/js_plugin/22.js
In MiMangaNu works as well TMO

**Comment by edgarMejia** [comment]
@MakuSensei In MeMangaNu he build al js function to get the canvas images, but in our case we are geting de images directly from the page, so our problem are the headers.

**Comment by mll-Kerberos** [comment]
I just made a pull request fixing this issue, seems to work fine now.

**Comment by edgarMejia** [comment]
> I just made a pull request fixing this issue, seems to work fine now.

Cool! Maybe it fix the issue.

**Comment by mll-Kerberos** [comment]
It has been merged, I just updated and checked and it's working fine, please check and confirm if you can.

**Comment by MerradOklom** [comment]
Just updated too, and I have encountered no problem so far. Thank you!

**Comment by edgarMejia** [comment]
Works perfect, thanks @mll-Kerberos
