### ISSUE TITLE
MangaRock not updating

### ISSUE THREAD

**Issue by felixalguzman** [inorichi/tachiyomi-extensions#569]
When I refresh my library not all the mangas in mangarock are shown in the list of updates, only if I go to the specific ones and update there, sorry for bad english.

Mangarock version : 1.0.2
Tachiyomi version: 0.8.0

**Comment by arkon** [comment]
Which manga?

**Comment by felixalguzman** [comment]
Peerless Dad, Haikyuu!!, The God of HighSchool, D.I.C.E., God of Martial Arts and many others

**Comment by joseph619** [comment]
Try switching to Mangadex to see if it works. Sometimes they update late. I have no issue on my end.

**Comment by as280093** [comment]
Close this issue as the error is related to MangaRock side they don't update due to legal matters or if they don't have a source to scrap from, i have confirmed it from their support staff.
