### ISSUE TITLE
MyReadingManga - Page list is empty + over pages(?)

### ISSUE THREAD

**Issue by missimperfect** [inorichi/tachiyomi-extensions#588]
Hii, sorry for troubling you guys again. But I wasn't able to open **chapter 7** of "**Gelateria Supernova**" in MRM as it gave me "Page list is empty" issue. And I was trying to download "**The Grandmaster of Demonic Cultivation**" webtoon and on of the chapter: **Chapter 16** gave me error message. I tried to compare chapter 16 in MRM website and it seems that the chapter 16 in Tachiyomi has more pages than the MRM website itself. Would be glad if you guys can take a look at it. Thank you.

**Comment by mll-Kerberos** [comment]
I'll take a look at it later, thanks for reporting.

**Comment by mll-Kerberos** [comment]
@missimperfect Both issues have been fixed in the last version of MyReadingManga extension, please update and try again. Thanks for reporting!

**Comment by mawee16** [comment]
I have the same problem with my latest version of MyReadingManga extension I tried opening different manga in the app but it says page list empty then when I tried opening it via my browser the manga is ok

**Comment by CarlosEsco** [comment]
@mawee16 don't comment on closed issues.  There is an open issue so until there is a fix it is broken
