### ISSUE TITLE
[Webcomics] Certain chapters locked to app-only

### ISSUE THREAD

**Issue by einstein95** [inorichi/tachiyomi-extensions#590]
Tachiyomi 0.8.0
Webcomics 1.2.1

Attempting to read [Holding Onto Him](http://www.webcomicsapp.com/reader.html?mangaId=5ad1f0d45bf9ca5e2e657ad0), [chapter 21](http://www.webcomicsapp.com/reader.html?mangaId=5ad1f0d45bf9ca5e2e657ad0&index=21) or up gives an error in Tachiyomi of "page list is empty". Attempting to read these chapters on the website gives a modal box with
```
You can read more wonderful in WebComics app.
Many interactions between creators
and readers are waiting for you~
```

As the current implementation uses the website, this cannot be fixed until it gets ported to use the API which uses encryption/obfuscation on the commands to the server.

**Comment by Anutrix** [comment]
Waiting for this. As it was the only source for a lot of Manhua.

**Comment by Mystique0414** [comment]
I agree I'm waiting for this too 😢
