### ISSUE TITLE
Mangadex gives error when trying to open a chapter

### ISSUE THREAD

**Issue by 1ll3g4l** [inorichi/tachiyomi-extensions#594]
<img src='https://i.imgur.com/HllE5jH.png'></img>

This is the error I get whenever I open a chapter for some certain mangas, it has happened with baki and black clover, they used to worked fine at first but suddenly I can't open the chapters anymore without this error.

Tachiyomi V 0.8.0
Mangadex V 1.2.41

**Comment by CarlosEsco** [comment]
They changed api a few versions ago. Swipe down to refresh chapter list and it should resolve issue

**Comment by 1ll3g4l** [comment]
Thank you
