### ISSUE TITLE
The Gamer not showing up in MangaRock

### ISSUE THREAD

**Issue by pixelPROPER** [inorichi/tachiyomi-extensions#596]
I'm currently migrating my library from the Manga Rock app (Version 3.6.3_definitive) but noticed that the series The Gamer doesnt come up when I search for it using the Manga Rock extension. It shows up in the Manga Rock app itself perfectly fine though. Thinking about it, it might be because I'm using the definitive version of the app that it comes up. I assume it might be excluded from the extensions search since it mimics the Google Play version of Manga Rock where series are excluded for licensing reasons?

Tachiyomi 0.8.0
Manga Rock extension 1.0.3

Anyway, I've already added it from another source but thought I might as well mention it here.

**Comment by arkon** [comment]
Shows up fine for me.

**Comment by pixelPROPER** [comment]
It does seem to be excluded for me in the USA. Using a VPN and connecting through France allows me to see the whole list with all the missing series. Without the VPN there's a bunch missing. 

The thing is that all these missing series show up just fine in the Manga Rock app without a VPN. 
![screenshot_20181102-161011_tachiyomi](https://user-images.githubusercontent.com/11582561/47941953-32aab180-debe-11e8-9f9d-3607dab57f3f.jpg)
![screenshot_20181102-161153_tachiyomi](https://user-images.githubusercontent.com/11582561/47941954-32aab180-debe-11e8-9ede-0cf86c3d3a45.jpg)

I did notice that I can add those region blocked manga while the VPN is connected and still access them perfectly when the VPN is disconnected.

**Comment by CarlosEsco** [comment]
I am guessing then they are blocking them on the search which if that's case I don't know if there is anything we can do on our end

**Comment by joseph619** [comment]
Manga Rock has region lock, so you can't read it without VPN if you're not in the region. This is not a Tachiyomi issue.
