### ISSUE TITLE
fixe Japscan Search

### ISSUE THREAD

**Issue by tom2411** [inorichi/tachiyomi-extensions#610]
Can You Fix the search of a manga on Japscan ? Because at every search it don't find the right mang that I want.

**Comment by arkon** [comment]
Does the search work properly on the website?

**Comment by tom2411** [comment]
Sorry i saw on the web site that there isn' t any search bar

**Comment by arkon** [comment]
Is this still an issue with the latest version?

**Comment by pokke456** [comment]
I think all is alright, the website recently add a search bar et the latest version of the extention already support it

**Comment by arkon** [comment]
Seems to work fine.
