### ISSUE TITLE
Mangarock share url incorrect

### ISSUE THREAD

**Issue by dhanjit** [inorichi/tachiyomi-extensions#613]
Tachiyomi version: 8.0
Mangarock 1.0.3

Open manga from library. Click share, share to hangouts. The url I get is https://api.mangarockhd.com/query/web400/info?oid=mrs-serie-94244

**Comment by arkon** [comment]
This is sort of a limitation of Tachiyomi and how the extension was implemented (directly using the API instead of scraping pages). I don't think it'll be "fixed" anytime soon.
