### ISSUE TITLE
[Issue] manhuaren extension crashes and exits app when opening

### ISSUE THREAD

**Issue by lilli34556** [inorichi/tachiyomi-extensions#614]
Tachiyomi version : v0.80
Extension version : v1.2.2
Extension name : manhuaren

After I install the catalog and I try to browse or look at the latest releases the app crashes and brings me back to my home screen.
This is on a kindle fire 8 HD, all the other extensions work on my device no problem.

**Comment by SeriousMatters** [comment]
I also experience the same issue with manhuaren extension
Under Catalogues, tapping either 'LATEST' or 'BROWSE' will crash Tachiyomi and exit to home screen

**Comment by arkon** [comment]
What version of Android are your devices on?

**Comment by lilli34556** [comment]
> What version of Android are your devices on?

It's using amazon's 5.6.2.0 which is equivalent to android lollipop
