### ISSUE TITLE
[issue] [JapScan] No thumbnail and only few mangas available

### ISSUE THREAD

**Issue by Daegnor** [inorichi/tachiyomi-extensions#616]
Tachiyomi version:0.8.0
JapScan version:1.2.3

The thumbnails are not working and there are only a few mangas compared to the website (I think that the mangas available are the ones from the "Top Manga of the Week" section)

**Comment by Daegnor** [comment]
Update : You have access to the Manga of the Week when exploring the "Browse" section of JapScan, you have access to other mangas when exploring the "Latest" section and you have to a few more manga by searching a manga (because you can't search for a manga on the website, when you do it on the app it will show you the firsts mangas in the alphabetical order). So it's hard, if not impossible, to find a certain manga.

**Comment by arkon** [comment]
Is this still an issue with the latest update?

**Comment by Daegnor** [comment]
The "Browse" section is still showing only a few mangas but you can search for a manga and the thumbnails are working so I would say it's fixed.
