### ISSUE TITLE
Mangafree

### ISSUE THREAD

**Issue by EtorixGaming** [inorichi/tachiyomi-extensions#619]
http://mangafree.online/

Versions:
Tachiyomi: 0.8.0
Mangafree: 1.2.2

Bug:
Searches often do not display the intended manga first and may not display it at all in the catalog due to being pushed down too far.

Cause:
Mangafree searches by keyword. When you search "A summer day", you'll actually be searching "A".

Fix:
Searching "Asummerday" instead will yield the intended result. As this is one word, the entire thing will be used as the keyword, and for whatever reason Mangafree still displays the correct results with an elongated keyword. So by forcing Mangafree to return results for "Asummerday" when users actually search "A summer day", correct results will be displayed.

Example Images:
![example 1](https://user-images.githubusercontent.com/34699938/48673103-cb624380-eaf2-11e8-92de-7eb3b04444b7.png)
![example 2](https://user-images.githubusercontent.com/34699938/48673104-cbfada00-eaf2-11e8-924e-cfef71788c19.png)
![example 3](https://user-images.githubusercontent.com/34699938/48673105-cbfada00-eaf2-11e8-8764-c9136deb250f.png)
![example 4](https://user-images.githubusercontent.com/34699938/48673106-cbfada00-eaf2-11e8-9877-70e3e5bdb1f8.png)
![example 5](https://user-images.githubusercontent.com/34699938/48673107-cbfada00-eaf2-11e8-80b4-4b4f0b2401e4.png)
![example 6](https://user-images.githubusercontent.com/34699938/48673108-cbfada00-eaf2-11e8-92d9-1fef4df01e20.png)

**Comment by arkon** [comment]
Are the results you see the same as what you'd see on the website?

Also as a side note, this site looks the same as MangaKakalot/MangaHasu.

**Comment by arkon** [comment]
Closing in favour of #1475
