### ISSUE TITLE
MangaFox is broken

### ISSUE THREAD

**Issue by hstark16** [inorichi/tachiyomi-extensions#620]
around 3 days ago, when i open catalogue, mangafox, it says "no results found", and when i download mangafox from my library it days "page list empt", it happen in previous version, then i update the app, but the problem still there

**Comment by lukexj** [comment]
I also get this issue

**Comment by MotorHorse** [comment]
Same issue

**Comment by Zero992** [comment]
Same issue here. It seems they haven't just changed look of their site, but probably something else that bugs extension.

**Comment by polydoo** [comment]
Same here. And yesterday I changed my whole library from mangafox to mangarock due to this issue, and today mangarock is "value unknown...java.lang.....JSONArray". I give up 😐

**Comment by arkon** [comment]
Using only one source is always a mistake. The MangaRock issue was fixed though, update the extension.

**Comment by 07shadow** [comment]
Same issue here.

**Comment by CarlosEsco** [comment]
This is a known issue now please stop commenting that you are having the issue.

**Comment by Flat** [comment]
@CarlosEsco I get no results found on mangafox though

**Comment by TNTKit** [comment]
Anyone knows when will it be fixed or stop?
