### ISSUE TITLE
Problem to Open wiemanga Pictures

### ISSUE THREAD

**Issue by kipferl2** [inorichi/tachiyomi-extensions#624]
Every time i Open a manga from wiemanga it displays the Massage: Image could not be decodet.
If i open it in the Browser i got the Error: The image ... cannot be displayed because it contains errors.

On the Website direktly everthing is fine.

**Comment by ROMSY-SAN** [comment]
maybe a helpful information: it seems like it tries to grab the wrong image.
for example one piece.
Link to the Page: https://img.wiemanga.com/comics/pic/37/229/209704/Kapitel937_0_867.png
but if you open int in tachiyomi (and then tell it to open it in the browser) it tries to open: https://img.wiemanga.com/comics/pic/37/229/209704/(superlongrandomstuffofcharacters).png

**Comment by CarlosEsco** [comment]
its using some kinda of validation, dont know what exactly maybe cookie or referrer
