### ISSUE TITLE
Missing new genre from manga rock extension

### ISSUE THREAD

**Issue by Taxiozaurus** [inorichi/tachiyomi-extensions#635]
A new category has been recently added to MangaRock

To be specific *Isekai*: https://mangarock.com/genre/mrs-genre-100291868

By the looks of it it should be added somehwere around here https://github.com/inorichi/tachiyomi-extensions/blob/master/src/en/mangarock/src/eu/kanade/tachiyomi/extension/en/mangarock/MangaRock.kt#L295

```kt
Genre("Isekai", "mrs-genre-100291868"),
```

Have no idea about fork and external PR polilcy so am opening an issue

**Comment by arkon** [comment]
PRs are welcome.
