### ISSUE TITLE
MyReadingManga - Page List is Empty

### ISSUE THREAD

**Issue by LinMikan** [inorichi/tachiyomi-extensions#643]
Tachiyomi v 0.7.4
Extension v 1.2.16
I just updated the extension today and I thought it will be fixed since another issue like this was already closed. It's still giving me the same error. I bookmark multiple mangas at a time and download them straight as well, but nothing's been downloaded so I can say this happens to most of the mangas in this extension. Not that I succeeded opening one without any problems. I would really love to read from this extension since they're mostly updated. Please resolve. Thank you.

**Comment by happywillow0** [comment]
MRM updates their site sometimes with new ways of loading images for their manga. The last fix was an attempt by me and was coded based on their "current" way of loading images. This however means that some older manga that you have bookmarked is now broken (sorry)

If you have a specific manga and wish to provide a link or title (something that complies with any rules but enough that someone can look up the page), we may be able to take a look but I can't guarantee any timeline on fixes as I'm also self teaching as I go.

**Comment by LinMikan** [comment]
Tried refreshing the chapter list, cleared cache and cookies and unbookmark refreshed and bookmarked again but it's still the same. There are mangas that you can only find in MRM especially doujins. I'm going to wait and use other sources for the meantime but I hope it gets fixed as this the only reader I know that has extension for MRM. Thank you so much for replying. If there are other troubleshootings I can do, please tell me?
