### ISSUE TITLE
[ISSUE] HTTP error 503 on Mangahasu

### ISSUE THREAD

**Issue by aestopian** [inorichi/tachiyomi-extensions#646]
tachiyomi (v.0.8.0)
Mangahasu (v.1.2.2)
BUGS:
This problem is still on (no new), It cannot let me download any manga/manhua from Mangahasu, As well as reading it.
Screenshot below

**Comment by aestopian** [comment]
![screenshot_20181128-210846](https://user-images.githubusercontent.com/43212375/49154081-788a5680-f352-11e8-938d-29deedba469d.png)

**Comment by CarlosEsco** [comment]
Does it work on their website from your device?  503 usually means you can't.

**Comment by aestopian** [comment]
![screenshot_20181128-214354](https://user-images.githubusercontent.com/43212375/49155800-cef99400-f356-11e8-9ee7-6ef4aa483707.png)
It does, actually.

**Comment by aestopian** [comment]
There are two more people having the same issue, so is it a common issue?

**Comment by CarlosEsco** [comment]
Does the chapter? In original screen shot work on your device on the website on the same network the original screen shot was using

**Comment by CarlosEsco** [comment]
I'm not saying it's not but when you look up 503 this is general usage. 503 Service Unavailable. The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.  Which if that's the case it's not a tachiyomi issue. But if it's working on web fine then it's probably an extension issue

**Comment by aestopian** [comment]
It perfectly works on the website.
![screenshot_20181128-215251](https://user-images.githubusercontent.com/43212375/49156333-0e74b000-f358-11e8-8201-a75aa4ad20b6.png)

**Comment by CarlosEsco** [comment]
Ok thanks for the screen shots

**Comment by aestopian** [comment]
Thanks for addressing the issue! More powers on tachiyomi, then.

**Comment by CarlosEsco** [comment]
Also next time post it on the existing issue. So all info is compiled in one thread

**Comment by Sakurahime08** [comment]
I still have problems with this. What was the solution? Thanks!
