### ISSUE TITLE
[issue][manhuaren] images do not display when opening chapters

### ISSUE THREAD

**Issue by lilli34556** [inorichi/tachiyomi-extensions#653]
Website : https://www.manhuaren.com/search/ 
Tachiyomi version : v0.80
Extension version : v1.2.3
Extension name : manhuaren
 I am using an amazon fire hd 8 with android lollipop

When I open any manga it opens the chapter with no images and a retry button for every page. Clicking the retry button doesn't do anything.
I tried the actual website and it works for viewing chapters on my tablet's browser, but it does not work in the app. 
I tried clearing my cache and cookies, but it didn't do a difference.

**Comment by denniscgh** [comment]
I can confirm this issue as OP; same Tachiyomi version and manhuaren extension version. 
Was using my Android phone, on Oreo.
