### ISSUE TITLE
[Source Request] Manga Livre [PT-BR]

### ISSUE THREAD

**Issue by 1Herstein** [inorichi/tachiyomi-extensions#654]
https://mangalivre.com

Language: PT-BR

no problems with licensing

**Comment by masgritz** [comment]
Isn't that a mirror of mangasPROJECT (https://leitor.net/)? We already have an extension for it.

**Comment by 1Herstein** [comment]
Yes, but the mangasproject has a problem with some manga, because of licensing.

hunter x hunter, nanatsu no taizai among others can not be read now.

**Comment by masgritz** [comment]
I see. I'll try to do the extension this week. While it's not ready, you could check the Union Mangás extension.

**Comment by 1Herstein** [comment]
Ok, thanks.
