### ISSUE TITLE
[issue] [mangago] [kissmanga] [mangafox]

### ISSUE THREAD

**Issue by Gia987** [inorichi/tachiyomi-extensions#655]
Tachiyomi ver : 0.8.0
mangago ext ver : 1.2.6

I can't open mangago. There's a pop up which say java.security.cert.CertPathValidator.Exception

and also kissmanga and mangafox do not display anything only 'no result found'

i'm using xiaomi redmi note 3 pro 
please help

**Comment by CarlosEsco** [comment]
mangago is permanently broken.  mangafox there is already an issue open.  for kissmanga please login to the discord server for tachiyomi and read the faqs page
