### ISSUE TITLE
[tachiyomi-extensions] [request] [new sources] [arabic] 

### ISSUE THREAD

**Issue by TamySenpai** [inorichi/tachiyomi-extensions#656]
(CATALOGUE) SOURCE REQUESTS:
  One source per issue, create more issues if you have more websites
  Check for duplicates, use search (in issues, not the global one)
  Put the name of the site as Title, replace this text with clickable link to the site
BUGS:
  Provide tachiyomi version as well as version of source the report is about

**Comment by TamySenpai** [comment]
Why there's not an Arabic sources
It would be nice if you added some :) thanks

**Comment by Jendrej** [comment]
> Put the name of the site as Title, replace this text with clickable link to the site

**Comment by arkon** [comment]
There's existing requests for Arabic sources. This one doesn't even mention any sites.

**Comment by shipoxx** [comment]
Can i add some website or suggestion?

**Comment by CarlosEsco** [comment]
open a ticket with the source make sure its not a duplicate
