### ISSUE TITLE
how to put a new source

### ISSUE THREAD

**Issue by nevaend** [inorichi/tachiyomi-extensions#66]
can any one help me how can i put new source in project (tachiyomi-extensions) by steps

**Comment by j2ghz** [comment]
It says how to do it in the Readme https://github.com/inorichi/tachiyomi-extensions#writing-an-extension

**Comment by nevaend** [comment]
in the package eu.kanade.tachiyomi.extension.ar.gmanga

import ...

class GManga : ParsedHttpSource()

he said that Gmanga is never used 
is this any problem or it's normal
if it has problem what i do to solve it

**Comment by nevaend** [comment]
when i finish add to the project of (tachiyomi-extensions)
what i do to add the source to main project tachiyom

**Comment by null-dev** [comment]
Although I like to avoid discouraging people, I would recommend you take a
Java or Kotlin course before you start developing sources. It will save you
hours of time. Trust me...

If you do not wish to heed my warning, then: No, it is not a problem. You
can safely ignore this warning.

**Comment by nevaend** [comment]
but in another sources manga fox is used,
and thinks for this help,
i take course of kotlin but he didn't give me what i need
(https://www.udemy.com/the-complete-kotlin-developer-course/learn/v4/overview)

**Comment by meradoou** [comment]
But https://github.com/inorichi/tachiyomi/wiki/YAML-Sources still works ?

**Comment by j2ghz** [comment]
@meradoou It does, but it's not possible to add every site using YAML, so support for it will probably be removed in the future, when extensions have better support in the main app. It's also easier for users to install .apk than to place .yml in the correct folder.

**Comment by inorichi** [comment]
The readme contains enough information on how to create a new catalog based on the others. If you don't know programming, it's best to just post your request. Learning to code takes time and we can't teach you that.
