### ISSUE TITLE
[Bug] Mangago - Malformed UTF-8 data

### ISSUE THREAD

**Issue by Asthetic** [inorichi/tachiyomi-extensions#664]
Tachiyomi version: 0.8.0 (latest)
Mangago version: 1.2.6 (latest)

When using Mangago extension to read any chapter user will receive "Error: Malformed UTF-8 data"
Reproducibility: 5/5
Repro Steps:
  1. Install Mangago extension
  2. Search for a known manga title (In my case "Lily Love")
  3. Select Manga from Mangago
  4. Select "Chapters tab" 
  5. Observe "Malformed UTF-8 data" error

I tried to look into the website a little bit to see if they're returning incorrect data types. It's interesting to note that the website changes the URL to a "New Fashion" article upon loading a chapter and reloading the website redirects you the article in New Fashion's website. May want to look into this as this is potentially malicious.

**Comment by CarlosEsco** [comment]
Issue already open. There are no plans to fix cause mangago actively tries to prevent scrappers
