### ISSUE TITLE
what i do when i finishing of adding a new source

### ISSUE THREAD

**Issue by nevaend** [inorichi/tachiyomi-extensions#67]
when i finish to add a new source to the project of (tachiyomi-extensions)
what i do to add this source to the main project in tachiyom

**Comment by j2ghz** [comment]
If you have finished everything from https://github.com/inorichi/tachiyomi-extensions#writing-an-extension you need to open a pull request https://help.github.com/articles/creating-a-pull-request/

**Comment by nevaend** [comment]
if i need to test the new source what i do

**Comment by inorichi** [comment]
I'll add a new section in the readme (don't know when) for debugging a catalog with Android Studio.

**Comment by CarlosEsco** [comment]
@nevaend can i close this?
