### ISSUE TITLE
[BUG] Boredom Society

### ISSUE THREAD

**Issue by Vverg** [inorichi/tachiyomi-extensions#679]
The chapterlist is reversed... so it thinks the last chapter is the first chapter. So if you click on chapter 1 you cant go to chapter 2 without clicking the "previous chapter" icon.

**Comment by Vverg** [comment]
Oh also the "recent" option does not work. It doesn't order titles based on date of updates.

**Comment by CarlosEsco** [comment]
Doh I sorted them oldest first lol

**Comment by GumiFlatline** [comment]
Can confirm. Even if you sort it out by chapter number, the first chapter is still considered the last one. 

Plus, pages are loading pretty slowly right now.

**Comment by Vverg** [comment]
GumiFlatline thats Cloudflare... it seems to have it hard at specific times. Mangadex as example also has this issue.
