### ISSUE TITLE
HTTP error 404

### ISSUE THREAD

**Issue by nevaend** [inorichi/tachiyomi-extensions#68]
i add a new source but when i open it's gives me that ( http error 404 )

**Comment by inorichi** [comment]
Then something is wrong with the implementation. You can't just change the base url and expect things to work.

**Comment by nevaend** [comment]
I finished it and it's dosen't give this error it's give's me this message
(no result)
And in manga rock ,manganese, zing box app have the same error
Note that
Message to the sources of Arabic language.
Gmanga
Manga arab
Manga for all
