### ISSUE TITLE
[Source Request] [Russian] mangaclub.ru

### ISSUE THREAD

**Issue by D3xron** [inorichi/tachiyomi-extensions#692]
https://mangaclub.ru/

**Comment by Pavkazzz** [comment]
Hey, what is the main point of mangaclub site?

**Comment by D3xron** [comment]
What to do you mean?

**Comment by Pavkazzz** [comment]
There is many russian manga sources: readmanga/mintmang, libmanga, mangachan, mangahub. What about mangaclub? Why it is better than other?

**Comment by as280093** [comment]
@CarlosEsco  Change title to **[Source Request [Russian] mangaclub.ru**  Because the second source 
 (http://henchan.me/) already has a separate issue #713

**Comment by AriaMoradi** [comment]
is this issue resolved?
