### ISSUE TITLE
MerakiScans error

### ISSUE THREAD

**Issue by tblader** [inorichi/tachiyomi-extensions#694]
MerakiScans giving HTTP error 404
They recently switched to a new site. 

https://merakiscans.com
MerakiScans 1.2.1

Tachiyomi version 0.8.0

**Comment by einstein95** [comment]
@Vesnyx Your fix didn't work as the URLs that Tachiyomi tries now 404.

**Comment by Vesnyx** [comment]
Yes, I know. I've almost finished completing the fix. I'm still finishing off the image parser.
