### ISSUE TITLE
[Multiple] MangaToon

### ISSUE THREAD

**Issue by Kirieh** [inorichi/tachiyomi-extensions#697]
https://h5.mangatoon.mobi

Is it possible to add this website as an extension?

**Comment by as280093** [comment]
@arkon add label to this too [source Request]

**Comment by WhoIsStone** [comment]
I would also like this one to be added if possible.

**Comment by arkon** [comment]
Includes English, Chinese, Indonesian, Vietnamese, and Spanish.

**Comment by tdosch616** [comment]
please add mangatoon english

**Comment by Allanrex92** [comment]
Is this source still in progress?

**Comment by as280093** [comment]
Here the icons
[mangatoon.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614687/mangatoon.zip)

**Comment by b1ackhand5** [comment]
Add this source too please
