### ISSUE TITLE
[ISSUE] [Japscan] Display problem on few mangas

### ISSUE THREAD

**Issue by pokke456** [inorichi/tachiyomi-extensions#698]
Hi,
There is a display problem on some mangas of this source.
The images are like this on the app (Tachiyomi 0.80 / Japscan 1.2.5) : https://i.imgur.com/kswCbgo.jpg
All is fine on the website : https://www.japscan.to/lecture-en-ligne/shingeki-no-kyojin/112/2.html

The problem appear on these mangas (not exhaustive), on their recents chapters : _Shingeki No Kyojin_, _Twin Star Exorcists_, _Boruto_, _Eden's Zero_, _Fire Punch_...
I noticed that these mangas are rip from the official release, not a scantrad team's release.

I hope it can be fix '-'

**Comment by Rublood** [comment]
> Yeah, reason behind this is because japscans is essentially "encrypting" the image and having the browser decrypt it: https://c.japscan.to/clel/Shingeki-No-Kyojin/112/02.jpg
> 
> Going to have to implement some sort of decoder for these sorts of images unless one already exists here.

Hi,
any maj for this issue ?

**Comment by Nosrob** [comment]
I am also very interested in a fix for this issue :)

**Comment by Rublood** [comment]
Hi,

New problem with few manga like solo leveling https://www.japscan.to/manga/solo-leveling/

I think it's when this script is load:

<script src="/js/iYFbYi_Fee_gb_NbY.js"></script>

I hope can be fix
