### ISSUE TITLE
Dynasty Scans

### ISSUE THREAD

**Issue by MIC132** [inorichi/tachiyomi-extensions#7]
Can http://dynasty-scans.com/ be added as a source?

**Comment by MIC132** [comment]
Any progress on this?

**Comment by null-dev** [comment]
I've looked into doing this but the fact that dynasty scans splits their content into manga, doujinshi and anthologies makes it very difficult to implement.

**Comment by MIC132** [comment]
I remember there being a pull-request for main tachiyomi that I think included dynasty, but it was rejected because the whole extension system was being introduced. Maybe you could look into that?

I think it was this one:
https://github.com/inorichi/tachiyomi/pull/424

**Comment by ThePreviousOne** [comment]
I actually have done this  tvice one for 0.2.3 but waited to long testing and now I had to re write it so im almost done again

**Comment by ThePreviousOne** [comment]
https://github.com/inorichi/tachiyomi-extensions/pull/75

**Comment by ccrowles** [comment]
Any progress? No other reader has Dynasty Scans in the sources, so my hopes are with Tachiyomi.

**Comment by CarlosEsco** [comment]
This is done please close

**Comment by igalic** [comment]
yupp → https://github.com/inorichi/tachiyomi-extensions/pull/154 ← fixed here
