### ISSUE TITLE
[FoolSlide] Sites no longer using FoolSlide

### ISSUE THREAD

**Issue by einstein95** [inorichi/tachiyomi-extensions#702]
ChampionScans (http://reader.championscans.com) now uses ComiCake (see issue #354).

Hatigarm Scans (http://hatigarmscans.eu) now uses WpManga but lazy-loaded. (see issue #632)

Angelic Scanlations (http://www.angelicscans.net) is parked by GoDaddy.

Yuri-ism (https://reader.yuri-ism.com) has an invalid HTTPS certificate, not sure what anyone can do about that. HTTP works fine.

Ajia no Scantrad (https://ajianoscantrad.fr/reader) has an invalid HTTPS cert, HTTP works fine.

Anata no Motokare (https://motokare.maos.ca) ~~seems to be gone? Getting a "can't connect to server" error.~~ is now at https://motokare.xyz/reader/

**Comment by Vesnyx** [comment]
For Hatigarm, is the .eu domain their actual site? It seems like they've been uploading here: https://www.hatigarmscans.net/

**Comment by waptik** [comment]
> For Hatigarm, is the .eu domain their actual site? It seems like they've been uploading here: https://www.hatigarmscans.net/
> 
> Edit: JK just saw that they're planning on moving.
> 
> Edit2: But, we could point the domain to the .net one as it still seems to have their manga on it, at least as a temporary measure until their new site is up to date.

Hatigram is back using FoolSlide and `http://hatigarmscans.net` is now its official domain name. I'd like to ask if the contributors can update the domain name in the extension.
Thanks
