### ISSUE TITLE
Champion Scans no longer uses FoolSlide

### ISSUE THREAD

**Issue by xChickens** [inorichi/tachiyomi-extensions#703]
ChampionScans recently changed their reader to not be based on FoolSlide, meaning that all functionality for its source no longer works.

Some series URLs are the same, however, search features and chapters do not work at all anymore.
https://reader.championscans.com/

Tachiyomi version r1461
FoolSlide version 1.2.10

I'd also request for it to be added as a separate source now since it has a ton of series that I follow. (And a 2 week delay on MangaDex, why????)

**Comment by einstein95** [comment]
See #702

**Comment by xChickens** [comment]
Oof I didn't even see that when I first started to type, I got ninja'd >.<.
