### ISSUE TITLE
[Suggestion] Make a delete all for downloaded mangas

### ISSUE THREAD

**Issue by CyredCyre** [inorichi/tachiyomi-extensions#704]
I'm new to using Tachiyomi and find it really good to use, I love to download mangas and watch it later when I don't have any internet connection. 
Can you guys please make a delete all button for the manga without also deleting it from library?
Because I find it tiring to delete unwanted manga chapter 1 by 1, Thanks for your attention and hard work :)

**Comment by arkon** [comment]
This belongs in [the main repo](https://github.com/inorichi/tachiyomi). 

Also, you could in theory just delete everything from a file explorer, but maybe having this in the advanced settings would be nice.

**Comment by CarlosEsco** [comment]
To add. A super simple work around is to go to the info page. Click bookmark button. Click delete downloaded chapters. Then click bookmark button again
