### ISSUE TITLE
Add Goodreads as trackcker

### ISSUE THREAD

**Issue by Zocex** [inorichi/tachiyomi-extensions#708]
Hello i use this wonderful app to read comics.  i use goodreads.com to track not just my comics but also my book, novels, and manga and other stuff. it would be nice if you guys are open to the idea of adding this to your app. 

i know nothing about programing but this is the website api https://www.goodreads.com/api

**Comment by arkon** [comment]
This should be opened in [the main repo](https://github.com/inorichi/tachiyomi/issues).
