### ISSUE TITLE
[Source Request][English] Manhwahentai.com [NSFW]

### ISSUE THREAD

**Issue by metroid112** [inorichi/tachiyomi-extensions#711]
https://manhwahentai.com/

This website is hosting English translations of some Lezhin comics which are currently paywalled and not available on any other source that Tachiyomi hosts.

**Comment by joseph619** [comment]
I also request this site, has tons of exclusive webtoon which are behind paywall and currently the only site to host these webtoons

**Comment by Owldwaine** [comment]
I hope manhwahentai gets added as an extension
