### ISSUE TITLE
[mangadex] "chapter json must not be null"

### ISSUE THREAD

**Issue by einstein95** [inorichi/tachiyomi-extensions#715]
When opening https://mangadex.org/manga/12916/ in Tachiyomi, it comes up with "chapter json must not be null" and doesn't show any details about the manga.

**Comment by metroid112** [comment]
I can confirm I got the same error, maybe it has something to do with the lack of English chapters? In my case I'm using Mangadex with English language only. Both the servers and database were updated yesterday, so that might have something to do with it too, but I'm just assuming.

**Comment by CarlosEsco** [comment]
It has to do with 0 chapters of any language causing mangadex to not return the chapter field
