### ISSUE TITLE
[issue][mangadex] Status showing as "complete" even when the manga is ongoing

### ISSUE THREAD

**Issue by themagicalyang** [inorichi/tachiyomi-extensions#722]
https://mangadex.org/manga/32058/

It's an ongoing manga, publishing status is also ongoing. So it should not show up as completed when the chapters don't have the END tag.

Screenshot: https://i.imgur.com/5uMFD66.png

Tachiyomi version: r1461
Mangadex version: 1.2.45

**Comment by Flat** [comment]
Thanks for the report. This is likely an issue with the way oneshot manga is detected. #717 should fix it provided testing doesn't show further bugs.

**Comment by Flat** [comment]
PR has been merged. Please update and let me know if you encounter any other manga showing as complete that should not be. Thanks.
