### ISSUE TITLE
Is there a SFW version?

### ISSUE THREAD

**Issue by LightWing-IsMe** [inorichi/tachiyomi-extensions#726]
Some extentions have some NSFW content, I want to know if I can get (or I/someone with the knowledge can fork it) tachiyomi without the hentai extensions, and Mangadex without the R18 option, and the mmrcms without any hentai in it...

Maybe someone can teach me how to do it...

I've tried to modify the Mangadex APK to make all the cookies for R18 be zero, bcz that's the cookie for SFW Mangadex... But after installing I can still choose to manually see R18 content which I don't want to have (I've edited a few other places in the Mangadex.kt file)

**Comment by Xeiniac** [comment]
@LightWing-IsMe If you go to extensions and click on details for mangadex, there's an option to change the default r18 Setting. You can set it to Show No R18+

**Comment by LightWing-IsMe** [comment]
I know, but it's still possible to manually search for it in the folder
settings...

I mainly want to know how to change the source code so that it's impossible
to find, bcz as far as I know even on the website itself it's harder to get
to the NSFW content, also, Mangadex isn't my only concern, also the sources
with allot of sources, have NSFW sources mixed in, I want to mix them out...

**Comment by CarlosEsco** [comment]
In mangadex remove the client builder stuff and get it compile. Check an older version of the code to see how it used to be. That will remove option for r18. As for other extension you could compile your own tachiyomi and remove all the extension page stuff.

**Comment by LightWing-IsMe** [comment]
Ok, thanks, I'll try the next time I get on a computer.

**Comment by JukePlz** [comment]
What's the use case for this? Do you need parental controls to avoid children accessing R18 content? Maybe a proposal could be made to password protect the R18 settings.

**Comment by LightWing-IsMe** [comment]
More or less the reason, then you just need to mark the R18 settings to be
locked when you don't want them accessed, I know if a few (at least 2)
extensions which have in then some R18 sources and normal clean sources...
Or maybe the password can also go on the extensions page as well, so any
update or new installation would need approval...
