### ISSUE TITLE
[English] Bato.to

### ISSUE THREAD

**Issue by Xeiniac** [inorichi/tachiyomi-extensions#728]
**Source Website:** https://bato.to
**Language:** English

There are a few manga/manhwa/manhua on bato.to that I haven't been able to find anywhere else.
An example would be "Who Made Me A Princess".
Thanks in advance :D

**Comment by Locked-Key** [comment]
Bato.to already closed down.

**Comment by einstein95** [comment]
@Locked-Key This is Bato.to in name only. It is run by the same people as https://mangawindow.net/ but has quite a few manga missing.

**Comment by Xeiniac** [comment]
Yeah, it might not be the real bato.to but it still has few manga that aren't available on mangadex and other sites.

**Comment by Sakurahime08** [comment]
can't seem to find bato.to in the current app? is it already available?  thanks!

**Comment by einstein95** [comment]
@Sakurahime08 No, it is not available. The issue would have been closed when an extension was made
