### ISSUE TITLE
[Bug] [nhentai] HTTP error 404

### ISSUE THREAD

**Issue by blueRoseXIV** [inorichi/tachiyomi-extensions#729]
"HTTP error 404" appears when I try to browse nhentai's catalog or when I try to open a nhentai-sourced bookmarked manga.

Tachiyomi v0.8.0
nhentai extenstion v1.2.3

![screenshot_20190114-171412](https://user-images.githubusercontent.com/32766153/51121720-c256cf80-1820-11e9-81fe-4e6f680c82b9.jpg)

**Comment by CarlosEsco** [comment]
They took their API down. It will be broken for time being

**Comment by Jokerdrim** [comment]
Same problem

**Comment by hakapoid** [comment]
Does anyone have an ETA for the fix?

**Comment by CarlosEsco** [comment]
Not a tachiyomi problem it will be broken unless a complete rewrite of extension occurs

**Comment by Dinokin** [comment]
It there anybody working on this? cuz if not, i'll tackle this this weekend.

**Comment by LinkCable** [comment]
@Dinokin no one on the dev team is working on this

**Comment by hornsybatsy** [comment]
@Dinokin yes please
