### ISSUE TITLE
[Issue] Manhuaren "new" manga updates always remain in "Today" category

### ISSUE THREAD

**Issue by yogiwizard** [inorichi/tachiyomi-extensions#731]
Tachiyomi version : vr1438
Extension version : v1.2.4
Extension name : manhuaren

Manga added from Manhuaren source will always remain in Today's category under Library updates. These "new" chapters will always show up in today's category even after weeks passed.

**Comment by yogiwizard** [comment]
Found out the reason behind the manga chapters staying in Today's category under Library updates. Apparently each new chapter from Manhuaren source will show up and continue to stay under Today's category for a period of **1 MONTH** until it dropped out from the category.

**Comment by yogiwizard** [comment]
![1](https://user-images.githubusercontent.com/46705106/52031883-942ffa00-2559-11e9-9bef-f1a55888df5c.jpg)
![2](https://user-images.githubusercontent.com/46705106/52031888-96925400-2559-11e9-8c06-d6db8afe4094.jpg)
![screenshot_20190131-124431_tachiyomi](https://user-images.githubusercontent.com/46705106/52031891-97c38100-2559-11e9-926b-7d13af102827.jpg)

**Comment by SnakeDoc83** [comment]
Can't see how this was possible and I'm leaning toward it being a main-app issue (which is several versions newer now). This is too old to act on at this point; if you're still experiencing this open a new issue with a current example of the problem and I'll take a look.
