### ISSUE TITLE
[Russian] Unparseable data Mintmanga.com

### ISSUE THREAD

**Issue by DArkHekRoMaNT** [inorichi/tachiyomi-extensions#734]
[Mintmanga.com](http://mintmanga.com)
Tachiyomi 0.8.0
Error after reloading chapters or load new manga:
```Unparseable date: "<date>"```
"date" - last updated date of the manga chapter

**Comment by Taumer** [comment]
Already fixed by https://github.com/inorichi/tachiyomi-extensions/pull/724

**Comment by DArkHekRoMaNT** [comment]
Sorry, I don't turned on "check for updates". All works

**Comment by CarlosEsco** [comment]
Check for updates won't work for extensions anyways

**Comment by DArkHekRoMaNT** [comment]
Mintmanga works without extensions, or i do not understand something? 
Anyway, I turned on check for updates and after a few minutes, everything worked for me, but last a few days - don't work. Maybe it's a magic :)

**Comment by CarlosEsco** [comment]
Extension overwrites internal. So we don't have to release a new tachiyomi version when a source has a bug fix

**Comment by DArkHekRoMaNT** [comment]
Hmm. Or maybe it's working, when I am added Mintmanga extension. Although I did not understand what it adds (Mintmanga category already exists).UPD: Alright. If I am remove extension, category removed too. Even those that worked without extensions... I think it extension included in "default" Tachiyomi. And I m just reinstalled it and fixed problem. It's really magic, I am just installed extension, that find out how it works

**Comment by DArkHekRoMaNT** [comment]
I am too long write it.
Thanks for answer, now I will know what to do if something breaks again on some manga source
