### ISSUE TITLE
No results found Mangahere

### ISSUE THREAD

**Issue by ReGtrs** [inorichi/tachiyomi-extensions#736]
Mangahere has recently been dead in the app. Clicking browse in the catalogue says No results found and is completely blank in the latest. Have tried both the extension (1.2.6) and the preinstalled but results are the same. Tried opening the site in the browser and it seems fine although I do think that the issue could perhaps be on their side.

**Comment by TNTKit** [comment]
I got the same issue on mangahere and mangafox too

**Comment by FalconJ** [comment]
I got the same issue on mangahere and mangafox as well.

**Comment by lich21** [comment]
I have the same problem with mangacow

**Comment by SYtor** [comment]
MangaHere recently changed website, and now there is troublesome algorithm to fetch images.  I've found out that images are extracted from chapterfun.ashx that returns obfuscated javascript, but sometimes response from there is empty, I think it's somehow connected with cookies. Also this endpoint requires `key` parameter, which can be found at one of `<script>` tags in html and it packed same way. Does anyone work on this issue?

**Comment by alena199411** [comment]
I have been having the same issue with kissmanga and every other catalogue for quite some time. The search just doesn't give results at all for me anymore... Even with the latest update

**Comment by arkon** [comment]
For the record, Mangahere and Mangafox have the same method with the `key` thing. PR #657 included some work on it, but it was ultimately pretty messy. Someone else could try tackling it if they want to.

**Comment by SYtor** [comment]
I've made pull request with fix #1029
