### ISSUE TITLE
[Vietnamese] Ngon Phong comics

### ISSUE THREAD

**Issue by menomelissa** [inorichi/tachiyomi-extensions#738]
[https://ngonphongcomics.com](url)

**Comment by as280093** [comment]
@CarlosEsco change title to [Source Request] [Vietnamese] Ngon Phong comics

**Comment by as280093** [comment]
Here the icons
[ngonphongcomics.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614683/ngonphongcomics.zip)
