### ISSUE TITLE
[Bug] Mangadex extension won't load manga

### ISSUE THREAD

**Issue by FDLAHafa** [inorichi/tachiyomi-extensions#747]
Mangadex ver 1.2.46
Tachiyomi ver 0.8.0

Only mangadex has a problem loading any manga from the extension

Other manga provider such as manga rock works normally

**Comment by wopian** [comment]
Mangadex is currently being DDoSed 

https://i.reddit.com/r/manga/comments/akfd7g/mangadex_being_ddosed/

**Comment by CarlosEsco** [comment]
They are getting ddos

**Comment by bbtora** [comment]
Should have kept this open until the issue resolves so that other people can see this.
