### ISSUE TITLE
[Source Request] Manga Plus - Shueisha (official free licensed titles)

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi-extensions#750]
Manga Plus by Shueisha was recently launched worldwide for Shonen Jump, Jump SQ and Jump+ official licensed titles.

Web URL - https://mangaplus.shueisha.co.jp

**Comment by alessandrojean** [comment]
I took a look in their API, but as I expected, it's encrypted. 

However, the web version of the API is less encrypted, so I think that it can be used to create an extension when someone completely understand how it works and how to do the decryption of the data and the images. Unfortunately, it can take a while until this happens.
