### ISSUE TITLE
[Chinese] Dongman

### ISSUE THREAD

**Issue by ybhgl** [inorichi/tachiyomi-extensions#752]
**Dongman** is the Chinese version of **Webtoon**. All the cartoons on this site are from **Webtoon**, and all of them have been translated into Chinese. In China, if you access _www.webtoon.com_, you will **automatically** jump to _www.dongmanmanhua.cn_ 

Url: https://www.dongmanmanhua.cn/ (Please use the VPN server located in _**China**_ to access this website!)

**Comment by as280093** [comment]
Here the icons
[Dongman.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614663/Dongman.zip)
