### ISSUE TITLE
[NHENTAI] Bring back the old Info section details and format.

### ISSUE THREAD

**Issue by melnation-com** [inorichi/tachiyomi-extensions#754]
I am using Tachi dev 1463 now but even on 1462 was still the same, I just updated the Nhentai extension today which is now 1.2.5, not sure when this started cause I don't remember the last version Nhentai extension which still had more details, but the Nhentai extension ver 1.2.5 only has tags in the info tab, it used to have info like
`English Title: (C90) English title something something`
`Japanese Title: (C90) Title in Japanese characters`
`Short Title: Short title`

`Upload date: 2018-11-10`
`Length: 26 pages`
`Favorited: 1521 times`

`Tags:`
`tag <tag1> <tag2> <tag3> <tag4> `
`group: <scanlators1> `
`language: <english> <translated>`
`category: <doujinshi>`

Basically if you had not updated the info section(via swiping) on your old downloads, you still see the old info details & layout but when you update it it becomes the very short one. Not sure what's the issue now why it's far less info now, the old info was useful to check if the manga had too many pages so if you should download now or later and download the shorter ones now incase you wanna leave now. Basically it would be better to have the old infos back especially the info of number of pages. The old format for tags is also easier to the eye.

I've checked e-hentai, and it was just how Nhentai used to be.

My main language is not english and I try to be polite as when I had translated it, so pardon if something rubbed as rude. cause delivery is mostly out of my league for now.

Lastly, what I like about Nhentai, is I can search by tags, tried it on e-hentai it doesn't do that or can't.

**Comment by arkon** [comment]
A majority of the info is redundant since it'll show up elsewhere (e.g. language, group, upload date).

I guess that leaves the different titles and number of favourites?
