### ISSUE TITLE
[Mangakakalot] New chapters not showing up on "Library Updates" tab

### ISSUE THREAD

**Issue by Valkilor** [inorichi/tachiyomi-extensions#760]
App version: 0.8.0
New chapters from [Mangakakalot] (1.2.2) are not showing up on the "Library Updates" tab when they are appearing in my library. Other sources are showing up.

**Comment by Valkilor** [comment]
It looks like I am having the same issue with Manganelo (1.2.2).  Might be related since those sites seem to work in conjunction.

**Comment by einstein95** [comment]
This is because these sites do not return an uploaded date for each chapter, only a "Last updated" for the entire manga. It is merely due to the lack of information about the chapter from the site, nothing we can fix.

**Comment by Valkilor** [comment]
That makes sense now.  Much appreciated.
