### ISSUE TITLE
NHentai Extension Won't Install

### ISSUE THREAD

**Issue by TakuyaSama** [inorichi/tachiyomi-extensions#763]
(CATALOGUE) SOURCE REQUESTS:
  One source per issue, create more issues if you have more websites
  Check for duplicates, use search (in issues, not the global one)
  Put the name of the site as Title, replace this text with clickable link to the site
BUGS:
  Provide tachiyomi version as well as version of source the report is about

I just been experimenting this issue since 2 days ago, i tried to open some hentai from NHentai extension on Tachiyomi, but it was giving me a HTTP 403 or 404 (probably the last one) error. So i come to GitHub, both the app and the extensions one, to check that everything was OK, and there wasn't a new version of something.
So i uninstalled the extension, couldn't visualizing any hentai from NHentai, of course, because it need a loader, so i tried to reinstall it, but here's the problem, it doesn't install, more specifically, it doesn't even downloads. I tried about 15 times and nothing. I don't know why this is caused, but it's really frustrating, i don't know if it's a NHentai issue (i tried to open it at PC web browser to check the servers were alright and the result was OK), Tachiyomi's extension issue, anyway i noticed that now it's a new version of the extension (now it's 1.2.5 and before i think it was 1.2.2).

Tachiyomi version: 0.8.0.
Android version: LineageOS 15.1 (Android Oreo 8.1).

**Comment by arkon** [comment]
The usual solutions are:

- Turn off your VPN
- Restart the app
- Restart your phone

**Comment by TakuyaSama** [comment]
> 
> 
> The usual solutions are:
> 
>     * Turn off your VPN
> 
>     * Restart the app
> 
>     * Restart your phone

I see, i never have the VPN activated, anyways, i uninstalled the app about 2 weeks ago, a few days later i opened this issue.

Thank you very much samely and sorry for the inconveniences.

You're doing a great work with the app, keep it up.

Best regards.
