### ISSUE TITLE
[Webtoons] Small/easy request about music

### ISSUE THREAD

**Issue by Sredleg** [inorichi/tachiyomi-extensions#769]
I know it is hard to implement the music/sound Webtoons provides.
But is it possible to have a tiny music note in the title of the chapter (similar as how Webtoons does this) to indicate the chapter originally comes with music?

**Comment by arkon** [comment]
Do you have examples of Webtoons with music/sound?

**Comment by einstein95** [comment]
@arkon https://www.webtoons.com/en/fantasy/unordinary/list?title_no=679&page=13 chapters 20 and 26 for example

**Comment by Sredleg** [comment]
The first chapter of DICE and all chapters of 1000 and Backchannel have it
too.

**Comment by arkon** [comment]
I'll work on this. Only thing to note is that the chapter titles in Tachiyomi will change, so downloads/read status may be affected.
