### ISSUE TITLE
[Manga Host] HTTP Error 403

### ISSUE THREAD

**Issue by TemptingBadger** [inorichi/tachiyomi-extensions#774]
Two days ago, I create [this issue request](https://github.com/inorichi/tachiyomi-extensions/issues/761) and  it was fixed, but today the same error appears.
Please help.
Thanks for all.

**Comment by alessandrojean** [comment]
I tried here, but everything is working perfectly fine.

Maybe it's some old cache in your phone using the old URL.
Wipe the cache in the Tachiyomi settings and try again.

If the error continues, I can try to fix it.

**Comment by TemptingBadger** [comment]
It fixed when I clean up my cache.
Now its working perfectly for me, thanks so much!

**Comment by alessandrojean** [comment]
Can be closed since it doesn't require any fix, @CarlosEsco.
