### ISSUE TITLE
Bug: tapas source doesn't load; crashes app

### ISSUE THREAD

**Issue by raiskream** [inorichi/tachiyomi-extensions#80]
V. 0.6.1

_Sent from my HTC One A9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ThePreviousOne** [comment]
I just checked it out NoSuchMethodError...lol
I'll work on it soon

**Comment by inorichi** [comment]
It probably has to do with proguard removing a method.

**Comment by ThePreviousOne** [comment]
ya I expect so
