### ISSUE TITLE
[Source Request] add kissdoujin.com (English Source)

### ISSUE THREAD

**Issue by effiel97** [inorichi/tachiyomi-extensions#820]
coding maybe like kissmanga.com i tried but failed .. any suggestion will be accepted ..

**Comment by as280093** [comment]
Here the icons
[kissdoujin.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614435/Kissdosojin.zip)

**Comment by effiel97** [comment]
i think this website is already migrated to ninehentai which is available on tachiyomi.. Thank you for your precious time
