### ISSUE TITLE
NHentai extension not working

### ISSUE THREAD

**Issue by GutHib1209** [inorichi/tachiyomi-extensions#827]
NHentai extension for Tachiyomi initially functions normally but after a few moments ceases to function at all. Selecting 'Latest' yields a blank screen and selecting 'Browse' yields a "No results found" response. A reinstall does not solve the issue.  

App version: 0.8.0
Extension version: 1.2.5

**Comment by arkon** [comment]
Open it in your browser and do the captcha.

**Comment by GutHib1209** [comment]
Thank you.
