### ISSUE TITLE
Mangalib problems

### ISSUE THREAD

**Issue by Jokerdrim** [inorichi/tachiyomi-extensions#832]
Version r1463
Mangalib 1.2.2
Problem: Search didnt found manhwa (foe example: "she is young").  But on their site I can find this manhwa.

**Comment by Pavkazzz** [comment]
Seems like unathorized users doesn't see all manga in search. 
Write about it on their forum: https://mangalib.me/manga/forums/2-zhaloby-i-predlozheniya-sayta-mangalib/25-bagi-i-problemy?page=32#post-477

**Comment by Ilya87** [comment]
@jokerdream
