### ISSUE TITLE
Manga Plus by Shueisha doesn't load

### ISSUE THREAD

**Issue by DarkHorse1997** [inorichi/tachiyomi-extensions#833]
When I try to load manga from the Manga Plus extension, the following error is shown.

  
![tachiyomi-issue](https://user-images.githubusercontent.com/22052923/53284092-1d130d80-3775-11e9-9d0d-50384d0d80c5.jpg)

App version: r1463
Manga Plus by Shueisha version: 1.2.1

**Comment by einstein95** [comment]
```
Unknown server error
There are issues connecting to Manga+. Please try again later.(10000)*
```
