### ISSUE TITLE
Mass selection to flag multiple chatpers as "read" or "to read"

### ISSUE THREAD

**Issue by hhiru** [inorichi/tachiyomi-extensions#84]
The app is missing something to let you select more than one chapter for mass flagging.
Example: select chapters from 1 to 100 and mark them as read

**Comment by wopian** [comment]
This should be in the main repo, but this is already possible

Long hold any chapter, then tap each chapter you want to tag. Tap the 3-dot menu and `mark as (un)read`

Alternatively tap the 3-dot menu on a single chapter and mark all previous chapters as read

**Comment by hhiru** [comment]
What if I want to mark a starting and an ending point in a list? tapping only two points auto selecting what it's in between is easier than tapping 100 times

**Comment by j2ghz** [comment]
That is true, but it's such a rare case that it was decided it's not worth implementing. What you want implies that you've for example read chapters 40-60, now you want to read from 60 onward, but want the app to remember that you have never read 1-40, but you will read them in the future.

**Comment by hhiru** [comment]
I see, good point! btw I'm loving the app, good job everyone :)
