### ISSUE TITLE
Manga Rock Open in browser

### ISSUE THREAD

**Issue by phanirithvij** [inorichi/tachiyomi-extensions#840]
Tachiyomi version: 
**0.8.0-1463 dev**
Manga Rock version
**1.0.5**

Open in Browser opens the API link instead of the manga's source link.

Tried it for One Punch-Man (Source: Manga Rock(EN)).

Same as #627 I'm guessing.

And there is no update for Manga Rock(EN) extension after 1.0.5 right?

**Comment by arkon** [comment]
#613
