### ISSUE TITLE
[Bug]v0.8.0: Nhentai v1.2.5 No Results Found

### ISSUE THREAD

**Issue by WatashiWaPizza-Sama** [inorichi/tachiyomi-extensions#842]
When the extension is used in the catalogue section by clicking on 'Browse' an error message reads:'No Results Found'. Before this it was an 'http 440' error message. I am aware that this has occured before, but it would be nice if this issue were fixed again by any of you willing to do so. Thanks in advance.

**Comment by arkon** [comment]
#827

**Comment by FDmZ** [comment]
No, that one didn't solve the problem, it showed "no results" right from the very beginning. And opening the from the browser didn't show any captcha
