### ISSUE TITLE
Jmana 'page list is empty'

### ISSUE THREAD

**Issue by meitantei1** [inorichi/tachiyomi-extensions#843]
Tachiyomi: 0.8.0
Jmana extension: 1.2.2
All bookmarked manga from source Jmana show as 'page list is empty'. No results show when browsing the catalogue within the app. I've done everything that has been suggested before for this type of issue(reinstall, clear cache, etc.), but none of it worked.
I think it might be because the url for the actual site changed from jmana2 to jmana4, but the url for the extension is still jmana2. But not completely sure.

**Comment by arkon** [comment]
I think this was fixed in 18407b47022fea3c173139408986901b40ba736e
