### ISSUE TITLE
Jmana 'hostname not verified' error

### ISSUE THREAD

**Issue by meitantei1** [inorichi/tachiyomi-extensions#854]
Tachiyomi version: 0.8.0
Jmana version: 1.2.3
When I click on a manga chapter, or try to browse jmana, the error shown on the attached image shows up, and fails to load any results.
![jmana error](https://user-images.githubusercontent.com/47966381/53543693-681f8d00-3b88-11e9-91d3-88bb38859cf4.jpg)

**Comment by CarlosEsco** [comment]
What version of Android are on

**Comment by meitantei1** [comment]
@CarlosEsco Android version 8.0.0

**Comment by DitFranXX** [comment]
They changed internal url. I will submit PR soon.

**Comment by DitFranXX** [comment]
You may need to clear chapter caches

**Comment by meitantei1** [comment]
I tried that, but it didn't help much

**Comment by DitFranXX** [comment]
@meitantei1 Sorry, I mean after update to 1.2.4.

**Comment by meitantei1** [comment]
Oh ok. Thanks
