### ISSUE TITLE
Page list is empty error on readcomiconline

### ISSUE THREAD

**Issue by lightningdrake99** [inorichi/tachiyomi-extensions#86]
Tachiyomi version: 0.6.1-1191
Readcomiconline extension version: 1.0.1

For some reason I am able to download chapters just fine, but not able to view them without downloading.

**Comment by lightningdrake99** [comment]
Readcomiconline.to's image host being down caused this error to appear.

**Comment by CarlosEsco** [comment]
Update to latest and open new issue if it still persists
