### ISSUE TITLE
MangaPlus duplicate search

### ISSUE THREAD

**Issue by metroid112** [inorichi/tachiyomi-extensions#866]
Tachiyomi r1463
Manga Plus 1.2.2
Xiaomi Mi A2 Android Pie

Searching on the Manga Plus app through the catalogue will bring duplicate entries. The 2nd seems to be in Spanish from what I've checked but doesn't bring the cover (EDIT: nor title nor author nor description) and displays this error if you try to open it.

![](https://i.imgur.com/I2Avkvz.jpg)

![](https://i.imgur.com/5RECPRE.png)

![](https://i.imgur.com/lfDW4Qe.png)

**Comment by xChickens** [comment]
https://mangaplus.shueisha.co.jp/manga_list/all
I assume that they can't do much about it if it shows up on the official website.
