### ISSUE TITLE
Kissmanga download stuck.

### ISSUE THREAD

**Issue by phanirithvij** [inorichi/tachiyomi-extensions#872]
**Tachiyomi Version:** r1462
**Kissmanga Ext Version:** 1.2.9

The issue is when I tried to download a chapter from Kiss manga,
Specifically this one [kissmanga-url](https://kissmanga.com/Manga/Solo-Leveling/Ch-009?id=480531).

It downloads the whole thing in the `Tachiyomi/downloads/Kissmanga (EN)/Solo Leveling Ch.009_tmp` directory.
It downloads all the images from the chapter,
It has 37 images.
The progress is stuck at either `21/37` or `36/37` and the notification is stuck at `19/37`.

So the `_tmp` directory has all 37 valid images.
And even after I renamed the directory to be what it should be after the download is done.
i.e.
`Tachiyomi/downloads/Kissmanga (EN)/Solo Leveling Ch.009_tmp`
to
`Tachiyomi/downloads/Kissmanga (EN)/Solo Leveling Ch.009` 

i.e. removing `_tmp` it doesn't recognize that it's downloaded.

**Comment by phanirithvij** [comment]
Hmmm, I think the 22nd image is invalid.
My bad.

**Comment by phanirithvij** [comment]
Say could you deal with these cases,
i.e. Missing images in the middle but still be able to download them with the missing images being a `placeholder` image?

**Comment by SyntaxError1871** [comment]
Can confirm I have the same issue as OP on 0.8.4. I get downloads that are eternally "stuck" in the Download queue though manually browsing the files are all there. Only the folders with the *_tmp extension or files with a *(1) suffix are affected by this "stuck chapter" bug. Deleting the folder and redownloading or renaming/deleting the _tmp or (1) suffixes also fixes the problem upon the next Download refresh. 

Seems like the application is creating duplicate files somehow and the script fails to recognize that the chapter has been successfully downloaded and stricken off of the Download Queue.

**Comment by SnakeDoc83** [comment]
@arkon This can be closed.
