### ISSUE TITLE
MangaDex catalog search returns no results

### ISSUE THREAD

**Issue by briggsi** [inorichi/tachiyomi-extensions#875]
Mangadex extension version 1.2.51, also broken before update
Tachiyomi version 0.8.0

Mangadex search fails to return results from any query, likely due to MangaDex's requirement to log-in to search as an anti-DDoS measure. Other sources (Kissmanga, etc) return results on the overall catalog search, but Mangadex remains empty.

Log-in on the browser within Tachiyomi does not seem to count for the catalog search.

**Comment by metroid112** [comment]
Already talked on #871
