### ISSUE TITLE
Readmanhua.net giving HTTP 404 error

### ISSUE THREAD

**Issue by jesterkong** [inorichi/tachiyomi-extensions#878]
I'm using Tachiyomi 0.8.0 version.
I don't know which extension readmanhua.net uses so these are the extensions I have:
Comicake                           1.2.2
Foolslide                            1.2.16
My Manga reader CMS     1.2.14
WPManga                          1.2.3
I have some manhua from readmanhua.net in my library but recently, I'm getting http 404 errors whenever I visit them or try to browse the catalog. I tried opening the site in the browser and it worked. I tried it on different phones and different networks but the results were same.
Please help.

**Comment by arkon** [comment]
It's from My Manga reader CMS. I think they've changed their site to some sort of Wordpress site, but I don't know enough about these aggregate extensions to really comment.

**Comment by AmineI** [comment]
I'm updating the MMRCMS extension and indeed, readmanhua.net switched to WPManga. I'm not familiar with the WPManga extension at all but I may look into adding it to the extension later.

**Comment by AmineI** [comment]
I already cleaned up MMRCMS of the offline/changed sites it in my local copy,as I'm working on #144, so I'll make a PR with MMRCMS updates first (with Readmanhua.net removed) before I even look at WPManga :) .

**Comment by SnakeDoc83** [comment]
This can be closed, it's in Madara now.
