### ISSUE TITLE
Mangago bug

### ISSUE THREAD

**Issue by lucasce** [inorichi/tachiyomi-extensions#88]
Some mangas on mangago can't be read. Some error appears: "attempt to invoke virtual method..."
![screenshot_20170807-003135](https://user-images.githubusercontent.com/17147581/29012366-037012da-7b09-11e7-9a52-1bd530132d72.png)

I use Tachiyomi (Dev) 0.6.1 r1194
Sorry if my English is bad

**Comment by maneleleina01** [comment]
Same here! Was it solved for you?

**Comment by lucasce** [comment]
No, not yet...

**Comment by ccrowles** [comment]
Issue still not solved... Almost all manga from Mangago for me had this issue
