### ISSUE TITLE
[ISSUE] [Japscan] Inverted columns on decrypted images

### ISSUE THREAD

**Issue by pokke456** [inorichi/tachiyomi-extensions#888]
I just saw the recent update of the extension. Thanks for it ! 😃
It really works well but I've just noticed that _some_ mangas (not all) have the last two column inverted

Like this (from the extension) :
Platinum END _https://i.imgur.com/LTuX1VT.jpg_
Twin Star Exorcist _https://i.imgur.com/SrLHEf1.jpg_
We Never Learn _https://i.imgur.com/9TFZWSH.jpg_

(All is fine on the website
https://www.japscan.to/lecture-en-ligne/platinum-end/39/
https://www.japscan.to/lecture-en-ligne/twin-star-exorcists/56/
https://www.japscan.to/lecture-en-ligne/we-never-learn/30/2.html)

Otherwise, the decoder works well on manga like Shingeki no Kyojin _https://i.imgur.com/Ek5ktHk.jpg_ or Eden's Zero _https://i.imgur.com/wvtqcwN.jpg_ (and maybe others)

I don't really see what can cause this 😐 Maybe the images themselves ?

**Comment by AmineI** [comment]
By "decoder" you probably mean the discrambler #881 ?

**Comment by pokke456** [comment]
> By "decoder" you probably mean the discrambler #881 ?

Yes ! :)

**Comment by Peuuuur-Noel** [comment]
> EDIT: Not sure if it may help, but it the problem occures on images with a width 1200

The 2 last columns of images with 12 columns (1200px) are in good position and don't need to be swapped vertically.
Images from Shingeki no Kyojin are on 14 columns (1410px) and all swapped vertically.
It seems to happen only for 12 columns images.

I add another observation related to https://github.com/inorichi/tachiyomi-extensions/pull/881.

The method used to detect scrambled images is not reliable. Scrambled images are not only available from uri containing `clel`, but with `lel` too.
Like for this chapter of Log Horizon: https://www.japscan.to/lecture-en-ligne/log-horizon-la-brigade-du-vent-de-l-ouest/56/ the first page is loaded from: https://c.japscan.to/lel/Log-Horizon-La-Brigade-Du-Vent-De-L-Ouest/56/001.jpg

The only thing that differ between scrambled and clean images is the JS script.
For scrambled image this JS file is called in < head>: <script src="/js/iYFbYi_UibMqYb.js"></script>
And for other this JS file is called: <script src="/js/iYFbYi.js"></script>

But I don't know if the name is just obfuscated like the file's content or change when the content of the file is updated to avoid browser cache issue.

**Comment by DitFranXX** [comment]
I opened PR(#891) that fixes inverted columns and discrambler which not placed on `lel` prefix.

Since I'm not Japscans user, I didn't notice that problems. (only looked up Shingeki no Kyojin)

**Comment by pokke456** [comment]
> Since I'm not Japscans user, I didn't notice that problems.

It's fine, thanks ! 😁
