### ISSUE TITLE
[ISSUE] [Japscan] "SyntaxError: parse error (line 1)"

### ISSUE THREAD

**Issue by pokke456** [inorichi/tachiyomi-extensions#897]
I think the last update https://github.com/inorichi/tachiyomi-extensions/pull/891 created another problem.
When I try to open a chapter, I have "_SyntaxError: parse error (line 1)_".
Also, the list of chapters isn't up to date (I compare with the site). I tried to refresh, but nothing.

**Comment by CarlosEsco** [comment]
Same issue as kiss and read
