### ISSUE TITLE
Crashing after some 3~4 seconds if Manga Rock is installed

### ISSUE THREAD

**Issue by Konasaito** [inorichi/tachiyomi-extensions#899]
App Version: **0.8.0**
Source: **Manga Rock version 1.0.5**
Platform: using the latest version of **Bluestacks (4.50.5.1003)** and **Windows 10**
Android Version:         **7.1.2** (update just released)
Android SDK Version: **25**

Issue: If the extension is installed the app crashes a few seconds after opening. Already tried many extensions but only with Manga Rock Installed the app will crash.

Troubleshooting:
restarted pc
restarted Bluestacks
cleared cache and cookies in app settings
cleared app cache on phone
reinstalled app and extension
checked if I had adblocks, and I do not.
tried installing every other version of the Manga Rock extension there was

**Comment by arkon** [comment]
What version of Android is Bluestacks using?

**Comment by Konasaito** [comment]
Android Version:         **7.1.1**
Android SDK Version: **25**

**Comment by Konasaito** [comment]
I did some testing and found out that, even with Manga Rock installed, it only crashes after loading some specific covers. 

Once it loads that cover it will always crash after 5 seconds, even if you change categories. 

If I open the app and it starts in a category that does not have "trigger"covers appearing it won't crash, but if you scroll down and that category has a "trigger" cover, it will crash anyway after 5 seconds in case you saw the cover.

List mode or grid mode both crash.

I Still can't understand the logic behind which covers are triggers

**Comment by neufel** [comment]
That's one coincidence, as this happened to me today with a different setup.
App Version: 0.8.0
Source: ReadComicOnline version 1.2.5
Platform: Samsung Tab A 2016
Android Version: 8.1.0

Just as you described, the app chrases when it loads one particular page of my library only if:
1. the source is installed
2. the tablet has access to wi-fi. (If I turn on wi-fi while using the app, it closes a few seconds afterwards)

Readcomiconline is also (no pun intended) offline, and the crash started at the same moment.
I thought the app might be trying to find a missing cover (I can see two black covers) and crashes when it fails.

I have removed those two series from my library, and the problem stopped.
I'll add them back when the source is up again.

Hope my experience helps in some way !

**Comment by Konasaito** [comment]
I found out after some messing around that indeed, some series are doing that. 

But funny enough, they only make the app crash if they load in a certain order

**Comment by Konasaito** [comment]
So, in my case if I try to read comics from the Peak category using Sort by Source with the arrow pointing down, it won't crash. But using Sort by Source with the arrow up and I somehow load the trigger series, it WILL crash after 5 seconds.

![BlueStacks_ScreenShot](https://user-images.githubusercontent.com/8902913/54385569-aed7b180-4675-11e9-8307-c496b7a788b3.jpg)

**Comment by neufel** [comment]
Damn, I shouldn't have deleted the problematic series, now I can't try those different loading order.

**Comment by Konasaito** [comment]
I guess wait for a fix and meanwhile try to discover which Sortings should I use for my other categories

**Comment by arkon** [comment]
How much memory does the emulator have?

**Comment by Konasaito** [comment]
The emulator has 3gb of RAM and I allocated 4 cores of my I5 8600k to it

**Comment by MerradOklom** [comment]
Have you tried with the latest dev release? https://tachiyomi.kanade.eu/tachiyomi-r1465.apk
Tachiyomi crashed on my device while loading the manga covers from my library, but it's already fixed with that version.

**Comment by Konasaito** [comment]
I didn't, but since it's a whole new kind of app I would have to back up everything, and I dunno why but I always get at least a hundred errors afters restoring and lose some hundred comics :(' 

I'm kinda hoping there would be a fix for this one ;c

**Comment by inorichi** [comment]
This has been fixed on the app. There will be an update tomorrow.

**Comment by Konasaito** [comment]
Thanks, @inorichi :)
