### ISSUE TITLE
ITAscan

### ISSUE THREAD

**Issue by dotwizzy** [inorichi/tachiyomi-extensions#900]
(CATALOGUE) SOURCE REQUESTS:

Manga list direct link:
https://itascan.info/directory/

Home of website:
https://itascan.info

**Comment by dotwizzy** [comment]
Hello, I'm an Italian guy that likes manga a lot.
If something is wrong with my format pls reply there so I can edit. have a nice day!

**Comment by as280093** [comment]
issue already present at #753
