### ISSUE TITLE
Kissmanga syntaxerror

### ISSUE THREAD

**Issue by pseudophotographer** [inorichi/tachiyomi-extensions#901]
When trying to open any manga or even the kissmanga extension it appears the error "SyntaxError: parse error (line1)" and it seems to happen in other extensions as well. I don't know if the issue has been resolved before.

**Comment by mrcn0** [comment]
Same as me, version 0.8.0.

**Comment by CarlosEsco** [comment]
Issue is already opened on the extension repository

**Comment by rezwannn** [comment]
so is it still not working? cus ive still hv syntax error still

**Comment by weaka21** [comment]
Up until now is still syntax error

**Comment by CarlosEsco** [comment]
@weaka21 update your version to latest dev or.0.8.1
