### ISSUE TITLE
kissmanga syntax error

### ISSUE THREAD

**Issue by rezwannn** [inorichi/tachiyomi-extensions#903]
need help

**Comment by hakapoid** [comment]
same here. its that weird parse line error thing which noone seems to know how to solve :(

**Comment by rezwannn** [comment]
ikrrr. it just came out of nowhere :(

**Comment by hakapoid** [comment]
hope an update is released soon!

**Comment by arkon** [comment]
#894

Please do not spam, GitHub is not a forum.
