### ISSUE TITLE
KissManga syntaxerror: parse error(line 1)

### ISSUE THREAD

**Issue by etjs93** [inorichi/tachiyomi-extensions#904]
Version 0.8.0

KissManga syntaxerror: parse error(line 1)

As the title says; I'm having issues with assessing sources related to KissManga. I can't load or search on KissManga as well on the app.

**Comment by CarlosEsco** [comment]
Issue is already open please verify before opening issues in future

**Comment by Reiriin** [comment]
This is the lastest one... So it's still not resolve... :(

**Comment by CarlosEsco** [comment]
#894
