### ISSUE TITLE
[Source Request][ENGLISH] https://getcomics.info/

### ISSUE THREAD

**Issue by anhonorableleech** [inorichi/tachiyomi-extensions#906]
Requesting source to be added https://getcomics.info/

**Comment by Cassius19985** [comment]
But you know it is a site from which you download whole comics in .CBR or .CBZ formats not view them, right?

**Comment by as280093** [comment]
Here the icons
[getcomics.info.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614419/getcomics.info.zip)

**Comment by SnakeDoc83** [comment]
@anhonorableleech 

You could probably just use Read Comic Online in MMRCMS.  From what I see getcomics links to RCO for their online reader.  Otherwise, download comics and use Tachi's local manga.

**Comment by anhonorableleech** [comment]
@SnakeDoc83 

Thank you. I was using ReadComicOnline, but could not find certain titles. I now realize that there is two different databases (.to vs .ru). I have added MMRCMS, and the titles I was looking for are listed. Thank you again. Closing this request.
