### ISSUE TITLE
None of the extensions are working.

### ISSUE THREAD

**Issue by Hero9868** [inorichi/tachiyomi-extensions#908]
I am using Tachiyomi Ver. 0.8.0
My extension Versions are : 
Mangadex : 1.2.53
Kissmanga : 1.2.9
Manganelo : 1.2.3

These are all the extensions I tried and they all failed. (except for some hentai sites but lets not talk about that.)
It shows "SyntaxError: parse error (line 1)" and "attempt to invoke virtual method 'java.lang....." errors to me. I have updated all the extensions to the latest versions as well.
Please help me by fixing this problem.

**Comment by CarlosEsco** [comment]
Mangadex has ddos issues. Search is also down for guests

**Comment by CarlosEsco** [comment]
Kissmanga there is an open issue already

**Comment by CarlosEsco** [comment]
Actually anything with cloudflare is getting parse error. New version tomorrow
