### ISSUE TITLE
Source not working

### ISSUE THREAD

**Issue by SpaceMonkey87** [inorichi/tachiyomi-extensions#909]
(CATALOGUE) SOURCE REQUESTS:
  One source per issue, create more issues if you have more websites
  Check for duplicates, use search (in issues, not the global one)
  Put the name of the site as Title, replace this text with clickable link to the site
BUGS:
  Provide tachiyomi version as well as version of source the report is about

So I just downloaded the 0.7.4 version of the application as per suggestion of my friend and I downloaded a couple of extension and tried to access some of them but kept getting errors of http 400 or error at syntax line 1 and I'm stuck without being able to view any manga. Thank you :)

**Comment by arkon** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/894

Also, old versions aren't supported.
