### ISSUE TITLE
Request: Add Italian Source

### ISSUE THREAD

**Issue by blackmanga** [inorichi/tachiyomi-extensions#91]
Hello,
Please add source from https://hastareader.com/slide/ and http://www.hentaifantasy.it/
It is the best Italian sources.

Thanks

**Comment by ddmgy** [comment]
Hi there! I've made an extension for hastareader.com, after seeing that it is structured very similarly to a number of sites for which I've already made extensions. 

I've uploaded an APK [here](https://www.dropbox.com/s/ijknmug040cridz/tachiyomi-it.hastareader-v1.0.1-debug.apk?dl=0) if you would like to test it, or you can check out my personal branch [here](https://github.com/ddmgy/tachiyomi-extensions/tree/add-hastareader-extension) if you would prefer to build it yourself.

I can take a look at making an extension for hentaifantasy, as well, and let you know if I come up with anything.

**Comment by blackmanga** [comment]
Thanks, apk does't install, is my problem or apk corrupt?

**Comment by ddmgy** [comment]
Hmm, the APK installs just fine for me. Are you able to download it? What does your device say when you try to install it?

**Comment by sharedkestrel** [comment]
The apk installs and works just fine for me.

**Comment by blackmanga** [comment]
I solved, the download was corrupt. For now I did not find any problems. Thank you very much!

**Comment by ddmgy** [comment]
Great to hear!

I've got a working version for hentaifantasy, as well. Once I get search sorted, I'll put up an APK if you'd like to test it, and then submit a pull request.

Thanks for trying it out!

**Comment by ddmgy** [comment]
Alright, so [here](https://www.dropbox.com/s/d0o8h09srw3ajcf/tachiyomi-it.hentaifantasy-v1.0.1-debug.apk?dl=1) is an APK for hentaifantasy.it. You can see lists of most popular and latest updated manga, and you can search by manga title. It's in a working state, so I feel comfortable releasing it to be tested.

However, there are three other methods of searching on hentaifantasy.it:
1. by tag,
2. by author name,
3. by parody (manga series name).

All three of these use a different path to search, and sometimes (if there is only a single tag for which to search, for instance), the search will redirect to yet another path that is specific to that tag/author/parody. In addition, only some of these paths use paging, and those that don't, refuse to show *any* results if a page number exists in the URL. I'm still trying to figure out a way to catch all of these without it turning into a screaming mess. I'd like to have the search options in Tachiyomi be as close as possible to those on hentaifantasy.it, but it will take a little more work and time.

For now, if someone tests it and finds it to be working well enough, I'll open a PR for it, and additional search options can be pushed in whenever I figure them out.

**Comment by blackmanga** [comment]
the hasta reader extension has stopped working for a few days

**Comment by ddmgy** [comment]
I will take a look in a few hours  to see what has changed.

**Comment by ddmgy** [comment]
Fixed in #112. Loading  images was being redirected, so I added a 'Referer' header.

Next time, please open a new issue, rather than commenting on a closed one. I usually unsubscribe from closed issues, so I might not have seen this.

**Comment by chrono-kun** [comment]
I'm an admin of the site hastareader.com, can you remove our reader from the app? Furthemore,  blackmanga approached us taking merit for the app and asking if we were interested and we already told him no, but to no avail.

**Comment by ddmgy** [comment]
I'll open a pull request to remove the extension.
