### ISSUE TITLE
[Source Request] [English] https://readcomicsonline.me/

### ISSUE THREAD

**Issue by itsrumsey** [inorichi/tachiyomi-extensions#911]
Read Comics Online 
https://readcomicsonline.me/

not to be confused with ReadComicOnline (https://readcomiconline.to/) for which an extension already exists
or for ReadComicsOnline (https://readcomicsonline.ru/) which is supported through MMRCMS

**Comment by CarlosEsco** [comment]
Man these unoriginal naming people

**Comment by as280093** [comment]
hey @CarlosEsco  the source request is same of #33 if you try that source it will redirect you to this new url http://readcomicbooksonline.net --> https://readcomicsonline.me/   so its not new source request just domain change

**Comment by CarlosEsco** [comment]
Well it's new in sense other one was closed

**Comment by as280093** [comment]
it was closed as due to  arkon mentioning 
_Already in MMRCMS._
but i checked MMRCMS and found it countained http://readcomicsonline.ru not http://readcomicbooksonline.net so you show open #33 again and close this one

**Comment by CarlosEsco** [comment]
I will leave this one opened

**Comment by Cassius19985** [comment]
It apparently has changed again, new site adress is : https://comicpunch.net

**Comment by as280093** [comment]
Here the icons
[readcomicsonline.me.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614418/readcomicsonline.me.zip)
