### ISSUE TITLE
[Source Request] [Spanish] Ikuhentai

### ISSUE THREAD

**Issue by Credits125** [inorichi/tachiyomi-extensions#925]
URL:

[Ikuhentai](https://ikuhentai.net)

**Comment by as280093** [comment]
@karnadii Hey its UI is same as ManhwaHentai and ManhwaHand so it could be easy for you to make this extension

**Comment by karnadii** [comment]
Give me the icon, and i'll do it. . .

**Comment by as280093** [comment]
@karnadii Here is the res folder 
[res.zip](https://github.com/inorichi/tachiyomi-extensions/files/2977541/res.zip)
or you can find here https://github.com/as280093/TIcons/tree/master/Requested%20Extensions%20Icons/Ikuhentai/
