### ISSUE TITLE
Mangadex 403 implementing a captcha

### ISSUE THREAD

**Issue by uenoshita** [inorichi/tachiyomi-extensions#930]
Version: r1466
Extension version: Mangadex All 1.2.53
Looks like Mangadex is implementing a captcha as I was asked to answer one when trying to view the site. It might be temporary since the site probably has a heavy load right now but it's still bother some when you can't access the site via tachiyomi.

**Comment by CarlosEsco** [comment]
Nothing we can do fill the captcha then go back into tachiyomi

**Comment by bestepp78** [comment]
Ok thanks

**Comment by uenoshita** [comment]
The captcha only shows up in the browser. Tachiyomi only shows 403. I'd be ok with filling up the captcha though.

**Comment by CarlosEsco** [comment]
You should be able to open the browser fill the captcha then go back to tachiyomi.

**Comment by uenoshita** [comment]
Is there an option/ different version or something? It only shows HTTP error 403 retry everytime even when pressing retry. I even tried opening the default browser, firefox and chrome to solve the captcha but tachiyomi just shows the same error.

**Comment by CarlosEsco** [comment]
Will leave open but you are right captcha in browser doesn't work

**Comment by thousandsofthem** [comment]
Probably app can open internal webview with unmodified mangadex page, allow to solve captcha, login if needed etc, then close it and keep using stored cookies and stuff

**Comment by Solipso** [comment]
NerdNumber9 implemented that feature for Tsumino in his fork. Maybe you could do the same here.

**Comment by starg09** [comment]
> Seems the captcha was removed and now the site is reachable through Tachiyomi, can someone else confirm?

Captcha comes and goes, cloudflare protection is still a thing that affects the app though.

Latest/Browse's main page works, searching with "id:<mangadex_id>" works, any other search throws either no results or a 403.

Some method of solving the CF limitation would still be appreciated, even for when site isn't at maximum protection level.

**Comment by CarlosEsco** [comment]
@starg09  search is returning 503 because they disabled search for guests.  has nothing to do with cloudflare

**Comment by thousandsofthem** [comment]
> search is returning 503 because they disabled search for guests. has nothing to do with cloudflare
 
ability to solve captcha and log in will solve both so kinda related, not directly though

**Comment by CarlosEsco** [comment]
@thousandsofthem  yes but saying search is broken cause of 403 and cloudflare isnt correct
