### ISSUE TITLE
Mangago and Kissmanga not working

### ISSUE THREAD

**Issue by yasnil03** [inorichi/tachiyomi-extensions#933]
Like what my title say. Mangago and kissmanga is not working in my phone. Everytime I open it "Syntaxerro: parse error (line 1). Is it just my phone or something?

I already try #894 but still nothing happened.

**Comment by xChickens** [comment]
What version of the app are you using?

**Comment by yasnil03** [comment]
Latest

**Comment by xChickens** [comment]
Dev, stable? A version number would also be nice for checking if you actually do have latest.

**Comment by yasnil03** [comment]
Is Tachiyomi v0.8.0 is not the latest?

**Comment by xChickens** [comment]
Uh, 0.8.1 fixed the parseerror bug lol.

**Comment by yasnil03** [comment]
Where can i download that? All i search the outcome is 0.8.0

**Comment by einstein95** [comment]
https://github.com/inorichi/tachiyomi/releases/download/v0.8.1/tachiyomi-v0.8.1.apk

**Comment by yasnil03** [comment]
Ok thank. I'll try and download it☺

**Comment by yasnil03** [comment]
Hey last one hehe. I can't open a manga under mangago or download. If i open it always appear "Error: Malformed UTF-8 data" can you help me?

**Comment by xChickens** [comment]
MangaGo extension doesn't really work.
You should search before posting issues.
#601 #664 #825

**Comment by yasnil03** [comment]
Yeah i know its not totally working. But you can open the extension of mangagi but can't read
