### ISSUE TITLE
Update to Kissmanga extension causes any interaction with a kissmanga title to close the app

### ISSUE THREAD

**Issue by narfanar** [inorichi/tachiyomi-extensions#937]
Tachiyomi version: 0.8

Edited to add: (F-Droid doesn't have 0.8.1 yet)

Kissmanga extension version: N/A

Android: 4.4

I recently updated the kissmanga extension because the titles weren't getting any updates. The app would now very consistently close (not crash, I think; there's no "stopped working" message of any kind) when trying to open a title hosted on kissmanga or trying to migrate title from it.

Removing the extension doesn't fix the issue. It started exactly after updating it. I installed the update last Monday.

**Comment by bbtora** [comment]
Update app and let us know if the problem occurs.

**Comment by narfanar** [comment]
@bbtora , 0.8.1 isn't on active F-Droid yet :/

**Comment by CarlosEsco** [comment]
Fdroid isn't supported

**Comment by narfanar** [comment]
That... That's quite unfortunate. Updating is a pain otherwise. And settings don't carry over through an uninstall/reinstall (or backup).

I just did so. And lost all the manga that were on a non-functioning host (backup-restore doesn't add them when they respond with a 503), so... I can't even report if the titles with the (bizarre) issue are working or that I can migrate their source; because they're no longer in my library.

**Comment by CarlosEsco** [comment]
Backup adds them fine even if website is down
