### ISSUE TITLE
Kissmanga SyntaxError: parse error (line 1)

### ISSUE THREAD

**Issue by samjotong** [inorichi/tachiyomi-extensions#939]
Tachiyomi dev version: Version 0.7.4-1438
Kissmanga version: 1.2.9

Error appears when trying to open catalouge. Also, bookmarked manga from kissmanga in my library doesn't update.

**Comment by DitFranXX** [comment]
Update to 0.8.1 or Latest dev build.

**Comment by samjotong** [comment]
I'm using J2ghz's FDroid Repo in Tachiyomi but the last time the repository was able to update was on November 4, 2018, 12:49 AM. I can't seem to update it no matter how many times I try. On my F-droid app it says the dev version I am using is the latest and the latest on the ordinary tachiyomi is 0.8.0.

Any suggestions?

**Comment by DitFranXX** [comment]
F-Droid is not supported now(J2ghz's repo too). Please download on github. https://github.com/inorichi/tachiyomi/releases

(May related to inorichi/tachiyomi#1894)

**Comment by samjotong** [comment]
I have a question.

From the link that you sent there are 3 items that can be downloaded

tachiyomi-v0.8.1.apk
Source code (zip)
Source code (tar.gz)

What do I do with the source codes? Thanks!

**Comment by bbtora** [comment]
Just download and install apk file.

**Comment by samjotong** [comment]
Alright thanks everybody. :)
