### ISSUE TITLE
[Multiple] hitomi.la

### ISSUE THREAD

**Issue by HunterKurza** [inorichi/tachiyomi-extensions#94]

**Comment by AnimeAnimeAnimeAnimeAnime** [comment]
There is already sad panda extensions 
https://github.com/NerdNumber9/TachiyomiEH

**Comment by HunterKurza** [comment]
Any chance of having those sources merged into the main app?

**Comment by j2ghz** [comment]
If the author NerdNumber9 wants, they can add it the same way all the other extensions were added.

**Comment by NerdNumber9** [comment]
@j2ghz @HunterKurza Unfortunately, I doubt this will happen in the near future.

The E-Hentai and ExHentai sources are heavily configurable and thus require their own options screen/UI. ExHentai doesn't work at all without login (and the ExHentai login is a huge mess involving captchas, cookies, sessions and cache bypassing) which cannot be implemented currently without a custom UI API.

My fork of Tachiyomi also supports offline tag searching and batch URL adding which are useful for doujinshi/hentai sources but useless for regular manga.

My fork does have an app lock feature that I would be willing to port if @inorichi agrees but I think the rest of the stuff is too specialized to merge in for now.

If Tachiyomi does get a custom UI API however, I will probably rewrite my fork as an extension.

**Note:** It looks like someone's already ported the E-Hentai and nhentai sources as extensions over here: https://github.com/inorichi/tachiyomi-extensions/tree/master/src/all

**Comment by as280093** [comment]
Here the Icons
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3615376/ic_launcher.6.zip)
