### ISSUE TITLE
Japscan HTTP error 403 with new Tachiyomi version. 

### ISSUE THREAD

**Issue by GintokiXSakata** [inorichi/tachiyomi-extensions#941]
Hi, 

Even with the latest version of Tachiyomi (version 0.8.1), this source is still isn't working and it's the only French source that there is on the app (and that at least was working properly until now). Yes, I know there's the Mangakawaii French source but there are only few manga that are working.

Anyway, can anyone do something about this? It's been like this since almost a week now. Thanks in advance.

**Comment by bbtora** [comment]
#931
