### ISSUE TITLE
KissManga: HTTP error 503

### ISSUE THREAD

**Issue by Dial-upMan** [inorichi/tachiyomi-extensions#952]
**Version: 0.8.1 (Stable)
KissAnime Extension Version: 1.2.9**

As of two days ago I received the 503 error for KissManga after the site extension being fixed with the newest update for the stable build. For a small portion of time it worked on only data instead of my home network. I now cannot read/download anything in my library or check the catalogue. I have tried restarting my phone, re-installing the update/extension and cleared the chapter cache/cookies to no avail. No clue what else I could try, any and all help is extremely appreciated.

**Comment by terrym0** [comment]
Yeah I have same issue. Thought of just going through the process of migrating all to mangadex but cant because they still have search blocked from there ddos attack.  And now for the last few hours mangadex is showing error 403.  Hopefully everything gets fixed soon.

**Comment by DitFranXX** [comment]
Related to (or duplicate) #951

**Comment by CarlosEsco** [comment]
combined
