### ISSUE TITLE
[English] fullcomic.pro

### ISSUE THREAD

**Issue by carloleftthegroup** [inorichi/tachiyomi-extensions#956]
I would like to request http://fullcomic.pro/ as an extension it has high quality images and due to unstable readcomiconline extension maybe we could add another comic.

Thank you.

**Comment by Yong-L** [comment]
The source is returning a 403 forbidden error

**Comment by SnakeDoc83** [comment]
Nearly 3 months later and still gives a 403 error.  Site is probably be dead, might as well close this--it can always be requested again if it does come back.
