### ISSUE TITLE
E-Hentai - No results found

### ISSUE THREAD

**Issue by kaos46** [inorichi/tachiyomi-extensions#960]
Hello, since a few days i've got the response "No results found" from the E-Hentai Catalog.
I've tried the F-Droid Version of Tachiyomi 0.8.0 and the Dev-Version r1477. The Version of the E-Hentai Extension is 1.2.2

**Comment by ilwaz** [comment]
See related bug in TachiyomiEH: https://github.com/NerdNumber9/TachiyomiEH/issues/56

**Comment by arkon** [comment]
Can probably pull in some changes from https://github.com/ilwaz/TachiyomiEH

**Comment by ilwaz** [comment]
I would wait for this PR to land @arkon: https://github.com/ilwaz/TachiyomiEH/pull/5

**Comment by justinkruit** [comment]
When will the extension be updated with the code from that repo? As it looks like it's all fixed there.
