### ISSUE TITLE
no covers showing

### ISSUE THREAD

**Issue by fatimagrace015** [inorichi/tachiyomi-extensions#962]
idk if its just me but as the title said, no covers. all sources i use (except for webtoon), mangarock, mangahasu, mangago, myreadingmanga. i kept refreshing, clearing data base and all but none works.

tachiyomi r1474
sources said above are on their latest ver.

**Comment by joseph619** [comment]
Use the regular Tachiyomi

**Comment by fatimagrace015** [comment]
i used that too before installing tachiyomi r1474, mangahasu and some
sources doesnt work there

**Comment by fatimagrace015** [comment]
update, tachiyomi ver 0.8.2 only 47 covers showing out of 145 mangas in my library. i tried refreshing metadate a couple of times but doesnt work.

**Comment by CarlosEsco** [comment]
Have you tried clicking into the manga and seeing if it loads

**Comment by fatimagrace015** [comment]
yes, many times but doesnt work either.

**Comment by CarlosEsco** [comment]
What sources in particular have the issue.  I know you listed all the sources you use. but for example if all the no covers are mangago they arent going to load cause its broken

**Comment by fatimagrace015** [comment]
most of the uncovered ones are in myreadingmanga, few in mangahasu and
mangarock.

**Comment by fatimagrace015** [comment]
only mangas in myreadingmanga– all sources said above have covers after the update.

**Comment by CarlosEsco** [comment]
you said you keep clearing database, have you tried cookies and cache?  then went into the manga?

**Comment by fatimagrace015** [comment]
yes yes, tried them too, didnt work

**Comment by CarlosEsco** [comment]
extension is up to date?

**Comment by fatimagrace015** [comment]
yes, mrm ver 1.2.20

**Comment by quinnjet** [comment]
The missing covers from MRM source are errors on their end. MRM staff is going through and fixing the missing covers one at a time, but it'll probably take quite a bit. For now, I'd advise setting the cover images yourself.
