### ISSUE TITLE
Mangakakalot Not updating in Library updates

### ISSUE THREAD

**Issue by Darkvramp** [inorichi/tachiyomi-extensions#965]
Tachiyomi version = 0.8.1
Mangakakalot version = 1.2.4
The problem I have found is that the manga update in the library, I can go into my library and find them individually with brand new chapters, but the feature itself, library updates, does not track this change. Its less of a major issue and more of a quality of life change, but since I have spread my library around, to prevent one source going down and taking my library down with it, I find it is a problem.
However, it's still a bug and requires a report. 
Other sources/ catalogs still update normally for me on my version.

**Comment by arkon** [comment]
> should be as simple as adding the relative date parsing to https://github.com/inorichi/tachiyomi-extensions/blob/master/src/en/mangakakalot/src/eu/kanade/tachiyomi/extension/en/mangakakalot/Mangakakalot.kt#L93
> Example row is 
```
<div class="row">
<span><a href="https://mangakakalot.com/chapter/zx918606/chapter_5.5" title="Harlem Beat Chapter 5.5: Super Ultra Basket Man, Syu! Part 1">Chapter 5.5: Super Ultra Basket Man, Syu! Part 1</a></span>
<span>988</span>
<span>3 day ago </span>
</div>
```

**Comment by Darkvramp** [comment]
so what would I have to do to get this to work on my device, would it involve actually going into the code because I'm an absolute beginner at coding

**Comment by arkon** [comment]
Extension update, if someone gets around to it.
