### ISSUE TITLE
[Portuguese] Golden mangas

### ISSUE THREAD

**Issue by nicker7** [inorichi/tachiyomi-extensions#971]
[Golden mangas
](http://goldenmangas.online/)

**Comment by as280093** [comment]
Here the icons
[Golden mangas.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614416/Golden.mangas.zip)

**Comment by alessandrojean** [comment]
Is it really necessary? Because we already have extensions for the most popular brazilian websites, and I am almost sure that it don't have any exclusive content that the other websites doesn't already have.

**Comment by nicker7** [comment]
If I'm not mistaken, loading the content of this site is faster, this is the differential of it in my view.

**Comment by alessandrojean** [comment]
Did you know the relationship between this site and the others that use the same layout, as I mentioned above? Or which one is the original?

If I know this, I can create an extension with all the sites that use this system.

**Comment by nicker7** [comment]
About the differential, according to my friend, he still keeps in his catalog projects with rights acquired by the country's publishers.  which is very good I believe.  but if you're doing a lot of work, you can cancel the request.

**Comment by alessandrojean** [comment]
I mentioned the mirrors, but I think they are closed or they are not showing in Google. In the question of licensed manga, all brazilian extensions doesn't respect that and keeps the licensed mangas in their catalogs, except MangasProject because of an out-of-court notification by JBC at the time they were selling VIP plans.

I will create the extension.

**Comment by jotasete** [comment]
In addition to all the reasons cited this becomes more website for Brazilians.  It is not uncommon for one site or another to be blocked and only two of them update regularly (two that post content from other scans)

**Comment by jotasete** [comment]
It is not a competition but there are many with the same English language content for example

**Comment by jotasete** [comment]
And yet on the mangaslivre (which must belong to the same team do mangasproject) is more complete than him. For the reason already mentioned as well.

**Comment by alessandrojean** [comment]
I just submitted an PR with the extension, it should be added soon.
