### ISSUE TITLE
Homestuck?

### ISSUE THREAD

**Issue by wayyermany** [inorichi/tachiyomi-extensions#975]
Im not sure if this could work but it'd be great. The text and vids might be tough tbh, but i'd love to see it.

**Comment by as280093** [comment]
@wayyermany Can you explain more,
@CarlosEsco  if its about chat and videos you can close  it

**Comment by einstein95** [comment]
@as280093 Homestuck is a webcomic, although some parts are done via text and/or videos.

**Comment by Jendrej** [comment]
https://www.homestuck.com/story/1
It uses text in almost all parts as far as I can see, so… It probably should be closed.
