### ISSUE TITLE
Jmana trust anchor not found

### ISSUE THREAD

**Issue by meitantei1** [inorichi/tachiyomi-extensions#976]
Tachiyomi version: 0.8.2
Jmana version: 1.2.5
When I try to load the Jmana catalogue, or click on a chapter of a saved manga, the image attached shows up.
![20190328_093707](https://user-images.githubusercontent.com/47966381/55111177-ad5ebc80-513e-11e9-9415-da7808e54f7c.jpg)

**Comment by DitFranXX** [comment]
Fixed on #987 
(I forgot to add this issue on PR)
