### ISSUE TITLE
Mangarock search filter doesn't work

### ISSUE THREAD

**Issue by karnadii** [inorichi/tachiyomi-extensions#984]
Java.lang.string cannot be converted

**Comment by karnadii** [comment]
Downgrade to v1.0.5 fix the problem. . .

**Comment by arkon** [comment]
Due to the GSON changes in https://github.com/inorichi/tachiyomi-extensions/pull/977, but have yet to determine exactly what.

I originally avoided using GSON for this since it was overkill and added bloat to the extension...
