### ISSUE TITLE
[English] mangarock.com

### ISSUE THREAD

**Issue by ChaotikZ** [inorichi/tachiyomi-extensions#99]
https://mangarock.com/

**Comment by arkon** [comment]
I'll work on this.

**Comment by arkon** [comment]
I've gotten most of it to work (i.e. browsing, searching), but the hardest part is getting the actual images, which have to be decoded. Would it make sense to add a decoder to the main app?

Check out [this fiddle](https://jsfiddle.net/6h2sLcs4/15/) for an example.

**Comment by CarlosEsco** [comment]
Keep the decoder in the extension for now.

**Comment by arkon** [comment]
Makes sense, since it's tied to the source.

Another issue: even after decoding it, I end up with a data URI (e.g. `data:image/webp;base64,...`. I don't think the app supports that?

**Comment by Th3-822** [comment]
The base64 encoding it's done after decrypting the image, so it's nothing to be worried.
The image is sended to the b64 encoder after regenerating it's headers (first 15 bytes), the crypt it's a simple XOR crypt with 101 as the key

**Comment by wopian** [comment]
@arkon Skia should support webp

**Comment by arkon** [comment]
@wopian Thanks, you're right. Both Rapid and Skia can show [a regular absolute URL](https://www.gstatic.com/webp/gallery3/1_webp_ll.webp) fine, but a data URI doesn't seem to. I'm not really sure if it's an issue with the decoder or possibly [Glide's DataUrlLoader](https://github.com/bumptech/glide/blob/17c1c3d5781e953379904a60bae08524632e5053/library/src/main/java/com/bumptech/glide/load/model/DataUrlLoader.java)... I don't see anything helpful in the logs.

Example data URI:
```
data:image/webp;base64,UklGRi4AAABXRUJQVlA4TCEAAAAvAUAAEB8wAiMwAgSSNtse/cXjxyCCmrYNWPwmHRH9jwMA
```

**Comment by wopian** [comment]
You could potentially create a bitmap (converted to jpeg/png?) from the base64 data and give the image decoders that instead

**Comment by arkon** [comment]
I'll give that a shot. Currently having some issues because Kotlin doesn't natively support unsigned bytes.

Progress here: https://github.com/arkon/tachiyomi/commit/69752c64459bb7f66f036b3ccac8865542301cae

**Comment by arkon** [comment]
Update: I'm getting `Bitmap`s of the pages now, just need to figure out how to display that.

**Comment by arkon** [comment]
Any opinions/suggestions?

**Comment by paronos** [comment]
I think you first could add in the main application a content provider (similar to [ZipContentProvider](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/util/ZipContentProvider.kt)) that encodes the file content directly in the uri, and then use it in the extension (see [LocalSource](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt) as an example).

**Comment by CarlosEsco** [comment]
@paronos that won't work. Requires main app update, and extensions Lib  to be updated. Which means it probably won't be merged in.

**Comment by null-dev** [comment]
Add a network interceptor the the source's `OkHttpClient`. Then you can intercept image requests and decode them manually before passing the decoded data to the app.

**Comment by arkon** [comment]
I could probably save the images as pass the `Uri`s for them like a `LocalSource`, but there doesn't really seem like a clean way of doing that within the constraints of a class that extends `HttpSource`.

Not entirely sure what @null-dev is suggesting, I'm not having any issues with the request + decoding part, but more so how to pass the decoded data on after that.

**Comment by null-dev** [comment]
@arkon 
Alright, here is an example:
```
class WhateverSource : HttpSource {
    override val client = super.client.newBuilder().addInterceptor(new LoggingInterceptor()).build()
}
```

You can find more info here: https://github.com/square/okhttp/wiki/Interceptors

**Comment by null-dev** [comment]
@arkon 
Alright, here is an example:
```
class WhateverSource : HttpSource {
    override val client = super.client.newBuilder().addInterceptor({ chain ->
	val url = chain.request().url().toString()
	val response = chain.proceed(chain.request())
	if(!url.endsWith(".mri")) return response
	
	val decoded: Array<Byte> = decodeImage(response.body().string())
	val mediaType = MediaType.parse("image/webp")
	val rb = ResponseBody.create(mediaType, decoded)
	return response.newBuilder().body(rb).build()
    }).build()
    
    // ... Your other code for the source here
}
```

Basically, what we do is we intercept all network requests for URLs that end in ".mri". Then we decode the image from the result of the network request and replace the data the would have been passed on to Tachiyomi with our new decoded data.

You can find more info here: https://github.com/square/okhttp/wiki/Interceptors

**Comment by arkon** [comment]
@null-dev Nice, that works perfectly for this!

**Comment by CarlosEsco** [comment]
#275
